SELECT FTC_FOLIO_BITACORA AS FTC_FOLIO, FCN_ID_SUBPROCESO,
       SUM( ACEPTADOS) AS ACEPTADOS, 
       SUM(RECHAZADOS) AS RECHAZADOS, 
       SUM(ACEPTADOS)+SUM(RECHAZADOS) AS TOTAL, 
       SUM(MONTO_ACEPTADO)+SUM(MONTO_RECHAZADO) AS TOTALMONTO,
       SUM(MONTO_ACEPTADO) AS MONTO_ACEPTADO,
       SUM(MONTO_RECHAZADO) AS MONTO_RECHAZADO
  FROM (
        SELECT DISTINCT FTC_FOLIO_BITACORA,FCN_ID_SUBPROCESO,
               MONTO,
               SUM(CASE WHEN FTC_ESTA_REGI=1 THEN NUMERO ELSE 0 END) AS ACEPTADOS,
               SUM(CASE WHEN FTC_ESTA_REGI=0 THEN NUMERO ELSE 0 END) RECHAZADOS,
               SUM(CASE WHEN FTC_ESTA_REGI=1 THEN MONTO ELSE 0 END) MONTO_ACEPTADO,
               CASE WHEN FTC_ESTA_REGI=0 THEN MONTO ELSE 0 END MONTO_RECHAZADO
          FROM (
                SELECT FTC_FOLIO AS FTC_FOLIO_BITACORA
                      ,FCN_ID_SUBPROCESO
                      ,0 AS MONTO
                      ,FTC_ESTATUS AS FTC_ESTA_REGI
                      ,COUNT(*) OVER (PARTITION BY FTC_ESTATUS) NUMERO
                  FROM PROCESOS.TTAFOTRAS_DESMARCA_FOVST
                 WHERE FTC_FOLIO = '#SR_FOLIO#'
                   AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#)
        )
GROUP BY FTC_FOLIO_BITACORA,FCN_ID_SUBPROCESO
