SELECT 
       #SR_FOLIO# AS FTC_FOLIO,
       81 AS FCN_ID_SIEFORE,
       Q2.FRN_ID_MOV_SUBCTA AS FFN_ID_CONCEPTO_IMP,
       '#SR_USUARIO#' AS FTC_USU_REG,
       CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FTD_FEC_REG,
       Q1.TOTAL AS FTN_NUM_REG,
       Q1.RECHAZADOS AS FTN_NUM_REG_RECH,
       Q1.AIVS_97_ACEPTADO AS FTN_IMPORTE_ACEP_AIVS,
       Q1.SALDO_97_ACEPTADO AS FTN_IMPORTE_ACEP_PESOS,
       Q1.AIVS_97_RECHAZADO AS FTN_IMPORTE_RECH_AIVS,
       Q1.SALDO_97_RECHAZADO AS FTN_IMPORTE_RECH_PESOS,
       Q1.INTERES_97_ACEPTADO AS FTN_IMPORTE_ACT_PESOS_PRO
FROM (
    SELECT FTC_FOLIO,
           SUM(ACEPTADOS) AS ACEPTADOS,
           SUM(SALDO_97_ACEPTADO) AS SALDO_97_ACEPTADO,
           SUM(INTERES_SALDO_97_ACEPTADO) AS INTERES_97_ACEPTADO,
           SUM(AIVS_97_ACEPTADO) AS AIVS_97_ACEPTADO,
           SUM(RECHAZADOS) AS RECHAZADOS,
           SUM(SALDO_97_RECHAZADO) AS SALDO_97_RECHAZADO,
           SUM(AIVS_97_RECHAZADO) AS AIVS_97_RECHAZADO,
           SUM(ACEPTADOS)+SUM(RECHAZADOS) AS TOTAL,
           FCN_ID_SUBPROCESO,
           15 AS FCN_ID_TIPO_SUBCTA
      FROM (
            SELECT DISTINCT FTC_FOLIO,FCN_ID_SUBPROCESO,
                   
                   CASE WHEN FTC_ESTATUS=1 THEN NUMERO ELSE 0 END ACEPTADOS,
                   CASE WHEN FTC_ESTATUS=0 THEN NUMERO ELSE 0 END RECHAZADOS,
                 
                   CASE WHEN FTC_ESTATUS=1 THEN SALDO_97 ELSE 0 END SALDO_97_ACEPTADO,
                   CASE WHEN FTC_ESTATUS=0 THEN SALDO_97 ELSE 0 END SALDO_97_RECHAZADO,
                   
                   CASE WHEN FTC_ESTATUS=1 THEN INTERES_SALDO_97 ELSE 0 END INTERES_SALDO_97_ACEPTADO,
                   CASE WHEN FTC_ESTATUS=0 THEN INTERES_SALDO_97 ELSE 0 END INTERES_SALDO_97_RECHAZADO,
                   
                   CASE WHEN FTC_ESTATUS=1 THEN AIVS_97 ELSE 0 END AIVS_97_ACEPTADO,
                   CASE WHEN FTC_ESTATUS=0 THEN AIVS_97 ELSE 0 END AIVS_97_RECHAZADO
              FROM (
                   SELECT DEVO.FTC_FOLIO,DEVO.FCN_ID_SUBPROCESO,
                           sum(FTN_SALDO_97) AS SALDO_97,
                           sum(FTN_INTERES_SALDO_97) AS INTERES_SALDO_97,
                           sum(FTN_AIVS_VIV_97) AS AIVS_97,
                           FTC_ESTATUS,
                           COUNT(FTC_ESTATUS) AS NUMERO
                      FROM PROCESOS.TTAFOTRAS_DEVO_SALDO_EXC_INFO DEVO
                     WHERE FTC_FOLIO = '#SR_FOLIO#'
                       AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
                     GROUP BY DEVO.FTC_FOLIO, DEVO.FCN_ID_SUBPROCESO, FTC_ESTATUS)
            )
    GROUP BY FTC_FOLIO, FCN_ID_SUBPROCESO, 15
) Q1
INNER JOIN (
    SELECT FRN_ID_MOV_SUBCTA,
           FCN_ID_TIPO_SUBCTA,
           FCN_ID_SUBPROCESO
    FROM CIERREN.TRAFOGRAL_MOV_SUBCTA
    WHERE FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
) Q2 ON Q1.FCN_ID_SUBPROCESO = Q2.FCN_ID_SUBPROCESO AND Q1.FCN_ID_TIPO_SUBCTA = Q2.FCN_ID_TIPO_SUBCTA
WHERE Q1.SALDO_97_ACEPTADO > 0 OR Q1.SALDO_97_RECHAZADO > 0
