SELECT Trim(SUBSTR(ENC.FTC_LINEA,3,2)) AS FTC_ID_SERVICIO,
       Trim(SUBSTR(ENC.FTC_LINEA,5,2)) AS FTC_ID_OPERACION,
       Trim(SUBSTR(ENC.FTC_LINEA,20,8)) AS FTD_FEH_PRESEN,
       Trim(SUBSTR(DET.FTC_LINEA,1,2)) AS FTC_ID_TIPO_REGIST,
       Trim(SUBSTR(DET.FTC_LINEA,3,2)) AS FTN_LINEA_CREDIT,
       Trim(SUBSTR(DET.FTC_LINEA,5,1)) AS FTN_TIPTRA,
       Trim(SUBSTR(DET.FTC_LINEA,6,18)) AS FTC_CURP,
       Trim(SUBSTR(DET.FTC_LINEA,24,8)) AS FTC_ID_PROCESAR,
       Trim(SUBSTR(DET.FTC_LINEA,32,11)) AS FTC_NSS,
       Trim(SUBSTR(DET.FTC_LINEA,43,13)) AS FTC_RFC,
       Trim(SUBSTR(DET.FTC_LINEA,256,2)) AS FTC_TIPO_MAR_CRE_FOV
  FROM CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO ENC
  LEFT 
  JOIN CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO DET 
    ON ENC.FTN_ID_ARCHIVO=DET.FTN_ID_ARCHIVO
 WHERE ENC.FTN_ID_ARCHIVO = #sr_id_archivo#
   AND SUBSTR(ENC.FTC_LINEA,1,2) = 01
   AND SUBSTR(DET.FTC_LINEA,1,2) = 2.