--UPDATE CIERREN.TTAFOGRAL_IND_CTA_INDV C
SELECT DISTINCT
	C.FTN_NUM_CTA_INVDUAL,
	CASE WHEN  (
					CASE 
					    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
					    THEN 0 
					    WHEN FFN_ID_CONFIG_INDI = 25 AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND = 0) 
					    THEN 1 
				    	ELSE 2 
					END
				) = 0 
		THEN 25 
		Else FFN_ID_CONFIG_INDI 
	END AS FFN_ID_CONFIG_INDI,
	CASE 
	    WHEN ((CASE 
				    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
				    THEN '0' 
				    WHEN FFN_ID_CONFIG_INDI = 25 AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND = 0) 
				    THEN '1' 
				    ELSE '2' 
				END) = 0 
				OR (CASE 
					    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
					    THEN '0' 
					    WHEN FFN_ID_CONFIG_INDI = 25 AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND = 0) 
					    THEN '1' 
					    ELSE '2' 
					END) = 1) 
				AND FTC_INSTITUTO_ORIGEN = '001' 
	    THEN '1' 
	    WHEN ((CASE 
				    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
				    THEN '0' 
				    WHEN FFN_ID_CONFIG_INDI = 25 AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND = 0) 
				    THEN '1' 
				    ELSE '2' 
				END) = 0 
				OR (CASE 
					    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
					    THEN '0' 
					    WHEN FFN_ID_CONFIG_INDI = 25 AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND = 0) 
					    THEN '1' 
					    ELSE '2' 
					END) = 1) AND FTC_INSTITUTO_ORIGEN = '002' 
	    THEN '2' 
	    ELSE FCC_VALOR_IND 
	END AS FCC_VALOR_IND,
	1 AS FTC_VIGENCIA,
	CASE WHEN 	(
					CASE 
					    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
					    THEN 0 
					    WHEN FFN_ID_CONFIG_INDI = 25 AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND = 0) 
					    THEN 1 
					    ELSE 2 
					END
				) = 0 
				OR
				(
					CASE 
					    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
					    THEN 0 
					    WHEN FFN_ID_CONFIG_INDI = 25 AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND = 0) 
					    THEN 1 
					    ELSE 2 
					END
				) = 1 
				THEN CURRENT_TIMESTAMP 
				Else C.FTD_FEH_REG 
	END AS FTD_FEH_REG,
	CASE WHEN 	(
					CASE 
					    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
					    THEN 0 
					    WHEN FFN_ID_CONFIG_INDI = 25 AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND = 0) 
					    THEN 1 
					    ELSE 2 
					END
				) = 0 
				OR 
				(
					CASE 
					    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
					    THEN 0 
					    WHEN FFN_ID_CONFIG_INDI = 25 AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND = 0) 
					    THEN 1 
					    ELSE 2 
					END
				) = 1 
			Then 'DATABRICKS' 
			Else C.FTC_USU_REG 
	END AS FTC_USU_REG,	
	CASE WHEN 	(
					CASE 
					    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
					    THEN 0 
					    WHEN FFN_ID_CONFIG_INDI = 25 AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND = 0) 
					    THEN 1 
					    ELSE 2 
					END
				) = 2 
				Then CURRENT_TIMESTAMP 
			Else NULL 
	END AS FTD_FEH_ACT,
	CASE WHEN 	(
					CASE 
					    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
					    THEN 0 
					    WHEN FFN_ID_CONFIG_INDI = 25 AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND = 0) 
					    THEN 1 
					    ELSE 2 
					END
				) = 2 
			Then 'DATABRICKS' 
			Else NULL 
	END AS FCC_USU_ACT,
	FTC_FOLIO
FROM 
	PROCESOS.TTAFOTRAS_TRANS_REC_PORTA P
INNER JOIN 
	CIERREN.TTAFOGRAL_IND_CTA_INDV C 
ON 
	P.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL 
WHERE 
	P.FTC_FOLIO = 202508041442432876
	AND P.FTC_ESTATUS_OPE = 1
	AND C.FFN_ID_CONFIG_INDI  = 25
	AND C.FTC_VIGENCIA = 1
