SELECT
	LEFT_TABLE.FTC_FECHA_LOTE,
	LEFT_TABLE.FTC_CONSECUTIVO,
	LEFT_TABLE.FTN_ID_ARCHIVO,
	LEFT_TABLE.FTN_TOTAL_CUENTAS_PAGAR,
	RIGHT_TABLE.FTC_IMPORTE_SAR_26,
	RIGHT_TABLE.FTC_IMPORTE_RET_27,
	RIGHT_TABLE.FTC_IMPORTE_CVP_28,
	RIGHT_TABLE.FTC_IMPORTE_CVT_29,
	RIGHT_TABLE.FTC_IMPORTE_SAR_30,
	RIGHT_TABLE.FTC_IMPORTE_RET_31,
	RIGHT_TABLE.FTC_IMPORTE_CVP_32,
	RIGHT_TABLE.FTC_IMPORTE_CVT_33,
	RIGHT_TABLE.FTC_IMPORTE_VIV_34,
	RIGHT_TABLE.FTC_IMPORTE_VIV_35,
	RIGHT_TABLE.FTC_IMPORTE_VIE_36,
	RIGHT_TABLE.FTC_IMPORTE_VIE_37,
	RIGHT_TABLE.FTC_IMPORTE_CSO_44,
	RIGHT_TABLE.FTC_IMPORTE_AVO_45,
	RIGHT_TABLE.FTC_IMPORTE_ACR_46,
	RIGHT_TABLE.FTC_IMPORTE_ALP_47,
	RIGHT_TABLE.FTC_IMPORTE_AAS_48,
	RIGHT_TABLE.FTC_IMPORTE_AAS_49,
	RIGHT_TABLE.FTC_IMPORTE_AST_31,
	RIGHT_TABLE.FTC_IMPORTE_ASD_32,
	RIGHT_TABLE.FTC_IINTERES_AST_33,
	RIGHT_TABLE.FTC_IINTERES_ASD_34,
	RIGHT_TABLE.FTC_IMPORTE_SAR_23,
	RIGHT_TABLE.FTC_IMPORTE_RET_24,
	RIGHT_TABLE.FTC_IMPORTE_CV_25,
	RIGHT_TABLE.FTC_IMPORTE_CV_26,
	RIGHT_TABLE.FTC_IMPORTE_SAR_27,
	RIGHT_TABLE.FTC_INTERES_RET_28,
	RIGHT_TABLE.FTC_INTERES_CV_29,
	RIGHT_TABLE.FTC_INTERES_CV_30,
	RIGHT_TABLE.FTC_IMPORTE_AT_31,
	RIGHT_TABLE.FTC_IMPORTE_AD_32,
	RIGHT_TABLE.FTC_INTERES_AT_33,
	RIGHT_TABLE.FTC_INTERES_AD_34,
	RIGHT_TABLE.FTC_IINTERES_SAR_35,
	RIGHT_TABLE.FTC_IINTERES_RET_36,
	RIGHT_TABLE.FTC_IINTERES_CVP_37,
	RIGHT_TABLE.FTC_IINTERES_CVT_38,
	RIGHT_TABLE.FTC_IINTERES_SAR_39,
	RIGHT_TABLE.FTC_IINTERES_RET_40,
	RIGHT_TABLE.FTC_IINTERES_CVP_41,
	RIGHT_TABLE.FTC_IINTERES_CVT_42,
	RIGHT_TABLE.FTC_IINTERES_AST_43,
	RIGHT_TABLE.FTC_IINTERES_ASD_44,
	RIGHT_TABLE.FTC_IINTERES_AST_45,
	RIGHT_TABLE.FTC_IINTERES_ASD_46,
	RIGHT_TABLE.FTC_IINTERES_TOT_47,
	RIGHT_TABLE.FTN_IMPORTE_RCV_10,
	RIGHT_TABLE.FTN_INTERES_RCV_11,
	RIGHT_TABLE.FTN_IMPORTE_AVOL_12,
	RIGHT_TABLE.FTN_INTERES_AVOL_13,
	RIGHT_TABLE.FTN_IMPORTE_RET_14,
	RIGHT_TABLE.FTN_INTERES_RET_15,
	RIGHT_TABLE.FTN_IMPORTE_ALP_16,
	RIGHT_TABLE.FTN_INTERES_ALP_17,
	RIGHT_TABLE.FTN_IMPORTE_SUB_18,
	RIGHT_TABLE.FTN_INTERES_SUB_19,
	RIGHT_TABLE.FTN_IMPORTE_APP_20,
	RIGHT_TABLE.FTN_INTERES_APP_21,
	RIGHT_TABLE.FTN_IMPORTE_GUB_22,
	RIGHT_TABLE.FTN_INTERES_GUB_23,
	RIGHT_TABLE.FTN_IMPORTE_VIV_27,
	RIGHT_TABLE.FTN_INTERES_VIV_28,
	RIGHT_TABLE.FTN_INTERES_VIV_29,
	RIGHT_TABLE.FTN_INTERES_VIV_30,
	RIGHT_TABLE.FTN_IMPORTE_REM_31,
	RIGHT_TABLE.FTN_INTERES_REM_32,
	RIGHT_TABLE.FTN_IMPORTE_EXT_33,
	RIGHT_TABLE.FTN_INTERES_EXT_34,
	RIGHT_TABLE.FTN_INTERES_VIV_35,
	SEGUNDA_TABLE.FTN_NUM_AP_28,
	TERCERA_TABLE.FTN_MONTO_PESOS
FROM(
	SELECT 
		SUBSTR(FTC_LINEA, 17, 8) AS FTC_FECHA_LOTE,
		SUBSTR(FTC_LINEA, 25, 3) AS FTC_CONSECUTIVO,
		FTN_ID_ARCHIVO,
		TCP.FTN_TOTAL_CUENTAS_PAGAR
	FROM #DELTA_TABLE_LEE_ARCH#
		JOIN
			(
				SELECT SUBSTR(FTC_LINEA, 412, 15) FTN_TOTAL_CUENTAS_PAGAR
				FROM #DELTA_TABLE_LEE_ARCH#
				WHERE SUBSTR(FTC_LINEA, 1, 2) = '09' AND FTN_ID_ARCHIVO = #SR_ID_ARCHIVO#
			) TCP ON 1 = 1
	WHERE SUBSTR(FTC_LINEA, 1, 2) = '01'
		AND FTN_ID_ARCHIVO = #SR_ID_ARCHIVO#
	) LEFT_TABLE
	LEFT JOIN (
		SELECT
			FTN_ID_ARCHIVO,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 26 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_SAR_26,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 27 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_RET_27,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 28 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_CVP_28,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 29 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_CVT_29,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 30 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_SAR_30,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 31 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_RET_31,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 32 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_CVP_32,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 33 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_CVT_33,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 34 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_VIV_34,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 35 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_VIV_35,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 36 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_VIE_36,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 37 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_VIE_37,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 44 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_CSO_44,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 45 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_AVO_45,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 46 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_ACR_46,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 47 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_ALP_47,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 48 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_AAS_48,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 49 AND #SR_SUBPROCESO# = 120 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_AAS_49,
			0 AS FTC_IMPORTE_AST_31,
			0 AS FTC_IMPORTE_ASD_32,
			0 AS FTC_IINTERES_AST_33,
			0 AS FTC_IINTERES_ASD_34,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 23 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_SAR_23,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 24 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_RET_24,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 25 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_CV_25,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 26 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_CV_26,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 27 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_SAR_27,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 28 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_INTERES_RET_28,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 29 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_INTERES_CV_29,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 30 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_INTERES_CV_30,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 31 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_AT_31,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 32 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IMPORTE_AD_32,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 33 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_INTERES_AT_33,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 34 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_INTERES_AD_34,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 35 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_SAR_35,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 36 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_RET_36,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 37 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_CVP_37,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 38 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_CVT_38,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 39 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_SAR_39,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 40 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_RET_40,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 41 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_CVP_41,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 42 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_CVT_42,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 43 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_AST_43,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 44 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_ASD_44,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 45 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_AST_45,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 46 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_ASD_46,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 47 AND #SR_SUBPROCESO# = 122 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTC_IINTERES_TOT_47,
			NVL(SUM(
			  CASE WHEN FTN_ID_MONTO = 20 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_PESOS ELSE 0 END + 
			  CASE WHEN FTN_ID_MONTO = 21 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_PESOS ELSE 0 END +
			  CASE WHEN FTN_ID_MONTO = 22 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_PESOS ELSE 0 END +
			  CASE WHEN FTN_ID_MONTO = 23 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_IMPORTE_RCV_10,
			NVL(SUM(
							CASE WHEN FTN_ID_MONTO = 20 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 3 THEN FTN_MONTO_PESOS ELSE 0 END +
							CASE WHEN FTN_ID_MONTO = 21 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 3 THEN FTN_MONTO_PESOS ELSE 0 END +
							CASE WHEN FTN_ID_MONTO = 22 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 3 THEN FTN_MONTO_PESOS ELSE 0 END +
							CASE WHEN FTN_ID_MONTO = 23 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 3 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_INTERES_RCV_11,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 24 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_IMPORTE_AVOL_12,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 24 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 3 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_INTERES_AVOL_13,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 25 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_IMPORTE_RET_14,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 25 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 3 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_INTERES_RET_15,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 41 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_IMPORTE_ALP_16,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 36 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 3 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_INTERES_ALP_17,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 42 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_IMPORTE_SUB_18,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 37 AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 3 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_INTERES_SUB_19,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 26  AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 AND FTC_ID_VIVIENDA = 0 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_IMPORTE_APP_20,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 26  AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 3 AND FTC_ID_VIVIENDA = 0 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_INTERES_APP_21,
			0 AS FTN_IMPORTE_GUB_22,
			0 AS FTN_INTERES_GUB_23,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 26  AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 AND FTC_ID_VIVIENDA = 1 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_IMPORTE_VIV_27,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 26  AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 3 AND FTC_ID_VIVIENDA = 1 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_INTERES_VIV_28,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 35  AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 AND FTC_ID_VIVIENDA = 0 THEN FTN_MONTO_AIVS ELSE 0 END),0) AS FTN_INTERES_VIV_29,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 35  AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 AND FTC_ID_VIVIENDA = 1 THEN FTN_MONTO_AIVS ELSE 0 END),0) AS FTN_INTERES_VIV_30,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 37  AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_IMPORTE_REM_31,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 38  AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_AIVS ELSE 0 END),0) AS FTN_INTERES_REM_32,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 39  AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_IMPORTE_EXT_33,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 40  AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 2 THEN FTN_MONTO_AIVS ELSE 0 END),0) AS FTN_INTERES_EXT_34,
			NVL(SUM(CASE WHEN FTN_ID_MONTO = 35  AND #SR_SUBPROCESO# = 118 AND FTN_TIPO_REG = 3 THEN FTN_MONTO_PESOS ELSE 0 END),0) AS FTN_INTERES_VIV_35
		FROM #DELTA_ACL_ESP_200#
		WHERE FTN_ID_ESTATUS = 0
		GROUP BY FTN_ID_ARCHIVO
		) RIGHT_TABLE ON LEFT_TABLE.FTN_ID_ARCHIVO = RIGHT_TABLE.FTN_ID_ARCHIVO
LEFT JOIN (
	SELECT
	FTN_ID_ARCHIVO,
	COUNT(1) AS FTN_NUM_AP_28
	FROM #DELTA_ACL_ESP_300#
	WHERE FTN_TIPO_REG = 2
		AND FTN_ID_ARCHIVO = #SR_ID_ARCHIVO#
	GROUP BY FTN_ID_ARCHIVO
)SEGUNDA_TABLE ON LEFT_TABLE.FTN_ID_ARCHIVO = SEGUNDA_TABLE.FTN_ID_ARCHIVO
LEFT JOIN (
	SELECT FTN_ID_ARCHIVO, SUM(FTN_MONTO_PESOS) AS FTN_MONTO_PESOS
	FROM #DELTA_ACL_ESP_400#
	GROUP BY FTN_ID_ARCHIVO) TERCERA_TABLE ON LEFT_TABLE.FTN_ID_ARCHIVO = TERCERA_TABLE.FTN_ID_ARCHIVO