SELECT
NVL(ICTE.FTC_FOLIO, 0) AS FTC_FOLIO,
NVL(ICTE.FTN_NUM_CTA_INVDUAL, 0) AS FTN_NUM_CTA_INVDUAL,
NVL(ICTE.FTC_CURP, 0) AS FTC_CURP,
NVL(ICTE.FTN_NSS, 0) AS FTN_NSS,
CASE 
  WHEN ICTE.FTN_ESTATUS_DIAG = 1 AND CONV.FTB_ESTATUS_MARCA IN (1, 2) 
  THEN '1' 
  ELSE '0' 
END AS FTN_ESTATUS
FROM 
CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE ICTE
LEFT JOIN 
CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV CONV
ON 
ICTE.FTC_FOLIO = CONV.FTC_FOLIO AND ICTE.FTN_NUM_CTA_INVDUAL = CONV.FTN_NUM_CTA_INVDUAL
AND CONV.FCN_ID_PROCESO = #P_PROCESO# AND CONV.FCN_ID_SUBPROCESO = #P_SUBPROCESO#
WHERE ICTE.FTC_FOLIO = #SR_FOLIO#