SELECT 
  FTN_ID_ARCHIVO,       
  FTN_NO_LINEA,         
  FNN_ID_REFERENCIA,    
  FTN_NUM_CTA_INVDUAL,  
  CASE 
    WHEN FTC_TABLA_NCI_MOV = 'VIV' THEN 81 
    ELSE FCN_ID_SIEFORE 
  END AS FCN_ID_SIEFORE,        
  FCN_ID_TIPO_SUBCTA,   
  FTF_MONTO_PESOS,      
  FTF_MONTO_ACCIONES,   
  FTC_TABLA_NCI_MOV,    
  FNN_ID_VIV_GARANTIA,  
  FFN_ID_CONCEPTO_MOV,  
  FCN_ID_PROCESO,       
  FCN_ID_SUBPROCESO,    
  FTC_FOLIO,            
  NVL(FTN_NSS, 0) AS FTN_NSS,
  NVL(FTC_CURP, 0) AS FTC_CURP,
  FTN_ID_MONTO,       
  FTN_TIPO_REG 
FROM 
  TTSISGRAL_ETL_DISPERSION
WHERE 
  FTC_FOLIO = #SR_FOLIO#