-- CREACION DE LA TABLA DELTA 400
SELECT
  FTN_ID_ARCHIVO,
  FTN_TIPO_REG,
  SUM(FTF_MONTO_PESOS) AS FTN_MONTO_PESOS
FROM #DELTA_TABLE_001#
WHERE FTN_ESTATUS = 1 AND FTC_TABLA_NCI_MOV <> 'TOT'
GROUP BY FTN_ID_ARCHIVO, FTN_TIPO_REG
UNION ALL
SELECT
  0 AS FTN_ID_ARCHIVO,
  2 AS FTN_TIPO_REG,
  0 AS FTN_MONTO_PESOS