-- CREACION DE LA TABLA DELTA 200
SELECT
  FCN_ID_SIEFORE,
  FTN_ID_MONTO,
  FTN_ID_CRED_VIV as FTC_ID_VIVIENDA,
  FTN_ID_ARCHIVO,
  FTN_TIPO_REG,
  FTC_FOLIO,
  --FTN_NUM_CTA_INVDUAL,
  FTN_ESTATUS AS FTN_ID_ESTATUS,
  --ROUND(SUM(FTF_MONTO_PESOS),2) AS FTN_MONTO_PESOS,
  ROUND(SUM(
  CASE 
    WHEN #SR_SUBPROCESO# <> 122 OR FTN_ID_MONTO <> 31 THEN FTF_MONTO_PESOS
    WHEN FTN_ID_MONTO = 31 AND FTF_MONTO_PESOS < 1000 THEN FTF_MONTO_PESOS
    ELSE 0
  END
), 2) AS FTN_MONTO_PESOS,
  ROUND(SUM(FTF_MONTO_ACCIONES), 6) AS FTN_MONTO_AIVS
FROM #DELTA_TABLE_001#
GROUP BY FCN_ID_SIEFORE, FTN_ID_MONTO, FTN_ID_CRED_VIV, FTN_ID_ARCHIVO, FTN_TIPO_REG, FTC_FOLIO, FTN_NUM_CTA_INVDUAL, FTN_ESTATUS
HAVING SUM(FTF_MONTO_PESOS) > 0 OR SUM(FTF_MONTO_ACCIONES) > 0