SELECT 
    BASE.*,
    CASE 
        WHEN BASE.FTN_NUM_CTA_INVDUAL IS NOT NULL 
             AND BASE.FTB_ESTATUS_MARCA IN (1, 2)
        THEN 1 
        ELSE 0 
    END AS FTN_ESTATUS
FROM (
    SELECT /*+ parallel(8) */   -- ACLARACIONES ESPECIALES
           D.FTC_FOLIO,
           NVL((CASE WHEN HIST.FTN_ESTATUS_REG = 558 THEN D.FTN_NUM_CTA_INVDUAL
                     ELSE NULL
                END), NULL) AS FTN_NUM_CTA_INVDUAL,
           D.FTN_ID_ARCHIVO,
           D.FTN_NO_LINEA,
           CASE WHEN D.FCN_ID_SIEFORE IS NULL THEN 846 ELSE D.FCN_ID_SIEFORE END AS FCN_ID_SIEFORE,
           D.FCN_ID_TIPO_SUBCTA,
           ROUND((CASE WHEN CCM.FCN_ID_TIPO_MONTO = 184 THEN D.FTF_MONTO_PESOS ELSE 0 END), 6) AS FTF_MONTO_PESOS,
           ROUND((CASE WHEN CCM.FCN_ID_TIPO_MONTO = 199 THEN D.FTF_MONTO_ACCIONES ELSE 0 END), 6) AS FTF_MONTO_ACCIONES,
           D.FTC_TABLA_NCI_MOV,
           D.FNN_ID_VIV_GARANTIA AS FTN_ID_CRED_VIV,
           D.FFN_ID_CONCEPTO_MOV,
           D.FTN_ID_MONTO,
           D.FTN_TIPO_REG,
           VMC.FTB_ESTATUS_MARCA
    FROM (
        SELECT *
        FROM CIERREN_ETL.TTSISGRAL_ETL_DISPERSION
        WHERE FFN_ID_CONCEPTO_MOV <> 231
          AND FTC_FOLIO = '#SR_FOLIO#'
    ) D
    INNER JOIN CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CCM 
            ON CCM.FFN_ID_CONCEPTO_MOV = D.FFN_ID_CONCEPTO_MOV
    LEFT OUTER JOIN PROCESOS.TTAFOAE_AEIM HIST
            ON (DECODE(LENGTH(TRIM(D.FTC_NOMBRE)), NULL, '1', TRIM(D.FTC_NOMBRE)) = DECODE(LENGTH(TRIM(HIST.FTC_NOMBRE_COMPLETO_ARCH)), NULL, '1', TRIM(HIST.FTC_NOMBRE_COMPLETO_ARCH))
            AND DECODE(LENGTH(TRIM(D.FTN_NSS)), NULL, '1', TRIM(D.FTN_NSS)) = DECODE(LENGTH(TRIM(HIST.FTN_NSS_ARCH)), NULL, '1', TRIM(HIST.FTN_NSS_ARCH))
            AND DECODE(LENGTH(TRIM(D.FTC_RFC)), NULL, '1', TRIM(D.FTC_RFC)) = DECODE(LENGTH(TRIM(HIST.FTC_RFC_ARCH)), NULL, '1', TRIM(HIST.FTC_RFC_ARCH))
            AND DECODE(LENGTH(TRIM(D.FCN_REG_PATRONAL_IMSS)), NULL, '1', TRIM(D.FCN_REG_PATRONAL_IMSS)) = DECODE(LENGTH(TRIM(HIST.FNC_REG_PATRONAL_IMSS)), NULL, '1', TRIM(HIST.FNC_REG_PATRONAL_IMSS)))
    LEFT JOIN (
        SELECT FTN_NUM_CTA_INVDUAL, FTB_ESTATUS_MARCA
        FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV
        WHERE FTC_FOLIO = '#SR_FOLIO#'
    ) VMC ON D.FTN_NUM_CTA_INVDUAL = VMC.FTN_NUM_CTA_INVDUAL
    WHERE D.FTC_FOLIO = '#SR_FOLIO#'
      AND D.FCN_ID_SUBPROCESO IN (118)
      AND CCM.FFB_VIGENCIA = 1
) BASE