-- CREACION DE LA TABLA DELTA 500
SELECT
  FTC_FOLIO,
  FTN_ESTATUS,
  1 AS FTN_TOT_REG
  --FTN_NO_LINEA,
  --FTN_TIPO_REG
  -- ROUND(SUM(FTF_MONTO_PESOS),2) AS FTN_MONTO_PESOS,
  -- ROUND(SUM(FTF_MONTO_ACCIONES),6) AS FTN_MONTO_ACCIONES
FROM #DELTA_TABLE_001#
GROUP BY FTC_FOLIO,FTN_ESTATUS,FTN_TOT_REG,FTN_NO_LINEA
HAVING ROUND(SUM(FTF_MONTO_PESOS),2) > 0 OR ROUND(SUM(FTF_MONTO_ACCIONES),6) > 0