-- CREACION DE LA TABLA DELTA 300
SELECT
  DISTINCT
  FTN_ID_ARCHIVO
  , FTN_NO_LINEA
  , FTN_TIPO_REG
FROM #DELTA_TABLE_001#
WHERE FTN_ESTATUS = 0

-- SELECT
--   FTN_ID_ARCHIVO
--   , FTN_NO_LINEA
--   , FTN_TIPO_REG
-- FROM (
--   SELECT
--     FTN_ID_ARCHIVO
--     , FTN_NO_LINEA
--     , FTN_TIPO_REG
--     , ROW_NUMBER() OVER (PARTITION BY FTN_ID_ARCHIVO, FTN_NO_LINEA, FTN_TIPO_REG ORDER BY FTN_ID_ARCHIVO) AS row_num
--   FROM #DELTA_TABLE_001#
--   WHERE FTN_ESTATUS = 0
-- ) subquery
-- WHERE row_num = 1