SELECT FTC_FOLIO
      ,SUM(CASE WHEN FTN_ESTATUS = 0 THEN FTN_TOT_REG ELSE 0 END) AS FLN_REG_RECHAZADOS
      ,SUM(FTN_TOT_REG) AS FLN_TOTAL_REGISTROS
      ,SUM(FTN_TOT_REG) - SUM(CASE WHEN FTN_ESTATUS = 0 THEN FTN_TOT_REG ELSE 0 END) AS FLN_REG_ACEPTADOS
      ,#SR_PROCESO# AS FCN_ID_PROCESO
      ,#SR_SUBPROCESO# AS FCN_ID_SUBPROCESO
      ,FROM_UTC_TIMESTAMP(CURRENT_TIMESTAMP(), 'America/Mexico_City') AS FLD_FEC_REG
      ,'#CRE_USUARIO#' AS FLC_USU_REG
FROM #DELTA_ACL_ESP_500#
GROUP BY FTC_FOLIO