MERGE INTO PROCESOS.TTAFOTRAS_TRANS_REC_PORTA   TGT
USING (
    SELECT DISTINCT
        FTN_NUM_CTA_INVDUAL,
        FTC_NSS_IMSS,
        FTC_INSTITUTO_ORIGEN,
        FTC_FOLIO,
        FTC_ESTATUS_OPE,
        FTC_MOTIVO_REC,
        FTD_FEH_ACT,
        FTC_USU_ACT
    FROM CIERREN_DATAUX.TTAFOTRAS_TRANS_REC_PORTA_AUX
    WHERE FTC_FOLIO = '#sr_folio#'
) SRC
ON (
    TGT.FTN_NUM_CTA_INVDUAL = SRC.FTN_NUM_CTA_INVDUAL
    AND TGT.FTC_NSS_IMSS = SRC.FTC_NSS_IMSS
    AND TGT.FTC_INSTITUTO_ORIGEN = SRC.FTC_INSTITUTO_ORIGEN
    AND TGT.FTC_FOLIO = SRC.FTC_FOLIO

)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTC_ESTATUS_OPE = SRC.FTC_ESTATUS_OPE,
        TGT.FTC_MOTIVO_REC = SRC.FTC_MOTIVO_REC,
        TGT.FTD_FEH_ACT = SRC.FTD_FEH_ACT,
        TGT.FTC_USU_ACT = SRC.FTC_USU_ACT
 