SELECT 
T.FTC_FOLIO AS FTC_FOLIO_BITA,
T.FTC_ID_SERVICIO,
T.FTC_ID_OPERACION,
T.FTD_FEH_PRESEN,
T.FTC_ID_TIPO_REGIST AS FTC_ID_TIPO_REG,
T.FTN_LINEA_CREDIT,
T.FTN_TIPTRA AS FCN_ID_TIPO_TRAB,
T.FTC_CURP,
T.FTC_ID_PROCESAR,
T.FTC_NSS,
T.FTC_RFC,
T.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_IND,
T.FCN_ID_SUBPROCESO,
CAST(CASE 
    WHEN T.FTC_ESTATUS IS NULL THEN CAST(NULL AS DECIMAL(2,0))
    WHEN LENGTH(TRIM(T.FTC_ESTATUS)) = 0 THEN CAST(NULL AS DECIMAL(2,0))
    ELSE CAST(T.FTC_ESTATUS AS DECIMAL(2,0))
END AS DECIMAL(2,0)) AS FCN_ID_ESTA_REG,
T.FTN_MOTIVO_RECHAZO AS FCN_ID_MOTI_RECH,
T.FTC_ID_INDICADOR AS FTC_ID_INDI_CRED,
T.FTD_FEH_CERTIFICACION,
T.FTC_VIGEN_CTA AS FTC_ID_VIGEN_CTA_IND,
CAST(2 AS DECIMAL(10,0)) AS FCN_ID_INSTITUTO,
to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_CRE,
CAST('#CX_CRE_USUARIO#' AS VARCHAR(30)) AS FTC_USU_CRE
FROM #CATALOG_SCHEMA#.TEMP_DSM_FOV_#SR_FOLIO# T
