SELECT 
FTC_FOLIO,
FTC_ID_SERVICIO,
FTC_ID_OPERACION,
FTD_FEH_PRESEN,
FTC_ID_TIPO_REGIST,
FTN_LINEA_CREDIT,
FTN_TIPTRA,
FTC_CURP,
FTC_ID_PROCESAR,
FTC_NSS,
FTC_RFC,
FTN_NUM_CTA_INVDUAL,
FCN_ID_SUBPROCESO,
FTC_ESTATUS,
FTN_MOTIVO_RECHAZO,
FTC_ID_INDICADOR,
FTD_FEH_CERTIFICACION,
FTC_VIGEN_CTA
FROM #CX_PRO_ESQUEMA#.#TL_PRO_DESM_FOV#
WHERE FTC_FOLIO = #SR_FOLIO#
  AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
