SELECT 
  FTC_CURP,
  FTC_NSS,
  FTC_APELLIDO_PATER_AFORE,
  FTC_APELLIDO_MATER_AFORE,
  FTC_NOMBRE_AFORE,
  FTC_RFC,
  FTC_FOLIO,
  FTN_ID_ARCHIVO,
  FTC_TIPO_ARCH,
  FTD_FEH_CRE,
  FTN_NUM_CTA_INVDUAL,
  FTC_RFC_BUC,
  FTC_BANDERA,
  FTN_CELULAR,
  FTC_CORREO_ELEC
FROM(
    SELECT 
      BUC.FTC_CURP,
      SDO.FTC_NSS_AFORE AS FTC_NSS,
      SDO.FTC_APELLIDO_PATER_AFORE,
      SDO.FTC_APELLIDO_MATER_AFORE,
      SDO.FTC_NOMBRE_AFORE,
      SDO.FTC_RFC_INFONA AS FTC_RFC,
      SDO.FTC_FOLIO,
      SDO.FTN_ID_ARCHIVO,
      SDO.FTC_TIPO_ARCH,
      SDO.FTD_FEH_CRE,
      BUC.FTN_NUM_CTA_INVDUAL,
      BUC.FTC_RFC_BUC,
      BUC.FTC_BANDERA_BUC AS FTC_BANDERA,
      BUC.FTN_CELULAR,
      BUC.FTC_CORREO_ELEC,
      BUC.RN
    FROM CIERREN_ETL.TTAFOTRAS_ETL_DEVO_SALDO_EXC SDO
    LEFT JOIN (
        SELECT 
          B.FTC_NSS,
          B.FTN_NUM_CTA_INVDUAL,
          B.FTC_RFC AS FTC_RFC_BUC,
          B.FTC_CURP,
          B.FTC_BANDERA FTC_BANDERA_BUC,
          B.FTN_CELULAR,
          B.FTC_CORREO_ELEC,
          ROW_NUMBER() OVER (PARTITION BY B.FTC_NSS, B.FTN_NUM_CTA_INVDUAL ORDER BY B.FTC_NSS, B.FTN_NUM_CTA_INVDUAL ASC) AS RN
        FROM (
          SELECT FTC_NSS_AFORE
            FROM CIERREN_ETL.TTAFOTRAS_ETL_DEVO_SALDO_EXC
            WHERE FTC_FOLIO='#SR_FOLIO#') A 
          LEFT JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC B 
            ON (A.FTC_NSS_AFORE=B.FTC_NSS)
    ) BUC
      ON  SDO.FTC_NSS_AFORE = BUC.FTC_NSS
      AND BUC.RN = 1
    WHERE SDO.FTN_ID_ARCHIVO = #SR_ID_ARCHIVO#
      AND SDO.FTC_FOLIO = '#SR_FOLIO#'
    ORDER BY SDO.FTC_NSS_AFORE
	)