SELECT 
    EX.FTC_TIPO_TRANSF,
    EX.FTD_FEH_PRESEN,
    EX.FTD_FEH_MOVI,
    EX.FTC_CURP,
    EX.FTN_CTA_AFORE,
    EX.FTC_NSS_AFORE,
    EX.FTC_APELLIDO_PATER_AFORE,
    EX.FTC_APELLIDO_MATER_AFORE,
    EX.FTC_NOMBRE_AFORE,
    EX.FTC_NOMBRE_IMSS,
    EX.FTC_RFC_INFONA,
    EX.FTN_NUM_CRED_INFONA,
    EX.FTC_IDENTI_LOTE_DEV,
    EX.FTN_AIVS_VIV_92,
    EX.FTN_SALDO_92,
    EX.FTN_INTERES_SALDO_92,
    EX.FTN_AIVS_VIV_97,
    EX.FTN_SALDO_97,
    EX.FTN_INTERES_SALDO_97,
    EX.FTD_FEH_VAL_VIV,
    EX.FTC_IDENTI_ASIG,
    EX.FTC_TIPO_DEV,
    EX.FTC_NSS_SEPAR_CTA,
    EX.FTC_ORIGEN_DEV,
    EX.FTN_MONTO_APORTA,
    EX.FTN_APLIC_INT_APORTA,
    EX.FTC_FOLIO,
    EX.FTN_ID_ARCHIVO,
    EX.FTC_TIPO_ARCH,
    EX.FCN_ID_SUBPROCESO,
    EX.FTN_CONTA_SERV,
    CT.FTN_NUM_CTA_INVDUAL, 
    CT.FTN_ESTATUS_DIAG,
    CT.FTC_ID_DIAGNOSTICO
FROM CIERREN_ETL.TTAFOTRAS_ETL_DEVO_SALDO_EXC EX
LEFT JOIN (
   SELECT 
     NVL(FTN_NSS,0) AS FTC_NSS_AFORE, 
     FTN_NUM_CTA_INVDUAL, 
     FTN_ESTATUS_DIAG,
     FTC_ID_DIAGNOSTICO
   FROM CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE 
   WHERE FTC_FOLIO = '#SR_FOLIO#'
) CT
ON EX.FTC_NSS_AFORE =  CT.FTC_NSS_AFORE
WHERE EX.FTC_FOLIO = '#SR_FOLIO#'
  AND EX.FTN_ID_ARCHIVO = #SR_ID_ARCHIVO#
ORDER BY EX.FTC_NSS_AFORE


