WITH src AS (
  SELECT *,
    CASE WHEN Diagnostico_97 IN ('100','101','104') THEN CAST(Diagnostico_97 AS INT) ELSE NULL END AS d97,
    CASE WHEN Diagnostico_08 IN ('100','101','104') THEN CAST(Diagnostico_08 AS INT) ELSE NULL END AS d08
  FROM #FU_504_UNI_COMPLETA#
),
calc AS (
  SELECT *,
    CASE
      WHEN d97 IS NULL OR d08 IS NULL THEN COALESCE(d97, d08)
      WHEN d97 = d08 THEN d97
      WHEN d97 <> d08 THEN 101
      ELSE 100
    END AS vDiagnostico
  FROM src
)
SELECT
  FTN_NUM_CTA_INVDUAL,
  FTN_IND_SDO_DISP_VIV97,
  FTN_IND_SDO_DISP_VIV08 AS FTN_IND_SDO_DISP_92,
  CASE WHEN FTN_IND_SDO_DISP_VIV97 = 1 THEN FTN_MONTO_PESOS / NULLIF(FCN_VALOR_ACCION, 0) ELSE 0 END AS FTN_SDO_AIVS,
  CASE WHEN FTN_IND_SDO_DISP_VIV08 = 1 THEN FTN_MONTO_PESOS_08 / NULLIF(FCN_VALOR_ACCION, 0) ELSE 0 END AS FTN_SDO_AIVS_92,
  CASE WHEN vMotivoRechazo IS NULL THEN FCN_VALOR_ACCION ELSE 0 END AS FTN_VALOR_AIVS,
  CAST(FTN_MONTO_PESOS AS DECIMAL(18,2)) AS FTN_MONTO_PESOS,
  CAST(FTN_MONTO_PESOS_08 AS DECIMAL(18,2)) AS FTN_MONTO_PESOS_92,
  CASE WHEN FTN_IND_SDO_DISP_VIV08 = 0 AND FTN_IND_SDO_DISP_VIV97 = 0 THEN 0 ELSE 1 END AS FCN_ESTATUS,
  CURRENT_TIMESTAMP AS FTD_FEH_CRE,
  'DATABRICKS' AS FTC_USU_CRE, -- replace with actual job user param if needed
  FTC_FOLIO_BITACORA,
  FCN_ID_REGIMEN,
  FCN_ID_TIPO_SUBCTA_97,
  FCN_ID_TIPO_SUBCTA_08 AS FCN_ID_TIPO_SUBCTA_92,
  FTN_SUBPROCESO AS FTN_ID_SUBP,
  FCN_ID_VALOR_ACCION,
  FTN_NO_LINEA AS FTN_CONTA_SERV,
  -- vMotivoRechazo numeric mapping per JP_PATRIF_VSS_0301 (100/101/104)
  CAST(
    CASE
      WHEN vDiagnostico IN (104, 100, 101) THEN vDiagnostico
      ELSE NULL
    END AS DECIMAL(10,0)
  ) AS FTN_MOTI_RECH
FROM (
  SELECT *,
    -- compute vMotivoRechazo here for readability (null when no motive)
    CASE
      WHEN
        (CASE
           WHEN d97 IS NULL OR d08 IS NULL THEN COALESCE(d97, d08)
           WHEN d97 = d08 THEN d97
           WHEN d97 <> d08 THEN 101
           ELSE 100
         END) IN (104,100,101)
      THEN
        (CASE
           WHEN d97 IS NULL OR d08 IS NULL THEN COALESCE(d97, d08)
           WHEN d97 = d08 THEN d97
           WHEN d97 <> d08 THEN 101
           ELSE 100
         END)
      ELSE NULL
    END AS vMotivoRechazo
  FROM calc
) t