WITH base AS (
  SELECT
    FTN_NUM_CTA_INVDUAL,
    FTN_SUBPROCESO,
    FTC_INSTITUTO_ORIGEN,
    FECHA_VALOR_AIVS,
    FTC_NSS_IMSS,
    FTN_MONTO_PESOS,
    FTN_TOTAL_AIVS,
    FTN_AIVS,
    SALDO_DISPONIBLE_AIVS_VIV97,
    SALDO_DISPONIBLE_AIVS_VIV92,
    FTN_NO_LINEA,
    FCN_ID_REGIMEN,
    FCN_ID_TIPO_SUBCTA_92,
    FTN_MONTO_PESOS_92,
    FTN_TOTAL_AIVS_92
  FROM #DS_300_TRANFERENCIAS#
  WHERE
    (SALDO_DISPONIBLE_AIVS_VIV97 > 0 AND FTN_MONTO_PESOS > 0)
    OR
    (SALDO_DISPONIBLE_AIVS_VIV92 > 0 AND FTN_MONTO_PESOS_92 > 0)
),
-- 2. Aggregation: Count by NSS
agg AS (
  SELECT
    FTC_NSS_IMSS,
    COUNT(FTN_NUM_CTA_INVDUAL) AS CONTEO
  FROM base
  GROUP BY FTC_NSS_IMSS
),
-- 3. Join: Attach CONTEO to each row
joined AS (
  SELECT
    b.*,
    a.CONTEO
  FROM base b
  LEFT JOIN agg a ON b.FTC_NSS_IMSS = a.FTC_NSS_IMSS
),
-- 4. Lookup: Get action values from Oracle table
valor_accion AS (
  SELECT
    -- Only the next month's value
    /*CASE WHEN FCN_ID_REGIMEN = 138 THEN FCD_FEH_ACCION ELSE CURRENT_DATE END AS FCD_FEH_ACCION_97,
    CASE WHEN FCN_ID_REGIMEN = 138 THEN FCN_VALOR_ACCION ELSE 0 END AS FCN_VALOR_ACCION_97,
    CASE WHEN FCN_ID_REGIMEN = 138 THEN FCN_ID_VALOR_ACCION ELSE 0 END AS FCN_ID_VALOR_ACCION_97,
    CASE WHEN FCN_ID_REGIMEN = 139 THEN FCD_FEH_ACCION ELSE CURRENT_DATE END AS FCD_FEH_ACCION_08,
    CASE WHEN FCN_ID_REGIMEN = 139 THEN TRUNC(FCN_VALOR_ACCION,6) ELSE 0 END AS FCN_VALOR_ACCION_08,
    CASE WHEN FCN_ID_REGIMEN = 139 THEN FCN_ID_VALOR_ACCION ELSE 0 END AS FCN_ID_VALOR_ACCION_08,
    ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1) AS FECHA_VALOR_AIVS,
    FCN_ID_REGIMEN*/
    *
  FROM #DS_500_VALOR_ACCION#
  /*WHERE
    FCN_ID_SIEFORE = 81
    AND FCN_ID_REGIMEN IN (138, 139)
    AND FCD_FEH_ACCION = ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1)*/
),
-- 5. Attach valor_accion by FECHA_VALOR_AIVS and FCN_ID_REGIMEN
enriched AS (
  SELECT
    j.*,
    va.FCN_VALOR_ACCION_97,
    va.FCN_VALOR_ACCION_08,
    va.FCN_ID_VALOR_ACCION_97,
    va.FCN_ID_VALOR_ACCION_08
  FROM joined j
  LEFT JOIN valor_accion va
    ON j.FECHA_VALOR_AIVS = va.FECHA_VALOR_AIVS
    AND j.FCN_ID_REGIMEN = va.FCN_ID_REGIMEN
)
-- 6. Transformer logic: Only CONTEO = 1 (unique NSS)
SELECT
  FTN_NUM_CTA_INVDUAL,
  -- FTN_IND_SDO_DISP_VIV97: 1 if vMonto97 > 0 or vMonto08 > 0 else 0
  CASE WHEN
    (CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN
      CASE
        WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0)) >= FTN_MONTO_PESOS
          THEN FTN_MONTO_PESOS
        WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0)) < FTN_MONTO_PESOS
          THEN (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0))
        ELSE 0
      END
    ELSE
      CASE
        WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0)) >= FTN_MONTO_PESOS
          THEN FTN_MONTO_PESOS
        WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0)) < FTN_MONTO_PESOS
          THEN (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0))
        ELSE 0
      END
    END
    ) > 0
    THEN 1 ELSE 0 END AS FTN_IND_SDO_DISP_VIV97,

  -- FTN_IND_SDO_DISP_VIV08: 1 if vMontoVIV92 > 0 or vMontoFOV92 > 0 else 0
  CASE WHEN
    (CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN
      CASE
        WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0)) >= FTN_MONTO_PESOS_92
          THEN FTN_MONTO_PESOS_92
        WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0)) < FTN_MONTO_PESOS_92
          THEN (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0))
        ELSE 0
      END
    ELSE
      CASE
        WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0)) >= FTN_MONTO_PESOS_92
          THEN FTN_MONTO_PESOS_92
        WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0)) < FTN_MONTO_PESOS_92
          THEN (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0))
        ELSE 0
      END
    END
    ) > 0
    THEN 1 ELSE 0 END AS FTN_IND_SDO_DISP_VIV08,

  -- FCN_VALOR_ACCION: depends on FTC_INSTITUTO_ORIGEN
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN FCN_VALOR_ACCION_97 ELSE FCN_VALOR_ACCION_08 END AS FCN_VALOR_ACCION,

  -- FTN_MONTO_PESOS: as above (vMonto97 or vMonto08)
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001'
    THEN
      CASE
        WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0)) >= FTN_MONTO_PESOS
          THEN FTN_MONTO_PESOS
        WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0)) < FTN_MONTO_PESOS
          THEN (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0))
        ELSE 0
      END
    ELSE
      CASE
        WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0)) >= FTN_MONTO_PESOS
          THEN FTN_MONTO_PESOS
        WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0)) < FTN_MONTO_PESOS
          THEN (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0))
        ELSE 0
      END
    END AS FTN_MONTO_PESOS,

  -- FTN_MONTO_PESOS_08: as above (vMontoVIV92 or vMontoFOV92)
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001'
    THEN
      CASE
        WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0)) >= FTN_MONTO_PESOS_92
          THEN FTN_MONTO_PESOS_92
        WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0)) < FTN_MONTO_PESOS_92
          THEN (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0))
        ELSE 0
      END
    ELSE
      CASE
        WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0)) >= FTN_MONTO_PESOS_92
          THEN FTN_MONTO_PESOS_92
        WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0)) < FTN_MONTO_PESOS_92
          THEN (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0))
        ELSE 0
      END
    END AS FTN_MONTO_PESOS_08,

  -- FTC_FOLIO_BITACORA: parameter value
  '#sr_folio#' AS FTC_FOLIO_BITACORA,

  -- FCN_ID_TIPO_SUBCTA_97: depends on FTC_INSTITUTO_ORIGEN
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN 15 ELSE 18 END AS FCN_ID_TIPO_SUBCTA_97,

  -- FCN_ID_TIPO_SUBCTA_08: depends on FTC_INSTITUTO_ORIGEN
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN 16 ELSE 17 END AS FCN_ID_TIPO_SUBCTA_08,

  FTN_SUBPROCESO,

  -- FCN_ID_VALOR_ACCION: depends on FTC_INSTITUTO_ORIGEN
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN FCN_ID_VALOR_ACCION_97 ELSE FCN_ID_VALOR_ACCION_08 END AS FCN_ID_VALOR_ACCION,

  FTN_TOTAL_AIVS,

  -- ValorSaldosSolPesos_VIV97
  CAST( CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN (CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN COALESCE(FTN_MONTO_PESOS,0) ELSE 0 END) ELSE (CASE WHEN FTC_INSTITUTO_ORIGEN = '002' THEN COALESCE(FTN_MONTO_PESOS,0) ELSE 0 END) END AS DECIMAL(12,2)) AS ValorSaldosSolPesos_VIV97,

  -- ValorSaldosSolPesos_VIV08
CAST(
  CASE
    WHEN FTC_INSTITUTO_ORIGEN = '001'
      THEN (CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN COALESCE(FTN_MONTO_PESOS_92,0) ELSE 0 END)
    ELSE (CASE WHEN FTC_INSTITUTO_ORIGEN = '002' THEN COALESCE(FTN_MONTO_PESOS_92,0) ELSE 0 END)
  END
AS DECIMAL(12,2)) AS ValorSaldosSolPesos_FOV08,

  -- FTN_TOTAL_AIVS_97: only for IMSS
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN FTN_TOTAL_AIVS ELSE 0 END AS FTN_TOTAL_AIVS_97,

  -- FTN_TOTAL_AIVS_08: only for ISSSTE
  CASE WHEN FTC_INSTITUTO_ORIGEN = '002' THEN FTN_TOTAL_AIVS ELSE 0 END AS FTN_TOTAL_AIVS_08,

  FTN_NO_LINEA,
  FCN_ID_REGIMEN,

  -- Diagnostico_97: see transformer logic (simplified)
  CASE
    WHEN FTC_INSTITUTO_ORIGEN = '001' THEN
      CASE
        WHEN FTN_MONTO_PESOS > 0 AND (CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN
          CASE
            WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0)) >= FTN_MONTO_PESOS
              THEN FTN_MONTO_PESOS
            WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0)) < FTN_MONTO_PESOS
              THEN (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0))
            ELSE 0
          END
        ELSE 0 END) = 0 THEN 104
        WHEN FTN_MONTO_PESOS > 0 AND FTN_MONTO_PESOS <= (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0)) THEN 100
        WHEN FTN_MONTO_PESOS > 0 AND FTN_MONTO_PESOS > (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0)) THEN 101
        ELSE NULL
      END
    ELSE
      CASE
        WHEN FTN_MONTO_PESOS > 0 AND (CASE WHEN FTC_INSTITUTO_ORIGEN = '002' THEN
          CASE
            WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0)) >= FTN_MONTO_PESOS
              THEN FTN_MONTO_PESOS
            WHEN FTN_MONTO_PESOS > 0 AND (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0)) < FTN_MONTO_PESOS
              THEN (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0))
            ELSE 0
          END
        ELSE 0 END) = 0 THEN 104
        WHEN FTN_MONTO_PESOS > 0 AND FTN_MONTO_PESOS <= (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0)) THEN 100
        WHEN FTN_MONTO_PESOS > 0 AND FTN_MONTO_PESOS > (SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0)) THEN 101
        ELSE NULL
      END
  END AS Diagnostico_97,

  -- Diagnostico_08: similar logic for VIV92/FOV92
  CASE
    WHEN FTC_INSTITUTO_ORIGEN = '001' THEN
      CASE
        WHEN FTN_MONTO_PESOS_92 > 0 AND (CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN
          CASE
            WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0)) >= FTN_MONTO_PESOS_92
              THEN FTN_MONTO_PESOS_92
            WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0)) < FTN_MONTO_PESOS_92
              THEN (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0))
            ELSE 0
          END
        ELSE 0 END) = 0 THEN 104
        WHEN FTN_MONTO_PESOS_92 > 0 AND FTN_MONTO_PESOS_92 <= (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0)) THEN 100
        WHEN FTN_MONTO_PESOS_92 > 0 AND FTN_MONTO_PESOS_92 > (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0)) THEN 101
        ELSE NULL
      END
    ELSE
      CASE
        WHEN FTN_MONTO_PESOS_92 > 0 AND (CASE WHEN FTC_INSTITUTO_ORIGEN = '002' THEN
          CASE
            WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0)) >= FTN_MONTO_PESOS_92
              THEN FTN_MONTO_PESOS_92
            WHEN FTN_MONTO_PESOS_92 > 0 AND (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0)) < FTN_MONTO_PESOS_92
              THEN (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0))
            ELSE 0
          END
        ELSE 0 END) = 0 THEN 104
        WHEN FTN_MONTO_PESOS_92 > 0 AND FTN_MONTO_PESOS_92 <= (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0)) THEN 100
        WHEN FTN_MONTO_PESOS_92 > 0 AND FTN_MONTO_PESOS_92 > (SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0)) THEN 101
        ELSE NULL
      END
  END AS Diagnostico_08,

  FTC_INSTITUTO_ORIGEN

FROM enriched
WHERE CONTEO = 1