WITH tf_505_stagevars AS (
  SELECT
    *,
    -- vDiagnostico
    CASE
      WHEN Diagnostico_97 IS NULL OR Diagnostico_08 IS NULL THEN COALESCE(Diagnostico_97, Diagnostico_08)
      WHEN Diagnostico_97 = Diagnostico_08 THEN Diagnostico_97
      WHEN Diagnostico_97 <> Diagnostico_08 THEN '101'
      ELSE '100'
    END AS vDiagnostico,
    -- vMotivoRechazo
    CASE
      WHEN
        CASE
          WHEN Diagnostico_97 IS NULL OR Diagnostico_08 IS NULL THEN COALESCE(Diagnostico_97, Diagnostico_08)
          WHEN Diagnostico_97 = Diagnostico_08 THEN Diagnostico_97
          WHEN Diagnostico_97 <> Diagnostico_08 THEN '101'
          ELSE '100'
        END = '104'
      THEN 104 ELSE NULL END AS vMotivoRechazo,
    -- vValAccionINF
    CASE WHEN FCN_ID_TIPO_SUBCTA_97 IN (15,18) THEN FCN_VALOR_ACCION ELSE 0 END AS vValAccionINF,
    -- vValAccionFOV
    CASE WHEN FCN_ID_TIPO_SUBCTA_08 IN (16,17) THEN FCN_VALOR_ACCION ELSE 0 END AS vValAccionFOV
  FROM #FU_504_UNI_COMPLETA#
),
tf_505_totals AS (
  SELECT
    *,
    -- vTotAivVIV97
    CASE
      WHEN FTC_INSTITUTO_ORIGEN = '001' AND FTN_IND_SDO_DISP_VIV97 = 1 AND (FTN_TOTAL_AIVS_97 IS NULL OR FTN_TOTAL_AIVS_97 = 0)
        THEN ValorSaldosSolPesos_VIV97 / NULLIF(vValAccionINF,0)
      ELSE FTN_TOTAL_AIVS_97
    END AS vTotAivVIV97,
    -- vTotAivViv92
    CASE
      WHEN FTC_INSTITUTO_ORIGEN = '001' AND FTN_IND_SDO_DISP_VIV08 = 1 AND (FTN_TOTAL_AIVS_08 IS NULL OR FTN_TOTAL_AIVS_08 = 0)
        THEN ValorSaldosSolPesos_FOV08 / NULLIF(vValAccionINF,0)
      ELSE FTN_TOTAL_AIVS_08
    END AS vTotAivViv92,
    -- vTotAivFov08
    CASE
      WHEN FTC_INSTITUTO_ORIGEN = '002' AND FTN_IND_SDO_DISP_VIV97 = 1 AND (FTN_TOTAL_AIVS_97 IS NULL OR FTN_TOTAL_AIVS_97 = 0)
        THEN ValorSaldosSolPesos_VIV97 / NULLIF(vValAccionFOV,0)
      ELSE FTN_TOTAL_AIVS_97
    END AS vTotAivFov08,
    -- vTotAivFov92
    CASE
      WHEN FTC_INSTITUTO_ORIGEN = '002' AND FTN_IND_SDO_DISP_VIV08 = 1 AND (FTN_TOTAL_AIVS_08 IS NULL OR FTN_TOTAL_AIVS_08 = 0)
        THEN ValorSaldosSolPesos_FOV08 / NULLIF(vValAccionFOV,0)
      ELSE FTN_TOTAL_AIVS_08
    END AS vTotAivFov92
  FROM tf_505_stagevars
)
SELECT
  FTN_NUM_CTA_INVDUAL,
  FTN_IND_SDO_DISP_VIV97,
  FTN_IND_SDO_DISP_VIV08 AS FTN_IND_SDO_DISP_92,
  CASE WHEN FTN_IND_SDO_DISP_VIV97 = 1 THEN FTN_MONTO_PESOS / NULLIF(FCN_VALOR_ACCION,0) ELSE 0 END AS FTN_SDO_AIVS,
  CASE WHEN FTN_IND_SDO_DISP_VIV08 = 1 THEN FTN_MONTO_PESOS_08 / NULLIF(FCN_VALOR_ACCION,0) ELSE 0 END AS FTN_SDO_AIVS_92,
  CASE WHEN vMotivoRechazo IS NULL THEN FCN_VALOR_ACCION ELSE 0 END AS FTN_VALOR_AIVS,
  CAST(FTN_MONTO_PESOS AS DECIMAL(18,2)) AS FTN_MONTO_PESOS,
  CAST(FTN_MONTO_PESOS_08 AS DECIMAL(18,2)) AS FTN_MONTO_PESOS_92,
  CASE WHEN FTN_IND_SDO_DISP_VIV08 = 0 AND FTN_IND_SDO_DISP_VIV97 = 0 THEN 0 ELSE 1 END AS FCN_ESTATUS,
  CURRENT_TIMESTAMP AS FTD_FEH_CRE,
  'DATABRICKS' AS FTD_USU_CRE, -- Replace with actual job user parameter
  FTC_FOLIO_BITACORA,
  FCN_ID_REGIMEN,
  FCN_ID_TIPO_SUBCTA_97,
  FCN_ID_TIPO_SUBCTA_08 AS FCN_ID_TIPO_SUBCTA_92,
  FTN_SUBPROCESO AS FTN_ID_SUBP,
  FCN_ID_VALOR_ACCION,
  FTN_NO_LINEA AS FTN_CONTA_SERV,
  vMotivoRechazo AS FTN_MOTI_RECH,
  ValorSaldosSolPesos_FOV08 AS FTN_NUM_APLI_INTE_VIVI92_SOL,
  ValorSaldosSolPesos_VIV97 AS FTN_NUM_APLI_INTE_VIVI97_SOL,
  CASE WHEN FCN_ID_TIPO_SUBCTA_97 = 15 THEN vTotAivVIV97 ELSE vTotAivFov08 END AS FTN_TOTAL_AIVS_97,
  CASE WHEN FCN_ID_TIPO_SUBCTA_08 = 16 THEN vTotAivViv92 ELSE vTotAivFov92 END AS FTN_TOTAL_AIVS_08
FROM tf_505_totals
