SELECT
  FTN_NUM_CTA_INVDUAL,
  FTN_IND_SDO_DISP_VIV97,
  FTN_IND_SDO_DISP_VIV08 AS FTN_IND_SDO_DISP_92,
  CASE WHEN FTN_IND_SDO_DISP_VIV97 = 1 THEN FTN_MONTO_PESOS / NULLIF(FCN_VALOR_ACCION,0) ELSE 0 END AS FTN_SDO_AIVS,
  CASE WHEN FTN_IND_SDO_DISP_VIV08 = 1 THEN FTN_MONTO_PESOS_08 / NULLIF(FCN_VALOR_ACCION,0) ELSE 0 END AS FTN_SDO_AIVS_92,
CASE
  WHEN (
    CASE
      WHEN Diagnostico_97 IS NULL OR Diagnostico_08 IS NULL THEN COALESCE(Diagnostico_97, Diagnostico_08)
      WHEN Diagnostico_97 = Diagnostico_08 THEN Diagnostico_97
      WHEN Diagnostico_97 <> Diagnostico_08 THEN '101'
      ELSE '100'
    END
  ) <> '104'
  THEN FCN_VALOR_ACCION
  ELSE 0
END AS FTN_VALOR_AIVS,
  CAST(FTN_MONTO_PESOS AS DECIMAL(18,2)) AS FTN_MONTO_PESOS,
  CAST(FTN_MONTO_PESOS_08 AS DECIMAL(18,2)) AS FTN_MONTO_PESOS_92,
  CASE WHEN FTN_IND_SDO_DISP_VIV08 = 0 AND FTN_IND_SDO_DISP_VIV97 = 0 THEN 0 ELSE 1 END AS FCN_ESTATUS,
  CURRENT_TIMESTAMP AS FTD_FEH_CRE,
  'DATABRICKS' AS FTC_USU_CRE, -- Replace with actual job user parameter
  FTC_FOLIO_BITACORA,
  FCN_ID_REGIMEN,
  FCN_ID_TIPO_SUBCTA_97,
  FCN_ID_TIPO_SUBCTA_08 AS FCN_ID_TIPO_SUBCTA_92,
  FTN_SUBPROCESO AS FTN_ID_SUBP,
  FCN_ID_VALOR_ACCION,
  FTN_NO_LINEA AS FTN_CONTA_SERV,
  -- FTN_MOTI_RECH logic:
  CASE
    WHEN (
      CASE
        WHEN Diagnostico_97 IS NULL OR Diagnostico_08 IS NULL THEN
          COALESCE(Diagnostico_97, Diagnostico_08)
        WHEN Diagnostico_97 = Diagnostico_08 THEN Diagnostico_97
        WHEN Diagnostico_97 <> Diagnostico_08 THEN '101'
        ELSE '100'
      END
    ) = '104' THEN 104
    ELSE NULL
  END AS FTN_MOTI_RECH
FROM #FU_504_UNI_COMPLETA#