SELECT
    FTN_NUM_CTA_INVDUAL,
    FTN_SUBPROCESO,
    FTN_NO_LINEA,
FTN_MONTO_PESOS,
    -- ensure decimal result (12,2)
    CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN FTN_MONTO_PESOS
         ELSE CAST(0.00 AS NUMERIC(12,2))
    END AS ValorSaldosSolPesos_VIV97,

    CASE WHEN FTC_INSTITUTO_ORIGEN = '002' THEN FTN_MONTO_PESOS
         ELSE CAST(0.00 AS NUMERIC(12,2))
    END AS ValorSaldosSolPesos_FOV08,

    -- prefer parameters (shown as placeholders), fallback to explicit values if needed
    CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN CAST( 15 AS DECIMAL(4,0))
         WHEN FTC_INSTITUTO_ORIGEN = '002' THEN CAST(18  AS DECIMAL(4,0))
         ELSE NULL
    END AS FCN_ID_TIPO_SUBCTA_97,

    CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN CAST(16 AS DECIMAL(4,0))
         WHEN FTC_INSTITUTO_ORIGEN = '002' THEN CAST(17  AS DECIMAL(4,0))
         ELSE NULL
    END AS FCN_ID_TIPO_SUBCTA_08,

    FCN_ID_REGIMEN,
    FTC_INSTITUTO_ORIGEN
FROM #DS_300_TRANFERENCIAS#
WHERE
    (SALDO_DISPONIBLE_AIVS_VIV97 <= 0 OR FTN_MONTO_PESOS <= 0)
    AND
   (SALDO_DISPONIBLE_AIVS_VIV92 <= 0 OR FTN_MONTO_PESOS_92 <= 0)