SELECT  
  CASE WHEN FCN_ID_REGIMEN = 138 Then FCD_FEH_ACCION Else current_date end FCD_FEH_ACCION_97
, CASE WHEN FCN_ID_REGIMEN = 138 Then FCN_VALOR_ACCION Else 0 end FCN_VALOR_ACCION_97
, CASE WHEN FCN_ID_REGIMEN = 138 Then FCN_ID_VALOR_ACCION Else 0 end FCN_ID_VALOR_ACCION_97
, CASE WHEN FCN_ID_REGIMEN = 139 Then FCD_FEH_ACCION Else current_date end FCD_FEH_ACCION_08
, CASE WHEN FCN_ID_REGIMEN = 139 Then TRUNC(FCN_VALOR_ACCION,6) Else 0 end FCN_VALOR_ACCION_08
, CASE WHEN FCN_ID_REGIMEN = 139 Then FCN_ID_VALOR_ACCION Else 0 end FCN_ID_VALOR_ACCION_08
,ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1) FECHA_VALOR_AIVS
,FCN_ID_REGIMEN
from CIERREN.TCAFOGRAL_VALOR_ACCION 
WHERE FCN_ID_SIEFORE = 81
AND FCN_ID_REGIMEN in (138, 139)
AND FCD_FEH_ACCION = ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1)
