WITH
-- Step 1: Filtered base records from DS_300_TRANFERENCIAS
base AS (
  SELECT
    FTN_NUM_CTA_INVDUAL,
    FTN_SUBPROCESO,
    FTC_INSTITUTO_ORIGEN,
    FECHA_VALOR_AIVS,
    FTC_NSS_IMSS,
    FTN_MONTO_PESOS,
    FTN_TOTAL_AIVS,
    FTN_AIVS,
    SALDO_DISPONIBLE_AIVS_VIV97,
    SALDO_DISPONIBLE_AIVS_VIV92,
    FTN_NO_LINEA,
    FCN_ID_REGIMEN,
    FCN_ID_TIPO_SUBCTA_92,
    FTN_MONTO_PESOS_92,
    FTN_TOTAL_AIVS_92
  FROM #DS_300_TRANFERENCIAS#
  WHERE
    (SALDO_DISPONIBLE_AIVS_VIV97 > 0 AND FTN_MONTO_PESOS > 0)
    OR
    (SALDO_DISPONIBLE_AIVS_VIV92 > 0 AND FTN_MONTO_PESOS_92 > 0)
),

-- Step 2: Count how many accounts per NSS
agg AS (
  SELECT
    FTC_NSS_IMSS,
    COUNT(FTN_NUM_CTA_INVDUAL) AS CONTEO
  FROM base
  GROUP BY FTC_NSS_IMSS
),

-- Step 3: Join CONTEO to each row
joined AS (
  SELECT
    b.*,
    a.CONTEO
  FROM base b
  LEFT JOIN agg a ON b.FTC_NSS_IMSS = a.FTC_NSS_IMSS
),

-- Step 4: Lookup value action from Oracle table
valor_accion AS (
  SELECT
    *
  FROM #DS_500_VALOR_ACCION#
  
),

-- Step 5: Attach value action to each row
enriched AS (
  SELECT
    j.*,
    va.FCN_VALOR_ACCION_97,
    va.FCN_VALOR_ACCION_08,
    va.FCN_ID_VALOR_ACCION_97,
    va.FCN_ID_VALOR_ACCION_08
  FROM joined j
  LEFT JOIN valor_accion va
    ON j.FECHA_VALOR_AIVS = va.FECHA_VALOR_AIVS
    AND j.FCN_ID_REGIMEN = va.FCN_ID_REGIMEN
)

-- Step 6: Final transformation for DS_500_NSS_VAR (only CONTEO > 1)
SELECT
  FTN_NUM_CTA_INVDUAL,
  FTN_SUBPROCESO,
  FECHA_VALOR_AIVS,
  FTN_NO_LINEA,
  FTC_NSS_IMSS,

  -- FTN_NUM_APLI_INTE_VIVI08_SOL
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN FTN_AIVS ELSE 0 END AS FTN_NUM_APLI_INTE_VIVI08_SOL,

  -- FTN_NUM_APLI_INTE_VIVI97_SOL
  CASE WHEN FTC_INSTITUTO_ORIGEN = '002' THEN FTN_AIVS ELSE 0 END AS FTN_NUM_APLI_INTE_VIVI97_SOL,

  -- SALDO_DISPONIBLE_AIVS_VIV97
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN SALDO_DISPONIBLE_AIVS_VIV97 ELSE SALDO_DISPONIBLE_AIVS_VIV97 END AS SALDO_DISPONIBLE_AIVS_VIV97,

  -- SALDO_DISPONIBLE_AIVS_VIV08
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN SALDO_DISPONIBLE_AIVS_VIV92 ELSE SALDO_DISPONIBLE_AIVS_VIV92 END AS SALDO_DISPONIBLE_AIVS_VIV08,

  CONTEO,

  -- FCN_VALOR_ACCION
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN FCN_VALOR_ACCION_97 ELSE FCN_VALOR_ACCION_08 END AS FCN_VALOR_ACCION,

  -- FCN_ID_VALOR_ACCION
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN FCN_ID_VALOR_ACCION_97 ELSE FCN_ID_VALOR_ACCION_08 END AS FCN_ID_VALOR_ACCION,

  -- FTC_FOLIO_BITACORA
  '#sr_folio#' AS FTC_FOLIO_BITACORA,

  -- FCN_ID_TIPO_SUBCTA_97
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN 15 ELSE 18 END AS FCN_ID_TIPO_SUBCTA_97,

  -- FCN_ID_TIPO_SUBCTA_08
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN 16 ELSE 17 END AS FCN_ID_TIPO_SUBCTA_08,

  -- ValorSaldosSolPesos_VIV97
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN FTN_MONTO_PESOS ELSE 0 END AS ValorSaldosSolPesos_VIV97,

  -- ValorSaldosSolPesos_VIV08
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN FTN_MONTO_PESOS_92 ELSE 0 END AS ValorSaldosSolPesos_VIV08,

  -- FTN_TOTAL_AIVS_97
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001' THEN FTN_TOTAL_AIVS ELSE 0 END AS FTN_TOTAL_AIVS_97,

  -- FTN_TOTAL_AIVS_08
  CASE WHEN FTC_INSTITUTO_ORIGEN = '002' THEN FTN_TOTAL_AIVS ELSE 0 END AS FTN_TOTAL_AIVS_08,

  -- ValorSaldosDisPesos_VIV97
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001'
    THEN SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_97,0)
    ELSE SALDO_DISPONIBLE_AIVS_VIV97 * COALESCE(FCN_VALOR_ACCION_08,0)
  END AS ValorSaldosDisPesos_VIV97,

  -- ValorSaldosDisPesos_VIV08
  CASE WHEN FTC_INSTITUTO_ORIGEN = '001'
    THEN SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_97,0)
    ELSE SALDO_DISPONIBLE_AIVS_VIV92 * COALESCE(FCN_VALOR_ACCION_08,0)
  END AS ValorSaldosDisPesos_VIV08,

  FCN_ID_REGIMEN,
  FTC_INSTITUTO_ORIGEN

FROM enriched
WHERE CONTEO > 1
