--UPDATE CIERREN.TTAFOGRAL_IND_CTA_INDV
 ------|| Consulta que genera la Informacion que se va a actualizar de los socios no vigentes   
    WITH
  BD_0100_TL_MARCA_DESMARCA_INFO
  AS
  (
 SELECT
   FTN_CTA_AFORE AS FTN_NUM_CTA_INVDUAL
FROM
   PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
    WHERE FTC_FOLIO_BITACORA = '#sr_folio#'
    AND FTN_ID_SUBP = 354 
    AND FTC_ESTA_REGI = '1'
   ),
   BD_0200_IND_CTA_INDV
   AS
   (
SELECT FCN_ID_IND_CTA_INDV,
       FTN_NUM_CTA_INVDUAL,
       FFN_ID_CONFIG_INDI,
       FCC_VALOR_IND
  FROM CIERREN.TTAFOGRAL_IND_CTA_INDV
 WHERE FFN_ID_CONFIG_INDI = 14 
   AND FCC_VALOR_IND in ('1','4')
   AND FTC_VIGENCIA = '1'
   ),
   INSERCION
   AS
   (
SELECT 
   BD_0200.FCN_ID_IND_CTA_INDV,
   BD_0100.FTN_NUM_CTA_INVDUAL,
   BD_0200.FFN_ID_CONFIG_INDI,
   BD_0200.FCC_VALOR_IND,
   (SELECT CAST(CURRENT_TIMESTAMP AT TIME ZONE 'America/Mexico_City' AS DATE) FROM DUAL) AS FTD_FEH_ACT,
   'DATABRICKS' AS FCC_USU_ACT
   FROM BD_0100_TL_MARCA_DESMARCA_INFO BD_0100
  LEFT JOIN  BD_0200_IND_CTA_INDV BD_0200 
  ON BD_0100.FTN_NUM_CTA_INVDUAL = BD_0200.FTN_NUM_CTA_INVDUAL
  )
  SELECT DISTINCT
  FCN_ID_IND_CTA_INDV,
  1 AS FTN_NUM_CTA_INVDUAL,
  FCC_VALOR_IND,
  '0' AS FTC_VIGENCIA,
  FTD_FEH_ACT,
  FCC_USU_ACT,
	'#sr_folio#' AS FTC_FOLIO
  FROM INSERCION
  WHERE (FCC_VALOR_IND <> '1')
