MERGE /*+ PARALLEL(8) */ INTO #CX_DTM_ESQUEMA#.#TL_DTM_CAT_CLIENTE# ori
USING (
    SELECT /*+ PARALLEL(8) */
        FTC_RFC,
        FTC_CURP,
        FTN_NSS,
        FTC_APELLIDO_PATER_BDNSAR,
        FTC_APELLIDO_MATER_BDNSAR,
        FTC_NOMBRE_BDNSAR,
        FTN_NUM_CTA_IND
    FROM #CX_DATAUX_ESQUEMA#.#TL_DTM_CAT_CLIENTE_AUX# aux
) aux
ON (ori.FTN_NUM_CTA_IND = aux.FTN_NUM_CTA_IND)
WHEN MATCHED THEN
    UPDATE SET
        ori.FTC_RFC = aux.FTC_RFC,
        ori.FTC_CURP = aux.FTC_CURP,
        ori.FTN_NSS = aux.FTN_NSS,
        ori.FTC_APELLIDO_PATER_BDNSAR = aux.FTC_APELLIDO_PATER_BDNSAR,
        ori.FTC_APELLIDO_MATER_BDNSAR = aux.FTC_APELLIDO_MATER_BDNSAR,
        ori.FTC_NOMBRE_BDNSAR = aux.FTC_NOMBRE_BDNSAR
WHEN NOT MATCHED THEN
    INSERT (
        FTC_RFC,
        FTC_CURP,
        FTN_NSS,
        FTC_APELLIDO_PATER_BDNSAR,
        FTC_APELLIDO_MATER_BDNSAR,
        FTC_NOMBRE_BDNSAR,
        FTN_NUM_CTA_IND
    )
    VALUES (
        aux.FTC_RFC,
        aux.FTC_CURP,
        aux.FTN_NSS,
        aux.FTC_APELLIDO_PATER_BDNSAR,
        aux.FTC_APELLIDO_MATER_BDNSAR,
        aux.FTC_NOMBRE_BDNSAR,
        aux.FTN_NUM_CTA_IND
    )
