SELECT
    FTC_RFC,
    FTC_CURP,
    FTC_NSS,
    FTC_APELLIDO_PATE_BDNSAR,
    FTC_APELLIDO_MATE_BDNSAR,
    FTC_NOMBRE_BDNSAR,
    FTN_NUM_CTA_INVDUAL
FROM #CX_PRO_ESQUEMA#.#TL_PRO_TRANS_FOV#
WHERE FTC_FOLIO = #SR_FOLIO#
    AND FTC_ESTATUS = 1
