SELECT
    FTC_RFC,
    FTC_CURP,
    FTC_NSS AS FTN_NSS,
    FTC_APELLIDO_PATE_BDNSAR AS FTC_APELLIDO_PATER_BDNSAR,
    FTC_APELLIDO_MATE_BDNSAR AS FTC_APELLIDO_MATER_BDNSAR,
    FTC_NOMBRE_BDNSAR,
    FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_IND
FROM #CATALOG_SCHEMA#.TEMP_PROCESOS_#SR_FOLIO#
