SELECT FTC_ID_SERVICIO
       ,FTC_ID_OPERACION
       ,FTC_TIPO_ENT_DES
       ,TO_DATE(FTD_FEH_PRESEN, 'yyyyMMdd') AS FTD_FEH_PRESEN
       ,FTN_TIPO_TRABAJADOR
       ,FTC_CURP
       ,FTC_ID_PROCESAR
       ,FTC_NSS_BDNSAR
       ,FTN_LINEA_CRE
       ,FTN_TIPO_MOV
       , CAST(CONCAT(SUBSTRING(FTN_NUM_APLI_INTE_VIVI92, 1, 9), '.', SUBSTRING(FTN_NUM_APLI_INTE_VIVI92, 10, 6)) AS DECIMAL(15, 6)) AS FTN_NUM_APLI_INTE_VIVI92
       , CAST(CONCAT(SUBSTRING(FTN_VAL_APLI_INTE_VIVI92, 1, 6), '.', SUBSTRING(FTN_VAL_APLI_INTE_VIVI92, 7, 14)) AS DECIMAL(20, 14)) AS FTN_VAL_APLI_INTE_VIVI92
       , CAST(CONCAT(SUBSTRING(FTN_SALDO_TOT_VIVI92, 1, 13), '.', SUBSTRING(FTN_SALDO_TOT_VIVI92, 14, 2)) AS DECIMAL(15, 2)) AS FTN_SALDO_TOT_VIVI92
       , CAST(CONCAT(SUBSTRING(FTN_NUM_APLI_INTE_VIVI08, 1, 9), '.', SUBSTRING(FTN_NUM_APLI_INTE_VIVI08, 10, 6)) AS DECIMAL(15, 6)) AS FTN_NUM_APLI_INTE_VIVI08
       , CAST(CONCAT(SUBSTRING(FTN_VAL_APLI_INTE_VIVI08, 1, 6), '.', SUBSTRING(FTN_VAL_APLI_INTE_VIVI08, 7, 14)) AS DECIMAL(20, 14)) AS FTN_VAL_APLI_INTE_VIVI08
       , CAST(CONCAT(SUBSTRING(FTN_SALDO_TOT_VIVI08, 1, 13), '.', SUBSTRING(FTN_SALDO_TOT_VIVI08, 14, 2)) AS DECIMAL(15, 2)) AS FTN_SALDO_TOT_VIVI08
       ,TO_DATE(FTD_FEH_LIQ, 'yyyyMMdd') AS FTD_FEH_LIQ
       ,TO_DATE(FTD_FEH_VALOR_VIVI, 'yyyyMMdd') AS FTD_FEH_VALOR_VIVI
       ,#sr_folio# FTC_FOLIO
       ,#sr_id_archivo# FTN_ID_ARCHIVO
       ,to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_CRE
       ,#sr_subproceso# as FCN_ID_SUBPROCESO
       ,'DATABRICKS' as FTC_USU_CRE
FROM #DELTA_TABLA_NAME1#
