SELECT Trim(SUBSTR(ENC.FTC_LINEA,3,2)) AS FTC_ID_SERVICIO,
       Trim(SUBSTR(ENC.FTC_LINEA,5,2)) AS FTC_ID_OPERACION,
       Trim(SUBSTR(ENC.FTC_LINEA,7,2)) AS FTC_TIPO_ENT_DES,
       Trim(SUBSTR(ENC.FTC_LINEA,20,8)) AS FTD_FEH_PRESEN,
       Trim(SUBSTR(DET.FTC_LINEA,3,1)) AS FTN_TIPO_TRABAJADOR,
       Trim(SUBSTR(DET.FTC_LINEA,4,18)) AS FTC_CURP,
       Trim(SUBSTR(DET.FTC_LINEA,22,8)) AS FTC_ID_PROCESAR,
       Trim(SUBSTR(DET.FTC_LINEA,30,11)) AS FTC_NSS_BDNSAR,
       Trim(SUBSTR(DET.FTC_LINEA,41,2)) AS FTN_LINEA_CRE,
       Trim(SUBSTR(DET.FTC_LINEA,43,1)) AS FTN_TIPO_MOV,
       Trim(SUBSTR(DET.FTC_LINEA,44,15)) AS FTN_NUM_APLI_INTE_VIVI92,
       Trim(SUBSTR(DET.FTC_LINEA,59,20)) AS FTN_VAL_APLI_INTE_VIVI92,
       Trim(SUBSTR(DET.FTC_LINEA,79,15)) AS FTN_SALDO_TOT_VIVI92,
       Trim(SUBSTR(DET.FTC_LINEA,94,15)) AS FTN_NUM_APLI_INTE_VIVI08,
       Trim(SUBSTR(DET.FTC_LINEA,109,20)) AS FTN_VAL_APLI_INTE_VIVI08,
       Trim(SUBSTR(DET.FTC_LINEA,129,15)) AS FTN_SALDO_TOT_VIVI08,
       Trim(SUBSTR(DET.FTC_LINEA,144,8)) AS FTD_FEH_LIQ,
       Trim(SUBSTR(DET.FTC_LINEA,144,8)) AS FTD_FEH_VALOR_VIVI
  FROM CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO ENC
  LEFT 
  JOIN CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO DET 
    ON ENC.FTN_ID_ARCHIVO=DET.FTN_ID_ARCHIVO
 WHERE ENC.FTN_ID_ARCHIVO = #sr_id_archivo#
   AND SUBSTR(ENC.FTC_LINEA,1,2) = 01
   AND SUBSTR(DET.FTC_LINEA,1,2) = 2.


