SELECT 
FTD_FEH_PRESEN,
FTC_CURP,
FTC_NSS_INFONA,
FTN_CTA_AFORE,
FTC_RFC_INFONA,
FTC_IDENTI_LOTE_SOLIC,
FTC_NSS_AFORE,
FTC_RFC_AFORE,
FTN_SALDO_97,
FTN_SALDO_92,
FTN_NUM_CRED_INFONA,
FTN_INTERES_SALDO_97,
FTN_INTERES_SALDO_92,
FTN_PERIODO_PAGO, 
FTD_FEH_CARGA,
FTC_FOLIO_BITACORA,
FTC_IDENT_PROC_DESMA,
FTC_IDENT_CTA_VIGENTE,
FTC_ESTA_REGI,
FTD_FEH_ACT AS FTD_FEH_ACT_1,
FTN_ID_SUBP,
FTD_FEH_CRE,
FCC_USU_CRE,
FTN_MOTI_RECH
FROM #CX_PRO_ESQUEMA#.#TL_PRO_MARCA_DESMARCA_INFO#
WHERE FTC_FOLIO_BITACORA = #SR_FOLIO#
AND FTN_ID_SUBP = #SR_SUBPROCESO#

