SELECT
  CASE WHEN FTN_IND_SDO_DISP_VIV92 = 0 AND FTN_IND_SDO_DISP_VIV08 = 0
       THEN 001
       ELSE NULL
  END AS FTN_MOTIVO_RECHAZO,

  FTN_NUM_CTA_INVDUAL,
  #sr_folio# AS FTC_FOLIO,
  FTN_CONTA_SERV,

  CASE WHEN
    (CASE WHEN FTN_IND_SDO_DISP_VIV92 = 0 AND FTN_IND_SDO_DISP_VIV08 = 0
          THEN 001 ELSE NULL END) IS NULL
    THEN '1' ELSE '0'
  END AS FTC_ESTATUS,

  CASE
    WHEN FTC_DIAG_PROCESO08 = 003 AND FTC_DIAG_PROCESO92 = 002
      THEN '004'
    WHEN FTC_DIAG_PROCESO08 = 003 AND FTC_DIAG_PROCESO92 IS NULL
      THEN '003'
    WHEN FTC_DIAG_PROCESO92 = 002 AND FTC_DIAG_PROCESO08 IS NULL
      THEN '002'
    ELSE NULL
  END AS FTC_DIAG_PROCESO,

  to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_ACT,
  'DATABRICKS' AS FCC_USU_ACT,
  FTN_NUM_APLI_INTE_VIVI08_APL,
  FTN_NUM_APLI_INTE_VIVI92_APL,
  FTN_NUM_APLI_INTE_VIVI08_APL * FCN_VALOR_ACCION AS FTN_SALDO_TOT_VIVI08_APL,
  FTN_NUM_APLI_INTE_VIVI92_APL * FCN_VALOR_ACCION AS FTN_SALDO_TOT_VIVI92_APL

FROM #DELTA_TABLE_BD_600_TRANS_FOV_363#