MERGE INTO PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE TGT
USING (
    SELECT DISTINCT
        FTN_MOTIVO_RECHAZO,
        FTN_NUM_CTA_INVDUAL,
        FTC_FOLIO,
        FTN_CONTA_SERV,
        FTC_ESTATUS,
        FTC_DIAG_PROCESO,
        FTD_FEH_ACT,
        FCC_USU_ACT,
        FTN_NUM_APLI_INTE_VIVI08_APL,
        FTN_NUM_APLI_INTE_VIVI92_APL,
        FTN_SALDO_TOT_VIVI08_APL,
        FTN_SALDO_TOT_VIVI92_APL
    FROM CIERREN_DATAUX.TTAFOTRAS_TRANS_FOVISSSTE_AUX
    WHERE FTC_FOLIO = '#SR_FOLIO#'  -- Replace or remove as needed
) SRC
ON (
    TGT.FTC_FOLIO = SRC.FTC_FOLIO
    AND TGT.FTN_NUM_CTA_INVDUAL = SRC.FTN_NUM_CTA_INVDUAL
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTN_MOTIVO_RECHAZO           = SRC.FTN_MOTIVO_RECHAZO,
        TGT.FTN_CONTA_SERV               = SRC.FTN_CONTA_SERV,
        TGT.FTC_ESTATUS                  = SRC.FTC_ESTATUS,
        TGT.FTC_DIAG_PROCESO             = SRC.FTC_DIAG_PROCESO,
        TGT.FTD_FEH_ACT                  = SYSDATE,
        TGT.FCC_USU_ACT                  = 'DATABRICKS',
        TGT.FTN_NUM_APLI_INTE_VIVI08_APL = SRC.FTN_NUM_APLI_INTE_VIVI08_APL,
        TGT.FTN_NUM_APLI_INTE_VIVI92_APL = SRC.FTN_NUM_APLI_INTE_VIVI92_APL,
        TGT.FTN_SALDO_TOT_VIVI08_APL    = SRC.FTN_SALDO_TOT_VIVI08_APL,
        TGT.FTN_SALDO_TOT_VIVI92_APL    = SRC.FTN_SALDO_TOT_VIVI92_APL