MERGE INTO CIERREN.TTAFOGRAL_IND_CTA_INDV TGT
USING (
    SELECT DISTINCT
        FCN_ID_IND_CTA_INDV
				,FTN_NUM_CTA_INVDUAL
				,FCC_VALOR_IND 
				,FTD_FEH_ACT
				,FCC_USU_ACT
				,FTC_FOLIO
    FROM CIERREN_DATAUX.TTAFOGRAL_ETL_IND_CTA_INDV_AUX
    WHERE FTC_FOLIO = '#sr_folio#'
) SRC
ON (
    TGT.FCN_ID_IND_CTA_INDV = SRC.FCN_ID_IND_CTA_INDV
		AND TGT.FTN_NUM_CTA_INVDUAL = SRC.FTN_NUM_CTA_INVDUAL
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FCC_VALOR_IND = SRC.FCC_VALOR_IND,
        TGT.FTD_FEH_ACT = SRC.FTD_FEH_ACT,
        TGT.FCC_USU_ACT = SRC.FCC_USU_ACT