WITH IND_CTA_INDV AS (
SELECT FCN_ID_IND_CTA_INDV,
       FTN_NUM_CTA_INVDUAL,
       FFN_ID_CONFIG_INDI,
       FCC_VALOR_IND
  FROM CIERREN.TTAFOGRAL_IND_CTA_INDV
 WHERE FFN_ID_CONFIG_INDI = 15
   AND FTC_VIGENCIA = '1'
)
SELECT 
	CI.FCN_ID_IND_CTA_INDV
	,DF.FTN_NUM_CTA_INVDUAL
	,(CASE
	    WHEN CI.FCC_VALOR_IND = '1' THEN '0'
	    ELSE CI.FCC_VALOR_IND
	  END
		) AS FCC_VALOR_IND 
	,CURRENT_TIMESTAMP AS FTD_FEH_ACT
	,'DATABRICKS' AS FCC_USU_ACT
	,FTC_FOLIO
FROM 
	PROCESOS.TTAFOTRAS_DESMARCA_FOVST DF
LEFT JOIN 
	IND_CTA_INDV CI
ON
	CI.FTN_NUM_CTA_INVDUAL = DF.FTN_NUM_CTA_INVDUAL
WHERE 
	FTC_FOLIO = '#sr_folio#'
	AND FCN_ID_SUBPROCESO = '#sr_subproceso#' 
	AND FTC_ESTATUS = 1
	AND (FCC_VALOR_IND IS NULL OR FCC_VALOR_IND=1 Or FCC_VALOR_IND=0)
   