SELECT
  '02' AS ID_SERVICIO,
  '56' AS ID_OPERACION,
  '01' AS TIPO_ENT_ORIGEN,
  '534' AS CVE_ENT_ORIGEN,
  '03' AS TIPO_ENT_DESTINO,
  '001' AS CVE_ENT_DESTINO,
  FECHA_PRESENTACION AS FECHA_PROCESO,
  RPAD('0', 2, '0') AS RESULTADO_OPERA,
  RPAD('0', 3, '0') AS MOTIVO_RECHAZO,
  RPAD(' ', 621, ' ') AS FILLER
FROM
  (
    SELECT
      TO_CHAR(MAX(FTN_ANIO)) || LPAD(TO_CHAR(MAX(FTN_MES)), 2, '0')
      || TO_CHAR(MAX(FTN_DIA)) AS FECHA_PRESENTACION,
      TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE, 'MONTH'), 1), 'YYYYMMDD') FECHA_POSTERIOR
    FROM
      (
        SELECT
          FTN_ANIO,
          FTN_MES,
          FTN_DIA,
          FTN_DIA_HABIL,
          FTC_DIA_NOMBRE
        FROM
          PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE
          FTN_MES = SUBSTR(TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 6, 2)
          AND FTN_ANIO = SUBSTR(TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 1, 4)
          AND FTN_DIA_HABIL = 1
        ORDER BY
          FTN_ANIO,
          FTN_MES,
          FTN_DIA
      )
    WHERE
      ROWNUM <= 15
    GROUP BY
      TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE, 'MONTH'), 1), 'YYYYMMDD')
  )
  