SELECT
  VAL_SALD.FTC_FOLIO_BITACORA AS FTC_FOLIO
 ,97 AS FTN_ID_PROCESO
 ,VAL_SALD.FTN_ID_SUBP AS FTN_ID_SUBPROCESO
 ,VAL_SALD.FTN_NUM_CTA_INVDUAL
 ,COALESCE(VAL_SALD.FCN_ID_SIEFORE,M.FCN_ID_SIEFORE,81) as FTN_ID_SIEFORE
,COALESCE(VAL_SALD.FCN_ID_TIPO_SUBCTA,M.FCN_ID_TIPO_SUBCTA) AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,VAL_SALD.FTN_MONTO_ACCIONES as FTN_MONTO_ACCIONES
,VAL_SALD.FTN_MONTO_PESOS AS  FTN_MONTO_PESOS
,VAL_SALD.FCN_ID_VALOR_ACCION AS FTN_ID_VALOR_ACCION 
,M.FCN_ID_TIPO_MONTO AS FTN_ID_TIPO_MONTO
,CS.FCN_ID_SALDO_OPERA AS FTN_ID_SALDO_OPERA
,M.FCN_ID_TIPO_MOV AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT

FROM (

SELECT
FTC_FOLIO_BITACORA
,FCN_ID_SIEFORE
,FTN_NUM_CTA_INVDUAL 
,FTN_ID_SUBP
,TIPO_MOV
,SALD.FCN_ID_TIPO_SUBCTA
,FRN_ID_MOV_SUBCTA
,INDICADOR
,SUM(FTN_MONTO_PESOS) AS FTN_MONTO_PESOS
,SUM(FTN_MONTO_ACCIONES) AS FTN_MONTO_ACCIONES
,FCN_ID_VALOR_ACCION

FROM(
select distinct
A.FTC_FOLIO_BITACORA
,A.FCN_ID_SIEFORE
,A.FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL 
,A.FTN_ID_SUBP 
,25 AS TIPO_MOV
,X.FTN_IND_SDO_DISP_VIV97 AS INDICADOR
,X.FCN_ID_TIPO_SUBCTA_97 AS FCN_ID_TIPO_SUBCTA
,X.FTN_MONTO_PESOS AS  FTN_MONTO_PESOS
,X.FTN_SDO_AIVS AS FTN_MONTO_ACCIONES
,X.FCN_ID_VALOR_ACCION
from  PROCESOS.TTCRXGRAL_TRANS_INFONA A
LEFT OUTER JOIN  PROCESOS.TTSISGRAL_SUF_SALDOS X
ON A.FTC_FOLIO_BITACORA=X.FTC_FOLIO_BITACORA
AND A.FTN_NUM_CTA_AFORE=X.FTN_NUM_CTA_INVDUAL
AND A.FTN_CONTA_SERV=X.FTN_CONTA_SERV
where
A.FTC_FOLIO_BITACORA=#sr_folio#
and  A.FTN_ID_SUBP=#sr_subproceso#

UNION ALL

select DISTINCT
A.FTC_FOLIO_BITACORA
,A.FCN_ID_SIEFORE
,A.FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL 
,A.FTN_ID_SUBP 
,25 AS TIPO_MOV
,X.FTN_IND_SDO_DISP_92 AS INDICADOR
,X.FCN_ID_TIPO_SUBCTA_92 AS FCN_ID_TIPO_SUBCTA
,X.FTN_MONTO_PESOS_92 
,X.FTN_SDO_AIVS_92
,X.FCN_ID_VALOR_ACCION
from  PROCESOS.TTCRXGRAL_TRANS_INFONA A
LEFT OUTER JOIN  PROCESOS.TTSISGRAL_SUF_SALDOS X
ON A.FTC_FOLIO_BITACORA=X.FTC_FOLIO_BITACORA
AND A.FTN_NUM_CTA_AFORE=X.FTN_NUM_CTA_INVDUAL
AND A.FTN_CONTA_SERV=X.FTN_CONTA_SERV

where
A.FTC_FOLIO_BITACORA=#sr_folio#
and  A.FTN_ID_SUBP=#sr_subproceso#
)SALD 
LEFT OUTER JOIN(
 SELECT  
         FRN_ID_MOV_SUBCTA,
         FCN_ID_TIPO_SUBCTA,
         FCN_ID_SUBPROCESO 
     FROM  
         CIERREN.TRAFOGRAL_MOV_SUBCTA 
     WHERE 
      FCN_ID_TIPO_MOV = 180
)MOVSUB
 ON MOVSUB.FCN_ID_TIPO_SUBCTA = SALD.FCN_ID_TIPO_SUBCTA
     AND MOVSUB.FCN_ID_SUBPROCESO = SALD.FTN_ID_SUBP
WHERE INDICADOR=1
GROUP BY FTC_FOLIO_BITACORA
,FCN_ID_SIEFORE
,FTN_NUM_CTA_INVDUAL 
,FTN_ID_SUBP
,TIPO_MOV
,SALD.FCN_ID_TIPO_SUBCTA
,FRN_ID_MOV_SUBCTA
,INDICADOR
,FCN_ID_VALOR_ACCION

)VAL_SALD 
INNER JOIN(
SELECT  CMOV.FRN_ID_MOV_SUBCTA
       ,MSUB.FCN_ID_SUBPROCESO
       ,MSUB.FCN_ID_TIPO_SUBCTA
       ,MSUB.FCN_ID_TIPO_MOV
       ,CMOV.FFN_ID_CONCEPTO_MOV
       ,CMOV.FCN_ID_TIPO_MONTO
       ,CAT.FCN_ID_TIPO_CAT AS TIPO_MOV
       ,FCN_ID_REGIMEN
       ,FCN_ID_SIEFORE
FROM       CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CMOV
INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB ON CMOV.FRN_ID_MOV_SUBCTA = MSUB.FRN_ID_MOV_SUBCTA
INNER JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO CAT ON MSUB.FCN_ID_TIPO_MOV = CAT.FCN_ID_CAT_CATALOGO
INNER JOIN CIERREN.TCCRXGRAL_TIPO_CAT TCAT ON CAT.FCN_ID_TIPO_CAT = TCAT.FCN_ID_TIPO_CAT
INNER JOIN cierren.tccrxgral_tipo_subcta SUB ON  SUB.FCN_ID_TIPO_SUBCTA=MSUB.FCN_ID_TIPO_SUBCTA
LEFT OUTER JOIN (
SELECT 
FCN_ID_SIEFORE,
FCN_ID_GRUPO
FROM CIERREN.TCCRXGRAL_SIEFORE WHERE FCC_VIGENCIA=1
) SIEF ON SIEF.FCN_ID_GRUPO=MSUB.FCN_ID_GRUPO
WHERE  CMOV.FFB_VIGENCIA = 1
AND    MSUB.FRB_VIGENCIA = 1
AND    MSUB.FCN_ID_SUBPROCESO =#sr_subproceso#
AND    TCAT.FCN_ID_TIPO_CAT = 25
AND    TCAT.FCB_VIGENCIA = 1
AND    CAT.FCB_VIGENCIA = 1
AND    MSUB.FCN_ID_TIPO_SUBCTA in (15,16)
)M

ON VAL_SALD.FTN_ID_SUBP=M.FCN_ID_SUBPROCESO
AND VAL_SALD.TIPO_MOV=M.TIPO_MOV
AND VAL_SALD.FCN_ID_TIPO_SUBCTA=M.FCN_ID_TIPO_SUBCTA
     
LEFT OUTER JOIN CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA C 
ON  VAL_SALD.FTC_FOLIO_BITACORA=C.FTC_FOLIO
AND VAL_SALD.FRN_ID_MOV_SUBCTA=C.FRN_ID_MOV_SUBCTA

LEFT OUTER JOIN 
( SELECT FCN_ID_SALDO_OPERA, FCN_ID_SUBPROCESO
FROM CIERREN.TFAFOGRAL_CONFIG_SUBPROCESO CSUB
WHERE CSUB.FCN_ID_PROCESO = '97'
AND FCN_ID_SUBPROCESO =#sr_subproceso#) CS
ON  VAL_SALD.FTN_ID_SUBP =CS.FCN_ID_SUBPROCESO
WHERE (C.FTB_ESTATUS_MARCA=0 OR C.FTB_ESTATUS_MARCA is null)   
 ORDER BY FTN_NUM_CTA_INVDUAL
 
 
 
 

