SELECT  
Trim(SUBSTR(FTC_LINEA,25,8)) FTD_FEH_PRESEN,
Trim(SUBSTR(FTC_LINEA,41,18)) FTC_CURP,
Trim(SUBSTR(FTC_LINEA,59,11)) FTN_NSS_INFONA,
Trim(SUBSTR(FTC_LINEA,85,13)) FTC_RFC_INFONA,
Trim(SUBSTR(FTC_LINEA,98,40)) FTC_APELLIDO_PATER_INFONA,
Trim(SUBSTR(FTC_LINEA,138,40)) FTC_APELLIDO_MATER_INFONA,
Trim(SUBSTR(FTC_LINEA,178,40)) FTC_NOMBRE_INFONA,
to_number(Trim(SUBSTR(FTC_LINEA,240,16)))FTC_IDENTI_LOTE_SOLIC,
Trim(SUBSTR(FTC_LINEA,271,11)) FTN_NSS_AFORE,
Trim(SUBSTR(FTC_LINEA,282,13)) FTC_RFC_AFORE,
Trim(SUBSTR(FTC_LINEA,325,40)) FTC_APELLIDO_PATER_AFORE,
Trim(SUBSTR(FTC_LINEA,365,40)) FTC_APELLIDO_MATER_AFORE,
Trim(SUBSTR(FTC_LINEA,405,40) )FTC_NOMBRE_AFORE,
to_number(Trim(SUBSTR(FTC_LINEA,490,13))) FTN_SALDO_97,
to_number(Trim(SUBSTR(FTC_LINEA,565,13))) FTN_SALDO_92,
Trim(SUBSTR(FTC_LINEA,583,2)) FTN_CODIGO_RES_OPER,
Trim(SUBSTR(FTC_LINEA,585,15)) FTN_DIAGNOS_PROCE,
Trim(SUBSTR(FTC_LINEA,600,50)) FTC_NOMBRE_IMSS,
to_number(Trim(SUBSTR(FTC_LINEA,650,10))) FTN_NUM_CRED_INFONA,
to_number(Trim(SUBSTR(FTC_LINEA,660,13))) FTN_INTERES_SALDO_97,
to_number(Trim(SUBSTR(FTC_LINEA,675,13))) FTN_INTERES_SALDO_92,
to_number(Trim(SUBSTR(FTC_LINEA,713,6))) FTN_PERIODO_PAGO,
to_number(Trim(SUBSTR(FTC_LINEA,3,10)))FTN_CONTA_SERV
FROM   CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO
WHERE  SUBSTR(FTC_LINEA,1,2) = 02 
AND    FTN_ID_ARCHIVO = #sr_id_archivo#