SELECT 
TO_DATE(FTD_FEH_PRESEN, 'yyyyMMdd') FTD_FEH_PRESEN
, FTC_CURP
, FTN_NSS_INFONA AS FTC_NSS_INFONA
, FTC_RFC_INFONA
, FTC_APELLIDO_PATER_INFONA
, FTC_APELLIDO_MATER_INFONA
, FTC_NOMBRE_INFONA
, FTC_IDENTI_LOTE_SOLIC
, FTN_NSS_AFORE AS FTC_NSS_AFORE
, FTC_RFC_AFORE
, FTC_APELLIDO_PATER_AFORE
, FTC_APELLIDO_MATER_AFORE
, FTC_NOMBRE_AFORE
, FTN_SALDO_97
, FTN_SALDO_92
, FTN_CODIGO_RES_OPER AS FTC_CODIGO_RES_OPER
, CAST(FTN_DIAGNOS_PROCE AS STRING) FTC_DIAGNOS_PROCE
, FTC_NOMBRE_IMSS
, FTN_NUM_CRED_INFONA
, FTN_INTERES_SALDO_97
, FTN_INTERES_SALDO_92
, FTN_PERIODO_PAGO
, to_date(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) FTD_FEH_CARGA
, #sr_folio# AS FTC_FOLIO_BITACORA
, #sr_id_archivo# AS FTN_ID_ARCHIVO
, to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_CRE
, 'DATABRICKS' AS FCC_USU_CRE
, CAST('#sr_tipo_archivo#' AS STRING) AS FTC_TIPO_ARCH
, FTN_CONTA_SERV
FROM #DELTA_TABLA_NAME1#