SELECT
  A.FTN_CONTA_SERV,
  A.FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL,
  A.FTC_TIPO_ARCH,
  A.FTC_ESTATUS_REGISTRO,
  A.FTC_FOLIO_BITACORA,
  NVL(A.FTN_INTER_SALDO_VIVI97_ULT,0) AS FTN_INTER_SALDO_VIVI97_ULT,
  NVL(A.FTN_INTER_SALDO_VIVI92,0) AS FTN_INTER_SALDO_VIVI92,
  B.FTN_IND_SDO_DISP_VIV97,
  B.FCN_ID_TIPO_SUBCTA_97,
  B.FTN_SDO_AIVS,
  B.FTN_MONTO_PESOS,
  B.FTN_IND_SDO_DISP_92,
  B.FCN_ID_TIPO_SUBCTA_92,
  B.FTN_SDO_AIVS_92,
  B.FTN_MONTO_PESOS_92,
  B.FTN_ID_SUBP
FROM PROCESOS.TTCRXGRAL_TRANS_INFONA A
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS B
  ON A.FTN_NUM_CTA_AFORE = B.FTN_NUM_CTA_INVDUAL
  AND A.FTN_CONTA_SERV = B.FTN_CONTA_SERV
  AND B.FTC_FOLIO_BITACORA = '#SR_FOLIO#'
  AND B.FTN_ID_SUBP = #SR_SUBPROCESO#
WHERE A.FTC_FOLIO_BITACORA = '#SR_FOLIO#'
  AND A.FTN_ID_SUBP = #SR_SUBPROCESO#
  AND FTC_TIPO_ARCH IN ('09','06') 
  AND A.FTN_NUM_CTA_AFORE IS NOT NULL

-- WITH trans_infona AS (
--     SELECT 
--         FTN_CONTA_SERV,
--         FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL,
--         FTC_TIPO_ARCH,
--         FTC_ESTATUS_REGISTRO,
--         FTC_FOLIO_BITACORA,
--         NVL(FTN_INTER_SALDO_VIVI97_ULT,0) AS FTN_INTER_SALDO_VIVI97_ULT,
--         NVL(FTN_INTER_SALDO_VIVI92,0) AS FTN_INTER_SALDO_VIVI92
--     FROM PROCESOS.TTCRXGRAL_TRANS_INFONA
--     WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'
--       AND FTN_ID_SUBP = #SR_SUBPROCESO#
--       AND FTC_TIPO_ARCH IN (09, 06)
--       AND FTN_NUM_CTA_AFORE IS NOT NULL
-- ),
-- suf_saldos AS (
--     SELECT
--         FTN_NUM_CTA_INVDUAL,
--         FTN_IND_SDO_DISP_VIV97,
--         FCN_ID_TIPO_SUBCTA_97,
--         FTN_SDO_AIVS,
--         FTN_MONTO_PESOS,
--         FTN_IND_SDO_DISP_92,
--         FCN_ID_TIPO_SUBCTA_92,
--         FTN_SDO_AIVS_92,
--         FTN_MONTO_PESOS_92,
--         FTN_CONTA_SERV,
--         FTN_ID_SUBP
--     FROM PROCESOS.TTSISGRAL_SUF_SALDOS
--     WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'
--       AND FTN_ID_SUBP = #SR_SUBPROCESO#
-- )
-- SELECT 
--     t2.FTN_CONTA_SERV,
--     t2.FTN_NUM_CTA_INVDUAL,
--     t2.FTC_TIPO_ARCH,
--     t2.FTC_ESTATUS_REGISTRO,
--     t2.FTC_FOLIO_BITACORA,
--     t2.FTN_INTER_SALDO_VIVI97_ULT,
--     t2.FTN_INTER_SALDO_VIVI92 AS FTN_INTER_SALDO,
--     t1.FTN_IND_SDO_DISP_VIV97,
--     t1.FCN_ID_TIPO_SUBCTA_97,
--     t1.FTN_SDO_AIVS,
--     t1.FTN_MONTO_PESOS,
--     t1.FTN_IND_SDO_DISP_92 AS Indicador_Saldo_Disp,
--     t1.FCN_ID_TIPO_SUBCTA_92 AS FCN_ID_TIPO_SUBCTA,
--     t1.FTN_SDO_AIVS_92 AS FTN_SDO_AIVS,
--     t1.FTN_MONTO_PESOS_92 AS FTN_MONTO_PESOS,
--     t1.FTN_ID_SUBP AS FTN_ID_SUBP
-- FROM trans_infona t2
-- LEFT JOIN suf_saldos t1
--   ON t2.FTN_NUM_CTA_INVDUAL = t1.FTN_NUM_CTA_INVDUAL
--  AND t2.FTN_CONTA_SERV = t1.FTN_CONTA_SERV


