SELECT 
    sub15.FTN_CONTA_SERV,
    sub15.FTN_NUM_CTA_INVDUAL,
    sub15.FTC_TIPO_ARCH,
    sub15.FTC_ESTATUS_REGISTRO,
    sub15.FTC_FOLIO_BITACORA,
    sub15.FTN_IND_SDO_DISP_97 AS Indicador_Saldo_Disp,
    sub15.FCN_ID_TIPO_SUBCTA_97 AS FCN_ID_TIPO_SUBCTA,
    sub15.FTN_SDO_AIVS AS FTN_SDO_AIVS,
    sub15.FTN_MONTO_PESOS AS FTN_MONTO_PESOS,
    sub15.FTN_INTER_SALDO_VIVI97_ULT AS FTN_INTER_SALDO,
    sub15.FTN_ID_SUBP AS FTN_ID_SUBP
FROM #DELTA_400_CTA_INDV# sub15
WHERE FCN_ID_TIPO_SUBCTA_97= 15 AND FTN_IND_SDO_DISP_VIV97 = 1


