SELECT A.FTC_FOLIO_BITACORA,
       NVL(A.COUNT_ESTATUS_REGISTRO,0) AS CONTEO_TOTAL,
       NVL(B.COUNT_ESTATUS_REGISTRO,0) AS CONTEO_RECHAZO
  FROM (
        SELECT FTC_FOLIO_BITACORA,
               Count(FTC_ESTATUS_REGISTRO) COUNT_ESTATUS_REGISTRO
          FROM PROCESOS.TTCRXGRAL_TRANS_INFONA
         WHERE FTC_FOLIO_BITACORA = #SR_FOLIO#
           AND FTN_ID_SUBP = #SR_SUBPROCESO#
      group by FTC_FOLIO_BITACORA
        ) A LEFT JOIN (
                       SELECT FTC_FOLIO_BITACORA,
                              Count(FTC_ESTATUS_REGISTRO) COUNT_ESTATUS_REGISTRO
                         FROM PROCESOS.TTCRXGRAL_TRANS_INFONA
                        WHERE FTC_FOLIO_BITACORA = #SR_FOLIO#
                          AND FTN_ID_SUBP = #SR_SUBPROCESO#
                          and FTC_ESTATUS_REGISTRO=0
                     group by FTC_FOLIO_BITACORA) B
           ON A.FTC_FOLIO_BITACORA=B.FTC_FOLIO_BITACORA
