SELECT
    FTC_FOLIO,
    FRN_ID_MOV_SUBCTA AS FFN_ID_CONCEPTO_IMP,
    SUM(CASE WHEN FTC_TIPO_ARCH = '09' THEN FTN_MONTO_PESOS_ACEP ELSE NULL END) AS FTN_IMPORTE_RECH_PESOS_PRO,
    SUM(CASE WHEN FTC_TIPO_ARCH = '09' THEN FTN_SDO_AIVS_ACEP ELSE NULL END) AS FTN_IMPORTE_RECH_AIVS_PRO,
    SUM(CASE WHEN FTC_TIPO_ARCH = '06' THEN FTN_INTER_SALDO ELSE NULL END) AS FTN_IMPORTE_ACT_PESOS_PRO,
    SUM(CASE WHEN FTC_TIPO_ARCH = '09' THEN FTN_NUM_REG_RECH_PRO ELSE NULL END) AS FTN_NUM_REG_RECH_PRO,
    SUM(CASE WHEN FTC_TIPO_ARCH = '06' THEN FTN_NUM_REG_ACT_PRO ELSE NULL END) AS FTN_NUM_REG_ACT_PRO,
    from_utc_timestamp(current_timestamp(), 'America/Mexico_City') AS FTD_FEH_ACT,
    '#SR_USER#' AS FTC_USU_ACT
FROM #DELTA_JOIN_400#
GROUP BY FTC_FOLIO, FRN_ID_MOV_SUBCTA
