SELECT DISTINCT
    #SR_FOLIO# AS FTC_FOLIO,
    #SR_PROCESO# AS FCN_ID_PROCESO,
    #SR_SUBPROCESO# AS FCN_ID_SUBPROCESO,
    t_cctrl.CONTEO_TOTAL AS FLN_TOTAL_REGISTROS,
    t_cctrl.CONTEO_TOTAL - t_cctrl.CONTEO_RECHAZO AS FLN_REG_ACEPTADOS,
    t_cctrl.CONTEO_RECHAZO AS FLN_REG_RECHAZADOS,
    --CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FLD_FEC_REG,
    from_utc_timestamp(current_timestamp(), 'America/Mexico_City') AS FLD_FEC_REG,
    '#SR_USER#' AS FLC_USU_REG
FROM #DELTA_200_TI_JOIN# t_cctrl
