-- NB_PATRIF_REVMOV_0200_DESM_NCI_001_MAP_NCI.sql
-- Propósito: Extraer mapeo de claves NCI a claves Integrity
-- Tipo: OCI (Oracle)

SELECT 
    A.TIPO_PROCESO, 
    B.TIPO_SUBPROCESO, 
    A.PROCESO, 
    B.SUBPROCESO
FROM 
(
    SELECT 
        TMN_CVE_ITGY AS TIPO_PROCESO,
        TMN_CVE_NCI AS PROCESO
    FROM #CX_CRN_ESQUEMA#.#MAP_NCI_ITGY#
    WHERE TMC_VIGENCIA = 1
        AND TMC_USO = #DES_PROCESO#
) A
JOIN 
(
    SELECT 
        TMN_CVE_ITGY AS TIPO_SUBPROCESO,
        TMN_CVE_NCI AS SUBPROCESO
    FROM #CX_CRN_ESQUEMA#.#MAP_NCI_ITGY#
    WHERE TMC_VIGENCIA = 1
        AND TMN_CVE_NCI = #SR_SUBPROCESO#
        AND TMC_USO = 'SUBPROCESOS'
) B
ON 1 = 1

