-- NB_PATRIF_REVMOV_0200_DESM_NCI_003_PREPARE_AUX.sql
-- Propósito: Preparar datos para insertar en tabla auxiliar
-- Tipo: Delta (Databricks)

SELECT DISTINCT
    FTN_ID_MARCA, --FTN_ID_MARCA
    '0' AS FTC_ESTATUS_MARCA, --FTB_ESTATUS_MARCA
    FROM_UTC_TIMESTAMP(CURRENT_TIMESTAMP(), 'America/Mexico_City') AS FTD_FECHA, --FTD_FEH_ACT
    '#SR_FOLIO#' AS FTC_FOLIO, --FTC_FOLIO
    FTN_NUM_CTA_INVDUAL
FROM #CATALOG_SCHEMA#.TEMP_TR500_CAMPOS_#SR_FOLIO#
WHERE FTN_ID_MARCA IS NOT NULL

