-- NB_PATRIF_RMOV_0100_EXT_TRANSF_001_EXTRACT.sql
-- Propósito: Extraer registros de transferencias INFONAVIT rechazados por procesar
-- Tipo: OCI (Oracle)

SELECT
    M.FTN_NUM_CTA_INVDUAL,
    T.FTC_FOLIO_BITACORA,
    T.FTN_NUM_CTA_AFORE,
    T.FTC_CURP_TRABA,
    T.FTC_NSS_TRABA_AFORE,
    T.FTN_ID_SUBP AS SUBPROCESO, 
    #SR_PROCESO# AS PROCESO,
    M.FTN_ID_MARCA,
    C.FCN_ID_IND_CTA_INDV
FROM #CX_PRO_ESQUEMA#.#TL_TRANS_INFONA# T
LEFT JOIN #CX_CRN_ESQUEMA#.#TL_MATRIZ_CONVIV# M 
    ON T.FTC_FOLIO_BITACORA = M.FTC_FOLIO 
    AND T.FTN_NUM_CTA_AFORE = M.FTN_NUM_CTA_INVDUAL
LEFT JOIN #CX_CRN_ESQUEMA#.#TL_IND_CTA_INDV# C 
    ON T.FTN_NUM_CTA_AFORE = C.FTN_NUM_CTA_INVDUAL 
    AND C.FFN_ID_CONFIG_INDI = 14 
    AND C.FTC_VIGENCIA = 1
WHERE T.FTC_FOLIO_BITACORA = #SR_FOLIO#
    AND T.FTN_ID_SUBP = #SR_SUBPROCESO#
    AND T.FTC_ESTATUS_REGISTRO = 0
    AND T.FTC_TIPO_ARCH = 09
    AND T.FTN_MOTIVO_RECHAZO = 99

