SELECT
    CASE WHEN FTC_NSS_TRABA_AFORE IS NULL THEN FTC_CURP_TRABA ELSE FTC_NSS_TRABA_AFORE END AS NSS_CURP,
    FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL,
    FTC_NOMBRE_AFORE,
    FTC_APELLIDO_PATE_AFORE,
    FTC_APELLIDO_MATE_AFORE,
    FTC_CORREO_ELEC,
    FTC_CELULAR,
    FTN_CONTA_SERV AS FNN_ID_REFERENCIA,
    CASE 
        WHEN FTC_CORREO_ELEC IS NULL AND FTC_CELULAR IS NULL THEN 0
        WHEN FTC_CORREO_ELEC IS NULL AND FTC_CELULAR IS NOT NULL THEN 45 
        ELSE 46 
    END AS FCN_ID_MEDIO_NOTIFICACION,
    FTC_FOLIO_BITACORA AS FTC_FOLIO,
    #SR_PROCESO# AS FCN_ID_PROCESO,
    FTN_ID_SUBP
FROM
    PROCESOS.TTCRXGRAL_TRANS_INFONA
WHERE
    FTC_FOLIO_BITACORA = #SR_FOLIO#
    AND FTN_ID_SUBP = #SR_SUBPROCESO#
    AND FTC_ESTATUS_REGISTRO = 1
    AND FTN_NUM_CTA_AFORE IS NOT NULL
