-- NB_PATRIF_MCO_0100_COMUNICACION_01_003_DELTA_JOIN.sql
-- Propósito: Realizar un join entre las tablas extraídas en Delta
-- Tipo: Delta (Databricks)

SELECT 
    a.NSS_CURP,
    a.FTN_NUM_CTA_INVDUAL,
    a.FTC_NOMBRE_AFORE,
    a.FTC_APELLIDO_PATE_AFORE,
    a.FTC_APELLIDO_MATE_AFORE,
    a.FTC_CORREO_ELEC,
    a.FTC_CELULAR,
    a.FNN_ID_REFERENCIA,
    b.SUBCTA AS FCN_ID_TIPO_SUBCTA,
    a.FTC_FOLIO,
    a.FCN_ID_PROCESO,
    a.FTN_ID_SUBP,
    a.FCN_ID_MEDIO_NOTIFICACION
FROM 
    #CATALOG_SCHEMA#.#TRANS_INFO_TABLE# a
INNER JOIN 
    #CATALOG_SCHEMA#.#SUF_SALDOS_TABLE# b
ON 
    a.FTN_NUM_CTA_INVDUAL = b.FTN_NUM_CTA_INVDUAL
    AND a.FNN_ID_REFERENCIA = b.FNN_ID_REFERENCIA
