-- NB_PATRIF_MCO_0100_COMUNICACION_01_002_OCI_SUF_SALDOS.sql
-- Propósito: Extraer información de Suficiencia de Saldos desde Oracle
-- Tipo: OCI (Oracle)

SELECT 
    FTN_NUM_CTA_INVDUAL,
    FCN_ID_TIPO_SUBCTA_97 AS SUBCTA,
    CASE WHEN FTN_CONTA_SERV IS NULL THEN 0 ELSE FTN_CONTA_SERV END AS FNN_ID_REFERENCIA
FROM
    PROCESOS.TTSISGRAL_SUF_SALDOS
WHERE
    FTC_FOLIO_BITACORA = #SR_FOLIO#
    AND FTN_ID_SUBP = #SR_SUBPROCESO#
    AND FTN_IND_SDO_DISP_VIV97 = 1
    AND FTN_NUM_CTA_INVDUAL IS NOT NULL
UNION
SELECT 
    FTN_NUM_CTA_INVDUAL,
    FCN_ID_TIPO_SUBCTA_92 AS SUBCTA,
    CASE WHEN FTN_CONTA_SERV IS NULL THEN 0 ELSE FTN_CONTA_SERV END AS FNN_ID_REFERENCIA
FROM
    PROCESOS.TTSISGRAL_SUF_SALDOS
WHERE
    FTC_FOLIO_BITACORA = #SR_FOLIO#
    AND FTN_ID_SUBP = #SR_SUBPROCESO#
    AND FTN_IND_SDO_DISP_92 = 1
    AND FTN_NUM_CTA_INVDUAL IS NOT NULL
