SELECT            
     COUNT(*) OVER (PARTITION BY MC.FTC_FOLIO) TOTAL
    ,MC.FTC_FOLIO
    ,MC.FTN_NUM_CTA_INVDUAL
    ,MC.FTN_ID_MARCA
    ,MD.FTC_NSS_AFORE AS FTC_NSS
    ,MD.FTC_CURP
    ,TO_CHAR(CURRENT_DATE,'YYYYMMDD') FECHA_ENVIO
   FROM
    #TABLE_01# MC INNER JOIN
    #TABLE_02# MD
    ON MC.FTN_NUM_CTA_INVDUAL = MD.FTN_CTA_AFORE
    AND MC.FTC_FOLIO = MD.FTC_FOLIO_BITACORA
    AND MC.FTC_FOLIO = '#SR_FOLIO#'