SELECT 
A.TOTAL
,B.FTC_FOLIO
,B.FTN_NUM_CTA_INVDUAL
,B.FTN_ID_MARCA
,B.FTC_NSS
,B.FTC_CURP
,B.FTC_TIPO_ARCH
,TO_CHAR(CURRENT_DATE,'YYYYMMDD') FECHA_ENVIO
FROM (
  SELECT 
    COUNT(DISTINCT (FTN_NUM_CTA_INVDUAL)) TOTAL
   ,FTC_FOLIO
  FROM #TABLE_01#
    WHERE FTC_FOLIO = '#SR_FOLIO#'
    AND FTB_ESTATUS_MARCA = 1
    GROUP BY FTC_FOLIO)
A LEFT JOIN
(   SELECT            
     MC.FTC_FOLIO
    ,MC.FTN_NUM_CTA_INVDUAL
    ,MC.FTN_ID_MARCA
    ,MD.FTC_NSS_AFORE AS FTC_NSS
    ,MD.FTC_CURP
    ,MD.FTC_TIPO_ARCH
   FROM
    #TABLE_01# MC INNER JOIN
    #TABLE_02# MD
    ON MC.FTN_NUM_CTA_INVDUAL = MD.FTN_CTA_AFORE
    AND MC.FTC_FOLIO = MD.FTC_FOLIO_BITACORA
    AND MC.FTC_FOLIO = '#SR_FOLIO#'
    AND FTB_ESTATUS_MARCA = 1)B
ON A.FTC_FOLIO = B.FTC_FOLIO
