SELECT            
     COUNT(*) OVER (PARTITION BY MC.FTC_FOLIO) TOTAL
    ,MC.FTC_FOLIO
    ,MC.FTN_NUM_CTA_INVDUAL
    ,MC.FTN_ID_MARCA
    ,MD.FTC_NSS_BDNSAR AS FTC_NSS
    ,MD.FTC_CURP
    ,TO_CHAR(CURRENT_DATE,'YYYYMMDD') FECHA_ENVIO
   FROM
    #TABLE_01# MC INNER JOIN
    #TABLE_07# MD
    ON MC.FTN_NUM_CTA_INVDUAL = MD.FTN_NUM_CTA_INVDUAL
    AND MC.FTC_FOLIO = MD.FTC_FOLIO
    AND MC.FTC_FOLIO = '#SR_FOLIO#'