    SELECT            
     COUNT(*) OVER (PARTITION BY MC.FTC_FOLIO) TOTAL
    ,MC.FTC_FOLIO
    ,MC.FTN_NUM_CTA_INVDUAL
    ,MC.FTN_ID_MARCA
    ,DSE.FTN_CTA_AFORE AS FTC_NSS
    ,DSE.FTC_CURP
    ,TO_CHAR(CURRENT_DATE,'YYYYMMDD') FECHA_ENVIO
   FROM
    #TABLE_01# MC INNER JOIN
    #TABLE_06# DSE
    ON MC.FTN_NUM_CTA_INVDUAL = DSE.FTN_CTA_AFORE
    AND MC.FTC_FOLIO = DSE.FTC_FOLIO
    AND MC.FTC_FOLIO = '#SR_FOLIO#'