 SELECT 
A.TOTAL
,B.FTC_FOLIO
,B.FTN_NUM_CTA_INVDUAL
,B.FTN_ID_MARCA
,B.FTC_NSS
,B.FTC_CURP  
,TO_CHAR(CURRENT_DATE,'YYYYMMDD') FECHA_ENVIO
FROM (
  SELECT 
    COUNT(DISTINCT (FTN_NUM_CTA_INVDUAL)) TOTAL
   ,FTC_FOLIO
  FROM #TABLE_01#
    WHERE FTC_FOLIO = '#SR_FOLIO#'
     AND FTB_ESTATUS_MARCA = 1
    GROUP BY FTC_FOLIO)
A LEFT JOIN
(   SELECT            
     MC.FTC_FOLIO
    ,MC.FTN_NUM_CTA_INVDUAL
    ,MC.FTN_ID_MARCA
    ,TI.FTC_NSS
    ,TI.FTC_CURP
   FROM
    #TABLE_01# MC INNER JOIN
    #TABLE_04# TI
    ON MC.FTN_NUM_CTA_INVDUAL = TI.ftn_num_cta_invdual
    AND MC.FTC_FOLIO = TI.FTC_FOLIO
    AND MC.FTC_FOLIO = '#SR_FOLIO#'
    AND MC.FTB_ESTATUS_MARCA = 1)B
ON A.FTC_FOLIO = B.FTC_FOLIO