-- Query para generar EL DETALLE para archivo 69 desde tabla delta 
WITH RDK AS 
( 
SELECT 
  D.FTC_FOLIO,
  D.FTN_NUM_CTA_INVDUAL,
  NVL2(D.FTN_NUM_CTA_INVDUAL,LPAD(D.FTN_NUM_CTA_INVDUAL,10,'0'),'0000000000') AS FTN_NUM_CTA_INVDUAL_FMT, --10 POSICIONES
  LPAD(D.FTN_NUM_CTA_INVDUAL,10,'0') AS FTN_NUM_CTA_INVDUAL3,
  -- D.FCN_ID_PROCESO,
  -- D.FCN_ID_SUBPROCESO,
  D.FTC_NSS,
  NVL2(D.FTC_NSS,LPAD(D.FTC_NSS,11,'0'),'00000000000') AS FTC_NSS_FMT,  -- 11 POSICIONES
  D.FTC_CURP,
  NVL2(D.FTC_CURP,LPAD(D.FTC_CURP,18,'0'),'000000000000000000') AS FTC_CURP_FMT,  -- 18 POSICIONES
  SUB.TIPO_SUBPROCESO,
  NVL2(SUB.TIPO_SUBPROCESO,LPAD(SUB.TIPO_SUBPROCESO,4,'0'),'0000') AS TMN_CVE_ITGY_FMT,  -- 18 POSICIONES TIPOSUB
  PRO.TIPO_PROCESO,
  NVL2(PRO.TIPO_PROCESO,LPAD(PRO.TIPO_PROCESO,4,'0'),'0000') AS CVE_PROCESO_FMT,   -- 4 POSICIONES TIPO PRO
  LPAD(' ',79)   AS FILLER
  FROM #DELTA_TABLA_NAME1# D
  LEFT JOIN #DELTA_TABLA_SUB# SUB  
    ON  SUB.SUBPROCESO = #sr_subproceso#
  LEFT JOIN #DELTA_TABLA_PRO# PRO
    ON PRO.PROCESO = #sr_proceso#
  ORDER BY  D.FTN_NUM_CTA_INVDUAL
)
SELECT DISTINCT
2 AS POSICION,
CONCAT(
  '02' 
  ,RDK.FTN_NUM_CTA_INVDUAL_FMT
  ,RDK.CVE_PROCESO_FMT
  ,RDK.TMN_CVE_ITGY_FMT
  ,RDK.FTC_NSS_FMT
  ,RDK.FTC_CURP_FMT
  ,RDK.FILLER
  ) AS DETALLE
 -- ,RDK.* 
  FROM RDK
-- WHERE RN = 1
