-- MERGE
MERGE INTO CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA M
USING (
	SELECT FTC_FOLIO, 
	FTN_NUM_CTA_INVDUAL, 
	FTN_ID_MARCA,
	FTC_ESTATUS_MARCA 
	FROM CIERREN_DATAUX.TTAFOGRAL_ETL_MATRIZ_CONVIVENCIA_AUX
	WHERE FTC_FOLIO =  '#SR_FOLIO#') MAUX
ON (M.FTC_FOLIO = MAUX.FTC_FOLIO
	AND M.FTN_NUM_CTA_INVDUAL = MAUX.FTN_NUM_CTA_INVDUAL
	AND M.FTN_ID_MARCA = MAUX.FTN_ID_MARCA
    )
WHEN MATCHED THEN
	UPDATE SET
    M.FTB_ESTATUS_MARCA = MAUX.FTC_ESTATUS_MARCA,
		M.FTD_FEH_ACT = SYSDATE,
		M.FCC_USU_ACT = '#SR_USUARIO#'