-- Query INFO_PARA_DESMARCA_TIPO_SUB_PROCESO
SELECT 
TMN_CVE_ITGY AS TIPO_SUBPROCESO,
TMN_CVE_NCI AS SUBPROCESO
FROM CIERREN.TMSISGRAL_MAP_NCI_ITGY
WHERE TMC_VIGENCIA=1
AND TMN_CVE_NCI = #P_SR_SUBPROCESO# 
AND TMC_USO = 'SUBPROCESOS'