-- Query INFO_PARA_DESMARCA_TIPO_PROCESO
SELECT 
TMN_CVE_ITGY AS TIPO_PROCESO,
TMN_CVE_NCI AS PROCESO
FROM CIERREN.TMSISGRAL_MAP_NCI_ITGY
WHERE TMC_VIGENCIA=1
AND TMN_CVE_NCI = #SR_PROCESO#
AND TMC_USO = '#DES_PROCESO#'