SELECT     
DISTINCT
MAT.FTC_FOLIO,     
MAT.FTN_NUM_CTA_INVDUAL,     
MAT.FTN_ID_MARCA,     
0 AS FTC_ESTATUS_MARCA,     
'DATABRICKS' AS FCC_USU_ACT    
FROM CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA MAT
WHERE  (FTC_FOLIO = '#SR_FOLIO#' OR FTC_FOLIO_REL = '#SR_FOLIO#')
