-- MEhttps://adb-3494755435873649.9.azuredatabricks.net/editor/files/4094549815787994?o=3494755435873649$0RGE
MERGE INTO CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV M
USING (
    SELECT 
        FTC_FOLIO, 
        FTN_NUM_CTA_INVDUAL, 
        FTN_ID_MARCA,
        FCN_ID_TIPO_SUBCTA,
        FTC_ESTATUS_MARCA
    FROM CIERREN_DATAUX.TLSISGRAL_ETL_VAL_MATRIZ_CONV_AUX
    WHERE FTC_FOLIO = '#SR_FOLIO#'
) MAUX
ON (
    M.FTC_FOLIO = MAUX.FTC_FOLIO
    AND M.FTN_NUM_CTA_INVDUAL = MAUX.FTN_NUM_CTA_INVDUAL
    AND M.FTN_ID_MARCA = MAUX.FTN_ID_MARCA
    AND M.FCN_ID_TIPO_SUBCTA = MAUX.FCN_ID_TIPO_SUBCTA
)
WHEN MATCHED THEN
    UPDATE SET
        M.FTB_ESTATUS_MARCA = MAUX.FTC_ESTATUS_MARCA
        --M.FTD_FEH_ACT = SYSDATE
