-- Query para extraer informacion de los registros no desmarcados
WITH RID AS 
( 
SELECT
    '#SR_FOLIO#' AS FTC_FOLIO,
    SUBSTRING(D.FTC_LINEA,1,2) AS TIPO_REG,  -- VARIABLE DS   
    SUBSTRING(D.FTC_LINEA,63,8) AS FECHAMARCA,   -- VARIABLES DS
    SUBSTRING(D.FTC_LINEA,71,8) AS FECHADESMARCA,  -- VARIABLES DS
        CASE WHEN (
        SUBSTRING(D.FTC_LINEA,1,2) = '02'  AND 
        SUBSTRING(D.FTC_LINEA,50,1) = '0') 
          THEN '1' ELSE '0' END AS SINDESMARCAR, -- VARIABLES DS
    SUBSTRING(D.FTC_LINEA,3,10) AS FTN_NUM_CTA_INVDUAL,
    SUBSTRING(D.FTC_LINEA,21,11) AS FTC_NSS,
    SUBSTRING(D.FTC_LINEA,32,18) AS FTC_CURP,
    #SR_PROCESO# AS FTN_ID_PROCESO,
    #SR_SUBPROCESO# AS FTN_ID_SUBPROCESO,
    SUBSTRING(D.FTC_LINEA,13,4) AS FCN_ID_PROCESO,
    SUBSTRING(D.FTC_LINEA,17,4) AS FCN_ID_SUBPROCESO,
    SUBSTRING(D.FTC_LINEA,59,2) AS FHC_ESTADO_AFIL_INI,
    SUBSTRING(D.FTC_LINEA,63,8) AS FHD_FEH_MARCA 
  FROM #DELTA_TABLA_NAME1# D
)
SELECT 
  RID.FTN_NUM_CTA_INVDUAL,
  RID.FTC_NSS,
  RID.FTC_CURP,
  RID.FCN_ID_PROCESO,
  RID.FCN_ID_SUBPROCESO,
  RID.FHC_ESTADO_AFIL_INI,
  RID.FHD_FEH_MARCA
  -- RID.SINDESMARCAR
 FROM RID
WHERE 
  RID.TIPO_REG IN ('02') AND RID.SINDESMARCAR = '1'
