SELECT 
  A.TOTAL,
  B.FTC_FOLIO,
  B.FTN_NUM_CTA_INVDUAL,
  B.FTN_ID_MARCA,
  B.FTC_NSS,
  B.FTC_CURP,
  TO_CHAR(CURRENT_DATE, 'YYYYMMDD') AS FECHA_ENVIO
FROM (
  SELECT 
    COUNT(DISTINCT FTN_NUM_CTA_INVDUAL) AS TOTAL,
    FTC_FOLIO
  FROM CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA
  WHERE FTC_FOLIO = '#SR_FOLIO#'
    AND FTB_ESTATUS_MARCA = 1
  GROUP BY FTC_FOLIO
) A
LEFT JOIN (
  SELECT            
    MC.FTC_FOLIO,
    MC.FTN_NUM_CTA_INVDUAL,
    MC.FTN_ID_MARCA,
    BUC.FTC_NSS,
    BUC.FTC_CURP
  FROM CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA MC
  INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC BUC
    ON MC.FTN_NUM_CTA_INVDUAL = BUC.FTN_NUM_CTA_INVDUAL
  WHERE MC.FTC_FOLIO = '#SR_FOLIO#'
    AND MC.FTB_ESTATUS_MARCA = 1
) B
ON A.FTC_FOLIO = B.FTC_FOLIO

