-- Merge para la tabla de respuesta de integTTAFOGRAL_RESPUESTA_ITGY$0rity, solo debe de actualizar registros 
-- MERGE PARA UPDATE 
MERGE INTO PROCESOS.TTAFOGRAL_RESPUESTA_ITGY RI
USING (
SELECT
	FTC_FOLIO              
	,FTN_ID_PROCESO         
	,FTN_ID_SUBPROCESO      
	,FTN_REGISTROS_ENVIADOS 
	,FTN_REGISTROS_RECIBIDOS
	,FTN_ID_ESTATUS           
FROM CIERREN_DATAUX.TTAFOGRAL_RESPUESTA_ITGY_AUX
WHERE FTC_FOLIO =  '#SR_FOLIO#'   
AND FTN_ID_ESTATUS = 3880  -- SOLO REGISTROS NUEVOS 
	)  RIAUX
ON 
	(RI.FTC_FOLIO = RIAUX.FTC_FOLIO
	AND RI.FTN_ID_PROCESO=RIAUX.FTN_ID_PROCESO
	AND RI.FTN_ID_SUBPROCESO=RIAUX.FTN_ID_SUBPROCESO 
	-- AND RI.FTN_ID_ESTATUS = 3879 -- SOLO REGISTROS YA EXISTENTES no funciona en oracle el on de la columna a actualizar
	)
WHEN MATCHED
THEN UPDATE SET
	  RI.FTN_REGISTROS_RECIBIDOS=RIAUX.FTN_REGISTROS_RECIBIDOS
	, RI.FTN_ID_ESTATUS=RIAUX.FTN_ID_ESTATUS
	, RI.FTC_USU_ACT= 'DATABRICKS' 
	, RI.FTD_FEH_ACT = SYSDATE
WHEN NOT MATCHED
THEN INSERT 
	(
	RI.FTC_FOLIO, 
	RI.FTN_ID_PROCESO, 
	RI.FTN_ID_SUBPROCESO, 
	RI.FTN_REGISTROS_ENVIADOS, 
	RI.FTN_REGISTROS_RECIBIDOS, 
	RI.FTN_ID_ESTATUS, 
	RI.FTC_USU_CRE, 
	RI.FTD_FEH_CRE
	)
VALUES 
	(
	RIAUX.FTC_FOLIO, 
	RIAUX.FTN_ID_PROCESO, 
	RIAUX.FTN_ID_SUBPROCESO, 
	RIAUX.FTN_REGISTROS_ENVIADOS, 
	RIAUX.FTN_REGISTROS_RECIBIDOS, 
	RIAUX.FTN_ID_ESTATUS, 
	'DATABRICKS', 
	 SYSDATE 
	)