SELECT
DISTINCT
VM.FTC_FOLIO,
VM.FTN_NUM_CTA_INVDUAL,
VM.FTN_ID_MARCA,
VM.FCN_ID_TIPO_SUBCTA,            
0 AS FTC_ESTATUS_MARCA
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV VM
WHERE (VM.FTC_FOLIO = '#SR_FOLIO#' OR VM.FTC_FOLIO_REL = '#SR_FOLIO#')