-- Query para extraer informacion del detalle del archivo 65 desde tabla delta 
WITH RID AS 
( 
SELECT
    #SR_FOLIO# AS FTC_FOLIO,
    #SR_PROCESO# AS FTN_ID_PROCESO,
    #SR_SUBPROCESO# AS FTN_ID_SUBPROCESO,
    SUBSTRING(D.FTC_LINEA,1,2) AS TIPO_REG,  -- VARIABLE DS
    SUBSTRING(D.FTC_LINEA,11,9) AS FTN_REGISTROS_RECIBIDOS,
    3880 AS FTN_ID_ESTATUS
  FROM #DELTA_TABLA_NAME1# D
)
SELECT 
-- RID.*
    FTC_FOLIO,
    FTN_ID_PROCESO,
    FTN_ID_SUBPROCESO,
    0 AS FTN_REGISTROS_ENVIADOS,  -- PRA EVITAR EL ERROR DE CONSTRAINT CUANDO SE RECIBE LA RESPUESTA
    FTN_REGISTROS_RECIBIDOS,
    3880 AS FTN_ID_ESTATUS
 FROM RID
WHERE 
  RID.TIPO_REG IN ('01')