SELECT 
COALESCE(CVE_SIEFORE, RPAD('', 2, '0')) AS CVE_SIEFORE,
COALESCE(FTN_NUM_CTA_INVDUAL, RPAD('', 10, '0')) AS FTN_NUM_CTA_INVDUAL,
COALESCE(DVCUE, RPAD('', 1, '0')) AS DVCUE,
SUBSTR(LPAD(ROW_NUMBER() OVER (ORDER BY FFN_CODMOV ) , 8, '0'), -8) AS NUMREG,
COALESCE(FFN_CODMOV, RPAD('', 3, '0')) AS FFN_CODMOV,
LPAD(COALESCE(NSSTRA, ''), 11, ' ') AS NSSTRA,
COALESCE(FCD_FECPRO, RPAD('', 8, '0')) AS FCD_FECPRO,
RPAD('', 7, '0') AS SECPRO,
COALESCE(FTD_FEHCCON, RPAD('', 8, '0')) AS FTD_FEHCCON,
COALESCE(FCN_VALOR_ACCION, RPAD('', 12, '0')) AS FCN_VALOR_ACCION,
COALESCE(FECTRA, RPAD('', 8, '0')) AS FECTRA,
'994' AS SECLOT,
RPAD('', 8, '0') AS FNN_CORREL,
COALESCE(FTD_FEHCCON, RPAD('', 8, '0')) AS FND_FECHA_PAGO,
COALESCE(FNC_PERIODO_PAGO_PATRON, RPAD('', 6, '0')) AS FNC_PERIODO_PAGO_PATRON,
COALESCE(FNC_FOLIO_PAGO_SUA, RPAD('', 6, '0')) AS FNC_FOLIO_PAGO_SUA,
COALESCE(FECSUA, RPAD('', 8, '0')) AS FECSUA,
COALESCE(NSSEMP, RPAD('', 8, '0')) AS NSSEMP,

CASE
    WHEN FFN_CODMOV = 101 
    THEN RPAD('', 15 , '0')
    ELSE COALESCE(MONPES1, RPAD('', 15 , '0'))
END AS MONPES_1,

CASE
    WHEN FFN_CODMOV = 101 
    THEN RPAD('', 15 , '0')
    ELSE COALESCE(MONCUO1, RPAD('', 15 , '0'))
END AS MONCUO_1,

CASE
    WHEN FFN_CODMOV IN (102, 104) 
    THEN COALESCE(MONPES2, RPAD('', 15 , '0'))
    ELSE RPAD('', 15 , '0') 
END AS MONPES_2,

CASE
    WHEN FFN_CODMOV IN (102, 104) 
    THEN COALESCE(MONCUO2, RPAD('', 15 , '0'))
    ELSE RPAD('', 15 , '0') 
END AS MONCUO_2,

CASE
    WHEN FFN_CODMOV = 104 
    THEN RPAD('', 15 , '0')
    ELSE COALESCE(MONPES3, RPAD('', 15 , '0'))
END AS MONPES_3,

CASE
    WHEN FFN_CODMOV = 104 
    THEN RPAD('', 15 , '0')
    ELSE COALESCE(MONCUO3, RPAD('', 15 , '0'))
END AS MONCUO_3,

CASE
    WHEN FFN_CODMOV IN (101, 102) 
    THEN COALESCE(MONPES4, RPAD('', 15 , '0'))
    ELSE RPAD('', 15 , '0') 
END AS MONPES_4,

CASE
    WHEN FFN_CODMOV IN (101, 102) 
    THEN COALESCE(MONCUO4, RPAD('', 15 , '0'))
    ELSE RPAD('', 15 , '0') 
END AS MONCUO_4,

RPAD('', 15 , '0')  AS MONPES_5,
RPAD('', 15 , '0')  AS MONCUO_5,
RPAD('', 15 , '0')  AS MONPES_6,
RPAD('', 15 , '0')  AS MONCUO_6,
RPAD('', 15 , '0')  AS MONPES_7,
RPAD('', 15 , '0')  AS MONCUO_7,
RPAD('', 15 , '0')  AS MONPES_8,
RPAD('', 15 , '0')  AS MONCUO_8,
RPAD('', 15 , '0')  AS MONPES_9,
RPAD('', 15 , '0')  AS MONCUO_9,

CASE
	WHEN  FFN_CODMOV = 124 
	THEN '00000044' 
	ELSE RPAD('', 8 , '0') 
  END AS FECHA_1,

RPAD('', 8 , '0')  AS FECHA_2,

COALESCE(FND_FECVRCV, RPAD('', 8, '0')) AS FND_FECVRCV,
  
RPAD('', 8 , '0')  AS FND_FECHA_VALOR_IMSS_ACV_VIV,

COALESCE(FECVGUB, RPAD('', 8, '0')) AS FECVGUB,

'02' AS CVESERV,

RPAD('', 5 , '0')  AS VARMAX

FROM #CATALOG_SCHEMA#.#tabla_delta#