SELECT
  SUBSEC_NUMCUE
  || SUBSEC_NSSTRA
  || SUBSEC_VIVIENDA97
  || SUBSEC_FECCON
  || SUBSEC_PERPAG
  || SUBSEC_FECTRA
  || SUBSEC_SECLOT
  || SUBSEC_ESTATUS
  || SUBSEC_PARTICIPA97 AS ARCHIVO_SUBSEC_ISSSTE
FROM
  (
    SELECT
      FTN_NUM_CTA_INVDUAL AS SUBSEC_NUMCUE,
      FNN_NSS_ISSSTE_SUA AS SUBSEC_NSSTRA,
      LPAD(
        REPLACE(TO_CHAR(FTF_MONTO_PESOS_S, 'FM99999.90'),'.',''),7,'0'
      ) SUBSEC_VIVIENDA97,
      LPAD(NVL('#SR_FECHA_ACC#', '0'), 8, '0') SUBSEC_FECCON,
      FNC_PERIODO_PAGO_PATRON AS SUBSEC_PERPAG,
      FND_FECTRA_SUA AS SUBSEC_FECTRA,
      FNN_SECLOT_SUA AS SUBSEC_SECLOT,
      CASE
        WHEN(
          FCN_ID_CONCEPTO_MOV = 670
          OR FCN_ID_CONCEPTO_MOV = 671
        ) THEN '03'
        ELSE '04'
      END SUBSEC_ESTATUS,
      LPAD(REPLACE (TO_CHAR(FTF_MONTO_ACCIONES_S, 'FM999999999.999990'),'.',''),15,'0'
      ) SUBSEC_PARTICIPA97
    FROM
      CIERREN_ETL.TTSISGRAL_ETL_GEN_ARCHIVO
    WHERE
      (
        FCN_ID_CONCEPTO_MOV = 670
        OR FCN_ID_CONCEPTO_MOV = 672
        OR FCN_ID_CONCEPTO_MOV = 671
        OR FCN_ID_CONCEPTO_MOV = 673
      )
      AND FNN_ID_VIV_GARANTIA_SUA = 1
      AND FCC_TABLA_NCI_MOV = 'VIV'
      AND FTC_FOLIO = '#SR_FOLIO#'
  )