SELECT DISTINCT
  LPAD(NCI.FTN_NUM_CTA_INVDUAL, 10, '0') AS FTN_NUM_CTA_INVDUAL,
  NVL(NCI.FTC_DIG_VERIF, '0') AS FTC_DIG_VERIF,
  SUBSTR(NCIV.FCC_VALOR_IND, 1, 4) AS FCC_VALOR_IND,
  LPAD(NVL(MP2.TMN_CVE_ITGY, '00'), 2, '0') AS FNC_CVESERV
FROM
  CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS MOV
    INNER JOIN CIERREN.TTAFOGRAL_CTA_INVDUAL NCI
      ON NCI.FTN_NUM_CTA_INVDUAL = MOV.FTN_NUM_CTA_INVDUAL
    INNER JOIN CIERREN.TTAFOGRAL_IND_CTA_INDV NCIV
      ON NCI.FTN_NUM_CTA_INVDUAL = NCIV.FTN_NUM_CTA_INVDUAL
    INNER JOIN CIERREN.TMSISGRAL_MAP_NCI_ITGY MP2
      ON SUBSTR(NCIV.FCC_VALOR_IND, 1, 4) = MP2.TMN_CVE_NCI
WHERE
  MOV.FTC_FOLIO = '#SR_FOLIO#'
  AND NCIV.FFN_ID_CONFIG_INDI = 1
  AND NCIV.FTC_VIGENCIA = '1'
  AND MP2.TMC_VIGENCIA = 1
  AND MP2.TMC_USO = 'CTINDI'