SELECT DISTINCT
    LPAD(nvl(SUA.FNN_ID_REFERENCIA,'0'),8,'0') FNN_ID_REFERENCIA,
    SUA.FTC_FOLIO,
    LPAD(SUA.FTN_NUM_CTA_INVDUAL,10,'0') FTN_NUM_CTA_INVDUAL,
    SUBSTR(SUA.FTC_RFC,1,11) FTN_NSS_SUA,
    SUBSTR(SUA.FTC_RFC,12,1) FTC_DIG_VERI,
    LPAD(NVL(SUA.FTN_NSS,'0'),11,'0') FNN_NSS_ISSSTE_SUA,
    LPAD(NVL(TO_CHAR(SUA.FND_FEH_CRE,'yyyymmdd'),'0'),8,'0') as FND_FEH_CRE_SUA,
    LPAD(NVL(TO_CHAR(SUA.FND_FECHA_PAGO,'YYYYMMDD'),'0'),8,'0') FND_FECHA_PAGO_SUA,
    LPAD(NVL(SUA.FNC_PERIODO_PAGO_PATRON,'0'),6,'0') as FNC_PERIODO_PAGO_PATRON,
    LPAD(NVL(SUA.FNC_FOLIO_PAGO_SUA,'0'),6,'0') as FNC_FOLIO_PAGO_SUA,
    LPAD(NVL(SUA.FNC_REG_PATRONAL_IMSS,'0'),11,'0') FNC_REG_PATRN_IMSS_SUA,
    LPAD(NVL(TO_CHAR(SUA.FND_FECHA_VALOR_RCV,'YYYYMMDD'),'0'),8,'0') as FND_FECHA_VALOR_RCV, 
    LPAD(NVL(TO_CHAR(SUA.FND_FECHA_VALOR_IMSS_ACV_VIV ,'yyyymmdd'),'0'),8,'0') FND_FECHA_VALOR_IMSS_ACV_VIV,
    SUA.FNN_ID_VIV_GARANTIA as FNN_ID_VIV_GARANTIA_SUA,
    SUA.FNC_TIPREG
FROM 
CIERREN.TNAFORECA_SUA SUA
WHERE SUA.FTC_FOLIO = '#SR_FOLIO#' AND ((SUA.FNC_TIPREG=02 AND FCN_ID_SUBPROCESO=118) OR (FCN_ID_SUBPROCESO<>118))