SELECT
LPAD(MOV.FTN_NUM_CTA_INVDUAL,10,'0') AS FTN_NUM_CTA_INVDUAL
,MOV.FCN_ID_TIPO_SUBCTA
,CEQ.FFN_ID_CONCEPTO_MOV
,LPAD(NVL(SUBSTR(CEQ.FFN_COD_MOV_ITGY,0,3),0),3,'0') AS FFN_COD_MOV_ITGY
,LPAD(NVL(F.FTN_ID_ARCHIVO,'0'),7,'0') AS FTN_ID_ARCHIVO
,LPAD(NVL(TO_CHAR(MOV.FTD_FEH_LIQUIDACION,'YYYYMMDD'),'0'),8,'0') AS FTD_FEH_LIQUIDACION
,LPAD(NVL('#SR_FECHA_LOTE#','0'),8,'0') FND_FECTRA_SUA --PARÁMETRO
,LPAD(NVL('#SR_SEC_LOTE#','0'),3,'0') FNN_SECLOT_SUA --PARÁMETRO
,LPAD(NVL(MOV.FNN_ID_REFERENCIA,'0'),8,'0') FNN_ID_REFERENCIA
,'00000000' FND_FECHA_1
,'00000000' FND_FECHA_2
,'00000000' FND_FECVGUB
,'00000' FNC_VARMAX
,MOV.FTC_FOLIO FTC_FOLIO
,NVL(MOV.FTC_FOLIO_REL,MOV.FTC_FOLIO) FTC_FOLIO_SUA
,MOV.FCN_ID_SIEFORE
,MOV.FCN_ID_VALOR_ACCION
,LPAD(TRUNC(VA.FCN_VALOR_ACCION,7)*10000000,12,0) FCN_VALOR_ACCION
,MOV.FCN_ID_TIPO_MOV
,MOV.FTF_MONTO_PESOS AS FTF_MONTO_PESOS_S
,MOV.FTF_MONTO_ACCIONES AS FTF_MONTO_ACCIONES_S
,MOV.FCN_ID_CONCEPTO_MOV
,MOV.FCC_TABLA_NCI_MOV
,CEQ.FFN_POSICION_ITGY AS FFN_POSICION_ITGY
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 1 ) THEN MOV.FTF_MONTO_PESOS  ELSE 0 END AS FTF_MONPES1
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 2 ) THEN MOV.FTF_MONTO_PESOS  ELSE 0 END AS FTF_MONPES2
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 3 ) THEN MOV.FTF_MONTO_PESOS  ELSE 0 END AS FTF_MONPES3
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 4 ) THEN MOV.FTF_MONTO_PESOS  ELSE 0 END AS FTF_MONPES4
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 5 ) THEN MOV.FTF_MONTO_PESOS  ELSE 0 END AS FTF_MONPES5
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 6 ) THEN MOV.FTF_MONTO_PESOS  ELSE 0 END AS FTF_MONPES6
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 7 ) THEN MOV.FTF_MONTO_PESOS  ELSE 0 END AS FTF_MONPES7
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 8 ) THEN MOV.FTF_MONTO_PESOS  ELSE 0 END AS FTF_MONPES8
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 9 ) THEN MOV.FTF_MONTO_PESOS  ELSE 0 END AS FTF_MONPES9
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 1 ) THEN MOV.FTF_MONTO_ACCIONES  ELSE 0 END AS FTF_MONCUO1
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 2 ) THEN MOV.FTF_MONTO_ACCIONES  ELSE 0 END AS FTF_MONCUO2
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 3 ) THEN MOV.FTF_MONTO_ACCIONES  ELSE 0 END AS FTF_MONCUO3
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 4 ) THEN MOV.FTF_MONTO_ACCIONES  ELSE 0 END AS FTF_MONCUO4
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 5 ) THEN MOV.FTF_MONTO_ACCIONES  ELSE 0 END AS FTF_MONCUO5
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 6 ) THEN MOV.FTF_MONTO_ACCIONES  ELSE 0 END AS FTF_MONCUO6
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 7 ) THEN MOV.FTF_MONTO_ACCIONES  ELSE 0 END AS FTF_MONCUO7
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 8 ) THEN MOV.FTF_MONTO_ACCIONES  ELSE 0 END AS FTF_MONCUO8
,CASE WHEN(CEQ.FFN_POSICION_ITGY = 9 ) THEN MOV.FTF_MONTO_ACCIONES  ELSE 0 END AS FTF_MONCUO9
    ,SUB.FCN_ID_CAT_SUBCTA
    ,lpad(MP1.TMN_CVE_ITGY, 2, '0') FCN_CVE_SIEFORE
FROM CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS MOV
    JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MS 
ON MOV.FCN_ID_TIPO_SUBCTA = MS.FCN_ID_TIPO_SUBCTA
     JOIN CIERREN.TFCRXGRAL_CONFIG_MOV_ITGY CEQ
ON MOV.FCN_ID_CONCEPTO_MOV = CEQ.FFN_ID_CONCEPTO_MOV AND MS.FRN_ID_MOV_SUBCTA = CEQ.FRN_ID_MOV_SUBCTA
    JOIN CIERREN.TRAFOGRAL_ARCHIVO_FOLIO F 
ON MOV.FTC_FOLIO = F.FTC_FOLIO
    JOIN  CIERREN.TCCRXGRAL_TIPO_SUBCTA SUB
        ON SUB.FCN_ID_TIPO_SUBCTA = MOV.FCN_ID_TIPO_SUBCTA
    JOIN CIERREN.TMSISGRAL_MAP_NCI_ITGY MP1
        ON MP1.TMN_CVE_NCI = MOV.FCN_ID_SIEFORE AND MP1.TMC_VIGENCIA = 1  AND MP1.TMC_USO='CTINDI'
    JOIN CIERREN.TCAFOGRAL_VALOR_ACCION VA
        ON VA.FCN_ID_VALOR_ACCION = MOV.FCN_ID_VALOR_ACCION
WHERE
    MOV.FTC_FOLIO = '#SR_FOLIO#'
    AND CEQ.FFB_VIGENCIA = 1
 