WITH TF_700 AS (
    SELECT FTC_FOLIO_BITACORA, FCN_ID_SUBPROCESO,
           SUM(ACEPTADOS) AS ACEPTADOS, 
           SUM(RECHAZADOS) AS RECHAZADOS, 
           SUM(ACEPTADOS)+SUM(RECHAZADOS) AS TOTAL, 
           SUM(MONTO_ACEPTADO)+SUM(MONTO_RECHAZADO) AS TOTALMONTO,
           SUM(MONTO_ACEPTADO) AS MONTO_ACEPTADO,
           SUM(MONTO_RECHAZADO) AS MONTO_RECHAZADO
      FROM (
            SELECT DISTINCT FTC_FOLIO_BITACORA,FCN_ID_SUBPROCESO,
                   MONTO,
                   CASE WHEN FTC_ESTA_REGI=1 THEN NUMERO ELSE 0 END ACEPTADOS,
                   CASE WHEN FTC_ESTA_REGI=0 THEN NUMERO ELSE 0 END RECHAZADOS,
                   CASE WHEN FTC_ESTA_REGI=1 THEN MONTO ELSE 0 END MONTO_ACEPTADO,
                   CASE WHEN FTC_ESTA_REGI=0 THEN MONTO ELSE 0 END MONTO_RECHAZADO
              FROM (
                    SELECT FTC_FOLIO AS FTC_FOLIO_BITACORA
                          ,FCN_ID_SUBPROCESO
                          ,0 AS MONTO
                          ,FTC_ESTATUS AS FTC_ESTA_REGI
                          ,COUNT(*) OVER (PARTITION BY FTC_ESTATUS) NUMERO
                      FROM PROCESOS.TTAFOTRAS_DESMARCA_FOVST
                     WHERE FTC_FOLIO = '#SR_FOLIO#'
                       AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
                   )
            )
    GROUP BY FTC_FOLIO_BITACORA,FCN_ID_SUBPROCESO
)
	SELECT
    db800.FTC_FOLIO_BITACORA AS FTC_FOLIO,
    #SR_PROCESO# AS FCN_ID_PROCESO,
    db800.FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO,
    db800.TOTAL AS FLN_TOTAL_REGISTROS,
    db800.ACEPTADOS AS FLN_REG_ACEPTADOS,
    db800.RECHAZADOS AS FLN_REG_RECHAZADOS,
    CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FLD_FEC_REG,
    CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FTD_FEC_REG,
    '#USUARIO#' AS FLC_USU_REG,
    '#USUARIO#' AS FTC_USU_REG,
    81 AS FCN_ID_SIEFORE,
    '0' AS FFN_ID_CONCEPTO_IMP,
    db600.TOTAL AS FTN_NUM_REG,
    db600.RECHAZADOS AS FTN_NUM_REG_RECH,
    db600.MONTO_ACEPTADO AS FTN_IMPORTE_ACEP_AIVS,
    db600.MONTO_RECHAZADO AS FTN_IMPORTE_ACEP_PESOS,
    db600.MONTO_ACEPTADO AS FTN_IMPORTE_RECH_AIVS,
    db600.MONTO_RECHAZADO AS FTN_IMPORTE_RECH_PESOS
FROM TF_700 db800
JOIN TF_700 db600
  ON db800.FTC_FOLIO_BITACORA = db600.FTC_FOLIO_BITACORA
 AND db800.FCN_ID_SUBPROCESO = db600.FCN_ID_SUBPROCESO
