SELECT
    FTC_FOLIO_BITACORA AS FTC_FOLIO,
    #SR_PROCESO# AS FCN_ID_PROCESO, 
    FCN_ID_SUBPROCESO,
    SUM(CASE WHEN FTC_ESTA_REGI=1 THEN NUMERO ELSE 0 END) AS FLN_REG_ACEPTADOS, 
    SUM(CASE WHEN FTC_ESTA_REGI=0 THEN NUMERO ELSE 0 END) AS FLN_REG_RECHAZADOS, 
    SUM(NUMERO) AS FLN_TOTAL_REGISTROS,
    '#USUARIO#' AS FLC_USU_REG,
    CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FLD_FEC_REG
FROM (
    SELECT 
        FTC_FOLIO AS FTC_FOLIO_BITACORA,
        FCN_ID_SUBPROCESO,
        FTC_ESTATUS AS FTC_ESTA_REGI,
        COUNT(*) OVER (PARTITION BY FTC_ESTATUS) NUMERO
    FROM PROCESOS.TTAFOTRAS_DESMARCA_FOVST
    WHERE FTC_FOLIO = '#SR_FOLIO#'
    AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
    GROUP BY FTC_FOLIO, FCN_ID_SUBPROCESO, FTC_ESTATUS
)
GROUP BY FTC_FOLIO_BITACORA, FCN_ID_SUBPROCESO
