WITH base AS (
    SELECT
        DEVO.FTC_FOLIO,
        DEVO.FCN_ID_SUBPROCESO,
        DEVO.FTC_ESTATUS,
        SUM(NVL(FTN_SALDO_TOT_VIVI92,0)) AS SALDO_92,
        SUM(NVL(FTN_SALDO_TOT_VIVI08,0)) AS SALDO_08,
        SUM(NVL(FTN_NUM_APLI_INTE_VIVI92,0)) AS AIVS_92,
        SUM(NVL(FTN_NUM_APLI_INTE_VIVI08,0)) AS AIVS_08,
        COUNT(*) AS NUMERO
    FROM PROCESOS.TTAFOTRAS_DEVO_SALDO_EXC_FOV DEVO
    WHERE FTC_FOLIO = '#SR_FOLIO#'
      AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
    GROUP BY
        DEVO.FTC_FOLIO,
        DEVO.FCN_ID_SUBPROCESO,
        DEVO.FTC_ESTATUS
), 
exploded AS (
    SELECT
        FTC_FOLIO,
        FCN_ID_SUBPROCESO,
        FTC_ESTATUS,
        NUMERO,
        SALDO_92 AS SALDO,
        0 AS INTERES,
        AIVS_92 AS AIVS,
        17 AS ID_TIPO_SUBCTA
    FROM base
    UNION ALL
    SELECT
        FTC_FOLIO,
        FCN_ID_SUBPROCESO,
        FTC_ESTATUS,
        NUMERO,
        SALDO_08 AS SALDO,
        0 AS INTERES,
        AIVS_08 AS AIVS,
        18 AS ID_TIPO_SUBCTA
    FROM base
)
SELECT DISTINCT
    FTC_FOLIO,
    #SR_PROCESO# AS FCN_ID_PROCESO,
    SUM(CASE WHEN FTC_ESTATUS = 1 THEN NUMERO ELSE 0 END) AS FLN_REG_ACEPTADOS,
    SUM(CASE WHEN FTC_ESTATUS = 0 THEN NUMERO ELSE 0 END) AS FLN_REG_RECHAZADOS,
    SUM(NUMERO) AS FLN_TOTAL_REGISTROS,
    FCN_ID_SUBPROCESO,
    --ID_TIPO_SUBCTA,
    '#USUARIO#' AS FLC_USU_REG,
    CAST(
        FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC')
        AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP
    ) AS FLD_FEC_REG
FROM exploded 
GROUP BY
    FTC_FOLIO,
    FCN_ID_SUBPROCESO,
    ID_TIPO_SUBCTA