SELECT
    FTC_FOLIO,
    FCN_ID_SUBPROCESO,
    FCN_ID_TIPO_SUBCTA,
    SUM(ACEPTADOS) AS ACEPTADOS,
    SUM(IMPORTE_ACEP_PESOS) AS FTN_IMPORTE_ACEP_PESOS,
    SUM(IMPORTE_ACT_PESOS_PRO) AS FTN_IMPORTE_ACT_PESOS_PRO,
    SUM(IMPORTE_ACEP_AIVS) AS FTN_IMPORTE_ACEP_AIVS,
    SUM(RECHAZADOS) AS FTN_NUM_REG_RECH,
    SUM(IMPORTE_RECH_PESOS) AS FTN_IMPORTE_RECH_PESOS,
    SUM(IMPORTE_RECH_AIVS) AS FTN_IMPORTE_RECH_AIVS,
    SUM(ACEPTADOS) + SUM(RECHAZADOS) AS FTN_NUM_REG
FROM (
    SELECT
        FTC_FOLIO,
        FCN_ID_SUBPROCESO,
        17 AS FCN_ID_TIPO_SUBCTA,
        CASE WHEN FTC_ESTATUS=1 THEN NUMERO ELSE 0 END AS ACEPTADOS,
        CASE WHEN FTC_ESTATUS=0 THEN NUMERO ELSE 0 END AS RECHAZADOS,
        CASE WHEN FTC_ESTATUS=1 THEN SALDO_92 ELSE 0 END AS IMPORTE_ACEP_PESOS,
        CASE WHEN FTC_ESTATUS=1 THEN INTERES_SALDO_92 ELSE 0 END AS IMPORTE_ACT_PESOS_PRO,
        CASE WHEN FTC_ESTATUS=1 THEN AIVS_92 ELSE 0 END AS IMPORTE_ACEP_AIVS,
        CASE WHEN FTC_ESTATUS=0 THEN SALDO_92 ELSE 0 END AS IMPORTE_RECH_PESOS,
        CASE WHEN FTC_ESTATUS=0 THEN AIVS_92 ELSE 0 END AS IMPORTE_RECH_AIVS
    FROM (
        SELECT
            FTC_FOLIO,
            FCN_ID_SUBPROCESO,
            FTC_ESTATUS,
            COUNT(FTC_ESTATUS) AS NUMERO,
            SUM(FTN_SALDO_TOT_VIVI92) AS SALDO_92,
            0 AS INTERES_SALDO_92,
            SUM(FTN_NUM_APLI_INTE_VIVI92) AS AIVS_92
        FROM PROCESOS.TTAFOTRAS_DEVO_SALDO_EXC_FOV 
        WHERE FTC_FOLIO ='#SR_FOLIO#'
          AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
        GROUP BY FTC_FOLIO, FCN_ID_SUBPROCESO, FTC_ESTATUS
    )
    UNION ALL
    SELECT
        FTC_FOLIO,
        FCN_ID_SUBPROCESO,
        18 AS FCN_ID_TIPO_SUBCTA,
        CASE WHEN FTC_ESTATUS=1 THEN NUMERO ELSE 0 END AS ACEPTADOS,
        CASE WHEN FTC_ESTATUS=0 THEN NUMERO ELSE 0 END AS RECHAZADOS,
        CASE WHEN FTC_ESTATUS=1 THEN SALDO_08 ELSE 0 END AS IMPORTE_ACEP_PESOS,
        CASE WHEN FTC_ESTATUS=1 THEN INTERES_SALDO_08 ELSE 0 END AS IMPORTE_ACT_PESOS_PRO,
        CASE WHEN FTC_ESTATUS=1 THEN AIVS_08 ELSE 0 END AS IMPORTE_ACEP_AIVS,
        CASE WHEN FTC_ESTATUS=0 THEN SALDO_08 ELSE 0 END AS IMPORTE_RECH_PESOS,
        CASE WHEN FTC_ESTATUS=0 THEN AIVS_08 ELSE 0 END AS IMPORTE_RECH_AIVS
    FROM (
        SELECT
            FTC_FOLIO,
            FCN_ID_SUBPROCESO,
            FTC_ESTATUS,
            COUNT(FTC_ESTATUS) AS NUMERO,
            SUM(FTN_SALDO_TOT_VIVI08) AS SALDO_08,
            0 AS INTERES_SALDO_08,
            SUM(FTN_NUM_APLI_INTE_VIVI08) AS AIVS_08
        FROM PROCESOS.TTAFOTRAS_DEVO_SALDO_EXC_FOV
        WHERE FTC_FOLIO ='#SR_FOLIO#'
          AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
        GROUP BY FTC_FOLIO, FCN_ID_SUBPROCESO, FTC_ESTATUS
    )
)
GROUP BY FTC_FOLIO, FCN_ID_SUBPROCESO, FCN_ID_TIPO_SUBCTA
