SELECT DISTINCT
      T.FTC_FOLIO as FTC_FOLIO,
      lpad(t.ftn_num_cta_invdual,10,'0') as NUMCUE,
      lpad(nvl(T.FTC_NSS,'0'),11,'0') AS FTC_NSS_AFORE, 
      TRIM(IND.FTC_DIG_VERIF) AS DVCUE,
      to_char(T.FTD_FEH_CRE, 'YYYYMMDD')FTD_FEH_CRE,
      lpad(nvl(ET.FTN_ID_ARCHIVO,'0'),7,'0') AS FTN_ID_ARCHIVO,
      T.FCN_ID_SUBPROCESO FCN_ID_SUBPROCESO,
      lpad(nvl(T.FTN_CONTA_SERV,'0'),8,'0') AS FNN_ID_REFERENCIA,
      null FTC_INSTITUTO_ORIGEN
      FROM PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE T
      LEFT JOIN CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_FOVISSSTE ET
      ON ET.FTC_FOLIO=T.FTC_FOLIO AND ET.FTC_TIPO_ARCH='01'
      LEFT JOIN CIERREN.TTAFOGRAL_CTA_INVDUAL IND ON T.ftn_num_cta_invdual = IND.FTN_NUM_CTA_INVDUAL 
      WHERE T.FTC_FOLIO= '#sr_folio#'
      AND T.FCN_ID_SUBPROCESO=#sr_subproceso#
      AND T.FTC_ESTATUS=1