MERGE INTO PROCESOS.TTSISGRAL_SUF_SALDOS TGT
USING (
    SELECT 
        FTN_NUM_CTA_INVDUAL,
        FTN_IND_SDO_DISP_VIV97,
        FTN_IND_SDO_DISP_92,
        FTN_SDO_AIVS,
        FTN_SDO_AIVS_92,
        FTN_VALOR_AIVS,
        FTN_MONTO_PESOS,
        FTN_MONTO_PESOS_92,
        FCN_ESTATUS,
        FTD_FEH_CRE,
        FTC_USU_CRE,
        FTC_FOLIO_BITACORA,
        FCN_ID_REGIMEN,
        FCN_ID_TIPO_SUBCTA_97,
        FCN_ID_TIPO_SUBCTA_92,
        FTN_ID_SUBP,
        FCN_ID_VALOR_ACCION,
        FTN_CONTA_SERV,
        FTN_MOTI_RECH
    FROM CIERREN_DATAUX.TTSISGRAL_SUF_SALDOS_AUX
    WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'
) SRC
ON (
    TGT.FTC_FOLIO_BITACORA  = SRC.FTC_FOLIO_BITACORA
    AND TGT.FTN_NUM_CTA_INVDUAL = SRC.FTN_NUM_CTA_INVDUAL
    AND TGT.FTN_CONTA_SERV   = SRC.FTN_CONTA_SERV
)
WHEN MATCHED THEN
    UPDATE SET
      --  TGT.FTN_NUM_CTA_INVDUAL    = SRC.FTN_NUM_CTA_INVDUAL,
        TGT.FTN_IND_SDO_DISP_VIV97 = SRC.FTN_IND_SDO_DISP_VIV97,
        TGT.FTN_IND_SDO_DISP_92    = SRC.FTN_IND_SDO_DISP_92,
        TGT.FTN_SDO_AIVS           = SRC.FTN_SDO_AIVS,
        TGT.FTN_SDO_AIVS_92        = SRC.FTN_SDO_AIVS_92,
        TGT.FTN_VALOR_AIVS         = SRC.FTN_VALOR_AIVS,
        TGT.FTN_MONTO_PESOS        = SRC.FTN_MONTO_PESOS,
        TGT.FTN_MONTO_PESOS_92     = SRC.FTN_MONTO_PESOS_92,
        TGT.FCN_ESTATUS            = SRC.FCN_ESTATUS,
        TGT.FTD_FEH_CRE            = SRC.FTD_FEH_CRE,
        TGT.FTC_USU_CRE            = SRC.FTC_USU_CRE,
        --TGT.FTC_FOLIO_BITACORA     = SRC.FTC_FOLIO_BITACORA,
        TGT.FCN_ID_REGIMEN         = SRC.FCN_ID_REGIMEN,
        TGT.FCN_ID_TIPO_SUBCTA_97  = SRC.FCN_ID_TIPO_SUBCTA_97,
        TGT.FCN_ID_TIPO_SUBCTA_92  = SRC.FCN_ID_TIPO_SUBCTA_92,
        TGT.FTN_ID_SUBP            = SRC.FTN_ID_SUBP,
        TGT.FCN_ID_VALOR_ACCION    = SRC.FCN_ID_VALOR_ACCION,
       -- TGT.FTN_CONTA_SERV         = SRC.FTN_CONTA_SERV,
        TGT.FTN_MOTI_RECH          = SRC.FTN_MOTI_RECH