MERGE INTO PROCESOS.TTAFOTRAS_TRANS_REC_PORTA TGT
USING (
    SELECT DISTINCT
        FTC_FOLIO,
        FTN_NUM_CTA_INVDUAL,
        FTN_NO_LINEA,
        FTC_ESTATUS_OPE,
        FTC_DIAGNOSTICO,
        FTC_MOTIVO_REC,
        FTD_FEH_ACT,
        FTC_USU_ACT
    FROM CIERREN_DATAUX.TTAFOTRAS_TRANS_REC_PORTA_AUX
) SRC
ON (
    TGT.FTC_FOLIO = SRC.FTC_FOLIO
    AND TGT.FTN_NUM_CTA_INVDUAL = SRC.FTN_NUM_CTA_INVDUAL
    AND TGT.FTN_NO_LINEA = SRC.FTN_NO_LINEA
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTC_ESTATUS_OPE = SRC.FTC_ESTATUS_OPE,
        TGT.FTC_DIAGNOSTICO = SRC.FTC_DIAGNOSTICO,
        TGT.FTC_MOTIVO_REC = SRC.FTC_MOTIVO_REC,
        TGT.FTD_FEH_ACT = SRC.FTD_FEH_ACT,
        TGT.FTC_USU_ACT = SRC.FTC_USU_ACT