MERGE INTO CIERREN.TTAFOGRAL_IND_CTA_INDV TGT
USING (
    SELECT DISTINCT
        FCN_ID_IND_CTA_INDV
				,FTC_VIGENCIA 
				,FTD_FEH_ACT
				,FCC_USU_ACT
				,FTC_FOLIO
    FROM CIERREN_DATAUX.TTAFOGRAL_ETL_IND_CTA_INDV_AUX
    WHERE FTC_FOLIO = '#sr_folio#'
) SRC
ON (
    TGT.FCN_ID_IND_CTA_INDV = SRC.FCN_ID_IND_CTA_INDV
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTC_VIGENCIA = SRC.FTC_VIGENCIA,
        TGT.FTD_FEH_ACT = SRC.FTD_FEH_ACT,
        TGT.FCC_USU_ACT = SRC.FCC_USU_ACT