WITH IND_CTA_INDV AS (
SELECT FCN_ID_IND_CTA_INDV,
       FTN_NUM_CTA_INVDUAL,
       FFN_ID_CONFIG_INDI,
       FCC_VALOR_IND
  FROM CIERREN.TTAFOGRAL_IND_CTA_INDV
 WHERE FFN_ID_CONFIG_INDI = 14
   AND FCC_VALOR_IND <> '4'
   AND FTC_VIGENCIA = '1'
)
SELECT
   DMI.FTC_FOLIO_BITACORA AS FTC_FOLIO
   ,CI.FCN_ID_IND_CTA_INDV
   ,CI.FTN_NUM_CTA_INVDUAL
   ,0 AS FTC_VIGENCIA
   ,(SELECT CAST(CURRENT_TIMESTAMP AT TIME ZONE 'America/Mexico_City' AS DATE) FROM DUAL) AS FTD_FEH_ACT
   ,'DATABRICKS' AS FCC_USU_ACT
FROM
   PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO DMI
INNER JOIN 
	IND_CTA_INDV CI
ON
	CI.FTN_NUM_CTA_INVDUAL = DMI.FTN_CTA_AFORE
WHERE 
	 DMI.FTC_FOLIO_BITACORA = '#sr_folio#'
  AND DMI.FTN_ID_SUBP = '#sr_subproceso#' 
  AND DMI.FTC_ESTA_REGI = '1'