WITH IND_CTA_INDV AS (
SELECT FCN_ID_IND_CTA_INDV,
       FTN_NUM_CTA_INVDUAL,
       FFN_ID_CONFIG_INDI,
       FCC_VALOR_IND,
       FTC_VIGENCIA
  FROM CIERREN.TTAFOGRAL_IND_CTA_INDV
 WHERE FFN_ID_CONFIG_INDI = 14
   AND FCC_VALOR_IND IN ('0','1','2','3','4','5')
   AND FTC_VIGENCIA = '1'
),
MARCA_DESMARCA_INFO
AS
(
SELECT DISTINCT 
DMI.FTN_CTA_AFORE AS FTN_NUM_CTA_INVDUAL,
FFN_ID_CONFIG_INDI,
FCC_VALOR_IND,
FTC_VIGENCIA
FROM
   PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO DMI
LEFT JOIN 
	IND_CTA_INDV CI
ON
	CI.FTN_NUM_CTA_INVDUAL = DMI.FTN_CTA_AFORE
WHERE 
	FTC_FOLIO_BITACORA = '#sr_folio#'
  AND DMI.FTN_ID_SUBP = '#sr_subproceso#' 
  AND DMI.FTC_ESTA_REGI = '1'
  )
 SELECT
 FTN_NUM_CTA_INVDUAL
,14 AS FFN_ID_CONFIG_INDI
,4 AS FCC_VALOR_IND
,1 AS FTC_VIGENCIA
,(SELECT CAST(CURRENT_TIMESTAMP AT TIME ZONE 'America/Mexico_City' AS DATE) FROM DUAL) AS FTD_FEH_REG
,'DATABRICKS' AS FTC_USU_REG
 FROM MARCA_DESMARCA_INFO
 WHERE (FCC_VALOR_IND <> '4' OR FCC_VALOR_IND IS NULL)