SELECT 
FTD_FEH_PRESEN,
FTC_CURP_TRABA AS FTC_CURP,
FTC_NSS_TRABA_INFO AS FTC_NSS_INFONA,
FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_IND,
FTC_RFC_TRABA_INFO AS FTC_RFC_INFONA,
FTC_IDENT_LOTE_SOLI AS FTC_ID_LOTE_SOL,
FTC_NSS_TRABA_AFORE AS FTC_NSS,
FTC_RFC_TRABA_AFORE AS FTC_RFC,
CASE WHEN FTC_DIAG_PROCESO IS NULL THEN CAST(NULL AS VARCHAR(6)) ELSE SUBSTRING(FTC_DIAG_PROCESO, 1, 3) END AS FCC_ID_MOT_RECHA_PRO1,
CASE WHEN FTC_DIAG_PROCESO IS NULL THEN CAST(NULL AS VARCHAR(6)) ELSE SUBSTRING(FTC_DIAG_PROCESO, 4, 3) END AS FCC_ID_MOT_RECHA_PRO2,
CASE WHEN FTC_DIAG_PROCESO IS NULL THEN CAST(NULL AS VARCHAR(6)) ELSE SUBSTRING(FTC_DIAG_PROCESO, 7, 3) END AS FCC_ID_MOT_RECHA_PRO3,
CASE WHEN FTC_DIAG_PROCESO IS NULL THEN CAST(NULL AS VARCHAR(6)) ELSE SUBSTRING(FTC_DIAG_PROCESO, 10, 3) END AS FCC_ID_MOT_RECHA_PRO4,
CASE WHEN FTC_DIAG_PROCESO IS NULL THEN CAST(NULL AS VARCHAR(6)) ELSE SUBSTRING(FTC_DIAG_PROCESO, 13, 3) END AS FCC_ID_MOT_RECHA_PRO5,
CAST(FTC_NUMERO_CRED_INFONA AS DECIMAL(10,0)) AS FTN_NUM_CREDITO,
FTN_FOLIO_BITACORA AS FTC_FOLIO_BITA,
CASE WHEN FTC_ESTATUS_REGISTRO = '1' THEN '1' ELSE '0' END AS FTC_ID_CTA_VIGENTE,
FTC_ESTATUS_REGISTRO AS FCC_ID_ESTA_REG,
CAST(FTD_FEH_ACT AS DATE) AS FTD_FEH_ACTU_ESTA,
FTN_MOTIVO_RECHAZO AS FCN_ID_MOTI_RECH,
FTN_ID_SUBP AS FCN_ID_SUBPROCESO,
CASE 
    WHEN FTN_ID_SUBP = 365 THEN CAST(FTN_NUM_APLI_INTE_VIVI97_SOL AS DECIMAL(15,6))
    WHEN FTN_ID_SUBP = 368 THEN CAST(FTN_NUM_APLI_INTE_VIVI97_SOL AS DECIMAL(15,6))
    ELSE CAST(NULL AS DECIMAL(15,6))
END AS FTN_AIVS_97_SOL,
CASE 
    WHEN FTN_ID_SUBP = 368 THEN CAST(FTN_NUM_AIVS_97_ENV_TRN AS DECIMAL(15,6))
    ELSE CAST(NULL AS DECIMAL(15,6))
END AS FTN_AIVS_97_TRANS,
CASE 
    WHEN FTN_ID_SUBP = 364 THEN CAST(FTN_NUM_APLI_INTE_VIVI97_ULT AS DECIMAL(15,6))
    ELSE CAST(NULL AS DECIMAL(15,6))
END AS FTN_AIVS_97_ULT_AP,
CASE 
    WHEN FTN_ID_SUBP = 365 THEN CAST(FTN_NUM_AIVS_97_ENV_TRN AS DECIMAL(15,6))
    WHEN FTN_ID_SUBP = 364 THEN CAST(FTN_NUM_AIVS_97_ENV_TRN AS DECIMAL(15,6))
    ELSE CAST(NULL AS DECIMAL(15,6))
END AS FTN_AIVS_97_ENV,
CASE 
    WHEN FTN_ID_SUBP = 365 THEN CAST(FTN_NUM_AIVS_VIVI92_ENV_TRN AS DECIMAL(15,6))
    WHEN FTN_ID_SUBP = 364 THEN CAST(FTN_NUM_AIVS_VIVI92_ENV_TRN AS DECIMAL(15,6))
    ELSE CAST(NULL AS DECIMAL(15,6))
END AS FTN_AIVS_92_ENV,
CASE 
    WHEN FTN_ID_SUBP = 365 THEN CAST(FTN_NUM_APLI_INTE_VIVI92_SOL AS DECIMAL(15,6))
    ELSE CAST(NULL AS DECIMAL(15,6))
END AS FTN_AIVS_92_SOL,
CASE 
    WHEN FTN_ID_SUBP = 365 THEN CAST(FTN_NUM_APLI_INTE_VIVI97_SOL * FTN_VALOR_AIVS AS DECIMAL(15,2))
    WHEN FTN_ID_SUBP = 368 THEN CAST(FTN_NUM_APLI_INTE_VIVI97_SOL * FTN_VALOR_AIVS AS DECIMAL(15,2))
    ELSE CAST(NULL AS DECIMAL(15,2))
END AS FTN_SALDO_VIV97_SOL,
CASE 
    WHEN FTN_ID_SUBP = 368 THEN CAST(FTN_SALDO_VIVI97_ENV_TRN AS DECIMAL(15,2))
    ELSE CAST(NULL AS DECIMAL(15,2))
END AS FTN_SALDO_VIV97_TRANS,
CASE 
    WHEN FTN_ID_SUBP = 364 THEN CAST(FTN_UTLIMA_APOR_VIVI97 AS DECIMAL(15,2))
    ELSE CAST(NULL AS DECIMAL(15,2))
END AS FTN_SALDO_VIV97_ULT_AP,
CASE 
    WHEN FTN_ID_SUBP = 365 THEN CAST(FTN_SALDO_VIVI97_ENV_TRN AS DECIMAL(15,2))
    WHEN FTN_ID_SUBP = 364 THEN CAST(FTN_SALDO_VIVI97_ENV_TRN AS DECIMAL(15,2))
    ELSE CAST(NULL AS DECIMAL(15,2))
END AS FTN_SALDO_VIV97_ENV,
CASE 
    WHEN FTN_ID_SUBP = 365 THEN CAST(FTN_SALDO_VIVI92_ENV_TRN AS DECIMAL(15,2))
    WHEN FTN_ID_SUBP = 364 THEN CAST(FTN_SALDO_VIVI92_ENV_TRN AS DECIMAL(15,2))
    ELSE CAST(NULL AS DECIMAL(15,2))
END AS FTN_SALDO_VIV92_ENV,
CASE 
    WHEN FTN_ID_SUBP = 365 THEN CAST(FTN_NUM_APLI_INTE_VIVI92_SOL * FTN_VALOR_AIVS AS DECIMAL(15,2))
    ELSE CAST(NULL AS DECIMAL(15,2))
END AS FTN_SALDO_VIV92_SOL,
CASE 
    WHEN FTN_ID_SUBP = 365 THEN CAST(FTC_INDI_DIFE_VIVI92 AS DECIMAL(10,0))
    WHEN FTN_ID_SUBP = 368 THEN CAST(FTC_INDI_DIFE_VIVI92 AS DECIMAL(10,0))
    WHEN FTN_ID_SUBP = 364 THEN CAST(FTC_INDI_DIFE_VIVI92 AS DECIMAL(10,0))
    ELSE CAST(NULL AS DECIMAL(10,0))
END AS FTN_INDI_DIFE_VIVI92,
CASE 
    WHEN FTN_ID_SUBP = 365 THEN CAST(FTC_INDI_DIFE_VIVI97 AS DECIMAL(10,0))
    WHEN FTN_ID_SUBP = 368 THEN CAST(FTC_INDI_DIFE_VIVI97 AS DECIMAL(10,0))
    WHEN FTN_ID_SUBP = 364 THEN CAST(FTC_INDI_DIFE_VIVI97 AS DECIMAL(10,0))
    ELSE CAST(NULL AS DECIMAL(10,0))
END AS FTN_INDI_DIFE_VIVI97,
CAST(NULL AS DECIMAL(15,2)) AS FTN_INTER_SALDO_VIVI97_ULT,
CAST(NULL AS DECIMAL(15,2)) AS FTN_INTER_SALDO_VIVI92,
1 AS FCN_ID_INSTITUTO,
to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_CRE,
'CIERREN_ETL_APP' AS FTC_USU_CRE,
FTC_ORIGEN_TRANSFE AS FTC_ORIGEN_TRANS,
FTN_CONTA_SERV,
FTC_CODIGO_RES_OPER,
FTN_PERIODO_PAGO AS FTN_PERI_PAGO,
FTD_FEH_CARGA,
FTD_FEH_VALOR_VIVI,
FTN_IDENTI_MOVTO,
FCN_ID_SIEFORE,
FCN_ID_TIPO_SUBCTA,
FTD_FEH_MOVIMIENTO
FROM #CATALOG_SCHEMA#.TEMP_JOIN_MOVIMIENTOS_#SR_FOLIO#
WHERE FTN_ID_SUBP IN (365, 368, 364)
