SELECT 
FTC_RFC_TRABA_INFO AS FTC_RFC_INFONA,
FTC_CURP_TRABA AS FTC_CURP,
FTC_NSS_TRABA_INFO AS FTC_NSS_INFONA,
FTC_APELLIDO_PATE_INFO AS FTC_APELLIDO_PATER_INFONA,
FTC_APELLIDO_MATE_INFO AS FTC_APELLIDO_MATER_INFONA,
FTC_NOMBRES_INFO AS FTC_NOMBRE_INFONA,
FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_IND,
FTC_NOMBRE_TRABA_IMSS AS FTC_NOMBRE_IMSS
FROM #CATALOG_SCHEMA#.TEMP_JOIN_MOVIMIENTOS_#SR_FOLIO#
