SELECT DISTINCT FTC_FOLIO_BITACORA AS FTN_FOLIO_BITACORA, FTN_VALOR_AIVS 
FROM #CX_PRO_ESQUEMA#.#TL_PRO_SUF_SALDOS#
WHERE FTC_FOLIO_BITACORA= '#SR_FOLIO#'
AND FTN_ID_SUBP=#SR_SUBPROCESO#
AND FCN_ESTATUS=1
