SELECT DISTINCT FTC_FOLIO AS FTN_FOLIO_BITACORA, FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_AFORE, FNN_ID_REFERENCIA AS FTN_CONTA_SERV,
       FCD_FEH_CRE AS FTD_FEH_MOVIMIENTO
FROM #CX_CRE_ESQUEMA#.#TL_ETL_MOVIMIENTOS#  
WHERE FTC_FOLIO = '#SR_FOLIO#' AND FTN_MOV_GENERADO=1
