SELECT
    a.FTN_NUM_CTA_INVDUAL,
    a.FTN_CONSE_REG_LOTE,
    b.FCN_ID_TIPO_SUBCTA
FROM
    #DS_500_SDO_SOL_INFON# a
LEFT JOIN
    #DS_300_SDO_DISP_VIV97# b
    ON a.FTN_NUM_CTA_INVDUAL = b.FTN_NUM_CTA_INVDUAL
WHERE
    b.SDO_DISPONIBLE <= 0
    OR b.SDO_DISPONIBLE IS NULL