--DS_300_SDO_DISP_VIV97
SELECT 
  FTC_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL,
  SUM(FTN_DISP_ACCIONES) AS SDO_DISPONIBLE,
  FCN_ID_TIPO_SUBCTA,
  FCN_ID_SIEFORE
FROM cierren.TTAFOGRAL_BALANCE_MOVS
WHERE
  FTC_NUM_CTA_INVDUAL IN (
    SELECT FTN_NUM_CTA_INVDUAL 
    FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL 
    WHERE FTC_FOLIO = '#sr_folio#'
    /* AND FTC_ESTATUS=1 */
  )
  AND FCN_ID_TIPO_SUBCTA = 15
GROUP BY FTC_NUM_CTA_INVDUAL, FCN_ID_TIPO_SUBCTA, FCN_ID_SIEFORE
HAVING SUM(FTN_DISP_ACCIONES) > 0
ORDER BY FTC_NUM_CTA_INVDUAL, FCN_ID_TIPO_SUBCTA, FCN_ID_SIEFORE