WITH

-- 1. Solicited balances (SDO_SOL > 0)
FL_100_SEL_SDO_SOL AS (
    SELECT
        FTN_NUM_CTA_INVDUAL,
        FTC_NSS,
        FTN_CONSE_REG_LOTE,
        SDO_SOL,
        BANDERA_MONTO,
        BANDERA_SOL,
        FCN_ID_TIPO_SUBCTA
    FROM #DS_400_SDO_SOL_IMSS#
    WHERE SDO_SOL > 0
),

-- 2. Join with available balances per subaccount
JN_200_AG_SDO_DISP AS (
    SELECT
        f.FTN_NUM_CTA_INVDUAL,
        f.FTC_NSS,
        f.FTN_CONSE_REG_LOTE,
        f.SDO_SOL,
        f.BANDERA_MONTO,
        f.BANDERA_SOL,
        f.FCN_ID_TIPO_SUBCTA,
        d.SDO_DISPONIBLE_PESOS,
        d.SDO_DISPONIBLE_ACCION,
        d.FCN_ID_SIEFORE,
        d.FCD_FEH_ACCION,
        d.FCN_VALOR_ACCION,
        d.FCN_ID_REGIMEN,
        d.FCN_ID_VALOR_ACCION
    FROM FL_100_SEL_SDO_SOL f
    LEFT JOIN #DS_101_SDO_DISP_SUBCTAS_IMSS# d
      ON f.FTN_NUM_CTA_INVDUAL = d.FTN_NUM_CTA_INVDUAL
     AND f.FCN_ID_TIPO_SUBCTA = d.FCN_ID_TIPO_SUBCTA
),

-- 3. Aggregate available balances per account
AG_400_SUM_DISP_X_CTA AS (
    SELECT
        FTN_NUM_CTA_INVDUAL,
        SUM(SDO_DISPONIBLE_PESOS) AS SDO_DISPONIBLE_X_CTA
    FROM #DS_101_SDO_DISP_SUBCTAS_IMSS#
    GROUP BY FTN_NUM_CTA_INVDUAL
),

-- 4. Join detailed and aggregated data
JN_500_AG_DISP AS (
    SELECT
        j.*,
        a.SDO_DISPONIBLE_X_CTA
    FROM JN_200_AG_SDO_DISP j
    LEFT JOIN AG_400_SUM_DISP_X_CTA a
      ON j.FTN_NUM_CTA_INVDUAL = a.FTN_NUM_CTA_INVDUAL
),

-- 5. Split by subaccount type and available balance
RET97 AS (
    SELECT *
    FROM JN_500_AG_DISP
    WHERE SDO_DISPONIBLE_PESOS > 0 AND FCN_ID_TIPO_SUBCTA = 1
),
CV AS (
    SELECT *
    FROM JN_500_AG_DISP
    WHERE SDO_DISPONIBLE_PESOS > 0 AND FCN_ID_TIPO_SUBCTA = 2
),
CS AS (
    SELECT *
    FROM JN_500_AG_DISP
    WHERE SDO_DISPONIBLE_PESOS > 0 AND FCN_ID_TIPO_SUBCTA = 3
),

-- 6. For each, calculate remaining available balance after allocation and Bandera
TF_601_RESTA_SDOS_DISP_RET97 AS (
    SELECT
        FTN_NUM_CTA_INVDUAL,
        FTC_NSS,
        FTN_CONSE_REG_LOTE,
        SDO_SOL,
        BANDERA_MONTO,
        SDO_DISPONIBLE_PESOS,
        FCN_ID_SIEFORE,
        SDO_DISPONIBLE_ACCION,
        FCN_ID_TIPO_SUBCTA,
        FCN_VALOR_ACCION,
        FCD_FEH_ACCION,
        FCN_ID_REGIMEN,
        FCN_ID_VALOR_ACCION,
        (SDO_DISPONIBLE_PESOS - SDO_SOL) AS SALDOS,
        CASE WHEN (SDO_DISPONIBLE_PESOS - SDO_SOL) <= 0 THEN 0 ELSE 1 END AS Bandera
    FROM RET97
),
TF_602_RESTA_SDOS_DISP_CV AS (
    SELECT
        FTN_NUM_CTA_INVDUAL,
        FTC_NSS,
        FTN_CONSE_REG_LOTE,
        SDO_SOL,
        BANDERA_MONTO,
        SDO_DISPONIBLE_PESOS,
        FCN_ID_SIEFORE,
        SDO_DISPONIBLE_ACCION,
        FCN_ID_TIPO_SUBCTA,
        FCN_VALOR_ACCION,
        FCD_FEH_ACCION,
        FCN_ID_REGIMEN,
        FCN_ID_VALOR_ACCION,
        (SDO_DISPONIBLE_PESOS - SDO_SOL) AS SALDOS,
        CASE WHEN (SDO_DISPONIBLE_PESOS - SDO_SOL) <= 0 THEN 0 ELSE 1 END AS Bandera
    FROM CV
),
TF_603_RESTA_SDOS_DISP_CS AS (
    SELECT
        FTN_NUM_CTA_INVDUAL,
        FTC_NSS,
        FTN_CONSE_REG_LOTE,
        SDO_SOL,
        BANDERA_MONTO,
        SDO_DISPONIBLE_PESOS,
        FCN_ID_SIEFORE,
        SDO_DISPONIBLE_ACCION,
        FCN_ID_TIPO_SUBCTA,
        FCN_VALOR_ACCION,
        FCD_FEH_ACCION,
        FCN_ID_REGIMEN,
        FCN_ID_VALOR_ACCION,
        (SDO_DISPONIBLE_PESOS - SDO_SOL) AS SALDOS,
        CASE WHEN (SDO_DISPONIBLE_PESOS - SDO_SOL) <= 0 THEN 0 ELSE 1 END AS Bandera
    FROM CS
),

-- 7. Funnel (union all) the three streams
FN_700_UNE_SDOS AS (
    SELECT * FROM TF_601_RESTA_SDOS_DISP_RET97
    UNION ALL
    SELECT * FROM TF_602_RESTA_SDOS_DISP_CV
    UNION ALL
    SELECT * FROM TF_603_RESTA_SDOS_DISP_CS
),

-- 8. Filter for Bandera = 0 (insufficient available balance)
FL_800_SEP_SDOS_DISP AS (
    SELECT
        FTN_NUM_CTA_INVDUAL,
        FTN_CONSE_REG_LOTE,
        BANDERA_MONTO,
        FCN_ID_SIEFORE,
        FCN_ID_TIPO_SUBCTA
    FROM FN_700_UNE_SDOS
    WHERE Bandera = 0
)

-- 9. Final output for DS_801_CTAS_NO_ALCN_SDO_DISP
SELECT
    FTN_NUM_CTA_INVDUAL,
    FTN_CONSE_REG_LOTE,
    BANDERA_MONTO,
    FCN_ID_SIEFORE,
    FCN_ID_TIPO_SUBCTA
FROM FL_800_SEP_SDOS_DISP
ORDER BY
    FTN_NUM_CTA_INVDUAL ASC,
    FTN_CONSE_REG_LOTE ASC,
    BANDERA_MONTO ASC,
    FCN_ID_SIEFORE ASC,
    FCN_ID_TIPO_SUBCTA ASC
;