SELECT
  bm.FTC_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL,
  SUM(bm.FTN_DISP_ACCIONES) * va.FCN_VALOR_ACCION AS SDO_DISPONIBLE_PESOS,
  SUM(bm.FTN_DISP_ACCIONES) AS SDO_DISPONIBLE_ACCION,
  bm.FCN_ID_TIPO_SUBCTA,
  bm.FCN_ID_SIEFORE,
  va.FCD_FEH_ACCION,
  va.FCN_VALOR_ACCION,
  va.FCN_ID_REGIMEN,
  va.FCN_ID_VALOR_ACCION
FROM cierren.TTAFOGRAL_BALANCE_MOVS bm
JOIN cierren.TCAFOGRAL_VALOR_ACCION va
  ON bm.FCN_ID_SIEFORE = va.FCN_ID_SIEFORE
WHERE
  bm.FTC_NUM_CTA_INVDUAL IN (
    SELECT FTN_NUM_CTA_INVDUAL
    FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
    WHERE FTC_FOLIO = '#sr_folio#'
  )
  AND bm.FCN_ID_TIPO_SUBCTA IN (1, 2, 3)
  AND va.FCN_ID_REGIMEN = 138
  AND TRUNC(va.FCD_FEH_ACCION) = TRUNC(SYSDATE)
GROUP BY
  bm.FTC_NUM_CTA_INVDUAL,
  bm.FCN_ID_TIPO_SUBCTA,
  bm.FCN_ID_SIEFORE,
  va.FCD_FEH_ACCION,
  va.FCN_VALOR_ACCION,
  va.FCN_ID_REGIMEN,
  va.FCN_ID_VALOR_ACCION
HAVING SUM(bm.FTN_DISP_ACCIONES) > 0
ORDER BY
  bm.FTC_NUM_CTA_INVDUAL,
  bm.FCN_ID_TIPO_SUBCTA,
  bm.FCN_ID_SIEFORE