SELECT 
FCN_ID_VALOR_ACCION,
FCD_FEH_ACCION,
FCN_VALOR_ACCION,
FCN_ID_SIEFORE,
FCN_ID_REGIMEN
FROM CIERREN.TCAFOGRAL_VALOR_ACCION 
WHERE TRUNC(FCD_FEH_ACCION)= TO_TIMESTAMP(SYSDATE)
AND FCN_ID_REGIMEN=138
AND FCN_ID_SIEFORE=81