SELECT
  FTN_NUM_CTA_INVDUAL,
  FTC_NSS,
  FTN_CONSE_REG_LOTE,
  NVL(FTN_IMP_RET_DEVOLVER, 0) AS SDO_SOL,
  1 AS BANDERA_MONTO,
  CASE WHEN NVL(FTN_IMP_RET_DEVOLVER, 0) <= 0 THEN 1 ELSE 2 END AS BANDERA_SOL,
  1 AS FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
WHERE FTC_FOLIO = '#sr_folio#'
  AND FTC_CLAVE_ENT_ORIG = 001
  AND (FCN_ID_MOTIVO_RECHAZO NOT IN (93,254,375,1178) OR FCN_ID_MOTIVO_RECHAZO IS NULL)

UNION ALL

SELECT
  FTN_NUM_CTA_INVDUAL,
  FTC_NSS,
  FTN_CONSE_REG_LOTE,
  NVL(FTN_IMP_ACT_REC_RETIRO_DEV, 0) AS SDO_SOL,
  2 AS BANDERA_MONTO,
  CASE WHEN NVL(FTN_IMP_ACT_REC_RETIRO_DEV, 0) <= 0 THEN 1 ELSE 2 END AS BANDERA_SOL,
  1 AS FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
WHERE FTC_FOLIO = '#sr_folio#'
  AND FTC_CLAVE_ENT_ORIG = 001
  AND (FCN_ID_MOTIVO_RECHAZO NOT IN (93,254,375,1178) OR FCN_ID_MOTIVO_RECHAZO IS NULL)

UNION ALL

SELECT
  FTN_NUM_CTA_INVDUAL,
  FTC_NSS,
  FTN_CONSE_REG_LOTE,
  NVL(FTN_IMP_ACT_RET_REN_CUENTA, 0) AS SDO_SOL,
  3 AS BANDERA_MONTO,
  CASE WHEN NVL(FTN_IMP_ACT_RET_REN_CUENTA, 0) <= 0 THEN 1 ELSE 2 END AS BANDERA_SOL,
  1 AS FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
WHERE FTC_FOLIO = '#sr_folio#'
  AND FTC_CLAVE_ENT_ORIG = 001
  AND (FCN_ID_MOTIVO_RECHAZO NOT IN (93,254,375,1178) OR FCN_ID_MOTIVO_RECHAZO IS NULL)

UNION ALL

SELECT
  FTN_NUM_CTA_INVDUAL,
  FTC_NSS,
  FTN_CONSE_REG_LOTE,
  NVL(FTN_IMP_CES_CUO_PATRON_DEV, 0) AS SDO_SOL,
  1 AS BANDERA_MONTO,
  CASE WHEN NVL(FTN_IMP_CES_CUO_PATRON_DEV, 0) <= 0 THEN 1 ELSE 2 END AS BANDERA_SOL,
  2 AS FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
WHERE FTC_FOLIO = '#sr_folio#'
  AND FTC_CLAVE_ENT_ORIG = 001
  AND (FCN_ID_MOTIVO_RECHAZO NOT IN (93,254,375,1178) OR FCN_ID_MOTIVO_RECHAZO IS NULL)

UNION ALL

SELECT
  FTN_NUM_CTA_INVDUAL,
  FTC_NSS,
  FTN_CONSE_REG_LOTE,
  NVL(FTN_IMP_CES_CUO_TRABAJ_DEV, 0) AS SDO_SOL,
  2 AS BANDERA_MONTO,
  CASE WHEN NVL(FTN_IMP_CES_CUO_TRABAJ_DEV, 0) <= 0 THEN 1 ELSE 2 END AS BANDERA_SOL,
  2 AS FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
WHERE FTC_FOLIO = '#sr_folio#'
  AND FTC_CLAVE_ENT_ORIG = 001
  AND (FCN_ID_MOTIVO_RECHAZO NOT IN (93,254,375,1178) OR FCN_ID_MOTIVO_RECHAZO IS NULL)

UNION ALL

SELECT
  FTN_NUM_CTA_INVDUAL,
  FTC_NSS,
  FTN_CONSE_REG_LOTE,
  NVL(FTN_IMP_ACT_REC_CUO_PAT_DEV, 0) AS SDO_SOL,
  3 AS BANDERA_MONTO,
  CASE WHEN NVL(FTN_IMP_ACT_REC_CUO_PAT_DEV, 0) <= 0 THEN 1 ELSE 2 END AS BANDERA_SOL,
  2 AS FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
WHERE FTC_FOLIO = '#sr_folio#'
  AND FTC_CLAVE_ENT_ORIG = 001
  AND (FCN_ID_MOTIVO_RECHAZO NOT IN (93,254,375,1178) OR FCN_ID_MOTIVO_RECHAZO IS NULL)

UNION ALL

SELECT
  FTN_NUM_CTA_INVDUAL,
  FTC_NSS,
  FTN_CONSE_REG_LOTE,
  NVL(FTN_IMP_ACT_REC_CUO_TRA_DEV, 0) AS SDO_SOL,
  4 AS BANDERA_MONTO,
  CASE WHEN NVL(FTN_IMP_ACT_REC_CUO_TRA_DEV, 0) <= 0 THEN 1 ELSE 2 END AS BANDERA_SOL,
  2 AS FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
WHERE FTC_FOLIO = '#sr_folio#'
  AND FTC_CLAVE_ENT_ORIG = 001
  AND (FCN_ID_MOTIVO_RECHAZO NOT IN (93,254,375,1178) OR FCN_ID_MOTIVO_RECHAZO IS NULL)

UNION ALL

SELECT
  FTN_NUM_CTA_INVDUAL,
  FTC_NSS,
  FTN_CONSE_REG_LOTE,
  NVL(FTN_IMP_ACT_REN_CUE_IND_PAT, 0) AS SDO_SOL,
  5 AS BANDERA_MONTO,
  CASE WHEN NVL(FTN_IMP_ACT_REN_CUE_IND_PAT, 0) <= 0 THEN 1 ELSE 2 END AS BANDERA_SOL,
  2 AS FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
WHERE FTC_FOLIO = '#sr_folio#'
  AND FTC_CLAVE_ENT_ORIG = 001
  AND (FCN_ID_MOTIVO_RECHAZO NOT IN (93,254,375,1178) OR FCN_ID_MOTIVO_RECHAZO IS NULL)

UNION ALL

SELECT
  FTN_NUM_CTA_INVDUAL,
  FTC_NSS,
  FTN_CONSE_REG_LOTE,
  NVL(FTN_IMP_ACT_REN_CUE_IND_TRA, 0) AS SDO_SOL,
  6 AS BANDERA_MONTO,
  CASE WHEN NVL(FTN_IMP_ACT_REN_CUE_IND_TRA, 0) <= 0 THEN 1 ELSE 2 END AS BANDERA_SOL,
  2 AS FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
WHERE FTC_FOLIO = '#sr_folio#'
  AND FTC_CLAVE_ENT_ORIG = 001
  AND (FCN_ID_MOTIVO_RECHAZO NOT IN (93,254,375,1178) OR FCN_ID_MOTIVO_RECHAZO IS NULL)

UNION ALL

SELECT
  FTN_NUM_CTA_INVDUAL,
  FTC_NSS,
  FTN_CONSE_REG_LOTE,
  NVL(FTN_IMP_CUO_SOCIAL_DEV, 0) AS SDO_SOL,
  1 AS BANDERA_MONTO,
  CASE WHEN NVL(FTN_IMP_CUO_SOCIAL_DEV, 0) <= 0 THEN 1 ELSE 2 END AS BANDERA_SOL,
  3 AS FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
WHERE FTC_FOLIO = '#sr_folio#'
  AND FTC_CLAVE_ENT_ORIG = 001
  AND (FCN_ID_MOTIVO_RECHAZO NOT IN (93,254,375,1178) OR FCN_ID_MOTIVO_RECHAZO IS NULL)

ORDER BY
  FTN_NUM_CTA_INVDUAL ASC,
  FTC_NSS ASC,
  FTN_CONSE_REG_LOTE ASC,
  BANDERA_MONTO ASC
  