 WITH FL_100_SEL_SDO_SOL AS (
    SELECT
        FTN_NUM_CTA_INVDUAL,
        FTC_NSS,
        FTN_CONSE_REG_LOTE,
        SDO_SOL,
        BANDERA_MONTO,
        BANDERA_SOL,
        FCN_ID_TIPO_SUBCTA
    FROM #DS_400_SDO_SOL_IMSS#
    WHERE SDO_SOL > 0
),
JN_200_AG_SDO_DISP AS (
    SELECT
        f.FTN_NUM_CTA_INVDUAL,
        f.FTC_NSS,
        f.FTN_CONSE_REG_LOTE,
        f.SDO_SOL,
        f.BANDERA_MONTO,
        f.BANDERA_SOL,
        f.FCN_ID_TIPO_SUBCTA,
        d.SDO_DISPONIBLE_PESOS,
        d.SDO_DISPONIBLE_ACCION,
        d.FCN_ID_SIEFORE,
        d.FCD_FEH_ACCION,
        d.FCN_VALOR_ACCION,
        d.FCN_ID_REGIMEN,
        d.FCN_ID_VALOR_ACCION
    FROM FL_100_SEL_SDO_SOL f
    LEFT JOIN #DS_101_SDO_DISP_SUBCTAS_IMSS# d
      ON f.FTN_NUM_CTA_INVDUAL = d.FTN_NUM_CTA_INVDUAL
     AND f.FCN_ID_TIPO_SUBCTA = d.FCN_ID_TIPO_SUBCTA
),
AG_400_SUM_DISP_X_CTA AS (
    SELECT
        FTN_NUM_CTA_INVDUAL,
        SUM(SDO_DISPONIBLE_PESOS) AS SDO_DISPONIBLE_X_CTA
    FROM #DS_101_SDO_DISP_SUBCTAS_IMSS#
    GROUP BY FTN_NUM_CTA_INVDUAL
),
JN_500_AG_DISP AS (
    SELECT
        j.*,
        a.SDO_DISPONIBLE_X_CTA
    FROM JN_200_AG_SDO_DISP j
    LEFT JOIN AG_400_SUM_DISP_X_CTA a
      ON j.FTN_NUM_CTA_INVDUAL = a.FTN_NUM_CTA_INVDUAL
),
FL_600_SEP_X_SUBCTA AS (
    SELECT
        FTN_NUM_CTA_INVDUAL,
        FTN_CONSE_REG_LOTE,
        SDO_SOL,
        BANDERA_MONTO,
        FCN_ID_TIPO_SUBCTA,
        FCN_ID_SIEFORE
    FROM JN_500_AG_DISP
    WHERE SDO_DISPONIBLE_X_CTA <= 0 OR SDO_DISPONIBLE_X_CTA IS NULL
)
SELECT
    s.FTN_CONSE_REG_LOTE,
    s.FTN_NUM_CTA_INVDUAL,
    s.SDO_SOL,
    s.FCN_ID_TIPO_SUBCTA,
    s.FCN_ID_SIEFORE,
    0 AS FTN_ESTATUS_indiv,
    0 AS FTN_SDO_ACCIONES,
    0 AS FTN_SDO_PESOS,
    NULL AS FTN_VALOR_AIVS,
    NULL AS FCD_FEH_ACCION,
    NULL AS FCN_ID_VALOR_ACCION,
    NULL AS FFN_ID_CONCEPTO_MOV,
    138 AS FCN_ID_REGIMEN,
    '02' AS FTC_DIAG_DEV,
    0 AS FTN_ESTATUS
FROM FL_600_SEP_X_SUBCTA s
ORDER BY
    s.FTN_NUM_CTA_INVDUAL ASC,
    s.FTN_CONSE_REG_LOTE ASC,
    s.BANDERA_MONTO ASC,
    s.FCN_ID_SIEFORE ASC
