SELECT 
  BASE.FTC_IDENTIFICADOS   ,
  BASE.FTN_NUM_CTA_INVDUAL ,
  BASE.FTN_ID_DIAGNOSTICO  ,
  BASE.FTN_ID_SUBP_NO_CONV ,
  BASE.FTC_RFC_BUC         , 
  BASE.FTC_FOLIO           , 
  BASE.FTN_ID_ARCHIVO      ,
  BASE.FTC_NSS             , 
  BASE.FTC_CURP            , 
  BASE.FTC_RFC             ,
  BASE.FTN_VIGENCIA        ,
  'D' AS MARC_DUP          ,
  --SUMA.CUENTASVIG          , 
  BASE.FTC_APELLIDO_PATER_AFORE ,
  BASE.FTC_APELLIDO_MATER_AFORE ,
  BASE.FTC_NOMBRE_AFORE    ,
  BASE.FTC_CORREO_ELEC     ,
  BASE.FTN_CELULAR         
FROM #DELTA_TABLA_NAME# BASE
LEFT JOIN (
  SELECT FTC_NSS, SUM(FTN_VIGENCIA) AS CUENTASVIG
  FROM #DELTA_TABLA_NAME# 
  GROUP BY FTC_NSS
) SUMA
ON BASE.FTC_NSS = SUMA.FTC_NSS
WHERE CUENTASVIG >1 
  AND BASE.FTN_VIGENCIA = 1

UNION

SELECT 
  BASE.FTC_IDENTIFICADOS   ,
  BASE.FTN_NUM_CTA_INVDUAL ,
  BASE.FTN_ID_DIAGNOSTICO  ,
  BASE.FTN_ID_SUBP_NO_CONV ,
  BASE.FTC_RFC_BUC         , 
  BASE.FTC_FOLIO           , 
  BASE.FTN_ID_ARCHIVO      ,
  BASE.FTC_NSS             , 
  BASE.FTC_CURP            , 
  BASE.FTC_RFC             ,
  BASE.FTN_VIGENCIA        ,
  ' ' AS MARC_DUP          ,
  --SUMA.CUENTASVIG          , 
  BASE.FTC_APELLIDO_PATER_AFORE ,
  BASE.FTC_APELLIDO_MATER_AFORE ,
  BASE.FTC_NOMBRE_AFORE    ,
  BASE.FTC_CORREO_ELEC     ,
  BASE.FTN_CELULAR         
FROM #DELTA_TABLA_NAME# BASE
LEFT JOIN (
  SELECT FTC_NSS, SUM(FTN_VIGENCIA) AS CUENTASVIG
  FROM #DELTA_TABLA_NAME# 
  GROUP BY FTC_NSS
) SUMA
ON BASE.FTC_NSS = SUMA.FTC_NSS
WHERE CUENTASVIG < 2

