SELECT 
  VI.FTC_FOLIO              ,
  VI.FTN_NUM_CTA_INVDUAL    ,
  VI.FTN_ID_ARCHIVO         ,
  VI.FTC_FOLIO_PROCESAR     ,
  VI.FTN_NSS                 	,
  VI.FTC_APELLIDO_PATERNO		,
  VI.FTC_APELLIDO_MATERNO		,
  VI.FTC_NOMBRE				,
  VI.FTC_CURP					,
  VI.FTC_TIPO_OPERACION		,
  VI.FTC_INSTITUTO_ORIGEN		,
  VI.FTC_CREDITO				,
  VI.FTN_MONTO_PESOS			,
  VI.FTN_AIVS					,
  VI.FTD_FEH_VAL_AIVS			,
  VI.FTN_TOTAL_AIVS			,
  VI.FTD_FEH_CREDITO			,
  VI.FTD_FEH_VAL_TRANSFERENCIA	,
  VI.FTC_ESTATUS_OPE			,
  VI.FTC_DIAGNOSTICO			,
  VI.FTC_MOTIVO_REC			,
  VI.FCN_ID_TIPO_SUBCTA		,
  VI.FCN_ID_SIEFORE			,
  VI.FTN_SUBPROCESO			,
  VI.FTC_MASCARA_RECEP			,
  VI.FTN_NO_LINEA				,
  VI.FTC_RFC               	,
  VI.FTN_ESTATUS_DIAG      	,
  VI.FTC_ID_DIAGNOSTICO    	,
  VI.FTN_MONTO_PESOS_92		,
  VI.FTN_AIVS_92				,
  VI.FTD_FEH_VAL_AIVS_92		,
  VI.FTN_TOTAL_AIVS_92			,
  VI.FCN_ID_TIPO_SUBCTA_92     ,
  BUC.FTC_CORREO_ELEC          ,
  BUC.FTN_CELULAR              ,
  DUP.BNDDUP                   ,
  VI.FTC_NOMBRE_CTE            ,
  VI.FTC_ID_SUBP_NO_VIG        ,
  VI.FTD_FECHA_CERTIFICACION   ,
  VI.FTN_CTE_PENSIONADO        ,
  VI.FTC_CLAVE_ENT_RECEP       ,
  VI.FTC_CLAVE_TMP
FROM #DELTA_VAL_IDENT# VI
LEFT JOIN #DELTA_BUC# BUC
  ON VI.FTN_NSS = BUC.FTN_NSS
LEFT JOIN #DELTA_DUP# DUP
   ON VI.FTN_NSS = DUP.FTN_NSS 
  AND VI.FTN_NO_LINEA = DUP.FTN_NO_LINEA
ORDER BY VI.FTN_NSS

