SELECT 
  PT.FTC_FOLIO					,
  VAL.FTN_NUM_CTA_INVDUAL    ,
  PT.FTN_ID_ARCHIVO				,
  PT.FTC_FOLIO_PROCESAR			,
  PT.FTC_NSS_IMSS AS FTN_NSS	,
  PT.FTC_APELLIDO_PATERNO		,
  PT.FTC_APELLIDO_MATERNO		,
  PT.FTC_NOMBRE					,
  PT.FTC_CURP					,
  PT.FTC_TIPO_OPERACION			,
  PT.FTC_INSTITUTO_ORIGEN		,
  PT.FTC_CREDITO				,
  PT.FTN_MONTO_PESOS			,
  PT.FTN_AIVS					,
  PT.FTD_FEH_VAL_AIVS			,
  PT.FTN_TOTAL_AIVS				,
  PT.FTD_FEH_CREDITO			,
  PT.FTD_FEH_VAL_TRANSFERENCIA	,
  PT.FTC_ESTATUS_OPE			,
  PT.FTC_DIAGNOSTICO			,
  PT.FTC_MOTIVO_REC				,
  PT.FCN_ID_TIPO_SUBCTA			,
  PT.FCN_ID_SIEFORE				,
  PT.FTN_SUBPROCESO				,
  PT.FTC_MASCARA_RECEP			,
  PT.FTN_NO_LINEA				,
  VAL.FTC_RFC               ,
  VAL.FTN_ESTATUS_DIAG      ,
  VAL.FTC_ID_DIAGNOSTICO    ,
  PT.FTN_MONTO_PESOS_92			,
  PT.FTN_AIVS_92				,
  PT.FTD_FEH_VAL_AIVS_92		,
  PT.FTN_TOTAL_AIVS_92			,
  PT.FCN_ID_TIPO_SUBCTA_92      ,
  VAL.FTC_NOMBRE_CTE        ,
  VAL.FTC_ID_SUBP_NO_VIG    ,
  VAL.FTD_FECHA_CERTIFICACION,
  VAL.FTN_CTE_PENSIONADO    ,
  VAL.FTC_CLAVE_ENT_RECEP   ,
  VAL.FTC_CLAVE_TMP
FROM CIERREN_ETL.TTAFOTRAS_ETL_TRANS_REC_PORTA PT
LEFT JOIN (
  SELECT
    FTN_NUM_CTA_INVDUAL     ,
	  FTC_RFC                 ,
    FTN_NSS,
	  FTN_ESTATUS_DIAG        ,
    FTC_ID_DIAGNOSTICO      ,
    FTC_NOMBRE_CTE          ,
    FTC_ID_SUBP_NO_VIG      ,
    FTD_FECHA_CERTIFICACION ,
    FTN_CTE_PENSIONADO      ,
    FTC_CLAVE_ENT_RECEP     ,
    FTC_CLAVE_TMP
  FROM (
    SELECT
      FTN_NUM_CTA_INVDUAL     ,
      FTN_NSS, 
      FTC_RFC                 ,
  	  FTN_ESTATUS_DIAG        ,
      FTC_ID_DIAGNOSTICO      ,
      FTC_NOMBRE_CTE          ,
      FTC_ID_SUBP_NO_VIG      ,
      FTD_FECHA_CERTIFICACION ,
      FTN_CTE_PENSIONADO      ,
      FTC_CLAVE_ENT_RECEP     ,
      FTC_CLAVE_TMP           ,
	  ROW_NUMBER() OVER (PARTITION BY FTN_NSS, FTC_ID_DIAGNOSTICO ORDER BY FTN_NSS ASC, FTC_ID_DIAGNOSTICO ASC) AS rn
    FROM CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE
    WHERE FTC_FOLIO = '#SR_FOLIO#'
    )
    --WHERE rn = 1
  ) VAL
  ON PT.FTC_NSS_IMSS = VAL.FTN_NSS
WHERE PT.FTC_FOLIO = '#SR_FOLIO#'
  AND PT.FTC_INSTITUTO_ORIGEN = '001'
 
