SELECT 
  FTC_IDENTIFICADOS   ,
  FTN_NUM_CTA_INVDUAL ,
  FTN_ID_DIAGNOSTICO  ,
  FTN_ID_SUBP_NO_CONV ,
  FTC_RFC_BUC         , 
  FTC_FOLIO           , 
  FTN_ID_ARCHIVO      ,
  FTC_NSS             , 
  FTC_CURP            , 
  FTC_RFC             ,
  FTN_VIGENCIA        , 
  FTC_APELLIDO_PATER_AFORE ,
  FTC_APELLIDO_MATER_AFORE ,
  FTC_NOMBRE_AFORE    ,
  FTC_CORREO_ELEC     ,
  FTN_CELULAR         ,
  FTC_INSTITUTO_ORIGEN
FROM #DELTA_TABLA_NAME# 
WHERE FTC_INSTITUTO_ORIGEN = '002'

