SELECT DISTINCT
     BUC.FTC_BANDERA_BUC AS FTC_BANDERA        ,
     BUC.FTN_NUM_CTA_INVDUAL_BUC AS FTN_NUM_CTA_INVDUAL ,
     BUC.FTC_RFC_BUC             ,
     D3.FTC_FOLIO                ,
     D3.FTN_ID_ARCHIVO           ,
     D3.FTC_NSS_IMSS AS FTC_NSS             ,
     D3.FTC_CURP                 ,
     " " AS FTC_RFC              ,
     D3.FTC_APELLIDO_PATERNO     ,
     D3.FTC_APELLIDO_MATERNO     ,
     D3.FTC_NOMBRE               ,
     BUC.FTC_CORREO_ELEC         ,
     BUC.FTN_CELULAR             ,
     D3.FTC_INSTITUTO_ORIGEN   
FROM      #CATALOG_SCHEMA#.DELTA_300_TRP_#SR_FOLIO# D3
LEFT JOIN #CATALOG_SCHEMA#.DELTA_200_TRP_#SR_FOLIO# BUC
   ON D3.FTC_NSS_IMSS = BUC.FTC_NSS
WHERE D3.FTC_INSTITUTO_ORIGEN = '001'

UNION 

SELECT DISTINCT
     BUC.FTC_BANDERA_BUC AS FTC_BANDERA         ,
     BUC.FTN_NUM_CTA_INVDUAL_BUC AS FTN_NUM_CTA_INVDUAL ,
     BUC.FTC_RFC_BUC             ,
     D3.FTC_FOLIO                ,
     D3.FTN_ID_ARCHIVO           ,
     D3.FTC_NSS_IMSS AS FTC_NSS            ,
     D3.FTC_CURP                 ,
     " " AS FTC_RFC              ,
     D3.FTC_APELLIDO_PATERNO     ,
     D3.FTC_APELLIDO_MATERNO     ,
     D3.FTC_NOMBRE               ,
     BUC.FTC_CORREO_ELEC         ,
     BUC.FTN_CELULAR             ,
     D3.FTC_INSTITUTO_ORIGEN   
FROM      #CATALOG_SCHEMA#.DELTA_300_TRP_#SR_FOLIO# D3
LEFT JOIN #CATALOG_SCHEMA#.DELTA_200_TRP_#SR_FOLIO# BUC
  ON D3.FTC_CURP = BUC.FTC_CURP_BUC
WHERE D3.FTC_INSTITUTO_ORIGEN = '002'