SELECT 
   FTC_NSS_IMSS AS FTN_NSS ,
   FTC_CURP                ,
   FTN_NO_LINEA            ,
   CASE ROW_NUMBER() OVER (PARTITION BY FTC_NSS_IMSS, FTC_CURP, FTN_NO_LINEA ORDER BY FTC_NSS_IMSS ASC, FTC_CURP ASC, FTN_NO_LINEA ASC) 
     WHEN 1 THEN 1
     ELSE 0 END AS BNDDUP
FROM CIERREN_ETL.TTAFOTRAS_ETL_TRANS_REC_PORTA
WHERE FTC_FOLIO = '#SR_FOLIO#'
  AND FTC_INSTITUTO_ORIGEN IN ('001', '002')
ORDER BY FTC_NSS_IMSS, FTC_CURP, FTN_NO_LINEA

