SELECT 
   FCN_ID_IND_CTA_INDV   ,
   FTN_NUM_CTA_INVDUAL   ,
   FFN_ID_CONFIG_INDI    ,
   FCC_VALOR_IND         ,
   FTC_VIGENCIA          ,
   FTN_DETALLE
FROM #DELTA_TABLA_NAME#
WHERE FFN_ID_CONFIG_INDI = '2'
ORDER BY FTN_NUM_CTA_INVDUAL

