SELECT
C.FCN_ID_IND_CTA_INDV,
C.FTN_NUM_CTA_INVDUAL,
C.FFN_ID_CONFIG_INDI,
C.FCC_VALOR_IND,
C.FTC_VIGENCIA,
C.FTN_DETALLE,
C.FTD_FEH_REG
FROM ( SELECT B.FTN_NUM_CTA_INVDUAL
             FROM ( SELECT FTC_NSS_IMSS, FTC_CURP
                        FROM CIERREN_ETL.TTAFOTRAS_ETL_TRANS_REC_PORTA
                        WHERE FTC_FOLIO=#SR_FOLIO#
                        AND FTC_INSTITUTO_ORIGEN = '001') A 
	LEFT JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC B ON (A.FTC_NSS_IMSS=B.FTC_NSS))B, 
            CIERREN.TTAFOGRAL_IND_CTA_INDV C
             WHERE B.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
             AND C.FFN_ID_CONFIG_INDI IN (2,5,25) AND FTC_VIGENCIA=1
UNION
SELECT
C.FCN_ID_IND_CTA_INDV,
C.FTN_NUM_CTA_INVDUAL,
C.FFN_ID_CONFIG_INDI,
C.FCC_VALOR_IND,
C.FTC_VIGENCIA,
C.FTN_DETALLE,
C.FTD_FEH_REG
FROM ( SELECT B.FTN_NUM_CTA_INVDUAL
             FROM ( SELECT FTC_NSS_IMSS, FTC_CURP
                        FROM CIERREN_ETL.TTAFOTRAS_ETL_TRANS_REC_PORTA
                        WHERE FTC_FOLIO=#SR_FOLIO#
                        AND FTC_INSTITUTO_ORIGEN = '002') A 
			LEFT JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC B ON (A.FTC_CURP=B.FTC_CURP))B, 
            CIERREN.TTAFOGRAL_IND_CTA_INDV C
             WHERE B.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
             AND C.FFN_ID_CONFIG_INDI IN (2,5,25) AND FTC_VIGENCIA=1

