SELECT
   FTC_FOLIO                 ,
   FTN_NUM_CTA_INVDUAL       ,
   FTN_ID_ARCHIVO            ,
   FTC_FOLIO_PROCESAR        ,
   FTC_NSS_IMSS              ,
   FTC_APELLIDO_PATERNO      ,
   FTC_APELLIDO_MATERNO      ,
   FTC_NOMBRE                ,
   FTC_CURP                  ,
   FTC_TIPO_OPERACION        ,
   FTC_INSTITUTO_ORIGEN      ,
   FTC_CREDITO               ,
   FTN_MONTO_PESOS           ,
   FTN_AIVS                  ,
   FTD_FEH_VAL_AIVS          ,
   FTN_TOTAL_AIVS            ,
   FTD_FEH_CREDITO           ,
   FTD_FEH_VAL_TRANSFERENCIA ,
   FTC_ESTATUS_OPE           ,
   FTC_MOTIVO_REC            ,
   FCN_ID_TIPO_SUBCTA        ,
   FCN_ID_SIEFORE            ,
   FTN_SUBPROCESO            ,
   FTC_CELULAR               ,
   FTC_CORREO_ELEC           ,
   FTC_MASCARA_RECEP         ,
   FTD_FEH_CRE               ,
   FTC_USU_CRE               ,
   FTC_RFC                   ,
   FTN_NO_LINEA              ,
   FTN_MONTO_PESOS_92        ,
   FTN_AIVS_92               ,
   FTD_FEH_VAL_AIVS_92       ,
   FTN_TOTAL_AIVS_92         ,
   FCN_ID_TIPO_SUBCTA_92     
FROM #DELTA_CARGA_1# 

