SELECT
      FCN_ID_SIEFORE AS FCN_CVE_SIEFORE,
      FTN_CTA_AFORE AS FTN_NUM_CTA_INVDUAL,
      FTC_DIG_VERI,
      FFN_COD_MOV_ITG AS FFN_COD_MOV_ITGY,
      FTC_NSS_AFORE AS FNN_NSS_ISSSTE_SUA,
      FTD_FEH_CRE AS FND_FEH_CRE_SUA,
      FTN_ID_ARCHIVO,
      FTD_FEH_LIQUIDACION,
      FCN_VALOR_ACCION,
      FND_FECTRA_SUA,
      CASE 
        WHEN #sr_subproceso# = 348 THEN '666'
        WHEN #sr_subproceso# = 349 THEN '860'
        ELSE '000'
      END as FNN_SECLOT_SUA,
      FNN_ID_REFERENCIA,
      FTC_FOLIO,
      FND_FECHA_PAGO_SUA,
      FNC_PERIODO_PAGO_PATRON,
      FND_FECHA_VALOR_IMSS_ACV_VIV AS FNC_REG_PATRN_IMSS_SUA,
      FND_FECHA_VALOR_IMSS_ACV_VIV,
      FTF_MONPES1,
      FTF_MONCUO1,
      FTF_MONPES2,
      FTF_MONCUO2,
      FTF_MONPES3,
      FTF_MONCUO3,
      FTF_MONPES4,
      FTF_MONCUO4,
      FTF_MONPES5,
      FTF_MONCUO5,
      FTF_MONPES6,
      FTF_MONCUO6,
      FTF_MONPES7,
      FTF_MONCUO7,
      FTF_MONPES8,
      FTF_MONCUO8,
      FTF_MONPES9,
      FTF_MONCUO9,
      FND_FECHA_1,
      FND_FECHA_2,
      FND_FECHA_VALOR_RCV,
      FND_FECVGUB,
      CASE
        WHEN #sr_subproceso# IN (347, 348, 349, 351, 354, 364, 365, 368, 3832)
          OR (#sr_subproceso# = 3286 AND FTC_INSTITUTO_ORIGEN = '001')
        THEN '01'
        ELSE '02'
      END AS FNC_CVESERV,
      FNC_VARMAX
    FROM #DELTA_TABLA_NAME1# J