SELECT
  FTN_CONTA_SERV,
  FTN_NUM_CTA_INVDUAL,
  FTC_ESTATUS_OPE,
  FTC_FOLIO,
  FTN_IND_SDO_DISP_92 AS Indicador_Saldo_Disp,
  FCN_ID_TIPO_SUBCTA_92 AS FCN_ID_TIPO_SUBCTA,
  FTN_SDO_AIVS_92 AS FTN_SDO_AIVS,
  FTN_MONTO_PESOS_92 AS FTN_MONTO_PESOS,
  FTN_ID_SUBP
FROM #DELTA_300_JOIN_CTA_INDV#
WHERE (FCN_ID_TIPO_SUBCTA_92 = 16 OR FCN_ID_TIPO_SUBCTA_92 = 17) AND FTN_IND_SDO_DISP_92 = 1
