SELECT
    r.FTN_NO_LINEA AS FTN_CONTA_SERV,
    r.FTN_NUM_CTA_INVDUAL,
    r.FTC_ESTATUS_OPE,
    r.FTC_FOLIO,
    l.FTN_IND_SDO_DISP_VIV97,
    l.FCN_ID_TIPO_SUBCTA_97,
    l.FTN_SDO_AIVS,
    l.FTN_MONTO_PESOS,
    l.FTN_IND_SDO_DISP_92,
    l.FCN_ID_TIPO_SUBCTA_92,
    l.FTN_SDO_AIVS_92,
    l.FTN_MONTO_PESOS_92,
    l.FTN_ID_SUBP
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA r 
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS l ON l.FTN_NUM_CTA_INVDUAL = r.FTN_NUM_CTA_INVDUAL AND l.FTN_CONTA_SERV = r.FTN_NO_LINEA
WHERE (l.FTC_FOLIO_BITACORA = #SR_FOLIO# AND l.FTN_ID_SUBP = #SR_SUBPROCESO#) AND (r.FTC_FOLIO = #SR_FOLIO# AND r.FTN_SUBPROCESO = #SR_SUBPROCESO#)
