WITH AGG200 AS (
  SELECT
    D600.FTC_ESTATUS_OPE AS FTC_ESTATUS_REGISTRO,
    D600.FTC_FOLIO AS FTC_FOLIO_BITACORA,
    D600.FCN_ID_TIPO_SUBCTA AS FCN_ID_TIPO_SUBCTA,
    D600.Indicador_Saldo_Disp,
    P.CONTEO_TOTAL,
    P.CONTEO_RECHAZO,
    SUM(NVL(D600.FTN_MONTO_PESOS,0)) AS FTN_MONTO_PESOS_ACEP,
    SUM(NVL(D600.FTN_SDO_AIVS,0)) AS FTN_SDO_AIVS_ACEP,
    SUM(NVL(D600.Constante,0)) AS Contar
  FROM #DELTA_600# D600
  LEFT JOIN #DELTA_PROC_CONTEO# P ON D600.FTC_FOLIO = P.FTC_FOLIO
  GROUP BY D600.Indicador_Saldo_Disp, D600.FCN_ID_TIPO_SUBCTA, D600.FTC_ESTATUS_OPE, D600.FTC_FOLIO,P.CONTEO_RECHAZO,P.CONTEO_TOTAL
  ORDER BY D600.FTC_FOLIO, D600.FTC_ESTATUS_OPE)
  SELECT
    a.Indicador_Saldo_Disp,
    a.FCN_ID_TIPO_SUBCTA,
    a.FTC_ESTATUS_REGISTRO,
    a.FTC_FOLIO_BITACORA,
    a.CONTEO_TOTAL,
    a.CONTEO_RECHAZO,
    a.FTN_MONTO_PESOS_ACEP,
    a.FTN_SDO_AIVS_ACEP,
    a.Contar,
    t.FRN_ID_MOV_SUBCTA
    FROM AGG200 a LEFT JOIN #DELTA_MOV_SUBMARCA# t ON a.FCN_ID_TIPO_SUBCTA = t.FCN_ID_TIPO_SUBCTA ORDER BY a.FTC_FOLIO_BITACORA, a.FTC_ESTATUS_REGISTRO