SELECT
  DISTINCT
  #SR_FOLIO# AS FTC_FOLIO,
  #SR_PROCESO# AS FCN_ID_PROCESO,
  #SR_SUBPROCESO# AS FCN_ID_SUBPROCESO,
  CONTEO_TOTAL AS FLN_TOTAL_REGISTROS,
  (CONTEO_TOTAL - CONTEO_RECHAZO) AS FLN_REG_ACEPTADOS,
  CONTEO_RECHAZO AS FLN_REG_RECHAZADOS,
  from_utc_timestamp(current_timestamp(), 'America/Mexico_City') AS FLD_FEC_REG,
  '#USUARIO#' AS FLC_USU_REG
FROM #DELTA_JO_400#