SELECT
  #SR_FOLIO# AS FTC_FOLIO,
  FRN_ID_MOV_SUBCTA AS FFN_ID_CONCEPTO_IMP,
  81 AS FCN_ID_SIEFORE,
  SUM(CASE WHEN FTC_ESTATUS_REGISTRO = '01' THEN FTN_MONTO_PESOS_ACEP ELSE 0 END) AS FTN_IMPORTE_ACEP_PESOS,
  SUM(CASE WHEN FTC_ESTATUS_REGISTRO = '02' THEN FTN_MONTO_PESOS_ACEP ELSE 0 END) AS FTN_IMPORTE_RECH_PESOS,
  SUM(CASE WHEN FTC_ESTATUS_REGISTRO = '01' THEN FTN_SDO_AIVS_ACEP ELSE 0 END) AS FTN_IMPORTE_ACEP_AIVS,
  SUM(CASE WHEN FTC_ESTATUS_REGISTRO = '02' THEN FTN_SDO_AIVS_ACEP ELSE 0 END) AS FTN_IMPORTE_RECH_AIVS,
  CONTEO_TOTAL AS FTN_NUM_REG,
  CONTEO_RECHAZO AS FTN_NUM_REG_RECH,
  from_utc_timestamp(current_timestamp(), 'America/Mexico_City') AS FTD_FEC_REG,
  '#USUARIO#' AS FTC_USU_REG
  FROM #DELTA_JO_400#
  GROUP BY FFN_ID_CONCEPTO_IMP, FTC_FOLIO, CONTEO_TOTAL, CONTEO_RECHAZO