-- Registros para el INSERT de suficencia de saldos antes de insertar
SELECT 
    FTN_NUM_CTA_INVDUAL,
    FTN_IND_SDO_DISP_VIV97,
    SALDO_DISPONIBLE_AIVS AS FTN_SDO_AIVS,
    FCN_VALOR_ACCION AS FTN_VALOR_AIVS,
    SALDO_DISPONIBLE_PESOS AS FTN_MONTO_PESOS,
    CASE 
        WHEN FTN_IND_SDO_DISP_VIV97 = 0 THEN 0 
        ELSE 1 
    END AS FCN_ESTATUS,
    CURRENT_TIMESTAMP() AS FTD_FEH_CRE,
    "DATABRICKS" AS FTC_USU_CRE,
    '#sr_folio#' AS FTC_FOLIO_BITACORA,
    '138' AS FCN_ID_REGIMEN,
    '15' AS FCN_ID_TIPO_SUBCTA_97,
    CASE 
        WHEN FTN_IND_SDO_DISP_VIV97 = 0 THEN 500 
        ELSE NULL 
    END AS FTN_MOTI_RECH,
    FTN_ID_SUBP,
    FCN_ID_VALOR_ACCION,
    FTN_CONTA_SERV
FROM 
    #DELTA_TABLE_INSERT# D