SELECT
    a.FTD_FEH_PRESEN,
    a.FECHA_VALOR_ACCION,
    a.FTC_CURP,
    a.FTC_NSS_INFONA,
    a.FTN_NUM_CTA_INVDUAL,
    a.FTC_RFC_INFONA,
    a.FTC_APELLIDO_PATER_INFONA,
    a.FTC_APELLIDO_MATER_INFONA,
    a.FTC_NOMBRE_INFONA,
    a.FTC_IDENTI_LOTE_SOLIC,
    a.FTC_NSS_AFORE,
    a.FTC_RFC_AFORE,
    a.FTC_APELLIDO_PATER_AFORE,
    a.FTC_APELLIDO_MATER_AFORE,
    a.FTC_NOMBRE_AFORE,
    a.FTN_SALDO_97,
    a.FTN_SALDO_92,
    a.FTC_CODIGO_RES_OPER,
    a.FTC_DIAGNOS_PROCE,
    a.FTC_NOMBRE_IMSS,
    a.FTN_NUM_CRED_INFONA,
    a.FTN_INTERES_SALDO_97,
    a.FTN_INTERES_SALDO_92,
    a.FTN_PERIODO_PAGO,
    a.FTD_FEH_CARGA,
    a.FTC_FOLIO_BITACORA,
    a.FTN_ID_SUBP,
    a.FTN_CONTA_SERV,
    b.SALDO_DISPONIBLE_AIVS  -- Field from aggregate subquery
FROM
    (SELECT DISTINCT
        FTD_FEH_PRESEN,
        TRUNC(FTD_FEH_PRESEN, 'MM') AS FECHA_VALOR_ACCION,
        FTC_CURP,
        FTC_NSS_INFONA,
        FTN_CTA_AFORE AS FTN_NUM_CTA_INVDUAL,
        FTC_RFC_INFONA,
        FTC_APELLIDO_PATER_INFONA,
        FTC_APELLIDO_MATER_INFONA,
        FTC_NOMBRE_INFONA,
        FTC_IDENTI_LOTE_SOLIC,
        FTC_NSS_AFORE,
        FTC_RFC_AFORE,
        FTC_APELLIDO_PATER_AFORE,
        FTC_APELLIDO_MATER_AFORE,
        FTC_NOMBRE_AFORE,
        FTN_SALDO_97,
        FTN_SALDO_92,
        FTC_CODIGO_RES_OPER,
        FTC_DIAGNOS_PROCE,
        FTC_NOMBRE_IMSS,
        FTN_NUM_CRED_INFONA,
        FTN_INTERES_SALDO_97,
        FTN_INTERES_SALDO_92,
        FTN_PERIODO_PAGO,
        FTD_FEH_CARGA,
        FTC_FOLIO_BITACORA,
        FTN_ID_SUBP,
        FTN_CONTA_SERV
     FROM PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
     WHERE FTC_FOLIO_BITACORA = '#sr_folio#'
     AND FTC_ESTA_REGI=0
AND ((FTN_MOTI_RECH <> 93)
AND   (FTN_MOTI_RECH <> 254)
AND  (FTN_MOTI_RECH <> 375) 
AND  (FTN_MOTI_RECH <> 1178)
AND (FTN_MOTI_RECH <> 4437)
OR (FTN_MOTI_RECH IS NULL))
          ) a
LEFT JOIN 
    (SELECT FTC_NUM_CTA_INVDUAL, SUM(FTN_DISP_ACCIONES) AS SALDO_DISPONIBLE_AIVS
     FROM CIERREN.TTAFOGRAL_BALANCE_MOVS
     WHERE FCN_ID_SIEFORE = 81
     AND FCN_ID_TIPO_SUBCTA = 15
     GROUP BY FTC_NUM_CTA_INVDUAL) b
ON 
    a.FTN_NUM_CTA_INVDUAL = b.FTC_NUM_CTA_INVDUAL