-- Registros para el merge de desmarca marca:

MERGE INTO PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO  TGT
USING (
    SELECT DISTINCT
        FTN_MOTI_RECH,
        FTN_CTA_AFORE,
        FTC_FOLIO_BITACORA,
        FTC_ESTA_REGI,
        FTD_ACTU_ESTA,
        FTD_FEH_ACT,
        FCC_USU_ACT,
        FTN_CONTA_SERV
    FROM CIERREN_DATAUX.TTCRXGRAL_MARCA_DESMARCA_INFO_AUX
    WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'
) SRC
ON (
    TGT.FTC_FOLIO_BITACORA = SRC.FTC_FOLIO_BITACORA
    AND TGT.FTN_CTA_AFORE = SRC.FTN_CTA_AFORE
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTN_MOTI_RECH   = SRC.FTN_MOTI_RECH,
        TGT.FTC_ESTA_REGI   = SRC.FTC_ESTA_REGI,
        TGT.FTD_ACTU_ESTA   = SRC.FTD_ACTU_ESTA,
        TGT.FTD_FEH_ACT     = SYSDATE,
        TGT.FCC_USU_ACT     = 'DATABRICKS',
        TGT.FTN_CONTA_SERV  = SRC.FTN_CONTA_SERV
WHEN NOT MATCHED THEN
    INSERT (
        FTN_MOTI_RECH,
        FTN_CTA_AFORE,
        FTC_FOLIO_BITACORA,
        FTC_ESTA_REGI,
        FTD_ACTU_ESTA,
        FTD_FEH_ACT,
        FCC_USU_ACT,
        FTN_CONTA_SERV
    )
    VALUES (
        SRC.FTN_MOTI_RECH,
        SRC.FTN_CTA_AFORE,
        SRC.FTC_FOLIO_BITACORA,
        SRC.FTC_ESTA_REGI,
        SRC.FTD_ACTU_ESTA,
        SYSDATE,
        'DATABRICKS',
        SRC.FTN_CONTA_SERV
    )