-- Registros para el Update de suficencia de saldos antes de insertar
SELECT 
	CASE 
        WHEN FTN_IND_SDO_DISP_VIV97 <= 0 THEN 500 
        ELSE NULL 
    END AS FTN_MOTI_RECH,
	FTN_NUM_CTA_INVDUAL AS FTN_CTA_AFORE,
	FTC_FOLIO_BITACORA,
	'0' AS FTC_ESTA_REGI,
	CURRENT_DATE() AS FTD_ACTU_ESTA,
    CURRENT_TIMESTAMP() AS FTD_FEH_ACT,
    'DATABRICKS' AS FCC_USU_ACT,
    FTN_CONTA_SERV
FROM 
    #DELTA_TABLE_UPDATE# D
	WHERE FTN_IND_SDO_DISP_VIV97 <= 0