MERGE INTO PROCESOS.TTCRXGRAL_TRANS_INFONA T1
USING (

SELECT distinct
 FTC_FOLIO_1
,FCN_ID_SUBPROCESO_1
,FTN_NUM_CTA_INVDUAL_1
,FTC_ESTA_REGI_1
,FTD_ACTU_ESTA_1
,FTN_MOTI_RECH_1
,FTD_FEH_ACT_1
,FCC_USU_ACT_1
,SALD.FTN_CONTA_SERV AS FTN_CONTA_SERV_1
FROM(
SELECT DISTINCT
 FTC_FOLIO AS FTC_FOLIO_1
,FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO_1 
,FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_1
,FCN_ID_TIPO_SUBCTA
,0 AS FTC_ESTA_REGI_1
,SYSDATE AS FTD_ACTU_ESTA_1
,FTN_ID_SUBPROC_NO_CONV AS FTN_MOTI_RECH_1
,SYSDATE AS FTD_FEH_ACT_1
,'#sr_usuario#' AS FCC_USU_ACT_1
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV MCV
WHERE (FTC_FOLIO_REL = #sr_folio# OR FTC_FOLIO =#sr_folio#)  AND FTB_ESTATUS_MARCA <> FCN_CONV_INGTY

UNION ALL 

SELECT DISTINCT
 FTC_FOLIO AS FTC_FOLIO_1
,FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO_1 
,FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_1
,FCN_ID_TIPO_SUBCTA
,0 AS FTC_ESTA_REGI_1
,SYSDATE AS FTD_ACTU_ESTA_1
,FTN_ID_SUBPROC_NO_CONV AS FTN_MOTI_RECH_1
,SYSDATE AS FTD_FEH_ACT_1
,'#sr_usuario#' AS FCC_USU_ACT_1
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV MCV
WHERE (FTC_FOLIO_REL = #sr_folio# OR FTC_FOLIO = #sr_folio#)  AND FTB_ESTATUS_MARCA=0 AND FCN_CONV_INGTY=0

UNION ALL

SELECT DISTINCT
 FTC_FOLIO AS FTC_FOLIO_1
,FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO_1 
,FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_1
,FCN_ID_TIPO_SUBCTA
,1 AS FTC_ESTA_REGI_1
,SYSDATE AS FTD_ACTU_ESTA_1
,NULL AS FTN_MOTI_RECH_1
,SYSDATE AS FTD_FEH_ACT_1
,'#sr_usuario#' AS FCC_USU_ACT_1
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV MCV
WHERE (FTC_FOLIO_REL = #sr_folio# OR FTC_FOLIO = #sr_folio#)  AND FTB_ESTATUS_MARCA=1 AND FCN_CONV_INGTY=1
)XV INNER JOIN (
select distinct
A.FTC_FOLIO_BITACORA
,A.FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL 
,A.FTN_ID_SUBP 
,X.FCN_ID_TIPO_SUBCTA_97 AS FCN_ID_TIPO_SUBCTA
,X.FTN_CONTA_SERV
from  PROCESOS.TTCRXGRAL_TRANS_INFONA A
LEFT OUTER JOIN  PROCESOS.TTSISGRAL_SUF_SALDOS X
ON A.FTC_FOLIO_BITACORA=X.FTC_FOLIO_BITACORA
AND A.FTN_NUM_CTA_AFORE=X.FTN_NUM_CTA_INVDUAL
AND A.FTN_CONTA_SERV=X.FTN_CONTA_SERV
where
A.FTC_FOLIO_BITACORA=#sr_folio#
and  A.FTN_ID_SUBP=#sr_subproceso#
AND X.FTN_IND_SDO_DISP_VIV97=1

UNION ALL

select DISTINCT
A.FTC_FOLIO_BITACORA
,A.FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL 
,A.FTN_ID_SUBP 
,X.FCN_ID_TIPO_SUBCTA_92 AS FCN_ID_TIPO_SUBCTA
,X.FTN_CONTA_SERV
from  PROCESOS.TTCRXGRAL_TRANS_INFONA A
LEFT OUTER JOIN  PROCESOS.TTSISGRAL_SUF_SALDOS X
ON A.FTC_FOLIO_BITACORA=X.FTC_FOLIO_BITACORA
AND A.FTN_NUM_CTA_AFORE=X.FTN_NUM_CTA_INVDUAL
AND A.FTN_CONTA_SERV=X.FTN_CONTA_SERV
where
A.FTC_FOLIO_BITACORA=#sr_folio#
and  A.FTN_ID_SUBP=#sr_subproceso#
AND X.FTN_IND_SDO_DISP_92=1

)SALD
ON XV.FTC_FOLIO_1=SALD.FTC_FOLIO_BITACORA
AND XV.FTN_NUM_CTA_INVDUAL_1=SALD.FTN_NUM_CTA_INVDUAL
AND XV.FCN_ID_SUBPROCESO_1=SALD.FTN_ID_SUBP
AND XV.FCN_ID_TIPO_SUBCTA=SALD.FCN_ID_TIPO_SUBCTA

)MC
ON( T1.FTC_FOLIO_BITACORA=MC.FTC_FOLIO_1
AND T1.FTN_ID_SUBP=MC.FCN_ID_SUBPROCESO_1 
AND T1.FTN_NUM_CTA_AFORE=MC.FTN_NUM_CTA_INVDUAL_1
AND T1.FTN_CONTA_SERV=MC.FTN_CONTA_SERV_1)
WHEN MATCHED THEN 
UPDATE SET 
T1.FTC_ESTATUS_REGISTRO=MC.FTC_ESTA_REGI_1,
T1.FTD_FEH_ACTUA_ESTATUS=MC.FTD_ACTU_ESTA_1,
T1.FTN_MOTIVO_RECHAZO=MC.FTN_MOTI_RECH_1,
T1.FTD_FEH_ACT=MC.FTD_FEH_ACT_1,
T1.FCC_USU_ACT=MC.FCC_USU_ACT_1




 