MERGE INTO  PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE T1
USING(
SELECT
DISTINCT
 FTC_FOLIO_1
,FCN_ID_SUBPROCESO_1
,FTN_NUM_CTA_INVDUAL_1
,FTC_ESTATUS_REGISTRO
,FTD_ACTU_ESTA_1
,FTN_MOTI_RECH_1
,FTD_FEH_ACT_1
,FCC_USU_ACT_1
,SALD.FTN_CONTA_SERV AS FTN_CONTA_SERV_1
FROM (SELECT DISTINCT
 CV.FTC_FOLIO AS FTC_FOLIO_1
,CV.FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO_1
,CV.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_1
,0 AS FTC_ESTATUS_REGISTRO
,FCN_ID_TIPO_SUBCTA
,CURRENT_DATE AS FTD_ACTU_ESTA_1
,FTN_ID_SUBPROC_NO_CONV  AS FTN_MOTI_RECH_1
,SYSDATE AS FTD_FEH_ACT_1
,'#sr_usuario#' AS FCC_USU_ACT_1
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV CV
WHERE (CV.FTC_FOLIO_REL =#sr_folio#  OR CV.FTC_FOLIO =#sr_folio#) AND FTB_ESTATUS_MARCA <> FCN_CONV_INGTY

UNION ALL

SELECT DISTINCT
 CV.FTC_FOLIO AS FTC_FOLIO_1
,CV.FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO_1
,CV.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_1
,0 AS FTC_ESTATUS_REGISTRO
,FCN_ID_TIPO_SUBCTA
,CURRENT_DATE AS FTD_ACTU_ESTA_1
,FTN_ID_SUBPROC_NO_CONV  AS FTN_MOTI_RECH_1
,SYSDATE AS FTD_FEH_ACT_1
,'#sr_usuario#' AS FCC_USU_ACT_1
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV CV
WHERE (CV.FTC_FOLIO_REL =#sr_folio#  OR CV.FTC_FOLIO =#sr_folio#) AND FTB_ESTATUS_MARCA=0 AND FCN_CONV_INGTY=0

UNION ALL

SELECT DISTINCT
 CV.FTC_FOLIO AS FTC_FOLIO_1
,CV.FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO_1
,CV.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_1
,1 AS FTC_ESTATUS_REGISTRO
,FCN_ID_TIPO_SUBCTA
,CURRENT_DATE AS FTD_ACTU_ESTA_1
,NULL  AS FTN_MOTI_RECH_1
,SYSDATE AS FTD_FEH_ACT_1
,'#sr_usuario#' AS FCC_USU_ACT_1
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV CV
WHERE (CV.FTC_FOLIO_REL =#sr_folio#  OR CV.FTC_FOLIO =#sr_folio#) AND FTB_ESTATUS_MARCA=1 AND FCN_CONV_INGTY=1
)XV
INNER JOIN (

select DISTINCT
A.FTC_FOLIO
,A.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL 
,A.FCN_ID_SUBPROCESO
,X.FCN_ID_TIPO_SUBCTA_97 AS FCN_ID_TIPO_SUBCTA
,A.FTN_CONTA_SERV
from  PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE  A
LEFT OUTER JOIN  PROCESOS.TTSISGRAL_SUF_SALDOS X
ON A.FTC_FOLIO=X.FTC_FOLIO_BITACORA  
AND A.FTN_NUM_CTA_INVDUAL=X.FTN_NUM_CTA_INVDUAL
AND A.FTN_CONTA_SERV=X.FTN_CONTA_SERV
where
A.FTC_FOLIO=#sr_folio#
and  A.FCN_ID_SUBPROCESO=#sr_subproceso#
AND X.FTN_IND_SDO_DISP_VIV97=1

UNION ALL

select DISTINCT
A.FTC_FOLIO
,A.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL 
,A.FCN_ID_SUBPROCESO
,X.FCN_ID_TIPO_SUBCTA_92 AS FCN_ID_TIPO_SUBCTA
,A.FTN_CONTA_SERV
from  PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE  A
LEFT OUTER JOIN  PROCESOS.TTSISGRAL_SUF_SALDOS X
ON A.FTC_FOLIO=X.FTC_FOLIO_BITACORA  
AND A.FTN_NUM_CTA_INVDUAL=X.FTN_NUM_CTA_INVDUAL
AND A.FTN_CONTA_SERV=X.FTN_CONTA_SERV
where
A.FTC_FOLIO=#sr_folio#
and  A.FCN_ID_SUBPROCESO=#sr_subproceso#
AND X.FTN_IND_SDO_DISP_92=1

)SALD
ON XV.FTC_FOLIO_1=SALD.FTC_FOLIO
AND XV.FTN_NUM_CTA_INVDUAL_1=SALD.FTN_NUM_CTA_INVDUAL
AND XV.FCN_ID_SUBPROCESO_1=SALD.FCN_ID_SUBPROCESO
AND XV.FCN_ID_TIPO_SUBCTA=SALD.FCN_ID_TIPO_SUBCTA

)MC ON( T1.FTC_FOLIO=MC.FTC_FOLIO_1
AND T1.FCN_ID_SUBPROCESO=MC.FCN_ID_SUBPROCESO_1
AND T1.FTN_NUM_CTA_INVDUAL=MC.FTN_NUM_CTA_INVDUAL_1
AND T1.FTN_CONTA_SERV=MC.FTN_CONTA_SERV_1)
WHEN MATCHED THEN 
UPDATE SET 
T1.FTC_ESTATUS=MC.FTC_ESTATUS_REGISTRO,
T1.FTN_MOTIVO_RECHAZO=MC.FTN_MOTI_RECH_1,
T1.FTD_FEH_ACT=MC.FTD_FEH_ACT_1,
T1.FCC_USU_ACT=MC.FCC_USU_ACT_1
 