MERGE INTO PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO T1
USING (
SELECT DISTINCT
 CV.FTC_FOLIO AS FTC_FOLIO_1
,FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO_1 
,CV.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_1
,0 AS FTC_ESTA_REGI_1
,CURRENT_DATE AS FTD_ACTU_ESTA_1
,FTN_ID_SUBPROC_NO_CONV AS FTN_MOTI_RECH_1
,SYSDATE AS FTD_FEH_ACT_1
,'#sr_usuario#' AS FCC_USU_ACT_1
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV CV
INNER JOIN (SELECT DISTINCT FTC_FOLIO,FTN_NUM_CTA_INVDUAL

FROM CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ PREM WHERE (PREM.FTC_FOLIO_REL = #sr_folio# OR PREM.FTC_FOLIO = #sr_folio#) 
)PREMA ON PREMA.FTC_FOLIO=CV.FTC_FOLIO AND PREMA.FTN_NUM_CTA_INVDUAL=cv.ftn_num_cta_invdual
WHERE (CV.FTC_FOLIO_REL = #sr_folio# OR CV.FTC_FOLIO = #sr_folio#)  AND FTB_ESTATUS_MARCA = 0

UNION ALL

SELECT DISTINCT
 CV.FTC_FOLIO AS FTC_FOLIO_1
,FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO_1 
,CV.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_1
,1 AS FTC_ESTA_REGI_1
,CURRENT_DATE AS FTD_ACTU_ESTA_1
,NULL AS FTN_MOTI_RECH_1
,SYSDATE AS FTD_FEH_ACT_1
,'#sr_usuario#' AS FCC_USU_ACT_1
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV CV
INNER JOIN (SELECT DISTINCT FTC_FOLIO,FTN_NUM_CTA_INVDUAL

FROM CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ PREM WHERE (PREM.FTC_FOLIO_REL = #sr_folio# OR PREM.FTC_FOLIO = #sr_folio#) 
)PREMA ON PREMA.FTC_FOLIO=CV.FTC_FOLIO AND PREMA.FTN_NUM_CTA_INVDUAL=cv.ftn_num_cta_invdual
WHERE (CV.FTC_FOLIO_REL = #sr_folio# OR CV.FTC_FOLIO = #sr_folio#)  AND FTB_ESTATUS_MARCA = 1

)MC
ON( T1.FTC_FOLIO_BITACORA=MC.FTC_FOLIO_1
AND T1.FTN_ID_SUBP=MC.FCN_ID_SUBPROCESO_1
AND T1.FTN_CTA_AFORE=MC.FTN_NUM_CTA_INVDUAL_1

)
WHEN MATCHED THEN 
UPDATE SET 
T1.FTC_ESTA_REGI=MC.FTC_ESTA_REGI_1,
T1.FTN_MOTI_RECH=MC.FTN_MOTI_RECH_1,
T1.FTD_FEH_ACT=MC.FTD_FEH_ACT_1,
T1.FCC_USU_ACT=MC.FCC_USU_ACT_1
WHERE T1.FTC_ESTA_REGI=1



 