MERGE INTO PROCESOS.TTCRXGRAL_DEV_PAG_SJL T1
USING (
SELECT DISTINCT
 C.FTC_FOLIO AS FTC_FOLIO_1
,C.FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO_1
,C.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_1
,0 AS FTC_ESTATUS_REGISTRO
,CURRENT_DATE AS FTD_ACTU_ESTA_1
,FTN_ID_SUBPROC_NO_CONV  AS FTN_MOTI_RECH_1
,SYSDATE  AS FTD_FEH_ACT_1
,'#sr_usuario#' AS FCC_USU_ACT_1
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C
WHERE (C.FTC_FOLIO_REL = #sr_folio# OR C.FTC_FOLIO =#sr_folio# )  AND FTB_ESTATUS_MARCA <> FCN_CONV_INGTY

UNION ALL

SELECT DISTINCT
 C.FTC_FOLIO AS FTC_FOLIO_1
,C.FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO_1
,C.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_1
,0 AS FTC_ESTATUS_REGISTRO
,CURRENT_DATE AS FTD_ACTU_ESTA_1
,FTN_ID_SUBPROC_NO_CONV  AS FTN_MOTI_RECH_1
,SYSDATE  AS FTD_FEH_ACT_1
,'#sr_usuario#' AS FCC_USU_ACT_1
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C
WHERE (C.FTC_FOLIO_REL = #sr_folio# OR C.FTC_FOLIO =#sr_folio# )  AND FTB_ESTATUS_MARCA=0 AND FCN_CONV_INGTY=0

UNION ALL

SELECT DISTINCT
 C.FTC_FOLIO AS FTC_FOLIO_1
,C.FCN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO_1
,C.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_1
,1 AS FTC_ESTATUS_REGISTRO
,CURRENT_DATE AS FTD_ACTU_ESTA_1
,NULL  AS FTN_MOTI_RECH_1
,SYSDATE  AS FTD_FEH_ACT_1
,'#sr_usuario#' AS FCC_USU_ACT_1
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C
WHERE (C.FTC_FOLIO_REL = #sr_folio# OR C.FTC_FOLIO =#sr_folio# ) AND FTB_ESTATUS_MARCA=1 AND FCN_CONV_INGTY=1

)MC
ON( T1.FTC_FOLIO=MC.FTC_FOLIO_1
AND T1.FCN_ID_SUBPROCESO=MC.FCN_ID_SUBPROCESO_1
AND T1.FTN_NUM_CTA_INVDUAL=MC.FTN_NUM_CTA_INVDUAL_1)
WHEN MATCHED THEN 
UPDATE SET 
T1.FTC_ESTATUS=MC.FTC_ESTATUS_REGISTRO,
T1.FCN_ID_MOTIVO_RECHAZO=MC.FTN_MOTI_RECH_1,
T1.FTD_FEH_ACT=MC.FTD_FEH_ACT_1,
T1.FTC_USU_ACT=MC.FCC_USU_ACT_1
 