SELECT 
    FCN_ID_TIPO_SUBCTA,
    FCN_ID_SIEFORE,
    FTN_NUM_CTA_INVDUAL,
    FCN_ID_CONCEPTO_MOV,
    FNN_ID_REFERENCIA,
    FTF_MONTO_PESOS,
    FTF_MONTO_ACCIONES,
    FTC_FOLIO
FROM #CX_CRN_ESQUEMA#.#TL_CRN_MOV_RCV#
WHERE FTC_FOLIO = #SR_FOLIO#
UNION
SELECT 
    FCN_ID_TIPO_SUBCTA,
    FCN_ID_SIEFORE,
    FTN_NUM_CTA_INVDUAL,
    FCN_ID_CONCEPTO_MOV,
    FNN_ID_REFERENCIA,
    FTF_MONTO_PESOS,
    FTF_MONTO_ACCIONES,
    FTC_FOLIO
FROM #CX_CRN_ESQUEMA#.#TL_CRN_MOV_VIV#
WHERE FTC_FOLIO = #SR_FOLIO#
