MERGE /*+ PARALLEL(8) */ INTO #CX_DTM_ESQUEMA#.#TL_DTM_CAT_CTE_INFONAVIT# ori
USING (
    SELECT 
    FTC_RFC_INFONA,
    FTC_CURP,
    FTC_NSS_INFONA,
    FTC_APELLIDO_PATER_INFONA,
    FTC_APELLIDO_MATER_INFONA,
    FTC_NOMBRE_INFONA,
    FTN_NUM_CTA_IND,
    FTC_NOMBRE_IMSS
    FROM #CX_DATAUX_ESQUEMA#.#TL_DTM_CAT_CTE_INFONAVIT_AUX# aux
) aux
ON (ori.FTC_NSS_INFONA = aux.FTC_NSS_INFONA)
WHEN MATCHED THEN
    UPDATE SET
        ori.FTC_RFC_INFONA = aux.FTC_RFC_INFONA,
        ori.FTC_CURP = aux.FTC_CURP,
        ori.FTC_APELLIDO_PATER_INFONA = aux.FTC_APELLIDO_PATER_INFONA,
        ori.FTC_APELLIDO_MATER_INFONA = aux.FTC_APELLIDO_MATER_INFONA,
        ori.FTC_NOMBRE_INFONA = aux.FTC_NOMBRE_INFONA,
        ori.FTN_NUM_CTA_IND = aux.FTN_NUM_CTA_IND,
        ori.FTC_NOMBRE_IMSS = aux.FTC_NOMBRE_IMSS
WHEN NOT MATCHED THEN
    INSERT (
        FTC_RFC_INFONA,
        FTC_CURP,
        FTC_NSS_INFONA,
        FTC_APELLIDO_PATER_INFONA,
        FTC_APELLIDO_MATER_INFONA,
        FTC_NOMBRE_INFONA,
        FTN_NUM_CTA_IND,
        FTC_NOMBRE_IMSS
    )
    VALUES (
        aux.FTC_RFC_INFONA,
        aux.FTC_CURP,
        aux.FTC_NSS_INFONA,
        aux.FTC_APELLIDO_PATER_INFONA,
        aux.FTC_APELLIDO_MATER_INFONA,
        aux.FTC_NOMBRE_INFONA,
        aux.FTN_NUM_CTA_IND,
        aux.FTC_NOMBRE_IMSS
    )
