SELECT 
    FTC_RFC_INFONA,
    FTC_CURP,
    TRIM(FTC_NSS_INFONA) AS FTC_NSS_INFONA,
    FTC_APELLIDO_PATER_INFONA,
    FTC_APELLIDO_MATER_INFONA,
    FTC_NOMBRE_INFONA,
    FTN_CTA_AFORE AS FTN_NUM_CTA_IND,
    FTC_NOMBRE_IMSS
FROM #CATALOG_SCHEMA#.TEMP_PROCESOS_#SR_FOLIO#
