SELECT DISTINCT
    FTC_RFC_TRABA AS FTC_RFC_INFONA,
    FTC_CURP AS FTC_CURP,
    FTC_NSS AS FTC_NSS_INFONA,
    CAST(NULL AS VARCHAR2(40)) AS FTC_APELLIDO_PATER_INFONA,
    CAST(NULL AS VARCHAR2(40)) AS FTC_APELLIDO_MATER_INFONA,
    CAST(NULL AS VARCHAR2(40)) AS FTC_NOMBRE_INFONA,
    FTN_NUM_CTA_INVDUAL AS FTN_CTA_AFORE,
    FTC_NOMBRE AS FTC_NOMBRE_IMSS
FROM #CX_PRO_ESQUEMA#.#TL_PRO_DEV_PAG_SJL#
WHERE FTC_FOLIO = #SR_FOLIO#
ORDER BY FTN_CTA_AFORE, FTC_NSS_INFONA
