SELECT 
    FNN_ID_REFERENCIA AS FTN_CONSE_REG_LOTE,
    FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_IND,
    FCN_ID_TIPO_SUBCTA,
    FCN_ID_SIEFORE,
    FTC_FOLIO AS FTC_FOLIO_BITA,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4063 THEN FTF_MONTO_PESOS ELSE CAST(NULL AS DECIMAL(9,2)) END AS FTN_IMP_RET_DEV_APLI,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4070 THEN FTF_MONTO_PESOS ELSE CAST(NULL AS DECIMAL(9,2)) END AS FTN_IMP_CV_CP_DEV_APLI,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4527 THEN FTF_MONTO_PESOS ELSE CAST(NULL AS DECIMAL(9,2)) END AS FTN_IMP_CV_CT_DEV_APLI,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4184 THEN FTF_MONTO_PESOS ELSE CAST(NULL AS DECIMAL(9,2)) END AS FTN_IMP_CSOCIAL_DEV_APLI,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4182 THEN FTF_MONTO_PESOS ELSE CAST(NULL AS DECIMAL(9,2)) END AS FTN_IMP_ACT_REC_RET_DEV_APLI,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4183 THEN FTF_MONTO_PESOS ELSE CAST(NULL AS DECIMAL(9,2)) END AS FTN_IMP_ACT_REC_CV_CP_APLI,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4528 THEN FTF_MONTO_PESOS ELSE CAST(NULL AS DECIMAL(9,2)) END AS FTN_IMP_ACT_REC_CV_CT_APLI,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4072 THEN FTF_MONTO_PESOS ELSE CAST(NULL AS DECIMAL(9,2)) END AS FTN_IMP_APOR_PAT_VIV_DEV_APLI,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4072 THEN FTF_MONTO_ACCIONES ELSE CAST(NULL AS DECIMAL(15,6)) END AS FTN_AIVS_DEV_APLI,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4526 THEN FTF_MONTO_PESOS ELSE CAST(NULL AS DECIMAL(9,2)) END AS FTN_IMP_ACTRET_REN_CTAIND_APLI,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4529 THEN FTF_MONTO_PESOS ELSE CAST(NULL AS DECIMAL(9,2)) END AS FTN_IMP_ACT_CV_CTAIND_CP_APLI,
    CASE WHEN FCN_ID_CONCEPTO_MOV = 4530 THEN FTF_MONTO_PESOS ELSE CAST(NULL AS DECIMAL(9,2)) END AS FTN_IMPACT_CVREN_CTAINDCT_APLI
FROM #CATALOG_SCHEMA#.TEMP_MOV_RCV_VIV_#SR_FOLIO#
