MERGE INTO PROCESOS.TTCRXGRAL_TRANS_INFONA  TGT
USING (
    SELECT DISTINCT
        FTN_CONTA_SERV,
        FTC_FOLIO_BITACORA,
        FTN_NUM_CTA_AFORE,
        (SELECT TRUNC(SYSTIMESTAMP AT TIME ZONE 'America/Mexico_City')FROM DUAL) AS FTD_FEH_ACTUA_ESTATUS,
        (SELECT (SYSTIMESTAMP AT TIME ZONE 'America/Mexico_City')FROM DUAL) AS FTD_FEH_ACT,
        FCC_USU_ACT,
        NULL AS FTN_MOTIVO_RECHAZO,
        FTC_ESTATUS_REGISTRO
    FROM CIERREN_DATAUX.TTCRXGRAL_TRANS_INFONA_AUX
    WHERE FTC_FOLIO_BITACORA = '#sr_folio#'
) SRC
ON (
    TGT.FTC_FOLIO_BITACORA = SRC.FTC_FOLIO_BITACORA
    AND TGT.FTN_NUM_CTA_AFORE = SRC.FTN_NUM_CTA_AFORE
    AND TGT.FTN_CONTA_SERV = SRC.FTN_CONTA_SERV
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTD_FEH_ACTUA_ESTATUS = SRC.FTD_FEH_ACTUA_ESTATUS,
        TGT.FTD_FEH_ACT = SRC.FTD_FEH_ACT,
        TGT.FCC_USU_ACT = SRC.FCC_USU_ACT,
        TGT.FTN_MOTIVO_RECHAZO = SRC.FTN_MOTIVO_RECHAZO,
        TGT.FTC_ESTATUS_REGISTRO = SRC.FTC_ESTATUS_REGISTRO
 

