WITH TB_MARCA_DESMARCA_INFO AS (
	SELECT 
	FTC_NSS_AFORE,
	FTC_NSS_AFORE  AS FTC_NSS_AFORE_ORIG,
	FTC_FOLIO_BITACORA AS FTN_FOLIO_BITACORA_ORIG
	from PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
	where 
	FTC_FOLIO_BITACORA = '#sr_folio#'
	and  FTC_ESTA_REGI = '1' --'#sr_id_est_reg#'
	and   FTC_TIPO_ARCH = '01' --'#sr_tipo_arch_original#'
) 
SELECT
		DISTINCT
		M.FTC_NSS_AFORE,
		M.FTC_FOLIO_BITACORA AS FTC_FOLIO_BITACORA,
		M.FTN_ID_ARCHIVO AS FTN_ID_ARCHIVO,
		'#sr_tipo_archivo#' AS FTC_TIPO_ARCH, --sr_tipo_arch_rechazado
		(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_ACT,
		'DATABRICKS' AS FCC_USU_ACT,
		CASE WHEN INFO.FTC_NSS_AFORE_ORIG IS NULL THEN 0 ELSE 1 END AS FTN_COIN_PROCESAR
FROM 
	CIERREN_ETL.TTAFOTRAS_ETL_MARCA_DESMARCA M
LEFT JOIN
	TB_MARCA_DESMARCA_INFO INFO
ON
	INFO.FTC_NSS_AFORE = M.FTC_NSS_AFORE
WHERE 1=1
    AND FTN_ID_ARCHIVO = '#sr_id_archivo#' --sr_id_archivo_rechazado
    AND FTC_FOLIO_BITACORA = '#sr_folio#'
    AND FTC_TIPO_ARCH = '#sr_tipo_archivo#' --sr_tipo_arch_rechazado
	
