update PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
   set FTC_CODIGO_RES_OPER = NULL
      ,FTC_DIAGNOS_PROCE = NULL
      ,FTC_TIPO_ARCH = '01'
      ,FTC_ESTA_REGI = '1'
      ,FTD_ACTU_ESTA = NULL
      ,FTN_MOTI_RECH = NULL
      ,FTD_FEH_ACT = NULL
      ,FCC_USU_ACT = NULL
WHERE FTC_FOLIO_BITACORA='#sr_folio#'
   AND FTC_TIPO_ARCH='#sr_tipo_archivo#'
