MERGE INTO PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO  TGT
USING (
    SELECT DISTINCT
        FTC_NSS_AFORE,
        FTN_CTA_AFORE,
		FTC_FOLIO_BITACORA,
        FTC_CODIGO_RES_OPER,
		FTC_DIAGNOS_PROCE,
		FTC_TIPO_ARCH,
		FTC_ESTA_REGI,
		FTD_ACTU_ESTA,
		FTN_MOTI_RECH,
		FTD_FEH_ACT,
		FCC_USU_ACT
    FROM CIERREN_DATAUX.TTCRXGRAL_MARCA_DESMARCA_INFO_AUX
    WHERE FTC_FOLIO_BITACORA = '#sr_folio#'
) SRC
ON (
    TGT.FTC_FOLIO_BITACORA = SRC.FTC_FOLIO_BITACORA
    AND TGT.FTC_NSS_AFORE = SRC.FTC_NSS_AFORE
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTC_CODIGO_RES_OPER   = SRC.FTC_CODIGO_RES_OPER,
        TGT.FTC_DIAGNOS_PROCE     = SRC.FTC_DIAGNOS_PROCE,
        TGT.FTC_TIPO_ARCH     = SRC.FTC_TIPO_ARCH,
        TGT.FTC_ESTA_REGI   = SRC.FTC_ESTA_REGI,
        TGT.FTD_ACTU_ESTA   = SRC.FTD_ACTU_ESTA,
        TGT.FTN_MOTI_RECH   = SRC.FTN_MOTI_RECH,
        TGT.FTD_FEH_ACT   = SRC.FTD_FEH_ACT,
        TGT.FCC_USU_ACT   = SRC.FCC_USU_ACT
 