SELECT  
    TO_DATE(Trim(SUBSTR(FTC_LINEA,25,8)), 'YYYYMMDD') FTD_FEH_PRESEN, 
    Trim(SUBSTR(FTC_LINEA,41,18)) FTC_CURP,
    Trim(SUBSTR(FTC_LINEA,59,11)) FTC_NSS_INFONA,
    Trim(SUBSTR(FTC_LINEA,85,13)) FTC_RFC_INFONA,
    Trim(SUBSTR(FTC_LINEA,98,40)) FTC_APELLIDO_PATER_INFONA,
    Trim(SUBSTR(FTC_LINEA,138,40)) FTC_APELLIDO_MATER_INFONA,
    Trim(SUBSTR(FTC_LINEA,178,40)) FTC_NOMBRE_INFONA,
    Trim(SUBSTR(FTC_LINEA,240,16))FTC_IDENTI_LOTE_SOLIC,
    Trim(SUBSTR(FTC_LINEA,271,11)) FTC_NSS_AFORE,
    Trim(SUBSTR(FTC_LINEA,282,13)) FTC_RFC_AFORE,
    Trim(SUBSTR(FTC_LINEA,325,40)) FTC_APELLIDO_PATER_AFORE,
    Trim(SUBSTR(FTC_LINEA,365,40)) FTC_APELLIDO_MATER_AFORE,
    Trim(SUBSTR(FTC_LINEA,405,40) )FTC_NOMBRE_AFORE,
    to_number(Trim(SUBSTR(FTC_LINEA,490,15)/100)) FTN_SALDO_97,
    Trim(SUBSTR(FTC_LINEA,583,2)) FTC_CODIGO_RES_OPER,
    Trim(SUBSTR(FTC_LINEA,585,15)) FTC_DIAGNOS_PROCE,
    Trim(SUBSTR(FTC_LINEA,600,50)) FTC_NOMBRE_IMSS,
    to_number(Trim(SUBSTR(FTC_LINEA,650,10))) FTN_NUM_CRED_INFONA,
    to_number(Trim(SUBSTR(FTC_LINEA,713,6))) FTN_PERIODO_PAGO,
    to_number(Trim(SUBSTR(FTC_LINEA,3,10))) FTN_CONTA_SERV,
    FTN_ID_ARCHIVO,
    '#sr_tipo_archivo#' AS FTC_TIPO_ARCH,
    '#sr_folio#' AS FTC_FOLIO_BITACORA,
    (FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_CRE,
    'DATABRICKS' AS FCC_USU_CRE
    --CURRENT_TIMESTAMP AS FTD_FEH_ACT,
    --'DATABRICKS' AS FCC_USU_ACT
FROM   CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO 
WHERE   SUBSTR(FTC_LINEA,1,2) = 02
AND     FTN_ID_ARCHIVO = '#sr_id_archivo#' --73799
