WITH
ds_500_nss_ag AS (
  SELECT
    FTN_NUM_CTA_INVDUAL,
    FTN_ID_SUBP,
    FTN_CONTA_SERV,
    FTC_NSS_TRABA_AFORE,
    FTN_NUM_APLI_INTE_VIVI92_SOL,
    FTN_NUM_APLI_INTE_VIVI97_SOL,
    CONTEO,
    FCN_VALOR_ACCION,
    FCN_ID_VALOR_ACCION,
    FTC_FOLIO_BITACORA,
    FCN_ID_TIPO_SUBCTA_97,
    ValorSaldosSolPesos_VIV97,
    ValorSaldosSolPesos_VIV92,
    ValorSaldosDisPesos_VIV97,
    ValorSaldosDisPesos_VIV92
  FROM dbx_mit_dev_1udbvf_workspace.default.DELTA_TRA_DB_ATRIF_VSS_0100_INFO_TRANS_365_DS_900_NSS_MULTIPLES_202509221802045407
),

tf_501_resta_saldos AS (
  SELECT
    FTN_NUM_CTA_INVDUAL,
    FTN_ID_SUBP,
    FTN_CONTA_SERV,
    FTC_NSS_TRABA_AFORE,
    FTN_NUM_APLI_INTE_VIVI92_SOL,
    FTN_NUM_APLI_INTE_VIVI97_SOL,
    FCN_VALOR_ACCION,
    FCN_ID_VALOR_ACCION,
    FTC_FOLIO_BITACORA,
    ValorSaldosSolPesos_VIV97,
    ValorSaldosSolPesos_VIV92,
    ValorSaldosDisPesos_VIV97,
    ValorSaldosDisPesos_VIV92,
    -- SaldosVIV: if ValorSaldosSolPesos_X = 0 then 0 else ValorSaldosDisPesos_X
    CASE WHEN NVL(ValorSaldosSolPesos_VIV97,0) = 0 THEN 0 ELSE NVL(ValorSaldosDisPesos_VIV97,0) END AS SaldosVIV97,
    CASE WHEN NVL(ValorSaldosSolPesos_VIV92,0) = 0 THEN 0 ELSE NVL(ValorSaldosDisPesos_VIV92,0) END AS SaldosVIV92,
    -- Bandera flags
    CASE WHEN NVL(ValorSaldosSolPesos_VIV97,0) = 0 OR NVL(ValorSaldosDisPesos_VIV97,0) <= 0 THEN 0 ELSE 1 END AS BanderaVIV97,
    CASE WHEN NVL(ValorSaldosSolPesos_VIV92,0) = 0 OR NVL(ValorSaldosDisPesos_VIV92,0) <= 0 THEN 0 ELSE 1 END AS BanderaVIV92
  FROM ds_500_nss_ag
),

fi_502_rej_available AS (
  SELECT * FROM tf_501_resta_saldos
  WHERE BanderaVIV97 > 0 OR BanderaVIV92 > 0
),
fi_502_rej_rejected AS (
  SELECT
    FTN_NUM_CTA_INVDUAL,
    FTN_ID_SUBP,
    FTN_NUM_APLI_INTE_VIVI92_SOL,
    FTN_NUM_APLI_INTE_VIVI97_SOL,
    FTN_CONTA_SERV
  FROM tf_501_resta_saldos
  WHERE BanderaVIV97 = 0 AND BanderaVIV92 = 0
),

ds_400_rejinsaldos AS (
  SELECT
    FTN_NUM_CTA_INVDUAL,
    FTN_ID_SUBP,
    FTN_NUM_APLI_INTE_VIVI92_SOL,
    FTN_NUM_APLI_INTE_VIVI97_SOL,
    FTN_CONTA_SERV
  FROM dbx_mit_dev_1udbvf_workspace.default.DELTA_TRA_DB_ATRIF_VSS_0100_INFO_TRANS_365_DS_600_RejInsSaldos_202509221802045407
),

fu_401_union_rej AS (
  SELECT * FROM ds_400_rejinsaldos
  UNION ALL
  SELECT * FROM fi_502_rej_rejected
),



ds_400_nns_unico AS (
  SELECT
    FTN_NUM_CTA_INVDUAL,
    FTN_IND_SDO_DISP_VIV97,
    FTN_IND_SDO_DISP_92,
    FCN_VALOR_ACCION,
    FTN_MONTO_PESOS,
    FTN_MONTO_PESOS_92,
    FTC_FOLIO_BITACORA,
    FCN_ID_TIPO_SUBCTA_97,
    FCN_ID_TIPO_SUBCTA_92,
    FTN_ID_SUBP,
    FCN_ID_VALOR_ACCION,
    FTN_CONTA_SERV,
    FTN_NUM_APLI_INTE_VIVI92_SOL,
    FTN_NUM_APLI_INTE_VIVI97_SOL,
    DIAG92,
    DIAG97
  FROM dbx_mit_dev_1udbvf_workspace.default.DELTA_TRA_DB_ATRIF_VSS_0100_INFO_TRANS_365_DS_NSS_UNICO_202509221802045407
),

tf_503_resta_saldo AS (
  SELECT
    FTN_NUM_CTA_INVDUAL,
    CASE WHEN vSaldo97_calc > 0 THEN 1 ELSE 0 END AS FTN_IND_SDO_DISP_VIV97,
    CASE WHEN vSaldo92_calc > 0 THEN 1 ELSE 0 END AS FTN_IND_SDO_DISP_92,
    FCN_VALOR_ACCION,
    vSaldo97_calc AS FTN_MONTO_PESOS,
    vSaldo92_calc AS FTN_MONTO_PESOS_92,
    FTC_FOLIO_BITACORA,
    CAST(15 AS NUMERIC(4,0)) AS FCN_ID_TIPO_SUBCTA_97,
    CAST(16 AS NUMERIC(10,0)) AS FCN_ID_TIPO_SUBCTA_92,
    FTN_ID_SUBP,
    FCN_ID_VALOR_ACCION,
    FTN_CONTA_SERV,
    FTN_NUM_APLI_INTE_VIVI92_SOL,
    FTN_NUM_APLI_INTE_VIVI97_SOL,
    CASE WHEN NVL(ValorSaldosSolPesos_VIV92,0) = 0 AND vSaldoSol92 >= NVL(ValorSaldosSolPesos_VIV92,0) THEN NULL ELSE '01' END AS DIAG92,
    CASE WHEN NVL(ValorSaldosSolPesos_VIV97,0) = 0 AND vSaldoSol97 >= NVL(ValorSaldosSolPesos_VIV97,0) THEN NULL ELSE '01' END AS DIAG97
  FROM (
    SELECT
      a.*,
      GREATEST(NVL(SaldosVIV97,0),0) AS vSaldoSol97,
      GREATEST(NVL(SaldosVIV92,0),0) AS vSaldoSol92,
      LEAST(NVL(ValorSaldosSolPesos_VIV97,0), GREATEST(NVL(SaldosVIV97,0),0)) AS vSaldo97_calc,
      LEAST(NVL(ValorSaldosSolPesos_VIV92,0), GREATEST(NVL(SaldosVIV92,0),0)) AS vSaldo92_calc
    FROM fi_502_rej_available a
  )
)



SELECT
  FTN_NUM_CTA_INVDUAL, FTN_IND_SDO_DISP_VIV97, FTN_IND_SDO_DISP_92,
  FCN_VALOR_ACCION, FTN_MONTO_PESOS, FTN_MONTO_PESOS_92, FTC_FOLIO_BITACORA,
  FCN_ID_TIPO_SUBCTA_97, FCN_ID_TIPO_SUBCTA_92, FTN_ID_SUBP, FCN_ID_VALOR_ACCION,
  FTN_CONTA_SERV, FTN_NUM_APLI_INTE_VIVI92_SOL, FTN_NUM_APLI_INTE_VIVI97_SOL,
  DIAG92, DIAG97
FROM tf_503_resta_saldo

UNION ALL

SELECT
  FTN_NUM_CTA_INVDUAL, FTN_IND_SDO_DISP_VIV97, FTN_IND_SDO_DISP_92,
  FCN_VALOR_ACCION, FTN_MONTO_PESOS, FTN_MONTO_PESOS_92, FTC_FOLIO_BITACORA,
  FCN_ID_TIPO_SUBCTA_97, FCN_ID_TIPO_SUBCTA_92, FTN_ID_SUBP, FCN_ID_VALOR_ACCION,
  FTN_CONTA_SERV, FTN_NUM_APLI_INTE_VIVI92_SOL, FTN_NUM_APLI_INTE_VIVI97_SOL,
  DIAG92, DIAG97
FROM ds_400_nns_unico;