SELECT 
    FTN_NUM_CTA_INVDUAL,
    FTN_IND_SDO_DISP_VIV97,
    NULL AS FTN_IND_SDO_DISP_92, -- Set to NULL
    FTN_SDO_AIVS,
    NULL AS FTN_SDO_AIVS_92, -- Set to NULL
    FCN_VALOR_ACCION AS FTN_VALOR_AIVS, -- Pass-through column
    -- Calculate FTN_MONTO_PESOS
    CASE 
        WHEN FTN_IND_SDO_DISP_VIV97 = 1 THEN FTN_SDO_AIVS * FCN_VALOR_ACCION
        ELSE 0
    END AS FTN_MONTO_PESOS,
    NULL AS FTN_MONTO_PESOS_92, -- Set to NULL
    -- Calculate FCN_ESTATUS
    CASE 
        WHEN FTN_IND_SDO_DISP_VIV97 = 1 THEN 1
        ELSE 0
    END AS FCN_ESTATUS,
    -- Add current timestamp for FTD_FEH_CRE
    CURRENT_TIMESTAMP AS FTD_FEH_CRE,
    -- Add user parameter for FTC_USU_CRE
    'DATABRICKS' AS FTC_USU_CRE,
    FTC_FOLIO_BITACORA,
    -- Pass-through columns
    138 AS FCN_ID_REGIMEN, -- Parameterized value
    15 as FCN_ID_TIPO_SUBCTA_97,
    NULL AS FCN_ID_TIPO_SUBCTA_92, -- Set to NULL
    FTN_ID_SUBP,
    FCN_ID_VALOR_ACCION,
    FTN_CONTA_SERV,
    -- Calculate FTN_MOTI_RECH
    CASE 
        WHEN FTN_IND_SDO_DISP_VIV97 <= 0 THEN 584
        ELSE NULL
    END AS FTN_MOTI_RECH,
    NULL AS FTN_NUM_APLI_INTE_VIVI92_SOL, -- Set to NULL
    FTN_NUM_APLI_INTE_VIVI97_SOL,
    FTN_SALDO_VIVI97_SOLI
FROM #DELTA_TABLE_DS_700_SALDOS_PROC_368#