SELECT 
    FTN_NUM_CTA_INVDUAL,
    COALESCE(FTN_IND_SDO_DISP_VIV97, 0) AS FTN_IND_SDO_DISP_VIV97,
    COALESCE(FTN_IND_SDO_DISP_92, 0) AS FTN_IND_SDO_DISP_92,
    COALESCE(FTN_SDO_AIVS, 0) AS FTN_SDO_AIVS,
    COALESCE(FTN_SDO_AIVS_92, 0) AS FTN_SDO_AIVS_92,
    COALESCE(FCN_VALOR_ACCION, 0) AS FTN_VALOR_AIVS,
    COALESCE(FTN_MONTO_PESOS, 0) AS FTN_MONTO_PESOS,
    COALESCE(FTN_MONTO_PESOS_92, 0) AS FTN_MONTO_PESOS_92,
    CASE 
        WHEN COALESCE(FTN_IND_SDO_DISP_VIV97, 0) = 0 AND COALESCE(FTN_IND_SDO_DISP_92, 0) = 0 THEN 0
        ELSE 1
    END AS FCN_ESTATUS,
    CURRENT_TIMESTAMP AS FTD_FEH_CRE,
    'DATABRICKS' AS FTC_USU_CRE,
    '#sr_folio#' AS FTC_FOLIO_BITACORA,
    '138' AS FCN_ID_REGIMEN,
    15 AS FCN_ID_TIPO_SUBCTA_97,
    16 AS FCN_ID_TIPO_SUBCTA_92,
    FTN_ID_SUBP,
    COALESCE(FCN_ID_VALOR_ACCION, 0) AS FCN_ID_VALOR_ACCION,
    FTN_CONTA_SERV,
    CASE 
        WHEN COALESCE(FTN_IND_SDO_DISP_VIV97, 0) = 0 AND COALESCE(FTN_IND_SDO_DISP_92, 0) = 0 THEN 584
        ELSE NULL
    END AS FTN_MOTI_RECH,
    COALESCE(FTN_MONTO_PESOS, 0) AS FTN_SALDO_VIVI97_SOLI,
    COALESCE(FTN_SDO_AIVS_92, 0) AS FTN_NUM_APLI_INTE_VIVI92_SOL,
    COALESCE(FTN_SDO_AIVS, 0) AS FTN_NUM_APLI_INTE_VIVI97_SOL
FROM 
    #DELTA_TABLE_DS_700_SALDOS_PROC_364#