WITH computed AS (
  SELECT
    CASE
      WHEN TRIM(DIAG92) = '01' OR TRIM(DIAG97) = '01' THEN NULL
      WHEN NVL(FTN_IND_SDO_DISP_92,0) = 0
           AND NVL(FTN_IND_SDO_DISP_VIV97,0) = 0
      THEN 584
      ELSE NULL
    END AS FTN_MOTIVO_RECHAZO,
    FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_AFORE,
    FTC_FOLIO_BITACORA,
    FTN_CONTA_SERV,
    CASE
      WHEN TRIM(DIAG92) = '01' OR TRIM(DIAG97) = '01' THEN '1'
      ELSE '0'
    END AS FTC_ESTATUS_REGISTRO,
    CURRENT_DATE          AS FTD_FEH_ACTUA_ESTATUS,
    CURRENT_TIMESTAMP     AS FTD_FEH_ACT,
    'DATABRICKS'          AS FCC_USU_ACT,
    DIAG92                AS FTC_INDI_DIFE_VIVI92,
    DIAG97                AS FTC_INDI_DIFE_VIVI97,
    NVL(FTN_IND_SDO_DISP_92,0)    AS I92,
    NVL(FTN_IND_SDO_DISP_VIV97,0) AS IV97,
    0                      AS FTN_ID_SUBP
  FROM
    #DELTA_TABLE_BD_600_TRANS_INFONA#
)
SELECT
  FTN_MOTIVO_RECHAZO,
  FTN_NUM_CTA_AFORE,
  FTC_FOLIO_BITACORA,
  FTN_CONTA_SERV,
  FTC_ESTATUS_REGISTRO,
  FTD_FEH_ACTUA_ESTATUS,
  FTD_FEH_ACT,
  FCC_USU_ACT,
  FTC_INDI_DIFE_VIVI92,
  FTC_INDI_DIFE_VIVI97,
  FTN_ID_SUBP
FROM computed
WHERE
  -- Rule 1: motive equals the configured rejection code (literal 584 here)
  FTN_MOTIVO_RECHAZO = 584
  -- Rule 2: both indicators = 0
  OR (I92 = 0 AND IV97 = 0)
  -- Rule 3: DIAG flags = '01'
  OR TRIM(FTC_INDI_DIFE_VIVI92) = '01'
  OR TRIM(FTC_INDI_DIFE_VIVI97) = '01'