MERGE INTO PROCESOS.TTSISGRAL_SUF_SALDOS TGT
USING (
    SELECT DISTINCT
        FTN_NUM_CTA_INVDUAL,
        FTN_IND_SDO_DISP_VIV97,
        FTN_SDO_AIVS,
        FTN_VALOR_AIVS,
        FTN_MONTO_PESOS,
        FCN_ESTATUS,
        FTD_FEH_CRE,
        FTC_USU_CRE,
        FTC_FOLIO_BITACORA,
        FCN_ID_REGIMEN,
        FCN_ID_TIPO_SUBCTA_97,
        FTN_ID_SUBP,
        FCN_ID_VALOR_ACCION,
        FTN_CONTA_SERV,
        FTN_MOTI_RECH
    FROM CIERREN_DATAUX.TTSISGRAL_SUF_SALDOS_AUX
    WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'  -- Replace or remove as needed
) SRC
ON (
    TGT.FTC_FOLIO_BITACORA = SRC.FTC_FOLIO_BITACORA
    AND TGT.FTN_NUM_CTA_INVDUAL = SRC.FTN_NUM_CTA_INVDUAL
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTN_IND_SDO_DISP_VIV97    = SRC.FTN_IND_SDO_DISP_VIV97,
        TGT.FTN_SDO_AIVS              = SRC.FTN_SDO_AIVS,
        TGT.FTN_VALOR_AIVS            = SRC.FTN_VALOR_AIVS,
        TGT.FTN_MONTO_PESOS           = SRC.FTN_MONTO_PESOS,
        TGT.FCN_ESTATUS               = SRC.FCN_ESTATUS,
        -- Assuming creation date/user not updated on update
        TGT.FCN_ID_REGIMEN            = SRC.FCN_ID_REGIMEN,
        TGT.FCN_ID_TIPO_SUBCTA_97     = SRC.FCN_ID_TIPO_SUBCTA_97,
        TGT.FTN_ID_SUBP               = SRC.FTN_ID_SUBP,
        TGT.FCN_ID_VALOR_ACCION       = SRC.FCN_ID_VALOR_ACCION,
        TGT.FTN_CONTA_SERV            = SRC.FTN_CONTA_SERV,
        TGT.FTN_MOTI_RECH             = SRC.FTN_MOTI_RECH
WHEN NOT MATCHED THEN
    INSERT (
        FTN_NUM_CTA_INVDUAL,
        FTN_IND_SDO_DISP_VIV97,
        FTN_SDO_AIVS,
        FTN_VALOR_AIVS,
        FTN_MONTO_PESOS,
        FCN_ESTATUS,
        FTD_FEH_CRE,
        FTC_USU_CRE,
        FTC_FOLIO_BITACORA,
        FCN_ID_REGIMEN,
        FCN_ID_TIPO_SUBCTA_97,
        FTN_ID_SUBP,
        FCN_ID_VALOR_ACCION,
        FTN_CONTA_SERV,
        FTN_MOTI_RECH
    )
    VALUES (
        SRC.FTN_NUM_CTA_INVDUAL,
        SRC.FTN_IND_SDO_DISP_VIV97,
        SRC.FTN_SDO_AIVS,
        SRC.FTN_VALOR_AIVS,
        SRC.FTN_MONTO_PESOS,
        SRC.FCN_ESTATUS,
        SYSDATE,
        'DATABRICKS',
        SRC.FTC_FOLIO_BITACORA,
        SRC.FCN_ID_REGIMEN,
        SRC.FCN_ID_TIPO_SUBCTA_97,
        SRC.FTN_ID_SUBP,
        SRC.FCN_ID_VALOR_ACCION,
        SRC.FTN_CONTA_SERV,
        SRC.FTN_MOTI_RECH
    )