--BD_606_TL_PRO_SUF_SALDOS
---
SELECT 
    FTN_NUM_CTA_INVDUAL,
    FTN_IND_SDO_DISP_VIV97,
    FTN_SDO_AIVS,
    FCN_VALOR_ACCION AS FTN_VALOR_AIVS,
    CASE 
        WHEN FTN_IND_SDO_DISP_VIV97 = 1 THEN FTN_SDO_AIVS * FCN_VALOR_ACCION
        ELSE 0
    END AS FTN_MONTO_PESOS,
    CASE 
        WHEN FTN_IND_SDO_DISP_VIV97 = 1 THEN 1
        ELSE 0
    END AS FCN_ESTATUS,
    CURRENT_TIMESTAMP AS FTD_FEH_CRE,
    'DATABRICKS' AS FTC_USU_CRE,
    FTC_FOLIO_BITACORA,
    138 AS FCN_ID_REGIMEN,
    15 AS FCN_ID_TIPO_SUBCTA_97,
    FTN_ID_SUBP,
    FCN_ID_VALOR_ACCION,
    FTN_CONTA_SERV,
    CASE 
        WHEN FTN_IND_SDO_DISP_VIV97 <= 0 THEN 584
        ELSE NULL
    END AS FTN_MOTI_RECH
FROM 
    #FU_603_UNION_TOTAL#