 WITH MainData AS (
    SELECT 
        a.FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL, -- Ensuring aliasing for consistency
        a.FTN_ID_SUBP,
        ADD_MONTHS(TRUNC(a.FTD_FEH_PRESEN, 'MONTH'), 1) AS FECHA_VALOR_AIVS,
        a.FTN_CONTA_SERV,
        a.FTC_NSS_TRABA_AFORE,
        NVL(b.SALDO_DISPONIBLE_AIVS, 0) AS SALDO_DISPONIBLE_AIVS_VIV97,
        NVL(c.SALDO_DISPONIBLE_AIVS, 0) AS SALDO_DISPONIBLE_AIVS_VIV92
    FROM 
        PROCESOS.TTCRXGRAL_TRANS_INFONA a
    LEFT JOIN 
        (SELECT 
            FTC_NUM_CTA_INVDUAL,
            SUM(NVL(FTN_DISP_ACCIONES, 0)) AS SALDO_DISPONIBLE_AIVS,
            FCN_ID_TIPO_SUBCTA 
         FROM 
            CIERREN.TTAFOGRAL_BALANCE_MOVS
         WHERE 
            FCN_ID_SIEFORE = 81
            AND FCN_ID_TIPO_SUBCTA = 15 
            AND FTC_NUM_CTA_INVDUAL IN 
                (SELECT FTN_NUM_CTA_AFORE 
                 FROM PROCESOS.TTCRXGRAL_TRANS_INFONA 
                 WHERE FTC_FOLIO_BITACORA = '#sr_folio#')
         GROUP BY 
            FTC_NUM_CTA_INVDUAL, FCN_ID_TIPO_SUBCTA) b
    ON 
        a.FTN_NUM_CTA_AFORE = b.FTC_NUM_CTA_INVDUAL
    LEFT JOIN 
        (SELECT 
            FTC_NUM_CTA_INVDUAL,
            SUM(NVL(FTN_DISP_ACCIONES, 0)) AS SALDO_DISPONIBLE_AIVS,
            FCN_ID_TIPO_SUBCTA 
         FROM 
            CIERREN.TTAFOGRAL_BALANCE_MOVS
         WHERE 
            FCN_ID_SIEFORE = 81
            AND FCN_ID_TIPO_SUBCTA = 16
            AND FTC_NUM_CTA_INVDUAL IN 
                (SELECT FTN_NUM_CTA_AFORE 
                 FROM PROCESOS.TTCRXGRAL_TRANS_INFONA 
                 WHERE FTC_FOLIO_BITACORA = '#sr_folio#')
         GROUP BY 
            FTC_NUM_CTA_INVDUAL, FCN_ID_TIPO_SUBCTA) c
    ON 
        a.FTN_NUM_CTA_AFORE = c.FTC_NUM_CTA_INVDUAL
    WHERE 
        a.FTC_FOLIO_BITACORA = '#sr_folio#'
        AND a.FTC_ESTATUS_REGISTRO = 1
)
SELECT 
    FTN_NUM_CTA_INVDUAL,
    FTN_ID_SUBP,
    FTN_CONTA_SERV,
    FTC_NSS_TRABA_AFORE,
    SALDO_DISPONIBLE_AIVS_VIV97,
    SALDO_DISPONIBLE_AIVS_VIV92
FROM 
    MainData
WHERE 
    (SALDO_DISPONIBLE_AIVS_VIV97 <= 0 OR SALDO_DISPONIBLE_AIVS_VIV97 IS NULL)
    AND (SALDO_DISPONIBLE_AIVS_VIV92 <= 0 OR SALDO_DISPONIBLE_AIVS_VIV92 IS NULL)