MERGE INTO PROCESOS.TTCRXGRAL_TRANS_INFONA TGT
USING (
    SELECT DISTINCT
        FTN_MOTIVO_RECHAZO,
        FTN_NUM_CTA_AFORE,
        FTC_NSS_TRABA_AFORE,          -- Added column here
        FTC_FOLIO_BITACORA,
        FTN_CONTA_SERV,
        FTC_ESTATUS_REGISTRO,
        FTD_FEH_ACTUA_ESTATUS,
        FTD_FEH_ACT,
        FCC_USU_ACT
    FROM CIERREN_DATAUX.TTCRXGRAL_TRANS_INFONA_AUX
    WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'  -- Replace or remove as needed
) SRC
ON (
    TGT.FTC_FOLIO_BITACORA = SRC.FTC_FOLIO_BITACORA
    AND TGT.FTN_CONTA_SERV = SRC.FTN_CONTA_SERV
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTN_MOTIVO_RECHAZO       = SRC.FTN_MOTIVO_RECHAZO,
        TGT.FTN_NUM_CTA_AFORE        = SRC.FTN_NUM_CTA_AFORE,
        TGT.FTC_NSS_TRABA_AFORE      = SRC.FTC_NSS_TRABA_AFORE,  -- Added update
        TGT.FTC_ESTATUS_REGISTRO     = SRC.FTC_ESTATUS_REGISTRO,
        TGT.FTD_FEH_ACTUA_ESTATUS    = SRC.FTD_FEH_ACTUA_ESTATUS,
        TGT.FTD_FEH_ACT              = SYSDATE,
        TGT.FCC_USU_ACT              = 'DATABRICKS'
WHEN NOT MATCHED THEN
    INSERT (
        FTN_MOTIVO_RECHAZO,
        FTN_NUM_CTA_AFORE,
        FTC_NSS_TRABA_AFORE,          -- Added column here
        FTC_FOLIO_BITACORA,
        FTN_CONTA_SERV,
        FTC_ESTATUS_REGISTRO,
        FTD_FEH_ACTUA_ESTATUS,
        FTD_FEH_ACT,
        FCC_USU_ACT
    )
    VALUES (
        SRC.FTN_MOTIVO_RECHAZO,
        SRC.FTN_NUM_CTA_AFORE,
        SRC.FTC_NSS_TRABA_AFORE,      -- Added value here
        SRC.FTC_FOLIO_BITACORA,
        SRC.FTN_CONTA_SERV,
        SRC.FTC_ESTATUS_REGISTRO,
        SRC.FTD_FEH_ACTUA_ESTATUS,
        SYSDATE,
        'DATABRICKS'
    )