WITH input_data AS (
  -- Source rows for the folio and active status (DS_300_TRANFERENCIAS)
  SELECT
    a.FTN_NUM_CTA_AFORE                    AS FTN_NUM_CTA_INVDUAL,
    a.FTN_ID_SUBP,
    ADD_MONTHS(TRUNC(a.FTD_FEH_PRESEN,'MONTH'), 1) AS FECHA_VALOR_AIVS,
    a.FTN_CONTA_SERV,
    a.FTC_NSS_TRABA_AFORE,
    NVL(a.FTN_NUM_APLI_INTE_VIVI92_SOL,0)  AS FTN_NUM_APLI_INTE_VIVI92_SOL,
    NVL(a.FTN_NUM_APLI_INTE_VIVI97_SOL,0)  AS FTN_NUM_APLI_INTE_VIVI97_SOL
  FROM PROCESOS.TTCRXGRAL_TRANS_INFONA a
  WHERE a.FTC_FOLIO_BITACORA = '#sr_folio#'
    AND ((FTN_MOTIVO_RECHAZO <> 93)
AND   (FTN_MOTIVO_RECHAZO <> 254)
AND  (FTN_MOTIVO_RECHAZO <> 375) 
AND  (FTN_MOTIVO_RECHAZO <> 1178)
OR (FTN_MOTIVO_RECHAZO IS NULL))
),
balances AS (
  -- Aggregate available AIVS actions per account and subaccount type (balance source)
  SELECT
    FTC_NUM_CTA_INVDUAL,
    FCN_ID_TIPO_SUBCTA,
    SUM(NVL(FTN_DISP_ACCIONES,0)) AS SALDO_DISPONIBLE_AIVS
  FROM CIERREN.TTAFOGRAL_BALANCE_MOVS bm
  WHERE bm.FCN_ID_SIEFORE = 81
    AND bm.FCN_ID_TIPO_SUBCTA IN (15,16)
    AND bm.FTC_NUM_CTA_INVDUAL IN (SELECT FTN_NUM_CTA_INVDUAL FROM input_data)
  GROUP BY FTC_NUM_CTA_INVDUAL, FCN_ID_TIPO_SUBCTA
),
co AS (
  -- Attach balances for VIV97 (type 15) and VIV92 (type 16) and apply FL_301_SALDOS filter:
  -- keep rows where (available > 0 AND requested > 0) for at least one subaccount
  SELECT
    i.*,
    NVL(b15.SALDO_DISPONIBLE_AIVS, 0) AS SALDO_DISPONIBLE_AIVS_VIV97,
    NVL(b16.SALDO_DISPONIBLE_AIVS, 0) AS SALDO_DISPONIBLE_AIVS_VIV92
  FROM input_data i
  LEFT JOIN (SELECT FTC_NUM_CTA_INVDUAL, SALDO_DISPONIBLE_AIVS FROM balances WHERE FCN_ID_TIPO_SUBCTA = 15) b15
    ON i.FTN_NUM_CTA_INVDUAL = b15.FTC_NUM_CTA_INVDUAL
  LEFT JOIN (SELECT FTC_NUM_CTA_INVDUAL, SALDO_DISPONIBLE_AIVS FROM balances WHERE FCN_ID_TIPO_SUBCTA = 16) b16
    ON i.FTN_NUM_CTA_INVDUAL = b16.FTC_NUM_CTA_INVDUAL
  WHERE
    (NVL(b15.SALDO_DISPONIBLE_AIVS,0) > 0 AND NVL(i.FTN_NUM_APLI_INTE_VIVI97_SOL,0) > 0)
    OR
    (NVL(b16.SALDO_DISPONIBLE_AIVS,0) > 0 AND NVL(i.FTN_NUM_APLI_INTE_VIVI92_SOL,0) > 0)
),
ag AS (
  -- Compute CONTEO per FTC_NSS_TRABA_AFORE from accepted rows (AG_303_SumNSS)
  SELECT
    FTC_NSS_TRABA_AFORE,
    COUNT(*) AS CONTEO
  FROM co
  GROUP BY FTC_NSS_TRABA_AFORE
),
db_valor AS (
  -- AIVS valor rows for the target valuation date (next month). 
  -- We do NOT deduplicate here to match LO_305 allow_dups behavior; use INNER JOIN to enforce presence (if no db row exists will exclude inputs).
  SELECT
    FCD_FEH_ACCION,
    FCN_VALOR_ACCION,
    FCN_ID_VALOR_ACCION
  FROM CIERREN.TCAFOGRAL_VALOR_ACCION va
  WHERE va.FCN_ID_SIEFORE = 81
    AND va.FCN_ID_REGIMEN = 138
   -- AND TRUNC(va.FCD_FEH_ACCION) = ADD_MONTHS(TRUNC(SYSDATE,'MONTH'), 1)
)
SELECT
  co.FTN_NUM_CTA_INVDUAL,
  -- indicators: 1 when monto (peso) > 0 else 0
  CASE WHEN LEAST(
         NVL(co.FTN_NUM_APLI_INTE_VIVI97_SOL,0) * NVL(db.FCN_VALOR_ACCION,0),
         NVL(co.SALDO_DISPONIBLE_AIVS_VIV97,0) * NVL(db.FCN_VALOR_ACCION,0)
       ) > 0 THEN 1 ELSE 0 END AS FTN_IND_SDO_DISP_VIV97,
  -- FTN_IND_SDO_DISP_92 is the job-mapped indicator for VIV92 (FI_307 maps FTN_IND_SDO_DISP_92 = FTN_IND_SDO_DISP_VIV92)
  CASE WHEN LEAST(
         NVL(co.FTN_NUM_APLI_INTE_VIVI92_SOL,0) * NVL(db.FCN_VALOR_ACCION,0),
         NVL(co.SALDO_DISPONIBLE_AIVS_VIV92,0) * NVL(db.FCN_VALOR_ACCION,0)
       ) > 0 THEN 1 ELSE 0 END AS FTN_IND_SDO_DISP_92,
  -- AIVS valor (job transform uses 0 if null; we keep DB value but NVL in calculations)
  db.FCN_VALOR_ACCION,
  -- montos = min(requested*valor, available*valor)
  LEAST(
    NVL(co.FTN_NUM_APLI_INTE_VIVI97_SOL,0) * NVL(db.FCN_VALOR_ACCION,0),
    NVL(co.SALDO_DISPONIBLE_AIVS_VIV97,0) * NVL(db.FCN_VALOR_ACCION,0)
  ) AS FTN_MONTO_PESOS,
  LEAST(
    NVL(co.FTN_NUM_APLI_INTE_VIVI92_SOL,0) * NVL(db.FCN_VALOR_ACCION,0),
    NVL(co.SALDO_DISPONIBLE_AIVS_VIV92,0) * NVL(db.FCN_VALOR_ACCION,0)
  ) AS FTN_MONTO_PESOS_92,
  -- job folio and subaccount type ids (as job outputs)
  '#sr_folio#' AS FTC_FOLIO_BITACORA,
  15 AS FCN_ID_TIPO_SUBCTA_97,
  16 AS FCN_ID_TIPO_SUBCTA_92,
  co.FTN_ID_SUBP,
  db.FCN_ID_VALOR_ACCION,
  co.SALDO_DISPONIBLE_AIVS_VIV97,
  co.SALDO_DISPONIBLE_AIVS_VIV92,
  co.FTN_CONTA_SERV,
  co.FTN_NUM_APLI_INTE_VIVI92_SOL,
  co.FTN_NUM_APLI_INTE_VIVI97_SOL,
  -- DIAG: NULL unless (requested_pesos > 0 AND available_pesos < requested_pesos) -> '01'
  CASE
    WHEN (NVL(co.FTN_NUM_APLI_INTE_VIVI92_SOL,0) * NVL(db.FCN_VALOR_ACCION,0)) = 0
      OR (NVL(co.SALDO_DISPONIBLE_AIVS_VIV92,0) * NVL(db.FCN_VALOR_ACCION,0)) >= (NVL(co.FTN_NUM_APLI_INTE_VIVI92_SOL,0) * NVL(db.FCN_VALOR_ACCION,0))
    THEN NULL ELSE '01'
  END AS DIAG92,
  CASE
    WHEN (NVL(co.FTN_NUM_APLI_INTE_VIVI97_SOL,0) * NVL(db.FCN_VALOR_ACCION,0)) = 0
      OR (NVL(co.SALDO_DISPONIBLE_AIVS_VIV97,0) * NVL(db.FCN_VALOR_ACCION,0)) >= (NVL(co.FTN_NUM_APLI_INTE_VIVI97_SOL,0) * NVL(db.FCN_VALOR_ACCION,0))
    THEN NULL ELSE '01'
  END AS DIAG97
FROM co
JOIN ag ON co.FTC_NSS_TRABA_AFORE = ag.FTC_NSS_TRABA_AFORE
-- inner join to DB valor enforces presence of a DB row for the valuation date (mirrors -ifNotFound fail)
JOIN db_valor db ON co.FECHA_VALOR_AIVS = TRUNC(db.FCD_FEH_ACCION)
WHERE ag.CONTEO = 1
ORDER BY co.FTN_NUM_CTA_INVDUAL