   SELECT
    -- Motivo de rechazo: only set if both indicators are zero
    CASE 
        WHEN NVL(A.FTN_IND_SDO_DISP_VIV97, 0) = 0 AND NVL(A.FTN_IND_SDO_DISP_92, 0) = 0
            THEN 584
        ELSE NULL
    END AS FTN_MOTIVO_RECHAZO,
    A.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_AFORE,
    A.FTC_NSS_TRABA_AFORE,
   '#sr_folio#' AS FTC_FOLIO_BITACORA,
    A.FTN_CONTA_SERV,
    '0' AS FTC_ESTATUS_REGISTRO,
    CURRENT_DATE AS FTD_FEH_ACTUA_ESTATUS,
    CURRENT_TIMESTAMP AS FTD_FEH_ACT,
    'DATABRICKS' AS FCC_USU_ACT,
    0 AS  FTN_ID_SUBP
FROM
    #DELTA_TABLE_DS_900_SUF_SALDOS_PROC_364# A
WHERE
    NVL(A.FTN_IND_SDO_DISP_VIV97, 0) = 0
    AND NVL(A.FTN_IND_SDO_DISP_92, 0) = 0