

SELECT 
    a.FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL, -- Aliased column
    a.FTN_ID_SUBP,
    NVL(a.FTN_NUM_APLI_INTE_VIVI92_SOL, 0) AS FTN_NUM_APLI_INTE_VIVI92_SOL, -- Aliased with NVL
    NVL(a.FTN_NUM_APLI_INTE_VIVI97_SOL, 0) AS FTN_NUM_APLI_INTE_VIVI97_SOL, -- Aliased with NVL
    a.FTN_CONTA_SERV,
    NVL(b.SALDO_DISPONIBLE_AIVS, 0) AS SALDO_DISPONIBLE_AIVS_VIV97, -- Aliased column
    NVL(c.SALDO_DISPONIBLE_AIVS, 0) AS SALDO_DISPONIBLE_AIVS -- Aliased column
FROM 
    PROCESOS.TTCRXGRAL_TRANS_INFONA a
LEFT JOIN 
    (SELECT 
        FTC_NUM_CTA_INVDUAL,
        SUM(NVL(FTN_DISP_ACCIONES, 0)) AS SALDO_DISPONIBLE_AIVS,
        FCN_ID_TIPO_SUBCTA 
     FROM 
        CIERREN.TTAFOGRAL_BALANCE_MOVS
     WHERE 
        FCN_ID_SIEFORE = 81
        AND FCN_ID_TIPO_SUBCTA = 15 
        AND FTC_NUM_CTA_INVDUAL IN 
            (SELECT FTN_NUM_CTA_AFORE 
             FROM PROCESOS.TTCRXGRAL_TRANS_INFONA 
             WHERE FTC_FOLIO_BITACORA = '#sr_folio#')
     GROUP BY 
        FTC_NUM_CTA_INVDUAL, FCN_ID_TIPO_SUBCTA) b
ON 
    a.FTN_NUM_CTA_AFORE = b.FTC_NUM_CTA_INVDUAL
LEFT JOIN 
    (SELECT 
        FTC_NUM_CTA_INVDUAL,
        SUM(NVL(FTN_DISP_ACCIONES, 0)) AS SALDO_DISPONIBLE_AIVS,
        FCN_ID_TIPO_SUBCTA 
     FROM 
        CIERREN.TTAFOGRAL_BALANCE_MOVS
     WHERE 
        FCN_ID_SIEFORE = 81
        AND FCN_ID_TIPO_SUBCTA = 16
        AND FTC_NUM_CTA_INVDUAL IN 
            (SELECT FTN_NUM_CTA_AFORE 
             FROM PROCESOS.TTCRXGRAL_TRANS_INFONA 
             WHERE FTC_FOLIO_BITACORA = '#sr_folio#')
     GROUP BY 
        FTC_NUM_CTA_INVDUAL, FCN_ID_TIPO_SUBCTA) c
ON 
    a.FTN_NUM_CTA_AFORE = c.FTC_NUM_CTA_INVDUAL
WHERE 
    a.FTC_FOLIO_BITACORA = '#sr_folio#'
    AND a.FTC_ESTATUS_REGISTRO = 1
    AND (
        (NVL(c.SALDO_DISPONIBLE_AIVS, 0) <= 0 OR NVL(a.FTN_NUM_APLI_INTE_VIVI97_SOL, 0) is null )
        AND (NVL(b.SALDO_DISPONIBLE_AIVS, 0) <= 0 OR NVL(a.FTN_NUM_APLI_INTE_VIVI92_SOL, 0) is null)
    )