SELECT
    FTN_NUM_CTA_INVDUAL,
    FTN_IND_SDO_DISP_VIV97,
    FTN_IND_SDO_DISP_92,
    CASE
        WHEN FTN_IND_SDO_DISP_VIV97 = 1 THEN COALESCE(FTN_MONTO_PESOS / NULLIF(FCN_VALOR_ACCION, 0), 0)
        ELSE 0
    END AS FTN_SDO_AIVS,
    CASE
        WHEN FTN_IND_SDO_DISP_92 = 1 THEN COALESCE(FTN_MONTO_PESOS_92 / NULLIF(FCN_VALOR_ACCION, 0), 0)
        ELSE 0
    END AS FTN_SDO_AIVS_92,
    FCN_VALOR_ACCION AS FTN_VALOR_AIVS,
    FTN_MONTO_PESOS,
    FTN_MONTO_PESOS_92,
    CASE
        WHEN FTN_IND_SDO_DISP_92 = 0 AND FTN_IND_SDO_DISP_VIV97 = 0 THEN 0
        ELSE 1
    END AS FCN_ESTATUS,
    CURRENT_TIMESTAMP AS FTD_FEH_CRE,
    'DATABRICKS' AS FTC_USU_CRE,
    FTC_FOLIO_BITACORA,
    138 AS FCN_ID_REGIMEN,
    FCN_ID_TIPO_SUBCTA_97,
    FCN_ID_TIPO_SUBCTA_92,
    FTN_ID_SUBP,
    FCN_ID_VALOR_ACCION,
    FTN_CONTA_SERV,
    CASE
        WHEN FTN_IND_SDO_DISP_92 = 0 AND FTN_IND_SDO_DISP_VIV97 = 0 THEN 584
        ELSE NULL
    END AS FTN_MOTI_RECH,
    FTN_NUM_APLI_INTE_VIVI92_SOL,
    FTN_NUM_APLI_INTE_VIVI97_SOL,
    CAST(NULL AS NUMERIC(18,2)) AS FTN_SALDO_VIVI97_SOLI
FROM
    #DELTA_TABLE_DS_700_SALDOS_PROC_365#
WHERE
    FTN_IND_SDO_DISP_92 <> 0 OR FTN_IND_SDO_DISP_VIV97 <> 0

    