--BD_605_TL_PRO_TRANS_INFONA

    SELECT
    584 AS FTN_MOTIVO_RECHAZO,
    FTN_NUM_CTA_INVDUAL     AS FTN_NUM_CTA_AFORE,
    FTC_FOLIO_BITACORA,
    FTN_CONTA_SERV,
    0                       AS FTC_ESTATUS_REGISTRO,
    CURRENT_DATE            AS FTD_FEH_ACTUA_ESTATUS,
    CURRENT_TIMESTAMP       AS FTD_FEH_ACT,
    'DATABRICKS' AS FCC_USU_ACT,
    0 FTN_ID_SUBP
FROM
    #FU_603_UNION_TOTAL#
WHERE
    FTN_IND_SDO_DISP_VIV97 <= 0;