WITH input_data AS (
  -- source rows for the folio and active status
  SELECT
    a.FTN_NUM_CTA_AFORE                     AS FTN_NUM_CTA_INVDUAL,
    a.FTN_ID_SUBP,
    ADD_MONTHS(TRUNC(a.FTD_FEH_PRESEN,'MONTH'), 1) AS FECHA_VALOR_AIVS,
    a.FTN_CONTA_SERV,
    a.FTC_NSS_TRABA_AFORE,
    NVL(a.FTN_NUM_APLI_INTE_VIVI92_SOL, 0)  AS FTN_NUM_APLI_INTE_VIVI92_SOL,
    NVL(a.FTN_NUM_APLI_INTE_VIVI97_SOL, 0)  AS FTN_NUM_APLI_INTE_VIVI97_SOL
  FROM PROCESOS.TTCRXGRAL_TRANS_INFONA a
  WHERE a.FTC_FOLIO_BITACORA = '#sr_folio#'
    AND a.FTC_ESTATUS_REGISTRO = 1
),
balances AS (
  -- aggregated available AIVS actions per account and subaccount type
  SELECT
    FTC_NUM_CTA_INVDUAL,
    FCN_ID_TIPO_SUBCTA,
    SUM(NVL(FTN_DISP_ACCIONES,0)) AS SALDO_DISPONIBLE_AIVS
  FROM CIERREN.TTAFOGRAL_BALANCE_MOVS bm
  WHERE bm.FCN_ID_SIEFORE = 81
    AND bm.FCN_ID_TIPO_SUBCTA IN (15,16)
    AND bm.FTC_NUM_CTA_INVDUAL IN (SELECT FTN_NUM_CTA_INVDUAL FROM input_data)
  GROUP BY FTC_NUM_CTA_INVDUAL, FCN_ID_TIPO_SUBCTA
),
co AS (
  -- attach balances for VIV97 (type 15) and VIV92 (type 16) and apply FL_301_SALDOS filter
  SELECT
    i.*,
    NVL(b15.SALDO_DISPONIBLE_AIVS, 0) AS SALDO_DISPONIBLE_AIVS_VIV97,
    NVL(b16.SALDO_DISPONIBLE_AIVS, 0) AS SALDO_DISPONIBLE_AIVS_VIV92
  FROM input_data i
  LEFT JOIN (SELECT FTC_NUM_CTA_INVDUAL, SALDO_DISPONIBLE_AIVS FROM balances WHERE FCN_ID_TIPO_SUBCTA = 15) b15
    ON i.FTN_NUM_CTA_INVDUAL = b15.FTC_NUM_CTA_INVDUAL
  LEFT JOIN (SELECT FTC_NUM_CTA_INVDUAL, SALDO_DISPONIBLE_AIVS FROM balances WHERE FCN_ID_TIPO_SUBCTA = 16) b16
    ON i.FTN_NUM_CTA_INVDUAL = b16.FTC_NUM_CTA_INVDUAL
  -- apply FL_301_SALDOS: require actionable request+available in at least one subaccount
  WHERE (NVL(b15.SALDO_DISPONIBLE_AIVS,0) > 0 AND NVL(i.FTN_NUM_APLI_INTE_VIVI97_SOL,0) > 0)
     OR (NVL(b16.SALDO_DISPONIBLE_AIVS,0) > 0 AND NVL(i.FTN_NUM_APLI_INTE_VIVI92_SOL,0) > 0)
),
ag AS (
  -- compute CONTEO per FTC_NSS_TRABA_AFORE (AG_303_SumNSS)
  SELECT
    FTC_NSS_TRABA_AFORE,
    COUNT(*) AS CONTEO
  FROM co
  GROUP BY FTC_NSS_TRABA_AFORE
),
db_valor AS (
  -- pick single AIVS valor row for the target valuation date (next month)
  -- use ROW_NUMBER() to pick one row if duplicates exist
  SELECT
    TRUNC(FCD_FEH_ACCION) AS FCD_FEH_ACCION_TRUNC,
    FCN_VALOR_ACCION,
    FCN_ID_VALOR_ACCION
  FROM (
    SELECT
      FCD_FEH_ACCION,
      FCN_VALOR_ACCION,
      FCN_ID_VALOR_ACCION,
      ROW_NUMBER() OVER (PARTITION BY TRUNC(FCD_FEH_ACCION) ORDER BY FCD_FEH_ACCION DESC) AS rn
    FROM CIERREN.TCAFOGRAL_VALOR_ACCION va
    WHERE va.FCN_ID_SIEFORE = 81
      AND va.FCN_ID_REGIMEN = 138
  --    AND TRUNC(va.FCD_FEH_ACCION) = ADD_MONTHS(TRUNC(SYSDATE,'MONTH'), 1)
  )
  WHERE rn = 1
),
calc AS (
  -- join co + ag + db_valor and compute all intermediate peso values, montos, indicators and DIAGs
  SELECT
    co.FTN_NUM_CTA_INVDUAL,
    co.FTN_ID_SUBP,
    co.FECHA_VALOR_AIVS,
    co.FTN_CONTA_SERV,
    co.FTC_NSS_TRABA_AFORE,
    co.FTN_NUM_APLI_INTE_VIVI92_SOL,
    co.FTN_NUM_APLI_INTE_VIVI97_SOL,
    co.SALDO_DISPONIBLE_AIVS_VIV97,
    co.SALDO_DISPONIBLE_AIVS_VIV92,
    ag.CONTEO,
    -- DB valor: preserve original but use NVL in arithmetic below
    db.FCN_VALOR_ACCION,
    db.FCN_ID_VALOR_ACCION,
    -- Audit/static outputs as job emits
    '#sr_folio#' AS FTC_FOLIO_BITACORA,
    15 AS FCN_ID_TIPO_SUBCTA_97,
    16 AS FCN_ID_TIPO_SUBCTA_92,
    -- Peso intermediate values (use NVL to avoid NULL propagation)
    (NVL(co.FTN_NUM_APLI_INTE_VIVI97_SOL,0) * NVL(db.FCN_VALOR_ACCION,0)) AS ValorSaldosSolPesos_VIV97,
    (NVL(co.FTN_NUM_APLI_INTE_VIVI92_SOL,0) * NVL(db.FCN_VALOR_ACCION,0)) AS ValorSaldosSolPesos_VIV92,
    (NVL(co.SALDO_DISPONIBLE_AIVS_VIV97,0) * NVL(db.FCN_VALOR_ACCION,0)) AS ValorSaldosDisPesos_VIV97,
    (NVL(co.SALDO_DISPONIBLE_AIVS_VIV92,0) * NVL(db.FCN_VALOR_ACCION,0)) AS ValorSaldosDisPesos_VIV92,
    -- montos: min(requested*valor, available*valor)
    LEAST(
      NVL(co.FTN_NUM_APLI_INTE_VIVI97_SOL,0) * NVL(db.FCN_VALOR_ACCION,0),
      NVL(co.SALDO_DISPONIBLE_AIVS_VIV97,0) * NVL(db.FCN_VALOR_ACCION,0)
    ) AS FTN_MONTO_PESOS,
    LEAST(
      NVL(co.FTN_NUM_APLI_INTE_VIVI92_SOL,0) * NVL(db.FCN_VALOR_ACCION,0),
      NVL(co.SALDO_DISPONIBLE_AIVS_VIV92,0) * NVL(db.FCN_VALOR_ACCION,0)
    ) AS FTN_MONTO_PESOS_92,
    -- indicators
    CASE WHEN LEAST(
                NVL(co.FTN_NUM_APLI_INTE_VIVI97_SOL,0) * NVL(db.FCN_VALOR_ACCION,0),
                NVL(co.SALDO_DISPONIBLE_AIVS_VIV97,0) * NVL(db.FCN_VALOR_ACCION,0)
          ) > 0 THEN 1 ELSE 0 END AS FTN_IND_SDO_DISP_VIV97,
    CASE WHEN LEAST(
                NVL(co.FTN_NUM_APLI_INTE_VIVI92_SOL,0) * NVL(db.FCN_VALOR_ACCION,0),
                NVL(co.SALDO_DISPONIBLE_AIVS_VIV92,0) * NVL(db.FCN_VALOR_ACCION,0)
          ) > 0 THEN 1 ELSE 0 END AS FTN_IND_SDO_DISP_VIV92,
    -- DIAG: '01' when requested_pesos > 0 AND available_pesos < requested_pesos; else NULL
    CASE
      WHEN (NVL(co.FTN_NUM_APLI_INTE_VIVI92_SOL,0) * NVL(db.FCN_VALOR_ACCION,0)) = 0
        OR (NVL(co.SALDO_DISPONIBLE_AIVS_VIV92,0) * NVL(db.FCN_VALOR_ACCION,0)) >= (NVL(co.FTN_NUM_APLI_INTE_VIVI92_SOL,0) * NVL(db.FCN_VALOR_ACCION,0))
      THEN NULL ELSE '01'
    END AS DIAG92,
    CASE
      WHEN (NVL(co.FTN_NUM_APLI_INTE_VIVI97_SOL,0) * NVL(db.FCN_VALOR_ACCION,0)) = 0
        OR (NVL(co.SALDO_DISPONIBLE_AIVS_VIV97,0) * NVL(db.FCN_VALOR_ACCION,0)) >= (NVL(co.FTN_NUM_APLI_INTE_VIVI97_SOL,0) * NVL(db.FCN_VALOR_ACCION,0))
      THEN NULL ELSE '01'
    END AS DIAG97
  FROM co
  JOIN ag ON co.FTC_NSS_TRABA_AFORE = ag.FTC_NSS_TRABA_AFORE
  JOIN db_valor db ON co.FECHA_VALOR_AIVS = db.FCD_FEH_ACCION_TRUNC
)
SELECT
  -- return all columns exactly as produced by the job (calc CTE holds them)
  FTN_NUM_CTA_INVDUAL,
  FTN_ID_SUBP,
  FECHA_VALOR_AIVS,
  FTN_CONTA_SERV,
  FTC_NSS_TRABA_AFORE,
  FTN_NUM_APLI_INTE_VIVI92_SOL,
  FTN_NUM_APLI_INTE_VIVI97_SOL,
  SALDO_DISPONIBLE_AIVS_VIV97,
  SALDO_DISPONIBLE_AIVS_VIV92,
  CONTEO,
  FCN_VALOR_ACCION,
  FCN_ID_VALOR_ACCION,
  FTC_FOLIO_BITACORA,
  FCN_ID_TIPO_SUBCTA_97,
  FCN_ID_TIPO_SUBCTA_92,
  ValorSaldosSolPesos_VIV97,
  ValorSaldosSolPesos_VIV92,
  ValorSaldosDisPesos_VIV97,
  ValorSaldosDisPesos_VIV92,
  FTN_MONTO_PESOS,
  FTN_MONTO_PESOS_92,
  FTN_IND_SDO_DISP_VIV97,
  FTN_IND_SDO_DISP_VIV92,
  DIAG92,
  DIAG97
FROM calc
WHERE CONTEO > 1
ORDER BY FTC_NSS_TRABA_AFORE, FTN_CONTA_SERV