
 SELECT 
    a.FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL,
    a.FTN_ID_SUBP,
    a.FTN_CONTA_SERV
FROM 
    PROCESOS.TTCRXGRAL_TRANS_INFONA a
LEFT JOIN 
    (SELECT 
        FTC_NUM_CTA_INVDUAL,
        SUM(NVL(FTN_DISP_ACCIONES, 0)) AS SALDO_DISPONIBLE_AIVS
     FROM 
        CIERREN.TTAFOGRAL_BALANCE_MOVS
     WHERE 
        FCN_ID_SIEFORE = 81
        AND FCN_ID_TIPO_SUBCTA = 15
        AND FTC_NUM_CTA_INVDUAL IN 
            (SELECT FTN_NUM_CTA_AFORE 
             FROM PROCESOS.TTCRXGRAL_TRANS_INFONA 
             WHERE FTC_FOLIO_BITACORA = '#sr_folio#')
     GROUP BY 
        FTC_NUM_CTA_INVDUAL) c
ON 
    a.FTN_NUM_CTA_AFORE = c.FTC_NUM_CTA_INVDUAL
WHERE 
    a.FTC_FOLIO_BITACORA = '#sr_folio#'
    AND ((FTN_MOTIVO_RECHAZO <> 93)
AND   (FTN_MOTIVO_RECHAZO <> 254)
AND  (FTN_MOTIVO_RECHAZO <> 375) 
AND  (FTN_MOTIVO_RECHAZO <> 1178)
OR (FTN_MOTIVO_RECHAZO IS NULL))
    AND (
        NVL(c.SALDO_DISPONIBLE_AIVS, 0) <= 0 
        OR NVL(c.SALDO_DISPONIBLE_AIVS, 0) IS NULL
        OR NVL(a.FTN_NUM_APLI_INTE_VIVI97_SOL, 0) <= 0
    )