MERGE INTO PROCESOS.TTSISGRAL_SUF_SALDOS TGT
USING (
    SELECT
        FTN_NUM_CTA_INVDUAL,
        FTN_SDO_AIVS,
        FTN_MONTO_PESOS,
        FTN_IND_SDO_DISP_VIV97,
        FCN_ID_TIPO_SUBCTA_97,
        FCN_ESTATUS,
        FTN_SDO_AIVS_92,
        FTN_MONTO_PESOS_92,
        FTN_IND_SDO_DISP_92,
        FCN_ID_TIPO_SUBCTA_92,
        FTD_FEH_CRE,
        FTC_USU_CRE,
        FTC_FOLIO_BITACORA,
        FCN_ID_REGIMEN,
        FTN_ID_SUBP,
        FTN_CONTA_SERV,
        FTN_MOTI_RECH,
        FTN_VALOR_AIVS,
        FCN_ID_VALOR_ACCION
    FROM (
        SELECT
            a.*,
            ROW_NUMBER() OVER (
                PARTITION BY FTN_NUM_CTA_INVDUAL, FTN_CONTA_SERV, FTC_FOLIO_BITACORA
                ORDER BY FTN_NUM_CTA_INVDUAL, FTN_SDO_AIVS  DESC  -- choose most recent; use ASC for oldest
            ) AS RN
        FROM CIERREN_DATAUX.TTSISGRAL_SUF_SALDOS_AUX a
        WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'
    ) t
    WHERE RN = 1
) SRC
ON (
    TGT.FTC_FOLIO_BITACORA  = SRC.FTC_FOLIO_BITACORA
    AND TGT.FTN_NUM_CTA_INVDUAL = SRC.FTN_NUM_CTA_INVDUAL
    AND TGT.FTN_CONTA_SERV   = SRC.FTN_CONTA_SERV
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTN_SDO_AIVS            = SRC.FTN_SDO_AIVS,
        TGT.FTN_MONTO_PESOS         = SRC.FTN_MONTO_PESOS,
        TGT.FTN_IND_SDO_DISP_VIV97  = SRC.FTN_IND_SDO_DISP_VIV97,
        TGT.FCN_ID_TIPO_SUBCTA_97   = SRC.FCN_ID_TIPO_SUBCTA_97,
        TGT.FCN_ESTATUS             = SRC.FCN_ESTATUS,
        TGT.FTN_SDO_AIVS_92         = SRC.FTN_SDO_AIVS_92,
        TGT.FTN_MONTO_PESOS_92      = SRC.FTN_MONTO_PESOS_92,
        TGT.FTN_IND_SDO_DISP_92     = SRC.FTN_IND_SDO_DISP_92,
        TGT.FCN_ID_TIPO_SUBCTA_92   = SRC.FCN_ID_TIPO_SUBCTA_92,
        TGT.FCN_ID_REGIMEN          = SRC.FCN_ID_REGIMEN,
        TGT.FTN_ID_SUBP             = SRC.FTN_ID_SUBP,
        TGT.FTN_MOTI_RECH           = SRC.FTN_MOTI_RECH,
        TGT.FTN_VALOR_AIVS          = SRC.FTN_VALOR_AIVS,
        TGT.FCN_ID_VALOR_ACCION     = SRC.FCN_ID_VALOR_ACCION