--DS_600_VAL_CUENTAS
SELECT 
    FTN_NUM_CTA_INVDUAL,
    FTN_ID_SUBP,
    FTN_CONTA_SERV,
    FTC_NSS_TRABA_AFORE,
    -- Rule: SvSaldoDisponiblePesosViv97
    COALESCE(SALDO_DISPONIBLE_AIVS_VIV97, 0) AS FTN_SDO_AIVS,
    COALESCE(SALDO_DISPONIBLE_AIVS_VIV97, 0) * COALESCE(FCN_VALOR_ACCION, 0) AS FTN_MONTO_PESOS,
    -- Rule: FTN_IND_SDO_DISP_VIV97
    CASE 
        WHEN COALESCE(SALDO_DISPONIBLE_AIVS_VIV97, 0) = 0 THEN 0 
        ELSE 1 
    END AS FTN_IND_SDO_DISP_VIV97,
    -- Rule: FCN_ID_TIPO_SUBCTA_97
    CASE 
        WHEN COALESCE(SALDO_DISPONIBLE_AIVS_VIV97, 0) = 0 THEN 0 
        ELSE 15 
    END AS FCN_ID_TIPO_SUBCTA_97,
    -- Rule: SvSaldoDisponiblePesosViv92
    COALESCE(SALDO_DISPONIBLE_AIVS_VIV92, 0) AS FTN_SDO_AIVS_92,
    COALESCE(SALDO_DISPONIBLE_AIVS_VIV92, 0) * COALESCE(FCN_VALOR_ACCION, 0) AS FTN_MONTO_PESOS_92,
    -- Rule: FTN_IND_SDO_DISP_92
    CASE 
        WHEN COALESCE(SALDO_DISPONIBLE_AIVS_VIV92, 0) = 0 THEN 0 
        ELSE 1 
    END AS FTN_IND_SDO_DISP_92,
    -- Rule: FCN_ID_TIPO_SUBCTA_92
    CASE 
        WHEN COALESCE(SALDO_DISPONIBLE_AIVS_VIV92, 0) = 0 THEN 0 
        ELSE 16 
    END AS FCN_ID_TIPO_SUBCTA_92,
    FCN_VALOR_ACCION,
    FCN_ID_VALOR_ACCION
FROM 
    #DS_600_VAL_CUENTAS# VALC
UNION ALL 
SELECT 
    FTN_NUM_CTA_INVDUAL,
    FTN_ID_SUBP,
    FTN_CONTA_SERV,
    FTC_NSS_TRABA_AFORE,
    -- Generated columns
    0 AS FTN_SDO_AIVS,
    0 AS FTN_MONTO_PESOS,
    0 AS FTN_IND_SDO_DISP_VIV97,
    0 AS FCN_ID_TIPO_SUBCTA_97,
    0 AS FTN_SDO_AIVS_92,
    0 AS FTN_MONTO_PESOS_92,
    0 AS FTN_IND_SDO_DISP_92,
    0 AS FCN_ID_TIPO_SUBCTA_92,
    0 AS FCN_VALOR_ACCION,
    0 AS FCN_ID_VALOR_ACCION
FROM 
    #DS_400_RejInsSaldos# REJS
UNION ALL
SELECT 
    FTN_NUM_CTA_INVDUAL,
    FTN_ID_SUBP,
    FTN_CONTA_SERV,
    FTC_NSS_TRABA_AFORE,
    FTN_SDO_AIVS,
    FTN_MONTO_PESOS,
    FTN_IND_SDO_DISP_VIV97,
    FCN_ID_TIPO_SUBCTA_97,
    FTN_SDO_AIVS_92,
    FTN_MONTO_PESOS_92,
    FTN_IND_SDO_DISP_92,
    FCN_ID_TIPO_SUBCTA_92,
    FCN_VALOR_ACCION,
    FCN_ID_VALOR_ACCION
FROM 
    #DS_700_REJ_CUENTAS# REJC