MERGE INTO PROCESOS.TTCRXGRAL_TRANS_INFONA TGT
USING (
    SELECT DISTINCT
        FTN_MOTIVO_RECHAZO,
        FTN_NUM_CTA_AFORE,
        FTC_FOLIO_BITACORA,
        FTN_CONTA_SERV,
        FTC_ESTATUS_REGISTRO,
        FTD_FEH_ACTUA_ESTATUS,
        FTC_INDI_DIFE_VIVI92,
        FTC_INDI_DIFE_VIVI97
    FROM CIERREN_DATAUX.TTCRXGRAL_TRANS_INFONA_AUX
    WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'  -- Replace or remove as needed
) SRC
ON (
        tgt.FTN_NUM_CTA_AFORE = src.FTN_NUM_CTA_AFORE
    AND tgt.FTC_FOLIO_BITACORA = src.FTC_FOLIO_BITACORA
    AND tgt.FTN_CONTA_SERV = src.FTN_CONTA_SERV
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTN_MOTIVO_RECHAZO       = SRC.FTN_MOTIVO_RECHAZO,
       -- TGT.FTN_NUM_CTA_AFORE        = SRC.FTN_NUM_CTA_AFORE,
        TGT.FTC_ESTATUS_REGISTRO     = SRC.FTC_ESTATUS_REGISTRO,
        TGT.FTD_FEH_ACTUA_ESTATUS    = SRC.FTD_FEH_ACTUA_ESTATUS,
        TGT.FTC_INDI_DIFE_VIVI92     = SRC.FTC_INDI_DIFE_VIVI92,
        TGT.FTC_INDI_DIFE_VIVI97     = SRC.FTC_INDI_DIFE_VIVI97,
        TGT.FTD_FEH_ACT              = SYSDATE,
        TGT.FCC_USU_ACT              = 'DATABRICKS'
