SELECT 
    FTN_NUM_CTA_INVDUAL,
    FTN_IND_SDO_DISP_VIV97,
    FCN_VALOR_ACCION,
    FTC_FOLIO_BITACORA,
    FCN_ID_TIPO_SUBCTA_97,
    FTN_ID_SUBP,
    FTN_SALDO_VIVI97_SOLI,
    FTN_NUM_APLI_INTE_VIVI97_SOL,
    FCN_ID_VALOR_ACCION,
    -- Apply transformation logic for FTN_SDO_AIVS
    CASE 
        WHEN FTN_NUM_APLI_INTE_VIVI97_SOL <= Saldos THEN FTN_NUM_APLI_INTE_VIVI97_SOL
        ELSE Saldos
    END AS FTN_SDO_AIVS,
    FTN_CONTA_SERV
FROM (
    SELECT 
        FTN_NUM_CTA_INVDUAL,
        FTN_ID_SUBP,
        FTC_NSS_TRABA_AFORE,
        FTN_SALDO_VIVI97_SOLI,
        FTN_NUM_APLI_INTE_VIVI97_SOL,
        SALDO_DISPONIBLE_AIVS,
        FCN_VALOR_ACCION,
        FCN_ID_VALOR_ACCION,
        FTN_IND_SDO_DISP_VIV97,
        FTC_FOLIO_BITACORA,
        FCN_ID_TIPO_SUBCTA_97,
        FTN_CONTA_SERV,
        -- Calculate Saldos iteratively using a running sum
        SALDO_DISPONIBLE_AIVS
  - COALESCE(
      SUM(FTN_NUM_APLI_INTE_VIVI97_SOL) OVER (
        PARTITION BY FTC_NSS_TRABA_AFORE
        ORDER BY FTN_NUM_CTA_INVDUAL
        ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
      ), 0
    ) AS Saldos,

CASE
  WHEN SALDO_DISPONIBLE_AIVS
       - COALESCE(SUM(FTN_NUM_APLI_INTE_VIVI97_SOL) OVER (
           PARTITION BY FTC_NSS_TRABA_AFORE
           ORDER BY FTN_NUM_CTA_INVDUAL
           ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
         ), 0) < 0 THEN 0
  ELSE 1
END AS Bandera
    FROM 
 #DS_900_NSS_MULTIPLES#
) MUL
WHERE Bandera = 1 -- Filter valid rows

UNION ALL

-- Input 2: DS_600_RejInsSaldos → FU_601_UNION_REJ → CG_602_GEN_CAMPOS
SELECT 
    FTN_NUM_CTA_INVDUAL,
    0 AS FTN_IND_SDO_DISP_VIV97, -- Generated field
    0 AS FCN_VALOR_ACCION,       -- Generated field
    '#sr_folio#' AS FTC_FOLIO_BITACORA, -- Parameterized value
    15 AS FCN_ID_TIPO_SUBCTA_97, -- Parameterized value
    FTN_ID_SUBP,
    0 AS FTN_SALDO_VIVI97_SOLI, -- Generated field
    0 AS FTN_NUM_APLI_INTE_VIVI97_SOL, -- Generated field
    0 AS FCN_ID_VALOR_ACCION,    -- Generated field
    0 AS FTN_SDO_AIVS,           -- Generated field
    FTN_CONTA_SERV
FROM (
    SELECT 
        FTN_NUM_CTA_INVDUAL,
        FTN_ID_SUBP,
        FTN_CONTA_SERV
    FROM #DS_600_RejInsSaldos#
    UNION ALL
    SELECT 
        FTN_NUM_CTA_INVDUAL,
        FTN_ID_SUBP,
        FTN_CONTA_SERV
    FROM  (
    SELECT 
        FTN_NUM_CTA_INVDUAL,
        FTN_ID_SUBP,
        FTC_NSS_TRABA_AFORE,
        FTN_SALDO_VIVI97_SOLI,
        FTN_NUM_APLI_INTE_VIVI97_SOL,
        SALDO_DISPONIBLE_AIVS,
        FCN_VALOR_ACCION,
        FCN_ID_VALOR_ACCION,
        FTN_IND_SDO_DISP_VIV97,
        FTC_FOLIO_BITACORA,
        FCN_ID_TIPO_SUBCTA_97,
        FTN_CONTA_SERV,
        -- Calculate Saldos iteratively using a running sum
        SALDO_DISPONIBLE_AIVS
  - COALESCE(
      SUM(FTN_NUM_APLI_INTE_VIVI97_SOL) OVER (
        PARTITION BY FTC_NSS_TRABA_AFORE
        ORDER BY FTN_NUM_CTA_INVDUAL
        ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
      ), 0
    ) AS Saldos,

CASE
  WHEN SALDO_DISPONIBLE_AIVS
       - COALESCE(SUM(FTN_NUM_APLI_INTE_VIVI97_SOL) OVER (
           PARTITION BY FTC_NSS_TRABA_AFORE
           ORDER BY FTN_NUM_CTA_INVDUAL
           ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
         ), 0) < 0 THEN 0
  ELSE 1
END AS Bandera
    FROM 
 #DS_900_NSS_MULTIPLES#
) MUL
WHERE Bandera = 0
) AS FU_601_Output

UNION ALL

-- Input 3: DS_NSS_UNICO
SELECT 
    FTN_NUM_CTA_INVDUAL,
    FTN_IND_SDO_DISP_VIV97,
    FCN_VALOR_ACCION,
    FTC_FOLIO_BITACORA,
    FCN_ID_TIPO_SUBCTA_97,
    FTN_ID_SUBP,
    FTN_SALDO_VIVI97_SOLI,
    FTN_NUM_APLI_INTE_VIVI97_SOL,
    FCN_ID_VALOR_ACCION,
    FTN_SDO_AIVS,
    FTN_CONTA_SERV
FROM #DS_NSS_UNICO#;
