SELECT 
    a.FTC_ORIGEN_TRANSFE,
    a.FTN_CONTA_SERV,
    a.FTD_FEH_PRESEN,
    a.FTC_CURP_TRABA,
    a.FTC_NSS_TRABA_INFO,
    a.FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL,
    a.FTC_RFC_TRABA_INFO,
    a.FTC_APELLIDO_PATE_INFO,
    a.FTC_APELLIDO_MATE_INFO,
    a.FTC_NOMBRES_INFO,
    a.FTC_IDENT_LOTE_SOLI,
    a.FTC_NSS_TRABA_AFORE,
    a.FTC_RFC_TRABA_AFORE,
    a.FTC_APELLIDO_PATE_AFORE,
    a.FTC_APELLIDO_MATE_AFORE,
    a.FTC_NOMBRE_AFORE,
    NVL(a.FTN_SALDO_VIVI97_SOLI, 0) AS FTN_SALDO_VIVI97_SOLI,
    a.FTC_CODIGO_RES_OPER,
    a.FTC_DIAG_PROCESO,
    a.FTC_NOMBRE_TRABA_IMSS,
    a.FTN_PERIODO_PAGO,
    a.FTD_FEH_CARGA,
    a.FTC_FOLIO_BITACORA,
    a.FTC_INDI_CUENTA_VIG,
    a.FTD_FEH_VALOR_VIVI,
    a.FTC_ESTATUS,
    a.FTD_FEH_MOVIMIENTO,
    a.FTN_NUM_APLI_INTE_VIVI97_ULT,
    a.FTN_NUM_APLI_INTE_VIVI92_ENV,
    a.FTN_NUM_APLI_INTE_VIVI97_ENV,
    a.FTN_NUM_APLI_INTE_VIVI97_TRA,
    NVL(a.FTN_NUM_APLI_INTE_VIVI92_SOL, 0) AS FTN_NUM_APLI_INTE_VIVI92_SOL,
    NVL(a.FTN_NUM_APLI_INTE_VIVI97_SOL, 0) AS FTN_NUM_APLI_INTE_VIVI97_SOL,
    a.FTN_IDENTI_MOVTO,
    a.FTC_ESTATUS_REVE,
    a.FTN_UTLIMA_APOR_VIVI97,
    a.FTN_INTER_SALDO_VIVI97_ULT,
    a.FTN_INTER_SALDO_VIVI92,
    a.FTN_SALDO_TOT_VIVI92,
    a.FTN_NUM_AIVS_VIVI97_ULT,
    a.FTN_SALDO_VIVI97_ULT,
    a.FTN_SALDO_VIVI97_TRAN,
    a.FTC_INDI_VIVI,
    a.FTD_FEH_REGIS_INDI,
    a.FTC_TIPO_ARCH,
    a.FTC_ESTATUS_REGISTRO,
    a.FTD_FEH_ACTUA_ESTATUS,
    a.FTN_MOTIVO_RECHAZO,
    a.FTN_ESTADO_AFIL,
    a.FCN_ID_SIEFORE,
    a.FCN_ID_TIPO_SUBCTA,
    a.FTN_ID_SUBP,
    ADD_MONTHS(TRUNC(SYSDATE, 'MONTH'), 1) AS FECHA_VALOR_AIVS,
    TRUNC(SYSDATE, 'MONTH') AS FECHA_VALOR_AIVS_TA,
    NVL(c.SALDO_DISPONIBLE_AIVS, 0) AS SALDO_DISPONIBLE_AIVS_VIV97, -- Changed to include null check
    NVL(b.SALDO_DISPONIBLE_AIVS, 0) AS SALDO_DISPONIBLE_AIVS -- Changed to include null check
FROM 
    PROCESOS.TTCRXGRAL_TRANS_INFONA a
left JOIN 
    (SELECT 
        FTC_NUM_CTA_INVDUAL,
        SUM(NVL(FTN_DISP_ACCIONES, 0)) AS SALDO_DISPONIBLE_AIVS,
        FCN_ID_TIPO_SUBCTA 
     FROM 
        CIERREN.TTAFOGRAL_BALANCE_MOVS
     WHERE 
        FCN_ID_SIEFORE = 81
        AND FCN_ID_TIPO_SUBCTA = 15 
        AND FTC_NUM_CTA_INVDUAL IN 
            (SELECT FTN_NUM_CTA_AFORE 
             FROM PROCESOS.TTCRXGRAL_TRANS_INFONA 
             WHERE FTC_FOLIO_BITACORA = '#sr_folio#')
     GROUP BY 
        FTC_NUM_CTA_INVDUAL, FCN_ID_TIPO_SUBCTA) b
ON 
    a.FTN_NUM_CTA_AFORE = b.FTC_NUM_CTA_INVDUAL
left JOIN 
    (SELECT 
        FTC_NUM_CTA_INVDUAL,
        SUM(NVL(FTN_DISP_ACCIONES, 0)) AS SALDO_DISPONIBLE_AIVS,
        FCN_ID_TIPO_SUBCTA 
     FROM 
        CIERREN.TTAFOGRAL_BALANCE_MOVS
     WHERE 
        FCN_ID_SIEFORE = 81
        AND FCN_ID_TIPO_SUBCTA = 16
        AND FTC_NUM_CTA_INVDUAL IN 
            (SELECT FTN_NUM_CTA_AFORE 
             FROM PROCESOS.TTCRXGRAL_TRANS_INFONA 
             WHERE FTC_FOLIO_BITACORA = '#sr_folio#')
     GROUP BY 
        FTC_NUM_CTA_INVDUAL, FCN_ID_TIPO_SUBCTA) c
ON 
    a.FTN_NUM_CTA_AFORE = c.FTC_NUM_CTA_INVDUAL
WHERE 
    a.FTC_FOLIO_BITACORA = '#sr_folio#'
    AND a.FTC_ESTATUS_REGISTRO = 1