SELECT
T.FTC_RFC_INFONA,
T.FTC_CURP,
T.FTC_NSS_AFORE AS FTC_NSS_INFONA,
T.FTC_APELLIDO_PATER_INFONA,
T.FTC_APELLIDO_MATER_INFONA,
T.FTC_NOMBRE_AFORE AS FTC_NOMBRE_INFONA,
T.FTN_CTA_AFORE AS FTN_NUM_CTA_IND,
T.FTC_NOMBRE_IMSS
FROM #CATALOG_SCHEMA#.TEMP_CLIENTES_#SR_FOLIO# T
