SELECT
FTC_RFC_INFONA,
FTC_CURP,
FTC_NSS_AFORE,
ftc_apellido_pater_afore AS FTC_APELLIDO_PATER_INFONA,
ftc_apellido_mater_afore AS FTC_APELLIDO_MATER_INFONA,
FTC_NOMBRE_AFORE,
FTN_CTA_AFORE,
FTC_NOMBRE_IMSS
FROM #CX_PRO_ESQUEMA#.#TL_ETL_DEVO_SALD_EXC#
WHERE FTC_FOLIO = #SR_FOLIO#
ORDER BY FTN_CTA_AFORE, FTC_NSS_AFORE
