MERGE INTO #TABLE_002# ORIG
USING (
    SELECT DISTINCT
        FTC_FOLIO,
        FTN_ID_MARCA,
        FTC_ESTATUS_MARCA AS FTB_ESTATUS_MARCA,
        FTD_FEH_ACT,
        FCC_USU_ACT
    FROM #TABLE_001#
    WHERE FTC_FOLIO = '#SR_FOLIO#'
) AUX
ON (
    ORIG.FTC_FOLIO = AUX.FTC_FOLIO
    AND ORIG.FTN_ID_MARCA = AUX.FTN_ID_MARCA
)
WHEN MATCHED THEN
UPDATE SET
    ORIG.FTB_ESTATUS_MARCA = AUX.FTB_ESTATUS_MARCA,
    ORIG.FTD_FEH_ACT       = AUX.FTD_FEH_ACT,
    ORIG.FCC_USU_ACT       = AUX.FCC_USU_ACT
