    SELECT
       FTC_FOLIO,
       FTN_ID_MARCA,
       '#SR_ACCION#' AS FTB_ESTATUS_MARCA,
       CURRENT_TIMESTAMP AS FTD_FEH_ACT,
       'DATABRICKS' AS FCC_USU_ACT
       FROM CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA
    WHERE FTC_FOLIO='#SR_FOLIO#'