SELECT DISTINCT
    FTC_FOLIO AS FTC_FOLIO,
    FTN_ID_MARCA AS FTN_ID_MARCA ,
    FTB_ESTATUS_MARCA AS FTC_ESTATUS_MARCA,
    FROM_UTC_TIMESTAMP(CURRENT_TIMESTAMP(), 'GMT-6') AS FTD_FEH_ACT,
    FCC_USU_ACT AS FCC_USU_ACT,
    1 AS FTN_NUM_CTA_INVDUAL
FROM 
    #TEMP_VIEW#