SELECT
      '#SR_FOLIO#' AS FTC_FOLIO  
       MAT.FTN_ID_MARCA
       MAT.FTB_ESTATUS_MARCA
       CURRENT_TIMESTAMP AS FTD_FEH_ACT
       'DATABRICKS' AS FCC_USU_ACT
       FROM CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA MAT
       (SELECT DISTINCT 
           FTC_FOLIO
           FTN_NUM_CTA_INVDUAL
           FTC_ID_INSTANCIA
       FROM PROFAPOVOL.TTAFOAVOL_PRINCIPAL
       WHERE FTC_ID_INSTANCIA =#SR_FOLIO#
       AND FTN_REG_ACREDITADO=1) PRI 
       WHERE MAT.FTC_FOLIO=PRI.FTC_FOLIO
       AND MAT.FTN_NUM_CTA_INVDUAL=PRI.FTN_NUM_CTA_INVDUAL
    