SELECT 
Trim(SUBSTR(FTC_LINEA,3,10)) FTN_CONTA_SERV
    ,Trim(SUBSTR(FTC_LINEA,138,40)) FTC_APELLIDO_MATER_INFONA
	  ,Trim(SUBSTR(FTC_LINEA,365,40)) FTC_APELLIDO_MATER_AFORE
	  ,Trim(SUBSTR(FTC_LINEA,98,40)) FTC_APELLIDO_PATER_INFONA
	  ,Trim(SUBSTR(FTC_LINEA,325,40)) FTC_APELLIDO_PATER_AFORE
	  ,Trim(SUBSTR(FTC_LINEA,583,2)) FTN_CODIGO_RES_OPER
	  ,Trim(SUBSTR(FTC_LINEA,41,18)) FTC_CURP
	  ,Trim(SUBSTR(FTC_LINEA,585,15)) FTC_DIAGNOS_PROCE
	  ,Trim(SUBSTR(FTC_LINEA,25,8)) FTD_FEH_PRESEN
	  ,Trim(SUBSTR(FTC_LINEA,240,16))FTC_IDENTI_LOTE_SOLIC
	  ,Trim(SUBSTR(FTC_LINEA,23,2)) FTC_IDENT_PROC_DESMA
	  ,to_number(Trim(SUBSTR(FTC_LINEA,675,15))) FTN_INTERES_SALDO_92
	  ,to_number(Trim(SUBSTR(FTC_LINEA,660,15))) FTN_INTERES_SALDO_97
	  ,Trim(SUBSTR(FTC_LINEA,600,50)) FTC_NOMBRE_IMSS
	  ,Trim(SUBSTR(FTC_LINEA,178,40)) FTC_NOMBRE_INFONA 
	  ,Trim(SUBSTR(FTC_LINEA,405,40))FTC_NOMBRE_AFORE
	  ,Trim(SUBSTR(FTC_LINEA,59,11)) FTC_NSS_INFONA
	  ,Trim(SUBSTR(FTC_LINEA,271,11)) FTC_NSS_AFORE
	  ,to_number(Trim(SUBSTR(FTC_LINEA,650,10))) FTN_NUM_CRED_INFONA
	  ,to_number(Trim(SUBSTR(FTC_LINEA,713,6))) FTN_PERIODO_PAGO
	  ,Trim(SUBSTR(FTC_LINEA,282,13)) FTC_RFC_AFORE
	  ,Trim(SUBSTR(FTC_LINEA,85,13)) FTC_RFC_INFONA
	  ,to_number(Trim(SUBSTR(FTC_LINEA,565,15))) FTN_SALDO_92
	  ,to_number(Trim(SUBSTR(FTC_LINEA,660,15))) FTN_SALDO_97
FROM   CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO
WHERE  SUBSTR(FTC_LINEA,1,2) = 02 
AND    FTN_ID_ARCHIVO = #sr_id_archivo#