MERGE INTO PROCESOS.TTAFOTRAS_DESMARCA_FOVST  TGT
USING (
    SELECT DISTINCT
        FTC_FOLIO,
        FTC_CURP,
        FTN_NUM_CTA_INVDUAL,
        FTD_FEH_ACT,
        FTC_USU_ACT,
        FTN_MOTIVO_RECHAZO,
        FTC_ESTATUS
    FROM CIERREN_DATAUX.TTAFOTRAS_DESMARCA_FOVST_AUX
    WHERE FTC_FOLIO = '#sr_folio#'
) SRC
ON (
    TGT.FTC_FOLIO = SRC.FTC_FOLIO
    AND TGT.FTC_CURP = SRC.FTC_CURP
    AND TGT.FTN_NUM_CTA_INVDUAL = SRC.FTN_NUM_CTA_INVDUAL
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTD_FEH_ACT     = SRC.FTD_FEH_ACT,
        TGT.FTC_USU_ACT     = SRC.FTC_USU_ACT,
        TGT.FTN_MOTIVO_RECHAZO   = SRC.FTN_MOTIVO_RECHAZO,
        TGT.FTC_ESTATUS   = SRC.FTC_ESTATUS
  