SELECT 
	SDD.FTC_FOLIO
	,SDD.FTC_CURP
	,SDD.FTN_NUM_CTA_INVDUAL
	,CASE WHEN (
				CASE
				  WHEN C.FFN_ID_CONFIG_INDI IS NOT NULL
				       AND (C.FCC_VALOR_IND = 1 OR C.FCC_VALOR_IND = 0 OR C.FCC_VALOR_IND IS NULL)
				    THEN NULL
				  ELSE 679
				END
				) = NULL 
			THEN SDD.FTD_FEH_ACT 
			ELSE (FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') 
	END AS FTD_FEH_ACT
	,CASE WHEN (
				CASE
				  WHEN C.FFN_ID_CONFIG_INDI IS NOT NULL
				       AND (C.FCC_VALOR_IND = 1 OR C.FCC_VALOR_IND = 0 OR C.FCC_VALOR_IND IS NULL)
				    THEN NULL
				  ELSE 679
				END
				) = NULL 
			THEN SDD.FTC_USU_ACT 
			ELSE 'DATABRICKS' 
		END AS FTC_USU_ACT
	,CASE
		 WHEN C.FFN_ID_CONFIG_INDI IS NOT NULL
		    AND (C.FCC_VALOR_IND = 1 OR C.FCC_VALOR_IND = 0 OR C.FCC_VALOR_IND IS NULL)
		  THEN NULL
		 ELSE NULL --679
	END AS FTN_MOTIVO_RECHAZO 
	,CASE WHEN (
				CASE
				  WHEN C.FFN_ID_CONFIG_INDI IS NOT NULL
				       AND (C.FCC_VALOR_IND = 1 OR C.FCC_VALOR_IND = 0 OR C.FCC_VALOR_IND IS NULL)
				    THEN NULL
				  ELSE 679
				END
				) = NULL 
			THEN '1' --SDD.FTC_ESTATUS 
			ELSE 
				(
					CASE
					  WHEN C.FFN_ID_CONFIG_INDI IS NOT NULL
					       AND (C.FCC_VALOR_IND = '1' OR C.FCC_VALOR_IND = '0' OR C.FCC_VALOR_IND IS NULL)
					    THEN '1'
					  ELSE '1'--'0'
					END	
				)
		END AS FTC_ESTATUS,
		1 AS FCN_ID_SUBPROCESO, --VALOR DUMMY PARA INSERTAR EN TABLA AUXILIAR
		1 AS FTN_ID_ARCHIVO --VALOR DUMMY PARA INSERTAR EN TABLA AUXILIAR
FROM PROCESOS.TTAFOTRAS_DESMARCA_FOVST SDD
LEFT JOIN CIERREN.TTAFOGRAL_IND_CTA_INDV C
ON SDD.FTN_NUM_CTA_INVDUAL=c.ftn_num_cta_invdual
AND C.FFN_ID_CONFIG_INDI IN ('#config_indi#') 
AND C.FTC_VIGENCIA = '#ind_vigencia#'
WHERE SDD.FTC_FOLIO ='#sr_folio#'
 AND SDD.FTC_ESTATUS=0
AND (SDD.FTN_MOTIVO_RECHAZO NOT IN (93,254,375,1178) OR SDD.FTN_MOTIVO_RECHAZO IS NULL)



















