SELECT 
    FTC_NSS_CURP,
    FTC_NSS,
    FTC_CURP_BUC,
    FTN_NUM_CTA_INVDUAL_BUC,
    FTC_NOMBRE_BUC,
    FTC_AP_PATERNO_BUC,
    FTC_AP_MATERNO_BUC,
    FTC_RFC_BUC,
    FTC_BANDERA_BUC,
    FTN_CELULAR,
    FTC_CORREO_ELEC
FROM (
      SELECT 
         CASE WHEN B.FTC_NSS IS NULL THEN FTC_CURP ELSE FTC_NSS END AS FTC_NSS_CURP,
         B.FTC_NSS AS FTC_NSS,
         B.FTC_CURP FTC_CURP_BUC,
         B.FTN_NUM_CTA_INVDUAL FTN_NUM_CTA_INVDUAL_BUC,
         B.FTC_NOMBRE FTC_NOMBRE_BUC,
         B.FTC_AP_PATERNO FTC_AP_PATERNO_BUC,
         B.FTC_AP_MATERNO FTC_AP_MATERNO_BUC,
         B.FTC_RFC FTC_RFC_BUC,
         B.FTC_BANDERA FTC_BANDERA_BUC,
         B.FTN_CELULAR FTN_CELULAR,
         B.FTC_CORREO_ELEC FTC_CORREO_ELEC,
         ROW_NUMBER() OVER (PARTITION BY FTC_NSS, FTN_NUM_CTA_INVDUAL ORDER BY FTC_NSS, FTN_NUM_CTA_INVDUAL ASC) AS rn
      FROM (
         SELECT FTC_NSS_TRABA_INFO,FTC_NSS_TRABA_AFORE
         FROM CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_INFONAVIT
         WHERE FTC_FOLIO_BITACORA=#SR_FOLIO#) A
      LEFT JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC B 
         ON (A.FTC_NSS_TRABA_AFORE=B.FTC_NSS)
      ORDER BY FTC_NSS, FTN_NUM_CTA_INVDUAL
      )
WHERE rn = 1