SELECT DISTINCT
    MD.FTC_CURP                        ,
    MD.FTC_NSS_AFORE AS FTC_NSS        ,
    MD.FTC_APELLIDO_PATER_AFORE        ,
    MD.FTC_APELLIDO_MATER_AFORE        ,
    MD.FTC_NOMBRE_AFORE                ,
    MD.FTC_RFC_INFONA AS FTC_RFC       ,
    MD.FTC_FOLIO_BITACORA AS FTC_FOLIO ,
    MD.FTN_ID_ARCHIVO                  ,
    MD.FTC_TIPO_ARCH                   ,
    B.FTN_NUM_CTA_INVDUAL              ,
    B.FTC_RFC FTC_RFC_BUC              ,
    B.FTC_BANDERA                      ,
    B.FTN_CELULAR                      ,
    B.FTC_CORREO_ELEC
FROM CIERREN_ETL.TTAFOTRAS_ETL_MARCA_DESMARCA MD 
LEFT JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC B
    ON (MD.FTC_NSS_AFORE = B.FTC_NSS)
WHERE MD.FTN_ID_ARCHIVO='#SR_ID_ARCHIVO#'
  AND MD.FTC_FOLIO_BITACORA = '#SR_FOLIO#'
  ORDER BY MD.FTC_NSS_AFORE, B.FTN_NUM_CTA_INVDUAL