SELECT DISTINCT
   FTC_FOLIO_BITACORA,
   FTN_ID_ARCHIVO,
   FTC_NSS_TRABA_AFORE AS FTC_NSS,
   FTC_CURP_TRABA AS FTC_RFC,
   FTC_RFC_TRABA_INFO,
   FTC_APELLIDO_PATE_INFO,
   FTC_APELLIDO_MATE_INFO,
   FTC_NOMBRES_INFO,
   FTC_TIPO_ARCH
FROM  CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_INFONAVIT
WHERE FTN_ID_ARCHIVO= '#SR_ID_ARCHIVO#'
AND FTC_FOLIO_BITACORA = '#SR_FOLIO#'