SELECT
CASE WHEN B.FTC_NSS IS NULL THEN B.FTC_CURP ELSE B.FTC_NSS END AS FTC_NSS_CURP,
B.FTC_NSS AS FTC_NSS,
B.FTC_CURP FTC_CURP_BUC,
B.FTN_NUM_CTA_INVDUAL FTN_NUM_CTA_INVDUAL_BUC,
B.FTC_RFC FTC_RFC_BUC,
B.FTC_BANDERA FTC_BANDERA_BUC,
B.FTN_CELULAR,
B.FTC_CORREO_ELEC,

D.FTD_FEH_CRE

FROM (
           SELECT FTC_NSS_INFONA,FTC_NSS_AFORE
            FROM CIERREN_ETL.TTAFOTRAS_ETL_MARCA_DESMARCA
           WHERE FTC_FOLIO_BITACORA='#SR_FOLIO#') A
           LEFT JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC B ON (A.FTC_NSS_AFORE=B.FTC_NSS)

           LEFT JOIN CIERREN.TTAFOGRAL_CTA_INVDUAL D ON (B.FTC_NSS=D.FTN_NSS AND B.FTN_NUM_CTA_INVDUAL=D.FTN_NUM_CTA_INVDUAL)

ORDER BY B.FTC_NSS ASC, B.FTN_NUM_CTA_INVDUAL ASC