SELECT 
FTN_ID_ARCHIVO,
FTC_NSS_INFONA           ,
FTC_RFC_INFONA           ,
FTC_RFC_AFORE            ,
FTC_APELLIDO_PATER_AFORE ,
FTC_APELLIDO_MATER_AFORE ,
FTC_NOMBRE_AFORE         ,
FTC_FOLIO_BITACORA       ,
FTC_TIPO_ARCH
FROM CIERREN_ETL.TTAFOTRAS_ETL_MARCA_DESMARCA
WHERE FTN_ID_ARCHIVO= '#SR_ID_ARCHIVO#'
AND FTC_FOLIO_BITACORA = '#SR_FOLIO#'
ORDER BY FTC_NSS_AFORE