SELECT 
   FTC_NSS_AFORE AS FTN_NSS ,
   FTN_CONTA_SERV           ,
   CASE ROW_NUMBER() OVER (PARTITION BY FTC_NSS_AFORE ORDER BY FTC_NSS_AFORE ASC) 
      WHEN 1 THEN 1
      ELSE 0 END AS BNDDUP
FROM CIERREN_ETL.TTAFOTRAS_ETL_MARCA_DESMARCA
WHERE FTN_ID_ARCHIVO= '#SR_ID_ARCHIVO#'
AND FTC_FOLIO_BITACORA = '#SR_FOLIO#'
ORDER BY FTC_NSS_AFORE
