SELECT DISTINCT
   FTC_FOLIO               ,
   FTC_NSS_IMSS AS FTC_NSS ,
   FTN_ID_ARCHIVO          ,
   FTC_CURP                ,
   FTC_APELLIDO_PATERNO    ,
   FTC_APELLIDO_MATERNO    ,
   FTC_NOMBRE              ,
   FTC_INSTITUTO_ORIGEN
FROM #DELTA_TABLA_NAME#
WHERE FTC_INSTITUTO_ORIGEN = '001'