MERGE INTO PROCESOS.TTAFOTRAS_TRANS_REC_PORTA TRAN
USING (

SELECT
'#SR_FOLIO#' AS  FTC_FOLIO,		
'#SR_MASCARA_ARCHIVO#' AS FTC_MASCARA_ENVIO_PROCE,
TO_DATE('#SR_FECHA_ACTUAL#','DD-MM-YYYY') AS FTD_FEH_ENVIO_PROCE,
TO_TIMESTAMP('#SR_FECHA_ACTUAL_TIMESTAMP#','DD-MM-YYYY HH24:MI:SS.FF6') AS FTD_FEH_ACT,
'#SR_USUARIO#' AS FTC_USU_ACT
FROM DUAL
) UPDREC  ON
(
TRAN.FTC_FOLIO = UPDREC.FTC_FOLIO
)
WHEN MATCHED THEN UPDATE SET
TRAN.FTC_MASCARA_ENVIO_PROCE = UPDREC.FTC_MASCARA_ENVIO_PROCE,
TRAN.FTD_FEH_ENVIO_PROCE = UPDREC.FTD_FEH_ENVIO_PROCE,
TRAN.FTD_FEH_ACT = UPDREC.FTD_FEH_ACT,
TRAN.FTC_USU_ACT = UPDREC.FTC_USU_ACT