WITH BD_100_TRANS_REC_PORTA
AS
(
--BD_100_TRANS_REC_PORTA: The connector will use the following SELECT statement at runtime:

SELECT 
T.FTC_FOLIO,
T.FTN_SUBPROCESO,
CASE WHEN T.FTC_INSTITUTO_ORIGEN = 001 THEN T.FTC_NSS_IMSS ELSE T.FTC_CURP END NSS_CURP
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA T
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS S 
ON T.FTC_FOLIO=S.FTC_FOLIO_BITACORA AND T.FTN_NUM_CTA_INVDUAL=S.FTN_NUM_CTA_INVDUAL
AND T.FTN_SUBPROCESO=S.FTN_ID_SUBP  AND T.FTN_NO_LINEA = S.FTN_CONTA_SERV
LEFT JOIN CIERREN.TCAFOGRAL_VALOR_ACCION V ON S.FCN_ID_VALOR_ACCION=V.FCN_ID_VALOR_ACCION AND S.FCN_ID_REGIMEN = V.FCN_ID_REGIMEN
WHERE 1=1
AND T.FTC_FOLIO='#SR_FOLIO#' --  Párametrizado
AND T.FTN_SUBPROCESO = #SR_SUBPROCESO# --  Párametrizado

),
DS_FECHAS_250 AS
(
----||  DS_250_FECHAS
SELECT
'#SR_FOLIO#' AS FTC_FOLIO ---- Con este hace match  DS_250.FTC_FOLIO   y tambien se genera por medio del servicio llegando parametrizado
 ,TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS FECHA_PRESENTACION
,TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'YYYYMMDD') FECHA_POSTERIOR
FROM (
    select FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES       = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),6,2)
        AND FTN_ANIO        = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1 
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 15 
group by TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'YYYYMMDD')
), TF_700
AS
(
SELECT
BD_100.FTC_FOLIO,
BD_100.NSS_CURP,
DS_250.FECHA_PRESENTACION,
DS_250.FECHA_POSTERIOR
FROM BD_100_TRANS_REC_PORTA BD_100
INNER JOIN DS_FECHAS_250 DS_250 ON BD_100.FTC_FOLIO = DS_250.FTC_FOLIO
WHERE 1=1
AND BD_100.FTC_FOLIO = '#SR_FOLIO#' --  Párametrizado
AND BD_100.FTN_SUBPROCESO = #SR_SUBPROCESO# --  Párametrizado
)
 -----||  SE GENERA SUMARIO
SELECT 
'09' TIPO_REG,
'02' ID_SERVICIO,
'56' ID_OPERACION,
'01'ENTIDAD_ORIGEN,
'534' CVE_ORIGEN,
'03' ENTIDAD_DESTINO,
'001'CVE_DESTINO,
FECHA_PRESENTACION AS FECHA_PROCESO,
LPAD(TRIM(TO_CHAR(COUNT(*))),10,'0') AS TOTAL_REGISTROS,
RPAD(' ',616,' ') AS FILLER
FROM TF_700
GROUP BY
FECHA_PRESENTACION