WITH BD_100_TRANS_REC_PORTA
AS
(
--BD_100_TRANS_REC_PORTA: The connector will use the following SELECT statement at runtime:

SELECT 
T.FTC_FOLIO,
T.FTN_NUM_CTA_INVDUAL,
T.FTC_FOLIO_PROCESAR,
T.FTC_NSS_IMSS,
T.FTC_APELLIDO_PATERNO,
T.FTC_APELLIDO_MATERNO,
T.FTC_NOMBRE,
T.FTC_CURP,
T.FTC_TIPO_OPERACION,
T.FTC_INSTITUTO_ORIGEN,
T.FTC_CREDITO,
S.FTN_MONTO_PESOS FTN_MONTO_PESOS_97,
S.FTN_SDO_AIVS FTN_SDO_AIVS_97,
S.FTN_MONTO_PESOS_92,
S.FTN_SDO_AIVS_92,
S.FTN_VALOR_AIVS,
T.FTD_FEH_CREDITO,
T.FTD_FEH_VAL_TRANSFERENCIA,
T.FTC_DIAGNOSTICO,
To_Number(T.FTC_MOTIVO_REC) AS FTN_MOTIVO_RECHAZO,
T.FTC_ESTATUS_OPE,
T.FTN_SUBPROCESO,
to_char(V.FCD_FEH_ACCION,'yyyymmdd') FCD_FEH_ACCION,
S.FTN_IND_SDO_DISP_VIV97,
S.FTN_IND_SDO_DISP_92,
S.FCN_ID_TIPO_SUBCTA_97,
S.FCN_ID_TIPO_SUBCTA_92,
CASE WHEN T.FTC_INSTITUTO_ORIGEN = 001 THEN T.FTC_NSS_IMSS ELSE T.FTC_CURP END NSS_CURP
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA T
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS S 
ON T.FTC_FOLIO=S.FTC_FOLIO_BITACORA AND T.FTN_NUM_CTA_INVDUAL=S.FTN_NUM_CTA_INVDUAL
AND T.FTN_SUBPROCESO=S.FTN_ID_SUBP  AND T.FTN_NO_LINEA = S.FTN_CONTA_SERV
LEFT JOIN CIERREN.TCAFOGRAL_VALOR_ACCION V ON S.FCN_ID_VALOR_ACCION=V.FCN_ID_VALOR_ACCION AND S.FCN_ID_REGIMEN = V.FCN_ID_REGIMEN
WHERE 1=1
AND T.FTC_FOLIO='#SR_FOLIO#' --  Párametrizado
AND T.FTN_SUBPROCESO= #SR_SUBPROCESO# --  Párametrizado

),
BD_200_MAP_NCI_RECHAZO AS
(
--BD_200_MAP_NCI_RECHAZO: The connector will use the following SELECT statement at runtime:

SELECT 
C.FTN_MOTIVO_RECHAZO,
lpad(nvl(I.TMN_CVE_ITGY,'000'),3,'0') TMN_CVE_ITGY --- Se toma este campo
FROM(
SELECT FCN_ID_CAT_CATALOGO AS TMN_CVE_NCI,
CASE 
WHEN FCN_ID_TIPO_CAT=3   THEN FCN_ID_CAT_CATALOGO ---RECHAZO PROCESO NCI
WHEN FCN_ID_TIPO_CAT=20  THEN FCN_ID_CAT_CATALOGO ---RECHAZO IDC
WHEN FCN_ID_TIPO_CAT=223 THEN TO_NUMBER(FCC_VALOR)---RECHAZO TRASPASOS
WHEN FCN_ID_TIPO_CAT=291 THEN TO_NUMBER(FCC_VALOR)---RECHAZO ESTADOS AFIL 
END FTN_MOTIVO_RECHAZO  --- Con este hace match  BD_200.FTN_MOTIVO_RECHAZO
FROM CIERREN.TCCRXGRAL_CAT_CATALOGO 
WHERE FCN_ID_TIPO_CAT IN (3,20,223,291)
)C
INNER JOIN CIERREN.TMSISGRAL_MAP_NCI_ITGY I 
ON C.TMN_CVE_NCI=I.TMN_CVE_NCI
WHERE I.TMC_USO='MOTIVO DE RECHAZO PARA PROCESAR DE TRP'
),
BD_400_LEE_ARCHIVO AS
(

--BD_400_LEE_ARCHIVO: The connector will use the following SELECT statement at runtime:

SELECT
 CASE WHEN Trim(SUBSTR(FTC_LINEA,204,3)) = 001 THEN Trim(SUBSTR(FTC_LINEA,53,11)) ELSE Trim(SUBSTR(FTC_LINEA,184,18)) END NSS_CURP  --- con este hace match BD_400.NSS_CURP
,Trim(SUBSTR(FTC_LINEA,207,10)) IdCreditoInf ---  Se toma este campo
,Trim(SUBSTR(FTC_LINEA,267,10)) IdCreditoFov --- Se toma este campo
FROM CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO 
WHERE SUBSTR(FTC_LINEA,1,2) = 2
AND FTN_ID_ARCHIVO = (SELECT DISTINCT(FTN_ID_ARCHIVO) 
FROM CIERREN_ETL.TTAFOTRAS_ETL_TRANS_REC_PORTA WHERE FTC_FOLIO = '#SR_FOLIO#')
),
DS_FECHAS_250 AS
(
----||  DS_250_FECHAS
SELECT
'#SR_FOLIO#' AS FTC_FOLIO ---- Con este hace match  DS_250.FTC_FOLIO   y tambien se genera por medio del servicio llegando parametrizado
 ,TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS FECHA_PRESENTACION
,TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'YYYYMMDD') FECHA_POSTERIOR
FROM (
    select FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES       = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),6,2)
        AND FTN_ANIO        = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1 
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 15 
group by TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'YYYYMMDD')
), TF_700
AS
(
SELECT
BD_100.FTC_FOLIO,
BD_100.FTN_NUM_CTA_INVDUAL,
BD_100.FTC_FOLIO_PROCESAR,
BD_100.FTC_NSS_IMSS,
BD_100.FTC_APELLIDO_PATERNO,
BD_100.FTC_APELLIDO_MATERNO,
BD_100.FTC_NOMBRE,
BD_100.FTC_CURP,
BD_100.FTC_TIPO_OPERACION,
BD_100.FTC_INSTITUTO_ORIGEN,
BD_100.FTC_CREDITO,
BD_100.FTN_MONTO_PESOS_97,
BD_100.FTN_SDO_AIVS_97,
BD_100.FTN_MONTO_PESOS_92,
BD_100.FTN_SDO_AIVS_92,
BD_100.FTN_VALOR_AIVS,
BD_100.FTD_FEH_CREDITO,
BD_100.FTD_FEH_VAL_TRANSFERENCIA,
BD_100.FTC_DIAGNOSTICO,
REPLACE(TRIM(TRAILING '0' FROM TO_CHAR(BD_100.FTN_MOTIVO_RECHAZO)),'.','') AS vMotiRechToString,
CASE WHEN (REPLACE(TRIM(TRAILING '0' FROM TO_CHAR(BD_100.FTN_MOTIVO_RECHAZO)),'.','')) = '104' THEN '104' ELSE BD_200.TMN_CVE_ITGY END AS vMotiRech,
BD_100.FTC_ESTATUS_OPE,
BD_100.FTN_SUBPROCESO,
BD_100.FCD_FEH_ACCION,
BD_100.FTN_IND_SDO_DISP_VIV97,
BD_100.FTN_IND_SDO_DISP_92,
BD_100.FCN_ID_TIPO_SUBCTA_97,
BD_100.FCN_ID_TIPO_SUBCTA_92,
BD_100.NSS_CURP,
BD_200.TMN_CVE_ITGY,
BD_400.IdCreditoInf,
BD_400.IdCreditoFov,
DS_250.FECHA_PRESENTACION,
DS_250.FECHA_POSTERIOR
FROM BD_100_TRANS_REC_PORTA BD_100
LEFT JOIN BD_200_MAP_NCI_RECHAZO BD_200  ON BD_100.FTN_MOTIVO_RECHAZO = BD_200.FTN_MOTIVO_RECHAZO
INNER JOIN BD_400_LEE_ARCHIVO BD_400   ON BD_100.NSS_CURP = BD_400.NSS_CURP
INNER JOIN DS_FECHAS_250 DS_250 ON BD_100.FTC_FOLIO = DS_250.FTC_FOLIO
WHERE 1=1
AND BD_100.FTC_FOLIO = '#SR_FOLIO#' --  Párametrizado
AND BD_100.FTN_SUBPROCESO = #SR_SUBPROCESO# --  Párametrizado
)

----------------  TERMINA EL ULTIMO WITH Y EMPIEZA LA VALIDACION DE CAMPOS QUE SE ENCUENTRA EN LOS TRANSFORMERS

SELECT
'02' AS TIPO_REGISTRO,
CASE WHEN FTC_FOLIO_PROCESAR IS NULL THEN RPAD(' ',50) ELSE RPAD(FTC_FOLIO_PROCESAR,50,' ') END AS FTC_FOLIO_PROCESAR,
CASE WHEN FTC_NSS_IMSS IS NULL THEN RPAD(' ',11) ELSE RPAD(FTC_NSS_IMSS,11,' ') END AS FTC_NSS_IMSS, 
COALESCE(RPAD(FTC_APELLIDO_PATERNO, 40, ' '), RPAD(' ', 40, ' ')) AS FTC_APELLIDO_PATERNO,
COALESCE(RPAD(FTC_APELLIDO_MATERNO, 40, ' '), RPAD(' ', 40, ' ')) AS FTC_APELLIDO_MATERNO,
COALESCE(RPAD(FTC_NOMBRE, 40, ' '), RPAD(' ', 40, ' ')) AS FTC_NOMBRE,
CASE WHEN FTC_CURP IS NULL THEN RPAD(' ',18) ELSE RPAD(FTC_CURP,18,' ') END AS FTC_CURP,
CASE WHEN FTC_TIPO_OPERACION IS NULL THEN RPAD(' ',2) ELSE RPAD(FTC_TIPO_OPERACION,2,' ') END AS FTC_TIPO_OPERACION,
CASE WHEN FTC_INSTITUTO_ORIGEN IS NULL THEN RPAD(' ',3) ELSE RPAD(FTC_INSTITUTO_ORIGEN,3,' ') END AS FTC_INSTITUTO_ORIGEN,
CASE WHEN IdCreditoInf IS NULL THEN RPAD(' ',10) ELSE RPAD(IdCreditoInf,10,' ') END AS FTC_CREDITO_INFON,
CASE  WHEN 
     FTC_INSTITUTO_ORIGEN='001' 
     AND FTC_ESTATUS_OPE = '01' 
   THEN 
       CASE 
        WHEN FTN_MONTO_PESOS_97 IS NOT NULL
            THEN
          LPAD(
    REPLACE(
          LPAD(SUBSTR(TO_CHAR(FTN_MONTO_PESOS_97), 1, INSTR(TO_CHAR(FTN_MONTO_PESOS_97, 'FM9999999999.99')||'00', '.') - 1),10,'0') 
		  || RPAD(SUBSTR(TRIM(TO_CHAR(FTN_MONTO_PESOS_97, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(FTN_MONTO_PESOS_97, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
    ,'.','')
          ,12,'0')      
        ELSE CASE WHEN (FTN_MONTO_PESOS_97 IS NULL OR FTN_MONTO_PESOS_97 = 0)
               THEN RPAD('0',12,'0') ELSE RPAD('0',12,'0')   END END        
 ELSE RPAD('0',12,'0')
 END AS PESOS_INFON_97,
CASE  
  WHEN 
     FTC_INSTITUTO_ORIGEN = '001'
	 AND FCN_ID_TIPO_SUBCTA_97 = 15
	 AND FTN_IND_SDO_DISP_VIV97 = 1 
     AND FTC_ESTATUS_OPE = '01'
   THEN 
       CASE 
        WHEN FTN_VALOR_AIVS IS NOT NULL
            THEN
           LPAD(
            REPLACE(
          LPAD(SUBSTR(TO_CHAR(FTN_VALOR_AIVS), 1, INSTR(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.99')||'00', '.') - 1),9,'0') 
		  || RPAD(SUBSTR(TRIM(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
        ,'.','')
          ,15,'0')     
        ELSE 
           CASE 
             WHEN (FTN_VALOR_AIVS IS NULL OR FTN_VALOR_AIVS = 0)
               THEN 
                 RPAD('0',15,'0') 
          ELSE 
             RPAD('0',15,'0')   END END        
 ELSE 
   RPAD('0',15,'0')
 END AS VALOR_AIVS_INFON_97,
CASE  
  WHEN 
     FTC_INSTITUTO_ORIGEN = '001'
	 AND FCN_ID_TIPO_SUBCTA_97 = 15
	 AND FTN_IND_SDO_DISP_VIV97 = 1 
     AND FTC_ESTATUS_OPE = '01' 
   THEN 
       CASE 
	     WHEN FCD_FEH_ACCION IS NULL THEN '00010101'
		  ELSE RPAD(FCD_FEH_ACCION,8,'0')
		   END
ELSE ('00010101')
END AS FEH_ACCION_INFON_97,
CASE  
  WHEN 
     FTC_INSTITUTO_ORIGEN='001' 
     AND FTC_ESTATUS_OPE = '01' 
   THEN 
       CASE 
        WHEN FTN_SDO_AIVS_97 IS NOT NULL
         THEN 
          LPAD(
    REPLACE(
          LPAD(SUBSTR(TO_CHAR(FTN_SDO_AIVS_97), 1, INSTR(TO_CHAR(FTN_SDO_AIVS_97, 'FM9999999999.99'), '.') - 1),9,'0') 
		  || RPAD(SUBSTR(TRIM(TO_CHAR(FTN_SDO_AIVS_97, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(FTN_SDO_AIVS_97, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
    ,'.','')
          ,15,'0')
        ELSE 
           CASE 
             WHEN (FTN_SDO_AIVS_97 IS NULL OR FTN_SDO_AIVS_97 = 0)
               THEN 
                 RPAD('0',15,'0') 
          ELSE 
             RPAD('0',15,'0')  END END        
 ELSE 
   RPAD('0',15,'0')
 END AS TOT_AIVS_INFON_97,
CASE WHEN IdCreditoFov IS NOT NULL THEN RPAD(IdCreditoFov,10,' ')
ELSE RPAD(' ',10,' ') END AS FTC_CREDITO_FOVISSS,
CASE  
  WHEN 
     FTC_INSTITUTO_ORIGEN = '002'
     AND FTC_ESTATUS_OPE = '01'
   THEN 
       CASE 
        WHEN FTN_MONTO_PESOS_97 IS NOT NULL
            THEN
          LPAD(
  REPLACE(
          LPAD(SUBSTR(TO_CHAR(FTN_MONTO_PESOS_97), 1, INSTR(TO_CHAR(FTN_MONTO_PESOS_97, 'FM9999999999.99'), '.') - 1),10,'0') 
		  || RPAD(SUBSTR(TRIM(TO_CHAR(FTN_MONTO_PESOS_97, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(FTN_MONTO_PESOS_97, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
  ,'.','')
          ,12,'0')
        ELSE 
           CASE 
             WHEN (FTN_MONTO_PESOS_97 IS NULL OR FTN_MONTO_PESOS_97 = 0)
               THEN 
                 RPAD('0',12,'0') 
          ELSE 
             RPAD('0',12,'0')   END END        
 ELSE 
   RPAD('0',12,'0')
 END AS PESOS_FOVIS_2008,
CASE WHEN
FTC_INSTITUTO_ORIGEN = '002'
AND FCN_ID_TIPO_SUBCTA_97 = 18
AND FTN_IND_SDO_DISP_VIV97 = 1
AND FTC_ESTATUS_OPE = '01'
THEN CASE WHEN FTN_VALOR_AIVS IS NOT NULL 
THEN 
LPAD(
  REPLACE(
  LPAD(SUBSTR(TO_CHAR(FTN_VALOR_AIVS), 1, INSTR(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.99'), '.') - 1),9,'0')
||RPAD(SUBSTR(TRIM(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
  ,'.','')
,15,'0')
  ELSE CASE WHEN (FTN_VALOR_AIVS IS NULL OR FTN_VALOR_AIVS = 0) THEN 
  RPAD('0',15,'0')
  ELSE RPAD('0',15,'0') END END
 ELSE RPAD('0',15,'0') 
END AS VALOR_AIVS_FOVIS_2008,
CASE  
  WHEN 
     FTC_INSTITUTO_ORIGEN = '002'
	 AND FCN_ID_TIPO_SUBCTA_97 = 18
	 AND FTN_IND_SDO_DISP_VIV97 = 1 
     AND FTC_ESTATUS_OPE = '01' 
   THEN 
       CASE 
	     WHEN FCD_FEH_ACCION IS NULL THEN '00010101'
		  ELSE RPAD(FCD_FEH_ACCION,8,'0')
		   END
ELSE ('00010101')
END AS FEH_ACCION_FOVIS_2008,
CASE
    WHEN FTC_INSTITUTO_ORIGEN ='002'
         AND FTC_ESTATUS_OPE = '01'
    THEN
 CASE WHEN  FTN_SDO_AIVS_97 IS NOT NULL
 THEN LPAD(
  REPLACE(
   LPAD(SUBSTR(TO_CHAR(FTN_SDO_AIVS_97), 1, INSTR(TO_CHAR(FTN_SDO_AIVS_97, 'FM9999999999.99'), '.') - 1),9,'0') 
          || RPAD(SUBSTR(TRIM(TO_CHAR(FTN_SDO_AIVS_97, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(FTN_SDO_AIVS_97, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
  ,'.','')
    ,15,'0')
        ELSE 
           CASE 
             WHEN (FTN_SDO_AIVS_97 IS NULL OR FTN_SDO_AIVS_97 = 0)
               THEN 
                 RPAD('0',15,'0') 
          ELSE 
             RPAD('0',15,'0')  END END        
 ELSE 
   RPAD('0',15,'0')
 END AS TOT_AIVS_FOVIS_2008,
CASE  
  WHEN 
     FTD_FEH_CREDITO IS NULL
   THEN RPAD(' ',8,' ') 
ELSE TO_CHAR(FTD_FEH_CREDITO,'YYYYMMDD')
END AS FTD_FEH_CREDITO,
FECHA_POSTERIOR AS FTD_FEH_VAL_TRANSFERENCIA,
CASE
    WHEN FTC_ESTATUS_OPE = '02'
 THEN 
     CASE WHEN vMotiRech IS NOT NULL
            THEN vMotiRech
             ELSE RPAD('0',3,'0') END
ELSE 
   CASE 
      WHEN FTC_ESTATUS_OPE = '01'
       AND FTC_DIAGNOSTICO IS NOT NULL
    THEN FTC_DIAGNOSTICO
   ELSE RPAD('0',3,'0') END
END AS FTC_DIAGNOSTICO,
RPAD(' ',3,' ') AS FTN_MOTIVO_RECHAZO,
RPAD(' ',2,' ') AS FTC_ESTATUS_OPE,
CASE
WHEN FTC_INSTITUTO_ORIGEN='001'
AND FTC_ESTATUS_OPE = '01'
THEN CASE
WHEN FTN_MONTO_PESOS_92 IS NOT NULL
THEN   LPAD(
  REPLACE(
  LPAD(SUBSTR(TO_CHAR(FTN_MONTO_PESOS_92), 1, INSTR(TO_CHAR(FTN_MONTO_PESOS_92, 'FM9999999999.99'), '.') - 1),10,'0')
|| RPAD(SUBSTR(TRIM(TO_CHAR(FTN_MONTO_PESOS_92, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(FTN_MONTO_PESOS_92, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
  ,'.','')
,12,'0')
ELSE CASE WHEN (FTN_MONTO_PESOS_92 IS NULL OR FTN_MONTO_PESOS_92 = 0) 
THEN                  RPAD('0',12,'0') 
ELSE RPAD('0',12,'0') END END
ELSE    RPAD('0',12,'0') 
END AS PESOS_INFON_92,
CASE  
  WHEN 
     FTC_INSTITUTO_ORIGEN='001' 
     AND FCN_ID_TIPO_SUBCTA_92 = 16 
     AND FTN_IND_SDO_DISP_92 = 1  
     AND FTC_ESTATUS_OPE = '01' 
   THEN 
       CASE 
        WHEN FTN_VALOR_AIVS IS NOT NULL
         THEN 
          LPAD(
      REPLACE(
          LPAD(SUBSTR(TO_CHAR(FTN_VALOR_AIVS), 1, INSTR(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.99'), '.') - 1),9,'0') 
          || RPAD(SUBSTR(TRIM(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
      ,'.','')
          ,15,'0')
        ELSE 
           CASE 
             WHEN (FTN_VALOR_AIVS IS NULL OR FTN_VALOR_AIVS = 0)
               THEN 
                 RPAD('0',15,'0') 
          ELSE 
             RPAD('0',15,'0')  END END        
 ELSE 
   RPAD('0',15,'0')
 END AS VALOR_AIVS_INFON_92,
 CASE  
  WHEN 
     FTC_INSTITUTO_ORIGEN='001' 
     AND FCN_ID_TIPO_SUBCTA_92 = 16 
     AND FTN_IND_SDO_DISP_92 = 1  
     AND FTC_ESTATUS_OPE = '01' 
   THEN 
       CASE 
	     WHEN FCD_FEH_ACCION IS NULL THEN '00010101'
		  ELSE RPAD(FCD_FEH_ACCION,8,'0')
		   END
ELSE ('00010101')
END AS FEH_ACCION_INFON_92,
 CASE
    WHEN FTC_INSTITUTO_ORIGEN ='001'
         AND FTC_ESTATUS_OPE = '01'
    THEN
 CASE WHEN  FTN_SDO_AIVS_92 IS NOT NULL
 THEN LPAD(
  REPLACE(
   LPAD(SUBSTR(TO_CHAR(FTN_SDO_AIVS_92), 1, INSTR(TO_CHAR(FTN_SDO_AIVS_92, 'FM9999999999.99'), '.') - 1),9,'0') 
          || RPAD(SUBSTR(TRIM(TO_CHAR(FTN_SDO_AIVS_92, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(FTN_SDO_AIVS_92, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
  ,'.','')
          ,15,'0')
        ELSE 
           CASE 
             WHEN (FTN_SDO_AIVS_92 IS NULL OR FTN_SDO_AIVS_92 = 0)
               THEN 
                 RPAD('0',15,'0') 
          ELSE 
             RPAD('0',15,'0')  END END        
 ELSE 
   RPAD('0',15,'0')
 END AS TOT_AIVS_INFON_92,
 CASE  
  WHEN 
     FTC_INSTITUTO_ORIGEN='002' 
     AND FTC_ESTATUS_OPE = '01' 
   THEN 
       CASE 
        WHEN FTN_MONTO_PESOS_92 IS NOT NULL
            THEN
          LPAD(
    REPLACE(
      LPAD(SUBSTR(TO_CHAR(FTN_MONTO_PESOS_92), 1, INSTR(TO_CHAR(FTN_MONTO_PESOS_92, 'FM9999999999.99'), '.') - 1),10,'0') 
		  || RPAD(SUBSTR(TRIM(TO_CHAR(FTN_MONTO_PESOS_92, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(FTN_MONTO_PESOS_92, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
    ,'.','')
          ,12,'0')
         
        ELSE 
           CASE 
             WHEN (FTN_MONTO_PESOS_92 IS NULL OR FTN_MONTO_PESOS_92 = 0)
               THEN 
                 RPAD('0',12,'0') 
          ELSE 
             RPAD('0',12,'0')   END END        
 ELSE 
   RPAD('0',12,'0')
 END AS PESOS_FOVIS_92,
 CASE
    WHEN FTC_INSTITUTO_ORIGEN ='002'
	AND FCN_ID_TIPO_SUBCTA_92 = 17
	AND FTN_IND_SDO_DISP_92 = 1
    AND FTC_ESTATUS_OPE = '01'
    THEN
 CASE WHEN  FTN_VALOR_AIVS IS NOT NULL
 THEN LPAD(
  REPLACE(
LPAD(SUBSTR(TO_CHAR(FTN_VALOR_AIVS), 1, INSTR(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.99'), '.') - 1),9,'0') 
|| RPAD(SUBSTR(TRIM(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(FTN_VALOR_AIVS, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
  ,'.','')
          ,15,'0')
        ELSE 
           CASE 
             WHEN (FTN_VALOR_AIVS IS NULL OR FTN_VALOR_AIVS = 0)
               THEN 
                 RPAD('0',15,'0') 
          ELSE 
             RPAD('0',15,'0')  END END        
 ELSE 
   RPAD('0',15,'0')
 END AS VALOR_AIVS_FOVIS_92,
  CASE
    WHEN FTC_INSTITUTO_ORIGEN ='002'
	AND FCN_ID_TIPO_SUBCTA_92 = 17
	AND FTN_IND_SDO_DISP_92 = 1
    AND FTC_ESTATUS_OPE = '01'
	THEN CASE WHEN FCD_FEH_ACCION IS NULL
	         THEN '00010101'
			 ELSE RPAD(FCD_FEH_ACCION,8,'0') END
   ELSE ('00010101')
   END AS FEH_ACCION_FOVIS_92,
   CASE
    WHEN FTC_INSTITUTO_ORIGEN ='002'
    AND FTC_ESTATUS_OPE = '01'
    THEN
 CASE WHEN  FTN_SDO_AIVS_92 IS NOT NULL
 THEN LPAD(
  REPLACE(
  LPAD(SUBSTR(TO_CHAR(FTN_SDO_AIVS_92), 1, INSTR(TO_CHAR(FTN_SDO_AIVS_92, 'FM9999999999.99'), '.') - 1),9,'0') 
|| RPAD(SUBSTR(TRIM(TO_CHAR(FTN_SDO_AIVS_92, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(FTN_SDO_AIVS_92, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
  ,'.','')
          ,15,'0')
        ELSE 
           CASE 
             WHEN (FTN_SDO_AIVS_92 IS NULL OR FTN_SDO_AIVS_92 = 0)
               THEN 
                 RPAD('0',15,'0') 
          ELSE 
             RPAD('0',15,'0')  END END        
 ELSE 
   RPAD('0',15,'0')
 END AS TOT_AIVS_FOVIS_92,
RPAD(' ',200,' ') AS FILLER
FROM TF_700