WITH SF_300_ARCH_RESP_3286 AS
(
SELECT 1 AS ORDEN, 
TIPO_REGISTRO||ID_SERVICIO||ID_OPERACION||TIPO_ENT_ORIGEN||CVE_ENT_ORIGEN||TIPO_ENT_DESTINO||CVE_ENT_DESTINO||FECHA_PROCESO||RESULTADO_OPERA||MOTIVO_RECHAZO||FILLER AS TEXTO
FROM #DELTA_ENCABEZADO#
--dbx_mit_dev_1udbvf_workspace.default.delta_gar_0100_encabezado_202505161127393242
UNION ALL
SELECT 2 AS ORDEN,TIPO_REGISTRO||FTC_FOLIO_PROCESAR||FTC_NSS_IMSS||FTC_APELLIDO_PATERNO||FTC_APELLIDO_MATERNO||FTC_NOMBRE||FTC_CURP||FTC_TIPO_OPERACION||FTC_INSTITUTO_ORIGEN||FTC_CREDITO_INFON||PESOS_INFON_97||VALOR_AIVS_INFON_97||FEH_ACCION_INFON_97||TOT_AIVS_INFON_97||FTC_CREDITO_FOVISSS||PESOS_FOVIS_2008||VALOR_AIVS_FOVIS_2008||FEH_ACCION_FOVIS_2008||TOT_AIVS_FOVIS_2008||FTD_FEH_CREDITO||FTD_FEH_VAL_TRANSFERENCIA||FTC_DIAGNOSTICO||FTN_MOTIVO_RECHAZO||FTC_ESTATUS_OPE||PESOS_INFON_92||VALOR_AIVS_INFON_92||FEH_ACCION_INFON_92||TOT_AIVS_INFON_92||PESOS_FOVIS_92||VALOR_AIVS_FOVIS_92||FEH_ACCION_FOVIS_92||TOT_AIVS_FOVIS_92||FILLER AS TEXTO
FROM #DELTA_DETALLE#
--dbx_mit_dev_1udbvf_workspace.default.delta_gar_0200_detalle_202505161127393242
UNION ALL
SELECT 3 AS ORDEN,
 TIPO_REG||ID_SERVICIO||ID_OPERACION||ENTIDAD_ORIGEN||CVE_ORIGEN||ENTIDAD_DESTINO||CVE_DESTINO||FECHA_PROCESO||TOTAL_REGISTROS||FILLER AS TEXTO
FROM #DELTA_SUMARIO# 
--dbx_mit_dev_1udbvf_workspace.default.delta_gar_0300_sumario_202505161127393242
)
SELECT TEXTO FROM SF_300_ARCH_RESP_3286
ORDER BY ORDEN ASC