--UPDATE CIERREN.TTAFOGRAL_IND_CTA_INDV
SELECT DISTINCT
	C.FCN_ID_IND_CTA_INDV
	,0 as FTC_VIGENCIA
	, (FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_ACT
	, 'DATABRICKS' AS FCC_USU_ACT	
	, M.FTC_FOLIO AS FTC_FOLIO
FROM 
PROCESOS.TTAFOTRAS_DESMARCA_FOVST M
INNER JOIN
	CIERREN.TTAFOGRAL_IND_CTA_INDV C
ON
M.FTN_NUM_CTA_INVDUAL = C.FTN_NUM_CTA_INVDUAL
where
	M.FTC_FOLIO = '#sr_folio#'
	--AND M.FCC_USU_ACT = 'DATABRICKS'
	AND C.FFN_ID_CONFIG_INDI = 15
  AND C.FCC_VALOR_IND <> 0 --- PREGUNTAR SI OPERA CON 0 Y 1
	AND C.FTC_VIGENCIA = 1
	AND M.FTN_MOTIVO_RECHAZO IS NULL

 