--INSERT INTO PROCESOS.TTCRXGRAL_TRANS_INFONA
SELECT 
	FTC_ORIGEN_TRANSFE,
	FTN_CONTA_SERV,
	FTD_FEH_PRESEN,
	FTC_CURP_TRABA,
	FTC_NSS_TRABA_INFO,
	FTN_NUM_CTA_AFORE,
	FTC_RFC_TRABA_INFO,
	FTC_APELLIDO_PATE_INFO,
	FTC_APELLIDO_MATE_INFO,
	FTC_NOMBRES_INFO,
	FTC_IDENT_LOTE_SOLI,
	FTC_NSS_TRABA_AFORE,
	FTC_RFC_TRABA_AFORE,
	FTC_APELLIDO_PATE_AFORE,
	FTC_APELLIDO_MATE_AFORE,
	FTC_NOMBRE_AFORE,
	FTN_SALDO_VIVI97_SOLI,
	FTC_CODIGO_RES_OPER,
	FTC_DIAG_PROCESO,
	FTC_NOMBRE_TRABA_IMSS,
	FTC_NUMERO_CRED_INFONA,
	FTN_PERIODO_PAGO,
	FTD_FEH_CARGA,
	FTC_FOLIO_BITACORA,
	FTC_INDI_CUENTA_VIG,
	FTD_FEH_VALOR_VIVI,
	FTC_ESTATUS,
	FTD_FEH_MOVIMIENTO,
	FTN_NUM_APLI_INTE_VIVI97_ULT,
	FTN_NUM_APLI_INTE_VIVI92_ENV,
	FTN_NUM_APLI_INTE_VIVI97_ENV,
	FTN_NUM_APLI_INTE_VIVI97_TRA,
	FTN_NUM_APLI_INTE_VIVI92_SOL,
	FTN_NUM_APLI_INTE_VIVI97_SOL,
	FTC_INDI_DIFE_VIVI92,
	FTC_INDI_DIFE_VIVI97,
	FTN_IDENTI_MOVTO,
	FTC_ESTATUS_REVE,
	FTN_UTLIMA_APOR_VIVI97,
	FTN_INTER_SALDO_VIVI97_ULT,
	FTN_INTER_SALDO_VIVI92,
	FTN_SALDO_TOT_VIVI92,
	FTN_NUM_AIVS_VIVI97_ULT,
	FTN_SALDO_VIVI97_ULT,
	FTN_SALDO_VIVI97_TRAN,
	FTC_INDI_VIVI,
	FTD_FEH_REGIS_INDI,
	FTC_TIPO_ARCH,
	1 AS FTC_ESTATUS_REGISTRO, --MEJORA
	FTD_FEH_ACTUA_ESTATUS,
	FTN_MOTIVO_RECHAZO,
	FTN_ESTADO_AFIL,
	FTD_FEH_CRE,
	FTC_USU_CRE,
	CURRENT_DATE AS FTD_FEH_ACT,
	'DATABRICKS' AS FCC_USU_ACT,
	FCN_ID_SIEFORE,
	FCN_ID_TIPO_SUBCTA,
	FTN_ID_SUBP,
	FTC_CORREO_ELEC,
	FTC_CELULAR,
	FTN_CONTA_SERV_PROC,
	FTD_FEH_PRESEN_PROC
FROM 
PROCESOS.TTCRXGRAL_TRANS_INFONA M
INNER JOIN
	CIERREN.TTAFOGRAL_IND_CTA_INDV C
ON
M.FTN_NUM_CTA_AFORE = C.FTN_NUM_CTA_INVDUAL
where
	M.FTC_FOLIO_BITACORA = '#sr_folio#'
	AND M.FCC_USU_ACT = 'DATABRICKS'
	AND C.FFN_ID_CONFIG_INDI = 14
	AND C.FCC_VALOR_IND <> 2
	AND C.FTC_VIGENCIA = 1
	AND FTC_ESTATUS_REGISTRO = 0



