UPDATE PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE M
SET 
    M.FTD_FEH_ACT = SYSDATE,
    M.FCC_USU_ACT = 'DATABRICKS',
    M.FTN_MOTIVO_RECHAZO = NULL,
    M.FTC_ESTATUS = '1'
WHERE 
    M.FTC_FOLIO = '#sr_folio#'
    AND M.FTC_ESTATUS = '#ind_vigencia#'
    AND EXISTS (
        SELECT 1
        FROM CIERREN.TTAFOGRAL_IND_CTA_INDV C
        WHERE C.FTN_NUM_CTA_INVDUAL = M.FTN_NUM_CTA_INVDUAL
          AND C.FFN_ID_CONFIG_INDI = '#config_indi#'
          AND C.FTC_VIGENCIA = '#ind_vigencia#'
    )
		
/* eS EL SELECT QUE SE USARÍA PARA REALIZAR EL MERGE
SELECT 
FTN_CONTA_SERV
,FTC_FOLIO
,FTN_NUM_CTA_INVDUAL
,current_date AS FTD_FEH_ACT
,'DATABRICKS'  AS FCC_USU_ACT
,NULL AS FTN_MOTIVO_RECHAZO
,1 AS FTC_ESTATUS
FROM PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE M
LEFT JOIN 
    CIERREN.TTAFOGRAL_IND_CTA_INDV C ON 
    M.FTN_NUM_CTA_INVDUAL = C.FTN_NUM_CTA_INVDUAL 
    AND M.FTC_FOLIO = '#sr_folio#'
    AND M.FTC_ESTATUS = '#ind_vigencia#' 
    AND C.FFN_ID_CONFIG_INDI ='#config_indi#'
    AND C.FTC_VIGENCIA = '#ind_vigencia#' 
WHERE 
	M.FTC_FOLIO = '#sr_folio#' 
    AND M.FTC_ESTATUS = '#ind_vigencia#'

*/