--INSERT INTO CIERREN.TTAFOGRAL_IND_CTA_INDV C
SELECT
	C.FTN_NUM_CTA_INVDUAL
	, C.FFN_ID_CONFIG_INDI
	, CASE WHEN M.FTN_ID_SUBP = 364 THEN 2
				 WHEN M.FTN_ID_SUBP = 365 THEN 3
				 WHEN M.FTN_ID_SUBP = 368 THEN 1 
	  END AS FCC_VALOR_IND
	, 1 as FTC_VIGENCIA
	, (FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') as FTD_FEH_REG
	, 'DATABRICKS' as FTC_USU_REG
	, NULL AS FTD_FEH_ACT
	, NULL AS FCC_USU_ACT
	, C.FTN_DETALLE
	, C.FTN_ID_SUBPROCESO_INACTIVA	
FROM 
PROCESOS.TTCRXGRAL_TRANS_INFONA M
INNER JOIN
	CIERREN.TTAFOGRAL_IND_CTA_INDV C
ON
M.FTN_NUM_CTA_AFORE = C.FTN_NUM_CTA_INVDUAL
where
	M.FTC_FOLIO_BITACORA = '#sr_folio#'
	AND M.FCC_USU_ACT = 'DATABRICKS'
	AND C.FFN_ID_CONFIG_INDI = 14
	AND C.FCC_VALOR_IND <> (CASE WHEN M.FTN_ID_SUBP = 364 THEN 2
														WHEN M.FTN_ID_SUBP = 365 THEN 3
														WHEN M.FTN_ID_SUBP = 368 THEN 1 
													END)
	AND C.FTC_VIGENCIA = 1
	AND FTC_ESTATUS_REGISTRO = 0
	GROUP BY
	C.FTN_NUM_CTA_INVDUAL
	, C.FFN_ID_CONFIG_INDI
	, C.FTN_DETALLE
	, C.FTN_ID_SUBPROCESO_INACTIVA	
	, M.FTN_ID_SUBP