--INSERT INTO PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO M
SELECT
		FTD_FEH_PRESEN
         , FTC_CURP
         , FTC_NSS_INFONA
         , FTN_CTA_AFORE
         , FTC_RFC_INFONA
         , FTC_APELLIDO_PATER_INFONA
         , FTC_APELLIDO_MATER_INFONA
         , FTC_NOMBRE_INFONA
         , FTC_IDENTI_LOTE_SOLIC
         , FTC_NSS_AFORE
         , FTC_RFC_AFORE
         , FTC_APELLIDO_PATER_AFORE
         , FTC_APELLIDO_MATER_AFORE
         , FTC_NOMBRE_AFORE
         , FTN_SALDO_97
         , FTN_SALDO_92
         , FTC_CODIGO_RES_OPER
         , FTC_DIAGNOS_PROCE
         , FTC_NOMBRE_IMSS
         , FTN_NUM_CRED_INFONA
         , FTN_INTERES_SALDO_97
         , FTN_INTERES_SALDO_92
         , FTN_PERIODO_PAGO
         , FTD_FEH_CARGA
         , FTC_FOLIO_BITACORA
         , FTC_IDENT_PROC_DESMA
         , FTC_IDENT_CTA_VIGENTE
         , FTC_INDI_VIVI
         , FTD_REGI_INDI
         , FTC_TIPO_ARCH
         , 1 AS FTC_ESTA_REGI --MEJORA
         , FTD_ACTU_ESTA
         , FTN_MOTI_RECH
         , FTN_ESTA_AFIL
         , FTN_ID_SUBP
         , FTN_MOTI_RECH_SALDO
         , FTN_FOLIO_REL
         , FTD_FEH_CRE
         , FCC_USU_CRE
         , CURRENT_DATE AS FTD_FEH_ACT
         , 'DATABRICKS' AS FCC_USU_ACT
         , FTN_CONTA_SERV
         , FTN_NUM_APLI_VIV_97
FROM 
PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO M
INNER JOIN
	CIERREN.TTAFOGRAL_IND_CTA_INDV C
ON
M.FTN_CTA_AFORE = C.FTN_NUM_CTA_INVDUAL
where
	M.FTC_FOLIO_BITACORA = '#sr_folio#'
	AND M.FCC_USU_ACT = 'DATABRICKS'
	AND C.FFN_ID_CONFIG_INDI = 14
	AND C.FCC_VALOR_IND <> 1
	AND C.FTC_VIGENCIA = 1
	AND FTC_ESTA_REGI = 0