--INSERT INTO CIERREN.TTAFOGRAL_IND_CTA_INDV C
SELECT
C.FTN_NUM_CTA_INVDUAL
,C.FFN_ID_CONFIG_INDI
,'1' AS FCC_VALOR_IND
,'1' AS FTC_VIGENCIA
,(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_REG
,'DATABRICKS' AS FTC_USU_REG
,NULL AS FTD_FEH_ACT
,NULL AS FCC_USU_ACT
,C.FTN_DETALLE
,C.FTN_ID_SUBPROCESO_INACTIVA	
FROM 
PROCESOS.TTAFOTRAS_TRANS_REC_PORTA M
INNER JOIN CIERREN.TTAFOGRAL_IND_CTA_INDV C
ON M.FTN_NUM_CTA_INVDUAL = C.FTN_NUM_CTA_INVDUAL
WHERE
M.FTC_FOLIO = '#sr_folio#'
--AND M.FTC_USU_ACT = 'DATABRICKS'
AND C.FFN_ID_CONFIG_INDI = 25
AND C.FCC_VALOR_IND NOT IN ('0','1')
AND C.FTC_VIGENCIA = '1'
--AND FTC_ESTA_REGI = 0
GROUP BY
C.FTN_NUM_CTA_INVDUAL
,C.FFN_ID_CONFIG_INDI
,C.FTN_DETALLE
,C.FTN_ID_SUBPROCESO_INACTIVA