--UPDATE CIERREN.TTAFOGRAL_IND_CTA_INDV
SELECT DISTINCT
	C.FCN_ID_IND_CTA_INDV
	,0 as FTC_VIGENCIA
	, (FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_ACT
	, 'DATABRICKS' AS FCC_USU_ACT	
	, M.FTC_FOLIO_BITACORA AS FTC_FOLIO
FROM 
PROCESOS.TTCRXGRAL_TRANS_INFONA M
INNER JOIN
	CIERREN.TTAFOGRAL_IND_CTA_INDV C
ON
M.FTN_NUM_CTA_AFORE = C.FTN_NUM_CTA_INVDUAL
where
	M.FTC_FOLIO_BITACORA = '#sr_folio#'
	--AND M.FCC_USU_ACT = 'DATABRICKS'
	AND C.FFN_ID_CONFIG_INDI = 14
	AND C.FCC_VALOR_IND <> (CASE WHEN M.FTN_ID_SUBP = 364 THEN 2
                                 WHEN M.FTN_ID_SUBP = 365 THEN 3
                                 WHEN M.FTN_ID_SUBP = 368 THEN 1 
                            END)
	AND C.FTC_VIGENCIA = 1
	AND M.FTN_MOTIVO_RECHAZO IS NULL 