MERGE INTO CIERREN.TTAFOGRAL_IND_CTA_INDV   TGT
USING (
    SELECT DISTINCT
        FCN_ID_IND_CTA_INDV,
        FTN_NUM_CTA_INVDUAL,
        FFN_ID_CONFIG_INDI,
        FCC_VALOR_IND,
        FTC_VIGENCIA,
        FTD_FEH_REG,
        FTC_USU_REG,
        FTD_FEH_ACT,
        FCC_USU_ACT
    FROM CIERREN_DATAUX.TTAFOGRAL_ETL_IND_CTA_INDV_AUX
    WHERE FTC_FOLIO = '#sr_folio#'
) SRC
ON ( 
    TGT.FCN_ID_IND_CTA_INDV = SRC.FCN_ID_IND_CTA_INDV
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FFN_ID_CONFIG_INDI = SRC.FFN_ID_CONFIG_INDI,
        TGT.FCC_VALOR_IND = SRC.FCC_VALOR_IND,
        TGT.FTC_VIGENCIA = SRC.FTC_VIGENCIA,
        TGT.FTD_FEH_ACT = SRC.FTD_FEH_ACT,
        TGT.FCC_USU_ACT = SRC.FCC_USU_ACT