------  INSERT
WITH
DB_100_TRANS_INFONA
AS(
SELECT
FTN_CONTA_SERV,
FTN_NUM_CTA_INVDUAL,
FTC_NSS,
FTC_FOLIO,
FCN_ID_SUBPROCESO
from  PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE
where FTC_FOLIO = '#sr_folio#'
and  FTC_ESTATUS = '1'
),
DB_200_NCI_INDI
AS(
SELECT DISTINCT
C.FTN_NUM_CTA_INVDUAL,
C.FFN_ID_CONFIG_INDI,
C.FCC_VALOR_IND,
C.FTC_VIGENCIA,
C.FTC_USU_REG FTC_USU_REG_IND,
C.FTD_FEH_REG FTD_FEH_REG_IND
FROM 
	PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE T
INNER JOIN 
	CIERREN.TTAFOGRAL_IND_CTA_INDV C 

ON T.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL 
AND T.FTC_FOLIO='#sr_folio#'
AND T.FTC_ESTATUS='1'
AND C.FFN_ID_CONFIG_INDI  = 15 
AND C.FTC_VIGENCIA = '1'
),
TF_300_REGLAS
AS(
SELECT
T.FTN_CONTA_SERV,
T.FTN_NUM_CTA_INVDUAL,
T.FTC_NSS,
T.FTC_FOLIO,
T.FCN_ID_SUBPROCESO,
C.FFN_ID_CONFIG_INDI,
C.FCC_VALOR_IND,
C.FTC_USU_REG_IND,
C.FTD_FEH_REG_IND,
CASE 
			    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
			    THEN 0 
			    WHEN FFN_ID_CONFIG_INDI = 15 AND FCC_VALOR_IND <> '1'
			    THEN 1 
			    ELSE 2 
			END AS VALIDACION
FROM DB_100_TRANS_INFONA T
LEFT JOIN DB_200_NCI_INDI C ON T.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
WHERE T.FTC_FOLIO='#sr_folio#'
)
SELECT DISTINCT
	FTN_NUM_CTA_INVDUAL,
	15 AS FFN_ID_CONFIG_INDI,
	1 AS FCC_VALOR_IND,
	1 AS FTC_VIGENCIA,
	(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_REG,
	'DATABRICKS' AS FTC_USU_REG,
	NULL AS FTD_FEH_ACT,
	NULL AS FCC_USU_ACT
    FROM TF_300_REGLAS
WHERE VALIDACION IN (0,1)
