-- ==========================================
-- CONSULTA ORACLE: DB_200_TTAFOGRAL_BALANCE_MOVS
-- ==========================================
-- Extrae datos de balance de movimientos con consulta compleja
-- Equivalente al stage DB_200_TTAFOGRAL_BALANCE_MOVS
-- ==========================================

WITH PRE AS (
    SELECT FTN_NUM_CTA_INVDUAL
    FROM #CX_CRE_ESQUEMA#.#TL_CRE_PRE_MOVIMIENTOS# PRE
    WHERE PRE.FTC_FOLIO = '#SR_FOLIO#'
    UNION
    SELECT FTN_NUM_CTA_INVDUAL
    FROM #CX_CRE_ESQUEMA#.#TL_CRE_PRE_MOVIMIENTOS# PRE
    WHERE PRE.FTC_FOLIO_REL = '#SR_FOLIO#'
)
SELECT 
    FTN_NUM_CTA_INVDUAL,
    FCN_ID_TIPO_SUBCTA,
    FCN_ID_SIEFORE,
    FTN_DEDUCIBLE,
    FCN_ID_PLAZO,
    SUM(FTN_DISP_PESOS) AS FTN_DISP_PESOS,
    SUM(FTN_DISP_ACCIONES) AS FTN_DISP_ACCIONES
FROM (
    SELECT
        BAL.FTC_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL,
        BAL.FCN_ID_TIPO_SUBCTA,
        BAL.FCN_ID_SIEFORE,
        DECODE(BAL.FTN_DEDUCIBLE, NULL, 0, FTN_DEDUCIBLE) AS FTN_DEDUCIBLE,
        DECODE(BAL.FCN_ID_PLAZO, NULL, 1000, 0, 1000, FCN_ID_PLAZO) AS FCN_ID_PLAZO,
        NVL(BAL.FTN_DISP_PESOS, 0) AS FTN_DISP_PESOS,
        NVL(BAL.FTN_DISP_ACCIONES, 0) AS FTN_DISP_ACCIONES
    FROM #CX_CRN_ESQUEMA#.#TL_CRN_BALANCE_MOVS# BAL, PRE
    WHERE BAL.FTC_NUM_CTA_INVDUAL = PRE.FTN_NUM_CTA_INVDUAL
) 
GROUP BY 
    FTN_NUM_CTA_INVDUAL,
    FCN_ID_TIPO_SUBCTA,
    FCN_ID_SIEFORE,
    FTN_DEDUCIBLE,
    FCN_ID_PLAZO
ORDER BY 
    FTN_NUM_CTA_INVDUAL,
    FCN_ID_TIPO_SUBCTA,
    FCN_ID_SIEFORE,
    FTN_DEDUCIBLE,
    FCN_ID_PLAZO