-- ==========================================
-- JOIN: JO_140 - INNER JOIN CON MÁXIMOS ORACLE
-- ==========================================
-- Realizar Inner Join entre datos del join y máximos de Oracle
-- Equivalente al stage JO_140
-- ==========================================

SELECT
    JOIN_DATA.FCN_ID_SIEFORE,
    JOIN_DATA.FCN_ID_VALOR_ACCION,
    JOIN_DATA.FTC_FOLIO,
    JOIN_DATA.FTC_FOLIO_REL,
    JOIN_DATA.FTF_MONTO_PESOS,
    JOIN_DATA.FTF_MONTO_ACCIONES,
    JOIN_DATA.FTN_NUM_CTA_INVDUAL,
    JOIN_DATA.FCN_ID_TIPO_MOV,
    JOIN_DATA.FCC_TABLA_NCI_MOV,
    JOIN_DATA.FNN_ID_REFERENCIA,
    JOIN_DATA.FCN_ID_SUBPROCESO,
    JOIN_DATA.FTF_MONTO_PESOS_SOL,
    JOIN_DATA.FTF_MONTO_ACCIONES_SOL,
    JOIN_DATA.FCN_ID_CONCEPTO_MOV,
    JOIN_DATA.FTN_ID_MARCA,
    JOIN_DATA.FCN_ID_SALDO_OPERA,
    JOIN_DATA.FCN_ID_TIPO_SUBCTA,
    JOIN_DATA.FCN_ID_PLAZO,
    JOIN_DATA.FCN_ID_TIPO_MONTO,
    JOIN_DATA.FTN_ORIGEN_APORTACION,
    JOIN_DATA.FTN_DEDUCIBLE,
    JOIN_DATA.FCN_VALOR_ACCION,
    JOIN_DATA.FTF_MONTO_PESOS_SUM,
    JOIN_DATA.FTF_MONTO_ACCIONES_SUM,
    JOIN_DATA.FTN_DISP_PESOS,
    JOIN_DATA.FTN_DISP_ACCIONES,
    MAXIMOS.MAXIMO,
    MAXIMOS.MAXIMO2
FROM (
    SELECT *, 1 AS LLAVE
    FROM #CATALOG_SCHEMA#.TEMP_JOIN_MOVS_BALANCE_#SR_FOLIO#
) JOIN_DATA
INNER JOIN #CATALOG_SCHEMA#.TEMP_MAXIMOS_ORACLE_#SR_FOLIO# MAXIMOS
    ON JOIN_DATA.LLAVE = MAXIMOS.LLAVE;