-- NB_PANCIN_MOV_0050_CAN_BALANCE_001_MOVIMIENTOS.sql
-- Propósito: Leer movimientos de la tabla ETL_MOVIMIENTOS con UNION ALL
-- Tipo: OCI (Oracle) - SELECT con JOINs

-- Primera consulta: movimientos por FTC_FOLIO_REL
SELECT  M.FTC_FOLIO,
        M.FTC_FOLIO_REL,
        FTF_MONTO_PESOS,
        FTF_MONTO_ACCIONES,
        FTN_NUM_CTA_INVDUAL,
        M.FCN_ID_TIPO_SUBCTA,
        M.FCN_ID_SIEFORE,
        FCN_ID_VALOR_ACCION,
        FTD_FEH_LIQUIDACION,
        FCN_ID_TIPO_MOV,
        M.FCN_ID_CONCEPTO_MOV,
        FCC_TABLA_NCI_MOV,
        T.FCN_ID_PLAZO,
        FTN_DEDUCIBLE
FROM    #CX_CRE_ESQUEMA#.#TL_CRE_MOVIMIENTOS# M,
        #CX_CRN_ESQUEMA#.#TL_CRN_TIPO_SUBCTA# T,
        #CX_CRN_ESQUEMA#.#TL_CRN_CONFIG_CONCEP_MOV# C
WHERE   M.FTC_FOLIO_REL = '#SR_FOLIO#'
AND     M.FCN_ID_TIPO_SUBCTA = T.FCN_ID_TIPO_SUBCTA
AND     M.FCN_ID_CONCEPTO_MOV = C.FFN_ID_CONCEPTO_MOV
AND     C.FFB_VIGENCIA = 1

UNION ALL

-- Segunda consulta: movimientos por FTC_FOLIO
SELECT  M.FTC_FOLIO,
        M.FTC_FOLIO_REL,
        FTF_MONTO_PESOS,
        FTF_MONTO_ACCIONES,
        FTN_NUM_CTA_INVDUAL,
        M.FCN_ID_TIPO_SUBCTA,
        M.FCN_ID_SIEFORE,
        FCN_ID_VALOR_ACCION,
        FTD_FEH_LIQUIDACION,
        FCN_ID_TIPO_MOV,
        M.FCN_ID_CONCEPTO_MOV,
        FCC_TABLA_NCI_MOV,
        T.FCN_ID_PLAZO,
        FTN_DEDUCIBLE
FROM    #CX_CRE_ESQUEMA#.#TL_CRE_MOVIMIENTOS# M,
        #CX_CRN_ESQUEMA#.#TL_CRN_TIPO_SUBCTA# T,
        #CX_CRN_ESQUEMA#.#TL_CRN_CONFIG_CONCEP_MOV# C
WHERE   M.FTC_FOLIO = '#SR_FOLIO#'
AND     M.FCN_ID_TIPO_SUBCTA = T.FCN_ID_TIPO_SUBCTA
AND     M.FCN_ID_CONCEPTO_MOV = C.FFN_ID_CONCEPTO_MOV
AND     C.FFB_VIGENCIA = 1 