-- ==========================================
-- JOIN: JO_110 - INNER JOIN ENTRE DATASET Y ORACLE
-- ==========================================
-- Realizar Inner Join entre los datos del dataset y los datos de Oracle
-- Equivalente al stage JO_110
-- ==========================================

SELECT 
    DS.FTN_NUM_CTA_INVDUAL,
    DS.FCN_ID_TIPO_SUBCTA,
    DS.FCN_ID_SIEFORE,
    DS.FTN_DEDUCIBLE,
    DS.FCN_ID_PLAZO,
    DS.FTF_MONTO_PESOS_SUM,
    DS.FTF_MONTO_ACCIONES_SUM,
    DS.FTF_MONTO_PESOS_SOL,
    DS.FTF_MONTO_ACCIONES_SOL,
    BAL.FTN_DISP_PESOS,
    BAL.FTN_DISP_ACCIONES
FROM #CATALOG_SCHEMA#.RESULTADO_PREMOVIMIENTOS_#SR_FOLIO# DS
INNER JOIN #CATALOG_SCHEMA#.TEMP_BALANCE_MOVS_#SR_FOLIO# BAL
    ON DS.FTN_NUM_CTA_INVDUAL = BAL.FTN_NUM_CTA_INVDUAL
    AND DS.FCN_ID_TIPO_SUBCTA = BAL.FCN_ID_TIPO_SUBCTA
    AND DS.FCN_ID_SIEFORE = BAL.FCN_ID_SIEFORE
    AND DS.FTN_DEDUCIBLE = BAL.FTN_DEDUCIBLE
    AND DS.FCN_ID_PLAZO = BAL.FCN_ID_PLAZO