-- ==========================================
-- JOIN: JO_120 - LEFT JOIN ENTRE MOVIMIENTOS Y BALANCE
-- ==========================================
-- Realizar Left Join entre datos de movimientos y datos de balance
-- Equivalente al stage JO_120
-- ==========================================

SELECT
    MOV.FCN_ID_SIEFORE,
    MOV.FCN_ID_VALOR_ACCION,
    MOV.FTC_FOLIO,
    MOV.FTC_FOLIO_REL,
    MOV.FTF_MONTO_PESOS,
    MOV.FTF_MONTO_ACCIONES,
    MOV.FTN_NUM_CTA_INVDUAL,
    MOV.FCN_ID_TIPO_MOV,
    MOV.FCC_TABLA_NCI_MOV,
    MOV.FNN_ID_REFERENCIA,
    MOV.FCN_ID_SUBPROCESO,
    MOV.FTF_MONTO_PESOS_SOL,
    MOV.FTF_MONTO_ACCIONES_SOL,
    MOV.FCN_ID_CONCEPTO_MOV,
    MOV.FTN_ID_MARCA,
    MOV.FCN_ID_SALDO_OPERA,
    MOV.FCN_ID_TIPO_SUBCTA,
    MOV.FCN_ID_PLAZO,
    MOV.FCN_ID_TIPO_MONTO,
    MOV.FTN_ORIGEN_APORTACION,
    MOV.FTN_DEDUCIBLE,
    MOV.FCN_VALOR_ACCION,
    BAL.FTF_MONTO_PESOS_SUM,
    BAL.FTF_MONTO_ACCIONES_SUM,
    BAL.FTN_DISP_PESOS,
    BAL.FTN_DISP_ACCIONES
FROM #CATALOG_SCHEMA#.RESULTADO_MOVIMIENTOS_#SR_FOLIO# MOV
LEFT JOIN #CATALOG_SCHEMA#.RESULTADO_SUF_SALDO_FINAL_0020_#SR_FOLIO# BAL
    ON MOV.FTN_NUM_CTA_INVDUAL = BAL.FTN_NUM_CTA_INVDUAL
    AND MOV.FCN_ID_TIPO_SUBCTA = BAL.FCN_ID_TIPO_SUBCTA
    AND MOV.FCN_ID_SIEFORE = BAL.FCN_ID_SIEFORE
    AND MOV.FCN_ID_PLAZO = BAL.FCN_ID_PLAZO
    AND MOV.FTN_DEDUCIBLE = BAL.FTN_DEDUCIBLE 