SELECT 
    FTC_NSS_CURP,
    FTC_NSS,
    FTC_CURP,
    FTN_NUM_CTA_INVDUAL,
    FTC_NOMBRE_AFORE,
    FTC_APELLIDO_PATER_AFORE,
    FTC_APELLIDO_MATER_AFORE,
    FTC_RFC,
    FTC_BANDERA,
    FTN_CELULAR,
    FTC_CORREO_ELEC,
    FTD_FEH_CRE
FROM (
      SELECT 
         CASE WHEN B.FTC_NSS IS NULL THEN B.FTC_CURP ELSE B.FTC_NSS END AS FTC_NSS_CURP,
         B.FTC_NSS AS FTC_NSS,
         B.FTC_CURP,
         B.FTN_NUM_CTA_INVDUAL,
         B.FTC_NOMBRE FTC_NOMBRE_AFORE,
         B.FTC_AP_PATERNO FTC_APELLIDO_PATER_AFORE,
         B.FTC_AP_MATERNO FTC_APELLIDO_MATER_AFORE,
         B.FTC_RFC,
         B.FTC_BANDERA,
         B.FTN_CELULAR FTN_CELULAR,
         B.FTC_CORREO_ELEC FTC_CORREO_ELEC,
         D.FTD_FEH_CRE,
         ROW_NUMBER() OVER (PARTITION BY B.FTC_NSS, B.FTN_NUM_CTA_INVDUAL ORDER BY B.FTC_NSS, B.FTN_NUM_CTA_INVDUAL ASC) AS rn
      FROM (
         SELECT FTC_NSS_TRABA_INFO,FTC_NSS_TRABA_AFORE
         FROM CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_INFONAVIT
         WHERE FTC_FOLIO_BITACORA=#SR_FOLIO#) A
      LEFT JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC B 
         ON (A.FTC_NSS_TRABA_AFORE=B.FTC_NSS)

LEFT JOIN CIERREN.TTAFOGRAL_CTA_INVDUAL D ON (B.FTC_NSS=D.FTN_NSS AND B.FTN_NUM_CTA_INVDUAL=D.FTN_NUM_CTA_INVDUAL)

      ORDER BY FTC_NSS, FTN_NUM_CTA_INVDUAL
      )

WHERE rn = 1