SELECT
  MD.FTC_ORIGEN_TRANSFE,
  MD.FTN_CONTA_SERV,
  MD.FTD_FEH_PRESEN,
  MD.FTC_CURP_TRABA,
  MD.FTC_NSS_TRABA_INFO,
  MD.FTN_NUM_CTA_AFORE,
  MD.FTC_RFC_TRABA_INFO,
  MD.FTC_APELLIDO_PATE_INFO,
  MD.FTC_APELLIDO_MATE_INFO,
  MD.FTC_NOMBRES_INFO,
  MD.FTC_IDENT_LOTE_SOLI,
  MD.FTC_NSS_TRABA_AFORE,
  MD.FTC_RFC_TRABA_AFORE,
  MD.FTC_APELLIDO_PATE_AFORE,
  MD.FTC_APELLIDO_MATE_AFORE,
  MD.FTC_NOMBRE_AFORE,
  MD.FTN_SALDO_VIVI97_SOLI,
  MD.FTC_CODIGO_RES_OPER,
  MD.FTC_DIAG_PROCESO,
  MD.FTC_NOMBRE_TRABA_IMSS,
  MD.FTC_NUMERO_CRED_INFONA,
  MD.FTN_PERIODO_PAGO,
  MD.FTD_FEH_CARGA,
  MD.FTC_FOLIO_BITACORA,
  MD.FTC_INDI_CUENTA_VIG,
  MD.FTD_FEH_VALOR_VIVI,
  MD.FTC_ESTATUS,
  MD.FTD_FEH_MOVIMIENTO,
  MD.FTN_NUM_APLI_INTE_VIVI97_ULT,
  MD.FTN_NUM_APLI_INTE_VIVI92_ENV,
  MD.FTN_NUM_APLI_INTE_VIVI97_ENV,
  MD.FTN_NUM_APLI_INTE_VIVI97_TRA,
  MD.FTN_NUM_APLI_INTE_VIVI92_SOL,
  MD.FTN_NUM_APLI_INTE_VIVI97_SOL,
  MD.FTN_IDENTI_MOVTO,
  MD.FTC_ESTATUS_REVE,
  MD.FTN_UTLIMA_APOR_VIVI97,
  MD.FTN_INTER_SALDO_VIVI97_ULT,
  MD.FTN_INTER_SALDO_VIVI92,
  MD.FTN_SALDO_TOT_VIVI92,
  MD.FTN_NUM_AIVS_VIVI97_ULT,
  MD.FTN_SALDO_VIVI97_ULT,
  MD.FTN_SALDO_VIVI97_TRAN,
  MD.FTN_ID_ARCHIVO,
  MD.FTN_ID_SUBP,
  MD.FTC_TIPO_ARCH,
  VAL.FTN_NUM_CTA_INVDUAL,
  VAL.FTN_ESTATUS_DIAG,
  VAL.FTC_ID_DIAGNOSTICO

FROM CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_INFONAVIT MD
LEFT JOIN (
    SELECT 
       FTN_NSS             ,
       FTN_NUM_CTA_INVDUAL ,
       FTN_ESTATUS_DIAG    ,
       FTC_ID_DIAGNOSTICO
    FROM ( 
         SELECT 
            FTN_NSS             ,
            FTN_NUM_CTA_INVDUAL ,
            FTN_ESTATUS_DIAG    ,
            FTC_ID_DIAGNOSTICO  ,
            ROW_NUMBER() OVER (PARTITION BY FTN_NSS, FTC_ID_DIAGNOSTICO ORDER BY FTN_NSS, FTC_ID_DIAGNOSTICO ASC) AS rn
          FROM CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE
          WHERE FTC_FOLIO = '#SR_FOLIO#'
         )
         WHERE rn = 1
     ) VAL
  ON MD.FTC_NSS_TRABA_AFORE = VAL.FTN_NSS
WHERE MD.FTC_FOLIO_BITACORA= '#SR_FOLIO#'
  AND MD.FTN_ID_ARCHIVO = #SR_ID_ARCHIVO#
