SELECT
C.FCN_ID_IND_CTA_INDV,
C.FTN_NUM_CTA_INVDUAL,
C.FFN_ID_CONFIG_INDI,
C.FCC_VALOR_IND,
C.FTC_VIGENCIA,
C.FTN_DETALLE,
C.FTD_FEH_REG
FROM ( SELECT B.FTN_NUM_CTA_INVDUAL
             FROM ( SELECT FTC_CURP
                        FROM CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_FOVISSSTE
                        WHERE FTC_FOLIO = '#SR_FOLIO#') A 
	LEFT JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC B ON (A.FTC_CURP=B.FTC_CURP))B, 
            CIERREN.TTAFOGRAL_IND_CTA_INDV C
             WHERE B.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
               AND C.FFN_ID_CONFIG_INDI IN (2,5,15) 
               AND FTC_VIGENCIA=1
