 With MAPEO_PRE_DISP AS(

--RETIRO IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_RETIRO AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_RETIRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    677 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--RECARGOS IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_ACT_RECARGOS AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_ACT_RECARGOS / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    678 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--CESANTIA Y VEJEZ IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_CENSATIA_VEJEZ AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_CENSATIA_VEJEZ / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    679 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--RECARGOS CESANTIA Y VEJEZ IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_ACT_RECARGOS_CYV AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_ACT_RECARGOS_CYV / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    680 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--APORTACIONES VOLUNTARIAS IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_VOLUNT AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_VOLUNT / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'AVO' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    681 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--APORTACIONES COMPLEMENTARIAS RETIRO IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_APORT_COMPLE_RETIRO AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_APORT_COMPLE_RETIRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'COM' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    682 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--APORTACIONES LARGO PLAZO IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_APORT_LARGO_PLAZO AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_APORT_LARGO_PLAZO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'AVO' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    683 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 )

  SELECT 
FTC_FOLIO
,FTN_ID_ARCHIVO
,FTN_NO_LINEA
,FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA
,FCN_ID_PROCESO
,FCN_ID_SUBPROCESO
,FCN_ID_CAT_SUBCTA
,FTF_MONTO_PESOS
,FTF_MONTO_ACCIONES
,FTC_TABLA_NCI_MOV
,FNN_ID_VIV_GARANTIA
,FFN_ID_CONCEPTO_MOV
,FTN_NSS
,FTC_CURP
,to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEC_CRE
,"DATABRICKS" AS FTC_USU_CRE
,FLN_ID_LIB_APORT
,FTC_NOMBRE
,NULL AS FTN_TIPO_REG
,NULL AS FTN_ID_MONTO
,NULL AS FTC_RFC
,NULL AS FCN_REG_PATRONAL_IMSS
FROM MAPEO_PRE_DISP C