SELECT SUBSTR(FTC_LINEA,107,11) FTC_NSS
       ,SUBSTR(FTC_LINEA,13,11) FTC_NSS_IMSS
       ,FTN_ID_ARCHIVO
       ,SUBSTR(FTC_LINEA,524,12) FTC_IMPORTE_CUOTA_SOCIAL  -- ISSSTE
       ,'159' FTC_SUBCTA_CUOTA_SOCIAL  -- ISSSTE
       ,SUBSTR(FTC_LINEA,230,7) FTC_IMPORTE_CUOTA_SOCIAL_IMSS  -- IMSS
       ,'153' FTC_SUBCTA_CUOTA_SOCIAL_IMSS  -- IMSS
       ,SUBSTR(FTC_LINEA,237,7) FTC_IMPORTE_ESTATAL_IMSS  -- IMSS
       ,'154' FTC_SUBCTA_CUOTA_ESTATAL_IMSS  -- IMSS
       ,SUBSTR(FTC_LINEA,244,7) FTC_IMPORTE_ESPECIAL_IMSS  -- IMSS
       ,'155' FTC_SUBCTA_CUOTA_ESPECIAL_IMSS  -- IMSS
       ,SUBSTR (FTC_LINEA,443,1) FTC_ID_VIV_GARANTIA  -- ISSSTE
       ,SUBSTR (FTC_LINEA,280,1) FTC_ID_VIV_GARANTIA_IMSS
       ,SUBSTR (FTC_LINEA,005,8) FTC_ID_REFERENCIA
       ,FTN_NO_LINEA
       ,SUBSTR (FTC_LINEA,142,18) FTC_CURP   -- ISSSTE
       ,SUBSTR (FTC_LINEA,37,18) FTC_CURP_IMSS
       ,decode(SUBSTR (FTC_LINEA,281,2), '01', 268,'02', 269) FLN_ID_LIB_APORT
       ,decode(SUBSTR(FTC_LINEA,365,2),null,269,268) FLN_ID_LIB_APORT_IMSS
       ,SUBSTR(FTC_LINEA,55,50) FTC_NOMBRE_IMSS
       ,SUBSTR(TRIM(SUBSTR(FTC_LINEA,160,40)) || ' ' || TRIM(SUBSTR(FTC_LINEA,200,40)) || ' ' || TRIM(SUBSTR(FTC_LINEA,240,40)),1,200) FTC_NOMBRE_ISSSTE
       -- Solo para  Cliente Sua
       ,SUBSTR(FTC_LINEA,118,11) FTC_NSS_SEGUN_ISSSTE   --  ISSSTE
       ,SUBSTR(FTC_LINEA,129,13) FTC_RFC   --  ISSSTE
       ,SUBSTR(FTC_LINEA,24,13) FTC_RFC_IMSS
       ,SUBSTR(FTC_LINEA,85,6) FNC_PERIODO_PAGO_PATRON   --  ISSSTE
       ,SUBSTR(FTC_LINEA,105,6) FNC_PERIODO_PAGO_PATRON_IMSS
       ,SUBSTR(FTC_LINEA,91,8) FND_FECHA_PAGO   --  ISSSTE
       ,SUBSTR(FTC_LINEA,111,8) FND_FECHA_PAGO_IMSS
       ,SUBSTR(FTC_LINEA,99,8) FND_FECHA_VALOR_IMSS_ACV   --  ISSSTE
       ,SUBSTR(FTC_LINEA,127,8) FND_FECHA_VALOR_IMSS_ACV_IMSS
       ,SUBSTR(FTC_LINEA,283,7) FNN_ULTIMO_SALARIO_INT   --  ISSSTE
       ,SUBSTR(FTC_LINEA,135,7) FNN_ULTIMO_SALARIO_INT_IMSS	   
       ,SUBSTR(FTC_LINEA,142,6) FNC_FOLIO_PAGO_SUA_IMSS
       ,SUBSTR(FTC_LINEA,148,11) FNC_REG_PATRONAL_IMSS_IMSS
       ,SUBSTR(FTC_LINEA,16,12) FNC_RFC_PATRON   --  ISSSTE
       ,SUBSTR(FTC_LINEA,159,13) FNC_RFC_PATRON_IMSS
       ,SUBSTR(FTC_LINEA,290,3) FNN_DIAS_COTZDOS_BIM   --  ISSSTE
       ,CAST(SUBSTR(FTC_LINEA,175,2) AS VARCHAR(3)) FNN_DIAS_COTZDOS_BIM_IMSS
       ,SUBSTR(FTC_LINEA,293,3) FNN_DIAS_INCAP_BIMESTRE   --  ISSSTE
       ,CAST(SUBSTR(FTC_LINEA,177,2) AS VARCHAR(3)) FNN_DIAS_INCAP_BIMESTRE_IMSS
       ,SUBSTR(FTC_LINEA,296,3) FNN_DIAS_AUSENT_BIMESTRE   --  ISSSTE
       ,CAST(SUBSTR(FTC_LINEA,179,2) AS VARCHAR(3)) FNN_DIAS_AUSENT_BIMESTRE_IMSS
       ,SUBSTR(FTC_LINEA,443,1) FNN_ID_VIV_GARANTIA   --  ISSSTE
       ,SUBSTR(FTC_LINEA,272,8) FND_FECHA_PAGO_CUOTA_GUB_IMSS
       ,SUBSTR(FTC_LINEA,99,8) FND_FECHA_VALOR_RCV   --  ISSSTE
       ,SUBSTR(FTC_LINEA,119,8) FND_FECHA_VALOR_RCV_IMSS
       ,SUBSTR(FTC_LINEA,13,3) FNN_CVE_ENT_RECEP_PAGO   --  ISSSTE
       ,SUBSTR(FTC_LINEA,172,3) FNN_CVE_ENT_RECEP_PAGO_IMSS
       ,SUBSTR(FTC_LINEA,28,40) FNC_DEPEND_CTRO_PAGO   --  ISSSTE	
       ,SUBSTR(FTC_LINEA,68,7) FNN_CTRO_PAGO_SAR   --  ISSSTE
       ,SUBSTR(FTC_LINEA,75,5) FNN_CVE_RAMO   --  ISSSTE	
       ,SUBSTR(FTC_LINEA,80,5) FNC_CVE_PAGADURIA   --  ISSSTE
       ,SUBSTR(FTC_LINEA,283,7) FNN_SUELDO_BASICO_COTIZ_RCV   --  ISSSTE	
       ,SUBSTR(FTC_LINEA,280,1) FNC_ID_TRABAJADOR_BONO   --  ISSSTE
       ,SUBSTR(FTC_LINEA,281,2) FCN_ID_TIPO_APO   --  ISSSTE	
FROM   CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO
WHERE  SUBSTR(FTC_LINEA,1,2) = 02  
AND FTN_ID_ARCHIVO = #sr_id_archivo#