SELECT 
   SUBSTR(FTC_LINEA,107,11) FTC_NSS
            ,SUBSTR(FTC_LINEA,290,12) FTC_IMPORTE_SAR_23
        ,SUBSTR(FTC_LINEA,302,12) FTC_IMPORTE_RET_24
        ,SUBSTR(FTC_LINEA,314,12) FTC_IMPORTE_CV_25
        ,SUBSTR(FTC_LINEA,326,12) FTC_IMPORTE_CV_26
        ,SUBSTR(FTC_LINEA,338,12) FTC_IMPORTE_RET_SAR_27
        ,SUBSTR(FTC_LINEA,350,12) FTC_IMPORTE_RET_EXT_28
        ,SUBSTR(FTC_LINEA,362,12) FTC_IMPORTE_CV_PAT_29
        ,SUBSTR(FTC_LINEA,374,12) FTC_IMPORTE_CV_TRAB_30
        ,SUBSTR(FTC_LINEA,386,7) FTC_IMPORTE_AHO_TRAB_31
        ,SUBSTR(FTC_LINEA,393,7) FTC_IMPORTE_AHO_DEP_32
        ,SUBSTR(FTC_LINEA,400,12) FTC_IMPORTE_AHO_EXT_33
        ,SUBSTR(FTC_LINEA,412,12) FTC_IMPORTE_AHO_DEP_34
       ,FTN_ID_ARCHIVO     
       ,SUBSTR (FTC_LINEA,424,12) FTC_INTER_RETIRO_SAR
       ,'157' FTC_SUBCTA_INTER_RETIRO_SAR
       ,SUBSTR (FTC_LINEA,436,12) FTC_INTER_RETIRO_ISSSTE
       ,'158' FTC_SUBCTA_INTER_RETIRO_ISSSTE
       ,SUBSTR (FTC_LINEA,448,12) FTC_INTER_CV_PATRON
       ,'163' FTC_SUBCTA_CV_PATRON
       ,SUBSTR (FTC_LINEA,460,12) FTC_INTER_CV_TRAB
       ,'162' FTC_SUBCTA_CV_TRAB
       ,SUBSTR (FTC_LINEA,472,12) FTC_INTER_EXT_RETIRO_SAR
       ,'157' FTC_SUBCTA_INTER_EXT_SAR
       ,SUBSTR (FTC_LINEA,484,12) FTC_INTER_EXT_RETIRO
       ,'158' FTC_SUBCTA_INTER_EXT_RETIRO
       ,SUBSTR (FTC_LINEA,496,12) FTC_INTER_EXT_CV_PATRON
       ,'163' FTC_SUBCTA_INTER_EXT_CV_PATRON
       ,SUBSTR (FTC_LINEA,508,12) FTC_INTER_EXT_CV_TRAB
       ,'162' FTC_SUBCTA_INTER_EXT_CV_TRAB
       ,SUBSTR (FTC_LINEA,520,12) FTC_INTER_AHORRO_TRAB
       ,'160' FTC_SUBCTA_INTER_AHORRO_TRAB
       ,SUBSTR (FTC_LINEA,532,12) FTC_INTER_AHORRO_DEP
       ,'161' FTC_SUBCTA_INTER_AHORRO_DEP
       ,SUBSTR (FTC_LINEA,544,12) FTC_INTER_EXT_AHORRO
       ,'160' FTC_SUBCTA_INTER_EXT_AHORRO
       ,SUBSTR (FTC_LINEA,556,12) FTC_INTER_EXT_AHORRO_DEP
       ,'161' FTC_SUBCTA_INTER_EXT_DEP
       ,SUBSTR (FTC_LINEA,568,12) FTC_TOT_INTERES 
       ,SUBSTR (FTC_LINEA,005,8) FTC_ID_REFERENCIA
       ,FTN_NO_LINEA
       ,SUBSTR (FTC_LINEA,142,18) FTC_CURP
        ,SUBSTR (FTC_LINEA,1,2) FTN_TIPO_REG
        ,decode(SUBSTR (FTC_LINEA,281,2), '01', 268,'02', 269) FLN_ID_LIB_APORT
        ,TRIM(SUBSTR(FTC_LINEA,160,40)) || ' ' || TRIM(SUBSTR(FTC_LINEA,200,40)) || ' ' || TRIM(SUBSTR(FTC_LINEA,240,40)) FTC_NOMBRE
       -- Solo para Cliente SUA
       ,SUBSTR(FTC_LINEA,129,13) FTC_RFC   
       ,SUBSTR(FTC_LINEA,85,6) FNC_PERIODO_PAGO_PATRON   
       ,SUBSTR(FTC_LINEA,91,8) FND_FECHA_PAGO   
       ,SUBSTR(FTC_LINEA,99,8) FND_FECHA_VALOR_IMSS_ACV
       ,SUBSTR(FTC_LINEA,283,7) FNN_ULTIMO_SALARIO_INT_PER       
       ,SUBSTR(FTC_LINEA,16,12) FNC_RFC_PATRON
       ,SUBSTR(FTC_LINEA,290,3) FNN_DIAS_COTZDOS_BIM   
       ,SUBSTR(FTC_LINEA,293,3) FNN_DIAS_INCAP_BIMESTRE      
       ,SUBSTR(FTC_LINEA,296,3) FNN_DIAS_AUSENT_BIMESTRE   
       ,SUBSTR(FTC_LINEA,99,8) FND_FECHA_VALOR_RCV
       ,SUBSTR(FTC_LINEA,13,3) FNN_CVE_ENT_RECEP_PAGO
       ,SUBSTR(FTC_LINEA,118,11) FNN_NSS_ISSSTE
       ,SUBSTR(FTC_LINEA,28,40) FNC_DEPEND_CTRO_PAGO
       ,SUBSTR(FTC_LINEA,68,7) FNN_CTRO_PAGO_SAR
       ,SUBSTR(FTC_LINEA,75,5) FNN_CVE_RAMO   
       ,SUBSTR(FTC_LINEA,80,5) FNC_CVE_PAGADURIA   
       ,SUBSTR(FTC_LINEA,283,7) FNN_SUELDO_BASICO_COTIZ_RCV   
       ,SUBSTR(FTC_LINEA,280,1) FNC_ID_TRABAJADOR_BONO
       ,SUBSTR(FTC_LINEA,281,2) FCN_ID_TIPO_APO
FROM   CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO
WHERE  SUBSTR(FTC_LINEA,1,2) = 02 
AND    FTN_ID_ARCHIVO = #sr_id_archivo#