 With MAPEO_PRE_DISP AS(

--SUBCTA_RETIRO
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_RETIRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    639 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_RETIRO AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    20 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#

UNION ALL
--RECARG RETIRO
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_ACT_RECARG_RETIRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    640 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_RETIRO AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    21 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#

UNION ALL
--CESANTIA VEJEZ
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_CESANTIA_VEJEZ / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    643 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_CESANTIA_VEJEZ AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    22 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#

UNION ALL

--REG CESANTIA VEJEZ
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMP_ACT_REG_CESTIA_VEJEZ / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    644 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_CESANTIA_VEJEZ AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    23 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#

UNION ALL

--APORT VOLUNT
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_APORT_VOLUN / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'AVO' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    650 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_APORT_VOLUN AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    24 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#


UNION ALL

--APORT COMPL RETIRO
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTN_IMPORTE_APORT_COMPL_RETIRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'COM' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    652 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_APORT_COMPL_RETIRO AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    25 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#

UNION ALL

--APORT PATRONAL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_APORT_PATRONAL / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    647 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    26 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#


UNION ALL

--INTERES VIVIENDA
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FTF_MONTO_PESOS,
    FTC_APLIC_INTERES_VIVIENDA / 1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    696 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    35 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#

UNION ALL

--IMPUESTO INTERES VIVIENDA REMANENTE
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORT_REMAN_VIV / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    648 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    37 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#

UNION ALL

--IMPUESTO INTERES VIVIENDA PAGO EXT
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_INTER_PAGOS_EXT_VIVIENDA / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    649 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    39 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#


UNION ALL

--APORT LARGO PLAZO
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMP_APORT_LARGO_PLAZO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'AVO' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    654 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_APORT_LARGO_PLAZO AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    41 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#


UNION ALL

-- RETIRO APORT VOLUN
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_APORT_PATRONAL / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    231 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    26 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#
WHERE FTC_ID_VIV_GARANTIA = 1

UNION ALL

-- IMP INT REM VIV AIVS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FTF_MONTO_PESOS,
    FTC_APLIC_INT_VIV_REMANENTE / 1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    697 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    38 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#

UNION ALL

-- IMP INT PAGO EXT VIV AIVS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FTF_MONTO_PESOS,
    FTC_APLIC_INTER_VIV_PAG_EXT / 1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    698 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP AS FTC_CURP,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    40 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    FTC_RFC,
    FCN_REG_PATRONAL_IMSS
FROM #DELTA_TABLA_NAME1#

 )

SELECT 
FTC_FOLIO
,FTN_ID_ARCHIVO
,FTN_NO_LINEA
,FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA
,FCN_ID_PROCESO
,FCN_ID_SUBPROCESO
,FTF_MONTO_PESOS
,FTF_MONTO_ACCIONES
,FTC_TABLA_NCI_MOV
,FNN_ID_VIV_GARANTIA
,FFN_ID_CONCEPTO_MOV
,FTN_NSS
,FTC_CURP
,FCN_ID_CAT_SUBCTA
,FTN_TIPO_REG
,FTN_ID_MONTO
,to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEC_CRE
,"DATABRICKS" AS FTC_USU_CRE
,FLN_ID_LIB_APORT
,FTC_NOMBRE
,FTC_RFC
,FCN_REG_PATRONAL_IMSS
FROM MAPEO_PRE_DISP C