 With MAPEO_PRE_DISP AS(

SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_RETIRO_SAR AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_RETIRO_SAR / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'SAR' AS FTC_TABLA_NCI_MOV,
    684 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    35 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#

UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_RETIRO_ISSSTE AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_RETIRO_ISSSTE / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    686 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    36 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
 FROM #DELTA_TABLA_NAME1#
   
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_CV_PATRON AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_CV_PATRON / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    694 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    37 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_CV_TRAB AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_CV_TRAB / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    692 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    38 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_EXT_SAR AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_EXT_RETIRO_SAR / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'SAR' AS FTC_TABLA_NCI_MOV,
    685 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    39 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_EXT_RETIRO AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_EXT_RETIRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    687 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    40 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_EXT_CV_PATRON AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_EXT_CV_PATRON / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    695 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    41 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_EXT_CV_TRAB AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_EXT_CV_TRAB / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    693 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    42 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_AHORRO_TRAB AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_AHORRO_TRAB / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'COM' AS FTC_TABLA_NCI_MOV,
    688 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    43 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_AHORRO_DEP AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_AHORRO_DEP / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'COM' AS FTC_TABLA_NCI_MOV,
    690 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    44 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_EXT_AHORRO AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_EXT_AHORRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'COM' AS FTC_TABLA_NCI_MOV,
    689 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    45 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_INTER_EXT_DEP AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_EXT_AHORRO_DEP / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'COM' AS FTC_TABLA_NCI_MOV,
    691 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    46 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_TOT_INTERES / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    47 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_SAR_23 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    23 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_RET_24 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    24 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_CV_25 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    25 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_CV_26 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    26 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_RET_SAR_27 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    27 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_RET_EXT_28 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    28 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_CV_PAT_29 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    29 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_CV_TRAB_30 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    30 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_AHO_TRAB_31 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    31 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_AHO_DEP_32 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    32 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_AHO_EXT_33 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    33 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    
UNION ALL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_AHO_DEP_34 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'TOT' AS FTC_TABLA_NCI_MOV,
    0 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    34 AS FTN_ID_MONTO,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE,
    null AS FNN_ID_VIV_GARANTIA
    
FROM #DELTA_TABLA_NAME1#
    

 )

  SELECT 
FTC_FOLIO
,FTN_ID_ARCHIVO
,FTN_NO_LINEA
,FNN_ID_REFERENCIA
,FCN_ID_PROCESO
,FCN_ID_SUBPROCESO
,FCN_ID_CAT_SUBCTA
,FTF_MONTO_PESOS
,FTF_MONTO_ACCIONES
,FTC_TABLA_NCI_MOV
,FFN_ID_CONCEPTO_MOV
,FTN_NSS
,FTC_CURP
,FTN_ID_MONTO
,FTN_TIPO_REG
,FLN_ID_LIB_APORT
,FTC_NOMBRE
,FNN_ID_VIV_GARANTIA/*los campos de abajo no vienen en datastage pero no se si borrarlos*/
,to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEC_CRE
,"DATABRICKS" AS FTC_USU_CRE
,null AS FTC_RFC
,null AS FCN_REG_PATRONAL_IMSS
FROM MAPEO_PRE_DISP C
