-- Query para insertar en CLIENTE_SUA

SELECT 
T5.FNN_ID_REFERENCIA,
T5.FTC_FOLIO,
T5.FTN_NSS,
T5.FTC_RFC,
T5.FTC_CURP,
T5.FTC_NOMBRE,
T5.FNC_PERIODO_PAGO_PATRON,
T5.FND_FECHA_PAGO,
T5.FND_FECHA_VALOR_IMSS_ACV_VIV,
T5.FNN_ULTIMO_SALARIO_INT_PER,
T5.FNC_FOLIO_PAGO_SUA,
T5.FNC_REG_PATRONAL_IMSS,
T5.FNC_RFC_PATRON,
T5.FNN_DIAS_COTZDOS_BIMESTRE,
T5.FNN_DIAS_INCAP_BIMESTRE,
T5.FNN_DIAS_AUSENT_BIMESTRE,
T5.FNN_ID_VIV_GARANTIA,
T5.FNN_APLIC_INT_VIVIENDA,
T5.FNC_MOTIVO_LIBCION_APORT,
T5.FND_FECHA_PAGO_CUOTA_GUB,
T5.FND_FECHA_VALOR_RCV,
T5.FNN_CVE_ENT_RECEP_PAGO,
T5.FNN_NSS_ISSSTE,
T5.FNC_DEPEND_CTRO_PAGO,
T5.FNN_CTRO_PAGO_SAR,
T5.FNN_CVE_RAMO,
T5.FNC_CVE_PAGADURIA,
T5.FNN_SUELDO_BASICO_COTIZ_RCV,
CASE 
        WHEN FNC_ID_TRABAJADOR_BONO = '' 
        THEN '\u0000'
        ELSE FNC_ID_TRABAJADOR_BONO
    END AS FNC_ID_TRABAJADOR_BONO,
--T5.FNC_ID_TRABAJADOR_BONO,
T5.FND_FEH_CRE,
T5.FNC_USU_CRE,
T5.FTN_INTERESES_VIV92,
T5.FTN_INTERESES_VIV08,
T5.FCN_ID_PROCESO,
T5.FCN_ID_SUBPROCESO,
T5.FNC_TIPREG,
T2.FND_FECTRA,
T2.FNN_SECLOT,
T5.FNN_ID_ARCHIVO,
T5.FTN_CONS_REG_LOTE,
T5.FCN_ID_TIPO_APO
from  #DELTA_TABLA_NAME5# T5 
INNER JOIN #DELTA_TABLA_NAME2# T2 on T2.FNN_ID_ARCHIVO = T5.FNN_ID_ARCHIVO
