 With MAPEO_PRE_DISP AS(

--CUOTA ISSSTE
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_CUOTA_SOCIAL AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_CUOTA_SOCIAL / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'GOB' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    659 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE_ISSSTE FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
WHERE #sr_proceso# = "7" And #sr_subproceso# = "210"

UNION ALL
--CUOTA ISSSTE
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_CUOTA_SOCIAL_IMSS AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_CUOTA_SOCIAL_IMSS / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'GOB' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    656 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS_IMSS AS FTN_NSS,
    FTC_CURP_IMSS AS FTC_CURP,
    FLN_ID_LIB_APORT_IMSS FLN_ID_LIB_APORT,
    FTC_NOMBRE_IMSS FTC_NOMBRE 
FROM #DELTA_TABLA_NAME1#
WHERE #sr_proceso# = "7" And #sr_subproceso# = "439"


UNION ALL
--ESTATAL IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_CUOTA_ESTATAL_IMSS AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_ESTATAL_IMSS / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'GOB' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    657 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS_IMSS AS FTN_NSS,
    FTC_CURP_IMSS AS FTC_CURP,
    FLN_ID_LIB_APORT_IMSS FLN_ID_LIB_APORT,
    FTC_NOMBRE_IMSS FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
WHERE #sr_proceso# = "7" And #sr_subproceso# = "439"

UNION ALL

--ESPECIAL IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_CUOTA_ESPECIAL_IMSS AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_ESPECIAL_IMSS / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'GOB' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    658 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS_IMSS AS FTN_NSS,
    FTC_CURP_IMSS AS FTC_CURP,
    FLN_ID_LIB_APORT_IMSS FLN_ID_LIB_APORT,
    FTC_NOMBRE_IMSS FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
WHERE #sr_proceso# = "7" And #sr_subproceso# = "439"

 )

SELECT 
FTC_FOLIO
,FTN_ID_ARCHIVO
,FTN_NO_LINEA
,FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA
,FCN_ID_PROCESO
,FCN_ID_SUBPROCESO
,FCN_ID_CAT_SUBCTA
,FTF_MONTO_PESOS
,FTF_MONTO_ACCIONES
,FTC_TABLA_NCI_MOV
,FNN_ID_VIV_GARANTIA
,FFN_ID_CONCEPTO_MOV
,FTN_NSS
,FTC_CURP
,to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEC_CRE
,"DATABRICKS" AS FTC_USU_CRE
,FLN_ID_LIB_APORT
,FTC_NOMBRE
,NULL AS FTN_TIPO_REG
,NULL AS FTN_ID_MONTO
,NULL AS FTC_RFC
,NULL AS FCN_REG_PATRONAL_IMSS
FROM MAPEO_PRE_DISP C