SELECT
          TO_DATE(SUBSTR(FTC_LINEA,17,8),'YYYYMMDD') FND_FECTRA
         ,FTN_ID_ARCHIVO AS FNN_ID_ARCHIVO
         ,SUBSTR(FTC_LINEA,25,3) FNN_SECLOT
FROM  CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO
WHERE 
SUBSTR(FTC_LINEA,1,2) = '01'
AND   FTN_ID_ARCHIVO = #sr_id_archivo#