SELECT SUBSTR(FTC_LINEA,13,11) FTC_NSS
       ,FTN_ID_ARCHIVO
       ,SUBSTR (FTC_LINEA,181,7) FTC_INTER_RETIRO
       ,'151' FTC_SUBCTA_INTER_RETIRO --'641'
       ,SUBSTR (FTC_LINEA,188,7) FTC_INTER_ACT_RECARGOS
       ,'151' FTC_SUBCTA_INTER_ACT_RECARGOS --,'642
       ,SUBSTR (FTC_LINEA,195,7) FTC_INTER_CENSATIA_VEJEZ
       ,'152' FTC_SUBCTA_CENSATIA_VEJEZ --,'645'
       ,SUBSTR (FTC_LINEA,202,7) FTC_INTER_ACT_RECARGOS_CYV
       ,'152' FTC_SUBCTA_ACT_RECARGOS_CYV -- '646
       ,SUBSTR (FTC_LINEA,209,7) FTC_INTER_VOLUNT
       ,'169' FTC_SUBCTA_VOLUNT  --651
       ,SUBSTR (FTC_LINEA,216,7) FTC_INTER_APORT_COMPLE_RETIRO
       ,'171' FTC_SUBCTA_APORT_COMPLE_RETIRO --653
       ,SUBSTR (FTC_LINEA,288,7) FTC_INTER_APORT_LARGO_PLAZO
       ,'173' FTC_SUBCTA_APORT_LARGO_PLAZO --655
       ,SUBSTR (FTC_LINEA,280,1) FTC_ID_VIV_GARANTIA
       ,SUBSTR (FTC_LINEA,005,8) FTC_ID_REFERENCIA
       ,FTN_NO_LINEA
       ,case when length(trim(SUBSTR (FTC_LINEA,37,18)))<>18 then null else SUBSTR (FTC_LINEA,37,18) end FTC_CURP
        ,SUBSTR (FTC_LINEA,1,2) FTN_TIPO_REG       
       ,269 FLN_ID_LIB_APORT
      ,TRIM(SUBSTR(FTC_LINEA,55,50)) FTC_NOMBRE
       ,TRIM(SUBSTR(FTC_LINEA,24,13)) FTC_RFC
       ,TRIM(SUBSTR(FTC_LINEA,148,11)) FCN_REG_PATRONAL_IMSS
        -- Solo para Tabla Cliente SUA   
       ,SUBSTR(FTC_LINEA,105,6) FNC_PERIODO_PAGO_PATRON   
       ,SUBSTR(FTC_LINEA,111,8) FND_FECHA_PAGO   
       ,SUBSTR(FTC_LINEA,127,8) FND_FECHA_VALOR_IMSS_ACV
       ,SUBSTR(FTC_LINEA,135,7) FNN_ULTIMO_SALARIO_INT_PER
       ,SUBSTR(FTC_LINEA,142,6) FNC_FOLIO_PAGO_SUA	   
       ,SUBSTR(FTC_LINEA,159,13) FNC_RFC_PATRON   
       ,SUBSTR(FTC_LINEA,175,2) FNN_DIAS_COTZDOS_BIM   
       ,SUBSTR(FTC_LINEA,177,2) FNN_DIAS_INCAP_BIMESTRE      
       ,SUBSTR(FTC_LINEA,179,2) FNN_DIAS_AUSENT_BIMESTRE  
       ,SUBSTR(FTC_LINEA,281,15) FNN_APLIC_INT_VIVIENDA   
       ,SUBSTR(FTC_LINEA,365,2) FNC_MOTIVO_LIBCION_APORT      
       ,SUBSTR(FTC_LINEA,272,8) FND_FECHA_PAGO_CUOTA_GUB
       ,SUBSTR(FTC_LINEA,119,8) FND_FECHA_VALOR_RCV
       ,SUBSTR(FTC_LINEA,172,3) FNN_CVE_ENT_RECEP_PAGO
FROM   CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO
WHERE  SUBSTR(FTC_LINEA,1,2) = 03
AND FTN_ID_ARCHIVO = #sr_id_archivo#