-- Query para insertar en PRE_DISPERSION
SELECT 
T7.FTC_FOLIO
,T7.FTN_ID_ARCHIVO
,T7.FTN_NO_LINEA
,T7.FNN_ID_REFERENCIA
,T7.FCN_ID_PROCESO
,T7.FCN_ID_SUBPROCESO
,T7.FTF_MONTO_PESOS
,T7.FTF_MONTO_ACCIONES
,T7.FTC_TABLA_NCI_MOV
,T7.FFN_ID_CONCEPTO_MOV
,T7.FTN_NSS
,T7.FTC_CURP
,T7.FTN_ID_MONTO --
,T7.FTN_TIPO_REG --
,T7.FLN_ID_LIB_APORT
,T7.FTC_NOMBRE
,T7.FNN_ID_VIV_GARANTIA
,T7.FTC_RFC --
,T7.FCN_REG_PATRONAL_IMSS --
,T7.FCN_ID_TIPO_SUBCTA
FROM  #DELTA_TABLA_NAME7# T7 
WHERE FTC_TABLA_NCI_MOV = 'TOT'