With MAPEO_PRE_DISP AS(
 
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_SAR / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'SAR' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_SAR AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    26 AS FTN_ID_MONTO,
    FTC_SUBCTA_SAR AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_RETIRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_RETIRO AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    27 AS FTN_ID_MONTO,
    FTC_SUBCTA_RETIRO AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_CV_PATRON / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_CV_PATRON AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    28 AS FTN_ID_MONTO,
    FTC_SUBCTA_CV_PATRON AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_CV_TRAB / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_CV_TRAB AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    29 AS FTN_ID_MONTO,
    FTC_SUBCTA_CV_TRAB AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_INTER_EXT_SAR / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'SAR' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_X_SAR AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    30 AS FTN_ID_MONTO,
    FTC_SUBCTA_INTER_EXT_SAR AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_INTER_EXT_RETIRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_INT_X_RET AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    31 AS FTN_ID_MONTO,
    FTC_SUBCTA_INTER_EXT_RETIRO AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_INTER_EXT_PATRON / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_INT_X_PATRON AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    32 AS FTN_ID_MONTO,
    FTC_SUBCTA_INTER_EXT_PATRON AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_INTER_EXT_TRAB / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_INT_X_TRAB AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    33 AS FTN_ID_MONTO,
    FTC_SUBCTA_INTER_EXT_TRAB AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_VIV_92 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_IMP_SUB_VIV_92 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    34 AS FTN_ID_MONTO,
    FTC_SUBCTA_VIV_92 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_VIV_2008 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_IMPORTE_VIV_2008 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    35 AS FTN_ID_MONTO,
    FTC_SUBCTA_VIV_2008 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_INTER_EXT_VIV_92 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_EXT_VIV_92 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    36 AS FTN_ID_MONTO,
    FTC_SUBCTA_EXT_VIV_92 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_INTER_EXT_VIV_2008 / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_EXT_VIV_2008 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    37 AS FTN_ID_MONTO,
    FTC_SUBCTA_EXT_VIV_2008 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FTF_MONTO_PESOS,
    FTC_IMPORTE_AIVS_VIV_92 / 1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_AIVS_VIV_92 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    39 AS FTN_ID_MONTO,
    FTC_SUBCTA_AIVS_VIV_92 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FTF_MONTO_PESOS,
    FTC_IMPORTE_AIVS_VIV_2008 / 1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_AIVS_VIV_2008 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    40 AS FTN_ID_MONTO,
    FTC_SUBCTA_AIVS_VIV_2008 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FTF_MONTO_PESOS,
    FTC_IMPORTE_EXT_AIVS_VIV_92 / 1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_X_AIVS_VIV_92 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    41 AS FTN_ID_MONTO,
    FTC_SUBCTA_EXT_AIVS_VIV_92 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FTF_MONTO_PESOS,
    FTC_IMPORTE_EXT_AIVS_VIV_2008 / 1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_X_AIVS_VIV_2008 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    42 AS FTN_ID_MONTO,
    FTC_SUBCTA_EXT_AIVS_VIV_2008 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_APOVOL/100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'AVO' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_APOVOL AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    45 AS FTN_ID_MONTO,
    FTC_SUBCTA_APOVOL AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_COMPLE_RET/100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'COM' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_ACR AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    46 AS FTN_ID_MONTO,
    FTC_SUBCTA_COMPLE_RET AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_LARGO_PLAZO/100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'AVO' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_LP AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    47 AS FTN_ID_MONTO,
    FTC_SUBCTA_LARGO_PLAZO AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_AH_SOLID_TRAB/100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'COM' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_AH_SOLID_TRAB AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    48 AS FTN_ID_MONTO,
    FTC_SUBCTA_SOLID_TRAB AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_IMPORTE_AH_SOLID_DEPEN/100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'COM' AS FCC_TABLA_NCI_MOV,
    null AS FNN_ID_VIV_GARANTIA,
    FFN_MOV_AH_SOLID_DEPEN AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    49 AS FTN_ID_MONTO,
    FTC_SUBCTA_SOLID_DEPEN AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FTF_MONTO_PESOS,
    FTC_IMPORTE_AIVS_VIV_92/1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    637 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    null AS FTN_ID_MONTO,
    FTC_SUBCTA_AIVS_VIV_92 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
WHERE FTC_ID_VIV_GARANTIA = 1
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FTF_MONTO_PESOS,
    FTC_IMPORTE_AIVS_VIV_2008/1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    638 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    null AS FTN_ID_MONTO,
    FTC_SUBCTA_AIVS_VIV_2008 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
WHERE FTC_ID_VIV_GARANTIA = 1
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FTF_MONTO_PESOS,
    FTC_IMPORTE_EXT_AIVS_VIV_92/1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    1002 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    null AS FTN_ID_MONTO,
    FTC_SUBCTA_EXT_AIVS_VIV_92 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
WHERE FTC_ID_VIV_GARANTIA = 1
 
UNION ALL
SELECT
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    0 AS FTF_MONTO_PESOS,
    FTC_IMPORTE_EXT_AIVS_VIV_2008/1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FCC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    1003 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    null AS FTN_ID_MONTO,
    FTC_SUBCTA_AIVS_VIV_2008 AS FCN_ID_CAT_SUBCTA,
    FTN_TIPO_REG,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
WHERE FTC_ID_VIV_GARANTIA = 1
 
 
 )
 
  SELECT
FTC_FOLIO
,FTN_ID_ARCHIVO
,FTN_NO_LINEA
,FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA
,FCN_ID_PROCESO
,FCN_ID_SUBPROCESO
,FCN_ID_CAT_SUBCTA
,FTF_MONTO_PESOS
,FTF_MONTO_ACCIONES
,FCC_TABLA_NCI_MOV AS FTC_TABLA_NCI_MOV
,FNN_ID_VIV_GARANTIA
,FFN_ID_CONCEPTO_MOV
,FTN_NSS
,FTC_CURP
,to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEC_CRE
,"DATABRICKS" AS FTC_USU_CRE
,FLN_ID_LIB_APORT
,FTC_NOMBRE
,FTN_TIPO_REG
,FTN_ID_MONTO
,null AS FTC_RFC
,null AS FCN_REG_PATRONAL_IMSS
FROM MAPEO_PRE_DISP C