SELECT /*+ PARALLEL (8)*/ 
          SUBSTR(FTC_LINEA,107,11) FTC_NSS
        ,SUBSTR(FTC_LINEA,299,12) FTC_IMPORTE_SAR
        ,'157' FTC_SUBCTA_SAR
        ,660 FFN_MOV_SAR        
        ,SUBSTR(FTC_LINEA,311,12) FTC_IMPORTE_RETIRO
        ,'158' FTC_SUBCTA_RETIRO
        ,'662' FFN_MOV_RETIRO                
        ,SUBSTR(FTC_LINEA,323,12) FTC_IMPORTE_CV_PATRON
        ,'163' FTC_SUBCTA_CV_PATRON
        ,'668' FFN_MOV_CV_PATRON
        ,SUBSTR (FTC_LINEA,335,12) FTC_IMPORTE_CV_TRAB
        ,'162' FTC_SUBCTA_CV_TRAB
        ,'666' FFN_MOV_CV_TRAB
        ,SUBSTR (FTC_LINEA,347,12) FTC_INTER_EXT_SAR
        ,'157' FTC_SUBCTA_INTER_EXT_SAR
        ,'661' FFN_MOV_X_SAR
        ,SUBSTR (FTC_LINEA,359,12) FTC_INTER_EXT_RETIRO
        ,'158' FTC_SUBCTA_INTER_EXT_RETIRO
        ,'663' FFN_MOV_INT_X_RET
        ,SUBSTR (FTC_LINEA,371,12) FTC_INTER_EXT_PATRON
        ,'163' FTC_SUBCTA_INTER_EXT_PATRON
        ,'669' FFN_MOV_INT_X_PATRON
        ,SUBSTR (FTC_LINEA,383,12) FTC_INTER_EXT_TRAB
        ,'162' FTC_SUBCTA_INTER_EXT_TRAB
        ,'667' FFN_MOV_INT_X_TRAB
        ,SUBSTR (FTC_LINEA,395,12) FTC_IMPORTE_VIV_92
        ,'167' FTC_SUBCTA_VIV_92
        ,'670' FFN_MOV_IMP_SUB_VIV_92 
        ,SUBSTR (FTC_LINEA,407,12) FTC_IMPORTE_VIV_2008
        ,'168' FTC_SUBCTA_VIV_2008
        ,'672' FFN_MOV_IMPORTE_VIV_2008
        ,SUBSTR (FTC_LINEA,419,12) FTC_INTER_EXT_VIV_92
        ,'167' FTC_SUBCTA_EXT_VIV_92
        ,'671' FFN_MOV_EXT_VIV_92
        ,SUBSTR (FTC_LINEA,431,12) FTC_INTER_EXT_VIV_2008
        ,'168' FTC_SUBCTA_EXT_VIV_2008
        ,'673' FFN_MOV_EXT_VIV_2008
        /*******ACCIONES******/
        ,SUBSTR (FTC_LINEA,444,15) FTC_IMPORTE_AIVS_VIV_92
        ,'167' FTC_SUBCTA_AIVS_VIV_92
        ,'699' FFN_MOV_AIVS_VIV_92
        ,SUBSTR (FTC_LINEA,459,15) FTC_IMPORTE_AIVS_VIV_2008
        ,'168' FTC_SUBCTA_AIVS_VIV_2008
        ,'701' FFN_MOV_AIVS_VIV_2008
        ,SUBSTR (FTC_LINEA,474,15) FTC_IMPORTE_EXT_AIVS_VIV_92
        ,'167' FTC_SUBCTA_EXT_AIVS_VIV_92
        ,'700' FFN_MOV_X_AIVS_VIV_92
        ,SUBSTR (FTC_LINEA,489,15) FTC_IMPORTE_EXT_AIVS_VIV_2008
        ,'168' FTC_SUBCTA_EXT_AIVS_VIV_2008
        ,'702' FFN_MOV_X_AIVS_VIV_2008                        
        /*******ACCIONES******/    
        ,SUBSTR (FTC_LINEA,524,12) FTC_IMPORTE_CUOTA_SOCIAL
        ,'159' FTC_SUBCTA_CUOTA_SOCIAL 
        ,'659' FFN_MOV_CUO_SOCIAL                   
        ,SUBSTR (FTC_LINEA,536,7) FTC_IMPORTE_APOVOL
        ,'169' FTC_SUBCTA_APOVOL
        ,'674' FFN_MOV_APOVOL
        ,SUBSTR (FTC_LINEA,543,7) FTC_IMPORTE_COMPLE_RET
        ,'171' FTC_SUBCTA_COMPLE_RET
        ,'675' FFN_MOV_ACR
        ,SUBSTR (FTC_LINEA,550,7) FTC_IMPORTE_LARGO_PLAZO
        ,'173' FTC_SUBCTA_LARGO_PLAZO
        ,'676' FFN_MOV_LP
        ,SUBSTR (FTC_LINEA,557,7) FTC_IMPORTE_AH_SOLID_TRAB
        ,'160' FTC_SUBCTA_SOLID_TRAB
        ,'664' FFN_MOV_AH_SOLID_TRAB
        ,SUBSTR (FTC_LINEA,564,7) FTC_IMPORTE_AH_SOLID_DEPEN
        ,'161' FTC_SUBCTA_SOLID_DEPEN
        ,'665' FFN_MOV_AH_SOLID_DEPEN
        ,SUBSTR (FTC_LINEA,443,1) FTC_ID_VIV_GARANTIA
        ,SUBSTR (FTC_LINEA,005,8) FTC_ID_REFERENCIA
        ,FTN_NO_LINEA 
        ,SUBSTR (FTC_LINEA,142,18) FTC_CURP
        ,FTN_ID_ARCHIVO
        ,SUBSTR (FTC_LINEA,1,2) FTN_TIPO_REG
       ,TRIM(SUBSTR(FTC_LINEA,160,40)) || ' ' || TRIM(SUBSTR(FTC_LINEA,200,40)) || ' ' || TRIM(SUBSTR(FTC_LINEA,240,40)) FTC_NOMBRE
 ,decode(SUBSTR (FTC_LINEA,281,2), '01', 268,'02', 269) FLN_ID_LIB_APORT
 -- Solo para Cliente SUA
       ,SUBSTR(FTC_LINEA,129,13) FTC_RFC   
       ,SUBSTR(FTC_LINEA,85,6) FNC_PERIODO_PAGO_PATRON   
       ,SUBSTR(FTC_LINEA,91,8) FND_FECHA_PAGO   
       ,SUBSTR(FTC_LINEA,99,8) FND_FECHA_VALOR_IMSS_ACV      
       ,SUBSTR(FTC_LINEA,16,12) FNC_RFC_PATRON   
       ,SUBSTR(FTC_LINEA,290,3) FNN_DIAS_COTZDOS_BIM   
       ,SUBSTR(FTC_LINEA,293,3) FNN_DIAS_INCAP_BIMESTRE      
       ,SUBSTR(FTC_LINEA,296,3) FNN_DIAS_AUSENT_BIMESTRE   
       ,SUBSTR(FTC_LINEA,99,8) FND_FECHA_VALOR_RCV
       ,SUBSTR(FTC_LINEA,13,3) FNN_CVE_ENT_RECEP_PAGO
       ,SUBSTR(FTC_LINEA,118,11) FNN_NSS_ISSSTE
       ,SUBSTR(FTC_LINEA,28,40) FNC_DEPEND_CTRO_PAGO
       ,SUBSTR(FTC_LINEA,68,7) FNN_CTRO_PAGO_SAR
       ,SUBSTR(FTC_LINEA,75,5) FNN_CVE_RAMO   
       ,SUBSTR(FTC_LINEA,80,5) FNC_CVE_PAGADURIA   
       ,SUBSTR(FTC_LINEA,283,7) FNN_SUELDO_BASICO_COTIZ_RCV   
       ,SUBSTR(FTC_LINEA,280,1) FNC_ID_TRABAJADOR_BONO
       ,SUBSTR(FTC_LINEA,444,15) FTN_INTERESES_VIV92
       ,SUBSTR(FTC_LINEA,459,15) FTN_INTERESES_VIV08
       ,SUBSTR(FTC_LINEA,281,2) FCN_ID_TIPO_APO
FROM   CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO
WHERE  SUBSTR(FTC_LINEA,1,2) = 02
AND    FTN_ID_ARCHIVO = #sr_id_archivo#