 With MAPEO_PRE_DISP AS(

--RET
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_RETIRO AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_RETIRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    221 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    20 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--RECARGOS RETIRO
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_RETIRO AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_ACT_RECARG_RETIRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    222 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    21 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--CESANTIA Y VEJEZ IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_CESANTIA_VEJEZ AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_CESANTIA_VEJEZ / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    223 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    22 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--RECARGOS CESANTIA Y VEJEZ IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_CESANTIA_VEJEZ AS FCN_ID_CAT_SUBCTA,
    FTC_IMP_ACT_REG_CESTIA_VEJEZ / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'RCV' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    224 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    23 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--APORTACIONES VOLUNTARIAS IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_APORT_VOLUN AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_APORT_VOLUN / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'AVO' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    228 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    24 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--APORTACIONES COMPLEMENTARIAS RETIRO IMSS
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_APORT_COMPL_RETIRO AS FCN_ID_CAT_SUBCTA,
    FTN_IMPORTE_APORT_COMPL_RETIRO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'COM' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    229 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    25 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--APORT PATRONAL
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_APORT_PATRONAL / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    225 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    26 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--INTERESES VIVIENDA
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    0 AS FTF_MONTO_PESOS,
    FTC_APLIC_INTERES_VIVIENDA / 1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    270 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    35 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#


UNION ALL
--INT VIV REMANENTE
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORT_REMAN_VIV / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    NULL AS FNN_ID_VIV_GARANTIA,
    226 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    37 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
--INTER VIV PAG EXT
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    FTC_INTER_PAGOS_EXT_VIVIENDA / 100 AS FTF_MONTO_PESOS,
    FTC_APLIC_INTER_VIV_PAG_EXT / 1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    NULL AS FNN_ID_VIV_GARANTIA,
    227 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    39 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#


UNION ALL
--APORT LARGO PLAZO
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_APORT_LARGO_PLAZO AS FCN_ID_CAT_SUBCTA,
    FTC_IMP_APORT_LARGO_PLAZO / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'AVO' AS FTC_TABLA_NCI_MOV,
    0 AS FNN_ID_VIV_GARANTIA,
    230 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    41 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#


UNION ALL
--SUBS APORT PATRO
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    FTC_IMPORTE_APORT_PATRONAL / 100 AS FTF_MONTO_PESOS,
    0 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    FTC_ID_VIV_GARANTIA AS FNN_ID_VIV_GARANTIA,
    231 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    26 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#
WHERE FTC_ID_VIV_GARANTIA = 1

UNION ALL
-- INT REM VIV AIVS 
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    0 AS FTF_MONTO_PESOS,
    FTC_APLIC_INT_VIV_REMANENTE/1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    NULL AS FNN_ID_VIV_GARANTIA,
    271 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    38 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

UNION ALL
-- INT REM VIV AIVS 
SELECT 
    #sr_folio# AS FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NO_LINEA,
    FTC_ID_REFERENCIA,
    #sr_proceso# AS FCN_ID_PROCESO,
    #sr_subproceso# AS FCN_ID_SUBPROCESO,
    FTC_SUBCTA_VIVIENDA AS FCN_ID_CAT_SUBCTA,
    0 AS FTF_MONTO_PESOS,
    FTC_APLIC_INTER_VIV_PAG_EXT/1000000 AS FTF_MONTO_ACCIONES,
    'VIV' AS FTC_TABLA_NCI_MOV,
    NULL AS FNN_ID_VIV_GARANTIA,
    272 AS FFN_ID_CONCEPTO_MOV,
    FTC_NSS AS FTN_NSS,
    FTC_CURP,
    40 AS FTN_ID_MONTO,
    FLN_ID_LIB_APORT,
    FTC_NOMBRE
FROM #DELTA_TABLA_NAME1#

 )

  SELECT 
FTC_FOLIO
,FTN_ID_ARCHIVO
,FTN_NO_LINEA
,FTC_ID_REFERENCIA AS FNN_ID_REFERENCIA
,FCN_ID_PROCESO
,FCN_ID_SUBPROCESO
,FCN_ID_CAT_SUBCTA
,FTF_MONTO_PESOS
,FTF_MONTO_ACCIONES
,FTC_TABLA_NCI_MOV
,FNN_ID_VIV_GARANTIA
,FFN_ID_CONCEPTO_MOV
,FTN_NSS
,FTC_CURP
,to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEC_CRE
,"DATABRICKS" AS FTC_USU_CRE
,FLN_ID_LIB_APORT
,FTC_NOMBRE
,NULL AS FTN_TIPO_REG
,FTN_ID_MONTO
,NULL AS FTC_RFC
,NULL AS FCN_REG_PATRONAL_IMSS
FROM MAPEO_PRE_DISP C