SELECT SUBC.FCN_ID_CAT_SUBCTA,
       SUBC.FCN_ID_GRUPO,
       SUBC.FCN_ID_TIPO_SUBCTA
FROM   TCCRXGRAL_TIPO_SUBCTA SUBC
JOIN 
     (
      SELECT FCN_ID_CAT_CATALOGO REGIMEN
      FROM   TCCRXGRAL_TIPO_CAT TC
      JOIN   TCCRXGRAL_CAT_CATALOGO CAT ON TC.FCN_ID_TIPO_CAT = CAT.FCN_ID_TIPO_CAT
      WHERE  TC.FCN_ID_TIPO_CAT = 21 
      AND    TC.FCB_VIGENCIA = 1 
      AND    CAT.FCB_VIGENCIA = 1
      AND    CAT.FCN_ID_CAT_CATALOGO in (138,139,140)
     ) CAT
ON SUBC.FCN_ID_REGIMEN = CAT.REGIMEN