-- Query para insertar en AEIM
WITH TABLE_AIEM AS (
  SELECT
    #sr_folio# AS FTC_FOLIO,
    FTC_NOMBRE_COMPLETO_ARCH,
    FTN_NSS_ARCH,
    CASE WHEN FTC_NOMBRES IS NULL THEN get(split(trim(FTC_NOMBRE_COMPLETO_ARCH), ' '), 2) ELSE trim(FTC_NOMBRES) END AS FTC_NOMBRE_ARCH,
    CASE WHEN FTC_AP_PATERNO IS NULL THEN get(split(trim(FTC_NOMBRE_COMPLETO_ARCH), ' '), 0) ELSE trim(FTC_AP_PATERNO) END AS FTC_AP_PATERNO_ARCH,
    CASE WHEN FTC_AP_MATERNO IS NULL THEN get(split(trim(FTC_NOMBRE_COMPLETO_ARCH), ' '), 1) ELSE trim(FTC_AP_MATERNO) END AS FTC_AP_MATERNO_ARCH,
    FTC_RFC_ARCH,
    FNC_REG_PATRONAL_IMSS,
    560 AS FTN_ESTATUS_REG,
    to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_ULTIMO_USO,
    821 AS FTN_MOTIVO,
    FTC_CLAVE_ENT_RECEP,
    FTN_NUM_CTA_INVDUAL,
    ROW_NUMBER() OVER (PARTITION BY FTC_NOMBRE_COMPLETO_ARCH, FTN_NSS_ARCH, FTC_RFC_ARCH, FNC_REG_PATRONAL_IMSS ORDER BY FTC_CLAVE_ENT_RECEP DESC) AS rn
  FROM #DELTA_TABLA_NAME4# T4
)
SELECT 
    FTC_FOLIO,
    FTC_NOMBRE_COMPLETO_ARCH,
    FTN_NSS_ARCH,
    FTC_NOMBRE_ARCH,
    FTC_AP_PATERNO_ARCH,
    FTC_AP_MATERNO_ARCH,
    FTC_RFC_ARCH,
    FNC_REG_PATRONAL_IMSS,
    FTN_ESTATUS_REG,
    FTD_FEH_ULTIMO_USO,
    FTN_MOTIVO,
    FTC_CLAVE_ENT_RECEP,
    FTN_NUM_CTA_INVDUAL
 FROM TABLE_AIEM WHERE rn = 1