-- Query para insertar en PRE_DISPERSION
SELECT 
T4.FTC_FOLIO
,T4.FTN_ID_ARCHIVO
,T4.FTN_NO_LINEA
,T4.FNN_ID_REFERENCIA
,T4.FCN_ID_PROCESO
,T4.FCN_ID_SUBPROCESO
,T4.FTF_MONTO_PESOS
,T4.FTF_MONTO_ACCIONES
,T4.FTC_TABLA_NCI_MOV
,T4.FFN_ID_CONCEPTO_MOV
,T4.FTN_NSS
,T4.FTC_CURP
,T4.FTN_ID_MONTO --
,T4.FTN_TIPO_REG --
,T4.FLN_ID_LIB_APORT
,T4.FTC_NOMBRE
,T4.FNN_ID_VIV_GARANTIA
,T4.FTC_RFC --
,T4.FCN_REG_PATRONAL_IMSS --
,T3.FCN_ID_TIPO_SUBCTA
FROM  #DELTA_TABLA_NAME4# T4 
LEFT JOIN #DELTA_TABLA_NAME3# T3 on T4.FCN_ID_CAT_SUBCTA = T3.FCN_ID_CAT_SUBCTA
