SELECT
CAST(FTN_ID_ARCHIVO AS INT ) AS FTN_ID_ARCHIVO,
FTC_FOLIO,
FTC_NOMBRE,
CAST(FCN_ID_PROCESO AS INT ) AS FCN_ID_PROCESO,
CAST(FCN_ID_SUBPROCESO AS INT ) AS FCN_ID_SUBPROCESO,
FTD_FEH_GEN,
FTD_FEH_CRE,
FTC_USU_CRE,
FTD_FEH_ARCHIVO,
CAST(FCN_ID_ESTATUS_ARCHIVO as int) AS FCN_ID_ESTATUS_ARCHIVO
FROM
(
SELECT
  LAST_NUMBER AS FTN_ID_ARCHIVO,
  '#SR_FOLIO#' AS FTC_FOLIO,
  CASE 
    WHEN #SR_SUBPROCESO# = 364 THEN '#SR_PREFIJO_ARCH_TA_364##SR_FECHA_ACTUAL##SR_NOM_ARCHIVO_ACEPT_TA_364##SR_EXT_TXT#' 
    WHEN #SR_SUBPROCESO# = 365 THEN '#SR_PREFIJO_ARCH_AG_365##SR_FECHA_ACTUAL##SR_NOM_ARCHIVO_ACEPT_AG_365##SR_EXT_TXT#' 
    WHEN #SR_SUBPROCESO# = 368 THEN '#SR_PREFIJO_ARCH_UG_368##SR_FECHA_ACTUAL##SR_NOM_ARCHIVO_ACEPT_UG_368##SR_EXT_TXT#'
  END AS FTC_NOMBRE,
  #SR_PROCESO# AS FCN_ID_PROCESO,
  #SR_SUBPROCESO# AS FCN_ID_SUBPROCESO,
  TO_TIMESTAMP('#SR_TIMESTAMP#','DD-MM-YYYY HH24:MI:SS.FF6') AS FTD_FEH_GEN,
  TO_TIMESTAMP('#SR_TIMESTAMP#','DD-MM-YYYY HH24:MI:SS.FF6')  AS FTD_FEH_CRE,
  '#SR_USUARIO#' AS FTC_USU_CRE,
  TO_TIMESTAMP('#SR_TIMESTAMP#','DD-MM-YYYY HH24:MI:SS.FF6')  AS FTD_FEH_ARCHIVO,
  4186 AS FCN_ID_ESTATUS_ARCHIVO
FROM
  ALL_SEQUENCES
WHERE
  SEQUENCE_OWNER = 'CIERREN'
  AND SEQUENCE_NAME = 'SE_TTAFOGRAL_ARCHIVO_SE'
  )