SELECT
  A.FTC_FOLIO_BITACORA AS FTC_FOLIO
 ,97 AS FTN_ID_PROCESO
 ,A.FTN_ID_SUBP AS FTN_ID_SUBPROCESO
 ,A.FTN_NUM_CTA_INVDUAL
 ,V.FCN_ID_SIEFORE as FTN_ID_SIEFORE
,M.FCN_ID_TIPO_SUBCTA AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,SUM(BAL_MOVS.FTN_DISP_ACCIONES) as FTN_MONTO_ACCIONES
, SUM(COALESCE(BAL_MOVS.FTN_DISP_ACCIONES,0) * COALESCE(V.FCN_VALOR_ACCION,0)) AS  FTN_MONTO_PESOS
,V.FCN_ID_VALOR_ACCION AS FTN_ID_VALOR_ACCION 
,FCN_ID_TIPO_MONTO AS FTN_ID_TIPO_MONTO
,11 AS FTN_ID_SALDO_OPERA
,180 AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT

FROM (
        SELECT distinct 
         DPSJL.FTN_NUM_CTA_INVDUAL 
       , DPSJL.FCN_ID_SUBPROCESO as FTN_ID_SUBP 
       ,25  as TIPO_MOV  
       ,DPSJL.FTN_CONSE_REG_LOTE 
       ,DPSJL.FTC_FOLIO as FTC_FOLIO_BITACORA 
       ,C.FTN_ID_MARCA
       from  PROCESOS.TTCRXGRAL_DEV_PAG_SJL DPSJL
       INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C 
          ON DPSJL.FTC_FOLIO=C.FTC_FOLIO 
         AND DPSJL.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
       WHERE  DPSJL.FTC_FOLIO =#sr_folio#
       AND (C.FTB_ESTATUS_MARCA=0 OR C.FCN_CONV_INGTY=0)
       AND DPSJL.FTC_ESTATUS=0  
  
)A LEFT JOIN (
SELECT FTN_NUM_CTA_INVDUAL, 
       SUM(FTN_SDO_ACCIONES) AS FTN_SDO_AIVS,
       SUM(FTN_SDO_PESOS) AS FTN_MONTO_PESOS,
       FTC_FOLIO AS FTC_FOLIO_BITACORA,
       FTN_CONSE_REG_LOTE,
       FCN_ID_TIPO_SUBCTA,
       FTN_ESTATUS
from PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL
where FTC_FOLIO=#sr_folio#
group by FTN_NUM_CTA_INVDUAL,
          FTC_FOLIO, 
          FTN_CONSE_REG_LOTE, 
          FTN_ESTATUS, 
          FCN_ID_TIPO_SUBCTA
)X
ON A.FTC_FOLIO_BITACORA=X.FTC_FOLIO_BITACORA
AND A.FTN_NUM_CTA_INVDUAL=X.FTN_NUM_CTA_INVDUAL
AND A.FTN_CONSE_REG_LOTE=X.FTN_CONSE_REG_LOTE
INNER JOIN
(SELECT distinct DPSJL.FTN_NUM_CTA_INVDUAL
                ,DPSJL.FTN_CONSE_REG_LOTE
                ,DPSJL.FTC_FOLIO
				,FCN_ID_TIPO_SUBCTA
from  PROCESOS.TTCRXGRAL_DEV_PAG_SJL DPSJL
       INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C 
   ON DPSJL.FTC_FOLIO=C.FTC_FOLIO 
  AND DPSJL.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
WHERE  DPSJL.FTC_FOLIO = #sr_folio#
AND DPSJL.FTC_ESTATUS=0
AND FCN_ID_MOTIVO_RECHAZO NOT IN (382,93,354,275,1073)
) CI
ON A.FTN_NUM_CTA_INVDUAL=CI.FTN_NUM_CTA_INVDUAL 
AND A.FTN_CONSE_REG_LOTE=CI.FTN_CONSE_REG_LOTE
AND A.FTC_FOLIO_BITACORA=CI.FTC_FOLIO
AND X.FCN_ID_TIPO_SUBCTA=CI.FCN_ID_TIPO_SUBCTA
INNER join CIERREN.TTAFOGRAL_BALANCE_MOVS BAL_MOVS
ON A.FTN_NUM_CTA_INVDUAL = BAL_MOVS.FTC_NUM_CTA_INVDUAL
INNER JOIN(
SELECT  DISTINCT CMOV.FRN_ID_MOV_SUBCTA
       ,MSUB.FCN_ID_SUBPROCESO
       ,MSUB.FCN_ID_TIPO_SUBCTA
       ,MSUB.FCN_ID_TIPO_MOV
       ,CMOV.FCN_ID_TIPO_MONTO
       ,CAT.FCN_ID_TIPO_CAT AS TIPO_MOV
       ,FCN_ID_REGIMEN
FROM       CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CMOV
INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB ON CMOV.FRN_ID_MOV_SUBCTA = MSUB.FRN_ID_MOV_SUBCTA
INNER JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO CAT ON MSUB.FCN_ID_TIPO_MOV = CAT.FCN_ID_CAT_CATALOGO
INNER JOIN CIERREN.TCCRXGRAL_TIPO_CAT TCAT ON CAT.FCN_ID_TIPO_CAT = TCAT.FCN_ID_TIPO_CAT
INNER JOIN cierren.tccrxgral_tipo_subcta SUB ON  SUB.FCN_ID_TIPO_SUBCTA=MSUB.FCN_ID_TIPO_SUBCTA
WHERE  CMOV.FFB_VIGENCIA = 1
AND    MSUB.FRB_VIGENCIA = 1
AND    MSUB.FCN_ID_SUBPROCESO =#sr_subproceso#
AND    TCAT.FCN_ID_TIPO_CAT =25
AND    TCAT.FCB_VIGENCIA = 1
AND    CAT.FCB_VIGENCIA = 1
AND    MSUB.FCN_ID_TIPO_SUBCTA IN (15,1,2,3)
)M
ON A.FTN_ID_SUBP=M.FCN_ID_SUBPROCESO
AND A.TIPO_MOV=M.TIPO_MOV
AND BAL_MOVS.FCN_ID_TIPO_SUBCTA=M.FCN_ID_TIPO_SUBCTA
LEFT JOIN CIERREN.TCCRXGRAL_TIPO_SUBCTA SUBCTA
ON BAL_MOVS.FCN_ID_TIPO_SUBCTA = SUBCTA.FCN_ID_TIPO_SUBCTA
LEFT JOIN CIERREN.TCAFOGRAL_VALOR_ACCION V ON
BAL_MOVS.FCN_ID_SIEFORE = V.FCN_ID_SIEFORE
AND SUBCTA.FCN_ID_REGIMEN = V.FCN_ID_REGIMEN
--LEFT JOIN CIERREN.TCCRXGRAL_TIPO_SUBCTA SUBCTA ON BAL_MOVS.FCN_ID_TIPO_SUBCTA = SUBCTA.FCN_ID_TIPO_SUBCTA
--LEFT JOIN CIERREN.TCAFOGRAL_VALOR_ACCION V ON BAL_MOVS.FCN_ID_SIEFORE = V.FCN_ID_SIEFORE
--AND SUBCTA.FCN_ID_REGIMEN = V.FCN_ID_REGIMEN
WHERE   TO_TIMESTAMP(TRUNC(V.FCD_FEH_ACCION),'DD-MM-YY HH24:MI:SS') = TO_TIMESTAMP(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'DD-MM-YY HH24:MI:SS')
AND X.FTN_ESTATUS=1
group by A.FTC_FOLIO_BITACORA,A.FTN_ID_SUBP,A.FTN_NUM_CTA_INVDUAL
 ,V.FCN_ID_SIEFORE,M.FCN_ID_TIPO_SUBCTA,V.FCN_ID_VALOR_ACCION,FCN_ID_TIPO_MONTO
 ORDER BY FTN_NUM_CTA_INVDUAL
 
 