SELECT
  X.FTC_FOLIO_BITACORA AS FTC_FOLIO
 ,7 AS FTN_ID_PROCESO
 ,X.FTN_ID_SUBP AS FTN_ID_SUBPROCESO
 ,X.FTN_NUM_CTA_INVDUAL
 ,NVL(V.FCN_ID_SIEFORE,0) as FTN_ID_SIEFORE
,M.FCN_ID_TIPO_SUBCTA AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,SUM(BAL_MOVS.FTN_DISP_ACCIONES) as FTN_MONTO_ACCIONES
,SUM(COALESCE(BAL_MOVS.FTN_DISP_ACCIONES,0) * COALESCE(V.FCN_VALOR_ACCION,0)) AS  FTN_MONTO_PESOS
,NVL(V.FCN_ID_VALOR_ACCION,0) AS FTN_ID_VALOR_ACCION 
,FCN_ID_TIPO_MONTO AS FTN_ID_TIPO_MONTO
,FCN_ID_SALDO_OPERA AS FTN_ID_SALDO_OPERA
,FCN_ID_TIPO_MOV AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT

FROM (
select DISTINCT
SJL.FTC_FOLIO AS FTC_FOLIO_BITACORA
,SJL.FTN_NUM_CTA_INVDUAL  AS FTN_NUM_CTA_INVDUAL 
,SJL.FCN_ID_SUBPROCESO AS FTN_ID_SUBP 
,25 AS TIPO_MOV
,SALD.FTN_ESTATUS
,SALD.FCN_ID_TIPO_SUBCTA
from  PROCESOS.TTCRXGRAL_DEV_PAG_SJL SJL
 LEFT JOIN (
SELECT FTN_NUM_CTA_INVDUAL, 
       SUM(FTN_SDO_ACCIONES) AS FTN_SDO_AIVS,
       SUM(FTN_SDO_PESOS) AS FTN_MONTO_PESOS,
       FTC_FOLIO AS FTC_FOLIO_BITACORA,
       FTN_CONSE_REG_LOTE,
       FTN_ESTATUS AS FCN_ESTATUS,
       FCN_ID_TIPO_SUBCTA,
       FTN_ESTATUS
from PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL
where FTC_FOLIO=#sr_folio#
and FTN_ESTATUS=1
group by FTN_NUM_CTA_INVDUAL,
          FTC_FOLIO, 
          FTN_CONSE_REG_LOTE, 
          FTN_ESTATUS, 
          FCN_ID_TIPO_SUBCTA
)SALD
ON SJL.FTC_FOLIO=SALD.FTC_FOLIO_BITACORA
AND SJL.FTN_NUM_CTA_INVDUAL=SALD.FTN_NUM_CTA_INVDUAL
AND SJL.FTN_CONSE_REG_LOTE=SALD.FTN_CONSE_REG_LOTE
where
SJL.FTC_FOLIO=#sr_folio#
and  
SJL.FTC_ESTATUS = 1
  
)X
INNER JOIN(
SELECT  DISTINCT CMOV.FRN_ID_MOV_SUBCTA
       ,MSUB.FCN_ID_SUBPROCESO
       ,MSUB.FCN_ID_TIPO_SUBCTA
       ,MSUB.FCN_ID_TIPO_MOV
       ,CMOV.FCN_ID_TIPO_MONTO
       ,CAT.FCN_ID_TIPO_CAT AS TIPO_MOV
       ,FCN_ID_REGIMEN
FROM       CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CMOV
INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB ON CMOV.FRN_ID_MOV_SUBCTA = MSUB.FRN_ID_MOV_SUBCTA
INNER JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO CAT ON MSUB.FCN_ID_TIPO_MOV = CAT.FCN_ID_CAT_CATALOGO
INNER JOIN CIERREN.TCCRXGRAL_TIPO_CAT TCAT ON CAT.FCN_ID_TIPO_CAT = TCAT.FCN_ID_TIPO_CAT
INNER JOIN cierren.tccrxgral_tipo_subcta SUB ON  SUB.FCN_ID_TIPO_SUBCTA=MSUB.FCN_ID_TIPO_SUBCTA
WHERE  CMOV.FFB_VIGENCIA = 1
AND    MSUB.FRB_VIGENCIA = 1
AND    MSUB.FCN_ID_SUBPROCESO = #sr_subproceso#
AND    TCAT.FCN_ID_TIPO_CAT =25
AND    TCAT.FCB_VIGENCIA = 1
AND    CAT.FCB_VIGENCIA = 1
AND    MSUB.FCN_ID_TIPO_SUBCTA IN (15,1,2,3)
)M
ON X.FTN_ID_SUBP=M.FCN_ID_SUBPROCESO
AND X.TIPO_MOV=M.TIPO_MOV
AND X.FCN_ID_TIPO_SUBCTA=M.FCN_ID_TIPO_SUBCTA
left outer join (
SELECT   A.FTC_NUM_CTA_INVDUAL 
         ,A.FCN_ID_TIPO_SUBCTA
         ,A.FCN_ID_SIEFORE
         ,B.FCN_ID_REGIMEN
         ,SUM(NVL(A.FTN_DISP_ACCIONES,0))FTN_DISP_ACCIONES
  FROM   CIERREN.TTAFOGRAL_BALANCE_MOVS A
  INNER JOIN CIERREN.TCCRXGRAL_TIPO_SUBCTA B ON A.FCN_ID_TIPO_SUBCTA= B.FCN_ID_TIPO_SUBCTA
  WHERE A.FTC_NUM_CTA_INVDUAL  IN  
  (SELECT FTN_NUM_CTA_INVDUAL 
   FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL 
   WHERE FTC_FOLIO=#sr_folio#)
  AND A.FCN_ID_SIEFORE in (74,75,76,77,78,79,80,81,82,83)
  AND A.FCN_ID_TIPO_SUBCTA IN (15, 1,3,2)
  GROUP BY A.FTC_NUM_CTA_INVDUAL, A.FCN_ID_TIPO_SUBCTA, A.FCN_ID_SIEFORE ,B.FCN_ID_REGIMEN

) BAL_MOVS
ON X.FTN_NUM_CTA_INVDUAL = BAL_MOVS.FTC_NUM_CTA_INVDUAL
AND X.FCN_ID_TIPO_SUBCTA=BAL_MOVS.FCN_ID_TIPO_SUBCTA
LEFT OUTER JOIN CIERREN.TCAFOGRAL_VALOR_ACCION V ON
BAL_MOVS.FCN_ID_SIEFORE = V.FCN_ID_SIEFORE
AND BAL_MOVS.FCN_ID_REGIMEN = V.FCN_ID_REGIMEN
LEFT OUTER JOIN 
(  SELECT CON.FCN_ID_PROCESO
   ,CON.FCN_ID_SUBPROCESO
    ,CON.FCN_ID_SALDO_OPERA 
FROM CIERREN.TFAFOGRAL_CONFIG_SUBPROCESO CON   
WHERE CON.FCN_ID_PROCESO = 7  
AND       CON.FCN_ID_SUBPROCESO = #sr_subproceso#
ORDER BY CON.FCN_ID_PROCESO, CON.FCN_ID_SUBPROCESO ASC
) CS
ON  X.FTN_ID_SUBP=CS.FCN_ID_SUBPROCESO
--LEFT JOIN CIERREN.TCCRXGRAL_TIPO_SUBCTA SUBCTA ON BAL_MOVS.FCN_ID_TIPO_SUBCTA = SUBCTA.FCN_ID_TIPO_SUBCTA
--LEFT JOIN CIERREN.TCAFOGRAL_VALOR_ACCION V ON BAL_MOVS.FCN_ID_SIEFORE = V.FCN_ID_SIEFORE
--AND SUBCTA.FCN_ID_REGIMEN = V.FCN_ID_REGIMEN
WHERE   TO_TIMESTAMP(TRUNC(V.FCD_FEH_ACCION),'DD-MM-YY HH24:MI:SS') = TO_TIMESTAMP(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'DD-MM-YY HH24:MI:SS')
AND X.FTN_ESTATUS=1
group by X.FTC_FOLIO_BITACORA,X.FTN_ID_SUBP,X.FTN_NUM_CTA_INVDUAL
 ,V.FCN_ID_SIEFORE,M.FCN_ID_TIPO_SUBCTA,V.FCN_ID_VALOR_ACCION,FCN_ID_TIPO_MONTO,FCN_ID_SALDO_OPERA,FCN_ID_TIPO_MOV
 ORDER BY FTN_NUM_CTA_INVDUAL

 