SELECT
  TFI.FTC_FOLIO_BITACORA AS FTC_FOLIO
 ,97 AS FTN_ID_PROCESO
 ,TFI.FTN_ID_SUBP AS FTN_ID_SUBPROCESO
 ,TFI.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL
 ,BAL_MOVS.FCN_ID_SIEFORE AS FTN_ID_SIEFORE
,M.FCN_ID_TIPO_SUBCTA AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,SUM(BAL_MOVS.FTN_DISP_ACCIONES) as  FTN_MONTO_ACCIONES
, SUM(COALESCE(BAL_MOVS.FTN_DISP_ACCIONES,0) * COALESCE(V.FCN_VALOR_ACCION,0)) AS  FTN_MONTO_PESOS
,V.FCN_ID_VALOR_ACCION AS FTN_ID_VALOR_ACCION
,199 AS FTN_ID_TIPO_MONTO
,11 AS FTN_ID_SALDO_OPERA
,180 AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT
FROM  (select DISTINCT
FTC_FOLIO_BITACORA
,FCN_ID_SIEFORE
,FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL 
, FTN_ID_SUBP 
,25 AS TIPO_MOV

from  PROCESOS.TTCRXGRAL_TRANS_INFONA
where
FTC_FOLIO_BITACORA=#sr_folio#

) TFI
inner JOIN (
 select DISTINCT 
 FTC_FOLIO_BITACORA,
FTN_NUM_CTA_INVDUAL
from PROCESOS.TTSISGRAL_SUF_SALDOS
where FTC_FOLIO_BITACORA=#sr_folio#
)X
ON TFI.FTC_FOLIO_BITACORA=X.FTC_FOLIO_BITACORA
AND TFI.FTN_NUM_CTA_INVDUAL=X.FTN_NUM_CTA_INVDUAL

INNER JOIN  CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C 
ON TFI.FTC_FOLIO_BITACORA=C.FTC_FOLIO
AND TFI.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
AND TFI.FTN_ID_SUBP=C.FCN_ID_SUBPROCESO
left outer join CIERREN.TTAFOGRAL_BALANCE_MOVS BAL_MOVS
ON TFI.FTN_NUM_CTA_INVDUAL = BAL_MOVS.FTC_NUM_CTA_INVDUAL
INNER JOIN(
SELECT  CMOV.FRN_ID_MOV_SUBCTA
       ,MSUB.FCN_ID_SUBPROCESO
       ,MSUB.FCN_ID_TIPO_SUBCTA
       ,MSUB.FCN_ID_TIPO_MOV
       ,CMOV.FFN_ID_CONCEPTO_MOV
       ,CMOV.FCN_ID_TIPO_MONTO
       ,CAT.FCN_ID_TIPO_CAT AS TIPO_MOV
FROM       CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CMOV
INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB ON CMOV.FRN_ID_MOV_SUBCTA = MSUB.FRN_ID_MOV_SUBCTA
INNER JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO CAT ON MSUB.FCN_ID_TIPO_MOV = CAT.FCN_ID_CAT_CATALOGO
INNER JOIN CIERREN.TCCRXGRAL_TIPO_CAT TCAT ON CAT.FCN_ID_TIPO_CAT = TCAT.FCN_ID_TIPO_CAT
WHERE  CMOV.FFB_VIGENCIA = 1
AND    MSUB.FRB_VIGENCIA = 1
AND    MSUB.FCN_ID_SUBPROCESO =#sr_subproceso#
AND    TCAT.FCN_ID_TIPO_CAT = 25
AND    TCAT.FCB_VIGENCIA = 1
AND    CAT.FCB_VIGENCIA = 1
AND    MSUB.FCN_ID_TIPO_SUBCTA in (15,16)
)M
ON TFI.FTN_ID_SUBP=M.FCN_ID_SUBPROCESO
AND TFI.TIPO_MOV=M.TIPO_MOV
AND BAL_MOVS.FCN_ID_TIPO_SUBCTA=M.FCN_ID_TIPO_SUBCTA
LEFT JOIN CIERREN.TCCRXGRAL_TIPO_SUBCTA SUBCTA
ON BAL_MOVS.FCN_ID_TIPO_SUBCTA = SUBCTA.FCN_ID_TIPO_SUBCTA
LEFT JOIN CIERREN.TCAFOGRAL_VALOR_ACCION V ON
BAL_MOVS.FCN_ID_SIEFORE = V.FCN_ID_SIEFORE
AND SUBCTA.FCN_ID_REGIMEN = V.FCN_ID_REGIMEN
--LEFT JOIN CIERREN.TCCRXGRAL_TIPO_SUBCTA SUBCTA ON BAL_MOVS.FCN_ID_TIPO_SUBCTA = SUBCTA.FCN_ID_TIPO_SUBCTA
--LEFT JOIN CIERREN.TCAFOGRAL_VALOR_ACCION V ON BAL_MOVS.FCN_ID_SIEFORE = V.FCN_ID_SIEFORE
--AND SUBCTA.FCN_ID_REGIMEN = V.FCN_ID_REGIMEN
--WHERE  TRUNC(V.FCD_FEH_ACCION)  = TRUNC (SYSDATE)
WHERE (C.FTB_ESTATUS_MARCA=0 OR C.FCN_CONV_INGTY=0)
AND  TO_TIMESTAMP(TRUNC(V.FCD_FEH_ACCION),'DD-MM-YY HH24:MI:SS') = TO_TIMESTAMP(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'DD-MM-YY HH24:MI:SS')
GROUP BY   TFI.FTC_FOLIO_BITACORA,TFI.FTN_ID_SUBP,TFI.FTN_NUM_CTA_INVDUAL,BAL_MOVS.FCN_ID_SIEFORE,M.FCN_ID_TIPO_SUBCTA,V.FCN_ID_VALOR_ACCION

