SELECT
  X.FTC_FOLIO AS FTC_FOLIO
 ,7 AS FTN_ID_PROCESO
 ,X.FTN_ID_SUBP AS FTN_ID_SUBPROCESO
 ,X.FTN_NUM_CTA_INVDUAL
 ,NVL(X.FCN_ID_SIEFORE,0) as FTN_ID_SIEFORE
,M.FCN_ID_TIPO_SUBCTA AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,FTN_SDO_AIVS as FTN_MONTO_ACCIONES
, FTN_MONTO_PESOS AS  FTN_MONTO_PESOS
,NVL(FCN_ID_VALOR_ACCION,0) AS FTN_ID_VALOR_ACCION 
,FCN_ID_TIPO_MONTO AS FTN_ID_TIPO_MONTO
,FCN_ID_SALDO_OPERA AS FTN_ID_SALDO_OPERA
,FCN_ID_TIPO_MOV AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT

FROM (
       SELECT distinct 
         DPSJL.FTN_NUM_CTA_INVDUAL 
       , DPSJL.FCN_ID_SUBPROCESO as FTN_ID_SUBP 
       ,25  as TIPO_MOV  
       ,DPSJL.FTN_CONSE_REG_LOTE 
       ,DPSJL.FTC_FOLIO 
       ,SALD.FCN_ID_TIPO_SUBCTA
       ,SALD.FTN_ESTATUS
       ,FTN_SDO_AIVS
       ,FTN_MONTO_PESOS
       ,FCN_ID_VALOR_ACCION
       ,FCN_ID_SIEFORE
       from  PROCESOS.TTCRXGRAL_DEV_PAG_SJL DPSJL
       LEFT OUTER JOIN  CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA C 
          ON DPSJL.FTC_FOLIO=C.FTC_FOLIO 
         AND DPSJL.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
        LEFT JOIN (
    SELECT FTN_NUM_CTA_INVDUAL, 
       SUM(NVL(FTN_SDO_ACCIONES,0)) AS FTN_SDO_AIVS,
       SUM(NVL(FTN_SDO_PESOS,0)) AS FTN_MONTO_PESOS,
       FTC_FOLIO AS FTC_FOLIO_BITACORA,
       FTN_CONSE_REG_LOTE,
       FTN_ESTATUS AS FCN_ESTATUS,
       FCN_ID_TIPO_SUBCTA,
       FTN_ESTATUS,
       FCN_ID_SIEFORE,
       MAX(FCN_ID_VALOR_ACCION) AS FCN_ID_VALOR_ACCION
from PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL
where FTC_FOLIO=#sr_folio#
and FTN_ESTATUS<>0
group by FTN_NUM_CTA_INVDUAL,
          FTC_FOLIO, 
          FTN_CONSE_REG_LOTE, 
          FTN_ESTATUS, 
          FCN_ID_TIPO_SUBCTA,
        FCN_ID_SIEFORE
)SALD
ON DPSJL.FTC_FOLIO=SALD.FTC_FOLIO_BITACORA
AND DPSJL.FTN_NUM_CTA_INVDUAL=SALD.FTN_NUM_CTA_INVDUAL
AND DPSJL.FTN_CONSE_REG_LOTE=SALD.FTN_CONSE_REG_LOTE
       WHERE  DPSJL.FTC_FOLIO =#sr_folio#
        AND DPSJL.FTC_ESTATUS=1
       AND (C.FTB_ESTATUS_MARCA=0 OR C.FTB_ESTATUS_MARCA is null )
)X
LEFT OUTER JOIN
(SELECT distinct DPSJL.FTN_NUM_CTA_INVDUAL
                ,DPSJL.FTN_CONSE_REG_LOTE
                ,DPSJL.FTC_FOLIO
				,FCN_ID_TIPO_SUBCTA
from  PROCESOS.TTCRXGRAL_DEV_PAG_SJL DPSJL
       INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C 
   ON DPSJL.FTC_FOLIO=C.FTC_FOLIO 
  AND DPSJL.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
WHERE  DPSJL.FTC_FOLIO =#sr_folio#
) CI
ON X.FTN_NUM_CTA_INVDUAL=CI.FTN_NUM_CTA_INVDUAL 
AND X.FTN_CONSE_REG_LOTE=CI.FTN_CONSE_REG_LOTE
AND X.FTC_FOLIO=CI.FTC_FOLIO
AND X.FCN_ID_TIPO_SUBCTA=CI.FCN_ID_TIPO_SUBCTA
INNER JOIN(
SELECT  DISTINCT CMOV.FRN_ID_MOV_SUBCTA
       ,MSUB.FCN_ID_SUBPROCESO
       ,MSUB.FCN_ID_TIPO_SUBCTA
       ,MSUB.FCN_ID_TIPO_MOV
       ,CMOV.FCN_ID_TIPO_MONTO
       ,CAT.FCN_ID_TIPO_CAT AS TIPO_MOV
       ,FCN_ID_REGIMEN
FROM       CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CMOV
INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB ON CMOV.FRN_ID_MOV_SUBCTA = MSUB.FRN_ID_MOV_SUBCTA
INNER JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO CAT ON MSUB.FCN_ID_TIPO_MOV = CAT.FCN_ID_CAT_CATALOGO
INNER JOIN CIERREN.TCCRXGRAL_TIPO_CAT TCAT ON CAT.FCN_ID_TIPO_CAT = TCAT.FCN_ID_TIPO_CAT
INNER JOIN cierren.tccrxgral_tipo_subcta SUB ON  SUB.FCN_ID_TIPO_SUBCTA=MSUB.FCN_ID_TIPO_SUBCTA
WHERE  CMOV.FFB_VIGENCIA = 1
AND    MSUB.FRB_VIGENCIA = 1
AND    MSUB.FCN_ID_SUBPROCESO =#sr_subproceso#
AND    TCAT.FCN_ID_TIPO_CAT =25
AND    TCAT.FCB_VIGENCIA = 1
AND    CAT.FCB_VIGENCIA = 1
AND    MSUB.FCN_ID_TIPO_SUBCTA IN (15,1,2,3)
)M
ON X.FTN_ID_SUBP=M.FCN_ID_SUBPROCESO
AND X.TIPO_MOV=M.TIPO_MOV
AND X.FCN_ID_TIPO_SUBCTA=M.FCN_ID_TIPO_SUBCTA

LEFT OUTER JOIN 
(  SELECT CON.FCN_ID_PROCESO
   ,CON.FCN_ID_SUBPROCESO
    ,CON.FCN_ID_SALDO_OPERA 
FROM CIERREN.TFAFOGRAL_CONFIG_SUBPROCESO CON   
WHERE CON.FCN_ID_PROCESO = 7  
AND       CON.FCN_ID_SUBPROCESO =#sr_subproceso#
ORDER BY CON.FCN_ID_PROCESO, CON.FCN_ID_SUBPROCESO ASC
) CS
ON  X.FTN_ID_SUBP=CS.FCN_ID_SUBPROCESO
WHERE  X.FTN_ESTATUS=1

 
 