
SELECT
    -- If DIAG92 = '01' or DIAG97 = '01' then NULL else vMotivoRechazo
    CASE
        WHEN DIAG92 = '01' OR DIAG97 = '01' THEN NULL
        WHEN FTN_IND_SDO_DISP_92 = 0 AND FTN_IND_SDO_DISP_VIV97 = 0 THEN 584
        ELSE NULL
    END AS FTN_MOTIVO_RECHAZO,
    FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_AFORE,
    FTC_FOLIO_BITACORA,
    FTN_CONTA_SERV,
    -- If DIAG92 = '01' or DIAG97 = '01' then '1' else '0'
    CASE
        WHEN DIAG92 = '01' OR DIAG97 = '01' THEN '1'
        ELSE '0'
    END AS FTC_ESTATUS_REGISTRO,
    CURRENT_DATE AS FTD_FEH_ACTUA_ESTATUS,
    CURRENT_TIMESTAMP AS FTD_FEH_ACT,
    'DATABRICKS' AS FCC_USU_ACT,
    DIAG92 AS FTC_INDI_DIFE_VIVI92,
    DIAG97 AS FTC_INDI_DIFE_VIVI97,
     0 AS  FTN_ID_SUBP
FROM
    #DELTA_TABLE_BD_600_TRANS_INFONA#