SELECT
    A.FTN_NUM_CTA_INVDUAL,
    A.FCN_ID_SUBPROCESO,
    A.FTN_CONTA_SERV,
    A.FTN_NUM_APLI_INTE_VIVI92_SOL,
    A.FTN_NUM_APLI_INTE_VIVI08_SOL,
    A.FTN_SALDO_TOT_VIVI92,
    A.FTN_SALDO_TOT_VIVI08,
    NVL(L.FCN_VALOR_ACCION, 0) AS FCN_VALOR_ACCION,
    L.FCN_ID_VALOR_ACCION,
   18 as FCN_ID_TIPO_SUBCTA_08,
    17 as FCN_ID_TIPO_SUBCTA_92,
    CASE 
        WHEN CASE  
            WHEN NVL(A.FTN_NUM_APLI_INTE_VIVI08_SOL, 0) <= NVL(S08.SALDO_DISPONIBLE_AIVS, 0) THEN NVL(A.FTN_NUM_APLI_INTE_VIVI08_SOL, 0)
            ELSE NVL(S08.SALDO_DISPONIBLE_AIVS, 0)
            END <= 0 THEN 0 
        ELSE 1 
    END AS FTN_IND_SDO_DISP_VIV08,  -- Nueva columna para el resultado de la regla
    CASE 
        WHEN CASE  
            WHEN NVL(A.FTN_NUM_APLI_INTE_VIVI92_SOL, 0) <= NVL(S92.SALDO_DISPONIBLE_AIVS, 0) THEN NVL(A.FTN_NUM_APLI_INTE_VIVI92_SOL, 0)
            ELSE NVL(S92.SALDO_DISPONIBLE_AIVS, 0)
            END <= 0 THEN 0 
        ELSE 1 
    END AS FTN_IND_SDO_DISP_VIV92,
    CASE 
    WHEN (A.FTN_NUM_APLI_INTE_VIVI08_SOL  - 
          CASE 
            WHEN NVL(A.FTN_NUM_APLI_INTE_VIVI08_SOL, 0) <= NVL(S08.SALDO_DISPONIBLE_AIVS, 0) THEN NVL(A.FTN_NUM_APLI_INTE_VIVI08_SOL, 0)
            ELSE NVL(S08.SALDO_DISPONIBLE_AIVS, 0)
          END) >=1 
         AND (CASE 
                WHEN NVL(A.FTN_NUM_APLI_INTE_VIVI08_SOL, 0) <= NVL(S08.SALDO_DISPONIBLE_AIVS, 0) THEN NVL(A.FTN_NUM_APLI_INTE_VIVI08_SOL, 0)
                ELSE NVL(S08.SALDO_DISPONIBLE_AIVS, 0)
              END) <> 0 
    THEN '003' --p_MOT_ACE_PARCIAL08
    ELSE NULL 
  END AS FTC_DIAG_PROCESO08,  -- Nueva columna para el resultado de la regla
   CASE 
    WHEN (A.FTN_NUM_APLI_INTE_VIVI92_SOL - 
          CASE 
            WHEN NVL(A.FTN_NUM_APLI_INTE_VIVI92_SOL, 0) <= NVL(S92.SALDO_DISPONIBLE_AIVS, 0) THEN NVL(A.FTN_NUM_APLI_INTE_VIVI92_SOL, 0)
 ELSE NVL(S92.SALDO_DISPONIBLE_AIVS, 0)
          END) >= 1 
         AND (CASE 
                WHEN NVL(A.FTN_NUM_APLI_INTE_VIVI92_SOL, 0) <= NVL(S92.SALDO_DISPONIBLE_AIVS, 0) THEN NVL(A.FTN_NUM_APLI_INTE_VIVI92_SOL, 0)
                ELSE NVL(S92.SALDO_DISPONIBLE_AIVS, 0)
              END) <> 0 
    THEN '002'--p_MOT_ACE_PARCIAL92 
    ELSE NULL 
  END AS FTC_DIAG_PROCESO92,  -- Nueva columna para el resultado de la regla
   CASE 
                WHEN NVL(A.FTN_NUM_APLI_INTE_VIVI08_SOL, 0) <= NVL(S08.SALDO_DISPONIBLE_AIVS, 0) THEN NVL(A.FTN_NUM_APLI_INTE_VIVI08_SOL, 0)
                ELSE NVL(S08.SALDO_DISPONIBLE_AIVS, 0)
              END as FTN_NUM_APLI_INTE_VIVI08_APL,

   CASE 
                WHEN NVL(A.FTN_NUM_APLI_INTE_VIVI92_SOL, 0) <= NVL(S92.SALDO_DISPONIBLE_AIVS, 0) THEN NVL(A.FTN_NUM_APLI_INTE_VIVI92_SOL, 0)
                ELSE NVL(S92.SALDO_DISPONIBLE_AIVS, 0)
    END as FTN_NUM_APLI_INTE_VIVI92_APL
FROM
  PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE A
LEFT JOIN (
  SELECT
    FTC_NUM_CTA_INVDUAL,
    NVL(SUM(FTN_DISP_ACCIONES),0 ) AS SALDO_DISPONIBLE_AIVS
  FROM CIERREN.TTAFOGRAL_BALANCE_MOVS
  WHERE FCN_ID_SIEFORE = 81
    AND FCN_ID_TIPO_SUBCTA = 18 -- VIV08
    AND FTC_NUM_CTA_INVDUAL IN (
      SELECT FTN_NUM_CTA_AFORE
      FROM PROCESOS.TTCRXGRAL_TRANS_INFONA
      WHERE FTC_FOLIO_BITACORA = '202502122147367147'
    )
          GROUP BY FTC_NUM_CTA_INVDUAL
        ) S08
          ON A.FTN_NUM_CTA_INVDUAL = S08.FTC_NUM_CTA_INVDUAL
        LEFT JOIN (
          SELECT
            FTC_NUM_CTA_INVDUAL,
            NVL(SUM(FTN_DISP_ACCIONES), 0) AS SALDO_DISPONIBLE_AIVS
          FROM CIERREN.TTAFOGRAL_BALANCE_MOVS
          WHERE FCN_ID_SIEFORE = 81
            AND FCN_ID_TIPO_SUBCTA = 17 -- VIV92
            AND FTC_NUM_CTA_INVDUAL IN (
              SELECT FTN_NUM_CTA_AFORE
              FROM PROCESOS.TTCRXGRAL_TRANS_INFONA
              WHERE FTC_FOLIO_BITACORA = '202502122147367147'
    )
          GROUP BY FTC_NUM_CTA_INVDUAL
        ) S92
          ON A.FTN_NUM_CTA_INVDUAL = S92.FTC_NUM_CTA_INVDUAL
          left JOIN (
          SELECT 
            FCD_FEH_ACCION,
            FCN_VALOR_ACCION,
            FCN_ID_VALOR_ACCION  
          FROM CIERREN.TCAFOGRAL_VALOR_ACCION 
          WHERE FCN_ID_SIEFORE = 81
            AND FCN_ID_REGIMEN = 139
        ) L 
        ON ADD_MONTHS(TRUNC(SYSDATE, 'MONTH'), 1) = TRUNC(L.FCD_FEH_ACCION)
        WHERE
           A.FTC_FOLIO = '201908090920290001'
          and
          A.FTC_ESTATUS = 1
          AND (NVL(S08.SALDO_DISPONIBLE_AIVS,0) > 0 OR NVL(S92.SALDO_DISPONIBLE_AIVS,0) > 0)
          UNION ALL
SELECT
        A.FTN_NUM_CTA_INVDUAL,
        A.FCN_ID_SUBPROCESO,
        A.FTN_CONTA_SERV,
        A.FTN_NUM_APLI_INTE_VIVI92_SOL,
        A.FTN_NUM_APLI_INTE_VIVI08_SOL,
        CAST(0 AS decimal(18,2)) FTN_SALDO_TOT_VIVI92,     -- Generated
        CAST(0 AS decimal(18,2)) AS FTN_SALDO_TOT_VIVI08,
        CAST(0 AS decimal(18,14)) AS FCN_VALOR_ACCION,
        CAST(0 AS decimal(10,0)) AS FCN_ID_VALOR_ACCION,
        
        CAST(18 AS decimal(4,0)) AS FCN_ID_TIPO_SUBCTA_08,
        CAST(17 AS decimal(10,0)) AS FCN_ID_TIPO_SUBCTA_92,
        CAST(0 AS decimal(1,0)) AS FTN_IND_SDO_DISP_VIV08,
        CAST(0 AS decimal(1,0)) AS FTN_IND_SDO_DISP_VIV92,
        '' AS FTC_DIAG_PROCESO08,                              -- Generated CG_402_GEN_COL_FALTANTES
        '' AS FTC_DIAG_PROCESO92,
        CAST(0 AS decimal(18,6)) AS FTN_NUM_APLI_INTE_VIVI08_APL,
        CAST(0 AS decimal(18,6)) AS FTN_NUM_APLI_INTE_VIVI92_APL
    FROM
  PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE A
LEFT JOIN (
  SELECT
    FTC_NUM_CTA_INVDUAL,
    NVL(SUM(FTN_DISP_ACCIONES),0 ) AS SALDO_DISPONIBLE_AIVS
  FROM CIERREN.TTAFOGRAL_BALANCE_MOVS
  WHERE FCN_ID_SIEFORE = 81
    AND FCN_ID_TIPO_SUBCTA = 18 -- VIV08
    AND FTC_NUM_CTA_INVDUAL IN (
      SELECT FTN_NUM_CTA_AFORE
      FROM PROCESOS.TTCRXGRAL_TRANS_INFONA
      WHERE FTC_FOLIO_BITACORA = '202502122147367147'
    )
  GROUP BY FTC_NUM_CTA_INVDUAL
) S08
  ON A.FTN_NUM_CTA_INVDUAL = S08.FTC_NUM_CTA_INVDUAL
LEFT JOIN (
  SELECT
    FTC_NUM_CTA_INVDUAL,
    NVL(SUM(FTN_DISP_ACCIONES), 0) AS SALDO_DISPONIBLE_AIVS
  FROM CIERREN.TTAFOGRAL_BALANCE_MOVS
  WHERE FCN_ID_SIEFORE = 81
    AND FCN_ID_TIPO_SUBCTA = 17 -- VIV92
    AND FTC_NUM_CTA_INVDUAL IN (
      SELECT FTN_NUM_CTA_AFORE
      FROM PROCESOS.TTCRXGRAL_TRANS_INFONA
      WHERE FTC_FOLIO_BITACORA = '202502122147367147'
    )
  GROUP BY FTC_NUM_CTA_INVDUAL
) S92
  ON A.FTN_NUM_CTA_INVDUAL = S92.FTC_NUM_CTA_INVDUAL
WHERE
   A.FTC_FOLIO = '201908090920290001'
  and
  A.FTC_ESTATUS = 1
  AND (NVL(S08.SALDO_DISPONIBLE_AIVS,0) <= 0 AND NVL(S92.SALDO_DISPONIBLE_AIVS,0) <= 0);
  