SELECT DISTINCT /* INDEX(CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS IDX_TTSISGRAL_ETL_MOV_03) */
        FTC_FOLIO
        ,FTN_NUM_CTA_INVDUAL
        ,FNN_ID_REFERENCIA
FROM CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS
WHERE FTC_FOLIO = '#SR_FOLIO#' AND FTN_REG_ACREDITADO = 0