SELECT /*+ PARALLEL(4) */
    SUA.FNN_ID_REFERENCIA
    ,SUA.FTC_FOLIO
    ,SUA.FCN_ID_PROCESO
    ,SUA.FCN_ID_SUBPROCESO
    ,0 FNN_NUMREG
    ,SUA.FNC_TIPREG
    ,SUA.FTN_NSS
    ,SUA.FTN_CONS_REG_LOTE
    ,SUA.FTC_RFC
    ,SUA.FTC_CURP
    ,SUA.FTC_NOMBRE
    ,SUA.FNC_PERIODO_PAGO_PATRON
    ,SUA.FND_FECHA_PAGO
    ,SUA.FND_FECHA_VALOR_IMSS_ACV_VIV
    ,SUA.FNN_ULTIMO_SALARIO_INT_PER
    ,SUA.FNC_FOLIO_PAGO_SUA
    ,SUA.FNC_REG_PATRONAL_IMSS
    ,SUA.FNC_RFC_PATRON
    ,SUA.FNN_DIAS_COTZDOS_BIMESTRE
    ,SUA.FNN_DIAS_INCAP_BIMESTRE
    ,SUA.FNN_DIAS_AUSENT_BIMESTRE
    ,SUA.FNN_ID_VIV_GARANTIA
    ,SUA.FNN_APLIC_INT_VIVIENDA
    ,SUA.FNC_MOTIVO_LIBCION_APORT
    ,SUA.FND_FECHA_PAGO_CUOTA_GUB
    ,SUA.FND_FECHA_VALOR_RCV
    ,SUA.FND_FECTRA
    ,SUA.FNN_SECLOT
     ,0 FNN_AFORE
     ,0 FNN_DEVPAG
    ,SUA.FNN_CVE_ENT_RECEP_PAGO
    ,SUA.FNN_NSS_ISSSTE
    ,SUA.FNC_DEPEND_CTRO_PAGO
    ,SUA.FNN_CTRO_PAGO_SAR
    ,SUA.FNN_CVE_RAMO
    ,SUA.FNC_CVE_PAGADURIA
    ,SUA.FNN_SUELDO_BASICO_COTIZ_RCV
    ,SUA.FNC_ID_TRABAJADOR_BONO
    ,CAST(CURRENT_TIMESTAMP AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FND_FEH_CRE
    ,'#SR_USUARIO#' AS FNC_USU_CRE
    ,SUA.FTN_INTERESES_VIV92
    ,SUA.FTN_INTERESES_VIV08
    ,SUA.FCN_ID_TIPO_APO
FROM CIERREN_ETL.TLSISGRAL_ETL_CLIENTE_SUA SUA
WHERE FTC_FOLIO = '#SR_FOLIO#'

