------- UPDATE CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_FOVISSSTE
MERGE INTO PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE TGT
USING (
    SELECT DISTINCT
        FTC_NSS
				,FTC_CODIGO_RES_OPER
				,FTC_FOLIO 
				,FTC_CURP
				--,FTC_TIPO_ARCH_REJ
				,FTD_FEH_CRE
				,FTC_TIPO_ARCH 
				,FTC_ESTATUS 
				,FTN_MOTIVO_RECHAZO 
				,FTD_FEH_ACT  
				,FCC_USU_ACT
				--,FTN_COIN_PROCESAR 
				,FTC_DIAG_PROCESAR
				--,DETALLE
				--,VALIDACION 
				--,COD_ERROR
				--,DESC_ERROR 
				
    FROM CIERREN_DATAUX.TTAFOTRAS_TRANS_FOVISSSTE_AUX
    WHERE FTC_FOLIO = '#sr_folio#'
) SRC
ON (
    TGT.FTC_FOLIO = SRC.FTC_FOLIO
    AND TGT.FTC_CURP = SRC.FTC_CURP
)
WHEN MATCHED THEN
    UPDATE SET
		TGT.FTC_NSS = SRC.FTC_NSS
		,TGT.FTC_CODIGO_RES_OPER = SRC.FTC_CODIGO_RES_OPER
		,TGT.FTC_DIAG_PROCESAR = SRC.FTC_DIAG_PROCESAR
		,TGT.FTC_TIPO_ARCH = SRC.FTC_TIPO_ARCH
		,TGT.FTC_ESTATUS = SRC.FTC_ESTATUS
		,TGT.FTN_MOTIVO_RECHAZO = SRC.FTN_MOTIVO_RECHAZO
		,TGT.FTD_FEH_ACT = SRC.FTD_FEH_ACT
		,TGT.FCC_USU_ACT = SRC.FCC_USU_ACT
		



