SELECT FTC_CODIGO_RES_OPER
      ,FTC_DIAG_PROCESAR
      ,FTC_TIPO_ARCH
      ,FTC_ESTATUS
      ,FTN_MOTIVO_RECHAZO
      ,FTD_FEH_CRE
      ,FTD_FEH_ACT
FROM PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE
WHERE FTC_FOLIO ='#sr_folio#'
FETCH FIRST 20 ROWS ONLY