------- UPDATE CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_FOVISSSTE
WITH ORIG AS(
	SELECT  
		FTC_CURP,
		TRIM(FTC_CURP) AS FTC_CURP_ORIG
	FROM  
		PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE
	WHERE 
		FTC_FOLIO = '#sr_folio#'
		AND FTC_ESTATUS= '1' --'#sr_id_est_reg#'
		AND FTC_TIPO_ARCH = '01' --'#sr_tipo_arch_original#'
)
SELECT
	FTC_FOLIO
	,FOV.FTC_CURP
	,(CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) AS FTN_COIN_PROCESAR 
	,(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_ACT  
	,'DATABRICKS' AS FCC_USU_ACT
	,FTN_ID_ARCHIVO
FROM 
	CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_FOVISSSTE FOV
LEFT JOIN
	ORIG ORI
	ON
	ORI.FTC_CURP = FOV.FTC_CURP
WHERE 
	FTN_ID_ARCHIVO = '#sr_id_archivo#'
	AND FTC_FOLIO = '#sr_folio#'
	AND FTC_TIPO_ARCH = '#sr_tipo_archivo#'



