------- UPDATE PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE
MERGE INTO PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE TGT
USING (
    SELECT DISTINCT
        FTC_CODIGO_RES_OPER
      ,FTC_DIAG_PROCESAR
      ,FTC_TIPO_ARCH
      ,FTC_ESTATUS  -----  aqui viene seteado a 1
      ,FTN_MOTIVO_RECHAZO
      ,FTC_FOLIO
      ,FTN_CONTA_SERV
    FROM CIERREN_DATAUX.TTAFOTRAS_TRANS_FOVISSSTE_AUX
    WHERE FTC_FOLIO = '#sr_folio#'
) SRC
ON (
    TGT.FTC_FOLIO = SRC.FTC_FOLIO
	AND TGT.FTN_CONTA_SERV = SRC.FTN_CONTA_SERV
)
WHEN MATCHED THEN
    UPDATE SET
		TGT.FTC_CODIGO_RES_OPER = SRC.FTC_CODIGO_RES_OPER
		,TGT.FTC_DIAG_PROCESAR = SRC.FTC_DIAG_PROCESAR
        ,TGT.FTC_TIPO_ARCH = SRC.FTC_TIPO_ARCH
        ,TGT.FTC_ESTATUS = SRC.FTC_ESTATUS
        ,TGT.FTN_MOTIVO_RECHAZO = SRC.FTN_MOTIVO_RECHAZO



