------- UPDATE CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_FOVISSSTE
WITH ORIG AS(
	SELECT  
		FTC_CURP,
		TRIM(FTC_CURP) AS FTC_CURP_ORIG
	FROM  
		PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE
	WHERE 
		FTC_FOLIO = '#sr_folio#'
		AND FTC_ESTATUS= '1' --'#sr_id_est_reg#'
		AND FTC_TIPO_ARCH = '01' --'#sr_tipo_arch_original#'
)
SELECT
	TO_CHAR(CAST(FTD_FEH_CRE AS TIMESTAMP),'YYYY-MM-DD HH24:MI:SS') AS FECHA_CARGA
	,'02' AS DETALLE
	,FTC_NSS_TRABA AS NSS
	,FOV.FTC_CURP AS CURP
	,CASE WHEN (CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) = 0 THEN 'Registro No Coincidentes contra el archivo de Recepcion: ' || '#sr_folio#' ELSE 'Registro Coincidentes contra el archivo de Recepcion: ' || '#sr_folio#' END AS  VALIDACION 
	,CASE WHEN (CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) = 0 THEN '3857' ELSE '' END COD_ERROR
	,CASE WHEN (CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) = 0 THEN 'Registro No Coincidente' ELSE '' END AS DESC_ERROR 
	,FTN_ID_ARCHIVO
FROM 
	CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_FOVISSSTE FOV
LEFT JOIN
	ORIG ORI
	ON
	ORI.FTC_CURP = FOV.FTC_CURP
WHERE 
	FTN_ID_ARCHIVO = '#sr_id_archivo#'
	AND FTC_FOLIO = '#sr_folio#'
	AND FTC_TIPO_ARCH = '#sr_tipo_archivo#'



