SELECT 
	TRIM(SUBSTR(FTC_LINEA,1,2))FTC_TIPO_REG
	,TRIM(SUBSTR(FTC_LINEA,3,10))FTN_CONTA_SERV
	,TRIM(SUBSTR(FTC_LINEA,13,3))FTC_CVE_ENTIDAD_EMI_MV
	,TO_DATE(SUBSTR(FTC_LINEA,17,8),'yyyymmdd') FTD_FEH_MOVIMIENTO
	,TRIM(SUBSTR(FTC_LINEA,25,18)) FTC_CURP
	,TRIM(SUBSTR(FTC_LINEA,51,11))FTC_NSS_TRABA
	,'#sr_folio#' AS FTC_FOLIO
	,TRUNC(CURRENT_TIMESTAMP AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_PRESEN
	,'#sr_subproceso#' AS FCN_ID_SUBPROCESO
	,'#sr_id_archivo#' AS FTN_ID_ARCHIVO
	,TRIM(SUBSTR(FTC_LINEA,170,2)) AS FTC_CODIGO_RES_OPER
	,TRIM(SUBSTR(FTC_LINEA,172,3)) as FTC_DIAGNOS_PROCE
	,'#sr_tipo_archivo#' AS FTC_TIPO_ARCH
	,'DATABRICKS' AS FTC_USU_CRE
	,(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_CRE
FROM  
	CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO 
WHERE   
	SUBSTR(FTC_LINEA,1,2) =  '02'
AND
	FTN_ID_ARCHIVO = '#sr_id_archivo#'






