------- UPDATE CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_FOVISSSTE
MERGE INTO CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_FOVISSSTE TGT
USING (
    SELECT DISTINCT
        FTC_FOLIO
				,FTC_CURP
				,FTN_COIN_PROCESAR 
				,FTD_FEH_ACT  
				,FCC_USU_ACT
				,FTN_ID_ARCHIVO
    FROM CIERREN_DATAUX.TTAFOTRAS_ETL_TRANSF_FOVISSSTE_AUX
    WHERE FTC_FOLIO = '#sr_folio#'
) SRC
ON (
    TGT.FTC_FOLIO = SRC.FTC_FOLIO
    AND TGT.FTC_CURP = SRC.FTC_CURP
	AND TGT.FTN_ID_ARCHIVO = SRC.FTN_ID_ARCHIVO
)
WHEN MATCHED THEN
    UPDATE SET
		TGT.FTN_COIN_PROCESAR = SRC.FTN_COIN_PROCESAR
		,TGT.FTD_FEH_ACT = SRC.FTD_FEH_ACT
        ,TGT.FCC_USU_ACT = SRC.FCC_USU_ACT



