------- UPDATE CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_FOVISSSTE
/*mod 05122025*/
WITH ORIG AS(
	SELECT  
		FTC_CURP,
		TRIM(FTC_CURP) AS FTC_CURP_ORIG
	FROM  
		PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE
	WHERE 
		FTC_FOLIO = '#sr_folio#'
		AND FTC_ESTATUS= '1' --'#sr_id_est_reg#'
		AND FTC_TIPO_ARCH = '01' --'#sr_tipo_arch_original#'
)
SELECT
	FTC_NSS_TRABA AS FTC_NSS
	,FTC_CODIGO_RES_OPER
	,FTC_FOLIO 
	,FOV.FTC_CURP AS FTC_CURP
	--,'#sr_tipo_archivo#' AS FTC_TIPO_ARCH_REJ
	,FTD_FEH_CRE
	,'#sr_tipo_archivo#' AS FTC_TIPO_ARCH 
	,CASE WHEN (CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) = 1 AND FTC_CODIGO_RES_OPER = '02' THEN '0' ELSE '1' END AS FTC_ESTATUS 
	,CASE WHEN ((CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) = 1 AND FTC_CODIGO_RES_OPER = '02') OR (CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) = 0 THEN '99' ELSE NULL END AS FTN_MOTIVO_RECHAZO 
	,(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_ACT  
	,'DATABRICKS' AS FCC_USU_ACT
	--,(CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) AS FTN_COIN_PROCESAR ----------------------------------------------------------------------
	,FTC_DIAGNOS_PROCE AS FTC_DIAG_PROCESAR
	--,'02' AS DETALLE----------------------------------------------------------------------------------------------------------------------------------------
	--,CASE WHEN (CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) = 0 THEN 'Registro No Coincidentes contra el archivo de Recepcion: ' || '#sr_folio#' ELSE 'Registro Coincidentes ccontra el archivo de Recepcion: ' || '#sr_folio#' END AS  VALIDACION 
	--,CASE WHEN (CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) = 0 THEN '#sr_codigo_error#' ELSE '' END COD_ERROR
	--,CASE WHEN (CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) = 0 THEN 'Registro No Coincidente' ELSE '' END AS DESC_ERROR 
	--,FTN_ID_ARCHIVO
FROM 
	CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_FOVISSSTE FOV
LEFT JOIN
	ORIG ORI
	ON
	ORI.FTC_CURP = FOV.FTC_CURP
WHERE 
	FTN_ID_ARCHIVO = '#sr_id_archivo#'
	AND FTC_FOLIO = '#sr_folio#'
	AND FTC_TIPO_ARCH = '#sr_tipo_archivo#'
	AND (CASE WHEN ORI.FTC_CURP_ORIG IS NULL THEN 0 ELSE 1 END) = 1

