 SELECT 
 	M.FTC_FOLIO_BITACORA
 	,M.FTN_CTA_AFORE 
 	,CURRENT_DATE AS FTD_ACTU_ESTA
 	,(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_ACT
 	,'DATABRICKS' AS FCC_USU_ACT
 	,CASE 
	    WHEN TRIM(C.FCC_VALOR_IND) = 2 THEN NULL --antes 530
	    WHEN TRIM(C.FCC_VALOR_IND) = 3 THEN NULL --antes 533
	    WHEN C.FCC_VALOR_IND = 1 OR C.FCC_VALOR_IND = 4 THEN NULL
	    ELSE NULL --antes 678
	END AS FTN_MOTI_RECH
 	,CASE 
        WHEN C.FCC_VALOR_IND = 2 OR C.FCC_VALOR_IND = 3 THEN 1 --antes 0
        WHEN C.FCC_VALOR_IND = 1 OR C.FCC_VALOR_IND = 4 THEN 1
        ELSE 1 --antes 0
    END AS FTC_ESTA_REGI
FROM 
    PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO M
INNER JOIN
	CIERREN.TTAFOGRAL_IND_CTA_INDV C 
	ON 
	M.FTN_CTA_AFORE = C.FTN_NUM_CTA_INVDUAL 
    AND M.FTC_FOLIO_BITACORA = '#sr_folio#'
    AND M.FTC_ESTA_REGI = '#ind_vigencia#' 
    AND C.FFN_ID_CONFIG_INDI = '#config_indi#' 
    AND C.FTC_VIGENCIA = '#ind_vigencia#' 