MERGE INTO PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO  TGT
USING (
    SELECT DISTINCT
        FTC_FOLIO_BITACORA,
        FTN_CTA_AFORE,
        FTD_ACTU_ESTA,
        FTD_FEH_ACT,
        FCC_USU_ACT,
        FTN_MOTI_RECH,
        FTC_ESTA_REGI
    FROM CIERREN_DATAUX.TTCRXGRAL_MARCA_DESMARCA_INFO_AUX
    WHERE FTC_FOLIO_BITACORA = '#sr_folio#'
) SRC
ON (
    TGT.FTC_FOLIO_BITACORA = SRC.FTC_FOLIO_BITACORA
    AND TGT.FTN_CTA_AFORE = SRC.FTN_CTA_AFORE
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTD_ACTU_ESTA   = SRC.FTD_ACTU_ESTA,
        TGT.FTD_FEH_ACT     = SYSDATE,
        TGT.FCC_USU_ACT     = 'DATABRICKS',
        TGT.FTN_MOTI_RECH   = SRC.FTN_MOTI_RECH,
        TGT.FTC_ESTA_REGI   = SRC.FTC_ESTA_REGI
 