SELECT
      FTC_FOLIO_BITACORA AS FTC_FOLIO,
      #SR_PROCESO# AS FCN_ID_PROCESO,
      FCN_ID_SUBPROCESO AS FCN_ID_PROCESO,
      SUM( ACEPTADOS) AS FLN_REG_ACEPTADOS, 
      SUM(RECHAZADOS) AS FLN_REG_RECHAZADOS,
      #SR_USUARIO# AS FLC_USU_REG,
      CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FLD_FEC_REG
      --SUM(ACEPTADOS)+SUM(RECHAZADOS) AS FLN_TOTAL_REGISTROS, 
      --SUM(MONTO_ACEPTADO)+SUM(MONTO_RECHAZADO) AS TOTALMONTO,
      --SUM(MONTO_ACEPTADO) AS MONTO_ACEPTADO,
      --SUM(MONTO_RECHAZADO) AS MONTO_RECHAZADO
  FROM (
        SELECT DISTINCT FTC_FOLIO_BITACORA,FCN_ID_SUBPROCESO,
               MONTO,
               SUM(CASE WHEN FTC_ESTA_REGI=1 THEN NUMERO ELSE 0 END) AS ACEPTADOS,
               SUM(CASE WHEN FTC_ESTA_REGI=0 THEN NUMERO ELSE 0 END) RECHAZADOS,
               SUM(CASE WHEN FTC_ESTA_REGI=1 THEN MONTO ELSE 0 END) MONTO_ACEPTADO,
               CASE WHEN FTC_ESTA_REGI=0 THEN MONTO ELSE 0 END MONTO_RECHAZADO
          FROM (
                SELECT FTC_FOLIO AS FTC_FOLIO_BITACORA
                      ,FCN_ID_SUBPROCESO
                      ,0 AS MONTO
                      ,FTC_ESTATUS AS FTC_ESTA_REGI
                      ,COUNT(*) OVER (PARTITION BY FTC_ESTATUS) NUMERO
                  FROM PROCESOS.TTAFOTRAS_DESMARCA_FOVST
                 WHERE FTC_FOLIO = '#SR_FOLIO#'
                   AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#)
        )
GROUP BY
      FTC_FOLIO_BITACORA,
      FCN_ID_SUBPROCESO
