SELECT
    FTC_FOLIO_BITACORA AS FTC_FOLIO,
    #SR_PROCESO# AS FCN_ID_PROCESO,
    FCN_ID_SUBPROCESO,
    SUM(ACEPTADOS) AS FLN_REG_ACEPTADOS, 
    SUM(RECHAZADOS) AS FLN_REG_RECHAZADOS,
    SUM(ACEPTADOS) + SUM(RECHAZADOS) AS FLN_TOTAL_REGISTROS, 
    CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) 
    --CAST(from_utc_timestamp(current_timestamp, 'America/Mexico_City') AS TIMESTAMP)
    --from_utc_timestamp(current_timestamp(), 'America/Mexico_City')
    AS FLD_FEC_REG,
    '#SR_USUARIO#' AS FLC_USU_REG
FROM (
    SELECT DISTINCT FTC_FOLIO_BITACORA, FCN_ID_SUBPROCESO,
           CASE WHEN FTC_ESTA_REGI = 1 THEN NUMERO ELSE 0 END AS ACEPTADOS,
           CASE WHEN FTC_ESTA_REGI = 0 THEN NUMERO ELSE 0 END AS RECHAZADOS
    FROM (
        SELECT FTC_FOLIO_BITACORA, FTN_ID_SUBP AS FCN_ID_SUBPROCESO,
               FTC_ESTA_REGI,
               COUNT(*) OVER (PARTITION BY FTC_ESTA_REGI) AS NUMERO
        FROM PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
        WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'
          AND FTN_ID_SUBP = #SR_SUBPROCESO#
    )
)
GROUP BY FTC_FOLIO_BITACORA, FCN_ID_SUBPROCESO