SELECT
    #SR_FOLIO# AS FTC_FOLIO,
    81 AS FCN_ID_SIEFORE,
    '0' AS FFN_ID_CONCEPTO_IMP,
    '#SR_USUARIO#' AS FTC_USU_REG,
    CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FTD_FEC_REG,
    SUM(ACEPTADOS)+SUM(RECHAZADOS) AS FTN_NUM_REG,
    SUM(RECHAZADOS) AS FTN_NUM_REG_RECH,
    SUM(MONTO_ACEPTADO) AS FTN_IMPORTE_ACEP_PESOS,
    SUM(MONTO_ACEPTADO) AS FTN_IMPORTE_ACEP_AIVS,
    SUM(MONTO_RECHAZADO) AS FTN_IMPORTE_RECH_PESOS,
    SUM(MONTO_RECHAZADO) AS FTN_IMPORTE_RECH_AIVS   
  FROM (
        SELECT DISTINCT FTC_FOLIO_BITACORA,FCN_ID_SUBPROCESO,
               MONTO,
               CASE WHEN FTC_ESTA_REGI=1 THEN NUMERO ELSE 0 END ACEPTADOS,
               CASE WHEN FTC_ESTA_REGI=0 THEN NUMERO ELSE 0 END RECHAZADOS,
               CASE WHEN FTC_ESTA_REGI=1 THEN MONTO ELSE 0 END MONTO_ACEPTADO,
               CASE WHEN FTC_ESTA_REGI=0 THEN MONTO ELSE 0 END MONTO_RECHAZADO
          FROM (
                SELECT FTC_FOLIO_BITACORA,FTN_ID_SUBP AS FCN_ID_SUBPROCESO,
                       FTN_SALDO_97+FTN_SALDO_92 AS MONTO,
                       FTC_ESTA_REGI,
                       COUNT(*) OVER (PARTITION BY FTC_ESTA_REGI) NUMERO
                  FROM PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
                 WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'
                   AND FTN_ID_SUBP = #SR_SUBPROCESO#)
        )
GROUP BY FTC_FOLIO_BITACORA,FCN_ID_SUBPROCESO