SELECT
    INF.FTC_FOLIO_BITACORA AS FTC_FOLIO,
    SUM(SAL.FTN_MONTO_PESOS) AS FTN_IMPORTE_RECH_PESOS_PRO,
    SUM(SAL.FTN_SDO_AIVS) AS FTN_IMPORTE_RECH_AIVS_PRO,
    NVL(COUNT(*), 0) AS FTN_NUM_REG_RECH_PRO,
    CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FTD_FEH_ACT
FROM
    PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO INF
LEFT OUTER JOIN
    PROCESOS.TTSISGRAL_SUF_SALDOS SAL
    ON INF.FTN_CTA_AFORE = SAL.FTN_NUM_CTA_INVDUAL
    AND INF.FTN_CONTA_SERV = SAL.FTN_CONTA_SERV
    AND INF.FTC_FOLIO_BITACORA = SAL.FTC_FOLIO_BITACORA
    AND INF.FTN_ID_SUBP = SAL.FTN_ID_SUBP
WHERE
    INF.FTC_FOLIO_BITACORA = '#SR_FOLIO#'
    AND INF.FTN_ID_SUBP = #SR_SUBPROCESO#
    AND INF.FTC_TIPO_ARCH = #TIPO_ARCH#
GROUP BY
    INF.FTC_FOLIO_BITACORA
