SELECT
      #SR_FOLIO# AS FTC_FOLIO,
      81 AS FCN_ID_SIEFORE,
      '0' AS FFN_ID_CONCEPTO_IMP,
      #SR_USUARIO# AS FLC_USU_REG,
      CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FLD_FEC_REG
      --SUM( ACEPTADOS) AS ACEPTADOS, 
      SUM(RECHAZADOS) AS FTN_NUM_REG_RECH, 
      SUM(ACEPTADOS)+SUM(RECHAZADOS) AS FTN_NUM_REG, 
      --SUM(MONTO_ACEPTADO)+SUM(MONTO_RECHAZADO) AS TOTALMONTO,
      SUM(MONTO_ACEPTADO) AS FTN_IMPORTE_ACEP_AIVS,
      SUM(MONTO_RECHAZADO) AS FTN_IMPORTE_RECH_AIVS,
      SUM(MONTO_ACEPTADO) AS FTN_IMPORTE_ACEP_PESOS,
      SUM(MONTO_RECHAZADO) AS FTN_IMPORTE_ACEP_PESOS
  FROM (
        SELECT DISTINCT FTC_FOLIO_BITACORA,FCN_ID_SUBPROCESO,
               MONTO,
               SUM(CASE WHEN FTC_ESTA_REGI=1 THEN NUMERO ELSE 0 END) AS ACEPTADOS,
               SUM(CASE WHEN FTC_ESTA_REGI=0 THEN NUMERO ELSE 0 END) RECHAZADOS,
               SUM(CASE WHEN FTC_ESTA_REGI=1 THEN MONTO ELSE 0 END) MONTO_ACEPTADO,
               CASE WHEN FTC_ESTA_REGI=0 THEN MONTO ELSE 0 END MONTO_RECHAZADO
          FROM (
                SELECT FTC_FOLIO AS FTC_FOLIO_BITACORA
                      ,FCN_ID_SUBPROCESO
                      ,0 AS MONTO
                      ,FTC_ESTATUS AS FTC_ESTA_REGI
                      ,COUNT(*) OVER (PARTITION BY FTC_ESTATUS) NUMERO
                  FROM PROCESOS.TTAFOTRAS_DESMARCA_FOVST
                 WHERE FTC_FOLIO = '#SR_FOLIO#'
                   AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#)
        )
GROUP BY
      FTC_FOLIO_BITACORA,
      FCN_ID_SUBPROCESO
