
SELECT
  FCN_ID_TIPO_SUBCTA,
  FTC_FOLIO,
  FTC_FOLIO_REL,
  FCN_ID_SIEFORE,
  FTF_MONTO_PESOS,
  FTF_MONTO_ACCIONES,
  FCN_ID_VALOR_ACCION,
  FTN_NUM_CTA_INVDUAL,
  FTN_ID_SEMAFORO_MOV,
  FTD_FEH_LIQUIDACION,
  CAST(16 AS NUMBER(10)) AS FTD_ID_ESTATUS_MOV,
  FTN_ID_MARCA,
  FCN_ID_TIPO_MOV,
  FCD_FEH_CRE,
  FCC_USU_CRE,
  FCD_FEH_ACT,
  FCC_USU_ACT,
  FCN_ID_CONCEPTO_MOV,
  FNN_ID_REFERENCIA
FROM CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS
WHERE FTC_FOLIO = '#sr_folio#'
  AND FTN_ID_SEMAFORO_MOV IN (190,192)
  AND FTN_MOV_GENERADO <> 1
  AND SUBSTR(NVL(FCC_TABLA_NCI_MOV,' '),1,3) = 'SAR'
UNION ALL
SELECT
  FCN_ID_TIPO_SUBCTA,
  FTC_FOLIO,
  FTC_FOLIO_REL,
  FCN_ID_SIEFORE,
  FTF_MONTO_PESOS,
  FTF_MONTO_ACCIONES,
  FCN_ID_VALOR_ACCION,
  FTN_NUM_CTA_INVDUAL,
  FTN_ID_SEMAFORO_MOV,
  FTD_FEH_LIQUIDACION,
  CAST(16 AS NUMBER(10)) AS FTD_ID_ESTATUS_MOV,
  FTN_ID_MARCA,
  FCN_ID_TIPO_MOV,
  FCD_FEH_CRE,
  FCC_USU_CRE,
  FCD_FEH_ACT,
  FCC_USU_ACT,
  FCN_ID_CONCEPTO_MOV,
  FNN_ID_REFERENCIA
FROM CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS
WHERE FTC_FOLIO_REL = '#sr_folio#'
  AND FTN_ID_SEMAFORO_MOV IN (190,192)
  AND FTN_MOV_GENERADO <> 1
  AND SUBSTR(NVL(FCC_TABLA_NCI_MOV,' '),1,3) = 'SAR'