       SELECT        
       FTN_ID_MOV,
FCN_ID_TIPO_SUBCTA,
FTC_FOLIO,
FTC_FOLIO_REL,
FCN_ID_SIEFORE,
FTF_MONTO_PESOS,
FTF_MONTO_ACCIONES,
FCN_ID_VALOR_ACCION,
FTN_NUM_CTA_INVDUAL,
FTN_ID_SEMAFORO_MOV,
FTD_FEH_LIQUIDACION,
16 AS FTD_ID_ESTATUS_MOV,
FTN_ID_MARCA,
FCN_ID_TIPO_MOV,
FCD_FEH_CRE,
FCC_USU_CRE,
SYSDATE AS FCD_FEH_ACT,
'ACREDITACION_DATABRICKS' AS FCC_USU_ACT,
FCN_ID_CONCEPTO_MOV,
FCC_TABLA_NCI_MOV,
FNN_ID_REFERENCIA,
FTN_ID_ERROR_VAL,
1  AS FTN_MOV_GENERADO,
FTN_REG_ACREDITADO,
FTC_ID_INSTANCIA
  FROM CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS t
 WHERE t.FTN_ID_SEMAFORO_MOV IN (190,192)
   AND t.FTN_ID_ERROR_VAL IS NULL
   AND (
         (
           t.FTC_FOLIO_REL = '#sr_folio#'
           AND EXISTS (
                SELECT 1
                  FROM CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS x
                 WHERE x.FTC_FOLIO_REL = '#sr_folio#'
                   AND x.FTN_ID_SEMAFORO_MOV IN (190,192)
                   AND x.FTN_ID_ERROR_VAL IS NULL
               )
         )
         OR
         (
           t.FTC_FOLIO = '#sr_folio#'
           AND NOT EXISTS (
                SELECT 1
                  FROM CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS x
                 WHERE x.FTC_FOLIO_REL = '#sr_folio#'
                   AND x.FTN_ID_SEMAFORO_MOV IN (190,192)
                   AND x.FTN_ID_ERROR_VAL IS NULL
               )
         )
       )