SELECT
    (SELECT NVL(MAX(FTN_ID_BAL_MOV), 0) FROM CIERREN.TTAFOGRAL_BALANCE_MOVS) + 
    ROW_NUMBER() OVER (
      ORDER BY
        M.FTC_FOLIO,
        M.FTC_FOLIO_REL,
        M.FTN_NUM_CTA_INVDUAL
    ) AS FTN_ID_BAL_MOV,
    FTC_FOLIO,
    FTC_FOLIO_REL,
    CASE WHEN FCN_ID_TIPO_MOV = 180 THEN 0
         WHEN FCN_ID_TIPO_MOV = 181 THEN FTF_MONTO_PESOS
         ELSE 0 END AS FTN_DISP_PESOS,
    CASE WHEN FCN_ID_TIPO_MOV = 180 THEN 0
         WHEN FCN_ID_TIPO_MOV = 181 THEN FTF_MONTO_ACCIONES
         ELSE 0 END AS FTN_DISP_ACCIONES,
    CASE WHEN FCN_ID_TIPO_MOV = 180 THEN 0
         WHEN FCN_ID_TIPO_MOV = 181 THEN FTF_MONTO_PESOS * -1
         ELSE 0 END AS FTN_PDTE_PESOS,
    CASE WHEN FCN_ID_TIPO_MOV = 180 THEN 0
         WHEN FCN_ID_TIPO_MOV = 181 THEN FTF_MONTO_ACCIONES * -1
         ELSE 0 END AS FTN_PDTE_ACCIONES,
    CASE WHEN FCN_ID_TIPO_MOV = 180 THEN FTF_MONTO_PESOS * -1
         WHEN FCN_ID_TIPO_MOV = 181 THEN 0
         ELSE 0 END AS FTN_COMP_PESOS,
    CASE WHEN FCN_ID_TIPO_MOV = 180 THEN FTF_MONTO_ACCIONES * -1
         WHEN FCN_ID_TIPO_MOV = 181 THEN 0
         ELSE 0 END AS FTN_COMP_ACCIONES,
    CASE WHEN FCN_ID_TIPO_MOV = 180 THEN FTF_MONTO_PESOS * -1
         WHEN FCN_ID_TIPO_MOV = 181 THEN FTF_MONTO_PESOS
         ELSE 0 END AS FTN_DIA_PESOS,
    CASE WHEN FCN_ID_TIPO_MOV = 180 THEN FTF_MONTO_ACCIONES * -1
         WHEN FCN_ID_TIPO_MOV = 181 THEN FTF_MONTO_ACCIONES
         ELSE 0 END AS FTN_DIA_ACCIONES,
    FTN_NUM_CTA_INVDUAL AS FTC_NUM_CTA_INVDUAL,
    NULL AS FTN_ORIGEN_APORTACION,
    FCN_ID_TIPO_SUBCTA,
    NVL(FCN_ID_SIEFORE, 0) AS FCN_ID_SIEFORE,
    FCN_ID_VALOR_ACCION,
    FTD_FEH_LIQUIDACION,
    FCN_ID_TIPO_MOV,
    FCN_ID_CONCEPTO_MOV,
    SUBSTR(FCC_TABLA_NCI_MOV, 1, 5) AS FCC_TABLA_NCI_MOV,
    (FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FCD_FEH_CRE,
    'DATABRICKS' AS FCC_USU_CRE,
    NULL AS FCD_FEH_ACT,
    NULL AS FCC_USU_ACT,
    NVL(FTN_DEDUCIBLE, 0) AS FTN_DEDUCIBLE,
    FCN_ID_PLAZO
FROM (
  WITH MOVS AS (
SELECT  FTC_FOLIO,FTC_FOLIO_REL,FTF_MONTO_PESOS,FTF_MONTO_ACCIONES,FTN_NUM_CTA_INVDUAL,FCN_ID_TIPO_SUBCTA,FCN_ID_SIEFORE,FCN_ID_VALOR_ACCION,FTD_FEH_LIQUIDACION,
FCN_ID_TIPO_MOV,FCN_ID_CONCEPTO_MOV,FCC_TABLA_NCI_MOV,FTN_ID_SEMAFORO_MOV
from  CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS WHERE FTC_FOLIO = '#sr_folio#' AND FTN_ID_SEMAFORO_MOV IN (190,192) AND FTN_MOV_GENERADO = 0
UNION ALL
SELECT  FTC_FOLIO,FTC_FOLIO_REL,FTF_MONTO_PESOS,FTF_MONTO_ACCIONES,FTN_NUM_CTA_INVDUAL,FCN_ID_TIPO_SUBCTA,FCN_ID_SIEFORE,FCN_ID_VALOR_ACCION,FTD_FEH_LIQUIDACION,
FCN_ID_TIPO_MOV,FCN_ID_CONCEPTO_MOV,FCC_TABLA_NCI_MOV,FTN_ID_SEMAFORO_MOV
from  CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS WHERE FTC_FOLIO_REL = '#sr_folio#' AND FTN_ID_SEMAFORO_MOV IN (190,192) AND FTN_MOV_GENERADO = 0
)
SELECT  M.FTC_FOLIO,M.FTC_FOLIO_REL,FTF_MONTO_PESOS,FTF_MONTO_ACCIONES,FTN_NUM_CTA_INVDUAL,M.FCN_ID_TIPO_SUBCTA,M.FCN_ID_SIEFORE,FCN_ID_VALOR_ACCION,FTD_FEH_LIQUIDACION,
FCN_ID_TIPO_MOV,M.FCN_ID_CONCEPTO_MOV,FCC_TABLA_NCI_MOV,FTN_ID_SEMAFORO_MOV,T.FCN_ID_PLAZO,FTN_DEDUCIBLE
from  MOVS M, CIERREN.TCCRXGRAL_TIPO_SUBCTA T,CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV C
WHERE M.FCN_ID_TIPO_SUBCTA=T.FCN_ID_TIPO_SUBCTA
AND M.FCN_ID_CONCEPTO_MOV=C.FFN_ID_CONCEPTO_MOV
AND C.FFB_VIGENCIA = 1
) M
WHERE  M.FTN_ID_SEMAFORO_MOV IN (190,192)