MERGE INTO PROCESOS.TTAFOAE_AEIM ORI
USING (
  SELECT *
  FROM (
    SELECT
      FTC_NOMBRE_COMPLETO_ARCH,
      FTN_NSS_ARCH,
      FTC_RFC_ARCH,
      FNC_REG_PATRONAL_IMSS,
      FTC_FOLIO,
      FTC_NOMBRE_ARCH,
      FTC_AP_PATERNO_ARCH,
      FTC_AP_MATERNO_ARCH,
      FTN_NUM_CTA_INVDUAL,
      FTN_ESTATUS_REG,
      FTN_MOTIVO,
      FTD_FEH_ULTIMO_USO,
      CAST(CURRENT_TIMESTAMP AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FTD_FEH_CRE,
      '#SR_USUARIO#' AS FTC_USU_CRE,
      CAST(CURRENT_TIMESTAMP AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FTD_FEH_ACT,
      '#SR_USUARIO#' AS FTC_USU_ACT,
      FTC_CLAVE_ENT_RECEP,
      ROW_NUMBER() OVER (
        PARTITION BY
          FTC_NOMBRE_COMPLETO_ARCH,
          FTN_NSS_ARCH,
          FTC_RFC_ARCH,
          FNC_REG_PATRONAL_IMSS
        ORDER BY FTD_FEH_ULTIMO_USO DESC
      ) AS RN
    FROM CIERREN_DATAUX.TTSISGRAL_ETL_AEIM_AUX
    WHERE FTC_FOLIO = '#SR_FOLIO#'
      AND FTN_ESTATUS_REG > 0
      AND FTN_ESTATUS_REG <> 560
  )
  WHERE RN = 1
) AUX
ON (
  ORI.FTC_NOMBRE_COMPLETO_ARCH = AUX.FTC_NOMBRE_COMPLETO_ARCH
  AND ORI.FTN_NSS_ARCH = AUX.FTN_NSS_ARCH
  AND ORI.FTC_RFC_ARCH = AUX.FTC_RFC_ARCH
  AND ORI.FNC_REG_PATRONAL_IMSS = AUX.FNC_REG_PATRONAL_IMSS
)
WHEN MATCHED THEN 
  UPDATE SET 
    ORI.FTC_FOLIO = AUX.FTC_FOLIO,
    ORI.FTC_NOMBRE_ARCH = AUX.FTC_NOMBRE_ARCH,
    ORI.FTC_AP_PATERNO_ARCH = AUX.FTC_AP_PATERNO_ARCH,
    ORI.FTC_AP_MATERNO_ARCH = AUX.FTC_AP_MATERNO_ARCH,
    ORI.FTN_NUM_CTA_INVDUAL = AUX.FTN_NUM_CTA_INVDUAL,
    ORI.FTN_ESTATUS_REG = AUX.FTN_ESTATUS_REG,
    ORI.FTN_MOTIVO = AUX.FTN_MOTIVO,
    ORI.FTD_FEH_ULTIMO_USO = AUX.FTD_FEH_ULTIMO_USO,
    ORI.FTD_FEH_CRE = AUX.FTD_FEH_CRE,
    ORI.FTC_USU_CRE = AUX.FTC_USU_CRE,
    ORI.FTD_FEH_ACT = AUX.FTD_FEH_ACT,
    ORI.FTC_USU_ACT = AUX.FTC_USU_ACT,
    ORI.FTC_CLAVE_ENT_RECEP = AUX.FTC_CLAVE_ENT_RECEP
WHEN NOT MATCHED THEN
  INSERT (
    FTC_NOMBRE_COMPLETO_ARCH, FTN_NSS_ARCH, FTC_RFC_ARCH, 
    FNC_REG_PATRONAL_IMSS, FTC_FOLIO, FTC_NOMBRE_ARCH, 
    FTC_AP_PATERNO_ARCH, FTC_AP_MATERNO_ARCH, FTN_NUM_CTA_INVDUAL, 
    FTN_ESTATUS_REG, FTN_MOTIVO, FTD_FEH_ULTIMO_USO, 
    FTD_FEH_CRE, FTC_USU_CRE, FTD_FEH_ACT, FTC_USU_ACT, 
    FTC_CLAVE_ENT_RECEP
  )
  VALUES (
    AUX.FTC_NOMBRE_COMPLETO_ARCH, AUX.FTN_NSS_ARCH, AUX.FTC_RFC_ARCH, 
    AUX.FNC_REG_PATRONAL_IMSS, AUX.FTC_FOLIO, AUX.FTC_NOMBRE_ARCH, 
    AUX.FTC_AP_PATERNO_ARCH, AUX.FTC_AP_MATERNO_ARCH, AUX.FTN_NUM_CTA_INVDUAL, 
    AUX.FTN_ESTATUS_REG, AUX.FTN_MOTIVO, AUX.FTD_FEH_ULTIMO_USO, 
    AUX.FTD_FEH_CRE, AUX.FTC_USU_CRE, AUX.FTD_FEH_ACT, AUX.FTC_USU_ACT, 
    AUX.FTC_CLAVE_ENT_RECEP
  )