SELECT 
   FTC_FOLIO
  ,FTC_NOMBRE_COMPLETO_ARCH
  ,FTN_NSS_ARCH
  ,FTC_NOMBRE_ARCH
  ,FTC_AP_PATERNO_ARCH
  ,FTC_AP_MATERNO_ARCH
  ,FTC_RFC_ARCH
  ,FNC_REG_PATRONAL_IMSS
  ,FTN_NUM_CTA_INVDUAL
  ,FTN_ESTATUS_REG
  ,FTN_MOTIVO
  ,nvl(FTD_FEH_ULTIMO_USO, CAST(CURRENT_TIMESTAMP AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP)) AS FTD_FEH_ULTIMO_USO
  ,FTC_CLAVE_ENT_RECEP
FROM CIERREN_ETL.TTSISGRAL_ETL_AEIM
WHERE FTC_FOLIO = '#SR_FOLIO#'
AND FTN_ESTATUS_REG IS NOT NULL
AND FTN_NUM_CTA_INVDUAL IS NOT NULL
ORDER BY FTC_NOMBRE_COMPLETO_ARCH,FTN_NSS_ARCH,FTC_RFC_ARCH,FNC_REG_PATRONAL_IMSS