MERGE INTO CIERREN_ETL.TTSISGRAL_ETL_AEIM ORI
USING (
    SELECT *
    FROM (
        SELECT 
            FTC_FOLIO,
            FTN_NSS_ARCH,
            FTC_RFC_ARCH,
            FTC_NOMBRE_COMPLETO_ARCH,
            FNC_REG_PATRONAL_IMSS,
            FTN_ESTATUS_REG,
            FTN_MOTIVO,
            FTD_FEH_ULTIMO_USO,
            ROW_NUMBER() OVER (
                PARTITION BY 
                    FTC_FOLIO,
                    FTN_NSS_ARCH,
                    FTC_RFC_ARCH,
                    FTC_NOMBRE_COMPLETO_ARCH,
                    FNC_REG_PATRONAL_IMSS
                ORDER BY FTD_FEH_ULTIMO_USO DESC
            ) AS RN
        FROM CIERREN_DATAUX.TTSISGRAL_ETL_AEIM_AUX
        WHERE FTC_FOLIO = '#SR_FOLIO#'
    )
    WHERE RN = 1
) AUX
ON (
    ORI.FTC_FOLIO = AUX.FTC_FOLIO
    AND ORI.FTN_NSS_ARCH = AUX.FTN_NSS_ARCH
    AND ORI.FTC_RFC_ARCH = AUX.FTC_RFC_ARCH
    AND ORI.FTC_NOMBRE_COMPLETO_ARCH = AUX.FTC_NOMBRE_COMPLETO_ARCH
    AND ORI.FNC_REG_PATRONAL_IMSS = AUX.FNC_REG_PATRONAL_IMSS
)
WHEN MATCHED THEN 
UPDATE SET
    ORI.FTN_ESTATUS_REG = AUX.FTN_ESTATUS_REG,
    ORI.FTN_MOTIVO = AUX.FTN_MOTIVO,
    ORI.FTD_FEH_ULTIMO_USO = AUX.FTD_FEH_ULTIMO_USO
