SELECT
   A.FTC_NOMBRE_COMPLETO_ARCH,
   A.FTN_NSS_ARCH,
   A.FTC_RFC_ARCH,
   A.FNC_REG_PATRONAL_IMSS,
   A.FTN_NUM_CTA_INVDUAL,        
   A.FTC_NOMBRE_BUC,
   A.FTC_AP_PATERNO_BUC,
   A.FTC_AP_MATERNO_BUC,
   A.FTC_RFC_BUC,
   A.FTC_FOLIO,
   A.FTC_NOMBRE_COMPLETO_SIN_PESOS,
   A.FTC_NOMBRE_COMPLETO_BUC,
   A.COMP_NOMBRES,
   A.COMP_FECHAS,
   C.CRITERIO,
   B.FTC_NOMBRE_HIST,
   B.FTC_AP_PATERNO_HIST,
   B.FTC_AP_MATERNO_ARCH_HIST,
   B.FTN_ESTATUS_REG_HIST,
   B.FTN_MOTIVO_HIST
FROM (
   -- Consulta 1 optimizada
   SELECT          
       FTC_NOMBRE_COMPLETO_ARCH,
       FTN_NSS_ARCH,
       FTC_RFC_ARCH,
       FNC_REG_PATRONAL_IMSS,
       FTN_NUM_CTA_INVDUAL,        
       FTC_NOMBRE_BUC,
       FTC_AP_PATERNO_BUC,
       FTC_AP_MATERNO_BUC,
       FTC_RFC_BUC,
       FTC_FOLIO,
       TRIM(REPLACE(FTC_NOMBRE_COMPLETO_ARCH,'$',' ')) AS FTC_NOMBRE_COMPLETO_SIN_PESOS,
       TRIM(FTC_AP_PATERNO_BUC || ' ' || FTC_AP_MATERNO_BUC || ' ' || FTC_NOMBRE_BUC) AS FTC_NOMBRE_COMPLETO_BUC,
       SYS.UTL_MATCH.JARO_WINKLER_SIMILARITY(
           TRIM(REPLACE(FTC_NOMBRE_COMPLETO_ARCH,'$',' ')),
           TRIM(FTC_AP_PATERNO_BUC || ' ' || FTC_AP_MATERNO_BUC || ' ' || FTC_NOMBRE_BUC)
       ) AS COMP_NOMBRES,
       CASE
           WHEN NVL(SUBSTR(FTC_RFC_ARCH,5,6), '000000') = NVL(SUBSTR(FTC_RFC_BUC,5,6), '000000') THEN 1
           ELSE 0
       END AS COMP_FECHAS
   FROM CIERREN_ETL.TTSISGRAL_ETL_AEIM
   WHERE FTC_FOLIO = '#SR_FOLIO#'
   AND FTN_ESTATUS_REG <> 559
) A
LEFT JOIN (
   -- Consulta 2 optimizada
   SELECT
       FTC_NOMBRE_COMPLETO_ARCH,
       FTN_NSS_ARCH,
       FTC_RFC_ARCH,
       FNC_REG_PATRONAL_IMSS,
       FTC_NOMBRE_ARCH AS FTC_NOMBRE_HIST,
       FTC_AP_PATERNO_ARCH AS FTC_AP_PATERNO_HIST,
       FTC_AP_MATERNO_ARCH AS FTC_AP_MATERNO_ARCH_HIST,
       FTN_ESTATUS_REG AS FTN_ESTATUS_REG_HIST,
       FTN_MOTIVO AS FTN_MOTIVO_HIST
   FROM PROCESOS.TTAFOAE_AEIM
) B
ON A.FTC_NOMBRE_COMPLETO_ARCH = B.FTC_NOMBRE_COMPLETO_ARCH
AND A.FTN_NSS_ARCH = B.FTN_NSS_ARCH
AND A.FTC_RFC_ARCH = B.FTC_RFC_ARCH
AND A.FNC_REG_PATRONAL_IMSS = B.FNC_REG_PATRONAL_IMSS
CROSS JOIN (
   -- Consulta de criterio optimizada
   SELECT TO_NUMBER(FFC_VALOR) AS CRITERIO  
   FROM PROCESOS.TFCRXGRAL_CAT_CONFIG  
   WHERE --FCN_ID_TIPO_CAT = 40 --Se modificó a petición de usuario
   FFN_ID_CAT_CONFIG =10
) C
ORDER BY
   A.FTC_NOMBRE_COMPLETO_ARCH,
   A.FTN_NSS_ARCH,
   A.FTC_RFC_ARCH,
   A.FNC_REG_PATRONAL_IMSS
