MERGE INTO
  PROCESOS.TTAFOAE_AEIM ORI
USING (
  SELECT
    FTC_NOMBRE_COMPLETO_ARCH,
    FTN_NSS_ARCH,
    FTC_RFC_ARCH,
    FNC_REG_PATRONAL_IMSS,
    FTD_FEH_ULTIMO_USO,
    CAST(CURRENT_TIMESTAMP AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FTD_FEH_ACT,
    '#SR_USUARIO#' FTC_USU_ACT
  FROM
    CIERREN_DATAUX.TTSISGRAL_ETL_AEIM_AUX
    WHERE FTC_FOLIO = '#SR_FOLIO#' 
    AND FTN_ESTATUS_REG < 0 
) AUX
ON
  (
        
        ORI.FTC_NOMBRE_COMPLETO_ARCH = AUX.FTC_NOMBRE_COMPLETO_ARCH
    AND ORI.FTN_NSS_ARCH = AUX.FTN_NSS_ARCH
    AND ORI.FTC_RFC_ARCH = AUX.FTC_RFC_ARCH
    AND ORI.FNC_REG_PATRONAL_IMSS = AUX.FNC_REG_PATRONAL_IMSS
  )
WHEN MATCHED THEN UPDATE SET
  ORI.FTD_FEH_ACT = AUX.FTD_FEH_ACT,
  ORI.FTC_USU_ACT = AUX.FTC_USU_ACT,
  ORI.FTD_FEH_ULTIMO_USO = AUX.FTD_FEH_ULTIMO_USO
