WITH BD_100_TRANS_REC_PORTA
AS
(
--BD_100_TRANS_REC_PORTA: The connector will use the following SELECT statement at runtime:

SELECT 
T.FTC_FOLIO,
T.FTN_NUM_CTA_INVDUAL,
T.FTC_FOLIO_PROCESAR,
T.FTC_NSS_IMSS,
T.FTC_APELLIDO_PATERNO,
T.FTC_APELLIDO_MATERNO,
T.FTC_NOMBRE,
T.FTC_CURP,
T.FTC_TIPO_OPERACION,
T.FTC_INSTITUTO_ORIGEN,
T.FTC_CREDITO,
S.FTN_MONTO_PESOS FTN_MONTO_PESOS_97,
S.FTN_SDO_AIVS FTN_SDO_AIVS_97,
S.FTN_MONTO_PESOS_92,
S.FTN_SDO_AIVS_92,
S.FTN_VALOR_AIVS,
T.FTD_FEH_CREDITO,
T.FTD_FEH_VAL_TRANSFERENCIA,
T.FTC_DIAGNOSTICO,
To_Number(T.FTC_MOTIVO_REC) AS FTN_MOTIVO_RECHAZO,
T.FTC_ESTATUS_OPE,
T.FTN_SUBPROCESO,
to_char(V.FCD_FEH_ACCION,'yyyymmdd') FCD_FEH_ACCION,
S.FTN_IND_SDO_DISP_VIV97,
S.FTN_IND_SDO_DISP_92,
S.FCN_ID_TIPO_SUBCTA_97,
S.FCN_ID_TIPO_SUBCTA_92,
CASE WHEN T.FTC_INSTITUTO_ORIGEN = 001 THEN T.FTC_NSS_IMSS ELSE T.FTC_CURP END NSS_CURP
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA T
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS S 
ON T.FTC_FOLIO=S.FTC_FOLIO_BITACORA AND T.FTN_NUM_CTA_INVDUAL=S.FTN_NUM_CTA_INVDUAL
AND T.FTN_SUBPROCESO=S.FTN_ID_SUBP  AND T.FTN_NO_LINEA = S.FTN_CONTA_SERV
LEFT JOIN CIERREN.TCAFOGRAL_VALOR_ACCION V ON S.FCN_ID_VALOR_ACCION=V.FCN_ID_VALOR_ACCION AND S.FCN_ID_REGIMEN = V.FCN_ID_REGIMEN
WHERE 1=1
AND T.FTC_FOLIO='#SR_FOLIO#' --  Párametrizado
AND T.FTN_SUBPROCESO = #SR_SUBPROCESO# --  Párametrizado

),
BD_200_MAP_NCI_RECHAZO AS
(
--BD_200_MAP_NCI_RECHAZO: The connector will use the following SELECT statement at runtime:

SELECT 
C.FTN_MOTIVO_RECHAZO,
lpad(nvl(I.TMN_CVE_ITGY,'000'),3,'0') TMN_CVE_ITGY --- Se toma este campo
FROM(
SELECT FCN_ID_CAT_CATALOGO AS TMN_CVE_NCI,
CASE 
WHEN FCN_ID_TIPO_CAT=3   THEN FCN_ID_CAT_CATALOGO ---RECHAZO PROCESO NCI
WHEN FCN_ID_TIPO_CAT=20  THEN FCN_ID_CAT_CATALOGO ---RECHAZO IDC
WHEN FCN_ID_TIPO_CAT=223 THEN TO_NUMBER(FCC_VALOR)---RECHAZO TRASPASOS
WHEN FCN_ID_TIPO_CAT=291 THEN TO_NUMBER(FCC_VALOR)---RECHAZO ESTADOS AFIL 
END FTN_MOTIVO_RECHAZO  --- Con este hace match  BD_200.FTN_MOTIVO_RECHAZO
FROM CIERREN.TCCRXGRAL_CAT_CATALOGO 
WHERE FCN_ID_TIPO_CAT IN (3,20,223,291)
)C
INNER JOIN CIERREN.TMSISGRAL_MAP_NCI_ITGY I 
ON C.TMN_CVE_NCI=I.TMN_CVE_NCI
WHERE I.TMC_USO='MOTIVO DE RECHAZO PARA PROCESAR DE TRP'
),
BD_400_LEE_ARCHIVO AS
(

--BD_400_LEE_ARCHIVO: The connector will use the following SELECT statement at runtime:

SELECT
 CASE WHEN Trim(SUBSTR(FTC_LINEA,204,3)) = 001 THEN Trim(SUBSTR(FTC_LINEA,53,11)) ELSE Trim(SUBSTR(FTC_LINEA,184,18)) END NSS_CURP  --- con este hace match BD_400.NSS_CURP
,Trim(SUBSTR(FTC_LINEA,207,10)) IdCreditoInf ---  Se toma este campo
,Trim(SUBSTR(FTC_LINEA,267,10)) IdCreditoFov --- Se toma este campo
FROM CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO 
WHERE SUBSTR(FTC_LINEA,1,2) = 2
AND FTN_ID_ARCHIVO = (SELECT DISTINCT(FTN_ID_ARCHIVO) 
FROM CIERREN_ETL.TTAFOTRAS_ETL_TRANS_REC_PORTA WHERE FTC_FOLIO = '#SR_FOLIO#')
),
DS_FECHAS_250 AS
(
----||  DS_250_FECHAS
SELECT
'#SR_FOLIO#' AS FTC_FOLIO ---- Con este hace match  DS_250.FTC_FOLIO   y tambien se genera por medio del servicio llegando parametrizado
 ,TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS FECHA_PRESENTACION
,TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'YYYYMMDD') FECHA_POSTERIOR
FROM (
    select FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES       = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),6,2)
        AND FTN_ANIO        = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1 
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 15 
group by TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'YYYYMMDD')
), TF_700
AS
(
SELECT
BD_100.FTC_FOLIO,
BD_100.FTN_NUM_CTA_INVDUAL,
BD_100.FTC_FOLIO_PROCESAR,
BD_100.FTC_NSS_IMSS,
BD_100.FTC_APELLIDO_PATERNO,
BD_100.FTC_APELLIDO_MATERNO,
BD_100.FTC_NOMBRE,
BD_100.FTC_CURP,
BD_100.FTC_TIPO_OPERACION,
BD_100.FTC_INSTITUTO_ORIGEN,
BD_100.FTC_CREDITO,
BD_100.FTN_MONTO_PESOS_97,
BD_100.FTN_SDO_AIVS_97,
BD_100.FTN_MONTO_PESOS_92,
BD_100.FTN_SDO_AIVS_92,
BD_100.FTN_VALOR_AIVS,
BD_100.FTD_FEH_CREDITO,
BD_100.FTD_FEH_VAL_TRANSFERENCIA,
BD_100.FTC_DIAGNOSTICO,
BD_100.FTN_MOTIVO_RECHAZO,
BD_100.FTC_ESTATUS_OPE,
BD_100.FTN_SUBPROCESO,
BD_100.FCD_FEH_ACCION,
BD_100.FTN_IND_SDO_DISP_VIV97,
BD_100.FTN_IND_SDO_DISP_92,
BD_100.FCN_ID_TIPO_SUBCTA_97,
BD_100.FCN_ID_TIPO_SUBCTA_92,
BD_100.NSS_CURP,
BD_200.TMN_CVE_ITGY,
BD_400.IdCreditoInf,
BD_400.IdCreditoFov,
DS_250.FECHA_PRESENTACION,
DS_250.FECHA_POSTERIOR
FROM BD_100_TRANS_REC_PORTA BD_100
LEFT JOIN BD_200_MAP_NCI_RECHAZO BD_200  ON BD_100.FTN_MOTIVO_RECHAZO = BD_200.FTN_MOTIVO_RECHAZO
INNER JOIN BD_400_LEE_ARCHIVO BD_400   ON BD_100.NSS_CURP = BD_400.NSS_CURP
INNER JOIN DS_FECHAS_250 DS_250 ON BD_100.FTC_FOLIO = DS_250.FTC_FOLIO
WHERE 1=1
AND BD_100.FTC_FOLIO = '#SR_FOLIO#' --  Párametrizado
AND BD_100.FTN_SUBPROCESO = #SR_SUBPROCESO# --  Párametrizado
)
,
VARIABLES AS
(
SELECT
Consecutivo AS CONTADOR,
FTC_FOLIO,
vMotiRechToString,
CASE WHEN TO_CHAR(vMotiRechToString) = '104' THEN '104' ELSE TMN_CVE_ITGY END AS vMotiRech
FROM
(
SELECT
ROWNUM AS Consecutivo,
FTC_FOLIO,
REPLACE(TRIM(TRAILING '0' FROM TO_CHAR(FTN_MOTIVO_RECHAZO)),'.','') as vMotiRechToString,
TMN_CVE_ITGY
FROM TF_700
)
), 
TR_400_CAMPOS AS
(
SELECT DISTINCT
V.CONTADOR,
V.FTC_FOLIO,
TF.FECHA_PRESENTACION
FROM TF_700 TF
INNER JOIN VARIABLES V ON TF.FTC_FOLIO = V.FTC_FOLIO
WHERE V.FTC_FOLIO = '#SR_FOLIO#'
ORDER BY V.CONTADOR ASC)

 -----||  SE GENERA SUMARIO
SELECT 
'09' TIPO_REG,
'02' ID_SERVICIO,
'56' ID_OPERACION,
'01'ENTIDAD_ORIGEN,
'534' CVE_ORIGEN,
'03' ENTIDAD_DESTINO,
'001'CVE_DESTINO,
FECHA_PRESENTACION AS FECHA_PROCESO,
LPAD(TRIM(TO_CHAR(COUNT(*))),10,'0') AS TOTAL_REGISTROS,
RPAD(' ',616,' ') AS FILLER
FROM TR_400_CAMPOS
GROUP BY
FECHA_PRESENTACION