SELECT
  FTC_FOLIO,
  FCN_ID_SUBPROCESO,
  CONTEO_REGISTROS,
  TIPO,
  MONTOS_RECH,
  FFN_ID_CONCEPTO_MOV,
  DUMMY
FROM (
  SELECT
    FTC_FOLIO,
    FCN_ID_SUBPROCESO,
    COUNT(*) AS CONTEO_REGISTROS,
    SUM(NVL(FTN_IMP_RET_DEVOLVER,0)) AS REJ_IMP_PESOS_RET,
    SUM(NVL(FTN_IMP_ACT_REC_RETIRO_DEV,0)) AS REJ_ACT_PESOS_RET,
    SUM(NVL(FTN_IMP_ACT_RET_REN_CUENTA,0)) AS REJ_REN_PESOS_RET,
    SUM(NVL(FTN_IMP_CES_CUO_PATRON_DEV,0)) AS REJ_IMP_PESOS_CES_VEJ_PAT,
    SUM(NVL(FTN_IMP_CES_CUO_TRABAJ_DEV,0)) AS REJ_IMP_PESOS_CES_VEJ_TRA,
    SUM(NVL(FTN_IMP_ACT_REC_CUO_PAT_DEV,0)) AS REJ_ACT_PESOS_CES_VEJ_PAT,
    SUM(NVL(FTN_IMP_ACT_REC_CUO_TRA_DEV,0)) AS REJ_ACT_PESOS_CES_VEJ_TRA,
    SUM(NVL(FTN_IMP_ACT_REN_CUE_IND_PAT,0)) AS REJ_REN_PESOS_CES_VEJ_PAT,
    SUM(NVL(FTN_IMP_ACT_REN_CUE_IND_TRA,0)) AS REJ_REN_PESOS_CES_VEJ_TRA,
    SUM(NVL(FTN_IMP_CUO_SOCIAL_DEV,0)) AS REJ_IMP_PESOS_CUO_SOCIAL,
    SUM(NVL(FTN_NUM_APLI_VIV_APOR_PAT_DEV,0)) AS REJ_ACT_AIVS_VIV,
    SUM(NVL(FTN_IMP_APOR_PAT_VIV_DEV,0)) AS IMP_PESOS_VIV,
    CAST(4063 AS DECIMAL(4,0)) AS CON_MOV_IMP_PESOS_RET,
    CAST(4182 AS DECIMAL(4,0)) AS CON_MOV_ACT_PESOS_RET,
    CAST(4526 AS DECIMAL(4,0)) AS CON_MOV_REN_PESOS_RET,
    CAST(4070 AS DECIMAL(4,0)) AS CON_MOV_IMP_PESOS_CES_VEJ_PAT,
    CAST(4527 AS DECIMAL(4,0)) AS CON_MOV_IMP_PESOS_CES_VEJ_TRA,
    CAST(4183 AS DECIMAL(4,0)) AS CON_MOV_ACT_PESOS_CES_VEJ_PAT,
    CAST(4528 AS DECIMAL(4,0)) AS CON_MOV_ACT_PESOS_CES_VEJ_TRA,
    CAST(4529 AS DECIMAL(4,0)) AS CON_MOV_REN_PESOS_CES_VEJ_PAT,
    CAST(4530 AS DECIMAL(4,0)) AS CON_MOV_REN_PESOS_CES_VEJ_TRA,
    CAST(4184 AS DECIMAL(4,0)) AS CON_MOV_CS_IMP,
    CAST(4072 AS DECIMAL(4,0)) AS CON_MOV_VIV97,
    CAST(4072 AS DECIMAL(4,0)) AS CON_MOV_VIV97_PES,
    1 AS DUMMY_IMP_PESOS_RET,
    1 AS DUMMY_ACT_PESOS_RET,
    1 AS DUMMY_REN_PESOS_RET,
    1 AS DUMMY_IMP_PESOS_CES_VEJ_PAT,
    1 AS DUMMY_IMP_PESOS_CES_VEJ_TRA,
    1 AS DUMMY_ACT_PESOS_CES_VEJ_PAT,
    1 AS DUMMY_ACT_PESOS_CES_VEJ_TRA,
    1 AS DUMMY_REN_PESOS_CES_VEJ_PAT,
    1 AS DUMMY_REN_PESOS_CES_VEJ_TRA,
    1 AS DUMMY_CS_IMP,
    1 AS DUMMY_VIV97,
    2 AS DUMMY_VIV97_PES
  FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
  WHERE FTC_FOLIO = '#SR_FOLIO#'
    AND FCN_ID_SUBPROCESO = 3832
    AND FTC_ESTATUS = 0
  GROUP BY FTC_FOLIO, FCN_ID_SUBPROCESO
) SRC
UNPIVOT (
  -- (MONTOS_RECH, FFN_ID_CONCEPTO_MOV, DUMMY) <-- columnas de salida
  (MONTOS_RECH, FFN_ID_CONCEPTO_MOV, DUMMY)
  FOR TIPO IN (
    (REJ_IMP_PESOS_RET,     CON_MOV_IMP_PESOS_RET,     DUMMY_IMP_PESOS_RET)     AS 'IMP_PESOS_RET',
    (REJ_ACT_PESOS_RET,     CON_MOV_ACT_PESOS_RET,     DUMMY_ACT_PESOS_RET)     AS 'ACT_PESOS_RET',
    (REJ_REN_PESOS_RET,     CON_MOV_REN_PESOS_RET,     DUMMY_REN_PESOS_RET)     AS 'REN_PESOS_RET',
    (REJ_IMP_PESOS_CES_VEJ_PAT, CON_MOV_IMP_PESOS_CES_VEJ_PAT, DUMMY_IMP_PESOS_CES_VEJ_PAT) AS 'IMP_PESOS_CES_VEJ_PAT',
    (REJ_IMP_PESOS_CES_VEJ_TRA, CON_MOV_IMP_PESOS_CES_VEJ_TRA, DUMMY_IMP_PESOS_CES_VEJ_TRA) AS 'IMP_PESOS_CES_VEJ_TRA',
    (REJ_ACT_PESOS_CES_VEJ_PAT, CON_MOV_ACT_PESOS_CES_VEJ_PAT, DUMMY_ACT_PESOS_CES_VEJ_PAT) AS 'ACT_PESOS_CES_VEJ_PAT',
    (REJ_ACT_PESOS_CES_VEJ_TRA, CON_MOV_ACT_PESOS_CES_VEJ_TRA, DUMMY_ACT_PESOS_CES_VEJ_TRA) AS 'ACT_PESOS_CES_VEJ_TRA',
    (REJ_REN_PESOS_CES_VEJ_PAT, CON_MOV_REN_PESOS_CES_VEJ_PAT, DUMMY_REN_PESOS_CES_VEJ_PAT) AS 'REN_PESOS_CES_VEJ_PAT',
    (REJ_REN_PESOS_CES_VEJ_TRA, CON_MOV_REN_PESOS_CES_VEJ_TRA, DUMMY_REN_PESOS_CES_VEJ_TRA) AS 'REN_PESOS_CES_VEJ_TRA',
    (REJ_IMP_PESOS_CUO_SOCIAL,  CON_MOV_CS_IMP,              DUMMY_CS_IMP)              AS 'CS_IMP',
    (REJ_ACT_AIVS_VIV,          CON_MOV_VIV97,              DUMMY_VIV97)               AS 'VIV97',
    (IMP_PESOS_VIV,             CON_MOV_VIV97_PES,          DUMMY_VIV97_PES)           AS 'VIV97_PES'
  )
)