SELECT DISTINCT
SUBSTR(AE.FTC_LINEA,17,8) FTD_FEH_CRE_LOTE,
SUBSTR(AE.FTC_LINEA,28,8) FTD_FEH_LIM_RES,
TO_NUMBER(SUBSTR(AE.FTC_LINEA,25,3)) FTN_CONSEC_DIA,
SUBSTR(ASM.FTC_LINEA,1,2) FTC_TIPO_REG,
SUBSTR(ASM.FTC_LINEA,3,2) FTC_IDENTI_SERV,
TO_NUMBER(SUBSTR(ASM.FTC_LINEA,73,8)) FTN_NUM_REG_APORT_LOTE,
--TO_NUMBER(TRIM(SUBSTR(ASM.FTC_LINEA,99,6))) FTN_NUM_REG_CTAS_PAGAR
NULL FTN_NUM_REG_CTAS_PAGAR
FROM CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO  ASM
JOIN CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO  AE ON ASM.FTN_ID_ARCHIVO=AE.FTN_ID_ARCHIVO
WHERE ASM.FTN_ID_ARCHIVO = #sr_id_archivo#
AND SUBSTR(ASM.FTC_LINEA,1,2) = '09'
AND SUBSTR(AE.FTC_LINEA,1,2) = '01'