SELECT DISTINCT
TO_DATE(FTD_FEH_CRE_LOTE, 'yyyyMMdd') AS FTD_FEH_CRE_LOTE
, TO_DATE(FTD_FEH_LIM_RES, 'yyyyMMdd') AS FTD_FEH_LIM_RES
, FTN_CONSEC_DIA
, FTC_TIPO_REG
, FTC_IDENTI_SERV
, FTN_NUM_REG_APORT_LOTE
, FTN_NUM_REG_CTAS_PAGAR
, #SR_SUBPROCESO# AS FCN_ID_SUBPROCESO
, #sr_id_archivo# AS FTN_ID_ARCHIVO
, to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_CRE
, 'DATABRICKS' AS FTC_USU_CRE
, #sr_folio# AS FTC_FOLIO
, '#sr_tipo_archivo#' AS FTC_TIPO_ARCH
FROM #DELTA_TABLA_NAME1#