SELECT
---encabezado
TO_DATE(FTD_FEH_CRE_LOTE, 'yyyyMMdd') AS FTD_FEH_CRE_LOTE
, TO_DATE(FTD_FEH_LIM_RES, 'yyyyMMdd') AS FTD_FEH_LIM_RES
---detalle 02
, FTC_TIPO_REG
, FTC_IDENTI_SERV
, FTN_CONSE_REG_LOTE
, FTC_NSS
, FTC_CLAVE_ENT_ORIG
, FTC_RFC_TRABA
, FTC_CURP
, FTC_NOMBRE
, FTN_PERIODO_PAGO
, TO_DATE(FTD_FEH_PAGO, 'yyyyMMdd') AS FTD_FEH_PAGO
, TO_DATE(FTD_FEH_VALOR_RCV, 'yyyyMMdd') AS FTD_FEH_VALOR_RCV
, TO_DATE(FTD_FEH_VALOR_VIV, 'yyyyMMdd') AS FTD_FEH_VALOR_VIV
, FTN_FOLIO_SUA
, FNC_CVE_ENT_RECEP
, FNC_REG_PATRN_IMSS
, FTN_IMP_RET_DEVOLVER
, FTN_IMP_CES_CUO_PATRON_DEV
, FTN_IMP_CES_CUO_TRABAJ_DEV
, FTN_IMP_CUO_SOCIAL_DEV
, FTN_IMP_ACT_REC_RETIRO_DEV
, FTN_IMP_ACT_REC_CUO_PAT_DEV
, FTN_IMP_ACT_REC_CUO_TRA_DEV
, FTN_IMP_APOR_PAT_VIV_DEV
, FNN_DIAS_COTZDOS_BIM_DEV
, FTN_NUM_APLI_VIV_APOR_PAT_DEV
, FTN_IMP_ACT_RET_REN_CUENTA
, FTN_IMP_ACT_REN_CUE_IND_PAT
, FTN_IMP_ACT_REN_CUE_IND_TRA
, TO_DATE(FTD_FEH_ENV_ORG_SOL_PROC, 'yyyyMMdd') AS FTD_FEH_ENV_ORG_SOL_PROC
, FTC_DIAG_DEV
, FTC_MOT_DEV
, FTC_RES_OPERACION
, FTC_DIAGNOSTICO1
, FTC_DIAGNOSTICO2
, FTC_DIAGNOSTICO3
, FTN_CONSEC_DIA
, #SR_SUBPROCESO# AS FCN_ID_SUBPROCESO
, #sr_id_archivo# AS FTN_ID_ARCHIVO
, to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_CRE
, 'DATABRICKS' AS FTC_USU_CRE
, #sr_folio# AS FTC_FOLIO
, '#sr_tipo_archivo#' AS FTC_TIPO_ARCH
FROM #DELTA_TABLA_NAME1#