SELECT
TO_DATE(FTD_FEH_CRE_LOTE, 'yyyyMMdd') AS FTD_FEH_CRE_LOTE
, TO_DATE(FTD_FEH_LIM_RES, 'yyyyMMdd') AS FTD_FEH_LIM_RES
, FTN_CONSEC_DIA
---detalle 08
, FTC_TIPO_REG
, FTC_IDENTI_SERV
, FTC_ID_PAGO
, FTN_IMP_SOL_INSTITUTO
, TO_DATE(FTD_LIQUIDACION, 'yyyyMMdd') AS FTD_LIQUIDACION
, FTN_IMP_APACEP_RCV_DEV_ADM
, FTN_IMP_APEND_RCV_ADM
, FTN_IMP_APRECH_RCV_ADM
, FTN_NUM_APLI_INT_VIV_SOL_INST
, FTN_NUM_APLI_INT_VIV_ACDEV_ADM
, FTN_NUM_APLI_INT_VIV_PEND_ADM
, FTN_NUM_APLI_INT_VIV_RECH_ADM
, FTN_IMP_VIV_ACEP_DEV_ADM
, FTN_IMP_VIV_PEND_DEV_ADM
, FTN_IMP_VIV_RECH_DEV_ADM
, FTC_IND_SIEFORE
, FTC_TIPO_SIEFORE
, FTC_RES_OPERACION
, FTC_DIAGNOSTICO1
, FTC_DIAGNOSTICO2
, FTC_DIAGNOSTICO3
, #SR_SUBPROCESO# AS FCN_ID_SUBPROCESO
, #sr_id_archivo# AS FTN_ID_ARCHIVO
, to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_CRE
, 'DATABRICKS' AS FTC_USU_CRE
, #sr_folio# AS FTC_FOLIO
, '#sr_tipo_archivo#' AS FTC_TIPO_ARCH
FROM #DELTA_TABLA_NAME1#