SELECT 
    D.FTD_FEH_PRESEN, 
    D.FECHA_VALOR_ACCION, 
    D.FTC_CURP, 
    D.FTC_NSS_INFONA, 
    D.FTN_NUM_CTA_INVDUAL, 
    D.FTC_RFC_INFONA, 
    D.FTC_APELLIDO_PATER_INFONA, 
    D.FTC_APELLIDO_MATER_INFONA, 
    D.FTC_NOMBRE_INFONA, 
    D.FTC_IDENTI_LOTE_SOLIC, 
    D.FTC_NSS_AFORE, 
    D.FTC_RFC_AFORE, 
    D.FTC_APELLIDO_PATER_AFORE, 
    D.FTC_APELLIDO_MATER_AFORE, 
    D.FTC_NOMBRE_AFORE, 
    D.FTN_SALDO_97, 
    D.FTN_SALDO_92, 
    D.FTC_CODIGO_RES_OPER, 
    D.FTC_DIAGNOS_PROCE, 
    D.FTC_NOMBRE_IMSS, 
    D.FTN_NUM_CRED_INFONA, 
    D.FTN_INTERES_SALDO_97, 
    D.FTN_INTERES_SALDO_92, 
    D.FTN_PERIODO_PAGO, 
    D.FTD_FEH_CARGA, 
    D.FTC_FOLIO_BITACORA, 
    D.FTN_ID_SUBP, 
    D.FTN_CONTA_SERV, 
    D.SALDO_DISPONIBLE_AIVS,
    VAL.FCD_FEH_ACCION,
    VAL.FCN_VALOR_ACCION,
    VAL.FCN_ID_VALOR_ACCION
FROM 
    #DELTA_TABLE_DES_INF# D
JOIN 
    #DELTA_TABLE_VALOR_ACCION# VAL 
ON 
    D.FECHA_VALOR_ACCION = VAL.FCD_FEH_ACCION
WHERE 
    D.SALDO_DISPONIBLE_AIVS > 0;