SELECT 
   FTC_NSS_INFONA,
   FTC_IDENT_PROC_DESMA,
   FTN_CONTA_SERV,
   CASE ROW_NUMBER() OVER (PARTITION BY FTC_NSS_INFONA, FTC_IDENT_PROC_DESMA ORDER BY FTC_NSS_INFONA ASC, FTC_IDENT_PROC_DESMA ASC) 
     WHEN 1 THEN 1
     ELSE 0 END AS BNDDUP
FROM CIERREN_ETL.TTAFOTRAS_ETL_MARCA_DESMARCA
WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'
  AND FTN_ID_ARCHIVO = #SR_ID_ARCHIVO#
ORDER BY FTC_NSS_INFONA, FTC_IDENT_PROC_DESMA, FTN_CONTA_SERV

