SELECT
  DER.FTN_ESTATUS_DIAG,
  DER.FTC_ID_DIAGNOSTICO,
  DER.FTD_FEH_PRESEN,
  DER.FTC_CURP,
  DER.FTC_NSS_INFONA ,
  DER.FTN_CTA_AFORE,
  DER.FTC_RFC_INFONA,
  DER.FTC_APELLIDO_PATER_INFONA,
  DER.FTC_APELLIDO_MATER_INFONA,
  DER.FTC_NOMBRE_INFONA,
  DER.FTC_IDENTI_LOTE_SOLIC,
  DER.FTN_NSS ,
  DER.FTC_RFC_AFORE,
  DER.FTC_APELLIDO_PATER_AFORE,
  DER.FTC_APELLIDO_MATER_AFORE,
  DER.FTC_NOMBRE_AFORE,
  DER.FTN_SALDO_97,
  DER.FTN_SALDO_92,
  DER.FTC_CODIGO_RES_OPER,
  DER.FTC_DIAGNOS_PROCE,
  DER.FTC_NOMBRE_IMSS,
  DER.FTN_NUM_CRED_INFONA,
  DER.FTN_INTERES_SALDO_97,
  DER.FTN_INTERES_SALDO_92,
  DER.FTN_PERIODO_PAGO,
  DER.FTC_TIPO_ARCH,
  DER.FTN_NUM_CTA_INVDUAL,
  DER.FCC_VALOR_IND,
  DER.FTD_FEH_REG,
  DER.FTD_FEH_CARGA           ,
  DER.FTC_IDENT_PROC_DESMA    ,

  DER.FTN_CONTA_SERV,
  --DER.FTC_ID_DIAGNOSTICO,
  --DER.FCN_ID_IND_CTA_INDV,
  --DER.FFN_ID_CONFIG_INDI, 
  --DER.FTC_VIGENCIA,
  --DER.FTN_DETALLE,
  IZQ.BNDDUP
FROM (
    SELECT
      MCA.FTN_ESTATUS_DIAG,
      MCA.FTD_FEH_PRESEN,
      MCA.FTC_CURP,
      MCA.FTC_NSS_INFONA ,
      MCA.FTN_CTA_AFORE,
      MCA.FTC_RFC_INFONA,
      MCA.FTC_APELLIDO_PATER_INFONA,
      MCA.FTC_APELLIDO_MATER_INFONA,
      MCA.FTC_NOMBRE_INFONA,
      MCA.FTC_IDENTI_LOTE_SOLIC,
      MCA.FTN_NSS ,
      MCA.FTC_RFC_AFORE,
      MCA.FTC_APELLIDO_PATER_AFORE,
      MCA.FTC_APELLIDO_MATER_AFORE,
      MCA.FTC_NOMBRE_AFORE,
      MCA.FTN_SALDO_97,
      MCA.FTN_SALDO_92,
      MCA.FTC_CODIGO_RES_OPER,
      MCA.FTC_DIAGNOS_PROCE,
      MCA.FTC_NOMBRE_IMSS,
      MCA.FTN_NUM_CRED_INFONA,
      MCA.FTN_INTERES_SALDO_97,
      MCA.FTN_INTERES_SALDO_92,
      MCA.FTN_PERIODO_PAGO,
      MCA.FTC_TIPO_ARCH,
      MCA.FTN_CONTA_SERV,
      MCA.FTN_NUM_CTA_INVDUAL,
      MCA.FTC_ID_DIAGNOSTICO,
      MCA.FTD_FEH_CARGA            ,
      MCA.FTC_IDENT_PROC_DESMA      ,
      VIV.FCN_ID_IND_CTA_INDV,
      VIV.FFN_ID_CONFIG_INDI, 
      VIV.FCC_VALOR_IND,
      VIV.FTC_VIGENCIA,
      VIV.FTN_DETALLE,
      VIV.FTD_FEH_REG
    FROM #DELTA_VAL_IDENT# MCA
    LEFT JOIN #DELTA_VIV# VIV
      ON MCA.FTN_NUM_CTA_INVDUAL = VIV.FTN_NUM_CTA_INVDUAL
    ORDER BY MCA.FTN_NSS, MCA.FTN_CONTA_SERV
) DER
LEFT JOIN 
(  SELECT 
      BNDDUP, FTC_NSS_INFONA, FTN_CONTA_SERV  --FTN_NSS
    FROM #DELTA_DUP#
    ORDER BY FTC_NSS_INFONA, FTN_CONTA_SERV    --FTN_NSS
) IZQ
ON  DER.FTN_NSS = IZQ.FTC_NSS_INFONA  --FTN_NSS
AND DER.FTN_CONTA_SERV = IZQ.FTN_CONTA_SERV
