SELECT 
  FTD_FEH_PRESEN                       ,
  FTC_CURP                             ,
  FTC_NSS_INFONA                       ,
  FTN_CTA_AFORE                        ,
  FTC_RFC_INFONA                       ,
  FTC_APELLIDO_PATER_INFONA            ,
  FTC_APELLIDO_MATER_INFONA            ,
  FTC_NOMBRE_INFONA                    ,
  FTC_IDENTI_LOTE_SOLIC                ,
  FTC_NSS_AFORE                        ,
  FTC_RFC_AFORE                        ,
  FTC_APELLIDO_PATER_AFORE             ,
  FTC_APELLIDO_MATER_AFORE             ,
  FTC_NOMBRE_AFORE                     ,
  FTN_SALDO_97                         ,
  FTN_SALDO_92                         ,
  FTC_CODIGO_RES_OPER                  ,
  FTC_DIAGNOS_PROCE                    ,
  FTC_NOMBRE_IMSS                      ,
  FTN_NUM_CRED_INFONA                  ,
  FTN_INTERES_SALDO_97                 ,
  FTN_INTERES_SALDO_92                 ,
  FTN_PERIODO_PAGO                     ,
  FTC_TIPO_ARCH                        ,
  FTD_FEH_CARGA                        ,
  FTC_FOLIO_BITACORA                   ,
  FTN_ID_SUBP                          ,
  FTC_INDI_VIVI                        ,
  FTD_REGI_INDI                        ,
  FTC_ESTA_REGI                        ,
  FTD_FEH_CRE                          ,
  FCC_USU_CRE                          ,
  FTN_MOTI_RECH                        ,
  FTC_IDENT_PROC_DESMA                 ,
  FTN_CONTA_SERV
FROM(
    SELECT
      FTD_FEH_PRESEN                       ,
      FTC_CURP                             ,
      FTC_NSS_INFONA                       ,
      FTN_NUM_CTA_INVDUAL AS FTN_CTA_AFORE ,
      FTC_RFC_INFONA                       ,
      FTC_APELLIDO_PATER_INFONA            ,
      FTC_APELLIDO_MATER_INFONA            ,
      FTC_NOMBRE_INFONA                    ,
      FTC_IDENTI_LOTE_SOLIC                ,
      FTN_NSS AS FTC_NSS_AFORE             ,
      FTC_RFC_AFORE                        ,
      FTC_APELLIDO_PATER_AFORE             ,
      FTC_APELLIDO_MATER_AFORE             ,
      FTC_NOMBRE_AFORE                     ,
      FTN_SALDO_97                         ,
      FTN_SALDO_92                         ,
      FTC_CODIGO_RES_OPER                  ,
      FTC_DIAGNOS_PROCE                    ,
      FTC_NOMBRE_IMSS                      ,
      FTN_NUM_CRED_INFONA                  ,
      FTN_INTERES_SALDO_97                 ,
      FTN_INTERES_SALDO_92                 ,
      FTN_PERIODO_PAGO                     ,
      FTC_TIPO_ARCH                        ,
      FTN_CONTA_SERV                       ,
      current_date() AS FTD_FEH_CARGA      ,
      #SR_FOLIO# as FTC_FOLIO_BITACORA     ,
      #SR_SUBPROCESO# AS FTN_ID_SUBP       ,
      TRIM(FCC_VALOR_IND) AS FTC_INDI_VIVI ,
      FTD_FEH_REG AS FTD_REGI_INDI         ,
      CASE
        WHEN FTN_ESTATUS_DIAG = 0 THEN 0
    	  WHEN FTN_ESTATUS_DIAG <> 0 AND BNDDUP = 1 THEN 1
    	  ELSE 0 END AS FTC_ESTA_REGI        ,
      to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_CRE   ,
      'DATABRICKS' AS FCC_USU_CRE          ,
      CASE 
        WHEN FTN_ESTATUS_DIAG = 0 THEN FTC_ID_DIAGNOSTICO
        WHEN FTN_ESTATUS_DIAG <> 0 AND BNDDUP = 1 THEN NULL
    	ELSE 4437 END AS FTN_MOTI_RECH       ,
      FTC_IDENT_PROC_DESMA,
      FTN_CONTA_SERV,
    
	ROW_NUMBER() OVER (PARTITION BY FTN_NSS, FTN_CONTA_SERV ORDER BY FTN_NSS, FTN_CONTA_SERV ASC) AS rn
    FROM #DELTA_VIV_DUP# 
) 
WHERE rn = 1