SELECT
  VAL.FTN_ESTATUS_DIAG,
  MD.FTD_FEH_PRESEN,
  MD.FTC_CURP,
  MD.FTC_NSS_INFONA ,
  MD.FTN_CTA_AFORE,
  MD.FTC_RFC_INFONA,
  MD.FTC_APELLIDO_PATER_INFONA,
  MD.FTC_APELLIDO_MATER_INFONA,
  MD.FTC_NOMBRE_INFONA,
  MD.FTC_IDENTI_LOTE_SOLIC,
  MD.FTC_NSS_AFORE AS FTN_NSS  ,
  MD.FTC_RFC_AFORE,
  MD.FTC_APELLIDO_PATER_AFORE,
  MD.FTC_APELLIDO_MATER_AFORE,
  MD.FTC_NOMBRE_AFORE,
  MD.FTN_SALDO_97,
  MD.FTN_SALDO_92,
  MD.FTC_CODIGO_RES_OPER,
  MD.FTC_DIAGNOS_PROCE,
  MD.FTC_NOMBRE_IMSS,
  MD.FTN_NUM_CRED_INFONA,
  MD.FTN_INTERES_SALDO_97,
  MD.FTN_INTERES_SALDO_92,
  MD.FTN_PERIODO_PAGO,
  MD.FTC_TIPO_ARCH,
  VAL.FTN_NUM_CTA_INVDUAL,
  VAL.FTC_ID_DIAGNOSTICO,
  MD.FTD_FEH_CARGA,
  MD.FTC_IDENT_PROC_DESMA,
  MD.FTN_CONTA_SERV
  
FROM CIERREN_ETL.TTAFOTRAS_ETL_MARCA_DESMARCA MD
LEFT JOIN (
    SELECT 
       FTN_NSS             ,
       FTN_NUM_CTA_INVDUAL ,
       FTN_ESTATUS_DIAG    ,
       FTC_ID_DIAGNOSTICO
    FROM ( 
         SELECT 
            FTN_NSS             ,
            FTN_NUM_CTA_INVDUAL ,
            FTN_ESTATUS_DIAG    ,
            FTC_ID_DIAGNOSTICO  ,
            ROW_NUMBER() OVER (PARTITION BY FTN_NSS, FTC_ID_DIAGNOSTICO ORDER BY FTN_NSS, FTC_ID_DIAGNOSTICO ASC) AS rn
          FROM CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE
          WHERE FTC_FOLIO = '#SR_FOLIO#'
         )
         WHERE rn = 1
     ) VAL
  ON MD.FTC_NSS_AFORE = VAL.FTN_NSS
WHERE MD.FTC_FOLIO_BITACORA= '#SR_FOLIO#'
  AND MD.FTN_ID_ARCHIVO = #SR_ID_ARCHIVO#
