SELECT 
   MD.FTC_CURP,
   MD.FTC_NSS_AFORE AS FTC_NSS,
   MD.FTC_APELLIDO_PATER_AFORE,
   MD.FTC_APELLIDO_MATER_AFORE,
   MD.FTC_NOMBRE_AFORE,
   MD.FTC_RFC_INFONA AS FTC_RFC,
   MD.FTC_FOLIO_BITACORA AS FTC_FOLIO,
   MD.FTN_ID_ARCHIVO,
   MD.FTC_TIPO_ARCH,
   BUC.FTN_NUM_CTA_INVDUAL,
   BUC.FTC_RFC_BUC,
   BUC.FTC_BANDERA,
   BUC.FTN_CELULAR,
   BUC.FTC_CORREO_ELEC,
   CTA.FTD_FEH_CRE
FROM CIERREN_ETL.TTAFOTRAS_ETL_MARCA_DESMARCA MD
LEFT JOIN (
    SELECT * FROM (
      SELECT 
         CASE WHEN B.FTC_NSS IS NULL THEN FTC_CURP ELSE FTC_NSS END AS FTC_NSS_CURP,
         B.FTC_NSS,
         B.FTC_CURP AS FTC_CURP_BUC,
         B.FTN_NUM_CTA_INVDUAL,
         B.FTC_NOMBRE AS FTC_NOMBRE_BUC,
         B.FTC_AP_PATERNO AS FTC_AP_PATERNO_BUC,
         B.FTC_AP_MATERNO AS FTC_AP_MATERNO_BUC,
         B.FTC_RFC AS FTC_RFC_BUC,
         B.FTC_BANDERA,
         B.FTN_CELULAR,
         B.FTC_CORREO_ELEC,
         ROW_NUMBER() OVER (PARTITION BY B.FTC_NSS, B.FTN_NUM_CTA_INVDUAL ORDER BY B.FTC_NSS, B.FTN_NUM_CTA_INVDUAL ASC) AS RN
      FROM (
         SELECT FTC_NSS_INFONA,FTC_NSS_AFORE
         FROM CIERREN_ETL.TTAFOTRAS_ETL_MARCA_DESMARCA
         WHERE FTC_FOLIO_BITACORA= '#SR_FOLIO#') A 
         LEFT JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC B 
            ON A.FTC_NSS_AFORE = B.FTC_NSS
      WHERE B.FTC_NSS IS NOT NULL
   ) 
   WHERE RN = 1
) BUC
   ON MD.FTC_NSS_AFORE = BUC.FTC_NSS

LEFT JOIN CIERREN.TTAFOGRAL_CTA_INVDUAL CTA ON (MD.FTC_NSS_AFORE = CTA.FTN_NSS AND BUC.FTN_NUM_CTA_INVDUAL = CTA.FTN_NUM_CTA_INVDUAL)

WHERE MD.FTN_ID_ARCHIVO = #SR_ID_ARCHIVO#
  AND MD.FTC_FOLIO_BITACORA = '#SR_FOLIO#'



