SELECT  DISP.FTC_FOLIO
       ,DISP.FTC_FOLIO_REL
       ,DISP.FCN_ID_PROCESO
       ,DISP.FCN_ID_SUBPROCESO
       ,DISP.FTN_NUM_CTA_INVDUAL
       ,DISP.FCN_ID_TIPO_SUBCTA
       ,C_MOV.FCN_ID_TIPO_MONTO
       ,SUM(DISP.FTF_MONTO) FTN_MONTO
from #DELTA_TABLA_NAME1# DISP
INNER JOIN #DELTA_TABLA_NAME2# C_MOV
ON (DISP.FCN_ID_TIPO_SUBCTA = C_MOV.FCN_ID_TIPO_SUBCTA
AND DISP.FCN_ID_SUBPROCESO = C_MOV.FCN_ID_SUBPROCESO
AND DISP.FFN_ID_CONCEPTO_MOV = C_MOV.FFN_ID_CONCEPTO_MOV
AND DISP.TIPO_MOV= C_MOV.TIPO_MOV
) 
GROUP BY DISP.FTN_NUM_CTA_INVDUAL, 
DISP.FTC_FOLIO, 
DISP.FTC_FOLIO_REL, 
DISP.FCN_ID_PROCESO,
DISP.FCN_ID_SUBPROCESO, 
DISP.FCN_ID_TIPO_SUBCTA, 
C_MOV.FCN_ID_TIPO_MONTO
