SELECT  AEIM.FTN_NUM_CTA_INVDUAL
       ,DISP.FTC_FOLIO
       ,DISP.FTC_FOLIO_REL
       ,DISP.FCN_ID_PROCESO
       ,DISP.FCN_ID_SUBPROCESO
       ,DISP.FCN_ID_TIPO_SUBCTA
       ,SUM(DISP.FTF_MONTO) AS FTN_MONTO
       ,DISP.FCN_ID_TIPO_MONTO
FROM  #DELTA_TABLA_NAME2# DISP
INNER JOIN #DELTA_TABLA_NAME1# AEIM
ON DISP.FTN_NUM_CTA_INVDUAL = AEIM.FTN_NUM_CTA_INVDUAL
GROUP BY 
       AEIM.FTN_NUM_CTA_INVDUAL
       ,DISP.FTC_FOLIO
       ,DISP.FTC_FOLIO_REL
       ,DISP.FCN_ID_PROCESO
       ,DISP.FCN_ID_SUBPROCESO
       ,DISP.FCN_ID_TIPO_SUBCTA
       ,DISP.FCN_ID_TIPO_MONTO