/* Consulta las cuentas individuales de los clientes que fueron recibidos como parte del trámite de Aclaraciones Especiales, y cuyo estatus en la tabla histórica es '558' (ACEPTADO) */
SELECT DISTINCT
    ETL_AEIM.FTN_NUM_CTA_INVDUAL,
    PRO_AEIM.FTN_ESTATUS_REG
FROM 
    CIERREN_ETL.TTSISGRAL_ETL_AEIM ETL_AEIM
INNER JOIN  
    PROCESOS.TTAFOAE_AEIM PRO_AEIM --Tabla historica
    ON ETL_AEIM.FTC_NOMBRE_COMPLETO_ARCH = PRO_AEIM.FTC_NOMBRE_COMPLETO_ARCH
    AND ETL_AEIM.FTC_RFC_ARCH = PRO_AEIM.FTC_RFC_ARCH
    AND ETL_AEIM.FTN_NSS_ARCH = PRO_AEIM.FTN_NSS_ARCH
    AND ETL_AEIM.FNC_REG_PATRONAL_IMSS = PRO_AEIM.FNC_REG_PATRONAL_IMSS
WHERE 
    ETL_AEIM.FTC_FOLIO = '#SR_FOLIO_REL#'
    AND PRO_AEIM.FTN_ESTATUS_REG = 558 --ACEPTADO
