SELECT  CMOV.FRN_ID_MOV_SUBCTA
       ,MSUB.FCN_ID_SUBPROCESO
       ,DECODE('#sr_tipo_mov#','ABONO',0,
	                                     'CARGO',MSUB.FCN_ID_TIPO_SUBCTA) FCN_ID_TIPO_SUBCTA
       ,MSUB.FCN_ID_TIPO_MOV
       ,CMOV.FFN_ID_CONCEPTO_MOV
       ,CMOV.FCN_ID_TIPO_MONTO
       ,CAT.FCC_VALOR AS TIPO_MOV
FROM   CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CMOV
       ,CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB
       ,CIERREN.TCCRXGRAL_CAT_CATALOGO CAT
       ,CIERREN.TCCRXGRAL_TIPO_CAT TCAT
WHERE  
		CMOV.FRN_ID_MOV_SUBCTA = MSUB.FRN_ID_MOV_SUBCTA
AND    MSUB.FCN_ID_TIPO_MOV = CAT.FCN_ID_CAT_CATALOGO
AND    CAT.FCN_ID_TIPO_CAT = TCAT.FCN_ID_TIPO_CAT
AND    CMOV.FFB_VIGENCIA = 1
AND    MSUB.FRB_VIGENCIA = 1
AND    MSUB.FCN_ID_SUBPROCESO = #sr_subproceso#
AND    TCAT.FCN_ID_TIPO_CAT = 25
AND    TCAT.FCB_VIGENCIA = 1
AND    CAT.FCB_VIGENCIA = 1