SELECT  AEIM.FTN_NUM_CTA_INVDUAL
       ,DISP.FTC_FOLIO
       ,DISP.FCN_ID_PROCESO
       ,DISP.FCN_ID_SUBPROCESO
       ,DISP.FCN_ID_TIPO_SUBCTA
       ,DISP.FTF_MONTO
       ,DISP.FFN_ID_CONCEPTO_MOV
       ,DISP.TIPO_MOV
       ,DISP.FTC_FOLIO_REL
FROM  #DELTA_TABLA_NAME2# DISP
INNER JOIN #DELTA_TABLA_NAME1# AEIM
ON DISP.FTN_NUM_CTA_INVDUAL = AEIM.FTN_NUM_CTA_INVDUAL
