SELECT DISTINCT
CRE_AEIM.FTN_NUM_CTA_INVDUAL
FROM CIERREN_ETL.TTSISGRAL_ETL_AEIM CRE_AEIM
INNER JOIN PROCESOS.TTAFOAE_AEIM PRO_AEIM
ON (CRE_AEIM.FTC_NOMBRE_COMPLETO_ARCH = PRO_AEIM.FTC_NOMBRE_COMPLETO_ARCH
AND CRE_AEIM.FTN_NSS_ARCH = PRO_AEIM.FTN_NSS_ARCH
AND CRE_AEIM.FTC_RFC_ARCH = PRO_AEIM.FTC_RFC_ARCH
AND CRE_AEIM.FNC_REG_PATRONAL_IMSS = PRO_AEIM.FNC_REG_PATRONAL_IMSS)
WHERE CRE_AEIM.FTC_FOLIO = DECODE('#SR_TIPO_MOV#','ABONO','#SR_FOLIO#','#SR_FOLIO_REL#')
AND PRO_AEIM.FTN_ESTATUS_REG = 558 --558 = ACEPTADO
