SELECT 
   --FTC_FOLIO_BITACORA                         ,
   FTC_FOLIO_BITACORA AS FTC_FOLIO            ,
   FTN_CTA_AFORE AS FTN_NUM_CTA_INVDUAL       ,
   -- CURRENT_TIMESTAMP AS FTD_FEH_ACT           ,
   to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_ACT ,
   'CIERREN_ETL_APP' AS FCC_USU_ACT           ,
   --'0' AS FTB_ESTATUS_MARCA
   '0' AS FTC_ESTATUS_MARCA
FROM #DELTA_TABLA_NAME#
WHERE FTN_CTA_AFORE IS NOT NULL
