SELECT 
   IND.FTD_FEH_ACT         ,
   IND.FCC_USU_ACT         ,
   CTA.FCN_ID_IND_CTA_INDV ,
   '0' AS FTC_VIGENCIA     ,
   IND.FTC_FOLIO
FROM      #DELTA_INDICADORES# IND
LEFT JOIN #DELTA_CUENTAS# CTA
ON IND.FTN_NUM_CTA_INVDUAL = CTA.FTN_NUM_CTA_INVDUAL

