MERGE INTO CIERREN.TTAFOGRAL_IND_CTA_INDV ori
USING(
  SELECT 
     FTD_FEH_ACT         ,
	   FCC_USU_ACT         ,
	   FCN_ID_IND_CTA_INDV ,
	   FTC_VIGENCIA
  --FROM CIERREN.TTAFOGRAL_IND_CTA_INDV_AUX
  FROM CIERREN_DATAUX.TTAFOGRAL_IND_CTA_INDV_AUX
  WHERE
     FTC_FOLIO = '#SR_FOLIO#'
) aux
 ON (ori.FCN_ID_IND_CTA_INDV = aux.FCN_ID_IND_CTA_INDV)
WHEN MATCHED THEN UPDATE SET
  ori.FTD_FEH_ACT = aux.FTD_FEH_ACT,
  ori.FCC_USU_ACT = aux.FCC_USU_ACT,
  ori.FTC_VIGENCIA = aux.FTC_VIGENCIA
 