SELECT
   FCN_ID_IND_CTA_INDV ,
   FTN_NUM_CTA_INVDUAL ,
   FFN_ID_CONFIG_INDI  ,
   FCC_VALOR_IND       ,
   FTC_VIGENCIA
FROM 
  CIERREN.TTAFOGRAL_IND_CTA_INDV
WHERE FFN_ID_CONFIG_INDI = 14 
  AND FCC_VALOR_IND = '1' 
  AND FTC_VIGENCIA = '1'
  
