SELECT 
   FTN_CTA_AFORE AS FTN_NUM_CTA_INVDUAL       ,
   FTC_INDI_VIVI AS FCC_VALOR_IND             ,
   TO_TIMESTAMP(FTD_REGI_INDI) AS FTD_FEH_REG ,
   -- CURRENT_TIMESTAMP AS FTD_FEH_ACT           ,
   to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_ACT ,
   'CIERREN_ETL_APP' AS FCC_USU_ACT,
   #SR_FOLIO# AS FTC_FOLIO
FROM #DELTA_TABLA_NAME#
WHERE FTN_CTA_AFORE IS NOT NULL
