-- 2026-02-16 Se modifica tabla y columna FTB_ESTATUS_MARCE destino del MERGE
MERGE INTO CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA ori
USING(
  SELECT 
  DISTINCT
   --FTC_FOLIO_BITACORA  ,
   FTC_FOLIO  ,
	 FTN_NUM_CTA_INVDUAL ,
	 FTD_FEH_ACT         ,
	 FCC_USU_ACT         ,
	 --FTB_ESTATUS_MARCA
   FTC_ESTATUS_MARCA
  --FROM CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA_AUX
  FROM CIERREN_DATAUX.TTAFOGRAL_ETL_MATRIZ_CONVIVENCIA_AUX
  WHERE
     --FTC_FOLIO_BITACORA = '#SR_FOLIO#'
     FTC_FOLIO = '#SR_FOLIO#'
) aux
 ON (ori.FTN_NUM_CTA_INVDUAL = aux.FTN_NUM_CTA_INVDUAL
 --AND ori.FTC_FOLIO = aux.FTC_FOLIO_BITACORA)
 AND ori.FTC_FOLIO = aux.FTC_FOLIO)
WHEN MATCHED THEN UPDATE SET
  ori.FTD_FEH_ACT = aux.FTD_FEH_ACT,
  ori.FCC_USU_ACT = aux.FCC_USU_ACT,
  ori.FTB_ESTATUS_MARCA = aux.FTC_ESTATUS_MARCA
 