SELECT 
    TS.TIPO_PROCESO,
    TS.TIPO_SUBPROCESO,
    #SR_PROCESO# AS PROCESO             ,
    #SR_SUBPROCESO# AS SUBPROCESO       ,
    MD.FTC_NSS_AFORE                       ,
    MD.FTC_FOLIO_BITACORA                  ,
    #SR_ID_ARCHIVO# AS FTN_ID_ARCHIVO   ,
    MD.FTN_CTA_AFORE                       ,
    MD.FTC_INDI_VIVI                       ,
    MD.FTD_REGI_INDI
FROM PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO MD
LEFT JOIN (
   SELECT distinct
      A.TIPO_PROCESO,B.TIPO_SUBPROCESO,A.PROCESO,B.SUBPROCESO
   FROM ( 
      SELECT 
         TMN_CVE_ITGY AS TIPO_PROCESO,
         TMN_CVE_NCI AS PROCESO
      FROM CIERREN.TMSISGRAL_MAP_NCI_ITGY
      WHERE TMC_VIGENCIA=1
        AND TMN_CVE_NCI = 97)A
   JOIN (
      SELECT 
         TMN_CVE_ITGY AS TIPO_SUBPROCESO,
         TMN_CVE_NCI AS SUBPROCESO
      FROM CIERREN.TMSISGRAL_MAP_NCI_ITGY
      WHERE TMC_VIGENCIA=1
        AND TMN_CVE_NCI = 354 
        AND TMC_USO = 'SUBPROCESOS')B
      ON 1=1
) TS
ON PROCESO = TS.PROCESO
AND SUBPROCESO = TS.SUBPROCESO
WHERE MD.FTC_FOLIO_BITACORA='#SR_FOLIO#'
  AND MD.FTC_TIPO_ARCH=09
  AND MD.FTC_ESTA_REGI=0
   
