WITH BD_100_MARCA_INFO
AS(
SELECT
1 AS BANDERA
,FTC_CURP
,FTC_NSS_INFONA
,Trim(FTC_RFC_INFONA) AS FTC_RFC_INFONA
,FTC_APELLIDO_PATER_INFONA
,FTC_APELLIDO_MATER_INFONA
,FTC_NOMBRE_INFONA
,FTC_NSS_AFORE
,Trim(FTC_RFC_AFORE) AS FTC_RFC_AFORE
,FTC_APELLIDO_PATER_AFORE
,FTC_APELLIDO_MATER_AFORE
,FTC_NOMBRE_AFORE
,FTC_NOMBRE_IMSS
,FTN_NUM_CRED_INFONA
,FTD_FEH_PRESEN
,CASE WHEN FTN_CTA_AFORE IS NULL THEN 0 ELSE FTN_CTA_AFORE 
 END FTN_NUM_CTA_INVDUAL
,FTC_FOLIO_BITACORA
FROM
PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'  ---  PARAMETRIZADO '#SR_FOLIO#'
AND FTC_ESTA_REGI = 0
AND FTN_ID_SUBP = #SR_SUBPROCESO# ---  PARAMETRIZADO '#SR_SUBPROCESO#'
),
BD_400_SUF_SALDOS 
AS (
SELECT
CASE WHEN  FTN_NUM_CTA_INVDUAL IS NULL THEN 0 ELSE FTN_NUM_CTA_INVDUAL 
END FTN_NUM_CTA_INVDUAL 
,FTN_SDO_AIVS
,FTN_MONTO_PESOS 
FROM PROCESOS.TTSISGRAL_SUF_SALDOS
WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'  ---  PARAMETRIZADO '#SR_FOLIO#'
AND FTN_ID_SUBP = #SR_SUBPROCESO# ---  PARAMETRIZADO '#SR_SUBPROCESO#'
), -- Left Join por el campo FTN_NUM_CTA_INVDUAL  hacia BD_100_MARCA
SF_200_CONSECUTIVO AS
(
 SELECT
 '#SR_FOLIO#' AS FTC_FOLIO_BITACORA, ---  PARAMETRIZADO '#SR_FOLIO#'
  CASE WHEN PROCESOS IS NULL THEN '1' ELSE LPAD(PROCESOS,3,'0') END AS PROCESOS
  FROM
  (
  SELECT
SUM(Reg) PROCESOS
FROM
(
 SELECT 
    COUNT(DISTINCT(FTC_FOLIO_BITACORA)) Reg
   ,FTC_FOLIO_BITACORA
 FROM 
 PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
 WHERE FTD_FEH_CARGA = TO_DATE('#SR_SYSDATE#', 'DD/MM/YY')
 GROUP BY FTC_FOLIO_BITACORA
 ))
 ), -- Se une por un Inner Join Hacia el resultado del Left Join Anterior y se une por FTC_FOLIO_BITACORA
 DB_750_CONSECUTIVO AS
(
 SELECT 
 LA.FTN_ID_ARCHIVO
,AF.FTC_FOLIO AS FOLIO_BITACORA
,Trim(SUBSTR(FTC_LINEA,28,3)) ConsecutivoLote
FROM CIERREN.TRAFOGRAL_ARCHIVO_FOLIO AF 
INNER JOIN
CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO LA 
      ON AF.FTN_ID_ARCHIVO = LA.FTN_ID_ARCHIVO
  AND AF.FTC_FOLIO = '#SR_FOLIO#'
  AND SUBSTR(LA.FTC_LINEA,1,2) = '01'
), --datos de los Joins Anterios por el campo FTC_FOLIO_BITACORA y se hace por medio de un INNER JOIN
TF_200_CAMPOS AS
(
SELECT
BD_100.FTC_FOLIO_BITACORA
FROM BD_100_MARCA_INFO BD_100
LEFT JOIN BD_400_SUF_SALDOS BD_400 ON BD_100.FTN_NUM_CTA_INVDUAL =  BD_400.FTN_NUM_CTA_INVDUAL
INNER JOIN  SF_200_CONSECUTIVO SF_200 ON BD_100.FTC_FOLIO_BITACORA = SF_200.FTC_FOLIO_BITACORA
INNER JOIN  DB_750_CONSECUTIVO DB_750 ON BD_100.FTC_FOLIO_BITACORA = DB_750.FOLIO_BITACORA
)
SELECT
'09' AS TIPO_REGISTRO,
LPAD(TO_CHAR(TOTAL_REGISTRO),9,'0') AS TOTAL_REGISTRO,
FILLER,
SUM_SALDO97,
FILLER6
FROM
(
SELECT
FTC_FOLIO_BITACORA,
RPAD(' ',45,' ') AS FILLER,
RPAD('0',15,'0') AS SUM_SALDO97,
RPAD(' ',659,' ') AS FILLER6,
SUM(REG) AS TOTAL_REGISTRO
FROM
(
SELECT
FTC_FOLIO_BITACORA,
1 AS REG
FROM TF_200_CAMPOS
)
GROUP BY FTC_FOLIO_BITACORA
)