SELECT 
TEXTO
FROM
(
SELECT 
1 AS ORDEN, 
TIPO_REGISTRO||
ID_SERVICIO||
ID_OPERACION||
TIPO_ENTIDAD_ORI||
CLAVE_ENTIDAD_ORI||
TIPO_ENTIDAD_DES||
CLAVE_ENTIDAD_DES||
 ENTIDAD_FED_LOTE||
FECHA_PRESENTACION||
CONSECUTIVO_LOTE||
FILLER AS TEXTO
FROM #DELTA_SOLMARC_ENCABEZADO#
--dbx_mit_dev_1udbvf_workspace.default.delta_0300_arc_acep_lin1_encabezado_202507171410392809
UNION 
SELECT
2 AS ORDEN,
TIPO_REGISTRO||
CONTADOR_SERVICIO||
TIPO_ENTIDAD_RECEP||
CLAVE_ENTIDAD_RECEP||
TIPO_ENTIDAD_CED||
CLAVE_ENTIDAD_CED||
ORIGEN_TRANSFERENCIA||
FECHA_PRESENTACION||
FILLER9||
FTC_CURP||
FTC_NSS_INFONA||
FILLER12||
FTC_RFC_INFONA||
FTC_APELLIDO_PATER_INFONA||
FTC_APELLIDO_MATER_INFONA||
FTC_NOMBRE_INFONA||
FILLER17||
ID_LOTE_SOL||
FILLER19||
FTC_NSS_AFORE||
FTC_RFC_AFORE||
FILLER22||
FTC_APELLIDO_PATER_AFORE||
FTC_APELLIDO_MATER_AFOR||
FTC_NOMBRE_AFORE||
FILLER26||
NUM_VIV_97||
SALDO_VIV_97||
FILLER29||
FTC_NOMBRE_IMSS||
FTN_NUM_CRED_INFONA||
FILLER34 AS TEXTO
FROM #DELTA_SOLMARC_DETALLE#
--dbx_mit_dev_1udbvf_workspace.default.delta_0400_arc_acep_lin2_detalle_202507171410392809
UNION
SELECT
3 AS ORDEN,
TIPO_REGISTRO||
TOTAL_REGISTRO||
FILLER||
FTN_SDO_AIVS||
FTN_MONTO_PESOS||
FILLER6
FROM #DELTA_SOLMARC_SUMARIO#
--dbx_mit_dev_1udbvf_workspace.default.delta_0500_arc_acep_Lin3_sumario_202507171410392809
)
ORDER BY 1 ASC