SELECT 
TEXTO
FROM
(
SELECT 
1 AS ORDEN, 
TIPO_REGISTRO||
ID_SERVICIO||
ID_OPERACION||
TIPO_ENTIDAD_ORI||
CLAVE_ENTIDAD_ORI||
TIPO_ENTIDAD_DES||
CLAVE_ENTIDAD_DES||
ENTIDAD_FED_LOTE||
FECHA_PRESENTACION||
CONSECUTIVO_LOTE||
FILLER AS TEXTO
FROM #DELTA_SOLMARC_ENCABEZADO#
UNION 
SELECT
2 AS ORDEN,
TIPO_REGISTRO||
CONTADOR_SERVICIO||
TIPO_ENTIDAD_RECEP||
CLAVE_ENTIDAD_RECEP||
TIPO_ENTIDAD_CED||
CLAVE_ENTIDAD_CED||
ORIGEN_TRANSFERENCIA||
FECHA_PRESENTACION||
FILLER9||
FTC_CURP||
FTC_NSS_INFONA||
FILLER12||
FTC_RFC_INFONA||
FTC_APELLIDO_PATER_INFONA||
FTC_APELLIDO_MATER_INFONA||
FTC_NOMBRE_INFONA||
FILLER17||
ID_LOTE_SOL||
FILLER19||
FTC_NSS_AFORE||
FTC_RFC_AFORE||
FILLER22||
FTC_APELLIDO_PATER_AFORE||
FTC_APELLIDO_MATER_AFOR||
FTC_NOMBRE_AFORE||
FILLER26||
SALDO_VIV_97||
FILLER28||
FTC_NOMBRE_IMSS||
FTN_NUM_CRED_INFONA||
FILLER33||
MOTIVO_DEV||
FILLER35 AS TEXTO
FROM #DELTA_SOLMARC_DETALLE#
UNION
SELECT
3 AS ORDEN,
TIPO_REGISTRO||
TOTAL_REGISTRO||
FILLER||
SUM_SALDO97||
FILLER6 AS TEXTO
FROM #DELTA_SOLMARC_SUMARIO#
)
ORDER BY 1 ASC