MERGE INTO CIERREN.TTAFOGRAL_ARCHIVO ARCH
USING (
SELECT DISTINCT
FTN_ID_ARCHIVO,
FTC_NOMBRE,
FTN_TAM_ARCHIVO,
FTD_FEH_GEN,
FTD_FEH_ACT,
FTC_USU_ACT,
FCN_ID_ESTATUS_ARCHIVO
FROM CIERREN_DATAUX.TTAFOGRAL_ARCHIVO_AUX
WHERE FTN_ID_ARCHIVO = '#SR_ID_ARCHIVO_09#'  
  ) AUX
ON (
    ARCH.FTN_ID_ARCHIVO = AUX.FTN_ID_ARCHIVO
)
WHEN MATCHED THEN 
UPDATE SET
    ARCH.FTC_NOMBRE = AUX.FTC_NOMBRE,
    ARCH.FTN_TAM_ARCHIVO = AUX.FTN_TAM_ARCHIVO,
	ARCH.FTD_FEH_GEN = AUX.FTD_FEH_GEN,
	ARCH.FTD_FEH_ACT = AUX.FTD_FEH_ACT,
	ARCH.FTC_USU_ACT = AUX.FTC_USU_ACT,
    ARCH.FCN_ID_ESTATUS_ARCHIVO = AUX.FCN_ID_ESTATUS_ARCHIVO