WITH FECHA_PRESENTACION
AS(
SELECT
BANDERA,
 TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS DIA_HABIL
FROM (
    select 1 AS BANDERA,FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES       = SUBSTR(TO_CHAR(TO_DATE('#SR_SYSDATE#','DD-MM-YYYY'),'YYYY-MM-DD'),6,2)
        AND FTN_ANIO        = SUBSTR(TO_CHAR(TO_DATE('#SR_SYSDATE#','DD-MM-YYYY'),'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1  
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 12
GROUP BY BANDERA
),
BD_100_MARCA_DESMARCA AS
(
SELECT
A.BANDERA,
B.DIA_HABIL,
A.PROCESOS
FROM
(
SELECT
1 AS BANDERA,
SUM(Reg) PROCESOS
FROM
(
 SELECT 
   COUNT(DISTINCT(FTC_FOLIO_BITACORA)) Reg
   ,FTC_FOLIO_BITACORA
 FROM 
 PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
 WHERE FTD_FEH_CARGA = TO_DATE('#SR_SYSDATE#', 'DD/MM/YY')
 GROUP BY FTC_FOLIO_BITACORA
 )) A 
 INNER JOIN FECHA_PRESENTACION B ON A.BANDERA = B.BANDERA
 )
 SELECT 
 '01' AS TIPO_REGISTRO,
 '02' AS ID_SERVICIO,
 '06' AS ID_OPERACION,
 '01' AS TIPO_ENTIDAD_ORI,
 '534' AS CLAVE_ENTIDAD_ORI,
 '04' AS TIPO_ENTIDAD_DES,
 '002' AS CLAVE_ENTIDAD_DES,
 '009' AS ENTIDAD_FED_LOTE,
  DIA_HABIL AS FECHA_PRESENTACION,
 CASE WHEN PROCESOS IS NULL THEN '001' ELSE LPAD(PROCESOS,3,'0') END AS CONSECUTIVO_LOTE,
RPAD(' ',700,' ')AS FILLER
 FROM BD_100_MARCA_DESMARCA