SELECT
  DIS.FCN_ID_TIPO_SUBCTA,
  '#SR_FOLIO#' AS FTC_FOLIO,
  CAST(#SR_FOLIO_REL# AS VARCHAR2(100)) AS FTC_FOLIO_REL,
  DIS.FCN_ID_SIEFORE,
  DIS.FTF_MONTO_PESOS,
  VA.FCN_ID_VALOR_ACCION,
  DIS.FTN_NUM_CTA_INVDUAL,
  CONV.FTN_ID_MARCA,
  DIS.FTD_FEC_CRE,
  DIS.FTC_USU_CRE,
  DIS.FTD_FEC_ACT,
  DIS.FTC_USU_ACT,
  DIS.FFN_ID_CONCEPTO_MOV,
  DIS.FTC_TABLA_NCI_MOV,
  DIS.FNN_ID_REFERENCIA,
  NVL(CMOV.FTN_DEDUCIBLE, 0) AS FTN_DEDUCIBLE,
  VA.FCN_VALOR_ACCION,
  DECODE(
    DIS.FCN_ID_SUBPROCESO,
    8, 'IMSS',
    118, 'IMSS',
    439, 'IMSS',
    121, 'IMSS',
    9, 'IMSS',
    227, 'IMSS',
    120, 'ISSSTE',
    210, 'ISSSTE',
    122, 'ISSSTE',
    105, 'ISSSTE',
    839, 'ISSSTE',
    'XXXXX'
  ) AS INSTITUTO,
  CAST(NULL AS VARCHAR2(10)) AS FTN_ID_ERROR_VAL,
  SUB.FCN_ID_PLAZO,
  DIS.FTN_NO_LINEA
FROM (
  SELECT *
  FROM #CX_CRE_ESQUEMA#.#TL_CRE_DISPERSION#
  WHERE
    FTC_FOLIO = '#SR_FOLIO#'
    AND FTF_MONTO_PESOS > 0
    AND FFN_ID_CONCEPTO_MOV NOT IN (637, 638, 1002, 1003, 231)
    AND FCN_ID_SIEFORE NOT IN (846)
    AND FCN_ID_SUBPROCESO = 118
) DIS
INNER JOIN #CX_CRN_ESQUEMA#.#TL_CRN_MATRIZ_CONVIVENCIA# CONV
  ON CONV.FTC_FOLIO = DIS.FTC_FOLIO AND DIS.FTN_NUM_CTA_INVDUAL = CONV.FTN_NUM_CTA_INVDUAL
LEFT JOIN #CX_PRO_ESQUEMA#.#TL_PRO_AEIM# HIST
  ON DECODE(TRIM(DIS.FTC_NOMBRE), NULL, '1', TRIM(DIS.FTC_NOMBRE)) = DECODE(TRIM(HIST.FTC_NOMBRE_COMPLETO_ARCH), NULL, '1', TRIM(HIST.FTC_NOMBRE_COMPLETO_ARCH))
  AND DECODE(TRIM(DIS.FTN_NSS), NULL, '1', TRIM(DIS.FTN_NSS)) = DECODE(TRIM(HIST.FTN_NSS_ARCH), NULL, '1', TRIM(HIST.FTN_NSS_ARCH))
  AND DECODE(TRIM(DIS.FTC_RFC), NULL, '1', TRIM(DIS.FTC_RFC)) = DECODE(TRIM(HIST.FTC_RFC_ARCH), NULL, '1', TRIM(HIST.FTC_RFC_ARCH))
  AND DECODE(TRIM(DIS.FCN_REG_PATRONAL_IMSS), NULL, '1', TRIM(DIS.FCN_REG_PATRONAL_IMSS)) = DECODE(TRIM(HIST.FNC_REG_PATRONAL_IMSS), NULL, '1', TRIM(HIST.FNC_REG_PATRONAL_IMSS))
LEFT JOIN #CX_CRN_ESQUEMA#.#TL_CRN_TIPO_SUBCTA# SUB
  ON SUB.FCN_ID_TIPO_SUBCTA = DIS.FCN_ID_TIPO_SUBCTA
LEFT JOIN #CX_CRN_ESQUEMA#.#TL_CRN_VALOR_ACCION# VA
  ON VA.FCN_ID_SIEFORE = DIS.FCN_ID_SIEFORE
  AND TRUNC(VA.FCD_FEH_ACCION) = TO_DATE('#SR_FEC_ACC#', 'YYYY-MM-DD')
  AND DECODE(
    DIS.FCN_ID_SIEFORE,
    82, 140,
    83, 140,
    SUB.FCN_ID_REGIMEN
  ) = VA.FCN_ID_REGIMEN
INNER JOIN #CX_CRN_ESQUEMA#.#TL_CRN_CONFIG_CONCEP_MOV# CMOV
  ON CMOV.FFN_ID_CONCEPTO_MOV = DIS.FFN_ID_CONCEPTO_MOV AND FFB_VIGENCIA = '1'
WHERE
  HIST.FTN_ESTATUS_REG = 558
  AND CONV.FTB_ESTATUS_MARCA = '1'