SELECT
  A.FCN_ID_TIPO_SUBCTA,
  A.FTC_FOLIO,
  A.FCN_ID_SIEFORE,
  A.FTF_MONTO_PESOS,
  B.FTF_MONTO_ACCIONES,
  A.FTN_NUM_CTA_INVDUAL,
  A.FTD_FEC_CRE,
  A.FTC_USU_CRE,
  A.FTD_FEC_ACT,
  A.FTC_USU_ACT,
  A.FFN_ID_CONCEPTO_MOV,
  A.FTC_TABLA_NCI_MOV,
  A.FNN_ID_REFERENCIA,
  A.FCN_ID_VALOR_ACCION,
  A.FTN_ID_MARCA,
  A.FCN_VALOR_ACCION,
  A.FTC_FOLIO_REL,
  A.INSTITUTO,
  A.FTN_DEDUCIBLE,
  A.FTN_ID_ERROR_VAL,
  A.FCN_ID_PLAZO
FROM #CATALOG_SCHEMA#.#DELTA_001# A
LEFT JOIN #CATALOG_SCHEMA#.#DELTA_002# B
  ON A.FCN_ID_TIPO_SUBCTA = B.FCN_ID_TIPO_SUBCTA
  AND A.FCN_ID_SIEFORE = B.FCN_ID_SIEFORE
  AND A.FTN_NUM_CTA_INVDUAL = B.FTN_NUM_CTA_INVDUAL
  AND A.FTC_TABLA_NCI_MOV = B.FTC_TABLA_NCI_MOV
  AND A.FTN_NO_LINEA = B.FTN_NO_LINEA
  AND A.FFN_ID_CONCEPTO_MOV = B.FFN_ID_CONCEPTO_MOV