WITH
BD_500_IND_CTA
AS
(
SELECT DISTINCT
IND.FTN_NUM_CTA_INVDUAL, 
IND.FCC_VALOR_IND
FROM PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE TFS
LEFT JOIN CIERREN.TTAFOGRAL_IND_CTA_INDV IND ON TFS.FTN_NUM_CTA_INVDUAL = IND.FTN_NUM_CTA_INVDUAL
WHERE TFS.FTC_FOLIO = '#SR_FOLIO#' --'202108101439190646'
AND IND.FTC_VIGENCIA = 1 
AND (IND.FCC_VALOR_IND='714' OR IND.FCC_VALOR_IND= '713')
),
BD_200_MAP_CVES
AS
( 
 SELECT 
C.FTN_MOTIVO_RECHAZO,I.TMN_CVE_ITGY
FROM(
SELECT FCN_ID_CAT_CATALOGO AS TMN_CVE_NCI,
CASE 
WHEN FCN_ID_TIPO_CAT=3 THEN FCN_ID_CAT_CATALOGO
WHEN FCN_ID_TIPO_CAT=223 THEN TO_NUMBER(FCC_VALOR)
WHEN FCN_ID_TIPO_CAT=20 THEN FCN_ID_CAT_CATALOGO
WHEN FCN_ID_TIPO_CAT=291 THEN TO_NUMBER(FCC_VALOR)
END FTN_MOTIVO_RECHAZO
FROM CIERREN.TCCRXGRAL_CAT_CATALOGO 
WHERE FCN_ID_TIPO_CAT IN (223,3,20,291)
)C
INNER JOIN CIERREN.TMSISGRAL_MAP_NCI_ITGY I 
ON C.TMN_CVE_NCI=I.TMN_CVE_NCI
WHERE I.TMC_USO='MOTIVO DE RECHAZO PARA PROCESAR DE TRANSFERENCIA DE ACREDITADOS FOVISSSTE'
AND I.TMC_VIGENCIA = 1
)
,
TRANS_FOVISSSTE
 AS
(
SELECT 
TF.FTC_FOLIO,
TF.FTN_NUM_CTA_INVDUAL,
TF.FTN_CONTA_SERV,
TF.FTD_FEH_MOVIMIENTO,
TF.FTC_CURP,
TF.FTC_NSS, 
TF.FTC_ESTATUS,
TF.FTN_MOTIVO_RECHAZO,
TF.FTN_NUM_APLI_INTE_VIVI92_APL,
TF.FTN_VAL_APLI_INTE_92,
TF.FTN_SALDO_TOT_VIVI92_APL,
TF.FTC_DIAG_PROCESO,
TF.FTN_NUM_APLI_INTE_VIVI08_APL,
TF.FTN_VAL_APLI_INTE_08,
TF.FTN_SALDO_TOT_VIVI08_APL,
TF.FTN_NUM_APLI_INTE_VIVI08_SOL,
TF.FTN_NUM_APLI_INTE_VIVI92_SOL,
SS.FTN_VALOR_AIVS,
TF.FTN_SALDO_TOT_VIVI08,
TF.FTN_SALDO_TOT_VIVI92
FROM PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE TF
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS SS ON TF.FTC_FOLIO = SS.FTC_FOLIO_BITACORA 
                                           AND TF.FTN_NUM_CTA_INVDUAL = SS.FTN_NUM_CTA_INVDUAL
where TF.FTC_FOLIO = '#SR_FOLIO#'  -- '202108101439190646'
AND TF.FCN_ID_SUBPROCESO = #SR_SUBPROCESO#  --363
)
SELECT
'02' AS TIPO_REGISTRO,
LPAD(A.FTN_CONTA_SERV,10,'0') AS CONTADOR_SERVICIO,
'534' AS CVE_ENT_EMIS,
CASE WHEN C.FCC_VALOR_IND = 714 THEN '1' ELSE '2' END AS TIPO_TRABAJADOR,
TO_CHAR(FTD_FEH_MOVIMIENTO,'YYYYMMDD') AS FTD_FEH_MOVIMIENTO,
CASE WHEN A.FTC_CURP IS NULL THEN LPAD(' ',18,' ') ELSE LPAD(A.FTC_CURP,18,' ') END AS FTC_CURP,
LPAD('0',8,'0') AS ID_PROCESAR,
CASE WHEN A.FTC_NSS IS NULL OR A.FTC_NSS = '' THEN LPAD(' ',11,' ') ELSE LPAD(REPLACE(A.FTC_NSS,'.',''),11,' ') END AS FTC_NSS,
CASE WHEN A.FTC_ESTATUS = 1 THEN '01' ELSE '02' END AS IND_ACEPT,
CASE WHEN A.FTC_ESTATUS = 0 AND B.TMN_CVE_ITGY IS NOT NULL
THEN LPAD(REPLACE(B.TMN_CVE_ITGY,'.',''),2,'0')
ELSE CASE WHEN A.FTC_ESTATUS = 0 AND B.TMN_CVE_ITGY IS NULL THEN '00' ELSE '  ' END 
END AS MOTIVO_DEV,
CASE WHEN A.FTC_ESTATUS = 0 
THEN LPAD('0',15,'0') 
Else LPAD(REPLACE(A.FTN_NUM_APLI_INTE_VIVI92_APL,'.',''),15,'0')
END AS AIVS92,
CASE WHEN A.FTC_ESTATUS = 0 THEN LPAD('0',20,'0')
ELSE LPAD(
  REPLACE(
     LPAD(SUBSTR(TO_CHAR(A.FTN_VALOR_AIVS), 1, INSTR(TO_CHAR(A.FTN_VALOR_AIVS, 'FM9999999999.99'), '.') - 1),6,'0') 
   ||RPAD(SUBSTR(TRIM(TO_CHAR(A.FTN_VALOR_AIVS, 'FM9999999999.99999999999999')||'00'),INSTR(TRIM(TO_CHAR(A.FTN_VALOR_AIVS, 'FM9999999999.99999999999999')||'00'), '.') + 1, 14),14,'0'),'.','')
          ,20,'0') END FTN_VAL_APLI_INTE_92,
CASE WHEN A.FTC_ESTATUS = 0 
THEN LPAD('0',15,'0') 
ELSE LPAD(REPLACE(A.FTN_SALDO_TOT_VIVI92_APL,'.',''),15,'0')
END AS PESOS92,
CASE WHEN A.FTC_ESTATUS = 1 
AND ((A.FTN_NUM_APLI_INTE_VIVI92_SOL - A.FTN_NUM_APLI_INTE_VIVI92_APL) > 0) THEN '01'
ELSE '  ' END AS IND_DIF92,
CASE WHEN A.FTC_ESTATUS = 0 
THEN LPAD('0',15,'0') 
ELSE LPAD(REPLACE(A.FTN_NUM_APLI_INTE_VIVI08_APL,'.',''),15,'0')
END AS AIVS08,
CASE WHEN A.FTC_ESTATUS = 0 THEN LPAD('0',20,'0')
ELSE LPAD(
  REPLACE(
LPAD(SUBSTR(TO_CHAR(A.FTN_VALOR_AIVS), 1, INSTR(TO_CHAR(A.FTN_VALOR_AIVS, 'FM9999999999.99'), '.') - 1),6,'0') 
   ||RPAD(SUBSTR(TRIM(TO_CHAR(A.FTN_VALOR_AIVS, 'FM9999999999.99999999999999')||'00'),INSTR(TRIM(TO_CHAR(A.FTN_VALOR_AIVS, 'FM9999999999.99999999999999')||'00'), '.') + 1, 14),14,'0'),'.','')
          ,20,'0') END FTN_VAL_APLI_INTE_08,
CASE WHEN A.FTC_ESTATUS = 0 
THEN LPAD('0',15,'0') 
ELSE LPAD(REPLACE(A.FTN_SALDO_TOT_VIVI08_APL,'.',''),15,'0')
END AS PESOS08,
CASE WHEN A.FTC_ESTATUS = 1 
AND ((A.FTN_NUM_APLI_INTE_VIVI08_SOL - A.FTN_NUM_APLI_INTE_VIVI08_APL) > 0) THEN '01'
ELSE '  ' END AS IND_DIF08,
LPAD(' ',2,' ') AS COD_RES_OP,
LPAD(' ',3,' ') AS DIAG_PROC,
LPAD(' ',556,' ') AS Filler

FROM TRANS_FOVISSSTE A
LEFT JOIN BD_200_MAP_CVES B ON A.FTN_MOTIVO_RECHAZO = B.FTN_MOTIVO_RECHAZO
LEFT JOIN BD_500_IND_CTA C ON A.FTN_NUM_CTA_INVDUAL = C.FTN_NUM_CTA_INVDUAL