WITH FECHA_PRESENTACION
AS(
SELECT
BANDERA,
 TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS DIA_HABIL
FROM (
    select 1 AS BANDERA,FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES       = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),6,2)
        AND FTN_ANIO        = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1  
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 12
GROUP BY BANDERA
),
BD_100_TRANS_FOVISSSTE AS
(
SELECT
A.BANDERA,
B.DIA_HABIL,
A.LOTE
FROM
(
SELECT DISTINCT
 1 AS BANDERA,
 FTC_FOLIO,
 SUBSTR(TRIM(FTC_IDENT_LOTE_SOLI),14,3) AS LOTE
FROM PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE
WHERE 1=1
AND FTC_FOLIO = '#SR_FOLIO#' --202108101439190646'
AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#     --363
 ) A 
 INNER JOIN FECHA_PRESENTACION B ON A.BANDERA = B.BANDERA
 )
 SELECT 
'01' AS TIPO_REGISTRO,
'02' AS ID_SERVICIO,
'96' AS ID_OPERACION,
'01' AS TIPO_ENTIDAD_ORI,
'534' AS CLAVE_ENTIDAD_ORI,
'03' AS TIPO_ENTIDAD_DES,
'001' AS CLAVE_ENTIDAD_DES,
LPAD(' ',3,' ') AS FILLER1,
DIA_HABIL AS FECHA_PRESENTACION,
LPAD(REPLACE(LOTE,'.',''),3,'0') AS CONSECUTIVO_LOTE,
'02' AS CVEMODAL_RECEP,
LPAD(' ',698,' ') AS FILLER2
 FROM BD_100_TRANS_FOVISSSTE