
Select 
'' as FOLIO
,#SR_SUBETAPA# AS FTC_ID_SUBETAPA
,FLN_TOTAL_REGISTROS
,FLN_TOTAL_REGISTROS-FLN_REG_NO_CUMPLIERON as FLN_REG_CUMPLIERON
,FLN_REG_NO_CUMPLIERON
,'94' FLC_VALIDACION
,FLN_TOTAL_ERRORES
,FLC_DETALLE
,to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) FLD_FEC_REG
,'DATABRICKS' FLC_USU_REG
,'' FTC_FOLIO_REL
, #SR_ID_ARCHIVO# SR_ID_ARCHIVO
from (  
SELECT 
TEMP.FLC_DETALLE
,coalesce(FLN_TOTAL_01,FLN_TOTAL_09,TOTAL_02) AS FLN_TOTAL_REGISTROS
,SUM(FLN_REG_NO_CUMPLIERON) AS FLN_REG_NO_CUMPLIERON
,SUM(FLN_TOTAL_ERRORES) AS FLN_TOTAL_ERRORES
FROM (SELECT
  CASE WHEN TRIM(FTC_CONTROL) NOT IN('01','02','09') THEN '02' ELSE FTC_CONTROL END AS FLC_DETALLE,
  0 AS FLN_REG_NO_CUMPLIERON,
  count(1) as FLN_TOTAL_ERRORES
FROM #DELTA_003#
GROUP BY FLC_DETALLE

union ALL
SELECT
  CASE WHEN TRIM(FTC_CONTROL) NOT IN('01','02','09') THEN '02' ELSE FTC_CONTROL END AS FLC_DETALLE
  ,count(1)  AS FLN_REG_NO_CUMPLIERON
  ,0 as FLN_TOTAL_ERRORES
FROM #DELTA_003#  where campo IS NOT NULL 
GROUP BY FLC_DETALLE


) TEMP
LEFT OUTER JOIN
(
SELECT
'01' AS FLC_DETALLE,
COUNT(1) AS  FLN_TOTAL_01
FROM 
    #DELTA_002#
WHERE 
    FTN_NO_LINEA = 1
    AND FTC_CONTROL <> '01' OR FTC_CONTROL IS NULL

    )TEM2
  ON TEMP.FLC_DETALLE = TEM2.FLC_DETALLE
  LEFT OUTER JOIN(
    SELECT
'09' AS FLC_DETALLE,
COUNT(1) AS  FLN_TOTAL_09
FROM 
    #DELTA_002# TMP
JOIN 
    (SELECT MAX(FTN_NO_LINEA) AS FTN_NO_LINEA FROM #DELTA_002#) MAX_REC
    ON TMP.FTN_NO_LINEA = MAX_REC.FTN_NO_LINEA
WHERE 
    TMP.FTC_CONTROL <> '09' OR FTC_CONTROL IS NULL
  )TEM3 ON TEMP.FLC_DETALLE= TEM3.FLC_DETALLE 
LEFT OUTER JOIN(
SELECT
  '02' AS FLC_DETALLE,
  COUNT(1) AS TOTAL_02
FROM 
#DELTA_002# TMP 
CROSS JOIN(
  SELECT MAX(FTN_NO_LINEA) AS FTN_NO_LINEA_MAX FROM #DELTA_002#
  ) 
WHERE TMP.FTN_NO_LINEA >1 AND TMP.FTN_NO_LINEA<FTN_NO_LINEA_MAX
GROUP BY FLC_DETALLE
)TEMP4
 ON TEMP.FLC_DETALLE= TEMP4.FLC_DETALLE
GROUP BY TEMP.FLC_DETALLE ,FLN_TOTAL_01,FLN_TOTAL_09,TOTAL_02
)x
