
Select 
'#SR_FOLIO#' FTC_FOLIO
,#SR_SUBETAPA# AS FTC_ID_SUBETAPA
,FLN_TOTAL_REGISTROS
,FLN_TOTAL_REGISTROS-FLN_REG_NO_CUMPLIERON as FLN_REG_CUMPLIERON
,FLN_REG_NO_CUMPLIERON
,'94' FLC_VALIDACION
,FLN_TOTAL_ERRORES
,FLC_DETALLE
,to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) FLD_FEC_REG
,'DATABRICKS' FLC_USU_REG
,'' FTC_FOLIO_REL
, '' AS FTN_ID_ARCHIVO
from (  
SELECT 
 TEMP.FLC_DETALLE 
,coalesce(FLN_TOTAL_01,FLN_TOTAL_09,TOTAL_02,0) AS FLN_TOTAL_REGISTROS
,SUM(COALESCE(FLN_REG_NO_CUMPLIERON,0)) AS FLN_REG_NO_CUMPLIERON
,SUM(coalesce(FLN_TOTAL_ERRORES,0)) AS FLN_TOTAL_ERRORES
FROM (

SELECT
   FTC_CONTROL AS FLC_DETALLE
  ,0  AS FLN_REG_NO_CUMPLIERON
  ,count(1) as FLN_TOTAL_ERRORES
FROM 
(
  
  
  SELECT  CASE WHEN TMP1.FTC_CONTROL  NOT IN('02','2',2) THEN '02' ELSE '02' END AS FTC_CONTROL, TMP1.FTN_NO_LINEA,CAMPO FROM 
 #DELTA_003# TMP1   LEFT OUTER JOIN #DELTA_002# TMP2
  ON TMP1.FTN_NO_LINEA = TMP2.FTN_NO_LINEA
  CROSS JOIN(
  SELECT MAX(FTN_NO_LINEA) AS FTN_NO_LINEA_MAX FROM #DELTA_002#
  )TMP3 
  WHERE TMP1.FTN_NO_LINEA >1 AND TMP1.FTN_NO_LINEA<FTN_NO_LINEA_MAX

)X 
GROUP BY FLC_DETALLE

UNION ALL 

SELECT
   '01' AS FLC_DETALLE
  ,0 AS FLN_REG_NO_CUMPLIERON
  ,count(1) as FLN_TOTAL_ERRORES
FROM 
(
  
  
  SELECT   CASE WHEN TRIM(TMP1.FTC_CONTROL) NOT IN('01','1',1) THEN '01' ELSE '01'END  AS FTC_CONTROL, TMP1.FTN_NO_LINEA ,CAMPO FROM 
 #DELTA_002# TMP1   LEFT OUTER JOIN #DELTA_003# TMP2
  ON TMP1.FTN_NO_LINEA = TMP2.FTN_NO_LINEA
     WHERE 
    TMP1.FTN_NO_LINEA = 1 
    and TMP2.FTN_NO_LINEA IS NOT NULL

  

)X 
GROUP BY FLC_DETALLE

UNION ALL 

SELECT
 '09' AS  FLC_DETALLE
  ,0  AS FLN_REG_NO_CUMPLIERON
  ,count(1) as FLN_TOTAL_ERRORES
FROM 
(

  
  SELECT CASE WHEN TRIM(TMP1.FTC_CONTROL) NOT IN('09','9',9) THEN '09'ELSE '09' END  AS FTC_CONTROL,TMP1.FTN_NO_LINEA,CAMPO FROM 
 #DELTA_002# TMP1   LEFT OUTER JOIN #DELTA_003# TMP2
  ON TMP1.FTN_NO_LINEA = TMP2.FTN_NO_LINEA
 CROSS JOIN   (SELECT MAX(FTN_NO_LINEA) AS FTN_NO_LINEA_MAX FROM #DELTA_002#) MAX_REC
      WHERE  TMP1.FTN_NO_LINEA =FTN_NO_LINEA_MAX AND TMP2.FTN_NO_LINEA IS NOT NULL

    


)X 
GROUP BY FLC_DETALLE



union ALL

SELECT
   FTC_CONTROL AS FLC_DETALLE
  ,count(1)  AS FLN_REG_NO_CUMPLIERON
  ,0 as FLN_TOTAL_ERRORES
FROM 
(
  
  
  SELECT DISTINCT CASE WHEN TMP1.FTC_CONTROL  NOT IN('02','2',2) THEN '02' ELSE '02'END AS FTC_CONTROL,CAMPO, TMP2.FTN_NO_LINEA FROM 
 #DELTA_002# TMP1   LEFT OUTER JOIN #DELTA_003# TMP2
  ON TMP1.FTN_NO_LINEA = TMP2.FTN_NO_LINEA
  CROSS JOIN(
  SELECT MAX(FTN_NO_LINEA) AS FTN_NO_LINEA_MAX, MIN (FTN_NO_LINEA) AS FTN_NO_LINEA_MIN FROM #DELTA_002#
  )TMP3 
WHERE TMP1.FTN_NO_LINEA >FTN_NO_LINEA_MIN AND TMP1.FTN_NO_LINEA<FTN_NO_LINEA_MAX



)X  where campo IS NOT NULL 
GROUP BY FLC_DETALLE

UNION ALL 

SELECT
   '01' AS FLC_DETALLE
  ,count(1)  AS FLN_REG_NO_CUMPLIERON
  ,0 as FLN_TOTAL_ERRORES
FROM 
(
  
  
  SELECT DISTINCT CASE WHEN TRIM(TMP1.FTC_CONTROL) NOT IN('01') THEN '01'END  AS FTC_CONTROL ,CAMPO FROM 
 #DELTA_002# TMP1   LEFT OUTER JOIN #DELTA_003# TMP2
  ON TMP1.FTN_NO_LINEA = TMP2.FTN_NO_LINEA
     WHERE 
    TMP1.FTN_NO_LINEA = 1 
    AND TMP2.FTN_NO_LINEA IS NOT NULL

)X  where campo IS NOT NULL 
GROUP BY FLC_DETALLE

UNION ALL 

SELECT
 '09' AS  FLC_DETALLE
  ,count(1)  AS FLN_REG_NO_CUMPLIERON
  ,0 as FLN_TOTAL_ERRORES
FROM 
(

  
  SELECT DISTINCT   CASE WHEN TRIM(TMP1.FTC_CONTROL) NOT IN('09') THEN '09' else '09' END  AS FTC_CONTROL,CAMPO FROM 
 #DELTA_002# TMP1   LEFT OUTER JOIN #DELTA_003# TMP2
  ON TMP1.FTN_NO_LINEA = TMP2.FTN_NO_LINEA
  CROSS JOIN(
  SELECT MAX(FTN_NO_LINEA) AS FTN_NO_LINEA_MAX FROM #DELTA_002#
  )TMP3 WHERE TMP1.FTN_NO_LINEA =FTN_NO_LINEA_MAX
      AND TMP2.FTN_NO_LINEA IS NOT NULL


)X  where campo IS NOT NULL 
GROUP BY FLC_DETALLE


UNION ALL 

SELECT
'01' AS FLC_DETALLE
,0
,0
 FROM(
SELECT current_date
)X01
UNION ALL
SELECT
'02' AS FLC_DETALLE
,0
,0
 FROM(
SELECT current_date
)X02

UNION ALL
SELECT
'09' AS FLC_DETALLE
,0
,0
 FROM(
SELECT current_date
)X03

) TEMP
LEFT OUTER JOIN
(
SELECT
'01' AS FLC_DETALLE,
COUNT(1) AS  FLN_TOTAL_01
FROM 
    #DELTA_002#
WHERE 
    FTN_NO_LINEA = 1 

    )TEM2
  ON TEMP.FLC_DETALLE = TEM2.FLC_DETALLE
  LEFT OUTER JOIN(
    SELECT
'09' AS FLC_DETALLE,
COUNT(1) AS  FLN_TOTAL_09
FROM 
    #DELTA_002# TMP
JOIN 
    (SELECT MAX(FTN_NO_LINEA) AS FTN_NO_LINEA FROM #DELTA_002#) MAX_REC
    ON TMP.FTN_NO_LINEA = MAX_REC.FTN_NO_LINEA

  )TEM3 ON TEMP.FLC_DETALLE= TEM3.FLC_DETALLE 
LEFT OUTER JOIN(
SELECT
  '02' AS FLC_DETALLE,
  COUNT(1) AS TOTAL_02
FROM 
#DELTA_002# TMP 
CROSS JOIN(
  SELECT MAX(FTN_NO_LINEA) AS FTN_NO_LINEA_MAX FROM #DELTA_002#
  ) 
WHERE TMP.FTN_NO_LINEA >1 AND TMP.FTN_NO_LINEA<FTN_NO_LINEA_MAX
GROUP BY FLC_DETALLE
)TEMP4
 ON TEMP.FLC_DETALLE= TEMP4.FLC_DETALLE
GROUP BY TEMP.FLC_DETALLE ,FLN_TOTAL_01,FLN_TOTAL_09,TOTAL_02

)x

