-- VALIDACIÓN DE LA SECUENCIA Y FORMATO DE REGISTROS

WITH BASE AS (
  SELECT 
    FTN_NO_LINEA,
    FTC_CONTROL,
    FTC_LINEA,
    FTC_LONG_REG,
    SR_ID_ARCHIVO,
    FECHA_CARGA,

    -- Solo se consideran válidos los tipos 01, 02, 03, 05, 09
    CASE 
      WHEN FTC_CONTROL IN ('01','02','03','05','09') THEN FTC_CONTROL
      ELSE NULL
    END AS FTC_CONTROL_NULL,

    VAL_ESTATUS,
    VAL_LENGTH_RECORD
  FROM #DELTA_002#
),

SECUENCIA AS (
  SELECT
    *,
    LAG(FTC_CONTROL) OVER (ORDER BY FTN_NO_LINEA) AS ANT_CONTROL,
    LEAD(FTC_CONTROL) OVER (ORDER BY FTN_NO_LINEA) AS SIG_CONTROL
  FROM BASE
),

VALIDACION_SECUENCIA AS (
  SELECT
    FTN_NO_LINEA,
    FTC_CONTROL,
    SR_ID_ARCHIVO,
    FECHA_CARGA,
    FTC_LINEA,
    'Tipo de registro' AS CAMPO,
    'Error en tipo de registro' AS VALIDACION,
    0 AS COD_ERROR,
    'N/A' AS VALOR_A_VALIDAR,
    ANT_CONTROL,
    SIG_CONTROL,
    CASE
      WHEN FTN_NO_LINEA = 1 AND FTC_CONTROL_NULL IS NULL THEN '01'
      WHEN FTN_NO_LINEA = 2 AND FTC_CONTROL != '02' AND ANT_CONTROL NOT IN ('01','02','03','05','09') THEN '02'
      WHEN FTC_CONTROL_NULL IS NULL AND ANT_CONTROL = '01' THEN '02'
      WHEN FTC_CONTROL_NULL IS NULL AND ANT_CONTROL = '02' AND SIG_CONTROL IN ('02','05') THEN '03'
      WHEN FTC_CONTROL_NULL IS NULL AND ANT_CONTROL IN ('03','02') AND SIG_CONTROL IN ('02','09') THEN '05'
      WHEN FTC_CONTROL_NULL IS NULL AND ANT_CONTROL = '05' AND SIG_CONTROL IS NULL THEN '09'
      WHEN FTC_CONTROL_NULL IS NULL AND ANT_CONTROL = '05' THEN '02'
      ELSE NULL
    END AS DESC_ERROR
  FROM SECUENCIA
)

-- COMBINACIÓN FINAL DE VALIDACIONES + EXTERNAS

SELECT *
FROM (
  -- Errores de validación de secuencia
  SELECT
    SR_ID_ARCHIVO AS FTN_ID_ARCHIVO,
    FECHA_CARGA,
    FTC_CONTROL,
    FTN_NO_LINEA,
    CAMPO,
    VALIDACION,
    FTC_LINEA AS VALOR_CAMPO,
    COD_ERROR,
    DESC_ERROR,
    VALOR_A_VALIDAR
  FROM VALIDACION_SECUENCIA
  WHERE DESC_ERROR IS NOT NULL

  UNION ALL

  -- Validación: falta encabezado 01 en primera línea
 /* SELECT 
    SR_ID_ARCHIVO,
    FECHA_CARGA,
    NULL AS FTC_CONTROL,
    1 AS FTN_NO_LINEA,
    'Tipo de registro' AS CAMPO,
    'Error en tipo de registro' AS VALIDACION,
    FTC_LINEA,
    0 AS COD_ERROR,
    '01' AS DESC_ERROR,
    'N/A' AS VALOR_A_VALIDAR
  FROM #DELTA_002#
  WHERE FTN_NO_LINEA = 1
    AND NOT EXISTS (
      SELECT 1
      FROM #DELTA_002#
      WHERE FTN_NO_LINEA = 1 AND FTC_CONTROL = '01'
    )

  UNION ALL*/---Se comento 20250920

  -- Validación: falta sumario 09 en la última línea
  SELECT 
    SR_ID_ARCHIVO,
    FECHA_CARGA,
    NULL AS FTC_CONTROL,
    FTN_NO_LINEA,
    'Tipo de registro' AS CAMPO,
    'Error en tipo de registro' AS VALIDACION,
    FTC_LINEA,
    0 AS COD_ERROR,
    '09' AS DESC_ERROR,
    'N/A' AS VALOR_A_VALIDAR
  FROM #DELTA_002#
  WHERE FTN_NO_LINEA = (SELECT MAX(FTN_NO_LINEA) FROM #DELTA_002#)
    AND NOT EXISTS (
      SELECT 1
      FROM #DELTA_002#
      WHERE FTN_NO_LINEA = (SELECT MAX(FTN_NO_LINEA) FROM #DELTA_002#)
        AND FTC_CONTROL = '09'
    )

  UNION ALL

  -- Validación: longitud inválida
  SELECT
    SR_ID_ARCHIVO,
    FECHA_CARGA,
    FTC_CONTROL,
    FTN_NO_LINEA,
    'Tipo de registro' AS CAMPO,
    'Error en longitud de registro' AS VALIDACION,
    FTC_LINEA,
    0 AS COD_ERROR,
    FTC_CONTROL AS DESC_ERROR,
    'N/A' AS VALOR_A_VALIDAR
  FROM #DELTA_002#
  WHERE VAL_LENGTH_RECORD = 0
) ERRORES_TOTALES

-- Orden final de todos los errores
ORDER BY FTN_NO_LINEA;

