SELECT * FROM #DELTA_TABLE_NAME_001#
UNION ALL
SELECT FTC_FOLIO, FTC_ID_SUBETAPA, SUM(FLN_TOTAL_REGISTROS) FLN_TOTAL_REGISTROS, SUM(FLN_REG_CUMPLIERON) FLN_REG_CUMPLIERON, SUM(FLN_REG_NO_CUMPLIERON) FLN_REG_NO_CUMPLIERON,
	FLC_VALIDACION, SUM(FLN_TOTAL_ERRORES) FLN_TOTAL_ERRORES, '00' FLC_DETALLE, FLD_FEC_REG, FLC_USU_REG, FTC_FOLIO_REL, FTN_ID_ARCHIVO
FROM #DELTA_TABLE_NAME_001#
	JOIN (SELECT COUNT(1) TOTAL FROM #DELTA_TABLE_NAME_001# WHERE FLC_DETALLE = '00') CEROCERO
		ON 1 = 1
	JOIN (SELECT SUM(FLN_TOTAL_ERRORES) TOTAL FROM #DELTA_TABLE_NAME_001# WHERE FLC_DETALLE <> '00' AND FLN_TOTAL_ERRORES > 0) ERRORES
		ON 1 = 1
WHERE 1 = 1
	--AND CEROCERO.TOTAL = 0
	AND ERRORES.TOTAL > 0
GROUP BY FTC_FOLIO, FTC_ID_SUBETAPA, FLC_VALIDACION, FLD_FEC_REG, FLC_USU_REG, FTC_FOLIO_REL, FTN_ID_ARCHIVO