SELECT 
    FTC_LINEA,
    FTN_NO_LINEA,
    #SR_ID_ARCHIVO# SR_ID_ARCHIVO,
    #SR_SUBETAPA# SR_SUBETAPA,
    "" FTC_FOLIO,
     date_format(FROM_UTC_TIMESTAMP(CURRENT_TIMESTAMP(), 'GMT-6'), 'yyyy-MM-dd HH:mm:ss')  AS FECHA_CARGA,    
    SUBSTRING(FTC_LINEA,1,2) FTC_CONTROL,
    LENGTH(FTC_LINEA) AS FTC_LONG_REG,
    CASE 
        WHEN length(FTC_LINEA)  = #MAX_LENGTH# THEN 1 
        ELSE 0 
    END VAL_LENGTH_RECORD,
    LEAD(SUBSTRING(FTC_LINEA,1,2)) OVER (PARTITION BY #SR_ID_ARCHIVO# ORDER BY FTN_NO_LINEA ) SIG_CONTROL,
    LEAD(FTC_LINEA ) OVER (PARTITION BY #SR_ID_ARCHIVO# ORDER BY FTN_NO_LINEA ) SIG_LINEA,
    CASE 
        WHEN FTC_CONTROL = '01' AND SIG_CONTROL = '02' THEN 1
        WHEN FTC_CONTROL = '02' AND (SIG_CONTROL = '02') THEN 1
        WHEN FTC_CONTROL = '02' AND (SIG_CONTROL = '09') THEN 1
        WHEN FTC_CONTROL = '09' AND SIG_CONTROL IS NULL THEN 1
        WHEN FTC_CONTROL IN('01','02','09') THEN 1
        ELSE 0
    END AS VAL_ESTATUS
FROM(
    SELECT 
        FTC_LINEA,
        FTN_NO_LINEA,
        SUBSTR(FTC_LINEA, 1, 2) AS FTC_CONTROL,
        LEAD(SUBSTR(FTC_LINEA, 1, 2)) OVER (ORDER BY FTN_NO_LINEA) AS SIG_CONTROL,
        LEAD(FTC_LINEA) OVER (ORDER BY FTN_NO_LINEA) AS SIG_LINEA
    FROM 
        #DELTA_001#
)   