SELECT
    FTN_ID_ARCHIVO,
    FECHA_CARGA,
    FTC_CONTROL,
    FTN_NO_LINEA,
    CAMPO,
    VALIDACION AS VALIDACION,
    VALOR_CAMPO,
    0 AS COD_ERROR,
    DESC_ERROR,
    VALOR_A_VALIDAR AS VALOR_A_VALIDAR
FROM #DELTA_004#;