SELECT
    '' FTC_FOLIO
    , FTC_ID_SUBETAPA
    ,SUM(FLN_TOTAL_REGISTROS) FLN_TOTAL_REGISTROS
    ,SUM(FLN_REG_CUMPLIERON) FLN_REG_CUMPLIERON
    ,SUM(FLN_REG_NO_CUMPLIERON) FLN_REG_NO_CUMPLIERON
    ,'94' FLC_VALIDACION
    ,SUM(FLN_TOTAL_ERRORES) FLN_TOTAL_ERRORES
    ,CASE WHEN LENGTH(TRIM(FLC_DETALLE)) = 0 THEN '00' ELSE FLC_DETALLE END FLC_DETALLE
    ,to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) FLD_FEC_REG
    ,'DATABRICKS' FLC_USU_REG
    ,'' FTC_FOLIO_REL
    ,FTN_ID_ARCHIVO
FROM
    (
    SELECT
        SR_SUBETAPA FTC_ID_SUBETAPA
        ,COUNT(1) FLN_TOTAL_REGISTROS
        ,SUM(DECODE(VAL_LENGTH_RECORD + VAL_ESTATUS, 2, 1, 0)) FLN_REG_CUMPLIERON
        ,SUM(DECODE(VAL_LENGTH_RECORD + VAL_ESTATUS, 2, 0, 1)) FLN_REG_NO_CUMPLIERON
        ,CASE WHEN LENGTH(TRIM(FTC_CONTROL)) = 0 THEN '00' ELSE FTC_CONTROL END FLC_DETALLE
        ,SUM(DECODE(VAL_LENGTH_RECORD + VAL_ESTATUS, 2, 0, 1)) FLN_TOTAL_ERRORES
        ,SR_ID_ARCHIVO FTN_ID_ARCHIVO
    FROM #DELTA_002#
    GROUP BY SR_SUBETAPA, FTC_CONTROL, SR_ID_ARCHIVO
    UNION ALL
    SELECT
        SR_SUBETAPA
        ,0
        ,-1
        ,1
        ,'01'
        ,1
        ,SR_ID_ARCHIVO
    FROM #DELTA_002#
    WHERE 1 = 1
        AND FTN_NO_LINEA = 1
        AND FTC_CONTROL <> '01'
    UNION ALL
    SELECT
        SR_SUBETAPA
        ,0
        ,-1
        ,1
        ,'09'
        ,1
        ,SR_ID_ARCHIVO
    FROM #DELTA_002# TMP
        JOIN (SELECT MAX(FTN_NO_LINEA) FTN_NO_LINEA FROM #DELTA_002#) MAX_REC
            ON TMP.FTN_NO_LINEA = MAX_REC.FTN_NO_LINEA
    WHERE TMP.FTC_CONTROL <> '09'
    UNION ALL
    SELECT
        SR_SUBETAPA
        ,0
        ,-1
        ,1
        ,'00'
        ,1
        ,SR_ID_ARCHIVO
    FROM #DELTA_002# TMP
        JOIN (SELECT MAX(FTN_NO_LINEA) FTN_NO_LINEA FROM #DELTA_002#) MAX_REC
    WHERE 1 = 1
        AND (TMP.FTC_CONTROL <> '09'
        AND TMP.FTN_NO_LINEA = MAX_REC.FTN_NO_LINEA)
        OR (TMP.FTN_NO_LINEA = 1
        AND TMP.FTC_CONTROL <> '01')
    UNION ALL
    SELECT
        TMP.SR_SUBETAPA
        ,0
        ,-1
        ,1
       ,'00'
       ,1
       ,TMP.SR_ID_ARCHIVO
   FROM (SELECT DISTINCT SR_SUBETAPA, SR_ID_ARCHIVO FROM #DELTA_002#) TMP
   JOIN (SELECT COUNT(1) TOTAL FROM #DELTA_002# WHERE FTC_CONTROL = '03') CONTEO
        ON 1 = 1
    WHERE CONTEO.TOTAL = 0
    )GROUP BY FTC_ID_SUBETAPA, FLC_DETALLE,CURRENT_TIMESTAMP, FTN_ID_ARCHIVO