SELECT
    '' AS FTC_FOLIO,
    FTC_ID_SUBETAPA,
    SUM(FLN_TOTAL_REGISTROS) AS FLN_TOTAL_REGISTROS,
    SUM(FLN_REG_CUMPLIERON) AS FLN_REG_CUMPLIERON,
    SUM(FLN_REG_NO_CUMPLIERON) AS FLN_REG_NO_CUMPLIERON,
    '94' AS FLC_VALIDACION,
    SUM(FLN_TOTAL_ERRORES) AS FLN_TOTAL_ERRORES,
    CASE 
        WHEN LENGTH(TRIM(FLC_DETALLE)) = 0 THEN '00' 
        ELSE FLC_DETALLE 
    END AS FLC_DETALLE,
    TO_TIMESTAMP(FROM_UTC_TIMESTAMP(CURRENT_TIMESTAMP, 'GMT-6')) AS FLD_FEC_REG,
    'DATABRICKS' AS FLC_USU_REG,
    '' AS FTC_FOLIO_REL,
    FTN_ID_ARCHIVO
FROM (
    -- Registros válidos: solo códigos permitidos
    SELECT
        SR_SUBETAPA AS FTC_ID_SUBETAPA,
        COUNT(1) AS FLN_TOTAL_REGISTROS,
        SUM(DECODE(VAL_LENGTH_RECORD + VAL_ESTATUS, 2, 1, 0)) AS FLN_REG_CUMPLIERON,
        SUM(DECODE(VAL_LENGTH_RECORD + VAL_ESTATUS, 2, 0, 1)) AS FLN_REG_NO_CUMPLIERON,
        FTC_CONTROL AS FLC_DETALLE,
        SUM(DECODE(VAL_LENGTH_RECORD + VAL_ESTATUS, 2, 0, 1)) AS FLN_TOTAL_ERRORES,
        SR_ID_ARCHIVO AS FTN_ID_ARCHIVO
    FROM #DELTA_002#
    WHERE FTC_CONTROL IN ('01', '02', '03', '05', '09')
    GROUP BY SR_SUBETAPA, FTC_CONTROL, SR_ID_ARCHIVO

    UNION ALL

    -- Error: El primer registro no es '01'
 SELECT
    SR_SUBETAPA,
    0, -1, 1,
    '01', 1,
    SR_ID_ARCHIVO
FROM #DELTA_002#
WHERE FTN_NO_LINEA = 1
  AND (FTC_CONTROL IS NULL OR TRIM(FTC_CONTROL) <> '01') -- válidos pero incorrectos como primer registro

    UNION ALL

    -- Error: El último registro no es '09'
    SELECT
    SR_SUBETAPA,
    0, -1, 1,
    '09', 1,
    SR_ID_ARCHIVO
FROM #DELTA_002# TMP
JOIN (
    SELECT MAX(FTN_NO_LINEA) AS FTN_NO_LINEA
    FROM #DELTA_002#
) MAX_REC
    ON TMP.FTN_NO_LINEA = MAX_REC.FTN_NO_LINEA
WHERE TMP.FTC_CONTROL IS NULL OR TRIM(TMP.FTC_CONTROL) <> '09'  -- válido pero incorrecto como último registro

    UNION ALL

    -- Error genérico: primer o último registro incorrecto
    SELECT
        SR_SUBETAPA,
        0, -1, 1,
        '00', 1,
        SR_ID_ARCHIVO
    FROM #DELTA_002# TMP
    JOIN (
        SELECT MAX(FTN_NO_LINEA) AS FTN_NO_LINEA
        FROM #DELTA_002#
    ) MAX_REC
    WHERE (
        (TMP.FTC_CONTROL IN ('01', '02', '03', '05') AND TMP.FTN_NO_LINEA = MAX_REC.FTN_NO_LINEA)
        OR (TMP.FTN_NO_LINEA = 1 AND TMP.FTC_CONTROL IN ('02', '03', '05', '09'))
    )

    UNION ALL

    -- Error: No hay registros tipo '02'
    SELECT
        TMP.SR_SUBETAPA,
        0, -1, 1,
        '00', 1,
        TMP.SR_ID_ARCHIVO
    FROM (
        SELECT DISTINCT SR_SUBETAPA, SR_ID_ARCHIVO
        FROM #DELTA_002#
    ) TMP
    LEFT JOIN (
        SELECT COUNT(*) AS TOTAL
        FROM #DELTA_002#
        WHERE FTC_CONTROL = '02'
    ) CONTEO ON 1 = 1
    WHERE CONTEO.TOTAL = 0
)
GROUP BY FTC_ID_SUBETAPA, FLC_DETALLE, CURRENT_TIMESTAMP, FTN_ID_ARCHIVO
