SELECT * FROM #temp_view_002#
UNION ALL
SELECT FTC_FOLIO, FTC_ID_SUBETAPA, SUM(FLN_TOTAL_REGISTROS) FLN_TOTAL_REGISTROS, SUM(FLN_REG_CUMPLIERON) FLN_REG_CUMPLIERON, SUM(FLN_REG_NO_CUMPLIERON) FLN_REG_NO_CUMPLIERON,
	FLC_VALIDACION, SUM(FLN_TOTAL_ERRORES) FLN_TOTAL_ERRORES, '00' FLC_DETALLE, FLD_FEC_REG, FLC_USU_REG, FTC_FOLIO_REL, FTN_ID_ARCHIVO
FROM #temp_view_002#
GROUP BY FTC_FOLIO, FTC_ID_SUBETAPA, FLC_VALIDACION, FLD_FEC_REG, FLC_USU_REG, FTC_FOLIO_REL, FTN_ID_ARCHIVO