SELECT
    COALESCE(META.FTC_FOLIO, NULL) AS FTC_FOLIO,
    META.SR_SUBETAPA AS FTC_ID_SUBETAPA,    
    '94' AS FLC_VALIDACION,    
    TO_TIMESTAMP(FROM_UTC_TIMESTAMP(CURRENT_TIMESTAMP, 'GMT-6')) AS FLD_FEC_REG,
    'DATABRICKS' AS FLC_USU_REG,
    '' AS FTC_FOLIO_REL,
    META.SR_ID_ARCHIVO AS FTN_ID_ARCHIVO,
    
    DET.FLC_DETALLE,
    COALESCE(DET.FLN_REG_CUMPLIERON, 0) AS FLN_REG_CUMPLIERON,
    COALESCE(DET.FLN_TOTAL_ERRORES, 0) AS FLN_TOTAL_ERRORES,
    COALESCE(DET.FLN_TOTAL_REGISTROS, 0) AS FLN_TOTAL_REGISTROS,
    COALESCE(DET.FLN_TOTAL_ERRORES, 0) AS FLN_REG_NO_CUMPLIERON

FROM (
    SELECT DISTINCT 
        SR_SUBETAPA,
        SR_ID_ARCHIVO,
        FTC_FOLIO
    FROM #DELTA_002#
) META
CROSS JOIN #DELTA_004# DET


