WITH
-- 1. Códigos válidos
TIPOS_VALIDOS AS (
  SELECT '01' AS FLC_DETALLE UNION ALL
  SELECT '02' UNION ALL
  SELECT '03' UNION ALL
  SELECT '05' UNION ALL
  SELECT '09'
),

-- 2. Registros que cumplieron (no tienen errores)
CONTEO_CUMPLIERON AS (
  SELECT 
    TI.FTC_CONTROL AS FLC_DETALLE,
    COUNT(*) AS FLN_REG_CUMPLIERON
  FROM #DELTA_002# TI
  LEFT JOIN #DELTA_003# TE
    ON TI.FTN_NO_LINEA = TE.FTN_NO_LINEA
  WHERE TE.FTN_NO_LINEA IS NULL
    AND TI.FTC_CONTROL IN ('01', '02', '03', '05', '09')
  GROUP BY TI.FTC_CONTROL
),

-- 3. Registros que no cumplieron (errores)
CONTEO_ERRORES AS (
  SELECT 
    DESC_ERROR AS FLC_DETALLE,
    COUNT(*) AS FLN_TOTAL_ERRORES
  FROM #DELTA_003#
  WHERE DESC_ERROR IN ('01','02','03','05','09')
  GROUP BY DESC_ERROR
),

-- 4. Unión por código con COALESCE
DATOS_COMBINADOS AS (
  SELECT 
    TV.FLC_DETALLE,
    COALESCE(CE.FLN_REG_CUMPLIERON, 0) AS FLN_REG_CUMPLIERON,
    COALESCE(ER.FLN_TOTAL_ERRORES, 0) AS FLN_TOTAL_ERRORES,
    COALESCE(CE.FLN_REG_CUMPLIERON, 0) + COALESCE(ER.FLN_TOTAL_ERRORES, 0) AS FLN_TOTAL_REGISTROS
  FROM TIPOS_VALIDOS TV
  LEFT JOIN CONTEO_CUMPLIERON CE ON TV.FLC_DETALLE = CE.FLC_DETALLE
  LEFT JOIN CONTEO_ERRORES ER ON TV.FLC_DETALLE = ER.FLC_DETALLE
),

-- 5. Total general '00'
TOTAL_GENERAL AS (
  SELECT
    '00' AS FLC_DETALLE,
    SUM(FLN_REG_CUMPLIERON) AS FLN_REG_CUMPLIERON,
    SUM(FLN_TOTAL_ERRORES) AS FLN_TOTAL_ERRORES,
    SUM(FLN_TOTAL_REGISTROS) AS FLN_TOTAL_REGISTROS
  FROM DATOS_COMBINADOS
)

-- 6. Unión final
SELECT * FROM DATOS_COMBINADOS
UNION ALL
SELECT * FROM TOTAL_GENERAL

ORDER BY 
  CASE WHEN FLC_DETALLE = '00' THEN 1 ELSE 0 END,
  FLC_DETALLE;

