SELECT 
    FTC_RFC_INFONA,
    FTC_CURP,
    FTC_NSS_INFONA,
    FTC_APELLIDO_PATER_INFONA,
    FTC_APELLIDO_MATER_INFONA,
    FTC_NOMBRE_INFONA,
    FTN_NUM_CTA_IND,
    FTC_NOMBRE_IMSS
FROM (
    SELECT 
        FTC_RFC_INFONA,
        FTC_CURP,
        FTC_NSS_INFONA,
        FTC_APELLIDO_PATER_INFONA,
        FTC_APELLIDO_MATER_INFONA,
        FTC_NOMBRE_INFONA,
        FTN_NUM_CTA_IND,
        FTC_NOMBRE_IMSS,
        ROW_NUMBER() OVER (PARTITION BY FTC_NSS_INFONA ORDER BY FTC_NSS_INFONA) AS rn
    FROM #CATALOG_SCHEMA#.TEMP_MAPEO_#SR_FOLIO#
) t
WHERE rn = 1

