SELECT DISTINCT FTC_RFC_INFONA
      ,FTC_CURP
      ,FTC_NSS_INFONA
      ,FTC_APELLIDO_PATER_INFONA
      ,FTC_APELLIDO_MATER_INFONA
      ,FTC_NOMBRE_INFONA
      ,FTN_CTA_AFORE
      ,FTC_NOMBRE_IMSS
FROM #CX_PRO_ESQUEMA#.#TL_PRO_MARCA_DESMARCA_INFO#
WHERE FTC_FOLIO_BITACORA = #SR_FOLIO#
ORDER BY FTN_CTA_AFORE, FTC_NSS_INFONA

