SELECT
    FTN_NUM_CTA_INVDUAL AS FTN_CTA_AFORE,
    SUM(FTN_SDO_AIVS) AS FTN_SDO_AIVS,
    SUM(FTN_SDO_AIVS_92) AS FTN_SDO_AIVS_92,
    FTN_VALOR_AIVS,
    SUM(FTN_MONTO_PESOS) AS FTN_MONTO_PESOS,
    SUM(FTN_MONTO_PESOS_92) AS FTN_MONTO_PESOS_92,
    FCN_ID_REGIMEN,
    FTD_FEH_ACT,
    FTC_USU_ACT,
    FTC_FOLIO_BITACORA
FROM #CX_PRO_ESQUEMA#.#TL_PRO_SUF_SALDOS#
WHERE FTC_FOLIO_BITACORA = #SR_FOLIO#
AND FTN_ID_SUBP = #SR_SUBPROCESO#
GROUP BY FTN_NUM_CTA_INVDUAL, FTN_VALOR_AIVS, FCN_ID_REGIMEN, FTD_FEH_ACT, FTC_USU_ACT, FTC_FOLIO_BITACORA

