SELECT 
    FTC_RFC_INFONA,
    FTC_CURP,
    FTC_NSS_INFONA,
    FTC_APELLIDO_PATER_INFONA,
    FTC_APELLIDO_MATER_INFONA,
    FTC_NOMBRE_INFONA,
    FTN_NUM_CTA_IND,
    FTC_NOMBRE_IMSS,
    CAST('#SR_FOLIO#' AS STRING) AS FTC_FOLIO
FROM #CATALOG_SCHEMA#.TEMP_REMDUP_#SR_FOLIO#

