SELECT
  C.FTC_FOLIO AS FTC_FOLIO
 ,97 AS FTN_ID_PROCESO
 ,C.FCN_ID_SUBPROCESO AS FTN_ID_SUBPROCESO
 ,C.FTN_NUM_CTA_INVDUAL   AS FTN_NUM_CTA_INVDUAL
 ,81 as FTN_ID_SIEFORE
,SUBCTA.FCN_ID_TIPO_SUBCTA AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,SUM(BAL_MOVS.FTN_DISP_ACCIONES) as FTN_MONTO_ACCIONES
, SUM(COALESCE(BAL_MOVS.FTN_DISP_ACCIONES,0) * COALESCE(V.FCN_VALOR_ACCION,0)) AS  FTN_MONTO_PESOS
,V.FCN_ID_VALOR_ACCION AS FTN_ID_VALOR_ACCION 
,185 AS FTN_ID_TIPO_MONTO
,FCN_ID_SALDO_OPERA AS FTN_ID_SALDO_OPERA
,181 AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C 
CROSS JOIN (
SELECT  CMOV.FRN_ID_MOV_SUBCTA
       ,MSUB.FCN_ID_SUBPROCESO
       ,MSUB.FCN_ID_TIPO_SUBCTA
       ,MSUB.FCN_ID_TIPO_MOV
       ,CMOV.FFN_ID_CONCEPTO_MOV
       ,CMOV.FCN_ID_TIPO_MONTO
       ,CAT.FCN_ID_TIPO_CAT AS TIPO_MOV
       ,FCN_ID_REGIMEN
FROM       CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CMOV
INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB ON CMOV.FRN_ID_MOV_SUBCTA = MSUB.FRN_ID_MOV_SUBCTA
INNER JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO CAT ON MSUB.FCN_ID_TIPO_MOV = CAT.FCN_ID_CAT_CATALOGO
INNER JOIN CIERREN.TCCRXGRAL_TIPO_CAT TCAT ON CAT.FCN_ID_TIPO_CAT = TCAT.FCN_ID_TIPO_CAT
INNER JOIN cierren.tccrxgral_tipo_subcta SUB ON  SUB.FCN_ID_TIPO_SUBCTA=MSUB.FCN_ID_TIPO_SUBCTA
WHERE  CMOV.FFB_VIGENCIA = 1
AND    MSUB.FRB_VIGENCIA = 1
AND    MSUB.FCN_ID_SUBPROCESO = #sr_subproceso#
AND    TCAT.FCN_ID_TIPO_CAT = 25
AND    TCAT.FCB_VIGENCIA = 1
AND    CAT.FCB_VIGENCIA = 1
AND    MSUB.FCN_ID_TIPO_SUBCTA in (15,16)
)SUBCTA
INNER JOIN CIERREN.TTAFOGRAL_BALANCE_MOVS BAL_MOVS
ON C.FTN_NUM_CTA_INVDUAL = BAL_MOVS.FTC_NUM_CTA_INVDUAL
AND SUBCTA.FCN_ID_TIPO_SUBCTA=BAL_MOVS.FCN_ID_TIPO_SUBCTA
INNER JOIN (
SELECT  
 FCN_ID_VALOR_ACCION
,FCD_FEH_ACCION
,FCN_VALOR_ACCION
,FCN_ID_REGIMEN
,FCN_ID_SIEFORE
FROM CIERREN.TCAFOGRAL_VALOR_ACCION V
WHERE FCN_ID_SIEFORE = 81
and FCN_ID_REGIMEN = 138
AND  TO_TIMESTAMP(TRUNC(V.FCD_FEH_ACCION),'DD-MM-YY HH24:MI:SS') = TO_TIMESTAMP(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'DD-MM-YY HH24:MI:SS')
)V
ON SUBCTA.FCN_ID_REGIMEN=V.FCN_ID_REGIMEN
AND BAL_MOVS.FCN_ID_SIEFORE = V.FCN_ID_SIEFORE
LEFT OUTER JOIN 
( SELECT FCN_ID_SALDO_OPERA, FCN_ID_SUBPROCESO
FROM CIERREN.TFAFOGRAL_CONFIG_SUBPROCESO CSUB
WHERE CSUB.FCN_ID_PROCESO = '97'
AND FCN_ID_SUBPROCESO = #sr_subproceso#) CS
ON  C.FCN_ID_SUBPROCESO=CS.FCN_ID_SUBPROCESO
WHERE C.FTC_FOLIO =#sr_folio#
AND C.FCN_ID_SUBPROCESO =#sr_subproceso#
AND (C.FTB_ESTATUS_MARCA=0 OR C.FCN_CONV_INGTY=0)
group by C.FTC_FOLIO,C.FCN_ID_SUBPROCESO,C.FTN_NUM_CTA_INVDUAL  
 ,V.FCN_ID_SIEFORE,SUBCTA.FCN_ID_TIPO_SUBCTA,V.FCN_ID_VALOR_ACCION,FCN_ID_SALDO_OPERA
