 SELECT
  A.FTC_FOLIO AS FTC_FOLIO
 ,97 AS FTN_ID_PROCESO
 ,A.FCN_ID_SUBPROCESO AS FTN_ID_SUBPROCESO
 ,A.FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL
 ,coalesce(V.FCN_ID_SIEFORE,81) as FTN_ID_SIEFORE
,SUBCTA.FCN_ID_TIPO_SUBCTA AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,coalesce(FTN_SDO_AIVS,0) as FTN_MONTO_ACCIONES
,COALESCE(FTN_MONTO_PESOS,0) + COALESCE(FTN_SDO_AIVS,0) AS  FTN_MONTO_PESOS
,NVL(V.FCN_ID_VALOR_ACCION,0) AS FTN_ID_VALOR_ACCION 
,SUBCTA.FCN_ID_TIPO_MONTO AS FTN_ID_TIPO_MONTO
,FCN_ID_SALDO_OPERA AS FTN_ID_SALDO_OPERA
,SUBCTA.FCN_ID_TIPO_MOV AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT
FROM (
SELECT 
DISTINCT
 FTN_NUM_CTA_INVDUAL        FTN_NUM_CTA_INVDUAL
,FTC_FOLIO
,FTN_NUM_APLI_INTE_VIVI92 as FTN_SDO_AIVS
,FTN_SALDO_TOT_VIVI92 as  FTN_MONTO_PESOS
,139 FCN_ID_REGIMEN
,17 AS FCN_ID_TIPO_SUBCTA
,FCN_ID_SUBPROCESO
FROM PROCESOS.TTAFOTRAS_DEVO_SALDO_EXC_FOV 
WHERE FTC_FOLIO = #sr_folio#  AND FTC_ESTATUS = '1'
AND FCN_ID_SUBPROCESO=#sr_subproceso#

UNION ALL 

SELECT 
DISTINCT FTN_NUM_CTA_INVDUAL        FTN_NUM_CTA_INVDUAL
,FTC_FOLIO
,FTN_NUM_APLI_INTE_VIVI08 as FTN_SDO_AIVS
,FTN_SALDO_TOT_VIVI08 as  FTN_MONTO_PESOS
,139 FCN_ID_REGIMEN
,18 AS FCN_ID_TIPO_SUBCTA
,FCN_ID_SUBPROCESO
FROM PROCESOS.TTAFOTRAS_DEVO_SALDO_EXC_FOV 
WHERE FTC_FOLIO = #sr_folio#  AND FTC_ESTATUS = '1'
AND FCN_ID_SUBPROCESO=#sr_subproceso#
) A
INNER JOIN (
SELECT  CMOV.FRN_ID_MOV_SUBCTA
       ,MSUB.FCN_ID_SUBPROCESO
       ,MSUB.FCN_ID_TIPO_SUBCTA
       ,MSUB.FCN_ID_TIPO_MOV
       ,CMOV.FFN_ID_CONCEPTO_MOV
       ,CMOV.FCN_ID_TIPO_MONTO
       ,CAT.FCN_ID_TIPO_CAT AS TIPO_MOV
       ,FCN_ID_REGIMEN
FROM       CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CMOV
INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB ON CMOV.FRN_ID_MOV_SUBCTA = MSUB.FRN_ID_MOV_SUBCTA
INNER JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO CAT ON MSUB.FCN_ID_TIPO_MOV = CAT.FCN_ID_CAT_CATALOGO
INNER JOIN CIERREN.TCCRXGRAL_TIPO_CAT TCAT ON CAT.FCN_ID_TIPO_CAT = TCAT.FCN_ID_TIPO_CAT
INNER JOIN cierren.tccrxgral_tipo_subcta SUB ON  SUB.FCN_ID_TIPO_SUBCTA=MSUB.FCN_ID_TIPO_SUBCTA
WHERE  CMOV.FFB_VIGENCIA = 1
AND    MSUB.FRB_VIGENCIA = 1
AND    MSUB.FCN_ID_SUBPROCESO =#sr_subproceso#
AND    TCAT.FCN_ID_TIPO_CAT = 25
AND    TCAT.FCB_VIGENCIA = 1
AND    CAT.FCB_VIGENCIA = 1
AND    MSUB.FCN_ID_TIPO_SUBCTA in (17,18)
)SUBCTA
ON A.FCN_ID_SUBPROCESO=SUBCTA.FCN_ID_SUBPROCESO
AND A.FCN_ID_TIPO_SUBCTA=SUBCTA.FCN_ID_TIPO_SUBCTA
AND A.FCN_ID_REGIMEN=SUBCTA.FCN_ID_REGIMEN
CROSS JOIN (
SELECT  
 FCN_ID_VALOR_ACCION
,FCD_FEH_ACCION
,FCN_VALOR_ACCION
,FCN_ID_REGIMEN
,FCN_ID_SIEFORE
FROM CIERREN.TCAFOGRAL_VALOR_ACCION V
WHERE FCN_ID_SIEFORE = 81
and FCN_ID_REGIMEN = 139
AND  TO_TIMESTAMP(TRUNC(V.FCD_FEH_ACCION),'DD-MM-YY HH24:MI:SS') = TO_TIMESTAMP(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'DD-MM-YY HH24:MI:SS')
)V
LEFT OUTER JOIN 
( SELECT FCN_ID_SALDO_OPERA, FCN_ID_SUBPROCESO
FROM CIERREN.TFAFOGRAL_CONFIG_SUBPROCESO CSUB
WHERE CSUB.FCN_ID_PROCESO = '97'
AND FCN_ID_SUBPROCESO = #sr_subproceso#) CS
ON  A.FCN_ID_SUBPROCESO=CS.FCN_ID_SUBPROCESO