WITH
TF_300_APLICA_REGLAS
AS
(
SELECT
 DP.FTC_FOLIO 
,DP.FCN_ID_SUBPROCESO
,DP.FCN_ID_SIEFORE 
,SUM(DP.FTN_SDO_PESOS) PESOS
,SUM(DP.FTN_SDO_ACCIONES)ACCIONES
,DP.FFN_ID_CONCEPTO_MOV
,1 AS CUENTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL DEVP 
LEFT JOIN PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL DP 
ON DEVP.FTC_FOLIO = DP.FTC_FOLIO AND DEVP.FCN_ID_SUBPROCESO = DP.FCN_ID_SUBPROCESO 
AND DEVP.FTN_NUM_CTA_INVDUAL =  DP.FTN_NUM_CTA_INVDUAL AND DEVP.FTN_CONSE_REG_LOTE = DP.FTN_CONSE_REG_LOTE 
WHERE  FFN_ID_CONCEPTO_MOV IN (4063, 4182, 4526, 4070, 4527, 4183, 4528, 4529, 4530)
AND DEVP.FTC_FOLIO = '#SR_FOLIO#' ---  Parametrizado
AND DEVP.FCN_ID_SUBPROCESO = #SR_SUBPROCESO# --- Parametrizado
AND DEVP.FTC_ESTATUS = '1'
GROUP BY  DP.FTC_FOLIO,DP.FCN_ID_SUBPROCESO,DP.FCN_ID_SIEFORE,DP.FFN_ID_CONCEPTO_MOV
UNION
SELECT
 DP.FTC_FOLIO 
,DP.FCN_ID_SUBPROCESO
,DP.FCN_ID_SIEFORE 
,SUM(DP.FTN_SDO_PESOS) PESOS
,SUM(DP.FTN_SDO_ACCIONES)ACCIONES
,DP.FFN_ID_CONCEPTO_MOV
,2 AS CUENTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL DEVP 
LEFT JOIN PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL DP 
ON DEVP.FTC_FOLIO = DP.FTC_FOLIO AND DEVP.FCN_ID_SUBPROCESO = DP.FCN_ID_SUBPROCESO 
AND DEVP.FTN_NUM_CTA_INVDUAL =  DP.FTN_NUM_CTA_INVDUAL AND DEVP.FTN_CONSE_REG_LOTE = DP.FTN_CONSE_REG_LOTE 
WHERE DP.FFN_ID_CONCEPTO_MOV = 4184
AND DEVP.FTC_FOLIO = '#SR_FOLIO#' ---  Parametrizado
AND DEVP.FCN_ID_SUBPROCESO = #SR_SUBPROCESO# --- Parametrizado
AND DEVP.FTC_ESTATUS = '1'
GROUP BY  DP.FTC_FOLIO,DP.FCN_ID_SUBPROCESO,DP.FCN_ID_SIEFORE,DP.FFN_ID_CONCEPTO_MOV
UNION
SELECT
 DP.FTC_FOLIO 
,DP.FCN_ID_SUBPROCESO
,DP.FCN_ID_SIEFORE 
,SUM(DP.FTN_SDO_PESOS) PESOS
,SUM(DP.FTN_SDO_ACCIONES)ACCIONES
,DP.FFN_ID_CONCEPTO_MOV
,3 AS CUENTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL DEVP 
LEFT JOIN PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL DP 
ON DEVP.FTC_FOLIO = DP.FTC_FOLIO AND DEVP.FCN_ID_SUBPROCESO = DP.FCN_ID_SUBPROCESO 
AND DEVP.FTN_NUM_CTA_INVDUAL =  DP.FTN_NUM_CTA_INVDUAL AND DEVP.FTN_CONSE_REG_LOTE = DP.FTN_CONSE_REG_LOTE 
WHERE DP.FFN_ID_CONCEPTO_MOV = 4072
AND DEVP.FTC_FOLIO = '#SR_FOLIO#' ---  Parametrizado
AND DEVP.FCN_ID_SUBPROCESO = #SR_SUBPROCESO# --- Parametrizado
AND DEVP.FTC_ESTATUS = '1'
GROUP BY  DP.FTC_FOLIO,DP.FCN_ID_SUBPROCESO,DP.FCN_ID_SIEFORE,DP.FFN_ID_CONCEPTO_MOV
),
TF_701_APLICA_REGLAS
AS
(
SELECT 
FTC_FOLIO,
FCN_ID_SUBPROCESO,
FCN_ID_SIEFORE,
CUENTA,
SUM(PESOS) AS PESOS,
SUM(ACCIONES) AS ACCIONES
FROM TF_300_APLICA_REGLAS
GROUP BY FTC_FOLIO,
FCN_ID_SUBPROCESO,
FCN_ID_SIEFORE,
CUENTA
ORDER BY FTC_FOLIO,FCN_ID_SUBPROCESO,FCN_ID_SIEFORE ASC
),DS_700_VALORES_ACEPTADOS
AS
(
SELECT
FTC_FOLIO,
FCN_ID_SUBPROCESO,
SUM(AIVS_ACEPTADOS_VIV) AS AIVS_ACEPTADOS_VIV,
SUM(IMP_ACEPTADOS_VIV) AS IMP_ACEPTADOS_VIV,
SUM(IMP_ACEPTADOS_RCV) AS IMP_ACEPTADOS_RCV,
SUM(IMP_ACEPTADOS_CS) AS IMP_ACEPTADOS_CS
FROM
(
SELECT
FTC_FOLIO,
FCN_ID_SUBPROCESO,
CASE WHEN CUENTA = 1 THEN PESOS ELSE 0 END AS IMP_ACEPTADOS_RCV,
CASE WHEN CUENTA = 2 THEN PESOS ELSE 0 END AS IMP_ACEPTADOS_CS,
CASE WHEN CUENTA = 3 THEN PESOS ELSE 0 END AS IMP_ACEPTADOS_VIV,
CASE WHEN CUENTA = 3 THEN ACCIONES ELSE 0 END AS AIVS_ACEPTADOS_VIV
FROM TF_701_APLICA_REGLAS
)
GROUP BY FTC_FOLIO,FCN_ID_SUBPROCESO
),
DB_100_TL_PRO_DPSJL_SUMARIO
AS
(
SELECT 
 FTC_FOLIO
,FCN_ID_SUBPROCESO 
,FTC_TIPO_REG
,FTC_IDENTI_SERV
,'56'  Id_Operacion
,'01'  Tipo_Entidad_Origen
,'534' Clave_Entidad_Origen
,'03'  Tipo_Entidad_Destino
,'001'  Clave_Entidad_Destino
,to_char(FTD_FEH_CRE_LOTE, 'YYYYMMDD') FTD_FEH_CRE_LOTE
,FTN_CONSEC_DIA
,FTN_NUM_REG_APORT_LOTE
,FTN_NUM_REG_CTAS_PAGAR
FROM PROCESOS.TTCRXGRAL_DEV_PSJL_SUMARIZADOS 
WHERE FTC_FOLIO = '#SR_FOLIO#'  ----  Parametrizado
and FCN_ID_SUBPROCESO = #SR_SUBPROCESO# ----  Parametrizado
and FTC_TIPO_REG= '09'
),
DB_200_TL_PRO_DEV_PAG_SJL
AS
(
SELECT FTC_FOLIO_BITACORA AS FTC_FOLIO, 
      FCN_ID_SUBPROCESO,
       SUM( ACEPTADOS) AS ACEPTADOS, 
       SUM(RECHAZADOS) AS RECHAZADOS, 
       SUM(ACEPTADOS)+SUM(RECHAZADOS) AS TOTAL 
  FROM (
        SELECT DISTINCT FTC_FOLIO_BITACORA,
                        FCN_ID_SUBPROCESO,
                        CASE WHEN FTC_ESTATUS=1 THEN NUMERO ELSE 0 END ACEPTADOS,
                        CASE WHEN FTC_ESTATUS=0 THEN NUMERO ELSE 0 END RECHAZADOS
                FROM (
                SELECT FTC_FOLIO AS FTC_FOLIO_BITACORA,
                       FCN_ID_SUBPROCESO,
                       FTC_ESTATUS,
                       COUNT(*) OVER (PARTITION BY FTC_ESTATUS) NUMERO
                  FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
                 WHERE FTC_FOLIO ='#SR_FOLIO#'
                   AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
              )
        )
  GROUP BY FTC_FOLIO_BITACORA,FCN_ID_SUBPROCESO
  ),
  JO_301_TOTALES
  AS
 ( 
SELECT  
SUMAR.FTC_FOLIO
,SUMAR.FCN_ID_SUBPROCESO 
,SUMAR.FTC_TIPO_REG
,SUMAR.FTC_IDENTI_SERV
,SUMAR.Id_Operacion
,SUMAR.Tipo_Entidad_Origen
,SUMAR.Clave_Entidad_Origen
,SUMAR.Tipo_Entidad_Destino
,SUMAR.Clave_Entidad_Destino
,SUMAR.FTD_FEH_CRE_LOTE
,SUMAR.FTN_CONSEC_DIA
,SUMAR.FTN_NUM_REG_APORT_LOTE
,SUMAR.FTN_NUM_REG_CTAS_PAGAR
,PG.ACEPTADOS
,PG.RECHAZADOS
,PG.TOTAL
,DS_700.AIVS_ACEPTADOS_VIV
,DS_700.IMP_ACEPTADOS_VIV
,DS_700.IMP_ACEPTADOS_RCV
,DS_700.IMP_ACEPTADOS_CS
FROM DB_100_TL_PRO_DPSJL_SUMARIO SUMAR
INNER JOIN DB_200_TL_PRO_DEV_PAG_SJL PG ON SUMAR.FTC_FOLIO = PG.FTC_FOLIO
                                        AND SUMAR.FCN_ID_SUBPROCESO = PG.FCN_ID_SUBPROCESO
LEFT JOIN DS_700_VALORES_ACEPTADOS DS_700 ON SUMAR.FTC_FOLIO = DS_700.FTC_FOLIO
                                        AND SUMAR.FCN_ID_SUBPROCESO = DS_700.FCN_ID_SUBPROCESO
)
SELECT
FTC_TIPO_REG,
FTC_IDENTI_SERV,
ID_OPERACION,
TIPO_ENTIDAD_ORIGEN,
CLAVE_ENTIDAD_ORIGEN,
TIPO_ENTIDAD_DESTINO,
CLAVE_ENTIDAD_DESTINO,
CASE WHEN FTD_FEH_CRE_LOTE IS NULL THEN RPAD('0',8,'0') ELSE LPAD(FTD_FEH_CRE_LOTE,8,'0') END AS FTD_FEH_CRE_LOTE,
CASE WHEN FTN_CONSEC_DIA IS NULL THEN RPAD('0',3,'0') ELSE LPAD(FTN_CONSEC_DIA,3,'0') END AS FTN_CONSEC_DIA,
CASE 
        WHEN IMP_ACEPTADOS_RCV IS NULL THEN RPAD('0',15,'0')
         ELSE
          LPAD(
        REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACEPTADOS_RCV), 1, INSTR(TO_CHAR(IMP_ACEPTADOS_RCV, 'FM9999999999.99'), '.') - 1),13,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACEPTADOS_RCV, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACEPTADOS_RCV, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
        ,'.','')
          ,15,'0') END AS IMP_ACEPTADOS_RCV,
 CASE 
        WHEN IMP_ACEPTADOS_VIV IS NULL THEN RPAD('0',15,'0')
         ELSE
          LPAD(
        REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACEPTADOS_VIV), 1, INSTR(TO_CHAR(IMP_ACEPTADOS_VIV, 'FM9999999999.99'), '.') - 1),13,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACEPTADOS_VIV, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACEPTADOS_VIV, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
        ,'.','')
          ,15,'0') END AS IMP_ACEPTADO_VIV,
CASE 
        WHEN IMP_ACEPTADOS_CS IS NULL THEN RPAD('0',15,'0')
         ELSE
          LPAD(
        REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACEPTADOS_CS), 1, INSTR(TO_CHAR(IMP_ACEPTADOS_CS, 'FM9999999999.99'), '.') - 1),13,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACEPTADOS_CS, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACEPTADOS_CS, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
  ,'.','')
          ,15,'0') END AS TOTAL_NUM_GUB,
CASE WHEN FTN_CONSEC_DIA IS NULL THEN RPAD('0',8,'0') ELSE LPAD(FTN_NUM_REG_APORT_LOTE,8,'0') END AS FTN_NUM_REG_APORT_LOTE,
CASE WHEN TO_CHAR(ACEPTADOS) IS NULL THEN LPAD('0',6,'0') ELSE LPAD(TO_CHAR(ACEPTADOS),6,'0') END AS NUM_APORT_ACEPTADAS,
CASE WHEN TO_CHAR(RECHAZADOS) IS NULL THEN LPAD('0',6,'0') ELSE LPAD(TO_CHAR(RECHAZADOS),6,'0') END AS NUM_APORT_RECHAZADAS,
RPAD('0',6,'0') AS NUM_APORT_PENDIENTES,
RPAD(' ',6,' ') AS NUM_REG_CUENTAS_PAGAR,
CASE WHEN TO_CHAR(TOTAL) IS NULL THEN LPAD('0',6,'0') ELSE LPAD(TO_CHAR(TOTAL),6,'0') END AS NUM_REG_TOTAL_LOTE,
CASE WHEN AIVS_ACEPTADOS_VIV IS NULL THEN RPAD(' ',19,' ')
ELSE
 LPAD(
REPLACE(
LPAD(SUBSTR(TO_CHAR(AIVS_ACEPTADOS_VIV), 1, INSTR(TO_CHAR(AIVS_ACEPTADOS_VIV, 'FM9999999999.99'), '.') - 1),13,'0') 
|| RPAD(SUBSTR(TRIM(TO_CHAR(AIVS_ACEPTADOS_VIV, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(AIVS_ACEPTADOS_VIV, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
,'.','')
,19,'0')
	  END AS NUM_AIVS_VIV,
RPAD(' ',171,' ') AS FILLER
FROM JO_301_TOTALES