WITH
TF_300_APLICA_REGLAS
AS
(
SELECT
 DP.FTC_FOLIO 
,DP.FCN_ID_SUBPROCESO
,DP.FCN_ID_SIEFORE 
,SUM(DP.FTN_SDO_PESOS) PESOS
,SUM(DP.FTN_SDO_ACCIONES)ACCIONES
,DP.FFN_ID_CONCEPTO_MOV
,1 AS CUENTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL DEVP 
LEFT JOIN PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL DP 
ON DEVP.FTC_FOLIO = DP.FTC_FOLIO AND DEVP.FCN_ID_SUBPROCESO = DP.FCN_ID_SUBPROCESO 
AND DEVP.FTN_NUM_CTA_INVDUAL =  DP.FTN_NUM_CTA_INVDUAL AND DEVP.FTN_CONSE_REG_LOTE = DP.FTN_CONSE_REG_LOTE 
WHERE  (
DP.FFN_ID_CONCEPTO_MOV = 4063 OR
DP.FFN_ID_CONCEPTO_MOV = 4182 OR
DP.FFN_ID_CONCEPTO_MOV = 4526 OR
DP.FFN_ID_CONCEPTO_MOV = 4070 OR
DP.FFN_ID_CONCEPTO_MOV = 4527 OR
DP.FFN_ID_CONCEPTO_MOV = 4183 OR
DP.FFN_ID_CONCEPTO_MOV = 4528 OR
DP.FFN_ID_CONCEPTO_MOV = 4529 OR
DP.FFN_ID_CONCEPTO_MOV = 4530
)
AND DEVP.FTC_FOLIO = '#SR_FOLIO#' ---  Parametrizado
AND DEVP.FCN_ID_SUBPROCESO = #SR_SUBPROCESOS# --- Parametrizado
AND DEVP.FTC_ESTATUS = '1'
GROUP BY  DP.FTC_FOLIO,DP.FCN_ID_SUBPROCESO,DP.FCN_ID_SIEFORE,DP.FFN_ID_CONCEPTO_MOV
--ORDER BY DP.FTC_FOLIO ,DP.FCN_ID_SUBPROCESO,DP.FCN_ID_SIEFORE ASC
UNION
SELECT
 DP.FTC_FOLIO 
,DP.FCN_ID_SUBPROCESO
,DP.FCN_ID_SIEFORE 
,SUM(DP.FTN_SDO_PESOS) PESOS
,SUM(DP.FTN_SDO_ACCIONES)ACCIONES
,DP.FFN_ID_CONCEPTO_MOV
,2 AS CUENTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL DEVP 
LEFT JOIN PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL DP 
ON DEVP.FTC_FOLIO = DP.FTC_FOLIO AND DEVP.FCN_ID_SUBPROCESO = DP.FCN_ID_SUBPROCESO 
AND DEVP.FTN_NUM_CTA_INVDUAL =  DP.FTN_NUM_CTA_INVDUAL AND DEVP.FTN_CONSE_REG_LOTE = DP.FTN_CONSE_REG_LOTE 
WHERE DP.FFN_ID_CONCEPTO_MOV = 4184
AND DEVP.FTC_FOLIO = '#SR_FOLIO#' ---  Parametrizado
AND DEVP.FCN_ID_SUBPROCESO = #SR_SUBPROCESOS# --- Parametrizado
AND DEVP.FTC_ESTATUS = '1'
GROUP BY  DP.FTC_FOLIO,DP.FCN_ID_SUBPROCESO,DP.FCN_ID_SIEFORE,DP.FFN_ID_CONCEPTO_MOV
UNION
SELECT
 DP.FTC_FOLIO 
,DP.FCN_ID_SUBPROCESO
,DP.FCN_ID_SIEFORE 
,SUM(DP.FTN_SDO_PESOS) PESOS
,SUM(DP.FTN_SDO_ACCIONES)ACCIONES
,DP.FFN_ID_CONCEPTO_MOV
,3 AS CUENTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL DEVP 
LEFT JOIN PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL DP 
ON DEVP.FTC_FOLIO = DP.FTC_FOLIO AND DEVP.FCN_ID_SUBPROCESO = DP.FCN_ID_SUBPROCESO 
AND DEVP.FTN_NUM_CTA_INVDUAL =  DP.FTN_NUM_CTA_INVDUAL AND DEVP.FTN_CONSE_REG_LOTE = DP.FTN_CONSE_REG_LOTE 
WHERE DP.FFN_ID_CONCEPTO_MOV = 4072
AND DEVP.FTC_FOLIO = '#SR_FOLIO#' ---  Parametrizado
AND DEVP.FCN_ID_SUBPROCESO = #SR_SUBPROCESOS# --- Parametrizado
AND DEVP.FTC_ESTATUS = '1'
GROUP BY  DP.FTC_FOLIO,DP.FCN_ID_SUBPROCESO,DP.FCN_ID_SIEFORE,DP.FFN_ID_CONCEPTO_MOV
),
TF_701_APLICA_REGLAS
AS
(
SELECT 
FTC_FOLIO,
FCN_ID_SUBPROCESO,
FCN_ID_SIEFORE,
CUENTA,
SUM(PESOS) AS PESOS,
SUM(ACCIONES) AS ACCIONES
FROM TF_300_APLICA_REGLAS
GROUP BY FTC_FOLIO,
FCN_ID_SUBPROCESO,
FCN_ID_SIEFORE,
CUENTA
ORDER BY FTC_FOLIO,FCN_ID_SUBPROCESO,FCN_ID_SIEFORE ASC
)
SELECT
FTC_FOLIO,
FCN_ID_SUBPROCESO,
CASE WHEN CUENTA = 1 THEN PESOS ELSE 0 END AS IMP_ACEPTADOS_RCV,
CASE WHEN CUENTA = 2 THEN PESOS ELSE 0 END AS IMP_ACEPTADOS_CS,
CASE WHEN CUENTA = 3 THEN PESOS ELSE 0 END AS IMP_ACEPTADOS_VIV,
CASE WHEN CUENTA = 3 THEN ACCIONES ELSE 0 END AS AIVS_ACEPTADOS_VIV
FROM TF_701_APLICA_REGLAS