SELECT
'01' AS TIPO_REGISTRO,
'03' AS ID_SERVICIO,
'56' AS ID_OPERACION,
'01'TIPO_ENT_ORIGEN,
'534' AS CVE_ENT_ORIGEN,
'03' AS TIPO_ENT_DESTINO,
'001' AS CVE_ENT_DESTINO,
FECHA_CREACION_LOTE,
CONSECUTIVO_DIA,
FECHA_LIMITE_RESPUESTA,
RPAD(' ',2,' ') AS RESULTADO_OPERA,
RPAD(' ',3,' ') AS DIAGNOSTICO1,
RPAD(' ',3,' ') AS DIAGNOSTICO2,
RPAD(' ',3,' ') AS DIAGNOSTICO3,
RPAD(' ',254,' ') AS FILLER
FROM
(
SELECT 
DISTINCT
TRIM(SUBSTR(FTC_LINEA,17,8)) FECHA_CREACION_LOTE,
TRIM(SUBSTR(FTC_LINEA,25,3)) CONSECUTIVO_DIA,
TRIM(SUBSTR(FTC_LINEA,28,8)) FECHA_LIMITE_RESPUESTA
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL DEV 
INNER JOIN CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO ARC ON DEV.FTN_ID_ARCHIVO = ARC.FTN_ID_ARCHIVO
WHERE DEV.FTC_FOLIO = '#SR_FOLIO#' 
AND  DEV.FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
AND SUBSTR(ARC.FTC_LINEA,1,2) = '01'
)