WITH SF_300_ARCH_RESP_3832 AS
(
SELECT 1 AS ORDEN, 
TIPO_REGISTRO||
ID_SERVICIO||
ID_OPERACION||
TIPO_ENT_ORIGEN||
CVE_ENT_ORIGEN||
TIPO_ENT_DESTINO||
CVE_ENT_DESTINO||
FECHA_CREACION_LOTE||
CONSECUTIVO_DIA||
FECHA_LIMITE_RESPUESTA||
RESULTADO_OPERA||
DIAGNOSTICO1||
DIAGNOSTICO2||
DIAGNOSTICO3||
FILLER 
AS TEXTO
FROM #DELTA_DPSJL_ENCABEZADO#
UNION ALL
SELECT 2 AS ORDEN,
TIPO_REGISTRO||
IDENTIFICADOR_SERVICIO||
FTN_CONSE_REG_LOTE||
FTC_NSS||
FTC_CLAVE_ENT_ORIG||
FTC_RFC_TRABA||
FTC_CURP||
FTC_NOMBRE||
FTN_PERIODO_PAGO||
FTD_FEH_PAGO||
FTD_FEH_VALOR_RCV||
FTD_FEH_VALOR_VIV||
FTN_FOLIO_SUA||
FNC_CVE_ENT_RECEP||
FNC_REG_PATRN_IMSS||
IMP_RETIRO||
IMP_CV_PATR||
IMP_CV_TRAB||
IMP_CS||
IMP_ACT_RETIRO||
IMP_ACT_CV_PATR||
IMP_ACT_CV_TRAB||
PESOS_VIV97||
FNN_DIAS_COTZDOS_BIM_DEV||
AIVS_VIV97||
IMP_ACT_REN_RETIRO||
IMP_ACT_REN_CV_PATR||
IMP_ACT_REN_CV_TRAR||
FTD_FEH_ENV_ORG_SOL_PROC||
FTC_DIAG_DEV||
FTC_MOT_DEV||
FTC_RES_OPERACION||
FTC_DIAGNOSTICO1||
FTC_DIAGNOSTICO2||
FTC_DIAGNOSTICO3||
FILLER AS TEXTO
FROM #DELTA_DPSJL_DETALLE#
UNION ALL
SELECT 3 AS ORDEN,
 FTC_TIPO_REG||
FTC_IDENTI_SERV||
ID_OPERACION||
TIPO_ENTIDAD_ORIGEN||
CLAVE_ENTIDAD_ORIGEN||
TIPO_ENTIDAD_DESTINO||
CLAVE_ENTIDAD_DESTINO||
FTD_FEH_CRE_LOTE||
FTN_CONSEC_DIA||
IMP_ACEPTADOS_RCV||
IMP_ACEPTADO_VIV||
TOTAL_NUM_GUB||
FTN_NUM_REG_APORT_LOTE||
NUM_APORT_ACEPTADAS||
NUM_APORT_RECHAZADAS||
NUM_APORT_PENDIENTES||
NUM_REG_CUENTAS_PAGAR||
NUM_REG_TOTAL_LOTE||
NUM_AIVS_VIV||
FILLER
 AS TEXTO
FROM #DELTA_DPSJL_SUMARIO# 
)
SELECT TEXTO FROM SF_300_ARCH_RESP_3832
ORDER BY ORDEN ASC