WITH
DB_100_DEV_PAG_SJL
AS 
(
SELECT
 DEV.FTC_TIPO_REG
,DEV.FTC_IDENTI_SERV 
,DEV.FTN_NUM_CTA_INVDUAL
,DEV.FTC_FOLIO
,DEV.FCN_ID_SUBPROCESO 
,DEV.FTN_CONSE_REG_LOTE
,DEV.FTC_NSS
,DEV.FTC_CLAVE_ENT_ORIG
,DEV.FTC_RFC_TRABA
,DEV.FTC_CURP
,DEV.FTC_NOMBRE
,DEV.FTN_PERIODO_PAGO
,to_char(DEV.FTD_FEH_PAGO,'YYYYMMDD') FTD_FEH_PAGO
,to_char(DEV.FTD_FEH_VALOR_RCV,'YYYYMMDD') FTD_FEH_VALOR_RCV
,to_char(DEV.FTD_FEH_VALOR_VIV,'YYYYMMDD') FTD_FEH_VALOR_VIV
,lpad(NVL(DEV.FTN_FOLIO_SUA,'000000'),6,'0') FTN_FOLIO_SUA
,DEV.FNC_CVE_ENT_RECEP
,DEV.FNC_REG_PATRN_IMSS
,LPAD(NVL(DEV.FNN_DIAS_COTZDOS_BIM_DEV,'00'),2,'0') FNN_DIAS_COTZDOS_BIM_DEV 
,to_char(DEV.FTD_FEH_ENV_ORG_SOL_PROC,'YYYYMMDD')FTD_FEH_ENV_ORG_SOL_PROC
,DEV.FTC_DIAG_DEV
,DEV.FTC_MOT_DEV
,DEV.FTC_RES_OPERACION
,DEV.FTC_DIAGNOSTICO1
,DEV.FTC_DIAGNOSTICO2
,DEV.FTC_DIAGNOSTICO3
,DEV.FTC_ESTATUS
,DEV.FCN_ID_MOTIVO_RECHAZO
,SUM((NVL(DEV.FTN_IMP_RET_DEVOLVER,0)))        IMP_RETIRO_ORIG
,SUM((NVL(DEV.FTN_IMP_ACT_REC_RETIRO_DEV,0)))  IMP_ACT_RETIRO_ORIG 
,SUM((NVL(DEV.FTN_IMP_ACT_RET_REN_CUENTA,0)))  IMP_ACT_REN_RETIRO_ORIG
,SUM((NVL(DEV.FTN_IMP_CES_CUO_PATRON_DEV,0)))  IMP_CV_PATR_ORIG
,SUM((NVL(DEV.FTN_IMP_CES_CUO_TRABAJ_DEV,0)))  IMP_CV_TRAB_ORIG
,SUM((NVL(DEV.FTN_IMP_ACT_REC_CUO_PAT_DEV,0))) IMP_ACT_CV_PATR_ORIG
,SUM((NVL(DEV.FTN_IMP_ACT_REC_CUO_TRA_DEV,0))) IMP_ACT_CV_TRAB_ORIG
,SUM((NVL(DEV.FTN_IMP_ACT_REN_CUE_IND_PAT,0))) IMP_ACT_REN_CV_PATR_ORIG
,SUM((NVL(DEV.FTN_IMP_ACT_REN_CUE_IND_TRA,0))) IMP_ACT_REN_CV_TRAR_ORIG
,SUM((NVL(DEV.FTN_IMP_CUO_SOCIAL_DEV,0)))      IMP_CS_ORIG
,SUM((NVL(DEV.FTN_NUM_APLI_VIV_APOR_PAT_DEV,0)))AIVS_VIV97_ORIG
,SUM((NVL(DEV.FTN_IMP_APOR_PAT_VIV_DEV,0)))      PESOS_VIV97_ORIG
FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL DEV
WHERE 1=1
AND DEV.FTC_FOLIO = '#SR_FOLIO#'
AND DEV.FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
AND DEV.FTC_TIPO_REG = '02'
GROUP BY 
 DEV.FTC_TIPO_REG
,DEV.FTC_IDENTI_SERV 
,DEV.FTN_NUM_CTA_INVDUAL
,DEV.FTC_FOLIO
,DEV.FCN_ID_SUBPROCESO 
,DEV.FTN_CONSE_REG_LOTE
,DEV.FTC_NSS
,DEV.FTC_CLAVE_ENT_ORIG
,DEV.FTC_RFC_TRABA
,DEV.FTC_CURP
,DEV.FTC_NOMBRE
,DEV.FTN_PERIODO_PAGO
,to_char(DEV.FTD_FEH_PAGO,'YYYYMMDD') 
,to_char(DEV.FTD_FEH_VALOR_RCV,'YYYYMMDD') 
,to_char(DEV.FTD_FEH_VALOR_VIV,'YYYYMMDD')
,lpad(NVL(DEV.FTN_FOLIO_SUA,'000000'),6,'0') 
,DEV.FNC_CVE_ENT_RECEP
,DEV.FNC_REG_PATRN_IMSS
,LPAD(NVL(DEV.FNN_DIAS_COTZDOS_BIM_DEV,'00'),2,'0')
,to_char(DEV.FTD_FEH_ENV_ORG_SOL_PROC,'YYYYMMDD')
,DEV.FTC_DIAG_DEV
,DEV.FTC_MOT_DEV
,DEV.FTC_RES_OPERACION
,DEV.FTC_DIAGNOSTICO1
,DEV.FTC_DIAGNOSTICO2
,DEV.FTC_DIAGNOSTICO3
,DEV.FTC_ESTATUS
,DEV.FCN_ID_MOTIVO_RECHAZO
),
DB_200_VAL_SDOS_DPSJL
AS
(
SELECT
FTC_FOLIO,
FCN_ID_SUBPROCESO,
FTN_CONSE_REG_LOTE,
FTN_NUM_CTA_INVDUAL,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4063 THEN FTN_SDO_PESOS  ELSE 0 END) AS IMP_RETIRO,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4182 THEN FTN_SDO_PESOS  ELSE 0 END) AS IMP_ACT_RETIRO,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4526 THEN FTN_SDO_PESOS  ELSE 0 END) AS IMP_ACT_REN_RETIRO,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4070 THEN FTN_SDO_PESOS  ELSE 0 END) AS IMP_CV_PATR,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4527 THEN FTN_SDO_PESOS  ELSE 0 END) AS IMP_CV_TRAB,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4183 THEN FTN_SDO_PESOS  ELSE 0 END) AS IMP_ACT_CV_PATR,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4528 THEN FTN_SDO_PESOS  ELSE 0 END) AS IMP_ACT_CV_TRAB,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4529 THEN FTN_SDO_PESOS  ELSE 0 END) AS IMP_ACT_REN_CV_PATR,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4530 THEN FTN_SDO_PESOS  ELSE 0 END) AS IMP_ACT_REN_CV_TRAR,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4184 THEN FTN_SDO_PESOS  ELSE 0 END) AS IMP_CS,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4072 THEN FTN_SDO_PESOS  ELSE 0 END)AS PESOS_VIV97,
SUM(CASE WHEN FFN_ID_CONCEPTO_MOV = 4072 THEN FTN_SDO_ACCIONES  ELSE 0 END) AS AIVS_VIV97
FROM
(
SELECT 
 VSD.FTC_FOLIO
,VSD.FTN_CONSE_REG_LOTE
,VSD.FTN_NUM_CTA_INVDUAL
,VSD.FTN_SDO_ACCIONES
,VSD.FTN_SDO_PESOS
,VSD.FFN_ID_CONCEPTO_MOV
,VSD.FCN_ID_SUBPROCESO
FROM PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL VSD
WHERE 1=1
AND VSD.FTC_FOLIO = '#SR_FOLIO#' 
AND VSD.FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
)
GROUP BY 
FTC_FOLIO,
FCN_ID_SUBPROCESO,
FTN_CONSE_REG_LOTE,
FTN_NUM_CTA_INVDUAL
),
BD_400_MAP_NCI_RECHAZO
AS
(
SELECT 
C.FCN_ID_MOTIVO_RECHAZO,
I.TMN_CVE_ITGY
FROM(
SELECT FCN_ID_CAT_CATALOGO AS TMN_CVE_NCI,
CASE 
WHEN FCN_ID_TIPO_CAT=3   THEN FCN_ID_CAT_CATALOGO ---RECHAZO PROCESO NCI
WHEN FCN_ID_TIPO_CAT=20  THEN FCN_ID_CAT_CATALOGO ---RECHAZOS IDC
WHEN FCN_ID_TIPO_CAT=223 THEN TO_NUMBER(FCC_VALOR)---RECHAZOS VIVENDA 
WHEN FCN_ID_TIPO_CAT=291 THEN TO_NUMBER(FCC_VALOR)---RECHAZOS VIVENDA 
END FCN_ID_MOTIVO_RECHAZO
FROM CIERREN.TCCRXGRAL_CAT_CATALOGO  
WHERE FCN_ID_TIPO_CAT IN (3,20,223,291)
)C
INNER JOIN CIERREN.TMSISGRAL_MAP_NCI_ITGY I 
ON C.TMN_CVE_NCI=I.TMN_CVE_NCI
WHERE I.TMC_USO='MOTIVO DE RECHAZO PARA PROCESAR DE DPSJL'
),
TF_600_APLICA_REGLAS
AS
(
SELECT
DB_100.FTC_TIPO_REG,
DB_100.FTC_IDENTI_SERV,
DB_100.FTN_NUM_CTA_INVDUAL,
DB_100.FTC_FOLIO,
DB_100.FCN_ID_SUBPROCESO,
TRIM(DB_100.FTN_CONSE_REG_LOTE) AS FTN_CONSE_REG_LOTE,
DB_100.FTC_NSS,
DB_100.FTC_CLAVE_ENT_ORIG,
DB_100.FTC_RFC_TRABA,
DB_100.FTC_CURP,
DB_100.FTC_NOMBRE,
DB_100.FTN_PERIODO_PAGO,
DB_100.FTD_FEH_PAGO,
DB_100.FTD_FEH_VALOR_RCV,
DB_100.FTD_FEH_VALOR_VIV,
DB_100.FTN_FOLIO_SUA,
DB_100.FNC_CVE_ENT_RECEP,
DB_100.FNC_REG_PATRN_IMSS,
DB_100.FNN_DIAS_COTZDOS_BIM_DEV,
DB_100.FTD_FEH_ENV_ORG_SOL_PROC,
DB_100.FTC_DIAG_DEV,
DB_100.FTC_MOT_DEV,
DB_100.FTC_RES_OPERACION,
DB_100.FTC_DIAGNOSTICO1,
DB_100.FTC_DIAGNOSTICO2,
DB_100.FTC_DIAGNOSTICO3,
DB_100.FTC_ESTATUS,
DB_100.FCN_ID_MOTIVO_RECHAZO,
DB_100.IMP_RETIRO_ORIG,
DB_100.IMP_ACT_RETIRO_ORIG,
DB_100.IMP_ACT_REN_RETIRO_ORIG,
DB_100.IMP_CV_PATR_ORIG,
DB_100.IMP_CV_TRAB_ORIG,
DB_100.IMP_ACT_CV_PATR_ORIG,
DB_100.IMP_ACT_CV_TRAB_ORIG,
DB_100.IMP_ACT_REN_CV_PATR_ORIG,
DB_100.IMP_ACT_REN_CV_TRAR_ORIG,
DB_100.IMP_CS_ORIG,
DB_100.AIVS_VIV97_ORIG,
DB_100.PESOS_VIV97_ORIG,
DB_200.IMP_RETIRO,
DB_200.IMP_ACT_RETIRO,
DB_200.IMP_ACT_REN_RETIRO,
DB_200.IMP_CV_PATR,
DB_200.IMP_CV_TRAB,
DB_200.IMP_ACT_CV_PATR,
DB_200.IMP_ACT_CV_TRAB,
DB_200.IMP_ACT_REN_CV_PATR,
DB_200.IMP_ACT_REN_CV_TRAR,
DB_200.IMP_CS,
DB_200.PESOS_VIV97,
DB_200.AIVS_VIV97,
TRIM(DB_400.TMN_CVE_ITGY) AS vMotRej,
CASE WHEN DB_100.FTC_ESTATUS = '0' THEN '02' ELSE DB_100.FTC_DIAG_DEV END AS vDiagnostico
FROM DB_100_DEV_PAG_SJL DB_100
LEFT JOIN DB_200_VAL_SDOS_DPSJL DB_200 ON DB_100.FTC_FOLIO = DB_200.FTC_FOLIO
                                       AND DB_100.FCN_ID_SUBPROCESO = DB_200.FCN_ID_SUBPROCESO
                                       AND DB_100.FTN_NUM_CTA_INVDUAL = DB_200.FTN_NUM_CTA_INVDUAL
                                       AND DB_100.FTN_CONSE_REG_LOTE = DB_200.FTN_CONSE_REG_LOTE
LEFT JOIN BD_400_MAP_NCI_RECHAZO DB_400 ON  DB_100.FCN_ID_MOTIVO_RECHAZO = DB_400.FCN_ID_MOTIVO_RECHAZO
ORDER BY DB_100.FTN_CONSE_REG_LOTE ASC
)
SELECT
CASE WHEN FTC_TIPO_REG IS NULL THEN LPAD(' ',2,' ') ELSE LPAD(FTC_TIPO_REG,2,' ') END AS TIPO_REGISTRO,
CASE WHEN FTC_IDENTI_SERV IS NULL THEN LPAD(' ',2,' ') ELSE LPAD(FTC_IDENTI_SERV,2,' ') END AS IDENTIFICADOR_SERVICIO,
CASE WHEN FTN_CONSE_REG_LOTE IS NULL THEN LPAD('0',8,'0') ELSE LPAD(FTN_CONSE_REG_LOTE,8,'0') END AS FTN_CONSE_REG_LOTE,
CASE WHEN FTC_NSS IS NULL THEN LPAD(' ',11,' ') ELSE LPAD(FTC_NSS,11,' ') END AS FTC_NSS,
CASE WHEN FTC_CLAVE_ENT_ORIG IS NULL THEN LPAD(' ',3,' ') ELSE LPAD(FTC_CLAVE_ENT_ORIG,3,' ') END AS FTC_CLAVE_ENT_ORIG,
CASE WHEN FTC_RFC_TRABA IS NULL THEN LPAD(' ',13,' ') ELSE LPAD(FTC_RFC_TRABA,13,' ') END AS FTC_RFC_TRABA,
CASE WHEN FTC_CURP IS NULL THEN LPAD(' ',18,' ') ELSE LPAD(FTC_CURP,18,' ') END AS FTC_CURP,
CASE WHEN FTC_NOMBRE IS NULL THEN LPAD(' ',50,' ') ELSE LPAD(FTC_NOMBRE,50,' ') END AS FTC_NOMBRE,
CASE WHEN FTN_PERIODO_PAGO IS NULL THEN LPAD('0',6,'0') ELSE LPAD(FTN_PERIODO_PAGO,6,'0') END AS FTN_PERIODO_PAGO,
CASE WHEN FTD_FEH_PAGO IS NULL THEN LPAD('0',8,'0') ELSE LPAD(FTD_FEH_PAGO,8,'0') END AS FTD_FEH_PAGO,
CASE WHEN FTD_FEH_VALOR_RCV IS NULL THEN LPAD('0',8,'0') ELSE LPAD(FTD_FEH_VALOR_RCV,8,'0') END AS FTD_FEH_VALOR_RCV,
CASE WHEN FTD_FEH_VALOR_VIV IS NULL THEN LPAD('0',8,'0') ELSE LPAD(FTD_FEH_VALOR_VIV,8,'0') END AS FTD_FEH_VALOR_VIV,
FTN_FOLIO_SUA,
CASE WHEN FNC_CVE_ENT_RECEP IS NULL THEN LPAD('0',3,'0') ELSE LPAD(FNC_CVE_ENT_RECEP,3,'0') END AS FNC_CVE_ENT_RECEP,
CASE WHEN FNC_REG_PATRN_IMSS IS NULL THEN LPAD(' ',11,' ') ELSE LPAD(FNC_REG_PATRN_IMSS,11,' ') END AS FNC_REG_PATRN_IMSS,
CASE WHEN FTC_ESTATUS = '1' 
     THEN CASE WHEN IMP_RETIRO IS NULL THEN LPAD('0',9,'0')
       ELSE LPAD(
       REPLACE(       
              LPAD(SUBSTR(TO_CHAR(IMP_RETIRO), 1, INSTR(TO_CHAR(IMP_RETIRO, 'FM9999999999.99'), '.') - 1),7,'0') 
              ||RPAD(SUBSTR(TRIM(TO_CHAR(IMP_RETIRO, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_RETIRO, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
    ,9,'0') END 
 ELSE LPAD(
       REPLACE(
              LPAD(SUBSTR(TO_CHAR(IMP_RETIRO_ORIG), 1, INSTR(TO_CHAR(IMP_RETIRO_ORIG, 'FM9999999999.99'), '.') - 1),7,'0') 
              ||RPAD(SUBSTR(TRIM(TO_CHAR(IMP_RETIRO_ORIG, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_RETIRO_ORIG, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
    ,9,'0')   END AS IMP_RETIRO,
    
CASE WHEN FTC_ESTATUS = '1' 
    THEN CASE WHEN IMP_CV_PATR IS NULL THEN RPAD('0',9,'0')
          ELSE LPAD(
              REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_CV_PATR), 1, INSTR(TO_CHAR(IMP_CV_PATR, 'FM9999999999.99'), '.') - 1),7,'0') 
   || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_CV_PATR, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_CV_PATR, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
              ,'.','')
          ,9,'0') END
   ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_CV_PATR_ORIG), 1, INSTR(TO_CHAR(IMP_CV_PATR_ORIG, 'FM9999999999.99'), '.') - 1),7,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_CV_PATR_ORIG, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_CV_PATR_ORIG, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END AS IMP_CV_PATR,
              
 CASE WHEN FTC_ESTATUS = '1' 
    THEN CASE WHEN IMP_CV_TRAB IS NULL THEN RPAD('0',9,'0')
          ELSE LPAD(
    REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_CV_TRAB), 1, INSTR(TO_CHAR(IMP_CV_TRAB, 'FM9999999999.99'), '.') - 1),7,'0') 
   || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_CV_TRAB, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_CV_TRAB, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
    ,'.','')
          ,9,'0') END
   ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_CV_TRAB_ORIG), 1, INSTR(TO_CHAR(IMP_CV_TRAB_ORIG, 'FM9999999999.99'), '.') - 1),7,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_CV_TRAB_ORIG, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_CV_TRAB_ORIG, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END AS IMP_CV_TRAB,

 CASE WHEN FTC_ESTATUS = '1' 
    THEN CASE WHEN IMP_CS IS NULL THEN RPAD('0',9,'0')
          ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_CS), 1, INSTR(TO_CHAR(IMP_CS, 'FM9999999999.99'), '.') - 1),7,'0') 
   || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_CS, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_CS, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
              ,'.','')
          ,9,'0') END
   ELSE LPAD(
    REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_CS_ORIG), 1, INSTR(TO_CHAR(IMP_CS_ORIG, 'FM9999999999.99'), '.') - 1),7,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_CS_ORIG, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_CS_ORIG, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
    ,'.','')
          ,9,'0') END AS IMP_CS,

 CASE WHEN FTC_ESTATUS = '1' 
    THEN CASE WHEN IMP_ACT_RETIRO IS NULL THEN RPAD('0',9,'0')
          ELSE LPAD(
 REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_RETIRO), 1, INSTR(TO_CHAR(IMP_ACT_RETIRO, 'FM9999999999.99'), '.') - 1),7,'0') 
   || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_RETIRO, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_RETIRO, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
 ,'.','')
          ,9,'0') END
   ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_RETIRO_ORIG), 1, INSTR(TO_CHAR(IMP_ACT_RETIRO_ORIG, 'FM9999999999.99'), '.') - 1),7,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_RETIRO_ORIG, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_RETIRO_ORIG, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END AS IMP_ACT_RETIRO,

 CASE WHEN FTC_ESTATUS = '1' 
    THEN CASE WHEN IMP_ACT_RETIRO IS NULL THEN RPAD('0',9,'0')
          ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_CV_PATR), 1, INSTR(TO_CHAR(IMP_ACT_CV_PATR, 'FM9999999999.99'), '.') - 1),7,'0') 
   || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_CV_PATR, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_CV_PATR, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END
   ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_CV_PATR_ORIG), 1, INSTR(TO_CHAR(IMP_ACT_CV_PATR_ORIG, 'FM9999999999.99'), '.') - 1),7,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_CV_PATR_ORIG, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_CV_PATR_ORIG, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END AS IMP_ACT_CV_PATR,

 CASE WHEN FTC_ESTATUS = '1' 
    THEN CASE WHEN IMP_ACT_CV_TRAB IS NULL THEN RPAD('0',9,'0')
          ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_CV_TRAB), 1, INSTR(TO_CHAR(IMP_ACT_CV_TRAB, 'FM9999999999.99'), '.') - 1),7,'0') 
   || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_CV_TRAB, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_CV_TRAB, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END
   ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_CV_TRAB_ORIG), 1, INSTR(TO_CHAR(IMP_ACT_CV_TRAB_ORIG, 'FM9999999999.99'), '.') - 1),7,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_CV_TRAB_ORIG, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_CV_TRAB_ORIG, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END AS IMP_ACT_CV_TRAB,

 CASE WHEN FTC_ESTATUS = '1' AND FTC_CLAVE_ENT_ORIG = '002'
    THEN CASE WHEN PESOS_VIV97 IS NULL THEN RPAD('0',9,'0')
          ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(PESOS_VIV97), 1, INSTR(TO_CHAR(PESOS_VIV97, 'FM9999999999.99'), '.') - 1),7,'0') 
   || RPAD(SUBSTR(TRIM(TO_CHAR(PESOS_VIV97, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(PESOS_VIV97, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END
   ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(PESOS_VIV97_ORIG), 1, INSTR(TO_CHAR(PESOS_VIV97_ORIG, 'FM9999999999.99'), '.') - 1),7,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(PESOS_VIV97_ORIG, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(PESOS_VIV97_ORIG, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END AS PESOS_VIV97,
FNN_DIAS_COTZDOS_BIM_DEV,

 CASE WHEN FTC_ESTATUS = '1' AND FTC_CLAVE_ENT_ORIG = '002'
    THEN CASE WHEN AIVS_VIV97 IS NULL THEN RPAD('0',15,'0')
          ELSE LPAD(
       REPLACE( 
          LPAD(SUBSTR(TO_CHAR(AIVS_VIV97), 1, INSTR(TO_CHAR(AIVS_VIV97, 'FM9999999999.99'), '.') - 1),9,'0') 
	|| RPAD(SUBSTR(TRIM(TO_CHAR(AIVS_VIV97, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(AIVS_VIV97, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
       ,'.','')
          ,15,'0') END
   ELSE 
   LPAD(
       REPLACE(
        LPAD(SUBSTR(TO_CHAR(AIVS_VIV97_ORIG), 1, INSTR(TO_CHAR(AIVS_VIV97_ORIG, 'FM9999999999.99'), '.') - 1),9,'0') 
     || RPAD(SUBSTR(TRIM(TO_CHAR(AIVS_VIV97_ORIG, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(AIVS_VIV97_ORIG, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
       ,'.','')
          ,15,'0') END AS AIVS_VIV97,
        
 CASE WHEN FTC_ESTATUS = '1'
    THEN CASE WHEN IMP_ACT_REN_RETIRO IS NULL THEN RPAD('0',9,'0')
          ELSE LPAD(
              REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_REN_RETIRO), 1, INSTR(TO_CHAR(IMP_ACT_REN_RETIRO, 'FM9999999999.99'), '.') - 1),7,'0') 
   || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_REN_RETIRO, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_REN_RETIRO, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
              ,'.','')
          ,9,'0') END
   ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_REN_RETIRO_ORIG), 1, INSTR(TO_CHAR(IMP_ACT_REN_RETIRO_ORIG, 'FM9999999999.99'), '.') - 1),7,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_REN_RETIRO_ORIG, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_REN_RETIRO_ORIG, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END AS IMP_ACT_REN_RETIRO,

CASE WHEN FTC_ESTATUS = '1'
    THEN CASE WHEN IMP_ACT_REN_CV_PATR IS NULL THEN RPAD('0',9,'0')
          ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_REN_CV_PATR), 1, INSTR(TO_CHAR(IMP_ACT_REN_CV_PATR, 'FM9999999999.99'), '.') - 1),7,'0') 
   || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_REN_CV_PATR, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_REN_CV_PATR, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END
   ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_REN_CV_PATR_ORIG), 1, INSTR(TO_CHAR(IMP_ACT_REN_CV_PATR_ORIG, 'FM9999999999.99'), '.') - 1),7,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_REN_CV_PATR_ORIG, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_REN_CV_PATR_ORIG, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END AS IMP_ACT_REN_CV_PATR,

CASE WHEN FTC_ESTATUS = '1'
    THEN CASE WHEN IMP_ACT_REN_CV_TRAR IS NULL THEN RPAD('0',9,'0')
          ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_REN_CV_TRAR), 1, INSTR(TO_CHAR(IMP_ACT_REN_CV_TRAR, 'FM9999999999.99'), '.') - 1),7,'0') 
   || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_REN_CV_TRAR, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_REN_CV_TRAR, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END
   ELSE LPAD(
       REPLACE(
          LPAD(SUBSTR(TO_CHAR(IMP_ACT_REN_CV_TRAR_ORIG), 1, INSTR(TO_CHAR(IMP_ACT_REN_CV_TRAR_ORIG, 'FM9999999999.99'), '.') - 1),7,'0') 
  || RPAD(SUBSTR(TRIM(TO_CHAR(IMP_ACT_REN_CV_TRAR_ORIG, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(IMP_ACT_REN_CV_TRAR_ORIG, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
       ,'.','')
          ,9,'0') END AS IMP_ACT_REN_CV_TRAR,
CASE WHEN FTD_FEH_ENV_ORG_SOL_PROC IS NULL THEN RPAD('0',8,'0') ELSE LPAD(FTD_FEH_ENV_ORG_SOL_PROC,8,'0') END AS FTD_FEH_ENV_ORG_SOL_PROC,
CASE WHEN vDiagnostico IS NULL OR FTC_DIAG_DEV = '  ' THEN '02' ELSE LPAD(vDiagnostico,2,'0') END AS FTC_DIAG_DEV,
CASE WHEN vMotRej IS NULL THEN RPAD('0',3,'0') ELSE LPAD(vMotRej,3,'0') END AS FTC_MOT_DEV,
RPAD('0',2,'0') AS FTC_RES_OPERACION,
RPAD('0',3,'0') AS FTC_DIAGNOSTICO1,
RPAD('0',3,'0') AS FTC_DIAGNOSTICO2,
RPAD('0',3,'0') AS FTC_DIAGNOSTICO3,
RPAD(' ',3,' ') AS FILLER
FROM TF_600_APLICA_REGLAS