SELECT 
	SDD.FTC_FOLIO_BITACORA
	,SDD.FTN_CTA_AFORE
	,CASE WHEN (
				CASE 
				    WHEN (FCC_VALOR_IND = 1 AND FTC_IDENT_PROC_DESMA = '02') OR
				         (FCC_VALOR_IND = 2 AND FTC_IDENT_PROC_DESMA = '01') OR
				         (FCC_VALOR_IND = 3 AND FTC_IDENT_PROC_DESMA = '04') 
				    THEN NULL
				    WHEN FCC_VALOR_IND = 4 OR
				         FCC_VALOR_IND IS NULL OR
				         (FTC_IDENT_PROC_DESMA NOT IN ('01', '02', '04'))
				    THEN 677
				    ELSE 677
				END
				) = NULL
		THEN SDD.FTD_ACTU_ESTA
		ELSE  
			CURRENT_DATE
		END
		AS FTD_ACTU_ESTA
	,CASE WHEN (
				CASE 
				    WHEN (FCC_VALOR_IND = 1 AND FTC_IDENT_PROC_DESMA = '02') OR
				         (FCC_VALOR_IND = 2 AND FTC_IDENT_PROC_DESMA = '01') OR
				         (FCC_VALOR_IND = 3 AND FTC_IDENT_PROC_DESMA = '04') 
				    THEN NULL
				    WHEN FCC_VALOR_IND = 4 OR
				         FCC_VALOR_IND IS NULL OR
				         (FTC_IDENT_PROC_DESMA NOT IN ('01', '02', '04'))
				    THEN 677
				    ELSE 677
				END
				) = NULL
		THEN SDD.FTD_FEH_ACT
		ELSE  
			(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City')
		END
		AS FTD_FEH_ACT
	,CASE WHEN (
				CASE 
				    WHEN (FCC_VALOR_IND = 1 AND FTC_IDENT_PROC_DESMA = '02') OR
				         (FCC_VALOR_IND = 2 AND FTC_IDENT_PROC_DESMA = '01') OR
				         (FCC_VALOR_IND = 3 AND FTC_IDENT_PROC_DESMA = '04') 
				    THEN NULL
				    WHEN FCC_VALOR_IND = 4 OR
				         FCC_VALOR_IND IS NULL OR
				         (FTC_IDENT_PROC_DESMA NOT IN ('01', '02', '04'))
				    THEN 677
				    ELSE 677
				END
				) = NULL
		THEN SDD.FCC_USU_ACT
		ELSE  
			'DATABRICKS'
		END
		AS FCC_USU_ACT
	,CASE 
	    WHEN (FCC_VALOR_IND = 1 AND FTC_IDENT_PROC_DESMA = '02') OR
	         (FCC_VALOR_IND = 2 AND FTC_IDENT_PROC_DESMA = '01') OR
	         (FCC_VALOR_IND = 3 AND FTC_IDENT_PROC_DESMA = '04') 
	    THEN NULL
	    WHEN FCC_VALOR_IND = 4 OR
	         FCC_VALOR_IND IS NULL OR
	         (FTC_IDENT_PROC_DESMA NOT IN ('01', '02', '04'))
	    THEN NULL --677
	    ELSE NULL --677
	END AS FTN_MOTI_RECH
	,CASE WHEN (
				CASE 
				    WHEN (FCC_VALOR_IND = 1 AND FTC_IDENT_PROC_DESMA = '02') OR
				         (FCC_VALOR_IND = 2 AND FTC_IDENT_PROC_DESMA = '01') OR
				         (FCC_VALOR_IND = 3 AND FTC_IDENT_PROC_DESMA = '04') 
				    THEN '1' --NULL
				    WHEN FCC_VALOR_IND = 4 OR
				         FCC_VALOR_IND IS NULL OR
				         (FTC_IDENT_PROC_DESMA NOT IN ('01', '02', '04'))
				    THEN '1' --677
				    ELSE '1' --677
				END
				) = NULL
		THEN SDD.FTC_ESTA_REGI 
		ELSE  
			(
				CASE 
				    WHEN (FCC_VALOR_IND = 1 AND FTC_IDENT_PROC_DESMA = '02') OR
					     (FCC_VALOR_IND = 2 AND FTC_IDENT_PROC_DESMA = '01') OR
					     (FCC_VALOR_IND = 3 AND FTC_IDENT_PROC_DESMA = '04') 
					    THEN '1' --antes NULL
					WHEN FCC_VALOR_IND = 4 OR
					     FCC_VALOR_IND IS NULL OR
					     (FTC_IDENT_PROC_DESMA NOT IN ('01', '02', '04'))
					THEN '1' --antes 0
					ELSE '1' --antes 0
				END 	
			) --SvEstatus
	 END AS FTC_ESTA_REGI
	,SDD.FTC_IDENT_PROC_DESMA
	,SDD.FTN_CONTA_SERV 
FROM PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO SDD
LEFT JOIN CIERREN.TTAFOGRAL_IND_CTA_INDV C 
ON SDD.FTN_CTA_AFORE = c.ftn_num_cta_invdual
AND C.FFN_ID_CONFIG_INDI IN ('#config_indi#') 
AND C.FTC_VIGENCIA = '#ind_vigencia#'
WHERE SDD.FTC_FOLIO_BITACORA = '#sr_folio#'
  AND SDD.FTC_ESTA_REGI = 0
  AND ( 
			(
				CASE 
						WHEN (FCC_VALOR_IND = 1 AND FTC_IDENT_PROC_DESMA = '02') OR
								(FCC_VALOR_IND = 2 AND FTC_IDENT_PROC_DESMA = '01') OR
								(FCC_VALOR_IND = 3 AND FTC_IDENT_PROC_DESMA = '04') 
						THEN NULL
						WHEN FCC_VALOR_IND = 4 OR
								FCC_VALOR_IND IS NULL OR
								(FTC_IDENT_PROC_DESMA NOT IN ('01', '02', '04'))
						THEN 677
						ELSE 677
				END
			)
			 NOT IN (93,254,375,1178,4437) OR 
			 (
				CASE 
						WHEN (FCC_VALOR_IND = 1 AND FTC_IDENT_PROC_DESMA = '02') OR
								(FCC_VALOR_IND = 2 AND FTC_IDENT_PROC_DESMA = '01') OR
								(FCC_VALOR_IND = 3 AND FTC_IDENT_PROC_DESMA = '04') 
						THEN NULL
						WHEN FCC_VALOR_IND = 4 OR
								FCC_VALOR_IND IS NULL OR
								(FTC_IDENT_PROC_DESMA NOT IN ('01', '02', '04'))
						THEN 677
						ELSE 677
				END
			 )
			 IS NULL)















