MERGE INTO PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO  TGT
USING (
    SELECT DISTINCT
        FTC_FOLIO_BITACORA,
        FTN_CTA_AFORE,
        FTD_ACTU_ESTA,
        FTD_FEH_ACT,
        FCC_USU_ACT,
        FTN_MOTI_RECH,
        FTC_ESTA_REGI,
        FTC_IDENT_PROC_DESMA,
        FTN_CONTA_SERV
    FROM CIERREN_DATAUX.TTCRXGRAL_MARCA_DESMARCA_INFO_AUX
    WHERE FTC_FOLIO_BITACORA = '#sr_folio#'
) SRC
ON (
    TGT.FTC_FOLIO_BITACORA = SRC.FTC_FOLIO_BITACORA
    AND TGT.FTN_CTA_AFORE = SRC.FTN_CTA_AFORE
    AND TGT.FTC_IDENT_PROC_DESMA = SRC.FTC_IDENT_PROC_DESMA
    AND TGT.FTN_CONTA_SERV = SRC.FTN_CONTA_SERV
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTD_ACTU_ESTA   = SRC.FTD_ACTU_ESTA,
        TGT.FTD_FEH_ACT     = SRC.FTD_FEH_ACT,
        TGT.FCC_USU_ACT     = SRC.FCC_USU_ACT,
        TGT.FTN_MOTI_RECH   = SRC.FTN_MOTI_RECH,
        TGT.FTC_ESTA_REGI   = SRC.FTC_ESTA_REGI
  