SELECT 
	CASE
		WHEN length(REGEXP_REPLACE('#SR_FOLIO#', '[0-9]*', '')) = 0 
		THEN '#SR_FOLIO#' END FTC_FOLIO, #SR_SUBETAPA# FTC_ID_SUBETAPA, TOT.TOTAL_REGISTROS FLN_TOTAL_REGISTROS, TOT.TOTAL_REGISTROS - ERR.TOTAL_REGISTROS FLN_REG_CUMPLIERON, ERR.TOTAL_REGISTROS FLN_REG_NO_CUMPLIERON, '91' FLC_VALIDACION, ERR.TOTAL_REGISTROS FLN_TOTAL_ERRORES, '#FILTRO_ETAPA#' FLC_DETALLE, '' FLD_FEC_REG, '#USR#' FLC_USU_REG, '' FTC_FOLIO_REL, CASE WHEN length(REGEXP_REPLACE('#SR_ID_ARCHIVO#', '[0-9]*', '')) = 0 THEN #SR_ID_ARCHIVO# END FTN_ID_ARCHIVO
FROM (SELECT COUNT(1) TOTAL_REGISTROS FROM #DELTA_TABLE_NAME_001# WHERE substr(FTC_LINEA,1,2) = '#FILTRO_ETAPA#') TOT
	JOIN (SELECT COUNT(1) TOTAL_REGISTROS FROM #DELTA_TABLE_NAME_CLEANED_001#) ERR

UNION ALL

SELECT CASE WHEN length(REGEXP_REPLACE('#SR_FOLIO#', '[0-9]*', '')) = 0 THEN '#SR_FOLIO#' END, #SR_SUBETAPA#, TOT.TOTAL_REGISTROS, TOT.TOTAL_REGISTROS - ERR.TOTAL_REGISTROS, ERR.TOTAL_REGISTROS, '91', ERR.TOTAL_REGISTROS, '00', '', '#USR#', '', CASE WHEN length(REGEXP_REPLACE('#SR_ID_ARCHIVO#', '[0-9]*', '')) = 0 THEN #SR_ID_ARCHIVO# END
FROM (SELECT COUNT(1) TOTAL_REGISTROS FROM #DELTA_TABLE_NAME_001# WHERE substr(FTC_LINEA,1,2) = '#FILTRO_ETAPA#') TOT
	JOIN (SELECT COUNT(1) TOTAL_REGISTROS FROM #DELTA_TABLE_NAME_CLEANED_001#) ERR