SELECT 
	CASE WHEN FTC_FOLIO = '1' THEN '' ELSE FTC_FOLIO END FTC_FOLIO
	, FTC_ID_SUBETAPA
	, SUM(FLN_TOTAL_REGISTROS) FLN_TOTAL_REGISTROS
	, SUM(FLN_REG_CUMPLIERON) FLN_REG_CUMPLIERON
	, SUM(FLN_REG_NO_CUMPLIERON) FLN_REG_NO_CUMPLIERON
	, FLC_VALIDACION
	, SUM(FLN_TOTAL_ERRORES) FLN_TOTAL_ERRORES
	, FLC_DETALLE
	, to_timestamp(from_utc_timestamp(current_timestamp, 'GMT-6')) FLD_FEC_REG
	, FLC_USU_REG
	, FTC_FOLIO_REL
	, CASE WHEN FTN_ID_ARCHIVO = '1' THEN '' ELSE FTN_ID_ARCHIVO END FTN_ID_ARCHIVO
FROM #DELTA_TABLE_NAME_CIFRAS_CONTROL_001#
GROUP BY CASE WHEN FTC_FOLIO = '1' THEN '' ELSE FTC_FOLIO END, FTC_ID_SUBETAPA, FLC_VALIDACION, FLC_DETALLE, to_timestamp(from_utc_timestamp(current_timestamp, 'GMT-6')), FLC_USU_REG, FTC_FOLIO_REL, CASE WHEN FTN_ID_ARCHIVO = '1' THEN '' ELSE FTN_ID_ARCHIVO END