SELECT  
to_number(Trim(SUBSTR(FTC_LINEA,3,10))) FTN_CONTA_SERV,
Trim(SUBSTR(FTC_LINEA,23,2)) FTC_ORIGEN_TRANSFE,
Trim(SUBSTR(FTC_LINEA,25,8)) FTD_FEH_PRESEN,
Trim(SUBSTR(FTC_LINEA,41,18)) FTC_CURP_TRABA,
Trim(SUBSTR(FTC_LINEA,59,11)) FTN_NSS_TRABA_INFO,
Trim(SUBSTR(FTC_LINEA,85,13)) FTC_RFC_TRABA_INFO,
Trim(SUBSTR(FTC_LINEA,98,40)) FTC_APELLIDO_PATE_INFO,
Trim(SUBSTR(FTC_LINEA,138,40)) FTC_APELLIDO_MATE_INFO,
Trim(SUBSTR(FTC_LINEA,178,40)) FTC_NOMBRES_INFO,
Trim(SUBSTR(FTC_LINEA,240,16)) FTC_IDENT_LOTE_SOLI,
Trim(SUBSTR(FTC_LINEA,271,11)) FTN_NSS_TRABA_AFORE,
Trim(SUBSTR(FTC_LINEA,282,13)) FTC_RFC_TRABA_AFORE,
Trim(SUBSTR(FTC_LINEA,325,40)) FTC_APELLIDO_PATE_AFORE,
Trim(SUBSTR(FTC_LINEA,365,40)) FTC_APELLIDO_MATE_AFORE,
Trim(SUBSTR(FTC_LINEA,405,40)) FTC_NOMBRE_AFORE,
(Trim(SUBSTR(FTC_LINEA,490,15))/ 1000000) FTN_NUM_APLI_INTE_VIVI92_SOL, 
(Trim(SUBSTR(FTC_LINEA,565,15))/ 1000000) FTN_NUM_APLI_INTE_VIVI97_SOL,
Trim(SUBSTR(FTC_LINEA,588,50)) FTC_NOMBRE_TRABA_IMSS,
(Trim(SUBSTR(FTC_LINEA,638,10))) FTN_NUMERO_CRED_INFONA,
Trim(SUBSTR(FTC_LINEA,648,2)) FTC_CODIGO_RES_OPER,
Trim(SUBSTR(FTC_LINEA,650,15)) FTC_DIAG_PROCESO,
TO_CHAR(ADD_MONTHS(TRUNC(TO_DATE(Trim(SUBSTR(FTC_LINEA,25,8)),'yyyymmdd'),'MONTH'),1),'YYYYMMDD')  FTD_FEH_VAL_VIV
FROM CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO
WHERE SUBSTR(FTC_LINEA, 1, 2) = 02
	AND FTN_ID_ARCHIVO = #sr_id_archivo#