SELECT
  q1.FTN_NUM_CTA_INVDUAL,
  q2.FCN_ID_IND_6,
  q2.INDI_6,
  q2.FTC_VIG_6,
  q3.FCN_ID_IND_13,
  q3.INDI_13,
  q3.FTC_VIG_13,
  q4.FCN_ID_IND_16,
  q4.INDI_16,
  q4.FTC_VIG_16
FROM
  (
    SELECT DISTINCT
      FTN_NUM_CTA_INVDUAL
    FROM
      CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS
    WHERE
      FTC_FOLIO = '#SR_FOLIO#'
  ) q1
    LEFT JOIN (
      SELECT
        FTN_NUM_CTA_INVDUAL,
        DECODE(FFN_ID_CONFIG_INDI, 6, FCN_ID_IND_CTA_INDV, 0) FCN_ID_IND_6,
        DECODE(FFN_ID_CONFIG_INDI, 6, FFN_ID_CONFIG_INDI, 0) INDI_6,
        DECODE(FFN_ID_CONFIG_INDI, 6, FTC_VIGENCIA, 0) FTC_VIG_6
      FROM
        CIERREN.TTAFOGRAL_IND_CTA_INDV
      WHERE
        FFN_ID_CONFIG_INDI = 6
    ) q2
      ON q1.FTN_NUM_CTA_INVDUAL = q2.FTN_NUM_CTA_INVDUAL
    LEFT JOIN (
      SELECT
        FTN_NUM_CTA_INVDUAL,
        DECODE(FFN_ID_CONFIG_INDI, 13, FCN_ID_IND_CTA_INDV, 0) FCN_ID_IND_13,
        DECODE(FFN_ID_CONFIG_INDI, 13, FFN_ID_CONFIG_INDI, 0) INDI_13,
        DECODE(FFN_ID_CONFIG_INDI, 13, SUBSTR(FCC_VALOR_IND, 1, 1), 0) FTC_VIG_13
      FROM
        CIERREN.TTAFOGRAL_IND_CTA_INDV
      WHERE
        FFN_ID_CONFIG_INDI = 13
    ) q3
      ON q1.FTN_NUM_CTA_INVDUAL = q3.FTN_NUM_CTA_INVDUAL
    LEFT JOIN (
      SELECT
        FTN_NUM_CTA_INVDUAL,
        DECODE(FFN_ID_CONFIG_INDI, 16, FCN_ID_IND_CTA_INDV, 0) FCN_ID_IND_16,
        DECODE(FFN_ID_CONFIG_INDI, 16, FFN_ID_CONFIG_INDI, 0) INDI_16,
        DECODE(FFN_ID_CONFIG_INDI, 16, FTC_VIGENCIA, 0) FTC_VIG_16
      FROM
        CIERREN.TTAFOGRAL_IND_CTA_INDV
      WHERE
        FFN_ID_CONFIG_INDI = 16
    ) q4
      ON q1.FTN_NUM_CTA_INVDUAL = q4.FTN_NUM_CTA_INVDUAL