MERGE INTO CIERREN.TTAFOGRAL_IND_CTA_INDV ori USING (
  SELECT
    FTC_FOLIO,
    FTN_NUM_CTA_INVDUAL,
    FCN_ID_IND_CTA_INDV,
    FCC_VALOR_IND,
    FTC_VIGENCIA,
    FTD_FEH_ACT,
    FCC_USU_ACT
  FROM
    CIERREN_DATAUX.TTAFOGRAL_ETL_IND_CTA_INDV_AUX
  WHERE
    FTC_FOLIO = #SR_FOLIO#
) aux ON (
  ori.FCN_ID_IND_CTA_INDV = aux.FCN_ID_IND_CTA_INDV
)
WHEN MATCHED THEN
UPDATE
SET
  ori.FCC_VALOR_IND = aux.FCC_VALOR_IND,
  ori.FTC_VIGENCIA = aux.FTC_VIGENCIA,
  ori.FTD_FEH_ACT = aux.FTD_FEH_ACT,
  ori.FCC_USU_ACT = aux.FCC_USU_ACT