SELECT
    C1.FTN_NUM_CTA_INVDUAL,
    C1.FCN_ID_TIPO_SUBCTA,
    C1.FTD_FEH_LIQUIDACION,
    C2.FCN_ID_IND_6,
    C2.INDI_6,
    C2.FTC_VIG_6,
    C2.FCN_ID_IND_13,
    C2.INDI_13,
    C2.FTC_VIG_13,
    C2.FCN_ID_IND_16,
    C2.INDI_16,
    C2.FTC_VIG_16
FROM (
        SELECT DISTINCT
            FTC_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL,
            FCN_ID_TIPO_SUBCTA,
            FTD_FEH_LIQUIDACION
        FROM #CATALOG_NAME#.#SCHEMA_NAME#.ORACLE_DISPERSIONES_#SR_FOLIO#
        WHERE FCN_ID_TIPO_MOV = 181 

) C1
LEFT JOIN #CATALOG_NAME#.#SCHEMA_NAME#.DELTA_DISPER_ACT_IND_01_#SR_FOLIO# C2
ON C1.FTN_NUM_CTA_INVDUAL = C2.FTN_NUM_CTA_INVDUAL