SELECT DISTINCT 
    CTA.FTN_NUM_CTA_INVDUAL,
    NVL(IND_6.FCN_ID_IND_CTA_INDV, 0) AS FCN_ID_IND_6,
    NVL(IND_6.INDI_6, 0) AS INDI_6,
    NVL(IND_6.FTC_VIG_6, 0) AS FTC_VIG_6,
    NVL(IND_13.FCN_ID_IND_CTA_INDV, 0) AS FCN_ID_IND_13,
    NVL(IND_13.INDI_13, 0) AS INDI_13,
    NVL(IND_13.FTC_VIG_13, 0) AS FTC_VIG_13,
    NVL(IND_16.FCN_ID_IND_CTA_INDV, 0) AS FCN_ID_IND_16,
    NVL(IND_16.INDI_16, 0) AS INDI_16,
    NVL(IND_16.FTC_VIG_16, 0) AS FTC_VIG_16
FROM 
    (SELECT DISTINCT FTN_NUM_CTA_INVDUAL 
     FROM CIERREN.TTAFOGRAL_IND_CTA_INDV) CTA
INNER JOIN 
    CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS MOV
ON 
    CTA.FTN_NUM_CTA_INVDUAL = MOV.FTN_NUM_CTA_INVDUAL
AND 
    MOV.FTC_FOLIO = '#SR_FOLIO#'
LEFT JOIN 
    (SELECT 
        FTN_NUM_CTA_INVDUAL,
        FCN_ID_IND_CTA_INDV,
        FFN_ID_CONFIG_INDI AS INDI_6,
        FTC_VIGENCIA AS FTC_VIG_6
     FROM CIERREN.TTAFOGRAL_IND_CTA_INDV
     WHERE FFN_ID_CONFIG_INDI = 6) IND_6
ON 
    CTA.FTN_NUM_CTA_INVDUAL = IND_6.FTN_NUM_CTA_INVDUAL
LEFT JOIN 
    (SELECT 
        FTN_NUM_CTA_INVDUAL,
        FCN_ID_IND_CTA_INDV,
        FFN_ID_CONFIG_INDI AS INDI_13,
        SUBSTR(FCC_VALOR_IND, 1, 1) AS FTC_VIG_13
     FROM CIERREN.TTAFOGRAL_IND_CTA_INDV
     WHERE FFN_ID_CONFIG_INDI = 13) IND_13
ON 
    CTA.FTN_NUM_CTA_INVDUAL = IND_13.FTN_NUM_CTA_INVDUAL
LEFT JOIN 
    (SELECT 
        FTN_NUM_CTA_INVDUAL,
        FCN_ID_IND_CTA_INDV,
        FFN_ID_CONFIG_INDI AS INDI_16,
        FTC_VIGENCIA AS FTC_VIG_16
     FROM CIERREN.TTAFOGRAL_IND_CTA_INDV
     WHERE FFN_ID_CONFIG_INDI = 16) IND_16
ON 
    CTA.FTN_NUM_CTA_INVDUAL = IND_16.FTN_NUM_CTA_INVDUAL