SELECT DISTINCT
    NVL(IND.FCN_ID_IND_CTA_INDV, 0) AS FCN_ID_IND_CTA_INDV,
    NVL(IND.FTN_NUM_CTA_INVDUAL, 0) AS FTN_NUM_CTA_INVDUAL,
    IND.FFN_ID_CONFIG_INDI,
    NVL(IND.FCC_VALOR_IND, '0') AS FCC_VALOR_IND,
    NVL(IND.FTC_VIGENCIA, 0) AS FTC_VIGENCIA
FROM (
    -- Indicador 6
    SELECT
        NVL(T.FCN_ID_IND_CTA_INDV, 0) AS FCN_ID_IND_CTA_INDV,
        NVL(T.FTN_NUM_CTA_INVDUAL, 0) AS FTN_NUM_CTA_INVDUAL,
        6 AS FFN_ID_CONFIG_INDI,
        CAST('0' AS VARCHAR2(10)) AS FCC_VALOR_IND,
        NVL(T.FTC_VIGENCIA, 0) AS FTC_VIGENCIA
    FROM CIERREN.TTAFOGRAL_IND_CTA_INDV T
    WHERE T.FFN_ID_CONFIG_INDI = 6

    UNION ALL

    -- Indicador 13
    SELECT
        NVL(T.FCN_ID_IND_CTA_INDV, 0) AS FCN_ID_IND_CTA_INDV,
        NVL(T.FTN_NUM_CTA_INVDUAL, 0) AS FTN_NUM_CTA_INVDUAL,
        13 AS FFN_ID_CONFIG_INDI,
        NVL(SUBSTR(T.FCC_VALOR_IND, 1, 1), '0') AS FCC_VALOR_IND,
        NVL(T.FTC_VIGENCIA, 0) AS FTC_VIGENCIA
    FROM CIERREN.TTAFOGRAL_IND_CTA_INDV T
    WHERE T.FFN_ID_CONFIG_INDI = 13

    UNION ALL

    -- Indicador 16
    SELECT
        NVL(T.FCN_ID_IND_CTA_INDV, 0) AS FCN_ID_IND_CTA_INDV,
        NVL(T.FTN_NUM_CTA_INVDUAL, 0) AS FTN_NUM_CTA_INVDUAL,
        16 AS FFN_ID_CONFIG_INDI,
        CAST('0' AS VARCHAR2(10)) AS FCC_VALOR_IND,
        NVL(T.FTC_VIGENCIA, 0) AS FTC_VIGENCIA
    FROM CIERREN.TTAFOGRAL_IND_CTA_INDV T
    WHERE T.FFN_ID_CONFIG_INDI = 16
) IND
INNER JOIN (
    SELECT DISTINCT CTA.FTN_NUM_CTA_INVDUAL
    FROM CIERREN.TTAFOGRAL_IND_CTA_INDV CTA
    INNER JOIN CIERREN_ETL.TTSISGRAL_ETL_MOVIMIENTOS MOV
        ON CTA.FTN_NUM_CTA_INVDUAL = MOV.FTN_NUM_CTA_INVDUAL
       AND MOV.FTC_FOLIO = '#SR_FOLIO#'
) CTA_MOV
ON IND.FTN_NUM_CTA_INVDUAL = CTA_MOV.FTN_NUM_CTA_INVDUAL

