SELECT
  A.FTC_FOLIO_BITACORA AS FTC_FOLIO
 ,97 AS FTN_ID_PROCESO
 ,A.FTN_ID_SUBP AS FTN_ID_SUBPROCESO
 ,A.FTN_NUM_CTA_INVDUAL
 ,COALESCE(V.FCN_ID_SIEFORE,81) as FTN_ID_SIEFORE
,COALESCE(A.FCN_ID_TIPO_SUBCTA,15) AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,NVL(BAL_MOVS.FTN_DISP_ACCIONES,0) as FTN_MONTO_ACCIONES
,COALESCE(BAL_MOVS.FTN_DISP_ACCIONES,0) * COALESCE(V.FCN_VALOR_ACCION,0) AS  FTN_MONTO_PESOS
,NVL(V.FCN_ID_VALOR_ACCION,0) AS FTN_ID_VALOR_ACCION 
,199 AS FTN_ID_TIPO_MONTO
,CS.FCN_ID_SALDO_OPERA AS FTN_ID_SALDO_OPERA
,#sr_tipo_mov# AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT

FROM (
select DISTINCT
FTC_FOLIO_BITACORA
,TRUNC(FTD_FEH_PRESEN, 'MM') AS FECHA_VALOR_ACCION
,FTN_CTA_AFORE AS FTN_NUM_CTA_INVDUAL
,FTN_ID_SUBP
,FTN_MOTI_RECH
,15 as FCN_ID_TIPO_SUBCTA
   FROM PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
where
FTC_FOLIO_BITACORA=#sr_folio#
AND FTN_ID_SUBP=#sr_subproceso#
AND FTC_ESTA_REGI = 1
)A
LEFT JOIN CIERREN.TFAFOGRAL_CONFIG_SUBPROCESO CS 
	ON A.FTN_ID_SUBP = CS.FCN_ID_SUBPROCESO AND CS.FFB_VIGENCIA = '1'
LEFT OUTER JOIN CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA C
        ON A.FTC_FOLIO_BITACORA=C.FTC_FOLIO
       AND A.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
left outer join (

  SELECT FTC_NUM_CTA_INVDUAL,FCN_ID_SIEFORE,FCN_ID_TIPO_SUBCTA, SUM(FTN_DISP_ACCIONES) AS FTN_DISP_ACCIONES
     FROM CIERREN.TTAFOGRAL_BALANCE_MOVS
     WHERE FCN_ID_SIEFORE = 81
     AND FCN_ID_TIPO_SUBCTA = 15
     GROUP BY FTC_NUM_CTA_INVDUAL,FCN_ID_SIEFORE,FCN_ID_TIPO_SUBCTA
) BAL_MOVS
ON A.FTN_NUM_CTA_INVDUAL = BAL_MOVS.FTC_NUM_CTA_INVDUAL
LEFT JOIN (
select 
FCD_FEH_ACCION 
,FCN_VALOR_ACCION 
,FCN_ID_VALOR_ACCION  
,FCN_ID_SIEFORE
from CIERREN.TCAFOGRAL_VALOR_ACCION
WHERE FCN_ID_SIEFORE = 81
and FCN_ID_REGIMEN = 138
AND TO_TIMESTAMP(TRUNC(FCD_FEH_ACCION),'DD-MM-YY HH24:MI:SS') = TO_TIMESTAMP(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'DD-MM-YY HH24:MI:SS')
)V ON V.FCN_ID_SIEFORE=BAL_MOVS.FCN_ID_SIEFORE
WHERE 
   (C.FTB_ESTATUS_MARCA =0 
        Or C.FTB_ESTATUS_MARCA is null)
