WITH DS_200_DATOS AS (
  SELECT DISTINCT
    T.FTC_FOLIO_BITACORA as FTC_FOLIO,
    lpad(T.FTN_NUM_CTA_AFORE,10,'0')FTN_CTA_AFORE,
    --FCN_ID_SIEFORE,
    lpad(nvl(T.FTC_NSS_TRABA_AFORE,'0'),11,'0') AS FTC_NSS_AFORE,
    SUBSTR(T.FTC_RFC_TRABA_AFORE,12,1) AS FTC_DIG_VERI,
    to_char(T.FTD_FEH_CRE, 'YYYYMMDD')FTD_FEH_CRE,
    lpad(nvl(ET.FTN_ID_ARCHIVO,'0'),7,'0')FTN_ID_ARCHIVO,
    T.FTN_ID_SUBP FCN_ID_SUBPROCESO,
    T.FTN_PERIODO_PAGO,
    lpad(nvl(T.FTN_CONTA_SERV,'0'),8,'0') FNN_ID_REFERENCIA,
    null FTC_INSTITUTO_ORIGEN
  FROM PROCESOS.TTCRXGRAL_TRANS_INFONA T
  LEFT JOIN CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_INFONAVIT ET
ON ET.FTC_FOLIO_BITACORA=T.FTC_FOLIO_BITACORA AND ET.FTC_TIPO_ARCH='01'
  WHERE T.FTC_FOLIO_BITACORA = #sr_folio#
    AND T.FTN_ID_SUBP = #sr_subproceso#
    AND T.FTC_ESTATUS_REGISTRO = 1
),
BD_100_TL_MOV_VIV AS (
  SELECT
    MV.FTC_FOLIO,
    LPAD(MV.FTN_NUM_CTA_INVDUAL, 10, '0') AS FTN_CTA_AFORE,
    MV.FTD_ID_ESTATUS_MOV,
    TO_CHAR(MV.FTD_FEH_LIQUIDACION, 'YYYYMMDD') AS FTD_FEH_LIQUIDACION,
    LPAD(NVL(MV.FNN_ID_REFERENCIA, '0'), 8, '0') AS FNN_ID_REFERENCIA,
    MV.FCN_ID_VALOR_ACCION,
    LPAD(MV.FCN_ID_TIPO_SUBCTA, 4, '0') AS FCN_ID_TIPO_SUBCTA,
    MV.FCN_ID_TIPO_MOV,
    MV.FCN_ID_CONCEPTO_MOV,
    '00000000' AS FND_FECHA_1,
    '00000000' AS FND_FECHA_2,
    '00000000' AS FND_FECVGUB,
    '00000000' AS FND_FECHA_VALOR_RCV,
    '00000000' AS FND_FECHA_VALOR_IMSS_ACV_VIV,
    '00000' AS FNC_VARMAX,
    SIE.FCN_ID_SIEFORE,
    CMI.FFN_COD_MOV_ITG,
    CASE WHEN CMI.FFN_POSICION_ITGY = 1 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES1,
    CASE WHEN CMI.FFN_POSICION_ITGY = 1 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO1,
    CASE WHEN CMI.FFN_POSICION_ITGY = 2 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES2,
    CASE WHEN CMI.FFN_POSICION_ITGY = 2 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO2,
    CASE WHEN CMI.FFN_POSICION_ITGY = 3 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES3,
    CASE WHEN CMI.FFN_POSICION_ITGY = 3 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO3,
    CASE WHEN CMI.FFN_POSICION_ITGY = 4 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES4,
    CASE WHEN CMI.FFN_POSICION_ITGY = 4 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO4,
    CASE WHEN CMI.FFN_POSICION_ITGY = 5 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES5,
    CASE WHEN CMI.FFN_POSICION_ITGY = 5 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO5,
    CASE WHEN CMI.FFN_POSICION_ITGY = 6 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES6,
    CASE WHEN CMI.FFN_POSICION_ITGY = 6 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO6,
    CASE WHEN CMI.FFN_POSICION_ITGY = 7 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES7,
    CASE WHEN CMI.FFN_POSICION_ITGY = 7 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO7,
    CASE WHEN CMI.FFN_POSICION_ITGY = 8 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES8,
    CASE WHEN CMI.FFN_POSICION_ITGY = 8 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO8,
    CASE WHEN CMI.FFN_POSICION_ITGY = 9 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES9,
    CASE WHEN CMI.FFN_POSICION_ITGY = 9 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO9,
    TO_CHAR(MV.FTD_FEH_LIQUIDACION, 'YYYYMMDD') AS FND_FECHA_PAGO_SUA,
    TO_CHAR(MV.FTD_FEH_LIQUIDACION, 'YYYYMM') AS FNC_PERIODO_PAGO_PATRON,
    '00000000' AS FND_FECTRA_SUA
  FROM CIERREN.TTAFOGRAL_MOV_VIV MV
  INNER JOIN (
    SELECT
      LPAD(MPI.TMN_CVE_ITGY, 2, '0') AS FCN_ID_SIEFORE,
      MPI.TMN_CVE_NCI
    FROM CIERREN.TMSISGRAL_MAP_NCI_ITGY MPI
    WHERE MPI.TMC_VIGENCIA = 1 AND MPI.TMC_USO = 'CTINDI'
  ) SIE ON MV.FCN_ID_SIEFORE = SIE.TMN_CVE_NCI
  INNER JOIN (
    SELECT
      TSUB.FCN_ID_TIPO_SUBCTA,
      LPAD(NVL(SUBSTR(MIT.FFN_COD_MOV_ITGY, 0, 3), 0), 3, '0') AS FFN_COD_MOV_ITG,
      MIT.FFN_POSICION_ITGY,
      FFN_ID_CONCEPTO_MOV
    FROM CIERREN.TCCRXGRAL_TIPO_SUBCTA TSUB
    INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB
      ON TSUB.FCN_ID_TIPO_SUBCTA = MSUB.FCN_ID_TIPO_SUBCTA
      AND MSUB.FCN_ID_SUBPROCESO = #sr_subproceso#
    INNER JOIN CIERREN.TFCRXGRAL_CONFIG_MOV_ITGY MIT
      ON MSUB.FRN_ID_MOV_SUBCTA = MIT.FRN_ID_MOV_SUBCTA
  ) CMI ON MV.FCN_ID_TIPO_SUBCTA = CMI.FCN_ID_TIPO_SUBCTA
       AND MV.FCN_ID_CONCEPTO_MOV = CMI.FFN_ID_CONCEPTO_MOV
  WHERE MV.FTC_FOLIO = #sr_folio#
),
BD_700_VALOR_ACCION AS (
  SELECT
    LPAD(TRUNC(FCN_VALOR_ACCION, 7) * 10000000, 12, '0') AS FCN_VALOR_ACCION,
    FCN_ID_VALOR_ACCION,
    TO_CHAR(FCD_FEH_ACCION, 'YYYYMMDD') AS FCD_FEH_ACCION,
    TO_CHAR(FCD_FEH_ACCION, 'YYYYMMDD') AS FND_FECHA_PAGO_SUA,
    TO_CHAR(FCD_FEH_ACCION, 'YYYYMM') AS FNC_PERIODO_PAGO_PATRON
  FROM CIERREN.TCAFOGRAL_VALOR_ACCION
  WHERE FCN_ID_REGIMEN IN (138, 139)
),
JO_300_DATOS_TABLA AS (
  SELECT
    JO.FTC_FOLIO,
    JO.FTN_CTA_AFORE,
    JO.FTD_ID_ESTATUS_MOV,
    JO.FTD_FEH_LIQUIDACION,
    JO.FNN_ID_REFERENCIA,
    JO.FCN_ID_VALOR_ACCION,
    --LPAD(JO.FCN_ID_TIPO_SUBCTA, 4, '0') AS FCN_ID_TIPO_SUBCTA,
    JO.FCN_ID_TIPO_MOV,
    JO.FCN_ID_SIEFORE,
    JO.FCN_ID_CONCEPTO_MOV,
    JO.FND_FECHA_1,
    JO.FND_FECHA_2,
    JO.FND_FECVGUB,
    JO.FND_FECHA_VALOR_RCV,
    JO.FND_FECHA_VALOR_IMSS_ACV_VIV,
    JO.FNC_VARMAX,
    JO.FFN_COD_MOV_ITG,
    JO.FTF_MONPES1,
    JO.FTF_MONCUO1,
    JO.FTF_MONPES2,
    JO.FTF_MONCUO2,
    JO.FTF_MONPES3,
    JO.FTF_MONCUO3,
    JO.FTF_MONPES4,
    JO.FTF_MONCUO4,
    JO.FTF_MONPES5,
    JO.FTF_MONCUO5,
    JO.FTF_MONPES6,
    JO.FTF_MONCUO6,
    JO.FTF_MONPES7,
    JO.FTF_MONCUO7,
    JO.FTF_MONPES8,
    JO.FTF_MONCUO8,
    JO.FTF_MONPES9,
    JO.FTF_MONCUO9,
    JO.FND_FECHA_PAGO_SUA,
    JO.FNC_PERIODO_PAGO_PATRON,
    DS.FTC_NSS_AFORE,
    DS.FTC_DIG_VERI,
    DS.FTD_FEH_CRE,
    DS.FTN_ID_ARCHIVO,
    DS.FCN_ID_SUBPROCESO,
    DS.FTC_INSTITUTO_ORIGEN,
    JO.FND_FECTRA_SUA
  FROM BD_100_TL_MOV_VIV JO
  INNER JOIN DS_200_DATOS DS
    ON JO.FTC_FOLIO = DS.FTC_FOLIO
   AND JO.FTN_CTA_AFORE = DS.FTN_CTA_AFORE
   AND JO.FNN_ID_REFERENCIA = DS.FNN_ID_REFERENCIA
)
SELECT
  LO.FCN_ID_SIEFORE AS FCN_CVE_SIEFORE,
  LO.FTN_CTA_AFORE AS FTN_NUM_CTA_INVDUAL,
  LO.FTC_DIG_VERI,
  LO.FFN_COD_MOV_ITG AS FFN_COD_MOV_ITGY,
  LO.FTC_NSS_AFORE AS FNN_NSS_ISSSTE_SUA,
  LO.FTD_FEH_CRE AS FND_FEH_CRE_SUA,
  LO.FTN_ID_ARCHIVO,
  LO.FTD_FEH_LIQUIDACION,
  VA.FCN_VALOR_ACCION,
  LO.FND_FECTRA_SUA,
  CASE 
    WHEN #sr_subproceso# = 364 THEN '889'
    WHEN #sr_subproceso# = 365 THEN '857'
    WHEN #sr_subproceso# = 368 THEN '667'
    ELSE '000'
  END AS FNN_SECLOT_SUA,
  LO.FNN_ID_REFERENCIA,
  LO.FTC_FOLIO,
  VA.FND_FECHA_PAGO_SUA,
  VA.FNC_PERIODO_PAGO_PATRON,
  LO.FND_FECHA_VALOR_IMSS_ACV_VIV AS FNC_REG_PATRN_IMSS_SUA,
  LO.FTF_MONPES1,
  LO.FTF_MONCUO1,
  LO.FTF_MONPES2,
  LO.FTF_MONCUO2,
  LO.FTF_MONPES3,
  LO.FTF_MONCUO3,
  LO.FTF_MONPES4,
  LO.FTF_MONCUO4,
  LO.FTF_MONPES5,
  LO.FTF_MONCUO5,
  LO.FTF_MONPES6,
  LO.FTF_MONCUO6,
  LO.FTF_MONPES7,
  LO.FTF_MONCUO7,
  LO.FTF_MONPES8,
  LO.FTF_MONCUO8,
  LO.FTF_MONPES9,
  LO.FTF_MONCUO9,
  LO.FND_FECHA_1,
  LO.FND_FECHA_2,
  LO.FND_FECHA_VALOR_RCV,
  LO.FND_FECHA_VALOR_IMSS_ACV_VIV,
  LO.FND_FECVGUB,
  CASE
    WHEN #sr_subproceso# IN (347, 348, 349, 351, 354, 364, 365, 368, 3832)
      OR (#sr_subproceso# = 3286 AND LO.FTC_INSTITUTO_ORIGEN = '001')
    THEN '01'
    ELSE '02'
  END AS FNC_CVESERV,
  LO.FNC_VARMAX
FROM JO_300_DATOS_TABLA LO
INNER JOIN BD_700_VALOR_ACCION VA
  ON LO.FCN_ID_VALOR_ACCION = VA.FCN_ID_VALOR_ACCION

