SELECT
      FTC_FOLIO,
      #SR_PROCESO# AS FCN_ID_PROCESO,
      FCN_ID_SUBPROCESO,
      SUM(ACEPTADOS)+SUM(RECHAZADOS) AS FLN_TOTAL_REGISTROS,
      SUM(ACEPTADOS) AS FLN_REG_ACEPTADOS,
      SUM(RECHAZADOS) AS FLN_REG_RECHAZADOS,
      CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FLD_FEC_REG,
      #SR_USUARIO# AS FLC_USU_REG,
FROM (
        SELECT DISTINCT FTC_FOLIO,FCN_ID_SUBPROCESO,
               
               CASE WHEN FTC_ESTATUS=1 THEN NUMERO ELSE 0 END ACEPTADOS,
               CASE WHEN FTC_ESTATUS=0 THEN NUMERO ELSE 0 END RECHAZADOS,
             
               CASE WHEN FTC_ESTATUS=1 THEN SALDO_97 ELSE 0 END SALDO_97_ACEPTADO,
               CASE WHEN FTC_ESTATUS=0 THEN SALDO_97 ELSE 0 END SALDO_97_RECHAZADO,
               
               CASE WHEN FTC_ESTATUS=1 THEN INTERES_SALDO_97 ELSE 0 END INTERES_SALDO_97_ACEPTADO,
               CASE WHEN FTC_ESTATUS=0 THEN INTERES_SALDO_97 ELSE 0 END INTERES_SALDO_97_RECHAZADO,
               
               CASE WHEN FTC_ESTATUS=1 THEN AIVS_97 ELSE 0 END AIVS_97_ACEPTADO,
               CASE WHEN FTC_ESTATUS=0 THEN AIVS_97 ELSE 0 END AIVS_97_RECHAZADO
          FROM (
               SELECT DEVO.FTC_FOLIO,DEVO.FCN_ID_SUBPROCESO,
                       sum(FTN_SALDO_97) AS SALDO_97,
                       sum(FTN_INTERES_SALDO_97) AS INTERES_SALDO_97,
                       sum(FTN_AIVS_VIV_97) AS AIVS_97,
                       FTC_ESTATUS,
                       COUNT(FTC_ESTATUS)    NUMERO
                  FROM PROCESOS.TTAFOTRAS_DEVO_SALDO_EXC_INFO DEVO
                 WHERE FTC_FOLIO = '#SR_FOLIO#'
                   AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
                   group by DEVO.FTC_FOLIO, DEVO.FCN_ID_SUBPROCESO, FTC_ESTATUS)
        )
GROUP BY FTC_FOLIO, FCN_ID_SUBPROCESO, 15
