SELECT  -- MD.*   --  este es el universo de cuentas a procesar 
  	MD.FTC_FOLIO_BITACORA AS FTC_FOLIO,  
  	97 AS FTN_ID_PROCESO,    
  	SS.FTN_ID_SUBP  AS FTN_ID_SUBPROCESO,  
  	MD.FTN_CTA_AFORE AS FTN_NUM_CTA_INVDUAL,  
  	V.FCN_ID_SIEFORE  AS FTN_ID_SIEFORE,
  	SS.FCN_ID_TIPO_SUBCTA_97 AS FTN_ID_TIPO_SUBCTA, 
  	'' AS FTC_FOLIO_REL,
  	SS.FTN_SDO_AIVS AS FTN_MONTO_ACCIONES,
  	SS.FTN_MONTO_PESOS AS FTN_MONTO_PESOS,
  	SS.FCN_ID_VALOR_ACCION AS FTN_ID_VALOR_ACCION,
  	199 AS FTN_ID_TIPO_MONTO,
  	-- 11 AS FTN_ID_SALDO_OPERA,
  	CS.FCN_ID_SALDO_OPERA AS FTN_ID_SALDO_OPERA,
  	180 AS FTN_ID_TIPO_MOV,
    -- MS.FCN_ID_TIPO_MOV AS FTN_ID_TIPO_MOV,
  SYSDATE AS FTD_FEH_CRE,
  'TEST_DB' AS FTC_USU_CRE
FROM PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO MD
INNER JOIN PROCESOS.TTSISGRAL_SUF_SALDOS SS 
	ON SS.FTN_NUM_CTA_INVDUAL = MD.FTN_CTA_AFORE 
	AND SS.FTC_FOLIO_BITACORA = MD.FTC_FOLIO_BITACORA
INNER JOIN CIERREN.TCAFOGRAL_VALOR_ACCION V 
	ON V.FCN_ID_VALOR_ACCION = SS.FCN_ID_VALOR_ACCION
INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MS 
	ON MS.FCN_ID_SUBPROCESO = SS.FTN_ID_SUBP 
	AND MS.FCN_ID_TIPO_SUBCTA = SS.FCN_ID_TIPO_SUBCTA_97 
	AND MS.FRB_VIGENCIA = '1'
INNER JOIN CIERREN.TFAFOGRAL_CONFIG_SUBPROCESO CS 
	ON CS.FCN_ID_SUBPROCESO = SS.FTN_ID_SUBP AND CS.FFB_VIGENCIA = '1'
WHERE MD.FTC_FOLIO_BITACORA = #sr_folio# AND MD.FTC_ESTA_REGI=1
ORDER BY MD.FTN_CTA_AFORE


