SELECT
  A.FTC_FOLIO_BITACORA AS FTC_FOLIO
 ,97 AS FTN_ID_PROCESO
 ,A.FTN_ID_SUBP AS FTN_ID_SUBPROCESO
 ,A.FTN_NUM_CTA_INVDUAL
 ,81 as FTN_ID_SIEFORE
,X.FCN_ID_TIPO_SUBCTA_97 AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,X.FTN_SDO_AIVS as FTN_MONTO_ACCIONES
,X.FTN_MONTO_PESOS AS  FTN_MONTO_PESOS
,X.FCN_ID_VALOR_ACCION AS FTN_ID_VALOR_ACCION 
,199 AS FTN_ID_TIPO_MONTO
,11 AS FTN_ID_SALDO_OPERA
,#sr_tipo_mov# AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT

FROM (
select DISTINCT
FTC_FOLIO_BITACORA
,FTN_CTA_AFORE AS FTN_NUM_CTA_INVDUAL
,FTN_ID_SUBP
,TRUNC(FTD_FEH_PRESEN, 'MM') AS FECHA_VALOR_ACCION
FROM PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
where
FTC_FOLIO_BITACORA=#sr_folio#
AND FTN_ID_SUBP=#sr_subproceso#
)A INNER JOIN (
select  
DISTINCT 
FTC_FOLIO_BITACORA,
FTN_NUM_CTA_INVDUAL,
sum(FTN_SDO_AIVS) as FTN_SDO_AIVS,
sum(FTN_MONTO_PESOS) as FTN_MONTO_PESOS,
FCN_ID_TIPO_SUBCTA_97,
max(FCN_ID_VALOR_ACCION) as FCN_ID_VALOR_ACCION
from PROCESOS.TTSISGRAL_SUF_SALDOS
where FTC_FOLIO_BITACORA=#sr_folio#
group by FTC_FOLIO_BITACORA,
FTN_NUM_CTA_INVDUAL,
FCN_ID_TIPO_SUBCTA_97
)X
ON A.FTC_FOLIO_BITACORA=X.FTC_FOLIO_BITACORA
AND A.FTN_NUM_CTA_INVDUAL=X.FTN_NUM_CTA_INVDUAL
INNER JOIN  CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C 
ON A.FTC_FOLIO_BITACORA=C.FTC_FOLIO
AND A.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
AND A.FTN_ID_SUBP=C.FCN_ID_SUBPROCESO

WHERE (C.FTB_ESTATUS_MARCA=0
OR C.FCN_CONV_INGTY=0)
 ORDER BY FTN_NUM_CTA_INVDUAL