WITH
BD_100_TRANS_INFONA
AS
(
SELECT
T.FTC_FOLIO_BITACORA,
ROWNUM AS CONTADOR_SERVICIO,
S.FTN_SDO_AIVS as FTN_NUM_APLI_INTE_VIVI97_TRA,
S.FTN_MONTO_PESOS as FTN_SALDO_VIVI97_TRAN
FROM PROCESOS.TTCRXGRAL_TRANS_INFONA T
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS S ON T.FTC_FOLIO_BITACORA=S.FTC_FOLIO_BITACORA 
                                          AND T.FTN_NUM_CTA_AFORE=S.FTN_NUM_CTA_INVDUAL 
                                          AND T.FTN_CONTA_SERV = S.FTN_CONTA_SERV
WHERE 1=1
AND T.FTC_FOLIO_BITACORA = '#SR_FOLIO#'
AND T.FTC_ESTATUS_REGISTRO = 1
AND T.FTN_ID_SUBP = #SR_SUBPROCESO#
)
SELECT
'09' AS TIPO_REG,
LPAD(TO_CHAR(CANTIDAD_REG),9,'0') AS CANTIDAD_REG,
LPAD(' ',30,' ') AS FILLER,

CASE WHEN FTN_NUM_APLI_INTE_VIVI97_TRA IS NULL THEN LPAD('0',18,'0')
ELSE   LPAD(
REPLACE(
     LPAD(SUBSTR(TO_CHAR(FTN_NUM_APLI_INTE_VIVI97_TRA), 1, INSTR(TO_CHAR(FTN_NUM_APLI_INTE_VIVI97_TRA,'FM9999999999.99'), '.') - 1),12,'0') 
   ||RPAD(SUBSTR(TRIM(TO_CHAR(FTN_NUM_APLI_INTE_VIVI97_TRA, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(FTN_NUM_APLI_INTE_VIVI97_TRA, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0'),'.','')
          ,18,'0') 
END AS  SUM_NUM_APLI,
CASE WHEN FTN_SALDO_VIVI97_TRAN IS NULL THEN LPAD('0',15,'0')
   ELSE 
   LPAD(
REPLACE(   
    LPAD(SUBSTR(TO_CHAR(FTN_SALDO_VIVI97_TRAN), 1, INSTR(TO_CHAR(FTN_SALDO_VIVI97_TRAN, 'FM9999999999.99'), '.') - 1),13,'0') 
    ||RPAD(SUBSTR(TRIM(TO_CHAR(FTN_SALDO_VIVI97_TRAN, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(FTN_SALDO_VIVI97_TRAN, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0'),'.','')
     ,15,'0')
END AS SUM_SALDO_VIV97,        
LPAD(' ',656,' ') AS FILLER2
FROM
(
SELECT
FTC_FOLIO_BITACORA AS FOLIO,
MAX(CONTADOR_SERVICIO) AS CANTIDAD_REG,
SUM(FTN_NUM_APLI_INTE_VIVI97_TRA) AS FTN_NUM_APLI_INTE_VIVI97_TRA,
SUM(FTN_SALDO_VIVI97_TRAN) AS FTN_SALDO_VIVI97_TRAN
FROM BD_100_TRANS_INFONA
GROUP BY
FTC_FOLIO_BITACORA
)