WITH
BD_100_TRANS_INFONA
AS
(
SELECT
1 AS BANDERA,
'02' AS TIPO_REGISTRO,
ROWNUM AS CONTADOR_SERVICIO,
'04' AS TIPO_ENT_RECEPT,
'002' AS CVE_ENT_RECEPT,
'01' AS TIPO_ENT_CED,
'534' AS CVE_ENT_CED,
T.FTN_CONTA_SERV,
T.FTN_NUM_CTA_AFORE,
T.FTN_ID_SUBP,
T.FTC_ORIGEN_TRANSFE,
T.FTC_CURP_TRABA,
T.FTC_NSS_TRABA_INFO,
T.FTC_RFC_TRABA_INFO,
T.FTC_APELLIDO_PATE_INFO,
T.FTC_APELLIDO_MATE_INFO,
T.FTC_NOMBRES_INFO,
T.FTC_IDENT_LOTE_SOLI,
T.FTC_NSS_TRABA_AFORE,
T.FTC_RFC_TRABA_AFORE,
T.FTC_APELLIDO_PATE_AFORE,
T.FTC_APELLIDO_MATE_AFORE,
T.FTC_NOMBRE_AFORE,
T.FTC_INDI_DIFE_VIVI92,
T.FTC_INDI_DIFE_VIVI97,
S.FTN_SDO_AIVS,
S.FTN_SDO_AIVS_92,
T.FTC_NOMBRE_TRABA_IMSS,
T.FTC_NUMERO_CRED_INFONA,
T.FTC_FOLIO_BITACORA
FROM PROCESOS.TTCRXGRAL_TRANS_INFONA T
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS S ON T.FTC_FOLIO_BITACORA=S.FTC_FOLIO_BITACORA 
                                          AND T.FTN_NUM_CTA_AFORE=S.FTN_NUM_CTA_INVDUAL 
                                          AND T.FTN_CONTA_SERV = S.FTN_CONTA_SERV
WHERE 1=1
AND T.FTC_FOLIO_BITACORA = '#SR_FOLIO#'
AND T.FTC_ESTATUS_REGISTRO = 1
AND T.FTN_ID_SUBP = #SR_SUBPROCESO#
)
SELECT
'09' AS TIPO_REG,
LPAD(TO_CHAR(CANTIDAD_REG),9,'0') AS CANTIDAD_REG,
LPAD(' ',30,' ') AS FILLER1,
CASE WHEN SUM_NUM_APLI_VIV92 IS NULL THEN LPAD('0',18,'0')
ELSE   LPAD(
 REPLACE( 
     LPAD(SUBSTR(TO_CHAR(SUM_NUM_APLI_VIV92), 1, INSTR(TO_CHAR(SUM_NUM_APLI_VIV92,'FM9999999999.99'), '.') - 1),12,'0') 
   ||RPAD(SUBSTR(TRIM(TO_CHAR(SUM_NUM_APLI_VIV92, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(SUM_NUM_APLI_VIV92, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0'),'.','')
          ,18,'0') END SUM_NUM_APLI_VIV92,
          CASE WHEN SUM_NUM_APLI_VIV92 IS NULL THEN LPAD('0',18,'0')
ELSE   LPAD(
 REPLACE(  
     LPAD(SUBSTR(TO_CHAR(SUM_NUM_APLI_VIV97), 1, INSTR(TO_CHAR(SUM_NUM_APLI_VIV97,'FM9999999999.99'), '.') - 1),12,'0') 
   ||RPAD(SUBSTR(TRIM(TO_CHAR(SUM_NUM_APLI_VIV97, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(SUM_NUM_APLI_VIV97, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0'),'.','')
          ,18,'0') END SUM_NUM_APLI_VIV97,
LPAD(' ',653,' ') AS FILLER2
FROM
(
SELECT
FTC_FOLIO_BITACORA AS FOLIO,
MAX(CONTADOR_SERVICIO) AS CANTIDAD_REG,
SUM(FTN_SDO_AIVS) AS SUM_NUM_APLI_VIV97,
SUM(FTN_SDO_AIVS_92) AS SUM_NUM_APLI_VIV92
FROM BD_100_TRANS_INFONA
GROUP BY
FTC_FOLIO_BITACORA
)