WITH FECHA_PRESENTACION
AS(
SELECT
BANDERA,
 TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS DIA_HABIL
FROM (
    select 1 AS BANDERA,FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES = SUBSTR(TO_CHAR(TO_DATE('#SR_SYSDATE#','YYYYMMDD'),'YYYY-MM-DD'),6,2)
         AND FTN_ANIO = SUBSTR(TO_CHAR(TO_DATE('#SR_SYSDATE#','YYYYMMDD'),'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1  
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 12
GROUP BY BANDERA
),
BD_100_TRANS_INFONA
AS
(
SELECT
1 AS BANDERA,
'02' AS TIPO_REGISTRO,
ROWNUM AS CONTADOR_SERVICIO,
'04' AS TIPO_ENT_RECEPT,
'002' AS CVE_ENT_RECEPT,
'01' AS TIPO_ENT_CED,
'534' AS CVE_ENT_CED,
'18' AS FTC_ORIGEN_TRANSFE,
T.FTN_CONTA_SERV,
T.FTN_NUM_CTA_AFORE,
T.FTN_ID_SUBP,
T.FTC_CURP_TRABA,
T.FTC_NSS_TRABA_INFO,
T.FTC_RFC_TRABA_INFO,
T.FTC_APELLIDO_PATE_INFO,
T.FTC_APELLIDO_MATE_INFO,
T.FTC_NOMBRES_INFO,
T.FTC_IDENT_LOTE_SOLI,
T.FTC_NSS_TRABA_AFORE,
T.FTC_RFC_TRABA_AFORE,
T.FTC_APELLIDO_PATE_AFORE,
T.FTC_APELLIDO_MATE_AFORE,
T.FTC_NOMBRE_AFORE,
S.FTN_SDO_AIVS as FTN_NUM_APLI_INTE_VIVI97_TRA,
S.FTN_MONTO_PESOS as FTN_SALDO_VIVI97_TRAN,
T.FTC_NOMBRE_TRABA_IMSS,
T.FTC_NUMERO_CRED_INFONA,
T.FTN_PERIODO_PAGO,
T.FTC_FOLIO_BITACORA,
1 AS CRUCE
FROM PROCESOS.TTCRXGRAL_TRANS_INFONA T
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS S ON T.FTC_FOLIO_BITACORA=S.FTC_FOLIO_BITACORA 
                                          AND T.FTN_NUM_CTA_AFORE=S.FTN_NUM_CTA_INVDUAL 
                                          AND T.FTN_CONTA_SERV = S.FTN_CONTA_SERV
WHERE 1=1 
AND T.FTC_FOLIO_BITACORA = '#SR_FOLIO#' --'202507231058102829' 
AND T.FTC_ESTATUS_REGISTRO = 1
AND T.FTN_ID_SUBP = #SR_SUBPROCESO#  --368 
),
BD_100_CALENDARIO
AS
(
SELECT TO_CHAR(TRUNC(ADD_MONTHS(TO_DATE('#SR_SYSDATE#','YYYYMMDD'),1),'MM'),'YYYYMMDD') AS FECHA_MOVIENTO, 
1 AS CRUCE 
FROM DUAL
)
SELECT
A.TIPO_REGISTRO,
LPAD(A.CONTADOR_SERVICIO,10,'0') AS CONTADOR_SERVICIO,
A.TIPO_ENT_RECEPT,
A.CVE_ENT_RECEPT,
A.TIPO_ENT_CED,
A.CVE_ENT_CED,
A.FTC_ORIGEN_TRANSFE,
CASE WHEN FECH.DIA_HABIL IS NULL THEN LPAD(' ',8,' ') ELSE FECH.DIA_HABIL END AS FECHA_PRESENTACION,
CASE WHEN CAL.FECHA_MOVIENTO IS NULL THEN LPAD(' ',8,' ') ELSE CAL.FECHA_MOVIENTO END AS FECHA_MOVIMIENTO,
CASE WHEN A.FTC_CURP_TRABA IS NULL THEN LPAD(' ',18,' ') ELSE LPAD(A.FTC_CURP_TRABA,18,' ') END AS FTC_CURP_TRABA,
CASE WHEN A.FTC_NSS_TRABA_INFO IS NULL THEN LPAD(' ',11,' ') ELSE LPAD(A.FTC_NSS_TRABA_INFO,11,' ') END AS FTC_NSS_TRABA_INFO,
LPAD(' ',15,' ') AS FILLER,
CASE WHEN A.FTC_RFC_TRABA_INFO IS NULL THEN RPAD(' ',13,' ') ELSE RPAD(A.FTC_RFC_TRABA_INFO,13,' ') END AS FTC_RFC_TRABA_INFO,
CASE WHEN A.FTC_APELLIDO_PATE_INFO IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_PATE_INFO,40,' ') END AS FTC_APELLIDO_PATE_INFO,
CASE WHEN A.FTC_APELLIDO_MATE_INFO IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_MATE_INFO,40,' ') END AS FTC_APELLIDO_MATE_INFO,
CASE WHEN A.FTC_NOMBRES_INFO IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_NOMBRES_INFO,40,' ') END AS FTC_NOMBRES_INFO,
LPAD(' ',22,' ') AS FILLER1,
CASE WHEN A.FTC_IDENT_LOTE_SOLI IS NULL THEN LPAD(' ',16,' ') ELSE LPAD(A.FTC_IDENT_LOTE_SOLI,16,' ') END AS FTC_IDENT_LOTE_SOLI,
LPAD(' ',15,' ') AS FILLER2,
CASE WHEN A.FTC_NSS_TRABA_AFORE IS NULL THEN LPAD(' ',11,' ') ELSE LPAD(A.FTC_NSS_TRABA_AFORE,11,' ') END AS FTC_NSS_TRABA_AFORE,
CASE WHEN A.FTC_RFC_TRABA_AFORE IS NULL THEN RPAD(' ',13,' ') ELSE RPAD(A.FTC_RFC_TRABA_AFORE,13,' ') END AS FTC_RFC_TRABA_AFORE,
LPAD(' ',30,' ') AS FILLER3,
CASE WHEN A.FTC_APELLIDO_PATE_AFORE IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_PATE_AFORE,40,' ') END AS FTC_APELLIDO_PATE_AFORE,
CASE WHEN A.FTC_APELLIDO_MATE_AFORE IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_MATE_AFORE,40,' ') END AS FTC_APELLIDO_MATE_AFORE,
CASE WHEN A.FTC_NOMBRE_AFORE IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_NOMBRE_AFORE,40,' ') END AS FTC_NOMBRES_AFORE,
LPAD(' ',30,' ') AS FILLER4,
CASE WHEN A.FTN_NUM_APLI_INTE_VIVI97_TRA IS NULL THEN LPAD('0',15,'0')
ELSE   LPAD(
    REPLACE(
     LPAD(SUBSTR(TO_CHAR(A.FTN_NUM_APLI_INTE_VIVI97_TRA), 1, INSTR(TO_CHAR(A.FTN_NUM_APLI_INTE_VIVI97_TRA, 'FM9999999999.99'), '.') - 1),9,'0') 
   ||RPAD(SUBSTR(TRIM(TO_CHAR(A.FTN_NUM_APLI_INTE_VIVI97_TRA, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(A.FTN_NUM_APLI_INTE_VIVI97_TRA, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
   ,'.','')
          ,15,'0') END FTN_NUM_APLI_INTE_VIVI97_TRA,      
CASE WHEN A.FTN_SALDO_VIVI97_TRAN IS NULL THEN LPAD('0',15,'0')
    ELSE 
    LPAD(
    REPLACE(    
    LPAD(SUBSTR(TO_CHAR(A.FTN_SALDO_VIVI97_TRAN), 1, INSTR(TO_CHAR(A.FTN_SALDO_VIVI97_TRAN, 'FM9999999999.99'), '.') - 1),13,'0') 
    ||RPAD(SUBSTR(TRIM(TO_CHAR(A.FTN_SALDO_VIVI97_TRAN, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(A.FTN_SALDO_VIVI97_TRAN, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0')
    ,'.','')
    ,15,'0')
END AS FTN_SALDO_VIVI97_TRAN,
LPAD(' ',78,' ') AS FILLER5,     
LPAD(' ',2,' ') AS COD_RESULT_OPERACION,
LPAD(' ',15,' ') AS DIAG_PROCESO,
CASE WHEN A.FTC_NOMBRE_TRABA_IMSS IS NULL THEN RPAD(' ',50,' ') ELSE RPAD(A.FTC_NOMBRE_TRABA_IMSS,50,' ') END AS FTC_NOMBRE_TRABA_IMSS,
LPAD(NVL(A.FTC_NUMERO_CRED_INFONA,0),10,'0') AS FTN_NUMERO_CRED_INFONA,
LPAD(' ',53,' ') AS FILLER6,
CASE WHEN A.FTN_PERIODO_PAGO IS NULL THEN RPAD('0',6,'0') ELSE REPLACE(LTRIM(RTRIM(FTN_PERIODO_PAGO)),'.','') END AS FTN_PERIODO_PAGO,
LPAD(' ',12,' ') AS FILLER7
FROM BD_100_TRANS_INFONA A
INNER JOIN BD_100_CALENDARIO CAL ON A.CRUCE = CAL.CRUCE
INNER JOIN FECHA_PRESENTACION FECH ON A.BANDERA = FECH.BANDERA