SELECT 
TEXTO
FROM
(
SELECT 
1 AS ORDEN, 
TIPO_REGISTRO||
ID_SERVICIO||
ID_OPERACION||
TIPO_ENTIDAD_ORI||
CLAVE_ENTIDAD_ORI||
TIPO_ENTIDAD_DES||
CLAVE_ENTIDAD_DES||
ENTIDAD_FED_LOTE||
FECHA_PRESENTACION||
CONSECUTIVO_LOTE||
FILLER_CVEMODAL_RECEP||
CODIGO_RES_OPER||
MOTIV_RECH_LOTE||
FILLER1 AS TEXTO
FROM #DELTA_SOLMARC_ENCABEZADO#
UNION 
SELECT
2 AS ORDEN,
TIPO_REGISTRO||
CONTADOR_SERVICIO||
TIPO_ENT_RECEPT||
CVE_ENT_RECEPT||
TIPO_ENT_CED||
CVE_ENT_CED||
FTC_ORIGEN_TRANSFE||
FECHA_PRESENTACION||
FECHA_MOVIMIENTO||
FTC_CURP_TRABA||
FTC_NSS_TRABA_INFO||
FILLER||
FTC_RFC_TRABA_INFO||
FTC_APELLIDO_PATE_INFO||
FTC_APELLIDO_MATE_INFO||
FTC_NOMBRES_INFO||
FILLER1||
FTC_IDENT_LOTE_SOLI||
FILLER2||
FTC_NSS_TRABA_AFORE||
FTC_RFC_TRABA_AFORE||
FILLER3||
FTC_APELLIDO_PATE_AFORE||
FTC_APELLIDO_MATE_AFORE||
FTC_NOMBRES_AFORE||
FILLER4||
FTN_NUM_APLI_INTE_VIVI97_TRA||
FTN_SALDO_VIVI97_TRAN||
FILLER5||
COD_RESULT_OPERACION||
DIAG_PROCESO||
FTC_NOMBRE_TRABA_IMSS||
FTN_NUMERO_CRED_INFONA||
FILLER6||
FTN_PERIODO_PAGO||
FILLER7 AS TEXTO
FROM #DELTA_SOLMARC_DETALLE#
UNION
SELECT
3 AS ORDEN,
TIPO_REG||
CANTIDAD_REG||
FILLER||
SUM_NUM_APLI||
SUM_SALDO_VIV97||
FILLER2 AS TEXTO
FROM #DELTA_SOLMARC_SUMARIO#
)
ORDER BY 1 ASC