MERGE INTO PROCESOS.TTCRXGRAL_TRANS_INFONA INFONA
USING (
WITH
FECHA_PRESENTACION
AS
(
SELECT
BANDERA,
 TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS DIA_HABIL
FROM (
    select 1 AS BANDERA,FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES       = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),6,2)
        AND FTN_ANIO        = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1  
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 12
GROUP BY BANDERA
),
BD_100_TRANS_INFONA
AS
(
SELECT
1 AS BANDERA,
ROWNUM AS CONTADOR_SERVICIO,
T.FTN_CONTA_SERV,
T.FTN_NUM_CTA_AFORE,
T.FTN_ID_SUBP,
T.FTC_FOLIO_BITACORA,
TO_TIMESTAMP('#SR_TIMESTAMP#','DD-MM-YYYY HH24:MI:SS.FF6') AS FTD_FEH_ACT
FROM PROCESOS.TTCRXGRAL_TRANS_INFONA T
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS S ON T.FTC_FOLIO_BITACORA=S.FTC_FOLIO_BITACORA 
                                          AND T.FTN_NUM_CTA_AFORE=S.FTN_NUM_CTA_INVDUAL 
                                          AND T.FTN_CONTA_SERV = S.FTN_CONTA_SERV
WHERE 1=1
AND T.FTC_FOLIO_BITACORA =  '#SR_FOLIO#' --'202507231058102829'
AND T.FTC_ESTATUS_REGISTRO = 1
AND T.FTN_ID_SUBP = #SR_SUBPROCESO#   -- 368
),
TTCRXGRAL_TRANS_INFONA_AUX
AS
(
SELECT
A.FTC_FOLIO_BITACORA,
A.FTN_CONTA_SERV,
A.FTN_NUM_CTA_AFORE,
A.FTN_ID_SUBP,
A.CONTADOR_SERVICIO AS FTN_CONTA_SERV_PROC,
TO_DATE(F.DIA_HABIL,'YYYYMMDD') AS FTD_FEH_PRESEN_PROC,
A.FTD_FEH_ACT,
'#SR_USUARIO#' AS FCC_USU_ACT
FROM BD_100_TRANS_INFONA A
INNER JOIN FECHA_PRESENTACION F ON A.BANDERA = F.BANDERA
)
SELECT * FROM TTCRXGRAL_TRANS_INFONA_AUX 
) AUX
ON (
    INFONA.FTC_FOLIO_BITACORA = AUX.FTC_FOLIO_BITACORA
    AND INFONA.FTN_CONTA_SERV = AUX.FTN_CONTA_SERV
    AND INFONA.FTN_NUM_CTA_AFORE = AUX.FTN_NUM_CTA_AFORE
    AND INFONA.FTN_ID_SUBP = AUX.FTN_ID_SUBP
)
WHEN MATCHED THEN 
UPDATE SET
    INFONA.FTN_CONTA_SERV_PROC = AUX.FTN_CONTA_SERV_PROC,
    INFONA.FTD_FEH_PRESEN_PROC = AUX.FTD_FEH_PRESEN_PROC,
    INFONA.FTD_FEH_ACT = AUX.FTD_FEH_ACT,
    INFONA.FCC_USU_ACT = AUX.FCC_USU_ACT