SELECT DISTINCT
CAST(FTN_ID_ARCHIVO AS INT ) AS FTN_ID_ARCHIVO,
--FTC_FOLIO, --- Descomentar para consulta normal pero no este no se guardaria en la tabla auxiliar
FTC_NOMBRE,
CAST(FCN_ID_PROCESO AS INT ) AS FCN_ID_PROCESO,
CAST(FCN_ID_SUBPROCESO AS INT ) AS FCN_ID_SUBPROCESO,
FTD_FEH_GEN,
FTD_FEH_ACT,
FTC_USU_ACT,
FTD_FEH_ARCHIVO,
CAST(FCN_ID_ESTATUS_ARCHIVO AS INT) AS FCN_ID_ESTATUS_ARCHIVO
FROM
(
SELECT
  ARC.FTN_ID_ARCHIVO,
  AF.FTC_FOLIO,
  CASE 
    WHEN ARC.FCN_ID_SUBPROCESO = 364 THEN '#SR_PREFIJO_ARCH_TA_364##SR_FECHA_ACTUAL##SR_NOM_ARCHIVO_RECH_TA_364##SR_EXT_TXT#' 
    WHEN ARC.FCN_ID_SUBPROCESO = 365 THEN '#SR_PREFIJO_ARCH_AG_365##SR_FECHA_ACTUAL##SR_NOM_ARCHIVO_RECH_AG_365##SR_EXT_TXT#' 
    WHEN ARC.FCN_ID_SUBPROCESO = 368 THEN '#SR_PREFIJO_ARCH_UG_368##SR_FECHA_ACTUAL##SR_NOM_ARCHIVO_RECH_UG_368##SR_EXT_TXT#'
  END AS FTC_NOMBRE,
  #SR_PROCESO# AS FCN_ID_PROCESO,
  #SR_SUBPROCESO# AS FCN_ID_SUBPROCESO,
  TO_TIMESTAMP('#SR_TIMESTAMP#','DD-MM-YYYY HH24:MI:SS.FF6') AS FTD_FEH_GEN,
  TO_TIMESTAMP('#SR_TIMESTAMP#','DD-MM-YYYY HH24:MI:SS.FF6')  AS FTD_FEH_ACT,
  '#SR_USUARIO#' AS FTC_USU_ACT,
  TO_TIMESTAMP('#SR_TIMESTAMP#','DD-MM-YYYY HH24:MI:SS.FF6')  AS FTD_FEH_ARCHIVO,
  4186 AS FCN_ID_ESTATUS_ARCHIVO
FROM
  CIERREN.TRAFOGRAL_ARCHIVO_FOLIO AF
INNER JOIN   CIERREN.TTAFOGRAL_ARCHIVO ARC ON AF.FTN_ID_ARCHIVO = ARC.FTN_ID_ARCHIVO
WHERE
  AF.FTC_FOLIO = '#SR_FOLIO#'
  AND ARC.FTN_ID_ARCHIVO = '#SR_ID_ARCHIVO_06#'  ---- prefijo 06 para archivos rechazados
  )