WITH FECHA_PRESENTACION
AS(
SELECT
BANDERA,
 TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS DIA_HABIL
FROM (
    select 1 AS BANDERA,FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES = SUBSTR(TO_CHAR(TO_DATE('#SR_SYSDATE#','YYYYMMDD'),'YYYY-MM-DD'),6,2)
        AND FTN_ANIO = SUBSTR(TO_CHAR(TO_DATE('#SR_SYSDATE#','YYYYMMDD'),'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1  
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 12
GROUP BY BANDERA
),
BD_100_TRANS_INFONA AS
(
SELECT
A.BANDERA,
B.DIA_HABIL,
A.FTN_ID_SUBP,
A.PROCESOS
FROM
(
SELECT
1 AS BANDERA,
FTN_ID_SUBP,
SUM(Reg) PROCESOS
FROM(
 SELECT 
   COUNT(DISTINCT(FTC_FOLIO_BITACORA)) Reg
   ,FTC_FOLIO_BITACORA
   ,FTN_ID_SUBP
 FROM PROCESOS.TTCRXGRAL_TRANS_INFONA
 WHERE FTD_FEH_CARGA = TO_DATE('#SR_CARGA#', 'DD/MM/YY')
AND FTN_ID_SUBP = #SR_SUBPROCESO#
---AND FTC_ESTATUS_REGISTRO=1
 GROUP BY FTC_FOLIO_BITACORA,FTN_ID_SUBP)
 GROUP BY FTN_ID_SUBP
 ) A 
 INNER JOIN FECHA_PRESENTACION B ON A.BANDERA = B.BANDERA
 )
 SELECT 
'01' AS TIPO_REGISTRO,
'02' AS ID_SERVICIO,
'06' AS ID_OPERACION,
'01' AS TIPO_ENTIDAD_ORI,
'534' AS CLAVE_ENTIDAD_ORI,
'04' AS TIPO_ENTIDAD_DES,
'002' AS CLAVE_ENTIDAD_DES,
'009' AS ENTIDAD_FED_LOTE,
DIA_HABIL AS FECHA_PRESENTACION,
CASE WHEN PROCESOS IS NULL THEN '001' ELSE LPAD(PROCESOS,3,'0') END AS CONSECUTIVO_LOTE,
CASE WHEN #SR_SUBPROCESO# = 364 THEN '02' ELSE LPAD(' ',2,' ') END AS FILLER_CVEMODAL_RECEP,
LPAD(' ',2,' ')  Codigo_res_oper,
LPAD(' ',9,' ')  Motiv_rech_lote,
LPAD(' ',687,' ')AS FILLER1
 FROM BD_100_TRANS_INFONA