WITH
BD_100_TRANS_INFONA
AS
(
SELECT
ROWNUM AS CONTADOR_SERVICIO,
T.FTC_FOLIO_BITACORA,
T.FTN_NUM_AIVS_VIVI97_ULT,
T.FTN_UTLIMA_APOR_VIVI97
FROM PROCESOS.TTCRXGRAL_TRANS_INFONA T
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS S ON T.FTC_FOLIO_BITACORA=S.FTC_FOLIO_BITACORA 
AND T.FTN_NUM_CTA_AFORE=S.FTN_NUM_CTA_INVDUAL 
AND T.FTN_CONTA_SERV = S.FTN_CONTA_SERV
WHERE 1=1 
AND T.FTC_FOLIO_BITACORA = '#SR_FOLIO#' 
AND T.FTC_ESTATUS_REGISTRO = 0
AND T.FTN_ID_SUBP = #SR_SUBPROCESO# -- 364
)
SELECT 
'09' AS TIPO_REGISTRO,
LPAD(CONTADOR_SERVICIO,09,'0') AS CONSECUTIVO,
LPAD(' ',30,' ') AS FILLER,
CASE 
        WHEN FTN_NUM_AIVS_VIVI97_ULT IS NULL THEN LPAD('0',15,'0')
         ELSE
        LPAD(
    REPLACE(
     LPAD(SUBSTR(TO_CHAR(FTN_NUM_AIVS_VIVI97_ULT), 1, INSTR(TO_CHAR(FTN_NUM_AIVS_VIVI97_ULT, 'FM9999999999.99'), '.') - 1),9,'0') 
   ||RPAD(SUBSTR(TRIM(TO_CHAR(FTN_NUM_AIVS_VIVI97_ULT, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(FTN_NUM_AIVS_VIVI97_ULT, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0'),'.','')
          ,15,'0') END FTN_NUM_AIVS_VIVI97_ULT,   
CASE 
        WHEN FTN_UTLIMA_APOR_VIVI97 IS NULL THEN LPAD('0',15,'0')
            ELSE 
          LPAD(
            REPLACE(
          LPAD(SUBSTR(TO_CHAR(FTN_UTLIMA_APOR_VIVI97), 1, INSTR(TO_CHAR(FTN_UTLIMA_APOR_VIVI97, 'FM9999999999.99'), '.') - 1),13,'0') 
		  || RPAD(SUBSTR(TRIM(TO_CHAR(FTN_UTLIMA_APOR_VIVI97, 'FM9999999999.99')||'00'),INSTR(TRIM(TO_CHAR(FTN_UTLIMA_APOR_VIVI97, 'FM9999999999.99')||'00'), '.') + 1, 2),2,'0'),'.','')
          ,15,'0')
END AS FTN_UTLIMA_APOR_VIVI97,
LPAD(' ',659,' ') AS FILLER1
FROM
(
SELECT
FTC_FOLIO_BITACORA,
MAX(CONTADOR_SERVICIO) AS CONTADOR_SERVICIO,
SUM(FTN_NUM_AIVS_VIVI97_ULT) AS FTN_NUM_AIVS_VIVI97_ULT,
SUM(FTN_UTLIMA_APOR_VIVI97) AS FTN_UTLIMA_APOR_VIVI97
FROM BD_100_TRANS_INFONA
GROUP BY FTC_FOLIO_BITACORA
)