 WITH
FECHA_PRESENTACION
AS
(
SELECT
BANDERA,
 TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS DIA_HABIL
FROM (
    select 1 AS BANDERA,FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES = SUBSTR(TO_CHAR(TO_DATE('#SR_SYSDATE#','YYYYMMDD'),'YYYY-MM-DD'),6,2)
         AND FTN_ANIO = SUBSTR(TO_CHAR(TO_DATE('#SR_SYSDATE#','YYYYMMDD'),'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1  
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 12
GROUP BY BANDERA
),
BD_200_MAP_CVES
AS
(
SELECT 
C.FTN_MOTIVO_RECHAZO,
LPAD(I.TMN_CVE_ITGY,2,'0') AS TMN_CVE_ITGY
FROM(
SELECT FCN_ID_CAT_CATALOGO AS TMN_CVE_NCI,
CASE 
WHEN FCN_ID_TIPO_CAT=3   THEN FCN_ID_CAT_CATALOGO ---RECHAZO PROCESO NCI
WHEN FCN_ID_TIPO_CAT=20  THEN FCN_ID_CAT_CATALOGO ---RECHAZOS IDC
WHEN FCN_ID_TIPO_CAT=223 THEN TO_NUMBER(FCC_VALOR)---RECHAZOS VIVENDA 
WHEN FCN_ID_TIPO_CAT=291 THEN TO_NUMBER(FCC_VALOR)---RECHAZOS VIVENDA 
END FTN_MOTIVO_RECHAZO
FROM CIERREN.TCCRXGRAL_CAT_CATALOGO 
WHERE FCN_ID_TIPO_CAT IN (3,20,223,291)
)C
INNER JOIN CIERREN.TMSISGRAL_MAP_NCI_ITGY I 
ON C.TMN_CVE_NCI=I.TMN_CVE_NCI
WHERE I.TMC_USO='MOTIVO DE RECHAZO PARA PROCESAR DE ANUALIDADES GARANTIZADAS'

),
BD_100_TRANS_INFONA
AS
(
SELECT
1 AS BANDERA,
'02' AS TIPO_REGISTRO,
ROWNUM AS CONTADOR_SERVICIO,
'04' AS TIPO_ENT_RECEPT,
'002' AS CVE_ENT_RECEPT,
'01' AS TIPO_ENT_CED,
'534' AS CVE_ENT_CED,
T.FTC_ORIGEN_TRANSFE,
T.FTC_CURP_TRABA,
T.FTC_NSS_TRABA_INFO,
T.FTC_RFC_TRABA_INFO,
T.FTC_APELLIDO_PATE_INFO,
T.FTC_APELLIDO_MATE_INFO,
T.FTC_NOMBRES_INFO,
T.FTC_IDENT_LOTE_SOLI,
T.FTC_NSS_TRABA_AFORE,
T.FTC_RFC_TRABA_AFORE,
T.FTC_APELLIDO_PATE_AFORE,
T.FTC_APELLIDO_MATE_AFORE,
T.FTC_NOMBRE_AFORE,
T.FTC_NOMBRE_TRABA_IMSS,
T.FTC_NUMERO_CRED_INFONA,
T.FTC_FOLIO_BITACORA,
T.FTN_MOTIVO_RECHAZO
FROM PROCESOS.TTCRXGRAL_TRANS_INFONA T
WHERE 1=1 
AND T.FTC_FOLIO_BITACORA = '#SR_FOLIO#'  --'202507211759137875'
AND T.FTC_ESTATUS_REGISTRO = 0
AND T.FTN_ID_SUBP = #SR_SUBPROCESO#  --365
)
SELECT 
A.TIPO_REGISTRO,
LPAD(A.CONTADOR_SERVICIO,10,'0') AS CONTADOR_SERVICIO,
A.TIPO_ENT_RECEPT,
A.CVE_ENT_RECEPT,
A.TIPO_ENT_CED,
A.CVE_ENT_CED,
CASE WHEN A.FTC_ORIGEN_TRANSFE IS NULL THEN LPAD(' ',2,' ') ELSE LPAD(A.FTC_ORIGEN_TRANSFE,2,' ') END AS FTC_ORIGEN_TRANSFE,
F.DIA_HABIL AS FECHA_PRES,
LPAD(' ',8,' ') AS FILLER,
CASE WHEN A.FTC_CURP_TRABA IS NULL THEN LPAD(' ',18,' ') ELSE LPAD(A.FTC_CURP_TRABA,18,' ') END AS FTC_CURP_TRABA,
CASE WHEN A.FTC_NSS_TRABA_INFO IS NULL THEN LPAD(' ',11,' ') ELSE LPAD(A.FTC_NSS_TRABA_INFO,11,' ') END AS FTC_NSS_TRABA_INFO,
LPAD(' ',15,' ') AS FILLER1,
CASE WHEN A.FTC_RFC_TRABA_INFO IS NULL THEN RPAD(' ',13,' ') ELSE RPAD(A.FTC_RFC_TRABA_INFO,13,' ') END AS FTC_RFC_TRABA_INFO,
CASE WHEN A.FTC_APELLIDO_PATE_INFO IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_PATE_INFO,40,' ') END AS FTC_APELLIDO_PATE_INFO,
CASE WHEN A.FTC_APELLIDO_MATE_INFO IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_MATE_INFO,40,' ') END AS FTC_APELLIDO_MATE_INFO,
CASE WHEN A.FTC_NOMBRES_INFO IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_NOMBRES_INFO,40,' ') END AS FTC_NOMBRES_INFO,
LPAD(' ',22,' ') AS FILLER2,
CASE WHEN A.FTC_IDENT_LOTE_SOLI IS NULL THEN LPAD(' ',16,' ') ELSE LPAD(A.FTC_IDENT_LOTE_SOLI,16,' ') END AS FTC_IDENT_LOTE_SOLI,
LPAD(' ',15,' ') AS FILLER3,
CASE WHEN A.FTC_NSS_TRABA_AFORE IS NULL THEN LPAD(' ',11,' ') ELSE LPAD(A.FTC_NSS_TRABA_AFORE,11,' ') END AS FTC_NSS_TRABA_AFORE,
CASE WHEN A.FTC_RFC_TRABA_AFORE IS NULL THEN RPAD(' ',13,' ') ELSE RPAD(A.FTC_RFC_TRABA_AFORE,13,' ') END AS FTC_RFC_TRABA_AFORE,
LPAD(' ',30,' ') AS FILLER4,
CASE WHEN A.FTC_APELLIDO_PATE_AFORE IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_PATE_AFORE,40,' ') END AS FTC_APELLIDO_PATE_AFORE,
CASE WHEN A.FTC_APELLIDO_MATE_AFORE IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_MATE_AFORE,40,' ') END AS FTC_APELLIDO_MATE_AFORE,
CASE WHEN A.FTC_NOMBRE_AFORE IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_NOMBRE_AFORE,40,' ') END AS FTC_NOMBRES_AFORE,
LPAD(' ',138,' ') AS FILLER5,
LPAD(' ',2,' ') AS COD_RESULT_OPERACION,
LPAD(' ',15,' ') AS DIAG_PROCESO,
CASE WHEN A.FTC_NOMBRE_TRABA_IMSS IS NULL THEN RPAD(' ',50,' ') ELSE RPAD(A.FTC_NOMBRE_TRABA_IMSS,50,' ') END AS FTC_NOMBRE_TRABA_IMSS,
LPAD(NVL(A.FTC_NUMERO_CRED_INFONA,0),10,'0') AS FTN_NUMERO_CRED_INFONA,
LPAD(' ',43,' ') AS FILLER6,
CASE WHEN BD_200.TMN_CVE_ITGY IS NULL THEN RPAD(' ',2,' ') ELSE LPAD(BD_200.TMN_CVE_ITGY,2,'0') END AS MOTIVO_DEVOL,
LPAD(' ',26,' ') AS FILLER8
FROM BD_100_TRANS_INFONA A
INNER JOIN FECHA_PRESENTACION F ON A.BANDERA = F.BANDERA
LEFT JOIN BD_200_MAP_CVES BD_200 ON A.FTN_MOTIVO_RECHAZO = BD_200.FTN_MOTIVO_RECHAZO