WITH
BD_100_TRANS_INFONA
AS
(
SELECT
'09' AS TIPO_REGISTRO,
ROWNUM AS CONTADOR_SERVICIO,
T.FTC_FOLIO_BITACORA
FROM PROCESOS.TTCRXGRAL_TRANS_INFONA T
WHERE 1=1 
AND T.FTC_FOLIO_BITACORA = '#SR_FOLIO#'
AND T.FTC_ESTATUS_REGISTRO = 0
AND T.FTN_ID_SUBP = #SR_SUBPROCESO#
)
SELECT
'09' AS TIPO_REG,
LPAD(TO_CHAR(CANTIDAD_REG),9,'0') AS CANTIDAD_REG,
LPAD(' ',719,' ') AS FILLER
FROM
(
SELECT
TIPO_REGISTRO,
MAX(CONTADOR_SERVICIO) AS CANTIDAD_REG
FROM BD_100_TRANS_INFONA
GROUP BY
TIPO_REGISTRO
)