SELECT
CASE
WHEN Tot_Reg_Proc >= 1 AND Tot_Reg_No_Proc = 0 Then '1' 
WHEN Tot_Reg_Proc >= 1 AND Tot_Reg_No_Proc >= 1 Then '3' 
WHEN Tot_Reg_Proc = 0 AND Tot_Reg_No_Proc >= 1 Then '2' 
ELSE '4'  END AS INDICADOR
FROM
(
SELECT 
 CAST(A.T_REG_PROC AS INT) AS Tot_Reg_Proc
,CAST(B.T_REG_NO_PROC AS INT) AS Tot_Reg_No_Proc
FROM(
      SELECT 
       COUNT(*) T_REG_PROC,
       1 CAMPO
      FROM PROCESOS.TTCRXGRAL_TRANS_INFONA
      WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'
      AND FTN_ID_SUBP = #SR_SUBPROCESO#
      AND FTC_ESTATUS_REGISTRO = 1
     --AND FTD_FEH_CARGA = TO_DATE(current_date, 'DD/MM/YY')
     )A, 
(
 SELECT 
   COUNT(*) T_REG_NO_PROC,
   1 CAMPO
 FROM PROCESOS.TTCRXGRAL_TRANS_INFONA
 WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'
      AND FTN_ID_SUBP = #SR_SUBPROCESO#
 AND FTC_ESTATUS_REGISTRO = 0
   --  AND FTD_FEH_CARGA = TO_DATE(current_date, 'DD/MM/YY')
)B
WHERE A.CAMPO = B.CAMPO
)