WITH
FECHA_PRESENTACION
AS
(
SELECT
BANDERA,
 TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS DIA_HABIL
FROM (
    select 1 AS BANDERA,FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES = SUBSTR(TO_CHAR(TO_DATE('#SR_SYSDATE#','YYYYMMDD'),'YYYY-MM-DD'),6,2)
        AND FTN_ANIO = SUBSTR(TO_CHAR(TO_DATE('#SR_SYSDATE#','YYYYMMDD'),'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1  
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 12
GROUP BY BANDERA
),
BD_100_TRANS_INFONA
AS
(
SELECT
1 AS BANDERA,
'02' AS TIPO_REGISTRO,
ROWNUM AS CONTADOR_SERVICIO,
'04' AS TIPO_ENT_RECEPT,
'002' AS CVE_ENT_RECEPT,
'01' AS TIPO_ENT_CED,
'534' AS CVE_ENT_CED,
T.FTN_CONTA_SERV,
T.FTN_NUM_CTA_AFORE,
T.FTN_ID_SUBP,
T.FTC_ORIGEN_TRANSFE,
T.FTC_CURP_TRABA,
T.FTC_NSS_TRABA_INFO,
T.FTC_RFC_TRABA_INFO,
T.FTC_APELLIDO_PATE_INFO,
T.FTC_APELLIDO_MATE_INFO,
T.FTC_NOMBRES_INFO,
T.FTC_IDENT_LOTE_SOLI,
T.FTC_NSS_TRABA_AFORE,
T.FTC_RFC_TRABA_AFORE,
T.FTC_APELLIDO_PATE_AFORE,
T.FTC_APELLIDO_MATE_AFORE,
T.FTC_NOMBRE_AFORE,
T.FTC_INDI_DIFE_VIVI92,
T.FTC_INDI_DIFE_VIVI97,
S.FTN_SDO_AIVS,
S.FTN_SDO_AIVS_92,
T.FTC_NOMBRE_TRABA_IMSS,
T.FTC_NUMERO_CRED_INFONA,
T.FTC_FOLIO_BITACORA
FROM PROCESOS.TTCRXGRAL_TRANS_INFONA T
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS S ON T.FTC_FOLIO_BITACORA=S.FTC_FOLIO_BITACORA 
                                          AND T.FTN_NUM_CTA_AFORE=S.FTN_NUM_CTA_INVDUAL 
                                          AND T.FTN_CONTA_SERV = S.FTN_CONTA_SERV
WHERE 1=1
AND T.FTC_FOLIO_BITACORA = '#SR_FOLIO#'
AND T.FTC_ESTATUS_REGISTRO = 1
AND T.FTN_ID_SUBP = #SR_SUBPROCESO#
)
SELECT 
A.TIPO_REGISTRO,
LPAD(A.CONTADOR_SERVICIO,10,'0') AS CONTADOR_SERVICIO,
A.TIPO_ENT_RECEPT,
A.CVE_ENT_RECEPT,
A.TIPO_ENT_CED,
A.CVE_ENT_CED,
CASE WHEN A.FTC_ORIGEN_TRANSFE IS NULL THEN LPAD(' ',2,' ') ELSE LPAD(A.FTC_ORIGEN_TRANSFE,2,' ') END AS FTC_ORIGEN_TRANSFE,
CASE WHEN F.DIA_HABIL IS NULL THEN LPAD(' ',8,' ') ELSE F.DIA_HABIL END AS FECHA_PRES,
LPAD(' ',8,' ') AS FILLER,
CASE WHEN A.FTC_CURP_TRABA IS NULL THEN LPAD(' ',18,' ') ELSE LPAD(A.FTC_CURP_TRABA,18,' ') END AS FTC_CURP_TRABA,
CASE WHEN A.FTC_NSS_TRABA_INFO IS NULL THEN LPAD(' ',11,' ') ELSE LPAD(A.FTC_NSS_TRABA_INFO,11,' ') END AS FTC_NSS_TRABA_INFO,
LPAD(' ',15,' ') AS FILLER1,
CASE WHEN A.FTC_RFC_TRABA_INFO IS NULL THEN RPAD(' ',13,' ') ELSE RPAD(A.FTC_RFC_TRABA_INFO,13,' ') END AS FTC_RFC_TRABA_INFO,
CASE WHEN A.FTC_APELLIDO_PATE_INFO IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_PATE_INFO,40,' ') END AS FTC_APELLIDO_PATE_INFO,
CASE WHEN A.FTC_APELLIDO_MATE_INFO IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_MATE_INFO,40,' ') END AS FTC_APELLIDO_MATE_INFO,
CASE WHEN A.FTC_NOMBRES_INFO IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_NOMBRES_INFO,40,' ') END AS FTC_NOMBRES_INFO,
LPAD(' ',22,' ') AS FILLER2,
CASE WHEN A.FTC_IDENT_LOTE_SOLI IS NULL THEN LPAD(' ',16,' ') ELSE LPAD(A.FTC_IDENT_LOTE_SOLI,16,' ') END AS FTC_IDENT_LOTE_SOLI,
LPAD(' ',15,' ') AS FILLER3,
CASE WHEN A.FTC_NSS_TRABA_AFORE IS NULL THEN LPAD(' ',11,' ') ELSE LPAD(A.FTC_NSS_TRABA_AFORE,11,' ') END AS FTC_NSS_TRABA_AFORE,
CASE WHEN A.FTC_RFC_TRABA_AFORE IS NULL THEN RPAD(' ',13,' ') ELSE RPAD(A.FTC_RFC_TRABA_AFORE,13,' ') END AS FTC_RFC_TRABA_AFORE,
LPAD(' ',30,' ') AS FILLER4,
CASE WHEN A.FTC_APELLIDO_PATE_AFORE IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_PATE_AFORE,40,' ') END AS FTC_APELLIDO_PATE_AFORE,
CASE WHEN A.FTC_APELLIDO_MATE_AFORE IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_APELLIDO_MATE_AFORE,40,' ') END AS FTC_APELLIDO_MATE_AFORE,
CASE WHEN A.FTC_NOMBRE_AFORE IS NULL THEN RPAD(' ',40,' ') ELSE RPAD(A.FTC_NOMBRE_AFORE,40,' ') END AS FTC_NOMBRE_AFORE,
LPAD(' ',30,' ') AS FILLER5,
---SE AJUSTA FTN_SDO_AIVS_92 PARA QUE SE RELLENE CON CEROS A LA DERE
CASE WHEN A.FTN_SDO_AIVS_92 IS NULL THEN LPAD('0',15,'0')
ELSE   LPAD(
REPLACE(
     LPAD(SUBSTR(TO_CHAR(A.FTN_SDO_AIVS_92), 1, INSTR(TO_CHAR(A.FTN_SDO_AIVS_92, 'FM9999999999.99'), '.') - 1),9,'0') 
   ||RPAD(SUBSTR(TRIM(TO_CHAR(A.FTN_SDO_AIVS_92, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(A.FTN_SDO_AIVS_92, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
,'.','')
,15,'0') END FTN_NUM_APLI_INTE_VIVI92,
--
CASE WHEN A.FTC_INDI_DIFE_VIVI92 IS NULL THEN LPAD(' ',2,' ') ELSE LPAD(TRIM(A.FTC_INDI_DIFE_VIVI92),2,'0') END AS FTC_INDI_DIFE_VIVI92,
LPAD(' ',58,' ') AS FILLER6,
---SE AJUSTA FTN_SDO_AIVS PARA QUE SE RELLENE CON CEROS A LA DERECHA CUANDO NO TRAIGA DECIMALES
CASE WHEN A.FTN_SDO_AIVS IS NULL THEN LPAD('0',15,'0')
ELSE   LPAD(
REPLACE(
     LPAD(SUBSTR(TO_CHAR(A.FTN_SDO_AIVS), 1, INSTR(TO_CHAR(A.FTN_SDO_AIVS, 'FM9999999999.99'), '.') - 1),9,'0') 
   ||RPAD(SUBSTR(TRIM(TO_CHAR(A.FTN_SDO_AIVS, 'FM9999999999.999999')||'00'),INSTR(TRIM(TO_CHAR(A.FTN_SDO_AIVS, 'FM9999999999.999999')||'00'), '.') + 1, 6),6,'0')
,'.','')
  ,15,'0') END FTN_SDO_AIVS,
 --         
CASE WHEN A.FTC_INDI_DIFE_VIVI97 IS NULL THEN LPAD(' ',2,' ') ELSE LPAD(TRIM(A.FTC_INDI_DIFE_VIVI97),2,'0') END AS FTC_INDI_DIFE_VIVI97,
LPAD(' ',16,' ') AS FILLER7,
LPAD(' ',2,' ') AS COD_RESULT_OPERACION,
LPAD(' ',15,' ') AS DIAG_PROCESO,
CASE WHEN A.FTC_NOMBRE_TRABA_IMSS IS NULL THEN RPAD(' ',50,' ') ELSE RPAD(A.FTC_NOMBRE_TRABA_IMSS,50,' ') END AS FTC_NOMBRE_TRABA_IMSS,
LPAD(NVL(A.FTC_NUMERO_CRED_INFONA,0),10,'0') AS FTN_NUMERO_CRED_INFONA,
LPAD(' ',71,' ') AS FILLER8
FROM BD_100_TRANS_INFONA A
INNER JOIN FECHA_PRESENTACION F ON A.BANDERA = F.BANDERA