SELECT
  A.FTC_FOLIO AS FTC_FOLIO
 ,97 AS FTN_ID_PROCESO
 ,A.FCN_ID_SUBPROCESO AS FTN_ID_SUBPROCESO
 ,A.FTN_NUM_CTA_INVDUAL
 ,COALESCE(V.FCN_ID_SIEFORE,81) as FTN_ID_SIEFORE
,COALESCE(SUBCTA.FCN_ID_TIPO_SUBCTA,18) AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,SUM(NVL(BAL_MOVS.FTN_DISP_ACCIONES,0)) as FTN_MONTO_ACCIONES
, SUM(NVL(BAL_MOVS.FTN_DISP_ACCIONES,0) * COALESCE(V.FCN_VALOR_ACCION,0)) AS  FTN_MONTO_PESOS
,NVL(V.FCN_ID_VALOR_ACCION,0) AS FTN_ID_VALOR_ACCION 
,185 AS FTN_ID_TIPO_MONTO
,CS.FCN_ID_SALDO_OPERA AS FTN_ID_SALDO_OPERA
,180 AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT

FROM (
select DISTINCT
FTC_FOLIO
, FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL
,FCN_ID_SUBPROCESO
   FROM PROCESOS.TTAFOTRAS_DESMARCA_FOVST
where
FTC_FOLIO= #sr_folio#
AND  FTC_ESTATUS= 1
AND  FCN_ID_SUBPROCESO=#sr_subproceso#
)A
INNER JOIN CIERREN.TFAFOGRAL_CONFIG_SUBPROCESO CS 
ON A.FCN_ID_SUBPROCESO = CS.FCN_ID_SUBPROCESO AND CS.FFB_VIGENCIA = '1'
LEFT OUTER JOIN CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA MC
        ON A.FTC_FOLIO=MC.FTC_FOLIO
       AND A.FTN_NUM_CTA_INVDUAL=MC.FTN_NUM_CTA_INVDUAL
left outer join (
SELECT   A.FTC_NUM_CTA_INVDUAL 
         ,A.FCN_ID_TIPO_SUBCTA
         ,A.FCN_ID_SIEFORE
         ,B.FCN_ID_REGIMEN
         ,SUM(NVL(A.FTN_DISP_ACCIONES,0)) AS FTN_DISP_ACCIONES
  FROM   CIERREN.TTAFOGRAL_BALANCE_MOVS A
  INNER JOIN CIERREN.TCCRXGRAL_TIPO_SUBCTA B ON A.FCN_ID_TIPO_SUBCTA= B.FCN_ID_TIPO_SUBCTA
  AND A.FCN_ID_SIEFORE in (81)
  AND A.FCN_ID_TIPO_SUBCTA IN (18)
  GROUP BY A.FTC_NUM_CTA_INVDUAL, A.FCN_ID_TIPO_SUBCTA, A.FCN_ID_SIEFORE ,B.FCN_ID_REGIMEN

) BAL_MOVS
ON A.FTN_NUM_CTA_INVDUAL = BAL_MOVS.FTC_NUM_CTA_INVDUAL
LEFT JOIN CIERREN.TCCRXGRAL_TIPO_SUBCTA SUBCTA
ON BAL_MOVS.FCN_ID_TIPO_SUBCTA = SUBCTA.FCN_ID_TIPO_SUBCTA
LEFT JOIN (

SELECT  
 FCN_ID_VALOR_ACCION
,FCD_FEH_ACCION
,FCN_VALOR_ACCION
,FCN_ID_REGIMEN
,FCN_ID_SIEFORE
FROM CIERREN.TCAFOGRAL_VALOR_ACCION V
WHERE FCN_ID_SIEFORE = 81
AND FCN_ID_REGIMEN = 139
AND  TO_TIMESTAMP(TRUNC(V.FCD_FEH_ACCION),'DD-MM-YY HH24:MI:SS') = TO_TIMESTAMP(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'DD-MM-YY HH24:MI:SS')
)V ON
BAL_MOVS.FCN_ID_SIEFORE = V.FCN_ID_SIEFORE
AND SUBCTA.FCN_ID_REGIMEN = V.FCN_ID_REGIMEN
WHERE   (   MC.FTB_ESTATUS_MARCA =0 
        Or MC.FTB_ESTATUS_MARCA is null)
--LEFT JOIN CIERREN.TCCRXGRAL_TIPO_SUBCTA SUBCTA ON BAL_MOVS.FCN_ID_TIPO_SUBCTA = SUBCTA.FCN_ID_TIPO_SUBCTA
--LEFT JOIN CIERREN.TCAFOGRAL_VALOR_ACCION V ON BAL_MOVS.FCN_ID_SIEFORE = V.FCN_ID_SIEFORE
--AND SUBCTA.FCN_ID_REGIMEN = V.FCN_ID_REGIMEN
group by A.FTC_FOLIO,A.FCN_ID_SUBPROCESO,A.FTN_NUM_CTA_INVDUAL
 ,V.FCN_ID_SIEFORE,SUBCTA.FCN_ID_TIPO_SUBCTA,V.FCN_ID_VALOR_ACCION,CS.FCN_ID_SALDO_OPERA
 ORDER BY FTN_NUM_CTA_INVDUAL
 
