SELECT
   A.FTC_FOLIO AS FTC_FOLIO
 ,97 AS FTN_ID_PROCESO
 ,A.FTN_SUBPROCESO AS FTN_ID_SUBPROCESO
 ,A.FTN_NUM_CTA_INVDUAL  AS FTN_NUM_CTA_INVDUAL
 ,COALESCE(A.FCN_ID_SIEFORE,81) as FTN_ID_SIEFORE
,M.FCN_ID_TIPO_SUBCTA AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,NVL(X.FTN_DISP_ACCIONES,0) as FTN_MONTO_ACCIONES
,NVL(X.FTN_MONTO_PESOS,0) AS  FTN_MONTO_PESOS
,COALESCE(X.FCN_ID_VALOR_ACCION,0) AS FTN_ID_VALOR_ACCION 
,M.FCN_ID_TIPO_MONTO AS FTN_ID_TIPO_MONTO
,CS.FCN_ID_SALDO_OPERA AS FTN_ID_SALDO_OPERA
,M.FCN_ID_TIPO_MOV AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT

FROM (
SELECT 
TRP.FTN_NUM_CTA_INVDUAL,
TRP.FTC_FOLIO,
FCN_ID_SIEFORE,
TRP.FTN_SUBPROCESO,
25 AS TIPO_MOV,
TRP.FTN_NO_LINEA,
FTC_INSTITUTO_ORIGEN,
C.FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA TRP
INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C
ON TRP.FTC_FOLIO=C.FTC_FOLIO AND TRP.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
WHERE  TRP.FTC_FOLIO = #sr_folio#
AND (C.FTB_ESTATUS_MARCA=0 OR C.FCN_CONV_INGTY=0)
AND C.FCN_ID_TIPO_SUBCTA=15
AND FTC_INSTITUTO_ORIGEN='001'

UNION ALL 

SELECT 
TRP.FTN_NUM_CTA_INVDUAL,
TRP.FTC_FOLIO,
FCN_ID_SIEFORE,
TRP.FTN_SUBPROCESO,
25 AS TIPO_MOV,
TRP.FTN_NO_LINEA,
FTC_INSTITUTO_ORIGEN,
C.FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA TRP
INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C
ON TRP.FTC_FOLIO=C.FTC_FOLIO AND TRP.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
WHERE  TRP.FTC_FOLIO = #sr_folio#
AND (C.FTB_ESTATUS_MARCA=0 OR C.FCN_CONV_INGTY=0)
AND C.FCN_ID_TIPO_SUBCTA=16
AND FTC_INSTITUTO_ORIGEN='001'

UNION ALL 

SELECT 
TRP.FTN_NUM_CTA_INVDUAL,
TRP.FTC_FOLIO,
FCN_ID_SIEFORE,
TRP.FTN_SUBPROCESO,
25 AS TIPO_MOV,
TRP.FTN_NO_LINEA,
FTC_INSTITUTO_ORIGEN,
C.FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA TRP
INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C
ON TRP.FTC_FOLIO=C.FTC_FOLIO AND TRP.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
WHERE  TRP.FTC_FOLIO = #sr_folio#
AND (C.FTB_ESTATUS_MARCA=0 OR C.FCN_CONV_INGTY=0)
AND C.FCN_ID_TIPO_SUBCTA=18
AND FTC_INSTITUTO_ORIGEN='002'


UNION ALL

SELECT 
TRP.FTN_NUM_CTA_INVDUAL,
TRP.FTC_FOLIO,
FCN_ID_SIEFORE,
TRP.FTN_SUBPROCESO,
25 AS TIPO_MOV,
TRP.FTN_NO_LINEA,
FTC_INSTITUTO_ORIGEN,
C.FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA TRP
INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C
ON TRP.FTC_FOLIO=C.FTC_FOLIO AND TRP.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
WHERE  TRP.FTC_FOLIO = #sr_folio#
AND (C.FTB_ESTATUS_MARCA=0 OR C.FCN_CONV_INGTY=0)
AND C.FCN_ID_TIPO_SUBCTA=17
AND FTC_INSTITUTO_ORIGEN='002'

) A
INNER JOIN (
 select  
DISTINCT 
 FTC_FOLIO_BITACORA,
FTN_NUM_CTA_INVDUAL
,FTN_CONTA_SERV
,FCN_ESTATUS
,FTN_SDO_AIVS AS FTN_DISP_ACCIONES
,FTN_VALOR_AIVS
,FTN_MONTO_PESOS AS FTN_MONTO_PESOS
,FCN_ID_TIPO_SUBCTA_97 AS FCN_ID_TIPO_SUBCTA
,FCN_ID_REGIMEN
,FCN_ID_VALOR_ACCION
from PROCESOS.TTSISGRAL_SUF_SALDOS
where 
FTC_FOLIO_BITACORA=#sr_folio# AND 
FCN_ESTATUS=1 and FTN_IND_SDO_DISP_VIV97=1
UNION ALL

 select  
DISTINCT 
 FTC_FOLIO_BITACORA,
FTN_NUM_CTA_INVDUAL
,FTN_CONTA_SERV
,FCN_ESTATUS
,FTN_SDO_AIVS_92 AS FTN_DISP_ACCIONES
,FTN_VALOR_AIVS
,FTN_MONTO_PESOS_92 AS FTN_MONTO_PESOS
,FCN_ID_TIPO_SUBCTA_92 AS FCN_ID_TIPO_SUBCTA
,FCN_ID_REGIMEN
,FCN_ID_VALOR_ACCION
from PROCESOS.TTSISGRAL_SUF_SALDOS
where 
FTC_FOLIO_BITACORA=#sr_folio# AND 
FCN_ESTATUS=1 and FTN_IND_SDO_DISP_92=1

)X
ON A.FTC_FOLIO=X.FTC_FOLIO_BITACORA
AND A.FTN_NUM_CTA_INVDUAL=X.FTN_NUM_CTA_INVDUAL
AND A.FTN_NO_LINEA=X.FTN_CONTA_SERV 
AND A.FCN_ID_TIPO_SUBCTA=X.FCN_ID_TIPO_SUBCTA

INNER JOIN(
SELECT  CMOV.FRN_ID_MOV_SUBCTA
       ,MSUB.FCN_ID_SUBPROCESO
       ,MSUB.FCN_ID_TIPO_SUBCTA
       ,MSUB.FCN_ID_TIPO_MOV
       ,CMOV.FFN_ID_CONCEPTO_MOV
       ,CMOV.FCN_ID_TIPO_MONTO
       ,CAT.FCN_ID_TIPO_CAT AS TIPO_MOV
       ,FCN_ID_REGIMEN
FROM       CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CMOV
INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB ON CMOV.FRN_ID_MOV_SUBCTA = MSUB.FRN_ID_MOV_SUBCTA
INNER JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO CAT ON MSUB.FCN_ID_TIPO_MOV = CAT.FCN_ID_CAT_CATALOGO
INNER JOIN CIERREN.TCCRXGRAL_TIPO_CAT TCAT ON CAT.FCN_ID_TIPO_CAT = TCAT.FCN_ID_TIPO_CAT
INNER JOIN cierren.tccrxgral_tipo_subcta SUB ON  SUB.FCN_ID_TIPO_SUBCTA=MSUB.FCN_ID_TIPO_SUBCTA
WHERE  CMOV.FFB_VIGENCIA = 1
AND    MSUB.FRB_VIGENCIA = 1
AND    MSUB.FCN_ID_SUBPROCESO =#sr_subproceso#
AND    TCAT.FCN_ID_TIPO_CAT = 25
AND    TCAT.FCB_VIGENCIA = 1
AND    CAT.FCB_VIGENCIA = 1
AND    MSUB.FCN_ID_TIPO_SUBCTA IN (15,18,16,17)
)M
ON A.FTN_SUBPROCESO=M.FCN_ID_SUBPROCESO
AND A.TIPO_MOV=M.TIPO_MOV
AND A.FCN_ID_TIPO_SUBCTA=M.FCN_ID_TIPO_SUBCTA
LEFT OUTER JOIN 
( SELECT FCN_ID_SALDO_OPERA, FCN_ID_SUBPROCESO
FROM CIERREN.TFAFOGRAL_CONFIG_SUBPROCESO CSUB
WHERE CSUB.FCN_ID_PROCESO = '97'
AND FCN_ID_SUBPROCESO=#sr_subproceso#) CS
ON  A.FTN_SUBPROCESO =CS.FCN_ID_SUBPROCESO



