SELECT
  DER.FTN_NUM_APLI_INTE_VIVI08_SOL ,
  DER.FTC_CURP                     ,
  DER.FTC_CVE_ENTIDAD_REC_MV       ,
  DER.FTC_NOMBRE_BDNSAR            ,
  DER.FTC_CVE_ENTIDAD_EMI_MV       ,
  DER.FTN_VAL_APLI_INTE_08         ,
  DER.FTC_ORIGEN_TRANSF            ,
  DER.FTC_TIPO_REG                 ,
  DER.FTN_CONTA_SERV               ,
  DER.FTC_TIPO_ENTIDAD_EMI_MV      ,
  DER.FTC_TIPO_ENTIDAD_REC_MV      ,
  DER.FTD_FEH_PRESEN               ,
  DER.FTD_FEH_MOVIMIENTO           ,
  DER.FTC_APELLIDO_PATE_BDNSAR     ,
  DER.FTC_APELLIDO_MATE_BDNSAR     ,
  DER.FTC_IDENT_LOTE_SOLI          ,
  DER.FTC_TIPO1                    ,
  DER.FTC_TIPO2                    ,
  DER.FTN_NUM_APLI_INTE_VIVI92_SOL ,
  DER.FTN_VAL_APLI_INTE_92         ,
  DER.FTN_SALDO_TOT_VIVI92         ,
  DER.FTN_IDENTI_MOVTO             ,
  DER.FTN_SALDO_TOT_VIVI08         ,
  DER.FTC_FOLIO                    ,
  DER.FTD_FEH_VALOR_VIVI           ,
  DER.FTC_TIPO_ARCH                ,
  DER.FTD_FEH_CRE                  ,
  DER.FTC_USU_CRE                  ,
  DER.FTD_FEH_ACT                  ,
  DER.FCC_USU_ACT                  ,
  DER.FCN_ID_SUBPROCESO            ,
  DER.FTN_COIN_PROCESAR            ,
  DER.FTN_ID_ARCHIVO               ,  
  DER.FTC_RFC                      ,
  DER.FTN_NUM_CTA_INVDUAL          ,
  DER.FTN_ESTATUS_DIAG             ,
  DER.FTC_ID_DIAGNOSTICO           ,
  DER.FCN_ID_IND_CTA_INDV          ,
  DER.FFN_ID_CONFIG_INDI           , 
  DER.FCC_VALOR_IND                ,
  DER.FTC_VIGENCIA                 ,
  DER.FTN_DETALLE                  ,
  DER.FTD_FEH_REG                  ,
  IZQ.FTC_CORREO_ELEC              , 
  IZQ.FTN_CELULAR                  ,
  IZQ.FTC_NSS_BUC
FROM (
    SELECT
       MCA.FTN_NUM_APLI_INTE_VIVI08_SOL ,
       MCA.FTC_CURP                     ,
       MCA.FTC_CVE_ENTIDAD_REC_MV       ,
       MCA.FTC_NOMBRE_BDNSAR            ,
       MCA.FTC_CVE_ENTIDAD_EMI_MV       ,
       MCA.FTN_VAL_APLI_INTE_08         ,
       MCA.FTC_ORIGEN_TRANSF            ,
       MCA.FTC_TIPO_REG                 ,
       MCA.FTN_CONTA_SERV               ,
       MCA.FTC_TIPO_ENTIDAD_EMI_MV      ,
       MCA.FTC_TIPO_ENTIDAD_REC_MV      ,
       MCA.FTD_FEH_PRESEN               ,
       MCA.FTD_FEH_MOVIMIENTO           ,
       MCA.FTC_APELLIDO_PATE_BDNSAR     ,
       MCA.FTC_APELLIDO_MATE_BDNSAR     ,
       MCA.FTC_IDENT_LOTE_SOLI          ,
       MCA.FTC_TIPO1                    ,
       MCA.FTC_TIPO2                    ,
       MCA.FTN_NUM_APLI_INTE_VIVI92_SOL ,
       MCA.FTN_VAL_APLI_INTE_92         ,
       MCA.FTN_SALDO_TOT_VIVI92         ,
       MCA.FTN_IDENTI_MOVTO             ,
       MCA.FTN_SALDO_TOT_VIVI08         ,
       MCA.FTC_FOLIO                    ,
       MCA.FTD_FEH_VALOR_VIVI           ,
       MCA.FTC_TIPO_ARCH                ,
       MCA.FTD_FEH_CRE                  ,
       MCA.FTC_USU_CRE                  ,
       MCA.FTD_FEH_ACT                  ,
       MCA.FCC_USU_ACT                  ,
       MCA.FCN_ID_SUBPROCESO            ,
       MCA.FTN_COIN_PROCESAR            ,
       MCA.FTN_ID_ARCHIVO               ,  
       MCA.FTC_RFC                      ,
       MCA.FTN_NUM_CTA_INVDUAL          ,
       MCA.FTN_ESTATUS_DIAG             ,
       MCA.FTC_ID_DIAGNOSTICO           ,
       VIV.FCN_ID_IND_CTA_INDV          ,
       VIV.FFN_ID_CONFIG_INDI           , 
       VIV.FCC_VALOR_IND                ,
       VIV.FTC_VIGENCIA                 ,
       VIV.FTN_DETALLE                  ,
       VIV.FTD_FEH_REG
    FROM #DELTA_VAL_IDENT# MCA
    LEFT JOIN #DELTA_VIV# VIV
      ON MCA.FTN_NUM_CTA_INVDUAL = VIV.FCN_ID_IND_CTA_INDV
) DER
LEFT JOIN 
(  SELECT 
      FTC_CORREO_ELEC, FTN_CELULAR, FTC_NSS_BUC, FTC_CURP
    FROM #DELTA_BUC#
) IZQ
ON  DER.FTC_CURP = IZQ.FTC_CURP
ORDER BY DER.FTC_CURP, DER.FTN_CONTA_SERV
