SELECT 
  FTC_TIPO_REG                 ,
  FTN_CONTA_SERV               ,
  FTC_TIPO_ENTIDAD_EMI_MV      ,
  FTC_CVE_ENTIDAD_EMI_MV       ,
  FTC_TIPO_ENTIDAD_REC_MV      ,
  FTC_CVE_ENTIDAD_REC_MV       ,
  FTC_ORIGEN_TRANSF            ,
  FTD_FEH_PRESEN               ,
  FTD_FEH_MOVIMIENTO           ,
  FTC_CURP                     ,
  FTC_NSS                      ,
  FTC_RFC                      ,
  FTC_APELLIDO_PATE_BDNSAR     ,
  FTC_APELLIDO_MATE_BDNSAR     ,
  FTC_NOMBRE_BDNSAR            ,
  FTC_IDENT_LOTE_SOLI          ,
  FTC_TIPO1                    ,
  FTC_TIPO2                    ,
  FTN_NUM_APLI_INTE_VIVI92_SOL ,
  FTN_VAL_APLI_INTE_92         ,
  FTN_SALDO_TOT_VIVI92         ,
  FTN_IDENTI_MOVTO             ,
  FTN_NUM_APLI_INTE_VIVI08_SOL ,
  FTN_VAL_APLI_INTE_08         ,
  FTN_SALDO_TOT_VIVI08         ,
  FTN_NUM_CTA_INVDUAL          ,
  FTC_FOLIO                    ,
  FTD_FEH_VALOR_VIVI           ,
  FTC_ESTATUS                  ,
  FTC_TIPO_ARCH                ,
  FTD_FEH_CRE                  ,
  FTC_USU_CRE                  ,
  FCN_ID_SUBPROCESO            ,
  FTN_MOTIVO_RECHAZO           ,
  FTC_CORREO_ELEC              , 
  FTC_CELULAR  
FROM(
    SELECT
      FTN_NUM_APLI_INTE_VIVI08_SOL ,
      FTC_CURP                     ,
      FTC_CVE_ENTIDAD_REC_MV       ,
      FTC_NOMBRE_BDNSAR            ,
      FTC_CVE_ENTIDAD_EMI_MV       ,
      FTN_VAL_APLI_INTE_08         ,
      FTC_ORIGEN_TRANSF            ,
      FTC_TIPO_REG                 ,
      FTN_CONTA_SERV               ,
      FTC_TIPO_ENTIDAD_EMI_MV      ,
      FTC_TIPO_ENTIDAD_REC_MV      ,
      FTD_FEH_PRESEN               ,
      FTD_FEH_MOVIMIENTO           ,
      FTC_NSS_BUC AS FTC_NSS       ,
      FTC_RFC                      ,
      FTC_APELLIDO_PATE_BDNSAR     ,
      FTC_APELLIDO_MATE_BDNSAR     ,
      FTC_IDENT_LOTE_SOLI          ,
      FTC_TIPO1                    ,
      FTC_TIPO2                    ,
      FTN_NUM_APLI_INTE_VIVI92_SOL ,
      FTN_VAL_APLI_INTE_92         ,
      FTN_SALDO_TOT_VIVI92         ,
      FTN_IDENTI_MOVTO             ,
      FTN_SALDO_TOT_VIVI08         ,
      FTC_FOLIO                    ,
      FTD_FEH_VALOR_VIVI           ,
      FTC_TIPO_ARCH                ,
      to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_CRE ,
      'DATABRICKS' AS FTC_USU_CRE                  ,
      FCN_ID_SUBPROCESO            ,
      FTN_COIN_PROCESAR            ,
      FTN_ID_ARCHIVO               ,  
      FTN_NUM_CTA_INVDUAL          ,
      FTN_ESTATUS_DIAG             ,
      FTC_ID_DIAGNOSTICO           ,
      FTC_CORREO_ELEC              , 
      FTN_CELULAR AS FTC_CELULAR   ,
      FCN_ID_IND_CTA_INDV          ,
      FFN_ID_CONFIG_INDI           , 
      FCC_VALOR_IND                ,
      FTC_VIGENCIA                 ,
      FTN_DETALLE                  ,
      FTD_FEH_REG                  ,
      CASE
         WHEN FTN_ESTATUS_DIAG = 0 THEN 0
         ELSE 1 END AS FTC_ESTATUS ,
      CASE
         WHEN FTN_ESTATUS_DIAG = 0 THEN FTC_ID_DIAGNOSTICO
         ELSE NULL END AS FTN_MOTIVO_RECHAZO ,
    	ROW_NUMBER() OVER (PARTITION BY FTC_CURP, FTN_NUM_CTA_INVDUAL, FTN_CONTA_SERV 
                         ORDER BY FTC_CURP ASC, FTN_NUM_CTA_INVDUAL ASC, FTN_CONTA_SERV ASC) AS rn
    FROM #DELTA_VIV_DUP# 
) 
WHERE rn = 1