WITH BD_100_MARCA_INFO
AS(
SELECT
1 AS BANDERA
,FTC_CURP
,FTC_NSS_INFONA
,Trim(FTC_RFC_INFONA) AS FTC_RFC_INFONA
,FTC_APELLIDO_PATER_INFONA
,FTC_APELLIDO_MATER_INFONA
,FTC_NOMBRE_INFONA
,FTC_NSS_AFORE
,Trim(FTC_RFC_AFORE) AS FTC_RFC_AFORE
,FTC_APELLIDO_PATER_AFORE
,FTC_APELLIDO_MATER_AFORE
,FTC_NOMBRE_AFORE
,FTC_NOMBRE_IMSS
,FTN_NUM_CRED_INFONA
,FTD_FEH_PRESEN
,CASE WHEN FTN_CTA_AFORE IS NULL THEN 0 ELSE FTN_CTA_AFORE 
 END FTN_NUM_CTA_INVDUAL
,FTC_FOLIO_BITACORA
FROM
PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
WHERE FTC_FOLIO_BITACORA = '#SR_FOLIO#'
AND FTC_ESTA_REGI = 1
AND FTN_ID_SUBP = #SR_SUBPROCESO#
),
BD_400_SUF_SALDOS 
AS (
SELECT
CASE WHEN  FTN_NUM_CTA_INVDUAL IS NULL THEN 0 ELSE FTN_NUM_CTA_INVDUAL 
END FTN_NUM_CTA_INVDUAL 
,FTN_SDO_AIVS
,FTN_MONTO_PESOS 
FROM PROCESOS.TTSISGRAL_SUF_SALDOS
WHERE 1=1 
AND FTC_FOLIO_BITACORA = '#SR_FOLIO#'
AND FTN_ID_SUBP = #SR_SUBPROCESO#
),
SF_200_CONSECUTIVO AS
(
 SELECT
 '#SR_FOLIO#' AS FTC_FOLIO_BITACORA,
  CASE WHEN PROCESOS IS NULL THEN '1' ELSE LPAD(PROCESOS,3,'0') END AS PROCESOS
  FROM
  (
  SELECT
SUM(Reg) PROCESOS
FROM
(
 SELECT 
    COUNT(DISTINCT(FTC_FOLIO_BITACORA)) Reg
   ,FTC_FOLIO_BITACORA
 FROM 
 PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
 WHERE FTD_FEH_CARGA = TO_DATE(SYSDATE, 'DD/MM/YY')
 GROUP BY FTC_FOLIO_BITACORA))
 ),
 DB_750_CONSECUTIVO AS
(
 SELECT 
 LA.FTN_ID_ARCHIVO
,AF.FTC_FOLIO AS FOLIO_BITACORA
,Trim(SUBSTR(FTC_LINEA,28,3)) ConsecutivoLote
FROM CIERREN.TRAFOGRAL_ARCHIVO_FOLIO AF 
INNER JOIN
CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO LA 
      ON AF.FTN_ID_ARCHIVO = LA.FTN_ID_ARCHIVO
  AND AF.FTC_FOLIO = '#SR_FOLIO#'
  AND SUBSTR(LA.FTC_LINEA,1,2) = '01'
),
FECHA_PRESENTACION AS
(
SELECT
BANDERA,
 TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS DIA_HABIL
FROM (
    select 1 AS BANDERA,FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES       = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),6,2)
        AND FTN_ANIO        = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1  
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 12
GROUP BY BANDERA
),
TF_200_CAMPOS AS
(
SELECT
CAST(ROWNUM AS INT)AS CONTADOR_SERVICIO
,F.DIA_HABIL AS FECHA_PRESENTACION
,BD_100.FTC_CURP
,BD_100.FTC_NSS_INFONA
,BD_100.FTC_RFC_INFONA
,BD_100.FTC_APELLIDO_PATER_INFONA
,BD_100.FTC_APELLIDO_MATER_INFONA
,BD_100.FTC_NOMBRE_INFONA
,BD_100.FTC_NSS_AFORE
,BD_100.FTC_RFC_AFORE
,BD_100.FTC_APELLIDO_PATER_AFORE
,BD_100.FTC_APELLIDO_MATER_AFORE
,BD_100.FTC_NOMBRE_AFORE
,BD_100.FTC_NOMBRE_IMSS
,BD_100.FTN_NUM_CRED_INFONA
,BD_100.FTD_FEH_PRESEN
,BD_100.FTN_NUM_CTA_INVDUAL
,BD_100.FTC_FOLIO_BITACORA
,BD_400.FTN_SDO_AIVS
,BD_400.FTN_MONTO_PESOS
,SF_200.PROCESOS 
,DB_750.ConsecutivoLote
FROM BD_100_MARCA_INFO BD_100
LEFT JOIN BD_400_SUF_SALDOS BD_400 ON BD_100.FTN_NUM_CTA_INVDUAL =  BD_400.FTN_NUM_CTA_INVDUAL
INNER JOIN  SF_200_CONSECUTIVO SF_200 ON BD_100.FTC_FOLIO_BITACORA = SF_200.FTC_FOLIO_BITACORA
INNER JOIN  DB_750_CONSECUTIVO DB_750 ON BD_100.FTC_FOLIO_BITACORA = DB_750.FOLIO_BITACORA
INNER JOIN FECHA_PRESENTACION F ON BD_100.BANDERA = F.BANDERA
)
SELECT * FROM TF_200_CAMPOS