WITH BD_100_MARCA_INFO
AS(
SELECT
1 AS BANDERA
,DESM.FTC_CURP
,DESM.FTC_NSS_INFONA
,DESM.FTC_RFC_INFONA
,DESM.FTC_APELLIDO_PATER_INFONA
,DESM.FTC_APELLIDO_MATER_INFONA
,DESM.FTC_NOMBRE_INFONA
,DESM.FTC_NSS_AFORE
,DESM.FTC_RFC_AFORE
,DESM.FTC_APELLIDO_PATER_AFORE
,DESM.FTC_APELLIDO_MATER_AFORE
,DESM.FTC_NOMBRE_AFORE
,DESM.FTC_NOMBRE_IMSS
,DESM.FTN_NUM_CRED_INFONA
,DESM.FTD_FEH_PRESEN
,DESM.FTC_FOLIO_BITACORA
,CAT_MNI.TMN_CVE_ITGY
,to_char(DESM.FTN_MOTI_RECH) FTN_MOTI_RECH
FROM
PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO DESM
INNER JOIN
(
SELECT 
 TMC_DESC_ITGY
--,MNI.TMN_CVE_NCI 
,CASE 
 WHEN FCN_ID_TIPO_CAT = 223 THEN TO_NUMBER(FCC_VALOR) 
 WHEN FCN_ID_TIPO_CAT = 20 THEN TO_NUMBER(FCN_ID_CAT_CATALOGO)  
 WHEN FCN_ID_TIPO_CAT = 291 THEN TO_NUMBER(FCC_VALOR) 
 WHEN FCN_ID_TIPO_CAT=3  THEN FCN_ID_CAT_CATALOGO
 END TMN_CVE_NCI 
,Trim(MNI.TMN_CVE_ITGY) AS TMN_CVE_ITGY
FROM
CIERREN.TMSISGRAL_MAP_NCI_ITGY MNI INNER JOIN
CIERREN.TCCRXGRAL_CAT_CATALOGO CC
ON MNI.TMN_CVE_NCI = CC.FCN_ID_CAT_CATALOGO
WHERE TMC_USO = 'MOTIVO DE RECHAZO PARA PROCESAR DE SOLICITUD DE MARCA 43 BIS'
AND CC.FCN_ID_TIPO_CAT IN (20,223,291,3)
) CAT_MNI ON TO_CHAR(DESM.FTN_MOTI_RECH) = CAT_MNI.TMN_CVE_NCI
WHERE DESM.FTC_FOLIO_BITACORA = '#SR_FOLIO#' --- Campo Parametrizado '#SR_FOLIO#'
AND DESM.FTC_ESTA_REGI = 0
AND DESM.FTN_ID_SUBP = #SR_SUBPROCESO#  ---Campo Parametrizado #SR_SUBPROCESO#
),
SF_200_CONSECUTIVO AS
(
 SELECT
 '#SR_FOLIO#' AS FTC_FOLIO_BITACORA, --'#SR_FOLIO#'
  CASE WHEN PROCESOS IS NULL THEN '1' ELSE LPAD(PROCESOS,3,'0') END AS PROCESOS
  FROM
  (
  SELECT
SUM(Reg) PROCESOS
FROM
(
 SELECT 
    COUNT(DISTINCT(FTC_FOLIO_BITACORA)) Reg
   ,FTC_FOLIO_BITACORA
 FROM 
 PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO
 WHERE FTD_FEH_CARGA = TO_DATE(SYSDATE, 'DD/MM/YY')
 GROUP BY FTC_FOLIO_BITACORA))
 ),
 DB_750_CONSECUTIVO AS
(
 SELECT 
 LA.FTN_ID_ARCHIVO
,AF.FTC_FOLIO AS FOLIO_BITACORA
,Trim(SUBSTR(FTC_LINEA,28,3)) ConsecutivoLote
FROM CIERREN.TRAFOGRAL_ARCHIVO_FOLIO AF 
INNER JOIN
CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO LA 
      ON AF.FTN_ID_ARCHIVO = LA.FTN_ID_ARCHIVO
  AND AF.FTC_FOLIO = '#SR_FOLIO#'  --- Campo Parametrizado '#SR_FOLIO#'
  AND SUBSTR(LA.FTC_LINEA,1,2) = '01'
),
FECHA_PRESENTACION AS
(
SELECT
BANDERA,
 TO_CHAR(MAX(FTN_ANIO))||LPAD(TO_CHAR(MAX(FTN_MES)),2,'0')||TO_CHAR(MAX(FTN_DIA)) AS DIA_HABIL
FROM (
    select 1 AS BANDERA,FTN_ANIO,FTN_MES,FTN_DIA,FTN_DIA_HABIL,FTC_DIA_NOMBRE
        from PROCESOS.TTAFOGRAL_CALENDARIO
        WHERE FTN_MES       = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),6,2)
        AND FTN_ANIO        = SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD'),1,4)
        AND FTN_DIA_HABIL   = 1  
    ORDER BY FTN_ANIO,FTN_MES,FTN_DIA
)where  ROWNUM <= 12
GROUP BY BANDERA
),
TF_200_CAMPOS AS
(
SELECT
SF_200.FTC_FOLIO_BITACORA
,SF_200.PROCESOS 
,CAST(ROWNUM AS INT) AS CONTADOR_SERVICIO
,F.DIA_HABIL AS FECHA_PRESENTACION
,BD_100.FTC_CURP
,BD_100.FTC_NSS_INFONA
,BD_100.FTC_RFC_INFONA
,BD_100.FTC_APELLIDO_PATER_INFONA
,BD_100.FTC_APELLIDO_MATER_INFONA
,BD_100.FTC_NOMBRE_INFONA
,BD_100.FTC_NSS_AFORE
,BD_100.FTC_RFC_AFORE
,BD_100.FTC_APELLIDO_PATER_AFORE
,BD_100.FTC_APELLIDO_MATER_AFORE
,BD_100.FTC_NOMBRE_AFORE
,BD_100.FTC_NOMBRE_IMSS
,BD_100.FTN_NUM_CRED_INFONA
,BD_100.FTD_FEH_PRESEN
,BD_100.FTN_MOTI_RECH
,BD_100.TMN_CVE_ITGY
,DB_750.FTN_ID_ARCHIVO
,DB_750.ConsecutivoLote
FROM BD_100_MARCA_INFO BD_100
INNER JOIN  SF_200_CONSECUTIVO SF_200 ON BD_100.FTC_FOLIO_BITACORA = SF_200.FTC_FOLIO_BITACORA
INNER JOIN  DB_750_CONSECUTIVO DB_750 ON BD_100.FTC_FOLIO_BITACORA = DB_750.FOLIO_BITACORA
INNER JOIN FECHA_PRESENTACION F ON BD_100.BANDERA = F.BANDERA
)
SELECT * FROM TF_200_CAMPOS