SELECT
'09' AS TIPO_REGISTRO,
LPAD((TOTAL_REGISTRO:: STRING),9,'0') AS TOTAL_REGISTRO,
RPAD(' ',30,' ') AS FILLER,
CONCAT(LPAD(substr((FTN_SDO_AIVS:: STRING),1,charindex('.',(FTN_SDO_AIVS:: STRING))-1),12,'0')
,RPAD(substr((FTN_SDO_AIVS:: STRING),charindex('.',(FTN_SDO_AIVS:: STRING))+1,6),6,'0')) AS FTN_SDO_AIVS,
CONCAT(LPAD(substr((FTN_MONTO_PESOS:: STRING),1,charindex('.',(FTN_MONTO_PESOS:: STRING))-1),13,'0')
,RPAD(substr((FTN_MONTO_PESOS:: STRING),charindex('.',(FTN_MONTO_PESOS:: STRING))+1,2),2,'0')) AS FTN_MONTO_PESOS,
RPAD(' ',656,' ') AS FILLER6
FROM
(
SELECT
FTC_FOLIO_BITACORA,
SUM(FTN_SDO_AIVS) AS FTN_SDO_AIVS,
SUM(FTN_MONTO_PESOS) AS FTN_MONTO_PESOS,
SUM(REG) as TOTAL_REGISTRO
FROM
(
SELECT
substr((FTN_NUM_CTA_INVDUAL:: STRING),1,charindex('.',(FTN_NUM_CTA_INVDUAL:: STRING))-1) AS FTN_NUM_CTA_INVDUAL,
FTC_FOLIO_BITACORA,
CASE WHEN FTN_SDO_AIVS IS NULL THEN 0 ELSE CAST(FTN_SDO_AIVS AS DECIMAL(18,6)) END AS FTN_SDO_AIVS,
CASE WHEN FTN_MONTO_PESOS IS NULL THEN 0 ELSE CAST(FTN_MONTO_PESOS AS DECIMAL(18,2)) END AS FTN_MONTO_PESOS,
1 AS REG
FROM #DELTA_SUMARIO_SOLMARC#
--dbx_mit_dev_1udbvf_workspace.default.delta_0399_arc_acep_lin2_tf_200_campos_202507171410392809
)
GROUP BY FTC_FOLIO_BITACORA
)