SELECT
    SUBC.FCN_ID_CAT_SUBCTA,
    SUBC.FCN_ID_GRUPO,
    SUBC.FCN_ID_TIPO_SUBCTA,
    CAT.REGIMEN,
    OSS.FCN_ID_SIEFORE,
    OSS.FTN_NUM_CTA_INVDUAL
FROM
    CIERREN.TTAFOGRAL_OSS OSS
JOIN
    CIERREN.TCCRXGRAL_SIEFORE S
    ON OSS.FCN_ID_SIEFORE = S.FCN_ID_SIEFORE
JOIN
    CIERREN.TCCRXGRAL_TIPO_SUBCTA SUBC
    ON SUBC.FCN_ID_GRUPO = OSS.FCN_ID_GRUPO
JOIN (
    SELECT
        FCN_ID_CAT_CATALOGO AS REGIMEN
    FROM
        CIERREN.TCCRXGRAL_TIPO_CAT TC
    INNER JOIN
        CIERREN.TCCRXGRAL_CAT_CATALOGO CAT
        ON TC.FCN_ID_TIPO_CAT = CAT.FCN_ID_TIPO_CAT
    WHERE
        TC.FCN_ID_TIPO_CAT = 21
        AND TC.FCB_VIGENCIA = 1
        AND CAT.FCB_VIGENCIA = 1
        AND CAT.FCN_ID_CAT_CATALOGO IN (#ID_CAT_CATALOGO_1#, #ID_CAT_CATALOGO_2#)
) CAT
    ON SUBC.FCN_ID_REGIMEN = CAT.REGIMEN
WHERE
    OSS.FTC_ESTATUS = 1
    AND OSS.FTN_PRIORIDAD = 1
    AND EXISTS (
        SELECT
            FTN_NUM_CTA_INVDUAL
        FROM
            CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE CTE
        WHERE
            CTE.FTC_FOLIO = '#SR_FOLIO#'
            AND CTE.FTN_NUM_CTA_INVDUAL = OSS.FTN_NUM_CTA_INVDUAL
    )