WITH CARGA_CLIENTE AS (
  SELECT
      ENCON.FTN_NSS_CURP,
      ENCON.FTC_IDENTIFICADOS,
      ENCON.FTN_NUM_CTA_INVDUAL,
      ENCON.FTN_ID_DIAGNOSTICO,
      ENCON.FTN_ID_SUBP_NO_CONV,
      ENCON.FTC_NOMBRE_BUC,
      ENCON.FTC_AP_PATERNO_BUC,
      ENCON.FTC_AP_MATERNO_BUC,
      ENCON.FTC_RFC_BUC,
      ENCON.FTC_FOLIO,
      ENCON.FTN_ID_ARCHIVO,
      ENCON.FTN_NSS,
      ENCON.FTC_CURP,
      ENCON.FTC_RFC,
      ENCON.FTC_NOMBRE_CTE,
      ENCON.FTC_CLAVE_ENT_RECEP,
      ENCON.FTN_VIGENCIA,
      ENCON.MARC_DUP,
      ENCON.FCN_ID_TIPO_SUBCTA,
      FECHA.FCC_VALOR_IND AS FTD_FECHA_CERTIFICACION,
      NVL2(PENSION.FCC_VALOR_IND, '1', '0') AS FTN_CTE_PENSIONADO
  FROM #CATALOG_SCHEMA#.TEMP_ENCONTRADOS_06_#SR_ID_ARCHIVO# ENCON
  LEFT JOIN #CATALOG_SCHEMA#.TEMP_FECHAAPCTAIND_05_#SR_ID_ARCHIVO# FECHA
         ON ENCON.FTN_NUM_CTA_INVDUAL = FECHA.FTN_NUM_CTA_INVDUAL
  LEFT JOIN #CATALOG_SCHEMA#.TEMP_PENSIONADO_11_#SR_ID_ARCHIVO# PENSION
         ON ENCON.FTN_NUM_CTA_INVDUAL = PENSION.FTN_NUM_CTA_INVDUAL

  UNION ALL

  SELECT
      NOENCON.FTN_NSS_CURP,
      '0' AS FTC_IDENTIFICADOS,
      NOENCON.FTN_NUM_CTA_INVDUAL,
      NOENCON.FTN_ID_DIAGNOSTICO,
      NULL AS FTN_ID_SUBP_NO_CONV,
      NOENCON.FTC_NOMBRE_BUC,
      NOENCON.FTC_AP_PATERNO_BUC,
      NOENCON.FTC_AP_MATERNO_BUC,
      NOENCON.FTC_RFC_BUC,
      NOENCON.FTC_FOLIO,
      NOENCON.FTN_ID_ARCHIVO,
      NOENCON.FTN_NSS,
      NOENCON.FTC_CURP,
      NOENCON.FTC_RFC,
      NOENCON.FTC_NOMBRE_CTE,
      NOENCON.FTC_CLAVE_ENT_RECEP,
      NOENCON.FTN_VIGENCIA,
      NULL AS MARC_DUP,
      NOENCON.FCN_ID_TIPO_SUBCTA,
      NULL AS FTD_FECHA_CERTIFICACION,
      '0' AS FTN_CTE_PENSIONADO
  FROM #CATALOG_SCHEMA#.TEMP_NOENCONTRADOS_#SR_ID_ARCHIVO# NOENCON
),
RANKED AS (
  SELECT
      C.*,
      ROW_NUMBER() OVER (
        PARTITION BY C.FTN_NSS_CURP
        ORDER BY C.FTN_VIGENCIA DESC,
                 C.FTD_FECHA_CERTIFICACION DESC
      ) AS rn
  FROM CARGA_CLIENTE C
)
SELECT
    FTN_NSS_CURP,
    FTC_IDENTIFICADOS,
    FTN_NUM_CTA_INVDUAL,
    FTN_ID_DIAGNOSTICO,
    FTN_ID_SUBP_NO_CONV,
    FTC_NOMBRE_BUC,
    FTC_AP_PATERNO_BUC,
    FTC_AP_MATERNO_BUC,
    FTC_RFC_BUC,
    FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NSS,
    FTC_CURP,
    FTC_RFC,
    FTC_NOMBRE_CTE,
    FTC_CLAVE_ENT_RECEP,
    FTN_VIGENCIA,
    MARC_DUP,
    FCN_ID_TIPO_SUBCTA,
    FTD_FECHA_CERTIFICACION,
    FTN_CTE_PENSIONADO
FROM RANKED
WHERE rn = 1
