SELECT
  A.FTN_ID_ARCHIVO,
  CASE
    WHEN '#VAR_TRAMITE#' = 'IMSS' THEN FTC_CLAVE_ENT_RECEP_IMSS
    ELSE FTC_CLAVE_ENT_RECEP_ISSSTE
  END FTC_CLAVE_ENT_RECEP,
  CASE
    WHEN '#VAR_TRAMITE#' = 'IMSS' THEN FTN_NSS
    ELSE FTC_CURP
  END FTC_NSS_CURP,
  CASE
    WHEN '#VAR_TRAMITE#' = 'IMSS' THEN FTC_RFC_IMSS
    ELSE FTC_RFC_ISSSTE
  END FTC_RFC,
  CASE
    WHEN '#VAR_TRAMITE#' = 'IMSS' THEN FTC_NOMBRE_CTE_IMSS
    ELSE FTC_NOMBRE_CTE_ISSSTE
  END FTC_NOMBRE_CTE,
  B.FTC_FOLIO,
  B.FTN_NSS,
  B.FTC_CURP,
  CASE
    WHEN '#VAR_TRAMITE#' = 'IMSS' THEN FTN_NSS
    ELSE FTC_CURP
  END FTC_CLAVE_TMP,
  to_timestamp(from_utc_timestamp(current_timestamp, 'GMT-6')) FTD_FEH_CRE,
  '#SR_USUARIO#' FTC_USU_CRE
FROM
  #CATALOG_SCHEMA#.TEMP_MAP_IMSS_ISSSTE_#SR_ID_ARCHIVO# A
  INNER JOIN #CATALOG_SCHEMA#.TEMP_UNION_CLIENTE_#SR_ID_ARCHIVO# B
  ON (
    A.FTN_ID_ARCHIVO = B.FTN_ID_ARCHIVO
    AND A.FTN_NO_LINEA = B.FTN_NO_LINEA
  )