WITH UniqueRecords AS (
  SELECT
    CTAS.FTC_FOLIO,
    BUC.#VAR_CURP_NSS# FTN_NSS_CURP,
    BUC.FTN_NUM_CTA_INVDUAL,
    BUC.FTC_RFC FTC_RFC_BUC,
    BUC.FTC_NOMBRE FTC_NOMBRE_BUC,
    BUC.FTC_AP_PATERNO FTC_AP_PATERNO_BUC,
    BUC.FTC_AP_MATERNO FTC_AP_MATERNO_BUC,
    BUC.FTC_BANDERA,
    ROW_NUMBER() OVER (
        PARTITION BY BUC.FTC_NSS, BUC.FTN_NUM_CTA_INVDUAL
        ORDER BY CTAS.FTC_FOLIO
      ) AS rn
  FROM
    CIERREN_ETL.TLSISGRAL_ETL_BUC BUC
      INNER JOIN CIERREN_ETL.TTSISGRAL_ETL_DISPERSION_CTAS CTAS
        ON LTRIM(BUC.#VAR_CURP_NSS#, '0') = LTRIM(CTAS.FTC_NSS_CURP, '0')
  WHERE
    CTAS.FTC_FOLIO = '#SR_FOLIO#'
    AND BUC.FTN_NUM_CTA_INVDUAL NOT LIKE '972%'
)
SELECT
  FTC_FOLIO,
  FTN_NSS_CURP,
  FTN_NUM_CTA_INVDUAL,
  FTC_RFC_BUC,
  FTC_NOMBRE_BUC,
  FTC_AP_PATERNO_BUC,
  FTC_AP_MATERNO_BUC,
  FTC_BANDERA
FROM
  UniqueRecords
WHERE
  rn = 1