SELECT
        AEIM.FTC_FOLIO                     ,
        DISP.FTN_ID_ARCHIVO                ,
        AEIM.FTN_NSS_ARCH AS FTC_CLAVE_TMP,
        AEIM.FTN_NSS_ARCH AS FTN_NSS       ,
        DISP.FTC_CURP                      ,
        AEIM.FTC_RFC_ARCH AS FTC_RFC       ,
        AEIM.FTC_NOMBRE_COMPLETO_ARCH AS FTC_NOMBRE_CTE,
        AEIM.FTC_CLAVE_ENT_RECEP           ,
        0 AS FTN_ESTATUS_DIAG,
        AEIM.FNC_REG_PATRONAL_IMSS
FROM
        CIERREN_ETL.TTSISGRAL_ETL_AEIM AEIM
JOIN
        CIERREN_ETL.TTSISGRAL_ETL_PRE_DISPERSION DISP
ON
        AEIM.FTC_FOLIO    = DISP.FTC_FOLIO
AND     AEIM.FTN_NSS_ARCH = DISP.FTN_NSS
LEFT JOIN
        CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE IDEN
ON
        AEIM.FTN_NSS_ARCH = IDEN.FTN_NSS
AND     AEIM.FTC_FOLIO    = IDEN.FTC_FOLIO
WHERE
        AEIM.FTC_FOLIO = '#SR_FOLIO#'
AND     (
                IDEN.FTN_NSS IS NULL
        OR IDEN.FTN_ESTATUS_DIAG = 0)