SELECT
  A.FTN_ID_ARCHIVO,
  A.FTN_NO_LINEA,
  A.FNN_ID_REFERENCIA,
  A.FTN_NUM_CTA_INVDUAL,
  NVL(B.FCN_ID_SIEFORE, 846) AS FCN_ID_SIEFORE,
  A.FCN_ID_TIPO_SUBCTA,
  A.FTF_MONTO_PESOS,
  A.FTF_MONTO_ACCIONES,
  A.FTC_TABLA_NCI_MOV,
  A.FNN_ID_VIV_GARANTIA,
  A.FFN_ID_CONCEPTO_MOV,
  A.FCN_ID_PROCESO,
  A.FCN_ID_SUBPROCESO,
  A.FTC_FOLIO,
  A.FTN_NSS,
  A.FTC_CURP,
  A.FTC_NOMBRE,
  B.REGIMEN AS FCN_ID_REGIMEN,
  A.FTN_ID_MONTO,
  A.FTN_TIPO_REG,
  A.FLN_ID_LIB_APORT,
  A.FTC_RFC,
  A.FCN_REG_PATRONAL_IMSS
FROM
  #CATALOG#.#SCHEMA#.TEMP_PREDISPERSIONES_#SR_ID_ARCHIVO# A
  LEFT JOIN #CATALOG#.#SCHEMA#.TEMP_NIVEL_SIEFORE_#SR_ID_ARCHIVO# B
  ON A.FCN_ID_TIPO_SUBCTA = B.FCN_ID_TIPO_SUBCTA
  AND A.FTN_NUM_CTA_INVDUAL = B.FTN_NUM_CTA_INVDUAL