SELECT 
  val.FTN_NSS,
  val.FTC_CURP,
  val.FTC_NOMBRE_CTE,
  TO_CHAR(NVL(val.FTN_NUM_CTA_INVDUAL, 0)) AS FTN_NUM_CTA_INVDUAL,
  tcc_diag.FCC_VALOR AS DIAGNOSTICO,
  subp_cat.FCC_VALOR AS FTC_SUBP_NO_VIG,
  TO_CHAR(val.FTD_FECHA_CERTIFICACION, 'DD/MM/YYYY') AS FTD_FECHA_CERTIFICACION
FROM CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE val
LEFT JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO tcc_diag
  ON val.FTC_ID_DIAGNOSTICO = tcc_diag.FCN_ID_CAT_CATALOGO
LEFT JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO subp_cat
  ON subp_cat.FCN_ID_CAT_CATALOGO = val.FTC_ID_SUBP_NO_VIG
  --AND subp_cat.FCB_VIGENCIA = 1
LEFT JOIN CIERREN.TCCRXGRAL_TIPO_CAT subp_tc
  ON subp_tc.FCN_ID_TIPO_CAT = subp_cat.FCN_ID_TIPO_CAT
 -- AND subp_tc.FCB_VIGENCIA = 1
  AND subp_tc.FCN_ID_TIPO_CAT IN (3, 38)
WHERE val.FTC_FOLIO IN ('#sr_folio#')
  AND val.FTN_ESTATUS_DIAG = 0