SELECT
    A.FTC_FOLIO,
    CASE
        WHEN B.FCN_ID_SUBPROCESO IN (120,122,210,105) THEN A.FTC_CURP
        ELSE A.FTN_NSS
    END AS FTN_NSS_CURP,
    A.FCN_ID_TIPO_SUBCTA,
    A.FTN_ID_ARCHIVO,
    A.FTN_NO_LINEA,
    A.FTN_NSS,
    A.FTC_CURP
FROM (
    SELECT
        A.*,
        ROW_NUMBER() OVER (
            PARTITION BY
                CASE
                    WHEN B.FCN_ID_SUBPROCESO IN (120,122,210,105) THEN A.FTC_CURP
                    ELSE A.FTN_NSS
                END
            ORDER BY A.FTN_ID_ARCHIVO, A.FTN_NO_LINEA
        ) AS RN
    FROM
        CIERREN_ETL.TTSISGRAL_ETL_PRE_DISPERSION A
        INNER JOIN CIERREN.TTCRXGRAL_FOLIO B
            ON A.FTC_FOLIO = B.FTC_FOLIO
    WHERE
        A.FTC_FOLIO = '#SR_FOLIO#'
) A
INNER JOIN CIERREN.TTCRXGRAL_FOLIO B
    ON A.FTC_FOLIO = B.FTC_FOLIO
WHERE
    A.RN = 1
