SELECT 
    afo.FCN_ID_IND_CTA_INDV,
    afo.FTN_NUM_CTA_INVDUAL,
    afo.FFN_ID_CONFIG_INDI,
    afo.FCC_VALOR_IND,
    afo.FTC_VIGENCIA,
    afo.FTN_DETALLE
FROM (
    SELECT 
        afo.FCN_ID_IND_CTA_INDV,
        afo.FTN_NUM_CTA_INVDUAL,
        afo.FFN_ID_CONFIG_INDI,
        afo.FCC_VALOR_IND,
        afo.FTC_VIGENCIA,
        afo.FTN_DETALLE,
        CASE 
            WHEN 3 = #p_ind# THEN ind.FTN_NSS
            WHEN 2 = #p_ind# THEN ind.FTC_CURP
            ELSE '0'
        END AS FTC_NSS_CURP
    FROM CIERREN.TTAFOGRAL_IND_CTA_INDV afo
    INNER JOIN CIERREN.TTAFOGRAL_CTA_INVDUAL ind 
        ON afo.FTN_NUM_CTA_INVDUAL = ind.FTN_NUM_CTA_INVDUAL
    WHERE afo.FFN_ID_CONFIG_INDI IN (2, 5, 11)
      AND afo.FTC_VIGENCIA = 1
) AFO
INNER JOIN (
    SELECT DISTINCT FTC_NSS_CURP
    FROM CIERREN_ETL.TTSISGRAL_ETL_DISPERSION_CTAS
    WHERE FTC_FOLIO = '#SR_FOLIO#'
) B 
ON AFO.FTC_NSS_CURP = B.FTC_NSS_CURP