SELECT
  FCN_ID_TIPO_SUBCTA,
  FTC_FOLIO,
  CASE
    WHEN 3 = #p_ind# THEN FTN_NSS ELSE (CASE WHEN 2=#p_ind# THEN FTC_CURP ELSE '0' END) END AS FTN_NSS_CURP
    FROM
      CIERREN_ETL.TTSISGRAL_ETL_PRE_DISPERSION a
    WHERE
      FTC_FOLIO = '#sr_folio#'