MERGE INTO
  CIERREN_ETL.TTSISGRAL_ETL_AEIM ORI
USING (
  SELECT
    FTC_FOLIO,
    FTN_NSS_ARCH,
    FTC_RFC_ARCH,
    FTC_NOMBRE_COMPLETO_ARCH,
    FNC_REG_PATRONAL_IMSS,
    FTN_NUM_CTA_INVDUAL,
    FTN_ESTATUS_REG,
    FTN_MOTIVO,
    FTC_CLAVE_ENT_RECEP,
    FTC_NOMBRE_BUC,
    FTC_AP_PATERNO_BUC,
    FTC_AP_MATERNO_BUC,
    FTC_RFC_BUC
  FROM (
    SELECT
      FTC_FOLIO,
      FTN_NSS_ARCH,
      FTC_RFC_ARCH,
      FTC_NOMBRE_COMPLETO_ARCH,
      FNC_REG_PATRONAL_IMSS,
      FTN_NUM_CTA_INVDUAL,
      FTN_ESTATUS_REG,
      FTN_MOTIVO,
      FTC_CLAVE_ENT_RECEP,
      FTC_NOMBRE_BUC,
      FTC_AP_PATERNO_BUC,
      FTC_AP_MATERNO_BUC,
      FTC_RFC_BUC,
      ROW_NUMBER() OVER (
        PARTITION BY
          FTC_FOLIO,
          FTN_NSS_ARCH,
          FTC_RFC_ARCH,
          FTC_NOMBRE_COMPLETO_ARCH,
          FNC_REG_PATRONAL_IMSS
        ORDER BY
          FTN_ESTATUS_REG DESC
      ) AS rn
    FROM
      CIERREN_DATAUX.TTSISGRAL_ETL_AEIM_AUX WHERE FTC_FOLIO = '#SR_FOLIO#'
  )
  WHERE rn = 1
) AUX
ON (
  ORI.FTC_FOLIO = AUX.FTC_FOLIO AND
  ORI.FTN_NSS_ARCH = AUX.FTN_NSS_ARCH AND
  ORI.FTC_RFC_ARCH = AUX.FTC_RFC_ARCH AND
  ORI.FTC_NOMBRE_COMPLETO_ARCH = AUX.FTC_NOMBRE_COMPLETO_ARCH AND
  ORI.FNC_REG_PATRONAL_IMSS = AUX.FNC_REG_PATRONAL_IMSS
)
WHEN MATCHED THEN UPDATE SET
  ORI.FTN_NUM_CTA_INVDUAL       = AUX.FTN_NUM_CTA_INVDUAL,
  ORI.FTN_ESTATUS_REG           = AUX.FTN_ESTATUS_REG,
  ORI.FTN_MOTIVO                = AUX.FTN_MOTIVO,
  ORI.FTC_CLAVE_ENT_RECEP       = AUX.FTC_CLAVE_ENT_RECEP,
  ORI.FTC_NOMBRE_BUC            = AUX.FTC_NOMBRE_BUC,
  ORI.FTC_AP_PATERNO_BUC        = AUX.FTC_AP_PATERNO_BUC,
  ORI.FTC_AP_MATERNO_BUC        = AUX.FTC_AP_MATERNO_BUC,
  ORI.FTC_RFC_BUC               = AUX.FTC_RFC_BUC