SELECT
  IDC.FTC_FOLIO,
  IDC.FTN_NSS_CURP,
  IDC.FTN_ID_ARCHIVO,
  IDC.FTN_NO_LINEA,
  IDC.FTN_NSS,
  IDC.FTC_CURP,
  NOIDEN.FLAG,
  NOIDEN.FTN_ESTATUS_DIAG
FROM
  #CATALOG_SCHEMA#.TEMP_IDEN_CLIENTE_#SR_ID_ARCHIVO# IDC
  LEFT JOIN #CATALOG_SCHEMA#.TEMP_CLIENTE_NO_IDEN_#SR_ID_ARCHIVO# NOIDEN ON IDC.FTN_NSS_CURP = NOIDEN.FTN_NSS_CURP
WHERE
  NOIDEN.FLAG IS NULL
  OR NOIDEN.FTN_ESTATUS_DIAG = 0