SELECT
  O.FCN_ID_SIEFORE,
  O.FCN_ID_GRUPO,
  O.FTN_NUM_CTA_INVDUAL
FROM
  CIERREN.TTAFOGRAL_OSS O
    JOIN (
      SELECT DISTINCT
        S.FCN_ID_GRUPO
      FROM
        CIERREN.TCCRXGRAL_SIEFORE S
      WHERE
        S.FCC_VIGENCIA = 1
    ) S
      ON O.FCN_ID_GRUPO = S.FCN_ID_GRUPO
      and O.FTC_ESTATUS = 1
      AND O.FTN_PRIORIDAD = 1