SELECT  
     A.FTN_ID_ARCHIVO,  
     A.FTN_NO_LINEA,  
     SUBSTR(A.FTC_LINEA, 172, 3) AS FTC_CLAVE_ENT_RECEP_IMSS,  
     SUBSTR(A.FTC_LINEA, 13, 3) AS FTC_CLAVE_ENT_RECEP_ISSSTE,  
     SUBSTR(A.FTC_LINEA, 24, 13) AS FTC_RFC_IMSS,  
     SUBSTR(A.FTC_LINEA, 129, 13) AS FTC_RFC_ISSSTE,  
     SUBSTR(A.FTC_LINEA, 55, 50) AS FTC_NOMBRE_CTE_IMSS,  
     TRIM(SUBSTR(A.FTC_LINEA, 240, 40)) || ' ' ||  
     TRIM(SUBSTR(A.FTC_LINEA, 160, 40)) || ' ' ||  
     TRIM(SUBSTR(A.FTC_LINEA, 200, 40)) AS FTC_NOMBRE_CTE_ISSSTE  
FROM  
     CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO A  
WHERE  
     A.FTN_ID_ARCHIVO = #SR_ID_ARCHIVO# 