WITH ctas_clientes AS (
  SELECT
      FTC_FOLIO,
      FTN_ID_ARCHIVO,
      FTN_NSS,
      FTC_CURP,
      FTC_RFC,
      FTC_NOMBRE_CTE,
      FTC_CLAVE_ENT_RECEP,
      FTN_NSS_CURP,
      TRIM(FTN_NUM_CTA_INVDUAL)           AS FTN_NUM_CTA_INVDUAL,
      FTN_ID_DIAGNOSTICO,
      FTD_FECHA_CERTIFICACION,
      FTN_ID_SUBP_NO_CONV,
      FTC_IDENTIFICADOS                   AS FTN_ESTATUS_DIAG,
      FTN_CTE_PENSIONADO,
      TRIM(FCN_ID_TIPO_SUBCTA)            AS FCN_ID_TIPO_SUBCTA
  FROM #CATALOG_SCHEMA#.TEMP_IdentificacionClientes_07_#SR_ID_ARCHIVO#
),
siefore_dim AS (  -- una fila por combinación cuenta + tipo subcta
  SELECT DISTINCT
      TRIM(FTN_NUM_CTA_INVDUAL)           AS FTN_NUM_CTA_INVDUAL,
      FCN_ID_TIPO_SUBCTA,
      FCN_ID_GRUPO,
      FCN_ID_SIEFORE
  FROM #CATALOG_SCHEMA#.TEMP_Siefore01_#SR_ID_ARCHIVO#
),
siefore_sum AS (  -- suma por cuenta
  SELECT
      TRIM(FTN_NUM_CTA_INVDUAL)           AS FTN_NUM_CTA_INVDUAL,
      SUM(MARCA)                          AS SINSIEFORE
  FROM #CATALOG_SCHEMA#.TEMP_Siefore01_#SR_ID_ARCHIVO#
  GROUP BY TRIM(FTN_NUM_CTA_INVDUAL)
)
SELECT
    C.FTC_FOLIO,
    C.FTN_ID_ARCHIVO,
    C.FTN_NSS,
    C.FTC_CURP,
    C.FTC_RFC,
    C.FTC_NOMBRE_CTE,
    C.FTC_CLAVE_ENT_RECEP,
    C.FTN_NSS_CURP,
    C.FTN_NUM_CTA_INVDUAL,
    CASE
      WHEN C.FTN_ID_DIAGNOSTICO IS NULL AND NVL(S.SINSIEFORE,0) > 0 THEN 988
      ELSE C.FTN_ID_DIAGNOSTICO
    END                                       AS FTC_ID_DIAGNOSTICO,
    C.FTD_FECHA_CERTIFICACION,
    C.FTN_ID_SUBP_NO_CONV                      AS FTC_ID_SUBP_NO_VIG,
    CASE
      WHEN C.FTN_ESTATUS_DIAG = 0 OR NVL(S.SINSIEFORE,0) > 0 THEN 0
      ELSE C.FTN_ESTATUS_DIAG
    END                                       AS FTN_ESTATUS_DIAG,
    C.FTN_CTE_PENSIONADO,
    D.FCN_ID_TIPO_SUBCTA,
    D.FCN_ID_GRUPO,
    D.FCN_ID_SIEFORE,
    NVL(S.SINSIEFORE,0)                       AS SINSIEFORE
FROM ctas_clientes C
LEFT JOIN siefore_dim D
  ON D.FTN_NUM_CTA_INVDUAL = C.FTN_NUM_CTA_INVDUAL
 AND D.FCN_ID_TIPO_SUBCTA = C.FCN_ID_TIPO_SUBCTA
LEFT JOIN siefore_sum S
  ON S.FTN_NUM_CTA_INVDUAL = C.FTN_NUM_CTA_INVDUAL;
