SELECT
  FTC_FOLIO,
  FTN_NUM_CTA_INVDUAL AS FTN_NUM_CTA_INVDUAL_2,
  FTN_NSS,
  FTC_CURP AS FTC_CURP_2,
  FTN_ESTATUS_DIAG AS FTN_ESTATUS_DIAG_2,
  FTC_ID_DIAGNOSTICO AS FTC_ID_DIAGNOSTICO_2,
  FTC_ID_SUBP_NO_VIG AS FTC_ID_SUBP_NO_VIG_2,
  FTN_CTE_PENSIONADO AS FTN_CTE_PENSIONADO_2,
  FTD_FECHA_CERTIFICACION AS FTD_FECHA_CERTIFICACION_2
FROM
  CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE
WHERE
  FTC_FOLIO = '#SR_FOLIO#'