SELECT
    CAST(FTD_FECHA_CERTIFICACION AS TIMESTAMP) AS FTD_FECHA_CERTIFICACION,
    COALESCE(FTN_NSS_CURP, 0) AS FTC_CLAVE_TMP,
    COALESCE(FTN_NSS_CURP, 0) AS FTC_CLAVE_TMP2,
    FTN_NSS,
    CAST(TRIM(CLI.FTN_NUM_CTA_INVDUAL) AS DECIMAL(10)) AS FTN_NUM_CTA_INVDUAL,
    FTN_ID_SUBP_NO_CONV AS FTC_ID_SUBP_NO_VIG,
    FTN_ID_ARCHIVO,
    FTC_FOLIO,
    FTC_RFC,
    CASE
        WHEN FTN_ID_DIAGNOSTICO IS NULL AND SINSIEFORE > 0 THEN 988
        ELSE FTN_ID_DIAGNOSTICO
    END AS FTC_ID_DIAGNOSTICO,
    FTC_CURP,
    FTC_NOMBRE_CTE,
    CASE
        WHEN SINSIEFORE > 0 THEN 0
        ELSE FTC_IDENTIFICADOS
    END AS FTN_ESTATUS_DIAG,
    FTN_CTE_PENSIONADO,
    CAST(TRIM(CLI.FCN_ID_TIPO_SUBCTA) AS DECIMAL(10)) AS FCN_ID_TIPO_SUBCTA,
    FCN_ID_GRUPO,
    FCN_ID_SIEFORE,
    FTC_NOMBRE_BUC,
    FTC_AP_PATERNO_BUC,
    FTC_AP_MATERNO_BUC,
    FTC_RFC_BUC,
    FTC_CLAVE_ENT_RECEP,
    '0' AS FNC_REG_PATRONAL_IMSS,
    CASE
        WHEN FTC_IDENTIFICADOS = 1 THEN 560
        ELSE 559
    END AS FTN_ESTATUS_REG,
    CASE
        WHEN FTC_IDENTIFICADOS = 1 THEN 821
        ELSE 562
    END AS FTN_MOTIVO
FROM
    #CATALOG_NAME#.#SCHEMA_NAME#.TEMP_IDENTIFICACIONCLIENTES_07_#SR_ID_ARCHIVO# CLI
LEFT JOIN (
  ----------- DS_800_SIEFORE -------------------
    SELECT
        A.FTN_NUM_CTA_INVDUAL,
        A.FCN_ID_TIPO_SUBCTA,
        A.FCN_ID_GRUPO,
        A.FCN_ID_SIEFORE,
        B.SINSIEFORE
    FROM
       #CATALOG_NAME#.#SCHEMA_NAME#.TEMP_SIEFORE01_#SR_ID_ARCHIVO# A
    LEFT JOIN (
      -------- AG_640_SUMMARCA --------------------
        SELECT
            FTN_NUM_CTA_INVDUAL,
            SUM(MARCA) AS SINSIEFORE
        FROM
            #CATALOG_NAME#.#SCHEMA_NAME#.TEMP_SIEFORE01_#SR_ID_ARCHIVO# 
        GROUP BY
            FTN_NUM_CTA_INVDUAL
    ) B ON A.FTN_NUM_CTA_INVDUAL = B.FTN_NUM_CTA_INVDUAL
) SIEFORE ON SIEFORE.FTN_NUM_CTA_INVDUAL = CLI.FTN_NUM_CTA_INVDUAL
AND SIEFORE.FCN_ID_TIPO_SUBCTA = CLI.FCN_ID_TIPO_SUBCTA
ORDER BY
    FTN_NUM_CTA_INVDUAL ASC,
    FCN_ID_TIPO_SUBCTA ASC