----- CONSULTA CON TABLA DELTA ORIGEN-----
SELECT
  a.FTC_FOLIO,
  a.FTC_CLAVE_TMP AS FTN_NSS_ARCH,
  a.FTC_RFC AS FTC_RFC_ARCH,
  a.FTC_NOMBRE_CTE AS FTC_NOMBRE_COMPLETO_ARCH,
  a.FNC_REG_PATRONAL_IMSS,
  a.FTC_CLAVE_TMP,
  b.FTN_NUM_CTA_INVDUAL,
  b.FTN_ESTATUS_REG,
  b.FTN_MOTIVO,
  b.FTC_CLAVE_ENT_RECEP,
  b.FTC_NOMBRE_BUC,
  b.FTC_AP_PATERNO_BUC,
  b.FTC_AP_MATERNO_BUC,
  b.FTC_RFC_BUC
FROM
  #CATALOG_NAME#.#SCHEMA_NAME#.TEMP_DISP_IMSS_ISSSTE_#SR_ID_ARCHIVO# a ---CONTIENE CEROS
  LEFT JOIN #CATALOG_NAME#.#SCHEMA_NAME#.TEMP_CTAS_AEIM_CTE_#SR_ID_ARCHIVO# b -- NO CONTIENE CEROS
  ON a.FTC_FOLIO = b.FTC_FOLIO
  AND regexp_replace(a.FTC_CLAVE_TMP, '^0+', '') = b.FTC_CLAVE_TMP