SELECT
    CASE
        WHEN B.FCN_ID_SUBPROCESO IN (120,122,210,105)
        THEN A.FTC_CURP
        ELSE A.FTN_NSS
    END FTN_NSS_CURP,
    1 FLAG,
    A.FTN_ESTATUS_DIAG
FROM
    CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE A
INNER JOIN
    CIERREN.TTCRXGRAL_FOLIO B
ON A.FTC_FOLIO = B.FTC_FOLIO
WHERE
    A.FTC_FOLIO=  '#SR_FOLIO#'

