WITH IDENT_CTE AS (
  SELECT
    FTC_FOLIO,
    FTN_NSS AS FTN_NSS_2,
    FTN_NUM_CTA_INVDUAL_2,
    FTN_ESTATUS_DIAG_2,
    FTC_CURP_2 AS FTC_CURP,
    FTC_ID_DIAGNOSTICO_2,
    FTC_ID_SUBP_NO_VIG_2,
    FTN_CTE_PENSIONADO_2,
    FTD_FECHA_CERTIFICACION_2,
    1 AS FLAG
  FROM
    #CATALOG_NAME#.#SCHEMA_NAME#.TEMP_VAL_IDENT_CIENTE_01_#SR_ID_ARCHIVO# IDENT
)
SELECT
  CTAS.FTC_FOLIO,
  CTAS.FTN_ID_ARCHIVO,
  CTAS.FTN_NSS,
  CTAS.FTC_CURP,
  CTAS.FTC_NOMBRE_CTE,
  CTAS.FTN_NUM_CTA_INVDUAL,
  CTAS.FTN_ESTATUS_DIAG,
  CTAS.FTC_ID_DIAGNOSTICO,
  CTAS.FTC_ID_SUBP_NO_VIG,
  CTAS.FTD_FECHA_CERTIFICACION,
  CTAS.FTN_CTE_PENSIONADO,
  IDENT_CTE.FTN_NUM_CTA_INVDUAL_2,
  IDENT_CTE.FTN_ESTATUS_DIAG_2,
  IDENT_CTE.FTC_ID_DIAGNOSTICO_2,
  IDENT_CTE.FTC_ID_SUBP_NO_VIG_2,
  IDENT_CTE.FTN_CTE_PENSIONADO_2,
  IDENT_CTE.FTD_FECHA_CERTIFICACION_2,
  IDENT_CTE.FLAG
FROM
  #CATALOG_NAME#.#SCHEMA_NAME#.TEMP_CTAS_VIG_CARGA_#SR_ID_ARCHIVO# CTAS
  LEFT JOIN IDENT_CTE ON CTAS.FTC_FOLIO = IDENT_CTE.FTC_FOLIO
  AND CTAS.FTC_CURP = IDENT_CTE.FTC_CURP