SELECT
  subc.FCN_ID_CAT_SUBCTA,
  subc.FCN_ID_GRUPO,
  subc.FCN_ID_TIPO_SUBCTA
FROM
  CIERREN.TCCRXGRAL_TIPO_SUBCTA subc
    INNER JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO cat
      ON subc.FCN_ID_REGIMEN = cat.FCN_ID_CAT_CATALOGO
    INNER JOIN CIERREN.TCCRXGRAL_TIPO_CAT tc
      ON tc.FCN_ID_TIPO_CAT = cat.FCN_ID_TIPO_CAT
WHERE
  tc.FCN_ID_TIPO_CAT = 21
  AND tc.FCB_VIGENCIA = 1
  AND cat.FCB_VIGENCIA = 1