MERGE INTO
  CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE ori
USING (
  SELECT
    FTC_FOLIO,
    FTN_NSS,
    FTC_CURP,
    FTN_NUM_CTA_INVDUAL,
    FTN_ESTATUS_DIAG,
    FTC_ID_DIAGNOSTICO,
    FTC_ID_SUBP_NO_VIG,
    FTN_CTE_PENSIONADO,
    FTD_FECHA_CERTIFICACION
  FROM
    (
      SELECT
        FTC_FOLIO,
        FTC_NSS AS FTN_NSS,
        FTC_CURP,
        FTN_NUM_CTA_INVDUAL,
        FTN_ESTATUS_DIAG,
        FTN_ID_DIAGNOSTICO AS FTC_ID_DIAGNOSTICO,
        FTN_ID_SUBP_NO_VIG AS FTC_ID_SUBP_NO_VIG,
        FTN_CTE_PENSIONADO,
        FTD_FECHA_CERTIFICACION,
        ROW_NUMBER() OVER (PARTITION BY FTC_FOLIO, FTC_CURP ORDER BY FTC_FOLIO) AS rn
      FROM
        CIERREN_DATAUX.TTSISGRAL_ETL_VAL_IDENT_CTE_AUX
      WHERE
        FTC_FOLIO = '#SR_FOLIO#'
    ) subquery
  WHERE
    rn = 1
) aux
ON
  (
    ori.FTC_FOLIO = aux.FTC_FOLIO
    AND ori.FTC_CURP = aux.FTC_CURP
  )
WHEN MATCHED THEN UPDATE SET
  ori.FTN_NSS = aux.FTN_NSS,
  ori.FTN_NUM_CTA_INVDUAL = aux.FTN_NUM_CTA_INVDUAL,
  ori.FTN_ESTATUS_DIAG = aux.FTN_ESTATUS_DIAG,
  ori.FTC_ID_DIAGNOSTICO = aux.FTC_ID_DIAGNOSTICO,
  ori.FTC_ID_SUBP_NO_VIG = aux.FTC_ID_SUBP_NO_VIG,
  ori.FTN_CTE_PENSIONADO = aux.FTN_CTE_PENSIONADO,
  ori.FTD_FECHA_CERTIFICACION = aux.FTD_FECHA_CERTIFICACION