-- NB_PANCIN_IDC_0900_CIFRAS_CLIENTE_007B_DELTA_INSERT_CIERREN.sql
-- Propósito: Preparar datos para inserción en tabla principal CIERREN
-- Tipo: Delta (Databricks)

SELECT 
    FTC_ID_SUBETAPA,
    FLN_TOTAL_REGISTROS,
    FLN_REG_CUMPLIERON,
    FLN_REG_NO_CUMPLIERON,
    FLC_USU_REG,
    FLC_DETALLE,
    FLC_VALIDACION,
    FLD_FEC_REG,
    FLN_TOTAL_ERRORES,
    FTC_FOLIO
FROM #CATALOG_SCHEMA#.TEMP_CIFRAS_CONTROL_#SR_ID_ARCHIVO#
