-- Unir los dos conjuntos de datos (equivalente a FU_400_UNION_IDENTIFICADOS)
-- En DataStage: Funnel que une CO_110_DIVIDE (vigentes) con FI_300_FILTRO (no vigentes filtrados)
SELECT 
    FTN_NSS_CURP,
    FTN_NUM_CTA_INVDUAL,
    FTC_NOMBRE_BUC,
    FTC_AP_PATERNO_BUC,
    FTC_AP_MATERNO_BUC,
    FTC_RFC_BUC,
    FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NSS,
    FTC_CURP,
    FTC_RFC,
    FTC_NOMBRE_CTE,
    FTC_CLAVE_ENT_RECEP,
    FCC_VALOR_IND,
    FCN_ID_TIPO_SUBCTA
FROM #CATALOG_SCHEMA#.TEMP_VIGENTES_#SR_ID_ARCHIVO#

UNION ALL

SELECT 
    FTN_NSS_CURP,
    FTN_NUM_CTA_INVDUAL,
    FTC_NOMBRE_BUC,
    FTC_AP_PATERNO_BUC,
    FTC_AP_MATERNO_BUC,
    FTC_RFC_BUC,
    FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NSS,
    FTC_CURP,
    FTC_RFC,
    FTC_NOMBRE_CTE,
    FTC_CLAVE_ENT_RECEP,
    FCC_VALOR_IND,
    FCN_ID_TIPO_SUBCTA
FROM #CATALOG_SCHEMA#.TEMP_NO_VIGENTES_FILTRADOS_#SR_ID_ARCHIVO#