-- Unir datos procesados (TF_430) con datos rechazados (CG_310)
-- Equivalente al stage FU_440_UNION_F del job DataStage
-- En DataStage: Funnel que une TF_430_MARCA_1 + CG_310_MARCA_0

SELECT 
    FTN_NSS_CURP,
    FTC_IDENTIFICADOS,
    FTN_NUM_CTA_INVDUAL,
    FTN_ID_DIAGNOSTICO,
    FTN_ID_SUBP_NO_CONV,
    FTC_NOMBRE_BUC,
    FTC_AP_PATERNO_BUC,
    FTC_AP_MATERNO_BUC,
    FTC_RFC_BUC,
    FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NSS,
    FTC_CURP,
    FTC_RFC,
    FTC_NOMBRE_CTE,
    FTC_CLAVE_ENT_RECEP,
    FTN_VIGENCIA,
    FCN_ID_TIPO_SUBCTA
FROM #CATALOG_SCHEMA#.TEMP_PROCESA_IDENTIFICADOS_#SR_ID_ARCHIVO#

UNION ALL

SELECT 
    FTN_NSS_CURP,
    FTC_IDENTIFICADOS,
    FTN_NUM_CTA_INVDUAL,
    FTN_ID_DIAGNOSTICO,
    FTN_ID_SUBP_NO_CONV,
    FTC_NOMBRE_BUC,
    FTC_AP_PATERNO_BUC,
    FTC_AP_MATERNO_BUC,
    FTC_RFC_BUC,
    FTC_FOLIO,
    FTN_ID_ARCHIVO,
    FTN_NSS,
    FTC_CURP,
    FTC_RFC,
    FTC_NOMBRE_CTE,
    FTC_CLAVE_ENT_RECEP,
    FTN_VIGENCIA,
    FCN_ID_TIPO_SUBCTA
FROM #CATALOG_SCHEMA#.TEMP_MARCA_0_#SR_ID_ARCHIVO#
