WITH MARCA_DESMARCA_INFO AS (
    SELECT 
        I.ftc_folio_bitacora,
        I.ftc_esta_regi,
        COUNT(1) AS NUMERO,
        SUM(SS.FTN_SDO_AIVS) AS AIVS,
        SUM(SS.FTN_MONTO_PESOS) AS PESOS
    FROM PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO I
    LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS SS 
        ON I.FTN_CTA_AFORE = SS.FTN_NUM_CTA_INVDUAL 
        AND I.FTC_FOLIO_BITACORA = SS.FTC_FOLIO_BITACORA
        AND I.FTN_CONTA_SERV = SS.FTN_CONTA_SERV
    WHERE I.FTN_ID_SUBP = #SR_SUBPROCESO#
      AND I.FTC_FOLIO_BITACORA = '#SR_FOLIO#'
    GROUP BY 
        I.ftc_folio_bitacora, 
        I.ftc_esta_regi
)
SELECT 
    ftc_folio_bitacora AS FTC_FOLIO,
    SUM(CASE WHEN ftc_esta_regi = 1 THEN NUMERO ELSE 0 END) AS TOTAL_ACEPTADOS,
    SUM(CASE WHEN ftc_esta_regi = 1 THEN PESOS ELSE 0 END) AS PESOS_ACEPTADOS,
    SUM(CASE WHEN ftc_esta_regi = 1 THEN AIVS ELSE 0 END) AS AIVS_ACEPTADOS,
    SUM(CASE WHEN ftc_esta_regi = 0 THEN NUMERO ELSE 0 END) AS TOTAL_RECHAZADOS,
    SUM(CASE WHEN ftc_esta_regi = 0 THEN PESOS ELSE 0 END) AS PESOS_RECHAZADOS,
    SUM(CASE WHEN ftc_esta_regi = 0 THEN AIVS ELSE 0 END) AS AIVS_RECHAZADOS,
    SUM(NUMERO) AS TOTAL_REG,
    CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FLD_FEC_REG
FROM MARCA_DESMARCA_INFO
GROUP BY 
    ftc_folio_bitacora