-- Consulta 1 como subconsulta
    SELECT
     DP.FTC_FOLIO
    ,DP.FCN_ID_SUBPROCESO
    ,DP.FFN_ID_CONCEPTO_MOV
    ,DP.FCN_ID_SIEFORE
    ,SUM(DP.FTN_SDO_ACCIONES) AS FTN_SDO_ACCIONES
    ,SUM(DP.FTN_SDO_PESOS) AS FTN_SDO_PESOS
    ,VA.FTN_VALOR_AIVS
    FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL DEVP
    LEFT JOIN PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL DP 
        ON DEVP.FTC_FOLIO = DP.FTC_FOLIO 
        AND DEVP.FCN_ID_SUBPROCESO = DP.FCN_ID_SUBPROCESO
        AND DEVP.FTN_NUM_CTA_INVDUAL = DP.FTN_NUM_CTA_INVDUAL 
        AND DEVP.FTN_CONSE_REG_LOTE = DP.FTN_CONSE_REG_LOTE  
    LEFT JOIN (
        SELECT DISTINCT 
            FTC_FOLIO,
            FCN_ID_SUBPROCESO, 
            FTN_VALOR_AIVS, 
            FCN_ID_SIEFORE
        FROM PROCESOS.TTCRXGRAL_VAL_SDOS_DPSJL 
        WHERE FFN_ID_CONCEPTO_MOV = 4072
    ) VA ON DEVP.FTC_FOLIO = VA.FTC_FOLIO 
        AND DEVP.FCN_ID_SUBPROCESO = VA.FCN_ID_SUBPROCESO
    WHERE DEVP.FTC_FOLIO = '#SR_FOLIO#'
        AND DEVP.FCN_ID_SUBPROCESO = #SR_SUBPROCESO# 
        AND DEVP.FTC_ESTATUS = '1' 
        AND DP.FFN_ID_CONCEPTO_MOV IS NOT NULL
    GROUP BY  
        DP.FTC_FOLIO,
        DP.FCN_ID_SUBPROCESO,
        DP.FCN_ID_SIEFORE,
        DP.FFN_ID_CONCEPTO_MOV,
        VA.FTN_VALOR_AIVS