SELECT
    C1.`FTC_FOLIO`,
    C1.`FCN_ID_SUBPROCESO`,
    C1.`FFN_ID_CONCEPTO_MOV`,
    C1.`FCN_ID_SIEFORE`,
    C1.`FTN_SDO_ACCIONES`,
    C1.`FTN_SDO_PESOS`,
    C1.`FTN_VALOR_AIVS`,
    O.`FTC_FOLIO` AS rightRec_FTC_FOLIO,
    O.`FCN_ID_SUBPROCESO` AS rightRec_FCN_ID_SUBPROCESO,
    O.`FFN_ID_CONCEPTO_MOV` AS rightRec_FFN_ID_CONCEPTO_MOV,
    O.`MONTOS_RECH`,
    O.`DUMMY`
FROM `#DELTA_VAL_SDOS#` C1
FULL JOIN `#DELTA_900#` O 
    ON C1.`FTC_FOLIO` = O.`FTC_FOLIO`
    AND C1.`FCN_ID_SUBPROCESO` = O.`FCN_ID_SUBPROCESO`
    AND C1.`FFN_ID_CONCEPTO_MOV` = O.`FFN_ID_CONCEPTO_MOV`