SELECT DISTINCT
    C1.FTC_FOLIO,
    #SR_PROCESO# AS FCN_ID_PROCESO,
    C1.FCN_ID_SUBPROCESO,
    C1.ACEPTADOS AS FLN_REG_ACEPTADOS,
    C1.RECHAZADOS AS FLN_REG_RECHAZADOS,
    C1.TOTAL AS FLN_TOTAL_REGISTROS,
    from_utc_timestamp(current_timestamp(), 'America/Mexico_City') AS FLD_FEC_REG,
    '#SR_USUARIO#' AS FLC_USU_REG
FROM
    #DELTA_CONTEOS# C1