SELECT DISTINCT
  CASE WHEN C1.FTC_FOLIO IS NULL OR C1.FTC_FOLIO = '' THEN C1.rightRec_FTC_FOLIO ELSE C1.FTC_FOLIO END AS FTC_FOLIO,
  CASE 
    WHEN C1.FFN_ID_CONCEPTO_MOV = "4072" OR C1.rightRec_FFN_ID_CONCEPTO_MOV = "4072"
      THEN 1002
    WHEN C1.FFN_ID_CONCEPTO_MOV IS NULL
      THEN C1.rightRec_FFN_ID_CONCEPTO_MOV
    ELSE C1.FFN_ID_CONCEPTO_MOV
  END AS FFN_ID_CONCEPTO_IMP,
  C1.FCN_ID_SIEFORE,
  CASE 
    WHEN C1.FFN_ID_CONCEPTO_MOV = "4072" AND (C1.DUMMY = 1 OR C1.DUMMY IS NULL)
        THEN C1.FTN_SDO_PESOS
    WHEN C1.FFN_ID_CONCEPTO_MOV IN ("4063", "4182", "4526","4070", "4527","4183", "4528","4529", "4530","4184")
        THEN NVL(C1.FTN_SDO_PESOS, 0)
    ELSE NULL
  END AS FTN_IMPORTE_ACEP_PESOS,
  CASE 
    WHEN C1.rightRec_FFN_ID_CONCEPTO_MOV = "4072" AND C1.DUMMY = 2
        THEN C1.MONTOS_RECH
    WHEN C1.rightRec_FFN_ID_CONCEPTO_MOV IN ("4063", "4182", "4526","4070", "4527","4183", "4528","4529", "4530","4184")
        THEN NVL(C1.MONTOS_RECH, 0)
    ELSE NULL
  END AS FTN_IMPORTE_RECH_PESOS,
  CASE 
    WHEN C1.FFN_ID_CONCEPTO_MOV = "4072" AND (C1.DUMMY = 1 OR C1.DUMMY IS NULL)
        THEN NVL(C1.FTN_SDO_ACCIONES, 0)
    ELSE 0
  END AS FTN_IMPORTE_ACEP_AIVS,
  CASE 
    WHEN C1.rightRec_FFN_ID_CONCEPTO_MOV = "4072" AND C1.DUMMY = 1
        THEN NVL(C1.MONTOS_RECH, 0)
    ELSE NULL
  END AS FTN_IMPORTE_RECH_AIVS,
  C1.TOTAL AS FTN_NUM_REG,
  C1.RECHAZADOS AS FTN_NUM_REG_RECH,
  CAST(FROM_UTC_TIMESTAMP(current_timestamp, 'America/Mexico_City') AS TIMESTAMP) AS FTD_FEC_REG,
  '#SR_USUARIO#' AS FTC_USU_REG
FROM 
    #DELTA_TRANSFORMADA# C1