SELECT     
      C1.FTC_FOLIO,
      C1.FCN_ID_SUBPROCESO,
      C1.FFN_ID_CONCEPTO_MOV,
      C1.FCN_ID_SIEFORE,
      C1.FTN_SDO_ACCIONES,
      C1.FTN_SDO_PESOS,
      C1.FTN_VALOR_AIVS,
      C1.rightRec_FTC_FOLIO,
      C1.rightRec_FCN_ID_SUBPROCESO,
      C1.rightRec_FFN_ID_CONCEPTO_MOV,
      C1.MONTOS_RECH,
      C1.DUMMY,
      C3.ACEPTADOS,
      C3.RECHAZADOS,
      C3.TOTAL
FROM #DELTA_RECHAZOS# C1
LEFT JOIN #DELTA_PRO_DEV_PAG_SJL# C3
ON C1.FTC_FOLIO = C3.FTC_FOLIO
AND C1.FCN_ID_SUBPROCESO = C3.FCN_ID_SUBPROCESO