SELECT
    FTC_FOLIO_BITACORA AS FTC_FOLIO,
    FCN_ID_SUBPROCESO,
    SUM(ACEPTADOS) AS ACEPTADOS,
    SUM(RECHAZADOS) AS RECHAZADOS,
    SUM(ACEPTADOS)+SUM(RECHAZADOS) AS TOTAL
  FROM (
        SELECT DISTINCT FTC_FOLIO_BITACORA,
                        FCN_ID_SUBPROCESO,
                        CASE WHEN FTC_ESTATUS=1 THEN NUMERO ELSE 0 END ACEPTADOS,
                        CASE WHEN FTC_ESTATUS=0 THEN NUMERO ELSE 0 END RECHAZADOS
          FROM (
                SELECT FTC_FOLIO AS FTC_FOLIO_BITACORA,
                       FCN_ID_SUBPROCESO,
                       FTC_ESTATUS,
                       COUNT(*) OVER (PARTITION BY FTC_ESTATUS) NUMERO
                  FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL
                 WHERE FTC_FOLIO ='#SR_FOLIO#'
                   AND FCN_ID_SUBPROCESO = #SR_SUBPROCESO#
                )
        )
  GROUP BY FTC_FOLIO_BITACORA,FCN_ID_SUBPROCESO