SELECT
  FTN_CONTA_SERV,
  FTN_NUM_CTA_INVDUAL,
  FTC_ESTATUS,
  FTC_FOLIO,
  FTN_IND_SDO_DISP_VIV97 AS Indicador_Saldo_Disp,
  FCN_ID_TIPO_SUBCTA_97 AS FCN_ID_TIPO_SUBCTA,
  FTN_SDO_AIVS,
  FTN_MONTO_PESOS,
  FTN_ID_SUBP,
  1 AS Constante
FROM #DELTA_FL_400_SUBCTA#
WHERE FCN_ID_TIPO_SUBCTA_97 = 18 AND FTN_IND_SDO_DISP_VIV97 = 1
UNION ALL
SELECT
  FTN_CONTA_SERV,
  FTN_NUM_CTA_INVDUAL,
  FTC_ESTATUS,
  FTC_FOLIO,
  FTN_IND_SDO_DISP_92 AS Indicador_Saldo_Disp,
  FCN_ID_TIPO_SUBCTA_92 AS FCN_ID_TIPO_SUBCTA,
  FTN_SDO_AIVS_92 AS FTN_SDO_AIVS,
  FTN_MONTO_PESOS_92 AS FTN_MONTO_PESOS,
  FTN_ID_SUBP,
  1 AS Constante
FROM #DELTA_FL_400_SUBCTA#
WHERE FCN_ID_TIPO_SUBCTA_92 = 17 AND FTN_IND_SDO_DISP_92 = 1
UNION ALL
SELECT
  FTN_CONTA_SERV,
  FTN_NUM_CTA_INVDUAL,
  FTC_ESTATUS,
  FTC_FOLIO,
  FTN_IND_SDO_DISP_VIV97 AS Indicador_Saldo_Disp,
  FCN_ID_TIPO_SUBCTA_97 AS FCN_ID_TIPO_SUBCTA,
  FTN_SDO_AIVS,
  FTN_MONTO_PESOS,
  FTN_ID_SUBP,
  1 AS Constante
FROM #DELTA_FL_400_SUBCTA#
WHERE FTN_IND_SDO_DISP_VIV97 = 0 AND FTN_IND_SDO_DISP_92 = 0

