SELECT
  A.FTN_CONTA_SERV,
  A.FTN_NUM_CTA_INVDUAL,
  A.FTC_TIPO_ARCH,
  A.FTC_ESTATUS,
  A.FTC_FOLIO,
  B.FTN_IND_SDO_DISP_VIV97,
  B.FCN_ID_TIPO_SUBCTA_97,
  B.FTN_SDO_AIVS,
  B.FTN_MONTO_PESOS,
  B.FTN_IND_SDO_DISP_92,
  B.FCN_ID_TIPO_SUBCTA_92,
  B.FTN_SDO_AIVS_92,
  B.FTN_MONTO_PESOS_92,
  B.FTN_ID_SUBP
FROM PROCESOS.TTAFOTRAS_TRANS_FOVISSSTE A
LEFT JOIN PROCESOS.TTSISGRAL_SUF_SALDOS B
  ON A.FTN_NUM_CTA_INVDUAL = B.FTN_NUM_CTA_INVDUAL
  AND A.FTN_CONTA_SERV = B.FTN_CONTA_SERV
  AND B.FTC_FOLIO_BITACORA = '#SR_FOLIO#'
  AND B.FTN_ID_SUBP = #SR_SUBPROCESO#
WHERE A.FTC_FOLIO = '#SR_FOLIO#'
  AND A.FCN_ID_SUBPROCESO = #SR_SUBPROCESO#

