SELECT
  ds600.Indicador_Saldo_Disp,
  ds600.FCN_ID_TIPO_SUBCTA,
  ds600.FTC_TIPO_ARCH,
  ds600.FTC_ESTATUS,
  ds600.FTC_FOLIO,
  SUM(ds600.FTN_SDO_AIVS) AS FTN_IMPORTE_RECH_AIVS_PRO,
  SUM(ds600.FTN_MONTO_PESOS) AS FTN_IMPORTE_RECH_PESOS_PRO,
  SUM(ds600.Constante) AS Constante,
  mov.FRN_ID_MOV_SUBCTA
FROM #DELTA_600_TRANS# ds600
INNER JOIN #DELTA_MOV_SUBCTA# AS mov
  ON ds600.FCN_ID_TIPO_SUBCTA = mov.FCN_ID_TIPO_SUBCTA
GROUP BY
  ds600.Indicador_Saldo_Disp,
  ds600.FCN_ID_TIPO_SUBCTA,
  ds600.FTC_TIPO_ARCH,
  ds600.FTC_ESTATUS,
  ds600.FTC_FOLIO,
  mov.FRN_ID_MOV_SUBCTA
ORDER BY mov.FRN_ID_MOV_SUBCTA ASC