SELECT 
    sub16.FTN_CONTA_SERV,
    sub16.FTN_NUM_CTA_INVDUAL,
    sub16.FTC_TIPO_ARCH,
    sub16.FTC_ESTATUS,
    sub16.FTC_FOLIO,
    sub16.FTN_IND_SDO_DISP_92 AS Indicador_Saldo_Disp,
    sub16.FCN_ID_TIPO_SUBCTA_92 AS FCN_ID_TIPO_SUBCTA,
    sub16.FTN_SDO_AIVS_92 AS FTN_SDO_AIVS,
    sub16.FTN_MONTO_PESOS_92 AS FTN_MONTO_PESOS,
    sub16.FTN_ID_SUBP AS FTN_ID_SUBP,
    1 AS Constante
FROM #DELTA_400_CTA_INDV# sub16
WHERE FCN_ID_TIPO_SUBCTA_92 = 17 AND FTN_IND_SDO_DISP_92 = 1

UNION ALL

SELECT 
    sub15.FTN_CONTA_SERV,
    sub15.FTN_NUM_CTA_INVDUAL,
    sub15.FTC_TIPO_ARCH,
    sub15.FTC_ESTATUS,
    sub15.FTC_FOLIO,
    sub15.FTN_IND_SDO_DISP_VIV97 AS Indicador_Saldo_Disp,
    sub15.FCN_ID_TIPO_SUBCTA_97 AS FCN_ID_TIPO_SUBCTA,
    sub15.FTN_SDO_AIVS AS FTN_SDO_AIVS,
    sub15.FTN_MONTO_PESOS AS FTN_MONTO_PESOS,
    sub15.FTN_ID_SUBP AS FTN_ID_SUBP,
    1 AS Constante
FROM #DELTA_400_CTA_INDV# sub15
WHERE FCN_ID_TIPO_SUBCTA_97= 18 AND FTN_IND_SDO_DISP_VIV97 = 1


