SELECT
    #SR_FOLIO# AS FTC_FOLIO,
    t_cctrl.FRN_ID_MOV_SUBCTA AS FFN_ID_CONCEPTO_IMP,
    81 AS FCN_ID_SIEFORE,
    SUM(CASE WHEN t_cctrl.FTC_ESTATUS = '1' THEN t_cctrl.FTN_MONTO_PESOS_ACEP ELSE 0 END) AS FTN_IMPORTE_ACEP_PESOS,
    SUM(CASE WHEN t_cctrl.FTC_ESTATUS = '0' THEN t_cctrl.FTN_MONTO_PESOS_ACEP ELSE 0 END) AS FTN_IMPORTE_RECH_PESOS,
    SUM(CASE WHEN t_cctrl.FTC_ESTATUS = '1' THEN t_cctrl.FTN_SDO_AIVS_ACEP ELSE 0 END) AS FTN_IMPORTE_ACEP_AIVS,
    SUM(CASE WHEN t_cctrl.FTC_ESTATUS = '0' THEN t_cctrl.FTN_SDO_AIVS_ACEP ELSE 0 END) AS FTN_IMPORTE_RECH_AIVS,
    t_cctrl.CONTEO_TOTAL AS FTN_NUM_REG,
    t_cctrl.CONTEO_RECHAZO AS FTN_NUM_REG_RECH,
    --CAST(FROM_TZ(CAST(current_timestamp AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City' AS TIMESTAMP) AS FTD_FEC_REG,
    from_utc_timestamp(current_timestamp(), 'America/Mexico_City') AS FTD_FEC_REG,
    '#SR_USER#' AS FTC_USU_REG
    --t_cctrl.CONTEO_TOTAL AS CONTEO_TOTAL
    --t_cctrl.CONTEO_RECHAZO AS CONTEO_RECHAZO
FROM #DELTA_200_TI_JOIN# t_cctrl
GROUP BY
    --t_cctrl.FCN_ID_SIEFORE,
    t_cctrl.FRN_ID_MOV_SUBCTA,
    --#SR_FOLIO#,
    --'#SR_USER#',
    t_cctrl.CONTEO_TOTAL,
    t_cctrl.CONTEO_RECHAZO
    -- t_cctrl.FTC_FOLIO,
    -- t_cctrl.FLC_USU_REG,
    -- t_cctrl.FTD_FEC_REG,
    -- t_cctrl.FTN_NUM_REG,
    -- t_cctrl.FTN_NUM_REG_RECH



