MERGE INTO PROCESOS.TTCRXGRAL_TRANS_INFONA TGT
USING (
    SELECT DISTINCT
        FTC_NSS_TRABA_AFORE
        ,FTC_FOLIO_BITACORA
        ,FTC_CODIGO_RES_OPER
        ,FTC_INDI_DIFE_VIVI92
        ,FTC_INDI_DIFE_VIVI97
        ,FTC_DIAG_PROCESO
        ,FTC_TIPO_ARCH
        ,FTC_ESTATUS_REGISTRO
        ,FTD_FEH_ACTUA_ESTATUS
        ,FTN_MOTIVO_RECHAZO
        ,FTD_FEH_ACT
        ,FCC_USU_ACT
        ,FTN_INTER_SALDO_VIVI97_ULT
        ,FTN_INTER_SALDO_VIVI92
        ,FTN_CONTA_SERV
    FROM CIERREN_DATAUX.TTCRXGRAL_TRANS_INFONA_AUX
    WHERE FTC_FOLIO_BITACORA = '#sr_folio#'
) SRC
ON (
    TGT.FTC_NSS_TRABA_AFORE = SRC.FTC_NSS_TRABA_AFORE
    AND TGT.FTC_FOLIO_BITACORA = SRC.FTC_FOLIO_BITACORA
    AND TGT.FTN_CONTA_SERV = SRC.FTN_CONTA_SERV
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTC_CODIGO_RES_OPER = SRC.FTC_CODIGO_RES_OPER
        ,TGT.FTC_INDI_DIFE_VIVI92 = SRC.FTC_INDI_DIFE_VIVI92
        ,TGT.FTC_INDI_DIFE_VIVI97 = SRC.FTC_INDI_DIFE_VIVI97
        ,TGT.FTC_DIAG_PROCESO = SRC.FTC_DIAG_PROCESO
        ,TGT.FTC_TIPO_ARCH = SRC.FTC_TIPO_ARCH
        ,TGT.FTC_ESTATUS_REGISTRO = SRC.FTC_ESTATUS_REGISTRO
        ,TGT.FTD_FEH_ACTUA_ESTATUS = SRC.FTD_FEH_ACTUA_ESTATUS
        ,TGT.FTN_MOTIVO_RECHAZO = SRC.FTN_MOTIVO_RECHAZO
        ,TGT.FTD_FEH_ACT = SRC.FTD_FEH_ACT
        ,TGT.FCC_USU_ACT = SRC.FCC_USU_ACT
        ,TGT.FTN_INTER_SALDO_VIVI97_ULT = SRC.FTN_INTER_SALDO_VIVI97_ULT
        ,TGT.FTN_INTER_SALDO_VIVI92 = SRC.FTN_INTER_SALDO_VIVI92