MERGE INTO CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_INFONAVIT TGT
USING (
    SELECT DISTINCT
        FTC_NSS_TRABA_AFORE
        ,FTC_FOLIO_BITACORA
        ,FTN_ID_ARCHIVO
        ,FTC_TIPO_ARCH
        ,FTD_FEH_ACT
        ,FCC_USU_ACT
        ,FTN_COIN_PROCESAR
    FROM CIERREN_DATAUX.TTAFOTRAS_ETL_TRANSF_INFONAVIT_AUX
    WHERE FTC_FOLIO_BITACORA = '#sr_folio#'
) SRC
ON (
    TGT.FTC_NSS_TRABA_AFORE = SRC.FTC_NSS_TRABA_AFORE
    AND TGT.FTC_FOLIO_BITACORA = SRC.FTC_FOLIO_BITACORA
    AND TGT.FTN_ID_ARCHIVO = SRC.FTN_ID_ARCHIVO
    AND TGT.FTC_TIPO_ARCH = SRC.FTC_TIPO_ARCH
)
WHEN MATCHED THEN
    UPDATE SET
        TGT.FTD_FEH_ACT = SRC.FTD_FEH_ACT,
        TGT.FCC_USU_ACT = SRC.FCC_USU_ACT,
        TGT.FTN_COIN_PROCESAR = SRC.FTN_COIN_PROCESAR