--- ORDEN 2 IMPRIME ARCHIVO CSV
WITH ORIG AS(
	SELECT  
		FTC_NSS_TRABA_AFORE
		,FTC_NSS_TRABA_AFORE AS FTC_NSS_AFORE_ORIG
		,FTC_FOLIO_BITACORA AS FTN_FOLIO_BITACORA_ORIG
		,FTN_CONTA_SERV AS FTN_CONTA_SERV_ORIG
		,FTD_FEH_PRESEN_PROC AS FTD_FEH_PRESEN
	FROM 
		PROCESOS.TTCRXGRAL_TRANS_INFONA
	WHERE	
		FTC_FOLIO_BITACORA = '#sr_folio#' --'#p_SR_FOLIO_ORIGINAL#'
		AND	FTC_ESTATUS_REGISTRO = '1' --'#P_SR_ID_EST_REG#'
		AND	FTC_TIPO_ARCH = '01' --'#p_SR_TIPO_ARCH_ORIGINAL#'
)
SELECT
	INF.FTN_ID_ARCHIVO AS ID_ARCHIVO
	,INF.FTD_FEH_CRE AS FECHA_CARGA
	,'02' AS DETALLE
	,FTN_CONTA_SERV AS NO_LINEA
	,INF.FTC_NSS_TRABA_AFORE AS NSS
	,INF.FTC_CURP_TRABA AS CURP
	,CASE WHEN (CASE WHEN ORI.FTC_NSS_AFORE_ORIG IS NULL THEN 0 ELSE 1 END) = 0 
		THEN 'Registro No Coincidentes contra el archivo de Recepcion :' || '#sr_folio#' 
		ELSE 'Registro Coincidentes contra el archivo de Recepcion :' || '#sr_folio#' 
	END
	AS VALIDACION
	,CASE WHEN (CASE WHEN ORI.FTC_NSS_AFORE_ORIG IS NULL THEN 0 ELSE 1 END) = 0 THEN 5 ELSE NULL END AS COD_ERROR
	,CASE WHEN (CASE WHEN ORI.FTC_NSS_AFORE_ORIG IS NULL THEN 0 ELSE 1 END) = 0 THEN 'Registro no coincidente' ELSE '' END AS DESC_ERROR
FROM 
	CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_INFONAVIT INF
LEFT JOIN
ORIG ORI
ON
	ORI.FTC_NSS_TRABA_AFORE = INF.FTC_NSS_TRABA_AFORE
	AND
	ORI.FTN_CONTA_SERV_ORIG = INF.FTN_CONTA_SERV
	AND
	ORI.FTD_FEH_PRESEN = INF.FTD_FEH_PRESEN
WHERE 
	FTN_ID_ARCHIVO = '#sr_id_archivo#' 
	AND FTC_FOLIO_BITACORA = '#sr_folio#' 
	AND FTC_TIPO_ARCH = '#sr_tipo_archivo#' 