SELECT  
	to_number(Trim(SUBSTR(FTC_LINEA,3,10))) FTN_CONTA_SERV,
	Trim(SUBSTR(FTC_LINEA,23,2)) FTC_ORIGEN_TRANSFE,
	TO_DATE(Trim(SUBSTR(FTC_LINEA,25,8)), 'YYYYMMDD') FTD_FEH_PRESEN,
	TO_DATE(Trim(SUBSTR(FTC_LINEA,33,8)), 'YYYYMMDD') FTD_FEH_MOVIMIENTO,
	Trim(SUBSTR(FTC_LINEA,41,18)) FTC_CURP_TRABA,
	Trim(SUBSTR(FTC_LINEA,59,11)) FTC_NSS_TRABA_INFO,
	Trim(SUBSTR(FTC_LINEA,85,13)) FTC_RFC_TRABA_INFO,
	Trim(SUBSTR(FTC_LINEA,98,40)) FTC_APELLIDO_PATE_INFO,
	Trim(SUBSTR(FTC_LINEA,138,40)) FTC_APELLIDO_MATE_INFO,
	Trim(SUBSTR(FTC_LINEA,178,40)) FTC_NOMBRES_INFO,
	Trim(SUBSTR(FTC_LINEA,240,16)) FTC_IDENT_LOTE_SOLI,
	Trim(SUBSTR(FTC_LINEA,271,11)) FTC_NSS_TRABA_AFORE,
	Trim(SUBSTR(FTC_LINEA,282,13)) FTC_RFC_TRABA_AFORE,
	Trim(SUBSTR(FTC_LINEA,325,40)) FTC_APELLIDO_PATE_AFORE,
	Trim(SUBSTR(FTC_LINEA,365,40)) FTC_APELLIDO_MATE_AFORE,
	Trim(SUBSTR(FTC_LINEA,405,40)) FTC_NOMBRE_AFORE,
	Trim(SUBSTR(FTC_LINEA,583,2)) FTC_CODIGO_RES_OPER,
	Trim(SUBSTR(FTC_LINEA,585,15)) FTC_DIAG_PROCESO,
	Trim(SUBSTR(FTC_LINEA,600,50)) FTC_NOMBRE_TRABA_IMSS,
	Trim(SUBSTR(FTC_LINEA,713,6)) FTN_PERIODO_PAGO,
	(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_CARGA,
	'#sr_folio#' AS FTC_FOLIO_BITACORA,
	(Trim(SUBSTR(FTC_LINEA,650,10))) FTC_NUMERO_CRED_INFONA,
	(Trim(SUBSTR(FTC_LINEA,475,15))/ 1000000) FTN_NUM_APLI_INTE_VIVI97_ULT,
	(Trim(SUBSTR(FTC_LINEA,490,15))/ 100) FTN_UTLIMA_APOR_VIVI97,
	'#sr_id_archivo#' AS FTN_ID_ARCHIVO,
	(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_CRE,
	'DATABRICKS' AS FTC_USU_CRE,
	to_timestamp(TO_CHAR(ADD_MONTHS(TRUNC(TO_DATE(Trim(SUBSTR(FTC_LINEA,25,8)),'yyyymmdd'),'MONTH'),1),'YYYYDDMM'), 'yyyyMMdd') AS FTD_FEH_VALOR_VIVI,
	'#sr_subproceso#' AS FTN_ID_SUBP,
	'#sr_tipo_archivo#' AS FTC_TIPO_ARCH,
	(Trim(SUBSTR(FTC_LINEA,660,15))/100) FTN_INTER_SALDO_VIVI97_ULT,
	(Trim(SUBSTR(FTC_LINEA,675,15))/100) FTN_INTER_SALDO_VIVI92,
	(Trim(SUBSTR(FTC_LINEA,550,15))/1000000) FTN_NUM_AIVS_VIVI97_ULT,
	(Trim(SUBSTR(FTC_LINEA,565,15))/100) FTN_SALDO_TOT_VIVI92
FROM   CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO 
WHERE   SUBSTR(FTC_LINEA,1,2) = '02'
AND     FTN_ID_ARCHIVO = '#sr_id_archivo#'







