-- ORDEN 1 ACTUALIZA TABLA PROCESOS.TTCRXGRAL_TRANS_INFONA
--orig_ori
WITH ORIG AS(
	 SELECT  
		 FTC_NSS_TRABA_AFORE
		,FTC_NSS_TRABA_AFORE AS FTC_NSS_AFORE_ORIG
		,FTC_FOLIO_BITACORA AS FTN_FOLIO_BITACORA_ORIG
		,FTN_CONTA_SERV AS FTN_CONTA_SERV_ORIG
		,FTD_FEH_PRESEN_PROC AS FTD_FEH_PRESEN
	FROM 
		PROCESOS.TTCRXGRAL_TRANS_INFONA
	WHERE	
		FTC_FOLIO_BITACORA = '#sr_folio#' --'#p_SR_FOLIO_ORIGINAL#'
		AND	FTC_ESTATUS_REGISTRO= '1' --'#P_SR_ID_EST_REG#'
		AND	FTC_TIPO_ARCH = '01' --'#p_SR_TIPO_ARCH_ORIGINAL#'
)
SELECT
	 INF.FTC_NSS_TRABA_AFORE
	,INF.FTC_FOLIO_BITACORA
	,INF.FTC_CODIGO_RES_OPER
	,INF.FTC_INDI_DIFE_VIVI92
	,INF.FTC_INDI_DIFE_VIVI97
	,INF.FTC_DIAG_PROCESO
	,'#sr_tipo_archivo#' AS FTC_TIPO_ARCH
	,CASE WHEN '#sr_tipo_archivo#' = '09' THEN '0' ELSE '1' END AS FTC_ESTATUS_REGISTRO
	,CURRENT_DATE AS FTD_FEH_ACTUA_ESTATUS
	,CASE WHEN '#sr_tipo_archivo#' = '09' THEN '99' ELSE NULL END AS FTN_MOTIVO_RECHAZO
	,(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_ACT
	,'DATABRICKS' AS FCC_USU_ACT
	,CASE WHEN '#sr_tipo_archivo#' = '06' THEN INF.FTN_INTER_SALDO_VIVI97_ULT ELSE NULL END AS FTN_INTER_SALDO_VIVI97_ULT
	,CASE WHEN '#sr_tipo_archivo#' = '06' THEN INF.FTN_INTER_SALDO_VIVI92 ELSE NULL END AS FTN_INTER_SALDO_VIVI92
	,CASE WHEN ORI.FTN_CONTA_SERV_ORIG IS NULL THEN 0 ELSE ORI.FTN_CONTA_SERV_ORIG END AS FTN_CONTA_SERV
	,INF.FTN_ID_SUBP
FROM 
	CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_INFONAVIT INF
LEFT JOIN
	ORIG ORI
	ON
	ORI.FTC_NSS_TRABA_AFORE = INF.FTC_NSS_TRABA_AFORE
	AND
	ORI.FTN_CONTA_SERV_ORIG = INF.FTN_CONTA_SERV
	AND
	ORI.FTD_FEH_PRESEN = INF.FTD_FEH_PRESEN
WHERE 
	FTN_ID_ARCHIVO = '#sr_id_archivo#' --sr_id_archivo_rechazado
	AND FTC_FOLIO_BITACORA = '#sr_folio#' --sr_folio_rechazado
	AND FTC_TIPO_ARCH = '#sr_tipo_archivo#' --sr_tipo_arch_rechazado
  AND (CASE WHEN ORI.FTC_NSS_AFORE_ORIG IS NULL THEN 0 ELSE 1 END) = 1
