--- ORDEN 0 HACE UPDATE A CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_INFONAVIT
WITH ORIG AS(
	 SELECT  
		 FTC_NSS_TRABA_AFORE
		,FTC_NSS_TRABA_AFORE AS FTC_NSS_AFORE_ORIG
		,FTC_FOLIO_BITACORA AS FTN_FOLIO_BITACORA_ORIG
		,FTN_CONTA_SERV AS FTN_CONTA_SERV_ORIG
		,FTD_FEH_PRESEN_PROC AS FTD_FEH_PRESEN
	FROM 
		PROCESOS.TTCRXGRAL_TRANS_INFONA
	WHERE	
		FTC_FOLIO_BITACORA = '#sr_folio#' --sr_folio_original
		AND	FTC_ESTATUS_REGISTRO= '1' --'#sr_id_est_reg#'
		AND	FTC_TIPO_ARCH = '01' --'#sr_tipo_arch_original#'
)
SELECT
	 INF.FTC_NSS_TRABA_AFORE
  ,INF.FTC_FOLIO_BITACORA
  ,INF.FTN_ID_ARCHIVO
  ,'#sr_tipo_archivo#' AS FTC_TIPO_ARCH --sr_tipo_arch_rechazado
  ,(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_ACT
  ,'DATABRICKS' AS FCC_USU_ACT
  ,CASE WHEN ORI.FTC_NSS_AFORE_ORIG IS NULL THEN 0 ELSE 1 END AS FTN_COIN_PROCESAR
FROM 
	CIERREN_ETL.TTAFOTRAS_ETL_TRANSF_INFONAVIT INF
LEFT JOIN
	ORIG ORI
	ON
	ORI.FTC_NSS_TRABA_AFORE = INF.FTC_NSS_TRABA_AFORE
	AND
	ORI.FTN_CONTA_SERV_ORIG = INF.FTN_CONTA_SERV
	AND
	ORI.FTD_FEH_PRESEN = INF.FTD_FEH_PRESEN
WHERE 
	FTN_ID_ARCHIVO = '#sr_id_archivo#' --sr_id_archivo_rechazado
	AND FTC_FOLIO_BITACORA = '#sr_folio#' --sr_folio_rechazado
	AND FTC_TIPO_ARCH = '#sr_tipo_archivo#' --sr_tipo_arch_rechazado
  --AND (CASE WHEN ORI.FTC_NSS_AFORE_ORIG IS NULL THEN 0 ELSE 1 END) IN (0,1)

