SELECT 
   VI.FTN_NSS,
   VI.FTC_CURP,
   VI.FTC_NOMBRE_CTE AS FTC_NOMBRE,
   VI.FTN_NUM_CTA_INVDUAL,
   DIAG.FCC_VALOR AS FTC_ID_DIAGNOSTICO,
   CONV.FCC_VALOR AS FTC_ID_SUBP_NO_VIG,
   VI.FTD_FECHA_CERTIFICACION
FROM CIERREN_ETL.TTSISGRAL_ETL_VAL_IDENT_CTE VI
LEFT JOIN 
  (
  SELECT 
     FCC_NOM_CAT,
     FCN_ID_CAT_CATALOGO as FTN_ID_DIAGNOSTICO,
     FCC_VALOR
  FROM CIERREN.TCCRXGRAL_TIPO_CAT TC
  JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO CAT 
    ON TC.FCN_ID_TIPO_CAT = CAT.FCN_ID_TIPO_CAT
  WHERE TC.FCN_ID_TIPO_CAT = 20 
    AND TC.FCB_VIGENCIA = 1 
    AND CAT.FCB_VIGENCIA = 1
  ) DIAG
ON  VI.FTC_ID_DIAGNOSTICO = DIAG.FTN_ID_DIAGNOSTICO
LEFT JOIN (
  SELECT 
     TC.FCC_NOM_CAT,
     CAT.FCN_ID_CAT_CATALOGO as FTN_ID_SUBP_NO_CONV,
     CAT.FCC_VALOR
  FROM CIERREN.TCCRXGRAL_TIPO_CAT TC
  JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO CAT 
    ON TC.FCN_ID_TIPO_CAT = CAT.FCN_ID_TIPO_CAT
  WHERE (TC.FCN_ID_TIPO_CAT = 3 OR TC.FCN_ID_TIPO_CAT = 38) 
    AND TC.FCB_VIGENCIA = 1 
    AND CAT.FCB_VIGENCIA = 1
) CONV
ON VI.FTC_ID_SUBP_NO_VIG = CONV.FTN_ID_SUBP_NO_CONV
WHERE VI.FTC_FOLIO = '#SR_FOLIO#'
  AND VI.FTN_ESTATUS_DIAG = 0
