SELECT 
   FCN_ID_IND_CTA_INDV   ,
   FTN_NUM_CTA_INVDUAL   ,
   FFN_ID_CONFIG_INDI    ,
   FCC_VALOR_IND         ,
   FTC_VIGENCIA          ,
   FTN_DETALLE           ,
   FTD_FEH_REG
FROM #DELTA_TABLA_NAME#
WHERE FFN_ID_CONFIG_INDI = '14'