Insert into PROCESOS.TTCRXGRAL_DEV_PSJL_SUMARIZADOS(
  FTC_FOLIO                            ,
  FCN_ID_SUBPROCESO                    ,
  FTN_ID_ARCHIVO                        ,
  FTC_TIPO_ARCH                        ,
  FTD_FEH_CRE_LOTE                     ,
  FTD_FEH_LIM_RES                      ,
  FTN_CONSEC_DIA                       ,
  FTC_TIPO_REG                         ,
  FTC_IDENTI_SERV                      ,
  FTC_ID_PAGO                          ,
  FTN_IMP_SOL_INSTITUTO                ,
  FTD_LIQUIDACION                      ,
  FTN_IMP_APACEP_RCV_DEV_ADM           ,
  FTN_IMP_APEND_RCV_ADM                ,
  FTN_IMP_APRECH_RCV_ADM               ,
  FTN_NUM_APLI_INT_VIV_SOL_INST        ,
  FTN_NUM_APLI_INT_VIV_ACDEV_ADM       ,
  FTN_NUM_APLI_INT_VIV_PEND_ADM        ,
  FTN_NUM_APLI_INT_VIV_RECH_ADM        ,
  FTN_IMP_VIV_ACEP_DEV_ADM             ,
  FTN_IMP_VIV_PEND_DEV_ADM             ,
  FTN_IMP_VIV_RECH_DEV_ADM             ,
  FTC_IND_SIEFORE                      ,
  FTC_TIPO_SIEFORE                     ,
  FTC_RES_OPERACION                    ,
  FTC_DIAGNOSTICO1                     ,
  FTC_DIAGNOSTICO2                     ,
  FTC_DIAGNOSTICO3                     ,
  FTN_NUM_REG_APORT_LOTE               ,
  FTN_NUM_REG_CTAS_PAGAR               ,
  FTD_FEH_CRE                          ,
  FTC_USU_CRE                          ,
  FTN_ESTATUS_REGISTRO
)
SELECT
  #SR_FOLIO# AS FTC_FOLIO              ,
  3832 AS FCN_ID_SUBPROCESO            ,
  #SR_ID_ARCHIVO# AS FTN_ID_ARCHIVO    ,
  FTC_TIPO_ARCH                        ,
  FTD_FEH_CRE_LOTE                     ,
  FTD_FEH_LIM_RES                      ,
  FTN_CONSEC_DIA                       ,
  FTC_TIPO_REG                         ,
  FTC_IDENTI_SERV                      ,
  FTC_ID_PAGO                          ,
  FTN_IMP_SOL_INSTITUTO                ,
  FTD_LIQUIDACION                      ,
  FTN_IMP_APACEP_RCV_DEV_ADM           ,
  FTN_IMP_APEND_RCV_ADM                ,
  FTN_IMP_APRECH_RCV_ADM               ,
  FTN_NUM_APLI_INT_VIV_SOL_INST        ,
  FTN_NUM_APLI_INT_VIV_ACDEV_ADM       ,
  FTN_NUM_APLI_INT_VIV_PEND_ADM        ,
  FTN_NUM_APLI_INT_VIV_RECH_ADM        ,
  FTN_IMP_VIV_ACEP_DEV_ADM             ,
  FTN_IMP_VIV_PEND_DEV_ADM              ,
  FTN_IMP_VIV_RECH_DEV_ADM             ,
  FTC_IND_SIEFORE                      ,
  FTC_TIPO_SIEFORE                     ,
  FTC_RES_OPERACION                    ,
  FTC_DIAGNOSTICO1                     ,
  FTC_DIAGNOSTICO2                     ,
  FTC_DIAGNOSTICO3                     ,
  FTN_NUM_REG_APORT_LOTE               ,
  FTN_NUM_REG_CTAS_PAGAR               ,
  TO_TIMESTAMP_TZ(to_char(SYSTIMESTAMP,'YYYY-MM-DD HH:MI:SS'), 'YYYY-MM-DD HH:MI:SS') AS FTD_FEH_CRE     ,
  'DATABRICS' AS FTC_USU_CRE           ,
  1 AS FTN_ESTATUS_REGISTRO
FROM CIERREN_ETL.TTAFOTRAS_ETL_DEV_PAG_SJL
  
WHERE FTC_FOLIO = '#SR_FOLIO#'
  AND FTN_ID_ARCHIVO = #SR_ID_ARCHIVO#
  AND FTC_TIPO_REG IN ('08', '09')
