SELECT
  VI.FTD_FEH_CRE_LOTE               ,
  VI.FTD_FEH_LIM_RES                ,
  VI.FTC_TIPO_REG                   ,
  VI.FTC_IDENTI_SERV                ,
  VI.FTN_CONSE_REG_LOTE             , 
  VI.FTC_NSS                        ,
  VI.FTC_CLAVE_ENT_ORIG             ,
  VI.FTC_RFC_TRABA                  ,
  VI.FTC_CURP                       ,
  VI.FTC_NOMBRE                     ,
  VI.FTN_PERIODO_PAGO               ,
  VI.FTD_FEH_PAGO                   ,
  VI.FTD_FEH_VALOR_RCV              ,
  VI.FTD_FEH_VALOR_VIV              ,
  VI.FTN_FOLIO_SUA                  ,
  VI.FNC_CVE_ENT_RECEP              ,
  VI.FNC_REG_PATRN_IMSS             ,
  VI.FTN_IMP_RET_DEVOLVER           ,
  VI.FTN_IMP_CES_CUO_PATRON_DEV     ,
  VI.FTN_IMP_CES_CUO_TRABAJ_DEV     , 
  VI.FTN_IMP_CUO_SOCIAL_DEV         ,
  VI.FTN_IMP_ACT_REC_RETIRO_DEV     ,
  VI.FTN_IMP_ACT_REC_CUO_PAT_DEV    ,
  VI.FTN_IMP_ACT_REC_CUO_TRA_DEV    ,
  VI.FTN_IMP_APOR_PAT_VIV_DEV       ,
  VI.FNN_DIAS_COTZDOS_BIM_DEV       ,
  VI.FTN_NUM_APLI_VIV_APOR_PAT_DEV  ,
  VI.FTN_IMP_ACT_RET_REN_CUENTA     ,
  VI.FTN_IMP_ACT_REN_CUE_IND_PAT    ,
  VI.FTN_IMP_ACT_REN_CUE_IND_TRA    ,
  VI.FTD_FEH_ENV_ORG_SOL_PROC       ,
  VI.FTC_DIAG_DEV                   ,
  VI.FTC_MOT_DEV                    ,
  VI.FTC_RES_OPERACION              ,
  VI.FTC_DIAGNOSTICO1               ,
  VI.FTC_DIAGNOSTICO2               ,
  VI.FTC_DIAGNOSTICO3               ,
  VI.FCN_ID_SUBPROCESO              ,
  VI.FTN_ID_ARCHIVO                 ,
  VI.FTD_FEH_CRE                    ,
  VI.FTC_USU_CRE                    ,
  VI.FTC_TIPO_ARCH                  ,
  VI.FTN_CONSEC_DIA                 ,
  VI.FTN_NUM_REG_APORT_LOTE         ,
  VI.FTN_NUM_REG_CTAS_PAGAR         ,
  VI.FTC_ID_PAGO                    ,
  VI.FTN_IMP_SOL_INSTITUTO          ,
  VI.FTD_LIQUIDACION                ,
  VI.FTN_IMP_APACEP_RCV_DEV_ADM     ,
  VI.FTN_IMP_APEND_RCV_ADM          ,
  VI.FTN_IMP_APRECH_RCV_ADM         ,
  VI.FTN_NUM_APLI_INT_VIV_SOL_INST  ,
  VI.FTN_NUM_APLI_INT_VIV_ACDEV_ADM ,
  VI.FTN_NUM_APLI_INT_VIV_PEND_ADM  ,
  VI.FTN_NUM_APLI_INT_VIV_RECH_ADM  ,
  VI.FTN_IMP_VIV_ACEP_DEV_ADM       ,
  VI.FTN_IMP_VIV_PEND_DEV_ADM       ,
  VI.FTN_IMP_VIV_RECH_DEV_ADM       ,
  VI.FTC_IND_SIEFORE                ,
  VI.FTC_TIPO_SIEFORE               ,
  VI.FTC_RFC                        ,
  VI.FTC_CURP_IDC                   ,
  VI.FTN_NUM_CTA_INVDUAL            ,
  VI.FTN_ESTATUS_DIAG               ,
  VI.FTC_ID_DIAGNOSTICO             ,
  BUC.FTC_CORREO_ELEC ,
  BUC.FTN_CELULAR
FROM #DELTA_VAL_IDENT# VI
LEFT JOIN #DELTA_BUC# BUC
  ON VI.FTN_NUM_CTA_INVDUAL = BUC.FTN_NUM_CTA_INVDUAL_BUC
ORDER BY VI.FTC_NSS

