SELECT 
  FTD_FEH_CRE_LOTE               ,
  FTD_FEH_LIM_RES                ,
  FTC_TIPO_REG                   ,
  FTC_IDENTI_SERV                ,
  FTN_CONSE_REG_LOTE             , 
  FTC_NSS                        ,
  FTC_CLAVE_ENT_ORIG             ,
  FTC_RFC_TRABA                  ,
  FTC_CURP                       ,
  FTC_NOMBRE                     ,
  FTN_PERIODO_PAGO               ,
  FTD_FEH_PAGO                   ,
  FTD_FEH_VALOR_RCV              ,
  FTD_FEH_VALOR_VIV              ,
  FTN_FOLIO_SUA                  ,
  FNC_CVE_ENT_RECEP              ,
  FNC_REG_PATRN_IMSS             ,
  FTN_IMP_RET_DEVOLVER           ,
  FTN_IMP_CES_CUO_PATRON_DEV     ,
  FTN_IMP_CES_CUO_TRABAJ_DEV     , 
  FTN_IMP_CUO_SOCIAL_DEV         ,
  FTN_IMP_ACT_REC_RETIRO_DEV     ,
  FTN_IMP_ACT_REC_CUO_PAT_DEV    ,
  FTN_IMP_ACT_REC_CUO_TRA_DEV    ,
  FTN_IMP_APOR_PAT_VIV_DEV       ,
  FNN_DIAS_COTZDOS_BIM_DEV       ,
  FTN_NUM_APLI_VIV_APOR_PAT_DEV  ,
  FTN_IMP_ACT_RET_REN_CUENTA     ,
  FTN_IMP_ACT_REN_CUE_IND_PAT    ,
  FTN_IMP_ACT_REN_CUE_IND_TRA    ,
  FTD_FEH_ENV_ORG_SOL_PROC       ,
  FTC_DIAG_DEV                   ,
  FTC_MOT_DEV                    ,
  FTC_RES_OPERACION              ,
  FTC_DIAGNOSTICO1               ,
  FTC_DIAGNOSTICO2               ,
  FTC_DIAGNOSTICO3               ,
  FTC_FOLIO                      ,
  FTC_ESTATUS                    ,
  FCN_ID_SUBPROCESO              ,
  FTN_ID_ARCHIVO                 ,
  FTC_TIPO_ARCH                  ,
  FCN_ID_MOTIVO_RECHAZO          ,
  FTD_FEH_CRE                    ,
  FTC_USU_CRE                    ,
  FTN_CONSEC_DIA                 ,
  FTN_NUM_CTA_INVDUAL            ,
  FTC_CORREO_ELEC                ,
  FTC_CELULAR                    
FROM(
    SELECT
      FTD_FEH_CRE_LOTE               ,
      FTD_FEH_LIM_RES                ,
      FTC_TIPO_REG                   ,
      FTC_IDENTI_SERV                ,
      FTN_CONSE_REG_LOTE             , 
      FTC_NSS                        ,
      FTC_CLAVE_ENT_ORIG             ,
      FTC_RFC_TRABA                  ,
      FTC_CURP                       ,
      FTC_NOMBRE                     ,
      FTN_PERIODO_PAGO               ,
      FTD_FEH_PAGO                   ,
      FTD_FEH_VALOR_RCV              ,
      FTD_FEH_VALOR_VIV              ,
      FTN_FOLIO_SUA                  ,
      FNC_CVE_ENT_RECEP              ,
      FNC_REG_PATRN_IMSS             ,
      FTN_IMP_RET_DEVOLVER           ,
      FTN_IMP_CES_CUO_PATRON_DEV     ,
      FTN_IMP_CES_CUO_TRABAJ_DEV     , 
      FTN_IMP_CUO_SOCIAL_DEV         ,
      FTN_IMP_ACT_REC_RETIRO_DEV     ,
      FTN_IMP_ACT_REC_CUO_PAT_DEV    ,
      FTN_IMP_ACT_REC_CUO_TRA_DEV    ,
      FTN_IMP_APOR_PAT_VIV_DEV       ,
      FNN_DIAS_COTZDOS_BIM_DEV       ,
      FTN_NUM_APLI_VIV_APOR_PAT_DEV  ,
      FTN_IMP_ACT_RET_REN_CUENTA     ,
      FTN_IMP_ACT_REN_CUE_IND_PAT    ,
      FTN_IMP_ACT_REN_CUE_IND_TRA    ,
      FTD_FEH_ENV_ORG_SOL_PROC       ,
      FTC_DIAG_DEV                   ,
      FTC_MOT_DEV                    ,
      FTC_RES_OPERACION              ,
      FTC_DIAGNOSTICO1               ,
      FTC_DIAGNOSTICO2               ,
      FTC_DIAGNOSTICO3               ,
      FCN_ID_SUBPROCESO              ,
      FTN_ID_ARCHIVO                 ,
      Current_Timestamp AS FTD_FEH_CRE,
      'DATABRICKS' AS FTC_USU_CRE    ,
      FTC_TIPO_ARCH                  ,
      FTN_CONSEC_DIA                 ,
      FTN_NUM_REG_APORT_LOTE         ,
      FTN_NUM_REG_CTAS_PAGAR         ,
      FTC_ID_PAGO                    ,
      FTN_IMP_SOL_INSTITUTO          ,
      FTD_LIQUIDACION                ,
      FTN_IMP_APACEP_RCV_DEV_ADM     ,
      FTN_IMP_APEND_RCV_ADM          ,
      FTN_IMP_APRECH_RCV_ADM         ,
      FTN_NUM_APLI_INT_VIV_SOL_INST  ,
      FTN_NUM_APLI_INT_VIV_ACDEV_ADM ,
      FTN_NUM_APLI_INT_VIV_PEND_ADM  ,
      FTN_NUM_APLI_INT_VIV_RECH_ADM  ,
      FTN_IMP_VIV_ACEP_DEV_ADM       ,
      FTN_IMP_VIV_PEND_DEV_ADM       ,
      FTN_IMP_VIV_RECH_DEV_ADM       ,
      FTC_RFC                        ,
      FTC_CURP_IDC                   ,
      FTN_NUM_CTA_INVDUAL            ,
      FTN_ESTATUS_DIAG               ,
      FTC_ID_DIAGNOSTICO             ,
      FTC_CORREO_ELEC                ,
      FTN_CELULAR AS FTC_CELULAR     ,
      CASE 
        WHEN FTN_ESTATUS_DIAG = 0 
        THEN 0 ELSE 1 
      END AS FTC_ESTATUS            ,
      CASE
        WHEN FTN_ESTATUS_DIAG = 0
        THEN FTC_ID_DIAGNOSTICO ELSE NULL
      END AS FCN_ID_MOTIVO_RECHAZO   ,
      #SR_FOLIO# AS FTC_FOLIO        ,
      1 AS FTN_ESTATUS_REGISTRO      ,
      FTC_TIPO_SIEFORE               ,
      FTC_IND_SIEFORE                ,      
    
	ROW_NUMBER() OVER (PARTITION BY FTN_NUM_CTA_INVDUAL, FTC_NSS, FTN_ESTATUS_DIAG, FTN_CONSE_REG_LOTE 
               ORDER BY FTN_NUM_CTA_INVDUAL ASC, FTC_NSS ASC, FTN_ESTATUS_DIAG ASC, FTN_CONSE_REG_LOTE ASC) AS rn
    FROM #DELTA_VIV_DUP# 
) 
WHERE rn = 1