-- Query para generar INFORMACION SUMARIZADA DE PRE MATRIZ PARA ABONO
-- NO SE USA EL TIPO DE SUBCUENTA
SELECT PMAT.FTC_FOLIO
,PMAT.FTC_FOLIO_REL
,PMAT.FTN_NUM_CTA_INVDUAL 
,PMAT.FTN_ID_PROCESO
,PMAT.FTN_ID_SUBPROCESO
-- ,PMAT.FTN_ID_TIPO_SUBCTA
,PMAT.FTN_ID_TIPO_MONTO       
,SUM(PMAT.FTN_MONTO_PESOS) FTN_MONTO_PESOS 
 FROM CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ  PMAT
 LEFT JOIN  CIERREN.TRAFOGRAL_MOV_SUBCTA  MSUB 
        ON MSUB.FCN_ID_TIPO_SUBCTA=PMAT.FTN_ID_TIPO_SUBCTA  
       --AND MSUB.FCN_ID_SUBPROCESO = 307 
	   AND MSUB.FCN_ID_TIPO_MOV = 180
	   AND MSUB.FCN_ID_SUBPROCESO=PMAT.FTN_ID_SUBPROCESO  
 LEFT JOIN  
   (
    SELECT FTN_NUM_CTA_INVDUAL,FRN_ID_MOV_SUBCTA 
    FROM CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA 
    WHERE (FTC_FOLIO_REL = '#sr_folio#' OR FTC_FOLIO = '#sr_folio#') AND FTB_ESTATUS_MARCA = '1'
    )  MAT 
    ON (MAT.FTN_NUM_CTA_INVDUAL=PMAT.FTN_NUM_CTA_INVDUAL AND MAT.FRN_ID_MOV_SUBCTA = MSUB.FRN_ID_MOV_SUBCTA )
 WHERE (PMAT.FTC_FOLIO_REL = '#sr_folio#' OR PMAT.FTC_FOLIO = '#sr_folio#') AND MAT.FTN_NUM_CTA_INVDUAL IS NULL
 GROUP BY PMAT.FTC_FOLIO
,PMAT.FTC_FOLIO_REL
,PMAT.FTN_NUM_CTA_INVDUAL 
,PMAT.FTN_ID_PROCESO
,PMAT.FTN_ID_SUBPROCESO
-- ,PMAT.FTN_ID_TIPO_SUBCTA
,PMAT.FTN_ID_TIPO_MONTO 

