-- SELECT PARA ARCHIVO CSV DE MATRIZ
SELECT DISTINCT MAT.FTN_NUM_CTA_INVDUAL AS Cuenta,
       BUC.FTC_NSS AS NSS,
       BUC.FTC_CURP AS CURP,
       BUC.FTC_NOMBRE || ' ' || BUC.FTC_AP_PATERNO || ' ' || BUC.FTC_AP_MATERNO AS Nombre_del_trabajador,
       CASE 
           WHEN MAT.FTN_ID_ERROR_VAL = '283' THEN 'SUFICIENCIA DE SALDO'
           ELSE ERR.FCC_VALOR 
       END AS Validación,
       CASE 
           WHEN MAT.FTN_ID_ERROR_VAL = '283' THEN ERR.FCC_VALOR
           ELSE SUB.FCC_VALOR
       END AS Motivo_de_Rechazo,
       MAT.FTD_FECHA_BLOQ AS Fecha_de_bloqueo
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV MAT
LEFT JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC BUC ON BUC.FTN_NUM_CTA_INVDUAL = MAT.FTN_NUM_CTA_INVDUAL
LEFT JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO ERR ON ERR.FCN_ID_CAT_CATALOGO = MAT.FTN_ID_ERROR_VAL
LEFT JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO SUB ON SUB.FCN_ID_CAT_CATALOGO = MAT.FTN_ID_SUBPROC_NO_CONV
WHERE (MAT.FTC_FOLIO_REL = '#SR_FOLIO#' OR MAT.FTC_FOLIO = '#SR_FOLIO#') 
  AND (MAT.FTB_ESTATUS_MARCA = '0' OR MAT.FCN_CONV_INGTY = 0)
