-- Extrae info del sub proceso 354 de la tabla PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO y MATRIZ DE CONVIVENCIA 
SELECT 
A.TOTAL
,B.*
,TO_CHAR(CURRENT_DATE,'YYYYMMDD') FECHA_ENVIO
FROM (
  SELECT 
    COUNT(DISTINCT (FTN_NUM_CTA_INVDUAL)) TOTAL
   ,FTC_FOLIO
  FROM CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA
    WHERE FTC_FOLIO = '#SR_FOLIO#'
    AND FTB_ESTATUS_MARCA = 1
    GROUP BY FTC_FOLIO)   -- SUBQUERY PARA EXTRAER EL TOTAL DE CUENTAS
A LEFT JOIN
(   SELECT            
     MC.FTC_FOLIO
    ,MC.FTN_NUM_CTA_INVDUAL
    ,MC.FTN_ID_MARCA
    ,MD.FTC_NSS_AFORE AS FTC_NSS
    ,MD.FTC_CURP
    ,MD.FTC_TIPO_ARCH
   FROM
    CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA MC INNER JOIN
    PROCESOS.TTCRXGRAL_MARCA_DESMARCA_INFO MD
    ON MC.FTN_NUM_CTA_INVDUAL = MD.FTN_CTA_AFORE
    AND MC.FTC_FOLIO = MD.FTC_FOLIO_BITACORA
    AND MC.FTC_FOLIO = '#SR_FOLIO#'
    AND FTB_ESTATUS_MARCA = 1)B
ON A.FTC_FOLIO = B.FTC_FOLIO