-- Query para generar INFORMACION PARA LA TABLA TTAFOGRAL_RESPUESTA_ITGY 
WITH ED AS 
( 
SELECT 
  COUNT(*) AS CUANTOS 
  FROM #DELTA_TABLA_NAME1# D
  )
SELECT 
    '#SR_FOLIO#' AS FTC_FOLIO
    ,#SR_PROCESO# AS FTN_ID_PROCESO
    ,#SR_SUBPROCESO# AS FTN_ID_SUBPROCESO
    ,CUANTOS AS FTN_REGISTROS_ENVIADOS
    ,0 AS FTN_REGISTROS_RECIBIDOS
    ,3879 AS FTN_ID_ESTATUS
    ,'#SR_USUARIO#' AS FTC_USU_CRE
 FROM ED


