-- Extrae solo los que tienen marca en matriz 
WITH PMT AS (
    SELECT DISTINCT FTN_NUM_CTA_INVDUAL, FTC_FOLIO
    FROM CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ PMT
    WHERE PMT.FTC_FOLIO = '#sr_folio#' OR PMT.FTC_FOLIO_REL = '#sr_folio#'
)
SELECT DISTINCT 
    MAT.FTN_NUM_CTA_INVDUAL,
    FO.FCN_ID_PROCESO FCN_ID_PROCESO_CON,
    FO.FCN_ID_SUBPROCESO FCN_ID_SUBPROCESO_CON,
    SUBC.FCN_ID_TIPO_SUBCTA FCN_ID_TIPO_SUBCTA_CON,
    CCM.FCN_ID_TIPO_MONTO FCN_ID_TIPO_MONTO_CON,
    MAT.FTD_FEH_CRE FTD_FECHA_BLOQ,
    1 B_MATRIZ
FROM CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA MAT
INNER JOIN PMT
    ON MAT.FTN_NUM_CTA_INVDUAL = PMT.FTN_NUM_CTA_INVDUAL
    AND MAT.FTC_FOLIO <> PMT.FTC_FOLIO
INNER JOIN CIERREN.TTCRXGRAL_FOLIO FO 
    ON MAT.FTC_FOLIO = FO.FTC_FOLIO
LEFT JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA SUBC 
    ON FO.FCN_ID_SUBPROCESO = SUBC.FCN_ID_SUBPROCESO 
    AND SUBC.FRN_ID_MOV_SUBCTA = MAT.FRN_ID_MOV_SUBCTA 
    AND SUBC.FRB_VIGENCIA = 1
LEFT JOIN CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CCM 
    ON SUBC.FRN_ID_MOV_SUBCTA = CCM.FRN_ID_MOV_SUBCTA
INNER JOIN CIERREN.TFAFOGRAL_CONFIG_SUBPROCESO SUB 
    ON FO.FCN_ID_SUBPROCESO = SUB.FCN_ID_SUBPROCESO
WHERE MAT.FTB_ESTATUS_MARCA in ('1')