-- Query para generar INFORMACION ABONO para la tabla delta y posterior carga de MATRIZ 
SELECT 
  VM.FTN_ID_MARCA,
  VM.FTC_FOLIO,
  VM.FTC_FOLIO_REL,
  VM.FTN_NUM_CTA_INVDUAL,
  PMAT.FTN_ID_SALDO_OPERA AS FCN_TIPO_SALDO_OPERA,
  VM.FCN_ID_TIPO_MONTO ,
  VM.FTF_MONTO AS FTN_MONTO,
  VM.FTB_ESTATUS_MARCA AS FTC_ESTATUS_MARCA,
  NULL AS FRN_ID_MOV_SUBCTA
 -- NVL(NM.BANDERA_MARCA,1) BANDERA_MARCA
FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV VM
INNER JOIN (
    SELECT DISTINCT 
      FTN_NUM_CTA_INVDUAL,
      FTN_ID_SALDO_OPERA, 
      FTN_ID_SUBPROCESO
    FROM CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ
    WHERE FTC_FOLIO_REL = '#sr_folio#' OR FTC_FOLIO = '#sr_folio#'
) PMAT 
  ON PMAT.FTN_NUM_CTA_INVDUAL = VM.FTN_NUM_CTA_INVDUAL
LEFT JOIN (
    SELECT DISTINCT 
      FTN_NUM_CTA_INVDUAL,
      0 BANDERA_MARCA
    FROM CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV VMAT
    WHERE (VMAT.FTC_FOLIO_REL = '#sr_folio#' OR VMAT.FTC_FOLIO = '#sr_folio#')
      AND FTB_ESTATUS_MARCA = '0'
) NM
  ON VM.FTN_NUM_CTA_INVDUAL = NM.FTN_NUM_CTA_INVDUAL
WHERE 
  (VM.FTC_FOLIO_REL = '#sr_folio#' OR VM.FTC_FOLIO = '#sr_folio#')
  AND VM.FTB_ESTATUS_MARCA = '1'