-- MERGE de VAL_MATRIZ y VAL_MATRIZ_AUX
-- 20251008
MERGE  /*+ PARALLEL(8) */ INTO CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV VM
USING (
	SELECT FTC_FOLIO, 
	FTN_NUM_CTA_INVDUAL, 
	FTN_ID_SUBPROC_NO_CONV, 
	FTN_ID_ERROR_VAL, 
	FCN_CONV_INGTY
	FROM CIERREN_DATAUX.TLSISGRAL_ETL_VAL_MATRIZ_CONV_AUX
	WHERE FTC_FOLIO =  '#SR_FOLIO#') VMAX
ON (VM.FTC_FOLIO = VMAX.FTC_FOLIO
	AND VM.FTN_NUM_CTA_INVDUAL = VMAX.FTN_NUM_CTA_INVDUAL
    )
WHEN MATCHED THEN
	UPDATE  /*+ PARALLEL(8) */ SET
    VM.FTN_ID_SUBPROC_NO_CONV = VMAX.FTN_ID_SUBPROC_NO_CONV,
    VM.FTN_ID_ERROR_VAL = VMAX.FTN_ID_ERROR_VAL,
    VM.FCN_CONV_INGTY = VMAX.FCN_CONV_INGTY,
    VM.FTD_FECHA = SYSDATE

