-- MERGE de VAL_MATRIZ y VAL_MATRIZ_AUX
-- 20251008
MERGE  /*+ PARALLEL(8) */ INTO CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV VM
USING (
	SELECT FTC_FOLIO, 
	FCN_ID_PROCESO, 
	FCN_ID_SUBPROCESO, 
	FTN_NUM_CTA_INVDUAL, 
	FTN_MONTO, 
	FCN_ID_TIPO_SUBCTA, 
	FTC_ESTATUS_MARCA, 
	FCN_ID_TIPO_MONTO, 
	FTD_FECHA, 
	FTN_ID_SUBPROC_NO_CONV, 
	FTN_ID_ERROR_VAL, 
	FTC_FOLIO_REL, 
	FTN_ID_MARCA, 
	FCN_CONV_INGTY, 
	FTD_FECHA_BLOQ
	FROM CIERREN_DATAUX.TLSISGRAL_ETL_VAL_MATRIZ_CONV_AUX
	WHERE FTC_FOLIO =  '#SR_FOLIO#') VMAX
ON (VM.FTC_FOLIO = VMAX.FTC_FOLIO
	AND VM.FCN_ID_PROCESO = VMAX.FCN_ID_PROCESO
	AND VM.FCN_ID_SUBPROCESO = VMAX.FCN_ID_SUBPROCESO
	AND VM.FTN_NUM_CTA_INVDUAL = VMAX.FTN_NUM_CTA_INVDUAL
	AND VM.FCN_ID_TIPO_SUBCTA = VMAX.FCN_ID_TIPO_SUBCTA)
WHEN MATCHED THEN
	UPDATE  /*+ APPEND PARALLEL(8)*/  SET
    VM.FTF_MONTO = VMAX.FTN_MONTO,
    VM.FTB_ESTATUS_MARCA = VMAX.FTC_ESTATUS_MARCA,
    VM.FCN_ID_TIPO_MONTO = VMAX.FCN_ID_TIPO_MONTO,
    VM.FTD_FECHA = SYSDATE,
    VM.FTN_ID_SUBPROC_NO_CONV = VMAX.FTN_ID_SUBPROC_NO_CONV,
    VM.FTN_ID_ERROR_VAL = VMAX.FTN_ID_ERROR_VAL,
    VM.FTC_FOLIO_REL = VMAX.FTC_FOLIO_REL,
    VM.FTN_ID_MARCA = CIERREN.SE_TTAFOGRAL_MARCA_CTA_SUBCTA.nextval, 
    VM.FCN_CONV_INGTY = VMAX.FCN_CONV_INGTY,
    VM.FTD_FECHA_BLOQ = VMAX.FTD_FECHA_BLOQ
WHEN NOT MATCHED THEN 
	INSERT  /*+ APPEND PARALLEL(8)*/ 
    (VM.FTC_FOLIO, 
    VM.FCN_ID_PROCESO, 
    VM.FCN_ID_SUBPROCESO, 
    VM.FTN_NUM_CTA_INVDUAL, 
    VM.FTF_MONTO, 
    VM.FCN_ID_TIPO_SUBCTA, 
    VM.FTB_ESTATUS_MARCA, 
    VM.FCN_ID_TIPO_MONTO, 
    VM.FTD_FECHA, 
    VM.FTN_ID_SUBPROC_NO_CONV, 
    VM.FTN_ID_ERROR_VAL, 
    VM.FTC_FOLIO_REL, 
    VM.FTN_ID_MARCA, 
    VM.FCN_CONV_INGTY, 
    VM.FTD_FECHA_BLOQ)
	VALUES
    (VMAX.FTC_FOLIO,
    VMAX.FCN_ID_PROCESO,
    VMAX.FCN_ID_SUBPROCESO,
    VMAX.FTN_NUM_CTA_INVDUAL,
    VMAX.FTN_MONTO,
    VMAX.FCN_ID_TIPO_SUBCTA,
    VMAX.FTC_ESTATUS_MARCA,
    VMAX.FCN_ID_TIPO_MONTO,
    SYSDATE,
    VMAX.FTN_ID_SUBPROC_NO_CONV,
    VMAX.FTN_ID_ERROR_VAL,
    VMAX.FTC_FOLIO_REL,
    CIERREN.SE_TTAFOGRAL_MARCA_CTA_SUBCTA.nextval,
    VMAX.FCN_CONV_INGTY,
    VMAX.FTD_FECHA_BLOQ)
