-- Query para informacion previa de VAL_MATRIZ  y aplica reglas finales
-- VERIFICAR SI ES UPDATE O INSERT
-- FTC_FOLIO	FCN_ID_PROCESO	FCN_ID_SUBPROCESO	FTN_NUM_CTA_INVDUAL	FTN_MONTO	FCN_ID_TIPO_SUBCTA	FTC_ESTATUS_MARCA	FCN_ID_TIPO_MONTO	FTD_FECHA	FTN_ID_SUBPROC_NO_CONV	FTN_ID_ERROR_VAL	FTC_FOLIO_REL	FTN_ID_MARCA	FCN_CONV_INGTY	FTD_FECHA_BLOQ    
SELECT 
   PRE.FTC_FOLIO            -- LLAVE
  ,PRE.FTN_ID_PROCESO  AS FCN_ID_PROCESO       -- LLAVE
  ,PRE.FTN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO   -- LLAVE
  ,PRE.FTN_NUM_CTA_INVDUAL  -- LLAVE
  ,PRE.FTN_MONTO_PESOS  AS FTN_MONTO
  ,PRE.FTN_ID_TIPO_SUBCTA  AS FCN_ID_TIPO_SUBCTA  -- LLAVE
  -- IF IsNull(LK_JO120_TO_TF130.ESTATUS)  THEN '1' ELSE '0'
  ,CASE WHEN PRE.ESTATUS IS NULL THEN '1' ELSE '0' END AS FTC_ESTATUS_MARCA
  ,PRE.FTN_ID_TIPO_MONTO AS FCN_ID_TIPO_MONTO
  ,'' AS FTD_FECHA  -- MANDAR EL SYS DATE  CurrentTimestamp()
  -- IF IsNull(LK_JO120_TO_TF130.ESTATUS)  THEN  SETNULL() ELSE If LK_JO120_TO_TF130.ESTATUS=283 THEN SETNULL() ELSE LK_JO120_TO_TF130.FCN_ID_SUBPROCESO_CON
  ,CASE  WHEN PRE.ESTATUS IS NULL THEN NULL 
        WHEN PRE.ESTATUS = '283' THEN NULL 
        ELSE PRE.FCN_ID_SUBPROCESO_CON  END AS FTN_ID_SUBPROC_NO_CONV
  ,PRE.ESTATUS AS FTN_ID_ERROR_VAL
  ,PRE.FTC_FOLIO_REL
-- IF IsNull(LK_JO120_TO_TF130.ESTATUS)  THEN '1' ELSE '0'
  ,CASE WHEN PRE.ESTATUS IS NULL THEN '1' ELSE '0' END AS FCN_CONV_INGTY
 -- IF LK_JO120_TO_TF130.ESTATUS = 421 THEN  LK_JO120_TO_TF130.FTD_FECHA_BLOQ ELSE SETNULL()
  ,CASE WHEN PRE.ESTATUS = '421' THEN PRE.FTD_FECHA_BLOQ ELSE NULL END AS FTD_FECHA_BLOQ
 FROM 
(
SELECT  -- une resultados sumarizados de pre matriz con resultados de no convivencia
  PMAT.FTC_FOLIO
  ,PMAT.FTC_FOLIO_REL
  ,PMAT.FTN_ID_TIPO_SUBCTA
  ,PMAT.FTN_NUM_CTA_INVDUAL 
  ,PMAT.FTN_ID_TIPO_MONTO  
  ,PMAT.FTN_ID_PROCESO
  ,PMAT.FTN_ID_SUBPROCESO
  ,PMAT.FTN_MONTO_PESOS 
  ,NCON.FCN_ID_SUBPROCESO_CON
  ,NCON.FCN_ID_TIPO_SUBCTA_CON	
  ,NCON.FCN_ID_TIPO_MONTO_CON
  ,NCON.FTD_FECHA_BLOQ	
  ,NCON.ESTATUS
  ,NCON.MONTO_ACCIONES_BAL	
  ,NCON.MONTO_PESOS_BAL
 FROM #DELTA_TABLA_NAME1#  PMAT 
 LEFT JOIN #DELTA_TABLA_NAME2#  NCON 
  ON PMAT.FTN_NUM_CTA_INVDUAL = NCON.FTN_NUM_CTA_INVDUAL
  AND PMAT.FTN_ID_TIPO_SUBCTA = NCON.FTN_ID_TIPO_SUBCTA
 WHERE (PMAT.FTC_FOLIO_REL = '#sr_folio#' OR PMAT.FTC_FOLIO = '#sr_folio#') 
) PRE 


