-- MERGE de MATRIZ_CONVIVENCIA Y MATRIZ CONVIVENCIA AUX
-- 20251013- 
MERGE /*+ PARALLEL(8) */ INTO CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA M
USING (
	SELECT FTC_FOLIO, 
	FTN_NUM_CTA_INVDUAL, 
	FTC_ESTATUS_MARCA 
	FROM CIERREN_DATAUX.TTAFOGRAL_ETL_MATRIZ_CONVIVENCIA_AUX
	WHERE FTC_FOLIO =  '#SR_FOLIO#') MAUX
ON (M.FTC_FOLIO = MAUX.FTC_FOLIO
	AND M.FTN_NUM_CTA_INVDUAL = MAUX.FTN_NUM_CTA_INVDUAL
    )
WHEN MATCHED THEN
	UPDATE /*+ PARALLEL(8) */ SET
    M.FTB_ESTATUS_MARCA = MAUX.FTC_ESTATUS_MARCA,
		M.FTD_FEH_ACT = SYSDATE,
		M.FCC_USU_ACT = '#SR_USUARIO#'


