-- Query para generar INFORMACION SUMARIZADA DE PRE MATRIZ PARA ABONO
-- NO SE USA EL TIPO DE SUBCUENTA
WITH PM AS (
SELECT PMAT.FTC_FOLIO
,PMAT.FTC_FOLIO_REL
,PMAT.FTN_NUM_CTA_INVDUAL 
,PMAT.FTN_ID_PROCESO
,PMAT.FTN_ID_SUBPROCESO
,0 AS FTN_ID_TIPO_SUBCTA
,PMAT.FTN_ID_TIPO_MONTO       
,PMAT.FTN_MONTO_PESOS 
 FROM CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ  PMAT
 LEFT JOIN  
   (
    SELECT FTN_NUM_CTA_INVDUAL,FRN_ID_MOV_SUBCTA 
    FROM CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA 
    WHERE (FTC_FOLIO_REL = '#sr_folio#' OR FTC_FOLIO = '#sr_folio#') AND FTB_ESTATUS_MARCA = '1'
    )  MAT 
    ON (MAT.FTN_NUM_CTA_INVDUAL=PMAT.FTN_NUM_CTA_INVDUAL )
 WHERE (PMAT.FTC_FOLIO_REL = '#sr_folio#' OR PMAT.FTC_FOLIO = '#sr_folio#')   
  AND MAT.FTN_NUM_CTA_INVDUAL IS NULL
 )
 SELECT 
 PM.FTC_FOLIO
 ,PM.FTC_FOLIO_REL
,PM.FTN_NUM_CTA_INVDUAL 
,PM.FTN_ID_PROCESO
,PM.FTN_ID_SUBPROCESO
,PM.FTN_ID_TIPO_SUBCTA
,PM.FTN_ID_TIPO_MONTO       
,SUM(PM.FTN_MONTO_PESOS) FTN_MONTO_PESOS 
 FROM PM
 GROUP BY 
 PM.FTC_FOLIO
,PM.FTC_FOLIO_REL
,PM.FTN_NUM_CTA_INVDUAL 
,PM.FTN_ID_PROCESO
,PM.FTN_ID_SUBPROCESO
,PM.FTN_ID_TIPO_SUBCTA
,PM.FTN_ID_TIPO_MONTO
