-- Query para generar delta de proceso archivo 64
--  
SELECT  
	TMN_CVE_NCI AS FCN_ID_PROCESO, 
	TMN_CVE_ITGY AS CVE_PROCESO  
FROM CIERREN.TMSISGRAL_MAP_NCI_ITGY
WHERE TMC_USO='PROCESOS'
AND  TMC_VIGENCIA='1'