-- Query para generar INFORMACION para la tabla delta y posterior carga de MATRIZ  
SELECT 
    MAT.FTN_ID_MARCA,
    MAT.FTC_FOLIO,
    MAT.FTC_FOLIO_REL,
    MAT.FTN_NUM_CTA_INVDUAL,
    PMAT.FTN_ID_SALDO_OPERA AS FCN_TIPO_SALDO_OPERA,
    MAT.FCN_ID_TIPO_MONTO,
    MSUB.FRN_ID_MOV_SUBCTA AS FRN_ID_MOV_SUBCTA,
    MAT.FTF_MONTO AS FTN_MONTO,
    MAT.FTB_ESTATUS_MARCA AS FTC_ESTATUS_MARCA
--    NVL(NM.BANDERA_MARCA, 1) AS BANDERA_MARCA
FROM 
    CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV MAT
INNER JOIN 
    (SELECT DISTINCT 
         FTN_NUM_CTA_INVDUAL,
         FTN_ID_SALDO_OPERA,
         FTN_ID_SUBPROCESO
     FROM  
         CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ 
     WHERE 
         FTC_FOLIO_REL = '#sr_folio#' OR FTC_FOLIO = '#sr_folio#') PMAT 
     ON PMAT.FTN_NUM_CTA_INVDUAL = MAT.FTN_NUM_CTA_INVDUAL
INNER JOIN 
    (SELECT  
         FRN_ID_MOV_SUBCTA,
         FCN_ID_TIPO_SUBCTA,
         FCN_ID_SUBPROCESO 
     FROM  
         CIERREN.TRAFOGRAL_MOV_SUBCTA 
     WHERE 
         FCN_ID_SUBPROCESO IN 
             (SELECT DISTINCT FTN_ID_SUBPROCESO 
              FROM CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ
              WHERE FTC_FOLIO_REL = '#sr_folio#' OR FTC_FOLIO = '#sr_folio#') 
         AND FCN_ID_TIPO_MOV = 180) MSUB
     ON MSUB.FCN_ID_TIPO_SUBCTA = MAT.FCN_ID_TIPO_SUBCTA 
     AND MSUB.FCN_ID_SUBPROCESO = PMAT.FTN_ID_SUBPROCESO
LEFT JOIN 
    (SELECT DISTINCT 
         FTN_NUM_CTA_INVDUAL,
         0 AS BANDERA_MARCA 
     FROM 
         CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV MAT
     WHERE 
         (FTC_FOLIO_REL = '#sr_folio#' OR FTC_FOLIO = '#sr_folio#') 
         AND FTB_ESTATUS_MARCA = '0') NM
     ON MAT.FTN_NUM_CTA_INVDUAL = NM.FTN_NUM_CTA_INVDUAL
WHERE 
    (MAT.FTC_FOLIO_REL = '#sr_folio#' OR MAT.FTC_FOLIO = '#sr_folio#') 
    AND FTB_ESTATUS_MARCA = '1'
