-- Query que une las tablas delta de PRE Y MATRIZ con CONFIG CONVIV

SELECT 
        PREYM.FTN_NUM_CTA_INVDUAL
        ,PREYM.FTN_ID_PROCESO     
        ,PREYM.FTN_ID_SUBPROCESO  
        ,PREYM.FTN_ID_SIEFORE     
        ,PREYM.FTN_ID_TIPO_SUBCTA 
        ,PREYM.FTN_ID_TIPO_MONTO  
        ,PREYM.FTN_ID_SALDO_OPERA 
        ,PREYM.FTN_ID_TIPO_MOV    
        ,PREYM.FTN_MONTO_ACCIONES 
        ,PREYM.FTN_MONTO_PESOS 
    --   FTN_NUM_CTA_INVDUAL   
        ,PREYM.FCN_ID_PROCESO_CON    
        ,PREYM.FCN_ID_SUBPROCESO_CON 
        ,PREYM.FCN_ID_TIPO_SUBCTA_CON
        ,PREYM.FCN_ID_TIPO_MONTO_CON 
        ,PREYM.FTD_FECHA_BLOQ        
        ,PREYM.B_MATRIZ  
        ,CC.B_CONVIV
        ,CC.FFB_CONVIVENCIA               
    from #DELTA_TABLA_NAME1#  PREYM
    LEFT JOIN #DELTA_TABLA_NAME2# CC    
ON  PREYM.FCN_ID_PROCESO_CON = CC.FCN_ID_PROCESO_CON
AND PREYM.FCN_ID_SUBPROCESO_CON = CC.FCN_ID_SUBPROCESO_CON
AND PREYM.FTN_ID_SUBPROCESO = CC.FTN_ID_SUBPROCESO