-- MERGE de MATRIZ_CONVIVENCIA Y MATRIZ CONVIVENCIA AUX
-- 20251008- hints
MERGE /*+ PARALLEL(8) */ INTO CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA MC
USING (
	SELECT
	FTN_ID_MARCA, 
	FTC_FOLIO, 
	FTC_FOLIO_REL, 
	FTN_NUM_CTA_INVDUAL, 
	FCN_TIPO_SALDO_OPERA, 
	FCN_ID_TIPO_MONTO, 
	FRN_ID_MOV_SUBCTA, 
	FTN_MONTO, 
	FTC_ESTATUS_MARCA, 
	FTD_FEH_CRE, 
	FCC_USU_CRE 
	FROM CIERREN_DATAUX.TTAFOGRAL_ETL_MATRIZ_CONVIVENCIA_AUX
	WHERE FTC_FOLIO =  '#SR_FOLIO#' OR FTC_FOLIO_REL =  '#SR_FOLIO#' ) MCAUX 
ON (
		MC.FTC_FOLIO = MCAUX.FTC_FOLIO
	AND MC.FTN_NUM_CTA_INVDUAL = MCAUX.FTN_NUM_CTA_INVDUAL
	AND MC.FRN_ID_MOV_SUBCTA = MCAUX.FRN_ID_MOV_SUBCTA)
WHEN MATCHED THEN
	UPDATE  /*+ APPEND PARALLEL(8)*/ SET
	 MC.FTN_ID_MARCA=MCAUX.FTN_ID_MARCA
	,MC.FTC_FOLIO_REL=MCAUX.FTC_FOLIO_REL
	,MC.TCN_TIPO_SALDO_OPERA=MCAUX.FCN_TIPO_SALDO_OPERA
	,MC.FCN_ID_TIPO_MONTO=MCAUX.FCN_ID_TIPO_MONTO
	,MC.FTF_MONTO=MCAUX.FTN_MONTO
	,MC.FTB_ESTATUS_MARCA=MCAUX.FTC_ESTATUS_MARCA
	,MC.FTD_FEH_ACT= SYSDATE
	,MC.FCC_USU_ACT= 'DATABRICKS' 
WHEN NOT MATCHED THEN 
	INSERT  /*+ APPEND PARALLEL(8)*/
    (
    MC.FTN_ID_MARCA 
    ,MC.FTC_FOLIO 
    ,MC.FTC_FOLIO_REL 
    ,MC.FTN_NUM_CTA_INVDUAL 
    ,MC.TCN_TIPO_SALDO_OPERA 
    ,MC.FCN_ID_TIPO_MONTO 
    ,MC.FRN_ID_MOV_SUBCTA
    ,MC.FTF_MONTO 
    ,MC.FTB_ESTATUS_MARCA 
    ,MC.FTD_FEH_CRE 
    ,MC.FCC_USU_CRE 
    )
    VALUES
    (
     MCAUX.FTN_ID_MARCA
    ,MCAUX.FTC_FOLIO
    ,MCAUX.FTC_FOLIO_REL
    ,MCAUX.FTN_NUM_CTA_INVDUAL
    ,MCAUX.FCN_TIPO_SALDO_OPERA
    ,MCAUX.FCN_ID_TIPO_MONTO
    ,MCAUX.FRN_ID_MOV_SUBCTA
    ,MCAUX.FTN_MONTO
    ,MCAUX.FTC_ESTATUS_MARCA
    ,SYSDATE
    ,'DATABRICKS'  
    )
