-- Query para generar archivo 64 desde tabla delta 
WITH RDK AS 
( 
SELECT 
  D.FTC_FOLIO,
  D.FTN_NUM_CTA_INVDUAL,
  NVL2(D.FTN_NUM_CTA_INVDUAL,LPAD(D.FTN_NUM_CTA_INVDUAL,10,'0'),'0000000000') AS FTN_NUM_CTA_INVDUAL_FMT, --10 POSICIONES
  LPAD(D.FTN_NUM_CTA_INVDUAL,10,'0') AS FTN_NUM_CTA_INVDUAL3,
  D.FCN_ID_PROCESO,
  D.FCN_ID_SUBPROCESO,
  D.FTC_NSS,
  NVL2(D.FTC_NSS,LPAD(D.FTC_NSS,11,'0'),'00000000000') AS FTC_NSS_FMT,  -- 11 POSICIONES
  D.FTC_CURP,
  NVL2(D.FTC_CURP,LPAD(D.FTC_CURP,18,'0'),'000000000000000000') AS FTC_CURP_FMT,  -- 18 POSICIONES
  SUB.TMN_CVE_ITGY,
  NVL2(SUB.TMN_CVE_ITGY,LPAD(SUB.TMN_CVE_ITGY,4,'0'),'0000') AS TMN_CVE_ITGY_FMT,  -- 18 POSICIONES TIPOSUB
  PRO.CVE_PROCESO,
  NVL2(PRO.CVE_PROCESO,LPAD(PRO.CVE_PROCESO,4,'0'),'0000') AS CVE_PROCESO_FMT,   -- 4 POSICIONES TIPO PRO
  LPAD(' ',79)   AS FILLER
  FROM #DELTA_TABLA_NAME1# D
  LEFT JOIN #DELTA_TABLA_SUB# SUB  
    ON D.FCN_ID_SUBPROCESO = SUB.FCN_ID_SUBPROCESO
  LEFT JOIN #DELTA_TABLA_PRO# PRO
    ON D.FCN_ID_PROCESO = PRO.FCN_ID_PROCESO 
  ORDER BY  D.FTN_NUM_CTA_INVDUAL
)
SELECT 
2 AS POSICION,
CONCAT(
  '02' 
  ,RDK.FTN_NUM_CTA_INVDUAL_FMT
  ,RDK.CVE_PROCESO_FMT
  ,RDK.TMN_CVE_ITGY_FMT
  ,RDK.FTC_NSS_FMT
  ,RDK.FTC_CURP_FMT
  ,RDK.FILLER
  ) AS DETALLE
 -- ,RDK.* 
  FROM RDK
-- WHERE RN = 1


