-- Query para generar delta para PROCESO Y SUBPROCESO para archivo 64
--  Version de PROCESOS.TCSISGRAL_MAP_NCI_ITGY_PROCESO reemplazando CIERREN.TMSISGRAL_MAP_NCI_ITGY
SELECT 
   MNCI.FCN_CVE_PROC_NCI
  ,MNCI.FCN_CVE_SUBPROC_NCI
  ,MNCI.FCN_CVE_PROC_ITGY
  ,MNCI.FCN_CVE_SUBPROC_ITGY
  ,MNCI.FCC_DESC_SUBPROC_ITGY
  ,MNCI.FCC_DESC_SUBPROC_NCI
  ,( SELECT FCC_VALOR FROM CIERREN.TCCRXGRAL_CAT_CATALOGO WHERE FCN_ID_CAT_CATALOGO IN ( MNCI.FCN_CVE_PROC_NCI ) ) AS DESC_PROCESO
  ,( SELECT FCC_VALOR FROM CIERREN.TCCRXGRAL_CAT_CATALOGO WHERE FCN_ID_CAT_CATALOGO IN ( MNCI.FCN_CVE_SUBPROC_NCI ) ) AS DESC_SUBPROCESO
FROM PROCESOS.TCSISGRAL_MAP_NCI_ITGY_PROCESO MNCI
WHERE MNCI.FCB_VIGENCIA = 1