-- QUERY PARA ARCHIVO INTEGRITY 
SELECT DISTINCT 
    CASE 
        WHEN MA.FTC_FOLIO_REL IS NOT NULL THEN MA.FTC_FOLIO_REL 
        ELSE MA.FTC_FOLIO 
    END AS FTC_FOLIO,
    MA.FTN_NUM_CTA_INVDUAL,
    #SR_PROCESO# AS FCN_ID_PROCESO,
    PMAT.FTN_ID_SUBPROCESO AS FCN_ID_SUBPROCESO,
    BUC.FTC_NSS,
    BUC.FTC_CURP
FROM CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA MA
INNER JOIN (
    SELECT DISTINCT FTN_NUM_CTA_INVDUAL, FTN_ID_PROCESO, FTN_ID_SUBPROCESO
    FROM CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ
    WHERE (FTC_FOLIO_REL = '#SR_FOLIO#' OR FTC_FOLIO = '#SR_FOLIO#')
) PMAT ON MA.FTN_NUM_CTA_INVDUAL = PMAT.FTN_NUM_CTA_INVDUAL
LEFT JOIN CIERREN_ETL.TLSISGRAL_ETL_BUC BUC
ON BUC.FTN_NUM_CTA_INVDUAL = MA.FTN_NUM_CTA_INVDUAL
WHERE MA.FTB_ESTATUS_MARCA = 1
AND (MA.FTC_FOLIO_REL = '#SR_FOLIO#' OR MA.FTC_FOLIO = '#SR_FOLIO#')

