-- Extrae solo los que no tienen marca en matriz 
WITH PMT AS (
    SELECT 
        PRE.FTN_NUM_CTA_INVDUAL,
        PRE.FTN_ID_PROCESO,
        PRE.FTN_ID_SUBPROCESO,
        PRE.FTN_ID_SIEFORE,
        PRE.FTN_ID_TIPO_SUBCTA,
        PRE.FTN_ID_TIPO_MONTO,
        PRE.FTN_ID_SALDO_OPERA,
        PRE.FTN_ID_TIPO_MOV,
        PRE.FTN_MONTO_ACCIONES,
        PRE.FTN_MONTO_PESOS,
        PRE.FTC_FOLIO
    FROM 
        CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ PRE
    WHERE 
        PRE.FTC_FOLIO = '#sr_folio#'
        OR PRE.FTC_FOLIO_REL = '#sr_folio#'
)
SELECT 
    PMT.FTN_NUM_CTA_INVDUAL,
    PMT.FTN_ID_PROCESO,
    PMT.FTN_ID_SUBPROCESO,
    PMT.FTN_ID_SIEFORE,
    PMT.FTN_ID_TIPO_SUBCTA,
    PMT.FTN_ID_TIPO_MONTO,
    PMT.FTN_ID_SALDO_OPERA,
    PMT.FTN_ID_TIPO_MOV,
    PMT.FTN_MONTO_ACCIONES,
    PMT.FTN_MONTO_PESOS 
FROM 
    CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB
RIGHT JOIN 
    PMT
ON 
    MSUB.FCN_ID_TIPO_SUBCTA = PMT.FTN_ID_TIPO_SUBCTA  
    AND MSUB.FCN_ID_SUBPROCESO = PMT.FTN_ID_SUBPROCESO
    AND MSUB.FCN_ID_TIPO_MOV = #sr_tipo_mov# -- parametro   
LEFT JOIN  
    CIERREN.TTAFOGRAL_MATRIZ_CONVIVENCIA MAT 
ON 
    (MAT.FTN_NUM_CTA_INVDUAL = PMT.FTN_NUM_CTA_INVDUAL 
    AND MAT.FRN_ID_MOV_SUBCTA = 
        CASE PMT.FTN_ID_TIPO_MOV 
            WHEN 180 THEN MSUB.FRN_ID_MOV_SUBCTA 
            ELSE 0 
        END
    AND MAT.FTC_FOLIO = PMT.FTC_FOLIO  -- VERIICA QUE SOLO BUSQUE MARCAS QUE SON DEL MISMO FOLIO
    AND MAT.FTB_ESTATUS_MARCA = '1')
WHERE  MAT.FTN_NUM_CTA_INVDUAL IS NULL
