-- Query para generar delta de sub proceso archivo 64
--  
SELECT 
  MAP.TMN_CVE_NCI AS FCN_ID_SUBPROCESO, 
  MAP.TMN_CVE_ITGY 
FROM CIERREN.TMSISGRAL_MAP_NCI_ITGY MAP
WHERE TMC_USO='SUBPROCESOS'
AND TMC_VIGENCIA='1'


