-- Query extraer informacion de THAFOGRAL_MAR_DES_ITGY y join con MAP_NCI_ITGY_PROCESO
--  
SELECT 
	MD.FTC_FOLIO, 
	MD.FTN_NUM_CTA_INVDUAL,
	MD.FHN_ID_PROCESO_BLOQ ,
	MD.FHN_ID_SUBPROCESO_BLOQ,
	PRO.FCN_CVE_SUBPROC_NCI
FROM PROCESOS.THAFOGRAL_MAR_DES_ITGY  MD
LEFT JOIN 
(
	SELECT FCN_CVE_PROC_ITGY FHN_ID_PROCESO_BLOQ,FCN_CVE_SUBPROC_ITGY FHN_ID_SUBPROCESO_BLOQ, FCN_CVE_SUBPROC_NCI 
	FROM PROCESOS.TCSISGRAL_MAP_NCI_ITGY_PROCESO WHERE FCN_ID_CONFIG IN (
	SELECT MAX(FCN_ID_CONFIG) 
	FROM PROCESOS.TCSISGRAL_MAP_NCI_ITGY_PROCESO
	WHERE FCB_VIGENCIA = '1'
	GROUP BY FCN_CVE_PROC_ITGY,FCN_CVE_SUBPROC_ITGY)
) PRO
ON MD.FHN_ID_PROCESO_BLOQ = PRO.FHN_ID_PROCESO_BLOQ
AND MD.FHN_ID_SUBPROCESO_BLOQ = PRO.FHN_ID_SUBPROCESO_BLOQ
WHERE MD.FHC_ESTATUS_MARCA = '0'
AND MD.FTC_FOLIO = '#SR_FOLIO#'


