-- Query para Update/merge a VAL MATRIZ 
SELECT
    D.FTC_FOLIO,
    D.FTN_NUM_CTA_INVDUAL,
    D.FCN_CVE_SUBPROC_NCI AS FTN_ID_SUBPROC_NO_CONV,
    421 AS FTN_ID_ERROR_VAL,
    0 AS FCN_CONV_INGTY
 FROM #DELTA_TABLA_NAME1# D