-- Query para generar delta de acciones
--  
WITH T1 AS 
(
 SELECT   FTC_NUM_CTA_INVDUAL FTN_NUM_CTA_INVDUAL
         ,FCN_ID_TIPO_SUBCTA FTN_ID_TIPO_SUBCTA
         ,FCN_ID_SIEFORE FTN_ID_SIEFORE
         ,SUM(FTN_DISP_ACCIONES) MONTO_ACCIONES_BAL
  FROM   CIERREN.TTAFOGRAL_BALANCE_MOVS
  WHERE FTC_NUM_CTA_INVDUAL  IN 
  		(SELECT FTN_NUM_CTA_INVDUAL 
        	FROM CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ PRE
          WHERE 
          (PRE.FTC_FOLIO = '#sr_folio#'  OR PRE.FTC_FOLIO_REL = '#sr_folio#')
          )
GROUP BY FTC_NUM_CTA_INVDUAL
		,FCN_ID_TIPO_SUBCTA
		,FCN_ID_SIEFORE 
		HAVING SUM(FTN_DISP_ACCIONES) >= 0
) 
SELECT T1.*
,ROUND(T1.MONTO_ACCIONES_BAL * VAL.FCN_VALOR_ACCION,2) MONTO_PESOS_BAL
,1 B_SALDO 
FROM T1
INNER JOIN CIERREN_ETL.TTSISGRAL_ETL_PRE_MATRIZ PRE 
	ON PRE.FTN_NUM_CTA_INVDUAL=T1.FTN_NUM_CTA_INVDUAL 
	AND PRE.FTN_ID_SIEFORE=T1.FTN_ID_SIEFORE 
	AND PRE.FTN_ID_TIPO_SUBCTA=T1.FTN_ID_TIPO_SUBCTA 
	AND (FTC_FOLIO_REL = '#sr_folio#' OR FTC_FOLIO = '#sr_folio#')
INNER JOIN CIERREN.TCAFOGRAL_VALOR_ACCION VAL ON VAL.FCN_ID_VALOR_ACCION = PRE.FTN_ID_VALOR_ACCION


