-- Query para extraer el detalle de archivo 65 desde tabla delta 
WITH RID AS 
( 
SELECT
    #sr_folio# AS FTC_FOLIO,
    SUBSTRING(D.FTC_LINEA,1,2) AS TIPO_REG,  -- VARIABLE DS
    SUBSTRING(D.FTC_LINEA,63,8) AS FECHAMARCA,   -- VARIABLES DS
    SUBSTRING(D.FTC_LINEA,71,8) AS FECHADESMARCA,  -- VARIABLES DS
    CASE WHEN (
        SUBSTRING(D.FTC_LINEA,1,2) = '02'  AND 
        SUBSTRING(D.FTC_LINEA,50,1) = '0') 
          THEN '1' ELSE '0' END AS SINDESMARCAR, -- VARIABLES DS
    SUBSTRING(D.FTC_LINEA,3,10) AS FTN_NUM_CTA_INVDUAL,
    SUBSTRING(D.FTC_LINEA,13,4) AS FCN_ID_PROCESO,
    SUBSTRING(D.FTC_LINEA,17,4) AS FCN_ID_SUBPROCESO,
    SUBSTRING(D.FTC_LINEA,21,11) AS FTC_NSS,
    SUBSTRING(D.FTC_LINEA,32,18) AS FTC_CURP,
    SUBSTRING(D.FTC_LINEA,50,1) AS FHC_ESTATUS_MARCA,
    SUBSTRING(D.FTC_LINEA,51,4) AS FHN_ID_PROCESO_BLOQ,
    SUBSTRING(D.FTC_LINEA,55,4) AS FHN_ID_SUBPROCESO_BLOQ,
    SUBSTRING(D.FTC_LINEA,59,2) AS FHC_ESTADO_AFIL_INI,
    SUBSTRING(D.FTC_LINEA,61,2) AS FHC_ESTADO_AFIL_FIN,
    FROM_UTC_TIMESTAMP(CURRENT_TIMESTAMP(), 'GMT-6') AS FEH_HOY,
    SUBSTRING(D.FTC_LINEA,79,50) AS FHC_DESC_EDO_AFIL_BLOQ,
    'DATABRICKS' AS FHC_USU_CRE
  FROM #DELTA_TABLA_NAME1# D
)
SELECT 
-- RID.*
  RID.FTC_FOLIO,
  RID.FTN_NUM_CTA_INVDUAL,
  RID.FCN_ID_PROCESO,
  RID.FCN_ID_SUBPROCESO,
  RID.FTC_NSS,
  RID.FTC_CURP,
  RID.FHC_ESTATUS_MARCA,
  RID.FHN_ID_PROCESO_BLOQ,
  RID.FHN_ID_SUBPROCESO_BLOQ,
  RID.FHC_ESTADO_AFIL_INI,
  RID.FHC_ESTADO_AFIL_FIN,
  CASE WHEN RID.SINDESMARCAR = 1 THEN '' ELSE to_timestamp(RID.FECHAMARCA, 'yyyy-MM-dd') END AS  FHD_FEH_MARCA,
 --   CASE WHEN RID.SINDESMARCAR = 1 THEN '' ELSE RID.FECHAMARCA END AS FHD_FEH_MARCA,
 --  CASE WHEN RID.SINDESMARCAR = 1 THEN '' ELSE RID.FECHAMARCA END AS FHD_FEH_MARCA,
  '' AS FHD_FEH_DESMARCA,
  RID.FHC_DESC_EDO_AFIL_BLOQ,
  RID.FHC_USU_CRE,
  RID.FEH_HOY AS FHD_FEH_CRE 
 FROM RID
WHERE 
  RID.TIPO_REG IN ('02')



