-- Elimina registros del folio de VAL_MATRIZ_AUX
DELETE /*+ PARALLEL(8) INDEX(TTAFOGRAL_ETL_MATRIZ_CONVIVENCIA_AUX)*/
FROM CIERREN_DATAUX.TLSISGRAL_ETL_VAL_MATRIZ_CONV_AUX
WHERE
  FTC_FOLIO = '#SR_FOLIO#'