SELECT
FTC_TIPO_TRANSF
, FTD_FEH_PRESEN
, FTD_FEH_MOVI
, FTC_CURP
, FTC_NSS_AFORE
, ifnull(FTC_APELLIDO_PATER_AFORE, ' ') as FTC_APELLIDO_PATER_AFORE
, ifnull(FTC_APELLIDO_MATER_AFORE, ' ') as FTC_APELLIDO_MATER_AFORE
, FTC_NOMBRE_AFORE
, FTC_NOMBRE_IMSS
, FTC_RFC_INFONA
, ifnull(FTN_NUM_CRED_INFONA, 0) as FTN_NUM_CRED_INFONA
, FTC_IDENTI_LOTE_DEV
, FTN_AIVS_VIV_92
, FTN_SALDO_92
, FTN_INTERES_SALDO_92
, FTN_SALDO_97
, FTN_INTERES_SALDO_97
, FTN_AIVS_VIV_97
, FTD_FEH_VAL_VIV
, FTC_IDENTI_ASIG
, FTC_TIPO_DEV
, FTN_NSS_SEPAR_CTA as FTC_NSS_SEPAR_CTA
, FTC_ORIGEN_DEV
, FTN_MONTO_APORTA
, FTN_APLIC_INT_APORTA
, '#sr_folio#' AS FTC_FOLIO
, '#sr_tipo_archivo#' AS FTC_TIPO_ARCH
, CURRENT_DATE() AS FTD_FEH_CRE
, #sr_id_archivo# AS FTN_ID_ARCHIVO
, 'DATABRICKS' AS FTC_USU_CRE
, #SR_SUBPROCESO# AS FCN_ID_SUBPROCESO
, FTN_CONTA_SERV
FROM #DELTA_TABLA_NAME1#