SELECT  
Trim(SUBSTR(FTC_LINEA,23,2 )) FTC_TIPO_TRANSF,
TRIM(SUBSTR(FTC_LINEA,3,10))FTN_CONTA_SERV,
TO_DATE(Trim(SUBSTR(FTC_LINEA,25,8)),'yyyymmdd')FTD_FEH_PRESEN,
TO_DATE(Trim(SUBSTR(FTC_LINEA,33,8 )),'yyyymmdd')FTD_FEH_MOVI,
Trim(SUBSTR(FTC_LINEA,41,18 )) FTC_CURP,
Trim(SUBSTR(FTC_LINEA,59,11 )) FTN_NSS_AFORE,
Trim(SUBSTR(FTC_LINEA,98,40 )) FTC_APELLIDO_PATER_AFORE,
Trim(SUBSTR(FTC_LINEA,138,40 )) FTC_APELLIDO_MATER_AFORE,
Trim(SUBSTR(FTC_LINEA,178,40 )) FTC_NOMBRE_AFORE,
Trim(SUBSTR(FTC_LINEA,600,50 )) FTC_NOMBRE_IMSS,
Trim(SUBSTR(FTC_LINEA,650,10 )) FTN_NUM_CRED_INFONA,
Trim(SUBSTR(FTC_LINEA,240,16 )) FTC_IDENTI_LOTE_DEV,
Trim(SUBSTR(FTC_LINEA,475,15)) /1000000 AS FTN_AVIS_VIV_97,
Trim(SUBSTR(FTC_LINEA,490,15 ))/100 AS FTN_SALDO_97,
Trim(SUBSTR(FTC_LINEA,660,15 ))/100 AS FTN_INTERES_SALDO_97,
ADD_MONTHS(TRUNC(TO_DATE(Trim(SUBSTR(FTC_LINEA,25,8)),'yyyymmdd'),'MONTH'),1) FTD_FEH_VAL_VIV
FROM   CIERREN_ETL.TTSISGRAL_ETL_LEE_ARCHIVO
WHERE  SUBSTR(FTC_LINEA,1,2) = 02 
AND    FTN_ID_ARCHIVO = #sr_id_archivo#