SELECT  
FTC_TIPO_TRANSF
, FTD_FEH_PRESEN
, FTD_FEH_MOVI
, FTC_CURP
, FTN_NSS_AFORE AS FTC_NSS_AFORE
, COALESCE(FTC_APELLIDO_PATER_AFORE, ' ') AS FTC_APELLIDO_PATER_AFORE
, COALESCE(FTC_APELLIDO_MATER_AFORE, ' ') AS FTC_APELLIDO_MATER_AFORE
, TRIM(FTC_NOMBRE_AFORE) AS FTC_NOMBRE_AFORE
, FTC_NOMBRE_IMSS
, FTN_NUM_CRED_INFONA
, FTC_IDENTI_LOTE_DEV
, FTN_AVIS_VIV_97 AS FTN_AIVS_VIV_97
, FTN_SALDO_97
, FTN_INTERES_SALDO_97
, FTD_FEH_VAL_VIV
, '#sr_folio#' AS FTC_FOLIO
, #sr_id_archivo# AS FTN_ID_ARCHIVO
, '#sr_tipo_archivo#' AS FTC_TIPO_ARCH
, to_timestamp(from_utc_timestamp(CURRENT_TIMESTAMP, 'GMT-6')) AS FTD_FEH_CRE
, 'DATABRICKS' AS FTC_USU_CRE
, #SR_SUBPROCESO# AS FCN_ID_SUBPROCESO
, FTN_CONTA_SERV
FROM #DELTA_TABLA_NAME1#