----------------- TRANSFORMER UPD --------------------
 WITH TRANS_INFONA AS (
	SELECT DISTINCT
		FTN_CONTA_SERV,
		FTN_NUM_CTA_AFORE AS FTN_NUM_CTA_INVDUAL,
		FTC_NSS_TRABA_AFORE,
		FTC_FOLIO_BITACORA,
		FTN_ID_SUBP,
		FTD_FEH_ACTUA_ESTATUS,
		FTD_FEH_ACT,
		FCC_USU_ACT
	from  
		PROCESOS.TTCRXGRAL_TRANS_INFONA
	where 
		FTC_FOLIO_BITACORA = '#sr_folio#'
		and  FTC_ESTATUS_REGISTRO = 1
),
DB_200_NCI_INDI
AS
(
SELECT DISTINCT
C.FCN_ID_IND_CTA_INDV,
C.FTN_NUM_CTA_INVDUAL,
C.FFN_ID_CONFIG_INDI,
C.FCC_VALOR_IND,
C.FTC_USU_REG AS FTC_USU_REG,
C.FTD_FEH_REG AS FTD_FEH_REG
FROM PROCESOS.TTCRXGRAL_TRANS_INFONA M
INNER JOIN CIERREN.TTAFOGRAL_IND_CTA_INDV C ON M.FTN_NUM_CTA_AFORE=c.ftn_num_cta_invdual 
AND M.FTC_FOLIO_BITACORA = '#sr_folio#'
AND m.FTC_ESTATUS_REGISTRO='1'
AND C.FFN_ID_CONFIG_INDI  = 14 
AND FTC_VIGENCIA=1
),
VAL_IND
AS
(
SELECT DISTINCT
		C.FCN_ID_IND_CTA_INDV,
		M.FTN_CONTA_SERV,
		M.FTN_NUM_CTA_INVDUAL,
		M.FTC_NSS_TRABA_AFORE,
		M.FTC_FOLIO_BITACORA,
		M.FTN_ID_SUBP,
		M.FTD_FEH_ACTUA_ESTATUS,
		M.FTD_FEH_ACT,
		M.FCC_USU_ACT,
        C.FFN_ID_CONFIG_INDI,
        C.FCC_VALOR_IND,
        C.FTC_USU_REG,
        C.FTD_FEH_REG,
        CASE 
			    WHEN FFN_ID_CONFIG_INDI IS NULL AND FCC_VALOR_IND IS NULL 
			    THEN 0 
			    WHEN FFN_ID_CONFIG_INDI = 14 AND FCC_VALOR_IND = 4 
			    THEN 1 
			    ELSE 2 
			END Validacion
    FROM TRANS_INFONA M
    LEFT JOIN DB_200_NCI_INDI C ON M.FTN_NUM_CTA_INVDUAL = C.FTN_NUM_CTA_INVDUAL
    WHERE M.FTC_FOLIO_BITACORA = '#sr_folio#'
) 
SELECT DISTINCT
	FCN_ID_IND_CTA_INDV,
	FTN_NUM_CTA_INVDUAL,
	FFN_ID_CONFIG_INDI,
	FCC_VALOR_IND,
	0 AS FTC_VIGENCIA,
	FTD_FEH_REG,
	FTC_USU_REG,
	(FROM_TZ(CAST(SYSTIMESTAMP AS TIMESTAMP), 'UTC') AT TIME ZONE 'America/Mexico_City') AS FTD_FEH_ACT,
	'DATABRICKS' AS FCC_USU_ACT,
  	FTC_FOLIO_BITACORA AS FTC_FOLIO
FROM VAL_IND WHERE VALIDACION = 1


