SELECT
  '#sr_folio#' AS FTC_FOLIO,
  Null AS FTN_NUM_CTA_INVDUAL,
  #sr_id_archivo# AS FTN_ID_ARCHIVO,
  FTC_FOLIO_PROCESAR,
  FTC_NSS_IMSS,
  FTC_APELLIDO_PATERNO,
  FTC_APELLIDO_MATERNO,
  FTC_NOMBRE,
  FTC_CURP,
  FTC_TIPO_OPERACION,
  FTC_INSTITUTO_ORIGEN,

  CASE 
    WHEN FTC_INSTITUTO_ORIGEN = '001' -- PARAMETRO DS '#sr_instituto_inf#' 
    THEN IndCreditoInf
    ELSE IdCreditoFov
  END AS FTC_CREDITO,

  CASE 
    WHEN FTC_INSTITUTO_ORIGEN = '001' -- PARAMETRO DS '#sr_instituto_inf#' 
    THEN MontoPesosInf
    ELSE MontoPesosFov
  END AS FTN_MONTO_PESOS,

  CASE 
    WHEN FTC_INSTITUTO_ORIGEN = '001' -- PARAMETRO DS '#sr_instituto_inf#' 
    THEN ValorAivInf
    ELSE ValorAivFov
  END AS FTN_AIVS,

  CASE 
    WHEN FTC_INSTITUTO_ORIGEN = '001' -- PARAMETRO DS '#sr_instituto_inf#' 
    THEN TO_DATE(FechaAivInf, 'yyyyMMdd')
    ELSE TO_DATE(FechaAivFov, 'yyyyMMdd')
  END AS FTD_FEH_VAL_AIVS,

  CASE 
    WHEN FTC_INSTITUTO_ORIGEN = '001' -- PARAMETRO DS '#sr_instituto_inf#' 
    THEN TotalAivInf
    ELSE TotalAivFov
  END AS FTN_TOTAL_AIVS,

  TO_DATE(FTD_FEH_CREDITO, 'yyyyMMdd') AS FTD_FEH_CREDITO,
  TO_DATE(FTD_FEH_VAL_TRANSFERENCIA, 'yyyyMMdd') AS FTD_FEH_VAL_TRANSFERENCIA,

  Null AS FTC_ESTATUS_OPE,
  FTC_DIAGNOSTICO,
  FTC_MOTIVO_REC,

  CASE 
    WHEN FTC_INSTITUTO_ORIGEN = '001' -- PARAMETRO DS '#sr_instituto_inf#' 
    THEN 15 --PARAMETRO EN DS #sr_SUBCTA_15#
    ELSE 18 -- PARAMETRO EN DS #sr_SUBCTA_18#
  END AS FCN_ID_TIPO_SUBCTA,

  81 AS FCN_ID_SIEFORE,
  #SR_SUBPROCESO# AS FTN_SUBPROCESO,

  Null AS FTC_CELULAR,
  Null AS FTC_CORREO_ELEC,
  '#sr_mask_rec_trp#' AS FTC_MASCARA_RECEP,
  CURRENT_DATE() AS FTD_FEH_CRE,
  'DATABRICKS' AS FTC_USU_CRE,
  FTN_NO_LINEA,

  CASE 
    WHEN FTC_INSTITUTO_ORIGEN = '001' -- PARAMETRO DS '#sr_instituto_inf#' 
    THEN MontoPesosInf_92
    ELSE MontoPesosFov_92
  END AS FTN_MONTO_PESOS_92,

  CASE 
    WHEN FTC_INSTITUTO_ORIGEN = '001' -- PARAMETRO DS '#sr_instituto_inf#' 
    THEN ValorAivInf_92
    ELSE ValorAivFov_92
  END AS FTN_AIVS_92,

  CASE 
    WHEN FTC_INSTITUTO_ORIGEN = '001' -- PARAMETRO DS '#sr_instituto_inf#' 
    THEN TO_DATE(FechaAivInf_92, 'yyyyMMdd')
    ELSE TO_DATE(FechaAivFov_92, 'yyyyMMdd')
  END AS FTD_FEH_VAL_AIVS_92,

  CASE 
    WHEN FTC_INSTITUTO_ORIGEN = '001' -- PARAMETRO DS '#sr_instituto_inf#' 
    THEN TotalAivInf_92
    ELSE TotalAivFov_92
  END AS FTN_TOTAL_AIVS_92,

  CASE 
    WHEN FTC_INSTITUTO_ORIGEN = '001' -- PARAMETRO DS '#sr_instituto_inf#' 
    THEN 16 --PARAMETRO DS #sr_SUBCTA_16#
    ELSE 17 --PARAMETRO DS #sr_SUBCTA_17#
  END AS FCN_ID_TIPO_SUBCTA_92
FROM #DELTA_TABLA_NAME1#