SELECT
  A.FTC_FOLIO AS FTC_FOLIO
 ,97 AS FTN_ID_PROCESO
 ,A.FTN_SUBPROCESO AS FTN_ID_SUBPROCESO
 ,A.FTN_NUM_CTA_INVDUAL  AS FTN_NUM_CTA_INVDUAL
 ,81 as FTN_ID_SIEFORE
,M.FCN_ID_TIPO_SUBCTA AS FTN_ID_TIPO_SUBCTA
,'' AS FTC_FOLIO_REL
,NVL(BAL_MOVS.FTN_DISP_ACCIONES,0) as FTN_MONTO_ACCIONES
,COALESCE(BAL_MOVS.FTN_DISP_ACCIONES,0) * COALESCE(V.FCN_VALOR_ACCION,0) AS  FTN_MONTO_PESOS
,COALESCE(V.FCN_ID_VALOR_ACCION,0) AS FTN_ID_VALOR_ACCION 
,185 AS FTN_ID_TIPO_MONTO
,FCN_ID_SALDO_OPERA AS FTN_ID_SALDO_OPERA
,180 AS FTN_ID_TIPO_MOV
,SYSDATE AS FTD_FEH_CRE
,'DATABRICKS' AS FTC_USU_CRE
,NULL AS FTD_FEH_ACT
,NULL AS FTC_USU_ACT

FROM (
SELECT 
TRP.FTN_NUM_CTA_INVDUAL,
TRP.FTC_FOLIO,
FCN_ID_SIEFORE,
TRP.FTN_SUBPROCESO,
25 AS TIPO_MOV,
TRP.FTN_NO_LINEA,
FTC_INSTITUTO_ORIGEN,
C.FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA TRP
INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C
ON TRP.FTC_FOLIO=C.FTC_FOLIO AND TRP.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
WHERE  TRP.FTC_FOLIO = #sr_folio#
AND (C.FTB_ESTATUS_MARCA=0 OR C.FCN_CONV_INGTY=0)
AND C.FCN_ID_TIPO_SUBCTA=15
AND FTC_INSTITUTO_ORIGEN='001'

UNION ALL 

SELECT 
TRP.FTN_NUM_CTA_INVDUAL,
TRP.FTC_FOLIO,
FCN_ID_SIEFORE,
TRP.FTN_SUBPROCESO,
25 AS TIPO_MOV,
TRP.FTN_NO_LINEA,
FTC_INSTITUTO_ORIGEN,
C.FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA TRP
INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C
ON TRP.FTC_FOLIO=C.FTC_FOLIO AND TRP.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
WHERE  TRP.FTC_FOLIO = #sr_folio#
AND (C.FTB_ESTATUS_MARCA=0 OR C.FCN_CONV_INGTY=0)
AND C.FCN_ID_TIPO_SUBCTA=16
AND FTC_INSTITUTO_ORIGEN='001'

UNION ALL 

SELECT 
TRP.FTN_NUM_CTA_INVDUAL,
TRP.FTC_FOLIO,
FCN_ID_SIEFORE,
TRP.FTN_SUBPROCESO,
25 AS TIPO_MOV,
TRP.FTN_NO_LINEA,
FTC_INSTITUTO_ORIGEN,
C.FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA TRP
INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C
ON TRP.FTC_FOLIO=C.FTC_FOLIO AND TRP.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
WHERE  TRP.FTC_FOLIO = #sr_folio#
AND (C.FTB_ESTATUS_MARCA=0 OR C.FCN_CONV_INGTY=0)
AND C.FCN_ID_TIPO_SUBCTA=18
AND FTC_INSTITUTO_ORIGEN='002'


UNION ALL

SELECT 
TRP.FTN_NUM_CTA_INVDUAL,
TRP.FTC_FOLIO,
FCN_ID_SIEFORE,
TRP.FTN_SUBPROCESO,
25 AS TIPO_MOV,
TRP.FTN_NO_LINEA,
FTC_INSTITUTO_ORIGEN,
C.FCN_ID_TIPO_SUBCTA
FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA TRP
INNER JOIN CIERREN_ETL.TLSISGRAL_ETL_VAL_MATRIZ_CONV C
ON TRP.FTC_FOLIO=C.FTC_FOLIO AND TRP.FTN_NUM_CTA_INVDUAL=C.FTN_NUM_CTA_INVDUAL
WHERE  TRP.FTC_FOLIO = #sr_folio#
AND (C.FTB_ESTATUS_MARCA=0 OR C.FCN_CONV_INGTY=0)
AND C.FCN_ID_TIPO_SUBCTA=17
AND FTC_INSTITUTO_ORIGEN='002'


) A
LEFT OUTER JOIN (
 select  
DISTINCT 
 FTC_FOLIO_BITACORA,
FTN_NUM_CTA_INVDUAL
,FTN_CONTA_SERV
,FCN_ESTATUS
from PROCESOS.TTSISGRAL_SUF_SALDOS
where FTC_FOLIO_BITACORA=#sr_folio#
AND FCN_ESTATUS=1
)X
ON A.FTC_FOLIO=X.FTC_FOLIO_BITACORA
AND A.FTN_NUM_CTA_INVDUAL=X.FTN_NUM_CTA_INVDUAL
AND A.FTN_NO_LINEA=X.FTN_CONTA_SERV 

INNER JOIN(
SELECT  CMOV.FRN_ID_MOV_SUBCTA
       ,MSUB.FCN_ID_SUBPROCESO
       ,MSUB.FCN_ID_TIPO_SUBCTA
       ,MSUB.FCN_ID_TIPO_MOV
       ,CMOV.FFN_ID_CONCEPTO_MOV
       ,CMOV.FCN_ID_TIPO_MONTO
       ,CAT.FCN_ID_TIPO_CAT AS TIPO_MOV
       ,FCN_ID_REGIMEN
FROM       CIERREN.TFAFOGRAL_CONFIG_CONCEP_MOV CMOV
INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB ON CMOV.FRN_ID_MOV_SUBCTA = MSUB.FRN_ID_MOV_SUBCTA
INNER JOIN CIERREN.TCCRXGRAL_CAT_CATALOGO CAT ON MSUB.FCN_ID_TIPO_MOV = CAT.FCN_ID_CAT_CATALOGO
INNER JOIN CIERREN.TCCRXGRAL_TIPO_CAT TCAT ON CAT.FCN_ID_TIPO_CAT = TCAT.FCN_ID_TIPO_CAT
INNER JOIN cierren.tccrxgral_tipo_subcta SUB ON  SUB.FCN_ID_TIPO_SUBCTA=MSUB.FCN_ID_TIPO_SUBCTA
WHERE  CMOV.FFB_VIGENCIA = 1
AND    MSUB.FRB_VIGENCIA = 1
AND    MSUB.FCN_ID_SUBPROCESO =#sr_subproceso#
AND    TCAT.FCN_ID_TIPO_CAT = 25
AND    TCAT.FCB_VIGENCIA = 1
AND    CAT.FCB_VIGENCIA = 1
AND    MSUB.FCN_ID_TIPO_SUBCTA IN (15,18,16,17)
)M
ON A.FTN_SUBPROCESO=M.FCN_ID_SUBPROCESO
AND A.TIPO_MOV=M.TIPO_MOV
AND A.FCN_ID_TIPO_SUBCTA=M.FCN_ID_TIPO_SUBCTA
left outer join (

SELECT   A.FTC_NUM_CTA_INVDUAL 
         ,A.FCN_ID_TIPO_SUBCTA
         ,A.FCN_ID_SIEFORE
         ,B.FCN_ID_REGIMEN
         ,SUM(NVL(A.FTN_DISP_ACCIONES,0)) AS FTN_DISP_ACCIONES
  FROM   CIERREN.TTAFOGRAL_BALANCE_MOVS A
  INNER JOIN CIERREN.TCCRXGRAL_TIPO_SUBCTA B ON A.FCN_ID_TIPO_SUBCTA= B.FCN_ID_TIPO_SUBCTA
  WHERE A.FTC_NUM_CTA_INVDUAL  IN  
  (
  SELECT FTN_NUM_CTA_INVDUAL 
   FROM PROCESOS.TTAFOTRAS_TRANS_REC_PORTA 
   WHERE FTC_FOLIO=#sr_folio#
   )
  AND A.FCN_ID_SIEFORE in (81)
  AND A.FCN_ID_TIPO_SUBCTA IN (15,18,16,17)
  GROUP BY A.FTC_NUM_CTA_INVDUAL, A.FCN_ID_TIPO_SUBCTA, A.FCN_ID_SIEFORE ,B.FCN_ID_REGIMEN

)BAL_MOVS
ON A.FTN_NUM_CTA_INVDUAL = BAL_MOVS.FTC_NUM_CTA_INVDUAL
AND A.FCN_ID_TIPO_SUBCTA=BAL_MOVS.FCN_ID_TIPO_SUBCTA
INNER JOIN (
SELECT  
 FCN_ID_VALOR_ACCION
,FCD_FEH_ACCION
,FCN_VALOR_ACCION
,FCN_ID_REGIMEN
,FCN_ID_SIEFORE
FROM CIERREN.TCAFOGRAL_VALOR_ACCION V
WHERE FCN_ID_SIEFORE = 81
and FCN_ID_REGIMEN IN (138,139)
--AND -- V.FCD_FEH_ACCION = to_date('2025/07/14', 'YYYY/MM/DD')
AND  TO_TIMESTAMP(TRUNC(V.FCD_FEH_ACCION),'DD-MM-YY HH24:MI:SS') = TO_TIMESTAMP(ADD_MONTHS(TRUNC(SYSDATE,'MONTH'),1),'DD-MM-YY HH24:MI:SS')
)V
ON BAL_MOVS.FCN_ID_REGIMEN=V.FCN_ID_REGIMEN
AND BAL_MOVS.FCN_ID_SIEFORE=V.FCN_ID_SIEFORE
LEFT OUTER JOIN 
( SELECT FCN_ID_SALDO_OPERA, FCN_ID_SUBPROCESO
FROM CIERREN.TFAFOGRAL_CONFIG_SUBPROCESO CSUB
WHERE CSUB.FCN_ID_PROCESO = '97'
AND FCN_ID_SUBPROCESO = #sr_subproceso#) CS
ON  A.FTN_SUBPROCESO =CS.FCN_ID_SUBPROCESO
WHERE A.FTC_FOLIO =#sr_folio#
AND A.FTN_SUBPROCESO =#sr_subproceso#
AND X.FCN_ESTATUS=1

