SELECT M.FCN_ID_SIEFORE AS FCN_CVE_SIEFORE, 
M.FTN_CTA_AFORE AS FTN_NUM_CTA_INVDUAL, 
D.FTC_DIG_VERI, 
M.FFN_COD_MOV_ITG AS FFN_COD_MOV_ITGY, 
D.FTC_NSS_AFORE AS FNN_NSS_ISSSTE_SUA, 
D.FTD_FEH_CRE AS FND_FEH_CRE_SUA, 
D.FTN_ID_ARCHIVO, 
M.FTD_FEH_LIQUIDACION, 
M.FCN_VALOR_ACCION, 
M.FND_FECTRA_SUA, 
'153' AS FNN_SECLOT_SUA, 
M.FNN_ID_REFERENCIA, 
M.FTC_FOLIO, 
M.FND_FECHA_PAGO_SUA, 
M.FNC_PERIODO_PAGO_PATRON, 
M.FND_FECHA_VALOR_IMSS_ACV_VIV AS FNC_REG_PATRN_IMSS_SUA, 
M.FTF_MONPES1, 
M.FTF_MONCUO1, 
M.FTF_MONPES2, 
M.FTF_MONCUO2, 
M.FTF_MONPES3, 
M.FTF_MONCUO3, 
M.FTF_MONPES4, 
M.FTF_MONCUO4, 
M.FTF_MONPES5, 
M.FTF_MONCUO5, 
M.FTF_MONPES6, 
M.FTF_MONCUO6, 
M.FTF_MONPES7, 
M.FTF_MONCUO7, 
M.FTF_MONPES8, 
M.FTF_MONCUO8, 
M.FTF_MONPES9, 
M.FTF_MONCUO9, 
M.FND_FECHA_1, 
M.FND_FECHA_2, 
M.FND_FECHA_VALOR_RCV, 
M.FND_FECHA_VALOR_IMSS_ACV_VIV, 
M.FND_FECVGUB, 
CASE WHEN #sr_subproceso# IN (347,348,349,351,354,364,365,368,3832) OR (#sr_subproceso# = 3286 AND D.FTC_INSTITUTO_ORIGEN = '001') 
THEN '01' 
ELSE '02' END AS FNC_CVESERV, 
M.FNC_VARMAX 
FROM #DELTA_TABLA_NAME1# M 
INNER JOIN #DELTA_TABLA_NAME2# D 
ON M.FTC_FOLIO = D.FTC_FOLIO 
AND M.FTN_CTA_AFORE = D.FTN_CTA_AFORE 
AND M.FNN_ID_REFERENCIA = D.FNN_ID_REFERENCIA 
AND D.FTC_CLAVE_ENT_ORIG = #sr_clave_ent_orig#;