SELECT --DISTINCT
    DPSJL.FTC_FOLIO,
    lpad(DPSJL.FTN_NUM_CTA_INVDUAL,10,'0')FTN_CTA_AFORE,
    lpad(nvl(DPSJL.FTC_NSS,'0'),11,'0') AS FTC_NSS_AFORE,
    SUBSTR(DPSJL.FTC_RFC_TRABA,12,1) AS FTC_DIG_VERI,
    to_char(DPSJL.FTD_FEH_CRE, 'YYYYMMDD')FTD_FEH_CRE,
    lpad(nvl(DPSJL.FTN_ID_ARCHIVO,'0'),21,'0') FTN_ID_ARCHIVO,
    DPSJL.FCN_ID_SUBPROCESO,
    DPSJL.FTN_PERIODO_PAGO,
    lpad(nvl(DPSJL.FTN_CONSE_REG_LOTE,'0'),8,'0') FNN_ID_REFERENCIA,
    dpsjl.FTC_CLAVE_ENT_ORIG,
    dpsjl.FTN_FOLIO_SUA,
    null FTC_INSTITUTO_ORIGEN
    FROM PROCESOS.TTCRXGRAL_DEV_PAG_SJL DPSJL
    WHERE DPSJL.FTC_FOLIO = '#sr_folio#'
    --and dpsjl.FTC_CLAVE_ENT_ORIG='001'
    AND DPSJL.FCN_ID_SUBPROCESO=#sr_subproceso#
    AND DPSJL.FTC_ESTATUS=1
    AND DPSJL.FTC_TIPO_ARCH='01'
