WITH BD_100_TL_MOV_VIV AS (
    SELECT
      MV.FTC_FOLIO,
      LPAD(MV.FTN_NUM_CTA_INVDUAL, 10, '0') AS FTN_CTA_AFORE,
      MV.FTD_ID_ESTATUS_MOV,
      TO_CHAR(MV.FTD_FEH_LIQUIDACION, 'YYYYMMDD') AS FTD_FEH_LIQUIDACION,
      LPAD(NVL(MV.FNN_ID_REFERENCIA, '0'), 8, '0') AS FNN_ID_REFERENCIA,
      MV.FCN_ID_VALOR_ACCION,
      LPAD(MV.FCN_ID_TIPO_SUBCTA, 4, '0') AS FCN_ID_TIPO_SUBCTA,
      MV.FCN_ID_TIPO_MOV,
      MV.FCN_ID_CONCEPTO_MOV,
      '00000000' AS FND_FECHA_1,
      '00000000' AS FND_FECHA_2,
      '00000000' AS FND_FECVGUB,
      '00000000' AS FND_FECHA_VALOR_RCV,
      '00000000' AS FND_FECHA_VALOR_IMSS_ACV_VIV,
      '00000' AS FNC_VARMAX,
      SIE.FCN_ID_SIEFORE,
      CMI.FFN_COD_MOV_ITG,
      CASE WHEN CMI.FFN_POSICION_ITGY = 1 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES1,
      CASE WHEN CMI.FFN_POSICION_ITGY = 1 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO1,
      CASE WHEN CMI.FFN_POSICION_ITGY = 2 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES2,
      CASE WHEN CMI.FFN_POSICION_ITGY = 2 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO2,
      CASE WHEN CMI.FFN_POSICION_ITGY = 3 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES3,
      CASE WHEN CMI.FFN_POSICION_ITGY = 3 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO3,
      CASE WHEN CMI.FFN_POSICION_ITGY = 4 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES4,
      CASE WHEN CMI.FFN_POSICION_ITGY = 4 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO4,
      CASE WHEN CMI.FFN_POSICION_ITGY = 5 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES5,
      CASE WHEN CMI.FFN_POSICION_ITGY = 5 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO5,
      CASE WHEN CMI.FFN_POSICION_ITGY = 6 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES6,
      CASE WHEN CMI.FFN_POSICION_ITGY = 6 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO6,
      CASE WHEN CMI.FFN_POSICION_ITGY = 7 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES7,
      CASE WHEN CMI.FFN_POSICION_ITGY = 7 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO7,
      CASE WHEN CMI.FFN_POSICION_ITGY = 8 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES8,
      CASE WHEN CMI.FFN_POSICION_ITGY = 8 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO8,
      CASE WHEN CMI.FFN_POSICION_ITGY = 9 THEN FTF_MONTO_PESOS ELSE 0 END AS FTF_MONPES9,
      CASE WHEN CMI.FFN_POSICION_ITGY = 9 THEN FTF_MONTO_ACCIONES ELSE 0 END AS FTF_MONCUO9,
      TO_CHAR(MV.FTD_FEH_LIQUIDACION, 'YYYYMMDD') AS FND_FECHA_PAGO_SUA,
      TO_CHAR(MV.FTD_FEH_LIQUIDACION, 'YYYYMM') AS FNC_PERIODO_PAGO_PATRON,
      '00000000' AS FND_FECTRA_SUA
    FROM
      CIERREN.TTAFOGRAL_MOV_VIV MV
      INNER JOIN (
        SELECT
          LPAD(MPI.TMN_CVE_ITGY, 2, '0') AS FCN_ID_SIEFORE,
          MPI.TMN_CVE_NCI
        FROM
          CIERREN.TMSISGRAL_MAP_NCI_ITGY MPI
        WHERE
          MPI.TMC_VIGENCIA = 1
          AND MPI.TMC_USO = 'CTINDI'
      ) SIE ON MV.FCN_ID_SIEFORE = SIE.TMN_CVE_NCI
      INNER JOIN (
        SELECT
          TSUB.FCN_ID_TIPO_SUBCTA,
          LPAD(NVL(SUBSTR(MIT.FFN_COD_MOV_ITGY, 1, 3), '0'), 3, '0') AS FFN_COD_MOV_ITG,
          MIT.FFN_POSICION_ITGY,
          FFN_ID_CONCEPTO_MOV
        FROM
          CIERREN.TCCRXGRAL_TIPO_SUBCTA TSUB
          INNER JOIN CIERREN.TRAFOGRAL_MOV_SUBCTA MSUB ON TSUB.FCN_ID_TIPO_SUBCTA = MSUB.FCN_ID_TIPO_SUBCTA
            AND MSUB.FCN_ID_SUBPROCESO = #sr_subproceso#
          INNER JOIN CIERREN.TFCRXGRAL_CONFIG_MOV_ITGY MIT ON MSUB.FRN_ID_MOV_SUBCTA = MIT.FRN_ID_MOV_SUBCTA
      ) CMI ON MV.FCN_ID_TIPO_SUBCTA = CMI.FCN_ID_TIPO_SUBCTA
      AND MV.FCN_ID_CONCEPTO_MOV = CMI.FFN_ID_CONCEPTO_MOV
    WHERE
      MV.FTC_FOLIO = #sr_folio#
  ),
  BD_700_VALOR_ACCION AS (
    SELECT
      LPAD(TRUNC(FCN_VALOR_ACCION, 7) * 10000000, 12, '0') AS FCN_VALOR_ACCION,
      FCN_ID_VALOR_ACCION,
      TO_CHAR(FCD_FEH_ACCION, 'YYYYMMDD') AS FCD_FEH_ACCION,
      TO_CHAR(FCD_FEH_ACCION, 'YYYYMMDD') AS FND_FECHA_PAGO_SUA,
      TO_CHAR(FCD_FEH_ACCION, 'YYYYMM') AS FNC_PERIODO_PAGO_PATRON
    FROM
      CIERREN.TCAFOGRAL_VALOR_ACCION
    WHERE
      FCN_ID_REGIMEN IN ('138', '139')
  )
    SELECT
      M.FTC_FOLIO,
      M.FTN_CTA_AFORE,
      M.FTD_ID_ESTATUS_MOV,
      M.FTD_FEH_LIQUIDACION,
      M.FNN_ID_REFERENCIA,
      M.FCN_ID_VALOR_ACCION,
      M.FCN_ID_TIPO_SUBCTA,
      M.FCN_ID_TIPO_MOV,
      M.FCN_ID_CONCEPTO_MOV,
      M.FND_FECHA_1,
      M.FND_FECHA_2,
      M.FND_FECVGUB,
      M.FND_FECHA_VALOR_RCV,
      M.FND_FECHA_VALOR_IMSS_ACV_VIV,
      M.FNC_VARMAX,
      M.FCN_ID_SIEFORE,
      M.FFN_COD_MOV_ITG,
      M.FTF_MONPES1,
      M.FTF_MONCUO1,
      M.FTF_MONPES2,
      M.FTF_MONCUO2,
      M.FTF_MONPES3,
      M.FTF_MONCUO3,
      M.FTF_MONPES4,
      M.FTF_MONCUO4,
      M.FTF_MONPES5,
      M.FTF_MONCUO5,
      M.FTF_MONPES6,
      M.FTF_MONCUO6,
      M.FTF_MONPES7,
      M.FTF_MONCUO7,
      M.FTF_MONPES8,
      M.FTF_MONCUO8,
      M.FTF_MONPES9,
      M.FTF_MONCUO9,
      B.FND_FECHA_PAGO_SUA,
      B.FNC_PERIODO_PAGO_PATRON,
      M.FND_FECTRA_SUA,
      B.FCN_VALOR_ACCION
    FROM
      BD_100_TL_MOV_VIV M
      JOIN BD_700_VALOR_ACCION B ON M.FCN_ID_VALOR_ACCION = B.FCN_ID_VALOR_ACCION